### ISSUE TITLE
Diff items in GridLayout

### ISSUE THREAD

**Issue by NetylkinOV** [mikepenz/FastAdapter#1004]
Hello mikepenz. Tell me is it possible to do it? Add 2 different items to RecyclerView with GridLayoutManager 2 columns. Check image. Thank you :)

![example](https://user-images.githubusercontent.com/34498183/123184279-8e863680-d4bd-11eb-9d4d-ae2b2a062aa1.png)

**Comment by mikepenz** [comment]
@NetylkinOV yes this is possible. 

See this example: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/IconGridActivity.kt

**Comment by NetylkinOV** [comment]
Hi mikepenz, thank you so much for your help. The short answer is:

val gridLayoutManager = GridLayoutManager (this, 3)
         gridLayoutManager.spanSizeLookup = object: GridLayoutManager.SpanSizeLookup () {
             override fun getSpanSize (position: Int): Int {
                 return when (fastItemAdapter.getItemViewType (position)) {
                     R.id.fastadapter_expandable_item_id -> 3
                     R.id.fastadapter_icon_item_id -> 1
                     else -> -1
                 }
             }
         }

As I don't need an implementation with Expandable.
I have been using your library for several years now, it's amazing how powerful it is.

I'm still waiting for the multiplatform kotlin version :)))

**Comment by NetylkinOV** [comment]
I wish you health and good luck :)

**Comment by mikepenz** [comment]
Happy I could help :)
