### ISSUE TITLE
how to use multiple items for different models with Model Adapter

### ISSUE THREAD

**Issue by dsantix** [mikepenz/FastAdapter#1016]
## Checklist

- [V ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [V ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app) | (principally in MultiTypeModelItemActivity.kt)
- [ V] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ V] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ V] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
In the sample both have a base class `IconModel` but one is of type `RightIconModel`, as you can see in the type check. 

Do you want your headers to be sticky or stay as part of the list? (Sticky headers are not part of this library, as this is usually handled by decorators or such)  -> there's one sample activity in the sample app using an external library

for your order. you can surely achieve this either by having different model types (and in any case the top parent type could by `Any` if nothing else common applies) and then map to the target items you expect. 

In case you do not want to split `Model` and `Item` you can also achieve this.
