### ISSUE TITLE
Feature request: Default item if FastAdapter is empty

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/FastAdapter#102]
Default item should have icon, title, text,...
Maybe I will make a PR.
@mikepenz Please let it open.

**Comment by mikepenz** [comment]
@Rainer-Lang you could just provide an item with `height=MACHT_PARENT` which devs can use. 

Should be in the extension lib

**Comment by Rainer-Lang** [comment]
@mikepenz Thanks. Now I know where to put it. I will close this issue and prepare a pr.

**Comment by mikepenz** [comment]
Thanks ;)

**Comment by or-dvir** [comment]
@Rainer-Lang i am also interested in an empty view.
have you implemented this yet? if so how would i use it?

**Comment by mikepenz** [comment]
@or-dvir an empty view is really easy. I did something similar for the ABoutLibraries with an ProgressItem
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/ui/item/LoaderItem.java

**Comment by or-dvir** [comment]
@mikepenz forgive me but i dont understand how this link implements an empty view...

in the meantime i have tried using "registerAdapterDataObserver()" and overriding "onChanged()" like many people suggest on different forums. however, this method is not invoked :(
any idea why?

here is my implementation:

```
@Override
	public void onResume()
	{
		super.onResume();
		mAdapter.registerAdapterDataObserver(mDataObserver);
	}

	@Override
	public void onPause()
	{
		super.onPause();
		mAdapter.unregisterAdapterDataObserver(mDataObserver);
	}
```

and in onCreateView (i am using a fragment) i do this:
```
mDataObserver = new AdapterDataObserver()
		{
			@Override
			public void onChanged()
			{
				Log.i("aaaaa", "something changed!");
				super.onChanged();

				toggleEmptyView();
			}
		};
```

**Comment by anton-khansa** [comment]
i have some problem too with empty view, is there any sample code that you can share how to make it with fast adapter
