### ISSUE TITLE
Overload resolution ambiguity. All these functions match.

### ISSUE THREAD

**Issue by Airsaid** [mikepenz/FastAdapter#1030]
Hi, Mike. thanks a lot for this great library: amazing :-)

I am referring to the `MultiTypeModelItemActivity` example using several different item to show.

However, there is no inheritance between my multiple items, so when I use `Any` directly, I get the following problem:
```
Overload resolution ambiguity. All these functions match.
```

The example code:
```kotlin
val itemAdapter = ModelAdapter { element: Any ->
  if (element is Avatar) {
    AvatarItem(element)
  } else if (element is User) {
    UserItem(element)
  }
  throw IllegalArgumentException()
}

val fastAdapter = FastAdapter.with(listOf(itemAdapter))
val models = ArrayList<Any>()
for (i in 0 until Random.nextInt(0, 100)) {
  if (i % 3 == 0) {
    models.add(DataProvider.providerUser(i))
  } else {
    models.add(DataProvider.providerAvatar(i))
  }
}

itemAdapter.add(models) // failed: Overload resolution ambiguity. All these functions match.
```

## Details

- [ ] Used library version: Latest
- [ ] Used support library version: Latest
- [ ] Used gradle build tools version: 7.0.2
- [ ] Used tooling / Android Studio version: Android Studio Bumblebee | 2021.1.1 Patch 2
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Look a bit further in the error message. One part of the issue actually originates from the problem that your `ModelAdapter` does not have a proper generic type specification: `ModelAdapter<Any, Nothing>` 
<img width="496" alt="Screenshot 2022-03-25 at 09 26 58" src="https://user-images.githubusercontent.com/1476232/160083183-64ceddbc-dfb8-4053-90be-f9db3b4d7af2.png">

The generic type should resolve to: `<Model, Item : GenericItem>` with `GenericItem` being a typealias for ` IItem<out RecyclerView.ViewHolder>`
<img width="496" alt="Screenshot 2022-03-25 at 09 28 23" src="https://user-images.githubusercontent.com/1476232/160083387-cd21c1e9-3e5e-40dd-8035-cd2c6e40ab3f.png">

What you want to do is to ensure the generic type for the adapter is properly defined. 

The other issues results from the classes not having a common base interface or similar. In detail this also results from generics, but you can work around this easily by introducing a common interface. Somewhat like:

```
    { 
         val itemAdapter = ModelAdapter<X, GenericItem> { element: Any ->
            if (element is Avatar) {
                AvatarItem(element)
            } else if (element is User) {
                UserItem(element)
            }
            throw IllegalArgumentException()
        }

        val fastAdapter = FastAdapter.with(listOf(itemAdapter))
        val models = ArrayList<X>()
        for (i in 0 until nextInt(0, 100)) {
            if (i % 3 == 0) {
                models.add(User())
            } else {
                models.add(Avatar())
            }
        }

        itemAdapter.add(models)
    }

    interface X

    class Avatar(): X

    class User(): X

    class AvatarItem(val avatar: Avatar): AbstractItem<RecyclerView.ViewHolder>() {
        override val type: Int
            get() = TODO("Not yet implemented")
        override val layoutRes: Int
            get() = TODO("Not yet implemented")

        override fun getViewHolder(v: View): RecyclerView.ViewHolder {
            TODO("Not yet implemented")
        }
    }
```

**Comment by Airsaid** [comment]
I know the cause of the problem, there is duplication of method signatures because of generic erasure.

I wanted to express that when there is no association between two data classes, it is not possible to use entries of multiple types.

**Comment by mikepenz** [comment]
I am not sure if this can be resolved due to how generics work. If you have proposals I'd love to hear about them. 

In any case as outlined above, you can always introduce an interface adding a common interface between your classes.

**Comment by mikepenz** [comment]
I am not sure if this can be resolved due to how generics work. If you have proposals I'd love to hear about them. 

In any case as outlined above, you can always introduce an interface adding a common interface between your classes.
