### ISSUE TITLE
Proguard failure for versions 1.3.0+

### ISSUE THREAD

**Issue by mattiasbe** [mikepenz/FastAdapter#104]
Up until version 1.2.9 (inclusive) there were no proguard failures. With 1.3.0 and 1.4.0 there is.
I haven't investigated it much other than that and maybe due to unresolved classes in the extensions.
Noticed this in the CI server.

Error:

> FAILURE: Build failed with an exception.
>     * What went wrong:
>     Execution failed for task ':mobile:transformClassesAndResourcesWithProguardForTimerflowRelease'.
>     > java.io.IOException: Please correct the above warnings first.

Above warnings is:

> Warning: there were 47 unresolved references to classes or interfaces.
> You may need to add missing library jars or update their versions.

And furthermore there are lots of these now earlier on:

> Warning: com.mikepenz.fastadapter_extensions.items.SingleLineItem: can't find referenced class com.mikepenz.materialize.holder.StringHolder
>     Warning: com.mikepenz.fastadapter_extensions.items.SingleLineItem: can't find referenced class com.mikepenz.materialize.holder.StringHolder
etc

Added this to proguard rules:
`-dontwarn com.mikepenz.**`

And it works again for 1.4.0 of FastAdapter.

**Comment by mikepenz** [comment]
@mattiasbe not really sure if this is a good idea. 

I have updated the README to show that the extensions now also require transitive. They now depend on the `Materialize` library
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/build.gradle#L37

If you add the transitive the warning should go away

**Comment by mattiasbe** [comment]
Much better solution, thanks.
