### ISSUE TITLE
Selection in checkbox example

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/FastAdapter#105]
is possible to show the selection of the row in the checkbox example ? when the user clicks the row.
Thanks.

**Comment by seba123neo** [comment]
i mean show the ripple like in a normal row of a recyclerview

**Comment by mikepenz** [comment]
@seba123neo if you item allows click on itself, and has a selectable background it will show. This is not the case in the sample, as it showcases some different usecase

**Comment by seba123neo** [comment]
ok, thanks, you can close the issue.
