### ISSUE TITLE
Weird behavior on scroll with expandable

### ISSUE THREAD

**Issue by androidacy-user** [mikepenz/FastAdapter#1051]
## About this issue

When an expandable item's subitem is expanded when an user scrolls away, the sub item height randomly increases and as such there's an empty space in the subitem

## Details
- [x] Used library version: 5.7.0
- [ ] Used support library version
- [x] Used gradle build tools version: 8.1.2
- [x] Used tooling / Android Studio version: AGP 8.1.2
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

## Screenshots

- Before scrolling:

<img width="380" alt="image" src="https://github.com/mikepenz/FastAdapter/assets/45006100/8440b765-3729-4fdd-ab77-f6e5850e4fda">

- After

<img width="382" alt="image" src="https://github.com/mikepenz/FastAdapter/assets/45006100/ac64c50d-f00a-4467-abcd-d99f23c84ad1">

(item actually continues below bottom nav, not shown there)

**Comment by androidacy-user** [comment]
Upon further investigation, setting height to match_parent on the sub item layout causes this issue. But, it only becomes an issue *after* scrolling, which is very strange and unexpected behavior.

**Comment by mikepenz** [comment]
This is not related to this library, whereas this library only focuses on the `adapter` and binding of views and not on general `RecyclerView` behavior. 

Please refer to `RecyclerView` documentation to learn more about how it handles views and renders them as part of the RV.
