### ISSUE TITLE
It is a bad design to put model and view in a single class AbstractItem.

### ISSUE THREAD

**Issue by Alchemist0823** [mikepenz/FastAdapter#106]
For a model, developers probably have multiple viewHolder to display it.

**Comment by mikepenz** [comment]
@Alchemist0823 for this case there is the `GenericItemAdapter`

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/GenericItemActivity.java

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeGenericItemActivity.java
