### ISSUE TITLE
onLoadMore Question

### ISSUE THREAD

**Issue by R4md4c** [mikepenz/FastAdapter#107]
Hello,

I have a question.

I'm currently using v1.3.0 of your library and using your EndlessRecyclerOnScrollListener.

The case is that sometimes there is an error while loading a page, and onLoadMore stops getting called, after that error.

To describe more, Imagine that you keep scrolling and a network error happens, and  when you scroll up then down again, onLoadMore doesn't get called and now the list is not updated any more after the error happens. 

Is there a solution for that?

**Comment by Rainer-Lang** [comment]
@R4md4c Please try the newest version of FastAdapter and Extensions.
https://github.com/mikepenz/FastAdapter/releases/tag/v1.4.0

**Comment by dsbeckham** [comment]
From #108:

> For example, if I add 100 items to the adapter, scroll down a bit, clear the adapter, then add 10 more to the beginning, `onLoadMore` appears to stop getting called. I have to remove the listener from my RecyclerView, instantiate a new `EndlessRecyclerOnScrollListener` object, and then attach it to my RecyclerView again.

> I haven't really investigated why this is happening, but I guess it might have something to do with `mVisibleThreshold` not getting updated when items are removed ([line 89](https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnScrollListener.java#L89)).

I don't know if my issue is actually related to this one, but perhaps so. I am using v1.4.0, by the way.

**Comment by R4md4c** [comment]
@Rainer-Lang 
I don't think upgrading to v1.4.0 would solve the issue, according to [this](https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnScrollListener.java#L95) ```mLoading``` will be always true when the error happens, and since there is no change in ```mTotalItemCount```, then onLoadMore will never be callled.

**Comment by FabianTerhorst** [comment]
@R4md4c mTotalItemCount is getting updated on every scroll. When there are not enough items to scroll then it could happen that the count isn´t updated anymore. Im not sure if there is any listener for the RecyclerView or the adapter when a item got removed or added. The AdapterDataObserver isn´t the right listener for that.

**Comment by FabianTerhorst** [comment]
@dsbeckham the visible threshhold is only calculated to let you and the listener know how many items are one page. When you don´t have a dynamic api thats accept different page counts you can define a specific number inside the constructor.

**Comment by xxmbaobao** [comment]
update your version

**Comment by dsbeckham** [comment]
@FabianTerhorst: Yeah, that was just a guess about `mVisibleThreshold`.

[What about this?](https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnScrollListener.java#L96) I think the problem might just be that `mPreviousTotal` isn't always being reset. When items are removed from the adapter, and the user can no longer scroll down to the place where `mTotalItemCount` was set previously, then `mTotalItemCount` will never exceed `mPreviousTotal`, and `onLoadMore` won't be called again.

Maybe you should add another check somewhere to see if `mTotalItemCount`  is _less_ than `mPreviousTotal` at any point, and then reset `mPreviousTotal` in that case? I don't think you need any additional listeners to accomplish this. Just compare your stored values.

**Comment by mikepenz** [comment]
@FabianTerhorst has added two new methods to reset the `EndlessRecyclerOnScrollListener` which can be found in v1.4.1.1 of the `library-extensions` 

https://github.com/mikepenz/FastAdapter/commit/f6c9446c019f45516d99b80e94c019ad8df6aab7

**Comment by dsbeckham** [comment]
Sorry if this is a silly question (perhaps I'm just missing something), but how can we access these methods? `EndlessRecyclerOnScrollListener` is an abstract class, so we can't instantiate it.

**Comment by FabianTerhorst** [comment]
@dsbeckham 
```
mList.addOnScrollListener(new EndlessRecyclerOnScrollListener() {
            @Override
            public void onLoadMore(int currentPage) {
                resetPageCount();
       
            }
        });
```

**Comment by dsbeckham** [comment]
Ah, okay,  the second one works for me. I wasn't implementing `onLoadMore`. Thanks.
