### ISSUE TITLE
onLoadMore stops getting called when items are removed from the adapter

### ISSUE THREAD

**Issue by dsbeckham** [mikepenz/FastAdapter#108]
For example, if I add 100 items to the adapter, scroll down a bit, clear the adapter, then add 10 more to the beginning, `onLoadMore` appears to stop getting called. I have to remove the listener from my RecyclerView, instantiate a new `EndlessRecyclerOnScrollListener` object, and then attach it to my RecyclerView again.

I haven't really investigated why this is happening, but I guess it might have something to do with `mVisibleThreshold` not getting updated when items are removed ([line 89](https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnScrollListener.java#L89)).

**Comment by mikepenz** [comment]
please add your text to this issue: 
https://github.com/mikepenz/FastAdapter/issues/107
