### ISSUE TITLE
Click listener for expandable example

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/FastAdapter#109]
I need to detect the click in the expandable example and show information from the parent item, with event i need to use ?

**Comment by seba123neo** [comment]
i need to show a toast with the title from the child, and the title from the parent node clicked

**Comment by mikepenz** [comment]
@seba123neo in the sample the child does not know about the parent. You could extend the child items to get a reference to their parent (just set the parent when you add the child items to the container item) so you will always have a reference to the parent and get the information when the `onClick` happens

**Comment by seba123neo** [comment]
yes, that is what i did, thanks.
