### ISSUE TITLE
Incorrect click event forwarding when wraping an adapter

### ISSUE THREAD

**Issue by robertdolca** [mikepenz/FastAdapter#111]
In the `EndlessScrollSample` the footer adapter wraps the item adapter. When the ussers click on the footer item the click event is icorrectly forwarded to the item adapter which causes the app to crash because it expects an instance of `SampleItem` instead of `ProgressItem`.

**Comment by mikepenz** [comment]
@robertdolca thanks. fixed in v1.4.1.1 of the Sample app
