### ISSUE TITLE
Custom Color / Icon for each item when implementing the Swipe-Feature

### ISSUE THREAD

**Issue by jlelse** [mikepenz/FastAdapter#112]
Is this somehow possible? Didn't find it in the sample.

**Comment by mikepenz** [comment]
@jlelse I am sure it is possible. You just have to define the color in your `onBind` method. Shouldn't be a `FastAdapter` limitation as the `FastAdapter` doesn't know about how to visualize an item in general

**Comment by jlelse** [comment]
But [here](https://github.com/mikepenz/FastAdapter/blob/master/app/src/main/java/com/mikepenz/fastadapter/app/SwipeListActivity.java) the hole swipe thing isn't defined in the item itself. It is in the activity. How do I define it in the item?

**Comment by mikepenz** [comment]
@jlelse it wouldn't work with the `SimpleSwipeDragCallback` but you can have your own `SwipeDragCallback` which allows you to do this.

**Comment by jlelse** [comment]
In which package is this `SwipeDragCallback`?

**Comment by mikepenz** [comment]
The `SimpleDragCallback` is here:
https://github.com/mikepenz/FastAdapter/blob/master/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/drag/SimpleDragCallback.java

which extends from the `ItemTouchHelper.SimpleCallback` which comes with the following package:
```java
import android.support.v7.widget.helper.ItemTouchHelper;
```

**Comment by jlelse** [comment]
I still don't understand how I can add SimpleSwipeCallback to AbstractItem xD

**Comment by mikepenz** [comment]
@jlelse you can't get it into the `AbstractItem` you will have to implement your logic here:
https://github.com/mikepenz/FastAdapter/blob/master/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/swipe/SimpleSwipeCallback.java#L121

There's the `itemView` which has `getTag()` and the tag is the current `item` of this `itemView` if you `item` contains the color you can use this information to decide which color or drawable to use

**Comment by jlelse** [comment]
It will be hard, but doable I think. Thank you!

**Comment by mikepenz** [comment]
@jlelse as mentioned the `Simple*` classes are just an addition to the `FastAdapter` ia the extensions lib to simplify default behaviors. more complex custom behaviors will need to be implemented by the dev himself

**Comment by Rainer-Lang** [comment]
@jlelse If you figured it out, maybe you can contribute to this project and provide an extended example? :+1:

**Comment by jlelse** [comment]
@Rainer-Lang I gave it up. I'll find another way of implementing what I need.
