### ISSUE TITLE
zebra row background

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#114]
how can achieve to zebra background ( for example odd items has gray background and even white background) for item rows ?

thanks

**Comment by Rainer-Lang** [comment]
Set background in bindView.

**Comment by mikepenz** [comment]
@DJafari as @Rainer-Lang already said. Your item will have to set it's background in the `bindView()` method. Depending on it's position

**Comment by DJafari** [comment]
thanks

but how can get position in GenericAbstractItem ?

**Comment by Rainer-Lang** [comment]
Maybe with this: ```viewHolder.getAdapterPosition()```

**Comment by DJafari** [comment]
thanks @Rainer-Lang
