### ISSUE TITLE
(EndlessRecyclerOnScrollListener) onLoadMore called twice if added item to footer adapter.

### ISSUE THREAD

**Issue by markic22** [mikepenz/FastAdapter#115]
Hi, 

If someone adds item to footer adapter in OnScrollListener [your example](https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/EndlessScrollListActivity.java), the onLoadMore in [EndlessRecyclerOnScrollListener](https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnScrollListener.java) will be called twice, because mTotalItemCount will be bigger for number of items in footerAdapter. The problem is reproducible in your own example also (EndlessScroll Sample).

Thanks for awesome library, keep up the good work.

**Comment by FabianTerhorst** [comment]
Hi @markic22,

i have updated the EndlessRecyclerOnScrollListener.  https://github.com/mikepenz/FastAdapter/commit/d64c664c4eb5c8ac95f45378c2e1ff98a0c4ae5b

**Comment by mikepenz** [comment]
Fixed in the latest version of the extensions lib:
```gradle
compile 'com.mikepenz:fastadapter-extensions:1.4.2.1@aar'
```

Thanks @FabianTerhorst

**Comment by markic22** [comment]
Thanks for quick response guys. There seems to be issue with 
`compile 'com.mikepenz:fastadapter-extensions:1.4.2.1@aar'`
```
Error:(118, 13) Failed to resolve: com.mikepenz:fastadapter-extensions:1.4.2.1
```

**Comment by mikepenz** [comment]
@markic22 perhaps mavenCentral has not yet synced. have you jCenter also in your gradle?

**Comment by markic22** [comment]
@mikepenz, it searches there also, but doesn't find it.
`Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_localhostDebugCompile'.
   > Could not find com.mikepenz:fastadapter-extensions:1.4.2.1.
     Searched in the following locations:
   
         https://jcenter.bintray.com/com/mikepenz/fastadapter-extensions/1.4.2.1/fastadapter-extensions-1.4.2.1.pom
         https://jcenter.bintray.com/com/mikepenz/fastadapter-extensions/1.4.2.1/fastadapter-extensions-1.4.2.1.aar
         https://jitpack.io/com/mikepenz/fastadapter-extensions/1.4.2.1/fastadapter-extensions-1.4.2.1.pom
         https://jitpack.io/com/mikepenz/fastadapter-extensions/1.4.2.1/fastadapter-extensions-1.4.2.1.aar
         https://maven.fabric.io/public/com/mikepenz/fastadapter-extensions/1.4.2.1/fastadapter-extensions-1.4.2.1.pom
         https://maven.fabric.io/public/com/mikepenz/fastadapter-extensions/1.4.2.1/fastadapter-extensions-1.4.2.1.aar

**Comment by mikepenz** [comment]
ok it's at least already on maven central:
https://oss.sonatype.org/content/repositories/releases/com/mikepenz/fastadapter-extensions/1.4.2.1/
