### ISSUE TITLE
(Sticky)-Header View

### ISSUE THREAD

**Issue by mikepenz** [mikepenz/FastAdapter#12]
Provide a sample / or implement a feature which allows headers, and sticky headers

**Comment by mikepenz** [comment]
At the moment i've done this with the awesome lib by @timehop https://github.com/timehop/sticky-headers-recyclerview
The sample application contains a sample activity which showcases how to use this lib in combination with the `FastAdapter` by providing a `StickyHeaderAdapter`, and wrap it into the adapter chain. 

* The sample activity:
 * https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/StickyHeaderSampleActivity.java
* The adapter:
*  https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/adapter/StickyHeaderAdapter.java

**Comment by ankitbatra11** [comment]
https://github.com/timehop/sticky-headers-recyclerview is no longer maintained. Are you planning to replace the example with https://github.com/emilsjolander/StickyListHeaders?

**Comment by mikepenz** [comment]
The sticky header is just a sample of compatiblity. 

You can open a PR to provide a sample for that implementation ;)

**Comment by FabianTerhorst** [comment]
You could use the https://github.com/google/iosched/blob/master/third_party/sticky-headers/StickyHeaders/src/main/java/io/doist/recyclerviewext/sticky_headers/StickyHeadersLinearLayoutManager.java its an slim version of the recyclerview extensions from doist.

**Comment by AHarazim** [comment]
Unfortunately, the site that @FabianTerhorst provided is no longer available. 😞 
Do you have maybe another example?
