### ISSUE TITLE
Scrolling activity not showing toolbar properly

### ISSUE THREAD

**Issue by readbeard** [mikepenz/FastAdapter#120]
Hi,
i tried to use your library with a scrolling activity, and i have some problems with the toolbar. As you can see from the screen, only a half of the toolbar is displayed and also, when collapsed, only half of the title is shown. Do you have some idea?
Thanks in advance. 
![half_toolbar_1](https://cloud.githubusercontent.com/assets/6012118/14880510/b0133f9e-0d1e-11e6-8728-28c238b341e3.png)
![half_toolbar_2](https://cloud.githubusercontent.com/assets/6012118/14880511/b014aa00-0d1e-11e6-8644-bf00084b567e.png)

**Comment by mikepenz** [comment]
@readbeard that is not related to this library. Collapsing Toolbar was used in the `MaterialDrawer` it might help you

**Comment by readbeard** [comment]
I just used the same code you wrote in the README file. If i remove that snippet, the layout shows correctly. I think it is related to the library, and also the collapsing toolbar used it MaterialDrawer was not useful, because i have the same code of that one.
Do you have some other idea?
Thanks

**Comment by mikepenz** [comment]
@readbeard it is definitely not related to the `FastAdapter` as it is only an adapter and completely unrelated to `CollapsingToolbar` behavior or anything else UI specific. 

In the README there's just adapter and item logic. Nothing activity specific.

**Comment by readbeard** [comment]
Hi,
i found the problem. It was this call ```MaterializeBuilder().withActivity(this).build();``` that is from your other library ```MaterialDrawer```. I don't know if opening this problem can be useful for that library but sorry for opening the issue here!

**Comment by mikepenz** [comment]
@readbeard the question is if you even need the `Materialize` library in your project?

**Comment by readbeard** [comment]
yep! sorry again for wrong repo issue.
