### ISSUE TITLE
expand cardview for ExpandableItem

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#124]
how can i expand a item inside a parent cardview ?
can you give me a sample please ?
thanks

**Comment by Rainer-Lang** [comment]
Could you please give more information?

**Comment by DJafari** [comment]
i want to have a ExpandableItem with cardView, when this item expanded, more items add inside this cardview

( sorry for my bad english )

**Comment by mikepenz** [comment]
@DJafari That's nothing the `FastAdapter` can handle for you. This is just about the way your cardview is configured. Please see here: 
http://stackoverflow.com/questions/31273203/what-is-the-best-practice-to-group-items-into-cardview

When you expand you just have to change the margin of the parent `CardView` so it will "group" with the sub items.

**Comment by DJafari** [comment]
@mikepenz no , my main question is : how can i add sub items inside in cardview of expandable item ?

my subitems not having cardview, just simple, but i want subitems adds inside the cardview, not outer

**Comment by FabianTerhorst** [comment]
@DJafari you can add another recyclerview inside your item, but subitems are below the parent items.

**Comment by mikepenz** [comment]
@DJafari please look again at the link I posted above. It will group together the `CardView` so you can get the same effect and make it look as it is "inside" the `CardView` 

Otherwhise you will have to handle this on your own. You will have to listen for the click event and then call `notifyItemChanged()` and add the new views to your item inside the `bindView()` method

**Comment by DJafari** [comment]
@mikepenz @FabianTerhorst  ok thanks for your helps
