### ISSUE TITLE
Is there a reason why GenericFastItemAdapter cannot filter? 

### ISSUE THREAD

**Issue by hsdmiranda** [mikepenz/FastAdapter#126]
I am trying to use the GenericFastAdapter on my project, but I noticed that it does not contain the method withFilterPredicate like the FastItemAdapter. Is there a specific reason for that? Can I wrap it somehow to get the same result?

**Comment by mikepenz** [comment]
@hsdmiranda the method might not be added to the `GenericFastItemAdapter` but you should be able to call it directly on the  `GenericItemAdapter`. 

`GenericFastItemAdapter.getGenericItemAdapter().withFilterPredicate()` should do the job

**Comment by hsdmiranda** [comment]
Thanks for the quick reply as always @mikepenz. It worked

**Comment by mikepenz** [comment]
No problem :D Sometimes I wonder myself how many questions I can answer without even looking at my code :D
