### ISSUE TITLE
OnCreateViewHolderListener and FooterAdapter cast exception

### ISSUE THREAD

**Issue by alashow** [mikepenz/FastAdapter#128]
Cast exception throws at `onPreCreateViewHolder` when I add item to footerAdapter:
```ruby
java.lang.ClassCastException: tm.asmanoky.yenilhyzmat.model.BasketTotal cannot be cast to tm.asmanoky.yenilhyzmat.model.Product
```
```java
itemAdapter.withOnCreateViewHolderListener(new FastAdapter.OnCreateViewHolderListener() {
            @Override
            public RecyclerView.ViewHolder onPreCreateViewHolder(ViewGroup parent, int viewType) {
                return itemAdapter.getTypeInstance(viewType).getViewHolder(parent);
            }
...
 });
```

Yes, both objects have different/own type (id), layout, and generic definition define the correct type.

It works perfectly if I don't use `withOnCreateViewHolderListener`, footer item is visible. But I need to use ClickListenerHelper with it.

How can I fix it?
Thanks.

**UPDATE:**
Normal click listener also throwing class cast exception:
```java
itemAdapter.withOnClickListener(new FastAdapter.OnClickListener<Product>() {
                @Override
                public boolean onClick(View v, IAdapter<Product> adapter, Product item, int position) {
                     ...
                    return true;
                }
            });
```
```ruby
java.lang.ClassCastException: tm.asmanoky.yenilhyzmat.model.BasketTotal cannot be cast to tm.asmanoky.yenilhyzmat.model.Product
                                                                                   at tm.asmanoky.yenilhyzmat.ui.fragment.ProductListFragment$$Lambda$1.onClick(Unknown Source)
                                                                                   at com.mikepenz.fastadapter.FastAdapter$1.onClick(FastAdapter.java:350)
                                                                                   at android.view.View.performClick(View.java:5204)
```

**Comment by FabianTerhorst** [comment]
@alashow im also using `withOnCreateViewHolderListener` and don´t get the exception.```
@Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return ((AbstractItem) getTypeInstance(viewType)).getViewHolder(LayoutInflater.from(context).inflate(getLayoutRes((getTypeInstance(viewType)).getLayoutRes()), parent, false));
    }

    private static int getLayoutRes(@LayoutRes int layoutRes) {
        if (layoutRes == R.layout.item)
            return R.layout.item..;
        else if (layoutRes == R.layout.item...)
            return R.layout.item....;
        else if (layoutRes == R.layout.item....)
            return R.layout.item...;
        return layoutRes;
    }
```

**Comment by alashow** [comment]
@FabianTerhorst is there better solution? Because your version looks weird.

**Comment by FabianTerhorst** [comment]
@alashow have you tried to use `getTypeInstance` instead of `itemAdapter.getTypeInstance`?

**Comment by alashow** [comment]
@FabianTerhorst there is no `getTypeInstance` by itself. It's `FastAdapter`'s method, isn't it? and `itemAdapter` is instance of `FastAdapter`.

**Comment by FabianTerhorst** [comment]
@alashow i have extended the fastadapter to override the onCreateViewHolder method.

**Comment by alashow** [comment]
Got that work:
```java
itemAdapter.withOnCreateViewHolderListener(new FastAdapter.OnCreateViewHolderListener() {
            @Override
            public RecyclerView.ViewHolder onPreCreateViewHolder(ViewGroup parent, int viewType) {
                switch (viewType) {
                    case R.id.product:
                        return itemAdapter.getTypeInstance(viewType).getViewHolder(parent);
                    default:
                        return new BasketTotal().getViewHolder(parent);
                }
            }

            @Override
            public RecyclerView.ViewHolder onPostCreateViewHolder(RecyclerView.ViewHolder viewHolder) {
                if (viewHolder instanceof Product.ViewHolder) {
                    clickListenerHelper.listen(viewHolder, ((Product.ViewHolder) viewHolder).photo, (v, position, item)->{
                       ...
                    });
                    ...
                }
                return viewHolder;
            }
        });
```

But @mikepenz, is there normal solution?

**Comment by mikepenz** [comment]
@alashow the correct solution is that you have a non typed `FastAdapter` (or you go against the interface `IItem`) As the `FastAdapter` is there to manage all items he gets, Also those from sub adapters like the `FooterAdapter`, it is important that he is always on the base class for all your items. or he is not typed at all. or you use `IItem` as type. 

As of your exceptions it seems you have typed your `FastAdapter` to `Product` which is for sure not castable to your `FooterItem` `BasketTotal`

**Comment by alashow** [comment]
@mikepenz I assume you mean `FastItemAdapter` by saying `FastAdapter`. 
So then, I' changed my `FastItemAdapter` type to `AbstractItem` (also tried with `IItem`, and `?`). I casted items to my types (`Product`, `BasketTotal`) safely. 
Then, adding items to my `FastItemAdapter` are not working, `add()` methods are not resolving. My arrayList was `Product`, if I change it to `AbstractItem` my code becomes becomes garbage. Every time I access my list, I'll need to cast it to my type. Also I won't be able to create new arrays (ex. `List<AbstractItem> mylist = ArrayList<Product>();`, `List<AbstractItem> mylist = result.getProducts();`).

I just wanted to add footer, with different type..

Am I doing it wrong or this is the only way? 

Thanks.

**Comment by mikepenz** [comment]
@alashow `FastItemAdapter` == `ItemAdapter.wrap(FastAdapter)` 

That's correct, if you have an untyped `FastItemAdapter` all the methods of it will be with type `IItem` you will have to cast most things and get the correct type. 

What you can do is that you really split up `FastItemAdapter` to `ItemAdapter` and `FastAdapter` you will then have your `FastAdapter` with the general `IItem` interface, or your common base class, and your `ItemAdapter` typed to `Product`.

It is not possible to have a `FastAdapter` with a specific type, but another adapter (your `FooterAdapter`) which wraps the `FastAdapter` with a different type. That's how Java works, and that's how type safety is designed. 

You have to decide what fits more your usecaes. work with the interface, but loose the advantage of the correctly typed listeners etc. or you type the adapter but then you have to make sure you type it with a base class common to all other typed adapters which wrap the `FastAdapter`

**Comment by alashow** [comment]
> What you can do is that you really split up FastItemAdapter to ItemAdapter and FastAdapter you will then have your FastAdapter with the general IItem interface, or your common base class, and your ItemAdapter typed to Product.

I didn't know that there is `ItemAdapter`. I did like you said, split up them, wrapped fastAdapter, added some castings for listeners.

Now everything is works okay & clean code.

Thank you very much!😃
