### ISSUE TITLE
getView

### ISSUE THREAD

**Issue by artests87** [mikepenz/FastAdapter#129]
Hi, Mike!
I have one little trouble.
How can I get View for each Item in the FastAdapter, if I want to change the image_item, for example?
Or maybe you can give us the getImage method in AbstractItem to change it?
Thanks!

**Comment by mikepenz** [comment]
@artests87 you can't. An item must not have a view at all times.

If you want to change an item you will have to change it's data and notify the adapter about the changed item. It is nothing the `FastAdapter` will have to handle. Just add the udpate method for the data to your item. And make sure the `bindView` method will correctly handle the view and the data. If you call `notifyAdapterItemChanged()` `bindView` will get called and the view is then updated

You may should watch some talks regarding `RecyclerView` and how views are handled inside a RV

**Comment by artests87** [comment]
Okay, but how can I apply some filters for my Item's inner imageView during
creating? I can add image (withImage), but I can't apply some change for
it...
10 мая 2016 г. 5:54 PM пользователь "Mike Penz" <notifications@github.com>
написал:

**Comment by mikepenz** [comment]
@artests87 if you want to apply a filter on images, you will have to do this in the `bindView` method. If you want to change it at a later time, your item needs to have a variable which you can set, which will define which filter to set, if you change this variable on this item, and you want the change to be visible, you will have to call `notifyAdapterItemChanged()`

**Comment by artests87** [comment]
I want to change it a later time, but I don't know when and where can I do
a variable(( Because, if I do the variable in the blindView method, I have
received a NullPointerExcept (And it's perfectly problem for me now)

2016-05-10 23:34 GMT+03:00 Mike Penz <notifications@github.com>:
