### ISSUE TITLE
Collapsing opened items once another is clicked

### ISSUE THREAD

**Issue by bachhuberdesign** [mikepenz/FastAdapter#130]
Hey Mike. Just a quick question -- what is the best way to only have one parent item showing sub-items at a time? I want my implementation to close any opened items whenever another item is clicked.

Right now I am using your sample code for the Expandable adapter with the click listener in the adapter instead of the Activity/Fragment. I am porting from ExpandableListView which had the convenience method collapseGroup(position) for collapsing the previously opened parent item and am wondering if there is a simple way to get a similar functionality with FastAdapter/RecyclerView.

Thanks for the help!

**Comment by mikepenz** [comment]
Hi @bachhuberdesign 

Take a look at this method `withOnlyOneExpandedItem`:
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L251

It will always collapse all other expanded items and will just keep one opened.

**Comment by bachhuberdesign** [comment]
Perfect, thank you! I didn't notice that method when I was trying to solve my problem.

**Comment by suleymanccelik** [comment]
Hi Mike, withOnlyOneExpandedItem method works well. But for my ui requirements, when a item is expanded or collapsed, background color of items change. Is there any callback method to give me information about which item is closed or opened?

**Comment by mikepenz** [comment]
@suleymanccelik no there isn't but the `collapse` should trigger a `notifyItemChanged` on the parent which should call the `bindView` and so you should be able to just change the color there

**Comment by suleymanccelik** [comment]
Thanks @mikepenz
