### ISSUE TITLE
ImageItem Selectable?

### ISSUE THREAD

**Issue by artests87** [mikepenz/FastAdapter#132]
Hi, Mike!
When I did ImageItem selectable,
```java
//set the background for the item
UIUtils.setBackground(viewHolder.view, FastAdapterUIUtils.getSelectableBackground(ctx, Color.LTGRAY, true));
```
 I received the mistake:
```
java.lang.ClassCastException: android.graphics.drawable.StateListDrawable cannot be cast to android.support.v7.widget.RoundRectDrawableWithShadow
```

What did I do wrong?
Thanks.

**Comment by mikepenz** [comment]
@artests87 I do not know :D which support lib version do you use?

**Comment by artests87** [comment]
compile('com.mikepenz:fastadapter:1.5.0.b2-SNAPSHOT@aar') {
        transitive = true
    }

//extension:
    compile 'com.mikepenz:fastadapter-extensions:1.5.0.b2-SNAPSHOT@aar'

**Comment by mikepenz** [comment]
support libraries ;)

**Comment by artests87** [comment]
compileSdkVersion 23
    buildToolsVersion '23.0.2'

Is it?)

**Comment by mikepenz** [comment]
no support libraries. app-compat, and recyclerview and so on?

**Comment by mikepenz** [comment]
Do you use a different layout for the `ImageItem`?

**Comment by artests87** [comment]
compile 'com.android.support:appcompat-v7:23.2.0'
    compile 'com.android.support:recyclerview-v7:+'
    compile 'com.android.support:cardview-v7:23.0.0'

I was so close)

**Comment by mikepenz** [comment]
@artests87 maybe those conflict. 

You always should use the same version for all dependencies from the `com.android.support` package. So try to change all your support library dependencies to `v23.3.0` (the `FastAdapter` also uses v23.3.0) 

If it still crashes, do you use the `ImageItem` exactly as it is in the sample app? or your custom layout?

**Comment by artests87** [comment]
A version doesn't my problem.
But you are absolutely right about cardview.
I'm going to solve the problem.
Thanks a lot!

**Comment by mikepenz** [comment]
@artests87 oh you changed it to a `CardView` then you should check out this article: 
http://stackoverflow.com/questions/26399670/android-graphics-drawable-colordrawable-cannot-be-cast-to-android-support-v7-wid
