### ISSUE TITLE
setForeground adk 23-

### ISSUE THREAD

**Issue by artests87** [mikepenz/FastAdapter#133]
One more problem.
I have to select the image.
SetBackground won't help me in this way.
But I can't use setForeground, becouse I have to use min adk 15-16.
How can I use the command: viewHolder.view.setForeground(FastAdapterUIUtils.getSelectablePressedBackground(ctx, FastAdapterUIUtils.adjustAlpha(color, 100), 50, true));
in my case?
Maybe I able to use only Alpha in any way?)
Thanks)

**Comment by artests87** [comment]
((CardView)viewHolder.view).setForeground(FastAdapterUIUtils.getSelectablePressedBackground(ctx, FastAdapterUIUtils.adjustAlpha(Color.GRAY, 100),
                    50, true)); That's work)

**Comment by mikepenz** [comment]
Great that you solved it. But in general those questions are not library specific anymore. The logic how your view should look like is up to the dev who uses the `FastAdapter` that's completely independent from the lib
