### ISSUE TITLE
Issue with saveInstance in ImageItem

### ISSUE THREAD

**Issue by artests87** [mikepenz/FastAdapter#134]
Hi, Mike!
I found a new issue!
In your demo app.
Main form.
I selected few items and when I rotate screen - them states didn't save - I lose my select items.

**Comment by FabianTerhorst** [comment]
Have you builded the demo App from source? When I select 2 Items and rotate my device there stay selected.

**Comment by artests87** [comment]
In the main activity (imageItem)?

**Comment by mikepenz** [comment]
Use the latest app version from here:
https://github.com/mikepenz/FastAdapter/releases/tag/v1.5.1

It is no issue, in the previous versions I just had not stored the `savedInstanceState`so it is simple why it didn't stay. 

With this commit this was changed:
https://github.com/mikepenz/FastAdapter/commit/13bbe76165063bfd4bdad6fc44124bbb740ceb49

**Comment by artests87** [comment]
But I use the SNAPSHOT version? Will I have the feature that in
SNAPSHOT(group select, deselect and more) in new version?
14 мая 2016 г. 0:18 пользователь "Mike Penz" <notifications@github.com>
написал:
>
> Use the latest app version from here:
> https://github.com/mikepenz/FastAdapter/releases/tag/v1.5.1
>
> It is no issue, in the previous versions I just had not stored the
savedInstanceStateso it is simple why it didn't stay.

**Comment by mikepenz** [comment]
@artests87 the latest stable version has the features from your SNAPSHOT merged, so you can now use the upstream version (just enable the alternative state managment for your usecase) 

as mentioned, it was just not enabled in the sample, I have changed it and it will now retain the state

**Comment by artests87** [comment]
I have a new problem(( I have two FastAdapter. And if I try to save both - the program save only the second FastAdapter.
