### ISSUE TITLE
Simpler examples

### ISSUE THREAD

**Issue by ncapdevi** [mikepenz/FastAdapter#135]
Is there anyway to provide a sticky header example that wouldn't require including the entire Timehop Library which is no longer maintained?

**Comment by Rainer-Lang** [comment]
@ncapdevi Did you already search for another - still maintained - lib? btw how do you know if the lib isn't still maintained?

**Comment by mikepenz** [comment]
@ncapdevi the `FastAdapter` is just an adapter coming with all the items logic. You should be abel to use any `ItemDecorator` or any other library which provides `StickyHeader`s. I'm sorry that **timehope** stopped supporting their lib. It's pretty stable, with some small glitches when animating. If this is an issue on your side you might find better or other alternatives. 

Please report back if you find an alternative.

**Comment by Rainer-Lang** [comment]
@ncapdevi Maybe this lib helps: https://github.com/ShamylZakariya/StickyHeaders
When you tried it, please give a short feedback. Thanks.

**Comment by ncapdevi** [comment]
I don't think that that library will work, as it doesn't have an interface to implement, and requires you to extend its own adapter. This means that you can't have it be a subclass of AbstractAdapter AND of their SectionAdapter.

**Comment by hsdmiranda** [comment]
@ncapdevi did you give a shot for that library? I also need a better sticky header
