### ISSUE TITLE
Wrong behavior onClick with GenericItem and swipeable

### ISSUE THREAD

**Issue by dexion** [mikepenz/FastAdapter#136]
Initial:
- `GenericSomeItem` as wrapper for adapter and `SomeItem` as model
- FastAdapter with GenericItemAdapter with drag'n'drop and onClick listeners
- 2 items: `yellow` at 0 position and `red` at 1st position

Script:
- drag `yellow` from 0 to 1st position
- click on `red` (0 position). In onClick(View v, IAdapter<GenericShiftTypeItem> adapter, GenericShiftTypeItem item, int position) function we get: position: 0, item: `yellow`. It should be 'red'!

**Comment by mikepenz** [comment]
@dexion can you provide a sample showcasing exactly this issie?

**Comment by dexion** [comment]
@mikepenz, I can't make video with explanation, so I made [TestApplication](https://github.com/dexion/TestApplication).
Please, look at function [ListShiftTypeActivity.java#L224](https://github.com/dexion/TestApplication/blob/master/app/src/main/java/com/dexion/testapplication/ShiftType/ListShiftTypeActivity.java#L224) with code comments. At [ListShiftTypeActivity.java#L213](https://github.com/dexion/TestApplication/blob/master/app/src/main/java/com/dexion/testapplication/ShiftType/ListShiftTypeActivity.java#L213) we notified adapter about movement, but adapter still return wrong item at right position.

If I use `position` for retrieving my Item I can't use list filtering. If I use `item.getModel()` I can't use drag'n'drop.

**Comment by mikepenz** [comment]
@dexion to fix your issue just replace 
```java
fastAdapter.notifyAdapterItemMoved(oldPosition, newPosition);
```
in line 208 of your `ListShiftTypeActivity` with 
```
itemAdapter.moveModel(oldPosition, newPosition);
```

The following happens. By default this would be done by the `SimpleSwipeDragCallback` but as you want to handle the event on your own, the default behavior does not kick in and you have to call this method. You also don't have to notify then as this is done within the `moveModel` method.
