### ISSUE TITLE
Support for multiple layout in a single adapter

### ISSUE THREAD

**Issue by Schinizer** [mikepenz/FastAdapter#138]
Hello there,

Is there a way to implement multiple layouts in a single adapter? An example use case is instant messaging, where the are usually 2 layouts for messages (1 for user and 1 for recipient).

If there is, is there sample code to show how to implement this? (Can't find a sample with this)

Thank you very much.

**Comment by mikepenz** [comment]
@Schinizer yes this is possible. You can have as many types as you want. So there are different possible solutions to your question. 

In general it is possible to define the `Type` to your `FastAdapter` /  `ItemAdapter` /  `FastItemAdapter`, if you define a `Type` all added items have to fit this `Type`. If you have different types of items you can either use those adapters without a given type, or you use a parent class of your items as type (if they have something in common). 

There are also some examples which showcase this. (Not exactly the same, but even more complex situations) 

For example the `IconGridActivity` which has the `ExpandableItem` and the `IconItem`s which are added if you click the `ExpandableItem` (so in fact the `FastItemAdapter` in this sample will hold both types if expanded, in this sample the `FastItemAdapter` is not typed). In this case the events will fire with an `IItem` which you can cast to your specific type (make sure to check instanceof :D) 
See the sample here:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/IconGridActivity.java

You can also look at the `MultiTypeGenericItemActivity` sample where we have a model class, and multiple item classes:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeGenericItemActivity.java

I think this should already give you an idea how this works. 

As there is no sample for the typed MultiItem situation here a description:
MessageItem
LeftMessageItem extends MessageItem
RightMessageItem extends MessageItem
So your `FastAdapter` / `ItemAdapter` will have the type `MessageItem` which means all events will fire with a `MessageItem` and you can then decide on / cast to the specific item type.
