### ISSUE TITLE
Question about expandable items sample

### ISSUE THREAD

**Issue by pfives** [mikepenz/FastAdapter#139]
Hey thanks for the awesome effort you've put into this lib, looks very solid.

I'm just trying it out for the first time and am following the ExpandableSampleActivity. When an item expands, the `RecyclerView` expands and everything looks great. 

The issue I'm running into is when I collapse that item, the bottom items get quickly clipped by the bounds of the `RecyclerView`. My `RecyclerView` is `wrap_content` so I'm guessing when the item is tapped, the view bounds are recalculated for the post-animation so the bottom items are clipped before the animation finishes. Is there a simple solution to fix this or am I missing something? Thanks again!

Edit: additional question: is there any way to get notified when items expand or collapse? If we set an `OnClickListener` and modify the parent view when it expands (like flipping the arrow) the arrow will stay flipped if we are calling `withOnlyOneExpanedItem(true)` since that will auto collapse the view without the `OnClickListener` being involved (sorry for the wordiness)

**Comment by mikepenz** [comment]
Hi. Thank you. 

For the first issue, I have no idea as this is something handled by the `RecyclerView` and `LayoutManager` and not the adapter. So you may have to ask this somewhere like `StackOverflow` (expanding / collapsing is basically adding and removing items, so you might can ask it in a more general way)

Your second question. You are right, right now there is no solution that you can also get the `OnClick` event from the `ExpandableItem` as this is internally managed of the item. I made this decision as in general people will just want the single functionality from this item. I really should add the possibility to add an additional `OnItemClickListener` on it. 
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/ExpandableItem.java#L89
As an additional note. The general listener won't fire as we consume the `click` event here:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/ExpandableItem.java#L98

**Comment by mikepenz** [comment]
Will be in the next version
