### ISSUE TITLE
Issue with an inner item selected

### ISSUE THREAD

**Issue by artests87** [mikepenz/FastAdapter#140]
Hi, Mike!
Do you remember about issue 119 and your words "@artests87 you might be interested in this huge new feature: #122"
Then you did the feature- when we open expandapleItem and select inner Items, and to close expandItem we don't lose selected inner items.
But it works only 1.5.0.b2-SNAPSHOT@aar and not works in fresh version.
May I got new version and the feature?
Thanks!

**Comment by mikepenz** [comment]
@artests87 in the snapshot this behavior was default. For the stable branch it is not default and just has to be activated :D (to be correct the default behavior has to be deactivated)

```java
withPositionBasedStateManagement(false)
```

https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L225

**Comment by Rainer-Lang** [comment]
...and it is working great.

**Comment by artests87** [comment]
Can I use the snapshot and everything will work great?

2016-06-03 16:02 GMT+03:00 Rainer-Lang <notifications@github.com>:

**Comment by mikepenz** [comment]
@artests87 just use the latest stable version and set this property. then it's exactly as in the snapshot
