### ISSUE TITLE
How do I add ads from DFP/Google admob based on position in the stream

### ISSUE THREAD

**Issue by gupta11** [mikepenz/FastAdapter#141]
Hello,

I have used volley in the past and my own adapters and I am seeing choppyness when I scroll and when ads are called. 
How would the ad calling feature work on this?

**Comment by mikepenz** [comment]
@gupta11 are there now already native ads available? The `AdView` is not the most performant if used within a `RecyclerView`

**Comment by gupta11** [comment]
Yes you can have native Ads being sent realtime based on position on the infinite list so every 6 items or every 3 items etc. What would you recommend to use for the ListView if this is definitely a requirement.

**Comment by mikepenz** [comment]
But in general you can use the `WrapAdapter` which wraps around the `FastAdapter` and will add items inbetween your list:
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/adapters/WrapAdapter.java

(The above `WrapAdapter` will add the items of the given list in equal distances)

You can modify the above too add items all 6 items or so too. Just overwrite `shouldInsertItemAtPosition` and `itemInsertedBeforeCount` of the `AbstractWrapAdapter` 
I have done this here: https://github.com/mikepenz/FastAdapter/blob/feature/admob/library-extensions-admob/src/main/java/com/mikepenz/fastadapter_extensions/admob/AdmobAdapter.java (but this is not yet finished, as there were no real `NativeAds` at that time 
As you can see I used the `AdView` in this branch: https://github.com/mikepenz/FastAdapter/blob/feature/admob/library-extensions-admob/src/main/java/com/mikepenz/fastadapter_extensions/admob/items/AdBannerItem.java which resulted in bad performance.

**Comment by gupta11** [comment]
How does CNN and USA today have ads in their apps ?

**Comment by mikepenz** [comment]
@gupta11 probably not via the `AdView` of AdMob as it's a `WebView` that's why I asked if you have beta access to native ads which will then be image and text provided via api and is displayed natively as item, which will provide best possible performance :)

**Comment by mikepenz** [comment]
I think as far as I can tell this is answered.
