### ISSUE TITLE
Does it support non sticky footer?

### ISSUE THREAD

**Issue by stonecold123** [mikepenz/FastAdapter#142]
Read this https://github.com/mikepenz/FastAdapter/issues/68
but I still don't understand how to use `FooterAdapter` to add a non-sticky footer to the recyclerlist.
Suppose I have an xml layout as a footer,

````xml
<LinearLayout
        android:id="@+id/footer"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal">
       <Button
                android:id="@+id/delete_item"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:text="Delete"/>
</LinearLayout>
````
what is the way of adding this layout as a footer to the adapter ?  I'm not sure what to add to `footerAdapter.add()`. 

Took a shot in the dark after reading this [tutorial](http://blog.grafixartist.com/recyclerview-adapter-android-made-fast-easy/):

FooterView:
```java
public class FooterView extends AbstractItem<FooterView, FooterView.ViewHolder> {
    public FooterView() {
    }

    @Override
    public int getType() {
        return R.id.footer;
    }
    @Override
    public int getLayoutRes() {
        return R.layout.footer;
    }
    @Override
    public void bindView(ViewHolder holder) {
        super.bindView(holder);
        holder.pagerButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                     // sth action
            }
        });
    }
    protected static class ViewHolder extends RecyclerView.ViewHolder {
        View pagerButton;
        public ViewHolder(View itemView) {
            super(itemView);
            pagerButton = itemView.findViewById(R.id.delete_item);
        }
    }
}
```

In the Activity.class:
````java
GenericItemAdapter<ItemModel, ItemAdapter> adapter = new GenericItemAdapter<>(ItemAdapter.class, ItemModel.class);
fastAdapter = new FastAdapter();
fastAdapter.withSelectable(false);
FooterAdapter<FooterView> footerAdapter = new FooterAdapter();
footerAdapter.add(new FooterView());
GridLayoutManager gridLayoutManager = new GridLayoutManager(this,2);
recyclerView.setLayoutManager(gridLayoutManager);
recyclerView.setAdapter(footerAdapter.wrap(adapter.wrap(fastAdapter)));
adapter.addModel(productItem);
````
But I am getting errors at `footerAdapter.add(new FooterView());`

````
java.lang.NullPointerException
at com.mikepenz.fastadapter.AbstractAdapter.mapPossibleType(AbstractAdapter.java:244)
at com.mikepenz.fastadapter.AbstractAdapter.mapPossibleTypes(AbstractAdapter.java:233)
at com.mikepenz.fastadapter.adapters.ItemAdapter.add(ItemAdapter.java:323)
at com.mikepenz.fastadapter.adapters.ItemAdapter.add(ItemAdapter.java:309)
````

I have also tried the same with HeaderAdapter. It also shows the same error with the `add()` method.

**Comment by mikepenz** [comment]
@stonecold123 where do you "wrap" the adapters as done here:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/GenericItemActivity.java#L61

**Comment by stonecold123** [comment]
Do you mean I need to use FastScrollIndicatorAdapter and wrap the footeradapter with it?

**Comment by mikepenz** [comment]
@stonecold123 you have the `GenericItemAdapter` and the `FooterAdapter` so you need to do the following (the above link was just a sample)

footerAdapter.wrap(adapter);

and you then apply the `footerAdapter` to the `RecyclerView`

**Comment by stonecold123** [comment]
Thanks mike,just solved it. I should have put `footerAdapter.add(new FooterView());` after the the adapters are set.
````
FooterAdapter<FooterView> footerAdapter = new FooterAdapter();
GridLayoutManager gridLayoutManager = new GridLayoutManager(this,2);
recyclerView.setLayoutManager(gridLayoutManager);
recyclerView.setAdapter(footerAdapter.wrap(adapter.wrap(fastAdapter)));
adapter.addModel(productItem);
footerAdapter.add(new FooterView());
````

**Comment by mikepenz** [comment]
@stonecold123 yes correctly the `FooterAdapter` already needs the global `FastAdapter` because the `FastAdapter` will manage everything. and without this it will fail too.

(In your case the FastAdapter is the GenericItemAdapter which is FastAdapter + 1 GenericItemAdapter combined)
