### ISSUE TITLE
Reusing Item but with different xml layout in different activities

### ISSUE THREAD

**Issue by stonecold123** [mikepenz/FastAdapter#145]
Hi,
I want to reuse my `itemAdapter` but I also want to use different layouts in different activities. All of the other layouts' views have the same ids and view types as the original one so it should have no issue with the viewHolder class.

Is there a way to change/otherwrite either `getType()` or `getLayoutRes() ` after the GenericItemAdapter class is instantiated in the activity? 
Is there a `itemAdapter.setType(R.id.something)` or `itemAdapter.setLayoutRes(R.layout.something)` to overwrite the value in the ItemAdapter class?

For example:
````
GenericItemAdapter<ItemModel, ItemAdapter> itemAdapter = new GenericItemAdapter<>(ItemAdapter.class, ItemModel.class);
        itemAdapter.setType(R.id.other_argument); //<---- Any method like this to change the type or layout resource? 
        fastAdapter = new FastAdapter();
        FooterAdapter<FooterView> footerAdapter = new FooterAdapter<>();
        recyclerView.setAdapter(footerAdapter.wrap(itemAdapter.wrap(fastAdapter)));
        //......
`````

ItemAdapter.class
````
public class ItemAdapter extends GenericAbstractItem<ItemModel, ItemAdapter, ItemAdapter.ViewHolder> {
    private static final ViewHolderFactory<? extends ViewHolder> FACTORY = new ItemFactory();

    public ItemReCyclerFastAdapter(ItemModel itemModel) {
        super(itemModel);
    }

    @Override
    public int getType() {
        return R.id.recycle; // <--- I want it to be changable.
    }

    @Override
    public int getLayoutRes() {

        return R.layout.item_layout; <--- I want it to be changable.

    }
}
````
Thank you~

**Comment by mikepenz** [comment]
@stonecold123 first of all you mix up `Adapter`s and `Item`s. You are talking about an `item` the whole time. The `ItemAdapter` is a normal adapter which can be used with the `FastAdapter` and which will manage items. 

Coming back to your question of having different views with the same item in different activities. 

There is no way to set the layout and the type as this is a really bad behavior and should not be done! There are many scenarios where it will break, and it should not be done. 

An `Item` also has a `ViewHolder` which is `layout` specific so it also makes no sense to have it changeable. 

In some rare cases it might work though (no support will be given from my side). As you already write your own item implementation you can just overwrite those two methods and make it setable. 

REMEMBER:
- You must not have different layouts for the same type in one activity
- You must not change the layout during runtime in one activity
- You may can have the same item with different layouts and the same type in different activities (as long as you don't use a shared `Pool`)

**Comment by pkozlovskiy** [comment]
@mikepenz 
"You must not change the layout during runtime in one activity"
But how can I change layout of the Item, whan I change LayoutManager of RecyclerView(the useful case with List/Grid switcher)?

**Comment by mikepenz** [comment]
@pkozlovskiy with must not change layout it is meant that the layout file used for a specific item is not changed. That's also not possible with a normal recyclerview as the views are cached. You will need a different item for a different layout

**Comment by pkozlovskiy** [comment]
Thanks, now I understand this. Maybe https://github.com/google/flexbox-layout will help me...
