### ISSUE TITLE
Click on stickyheader

### ISSUE THREAD

**Issue by gaspar1423** [mikepenz/FastAdapter#146]
I'm trying to add a click to a a label on my stickyheader (i have two labels on my header view) but i can get it to work.
I've tried setting the clicklistener on the xml label, i've tried sending events but nothing works

When i create my item, i set it like:  item.withHeader(getString(R.string.checked_product_header)).withSelectable(true);

and still no click feedback.

**Comment by davideas** [comment]
The technique used doesn't allow it, it is simply impossible. So you have to change library or the library should change technique adopting a custom implementation or a new custom LayoutManager, which is quite long and complex to do it.
I gave up this drawing technique, I used the same and then I removed it, now in my library I created a new way to do it, if you are interested you can check it out.

**Comment by mikepenz** [comment]
@gaspar1423 this is not related to the `FastAdapter` this is related to the `StickyHeader` implementation of the 3rd party lib used in the sample. 

You may find some answers here: https://www.google.at/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=clicklistener%20decoration%20recyclerview

But otherwhise you have to switch to a different `StickyHeader` implementation

**Comment by LuizEdgar** [comment]
I'm sorry to open this, but I have a solution for you.

Check the page of the StickyHeader Library used in FastAdapter.

```

StickyRecyclerHeadersTouchListener touchListener =
    new StickyRecyclerHeadersTouchListener(recyclerView, headersDecor);
touchListener.setOnHeaderClickListener(
    new StickyRecyclerHeadersTouchListener.OnHeaderClickListener() {
      @Override
      public void onHeaderClick(View header, int position, long headerId) {
        Toast.makeText(MainActivity.this, "Header position: " + position + ", id: " + headerId,
            Toast.LENGTH_SHORT).show();
      }
    });
mRecyclerView.addOnItemTouchListener(touchListener);
```

**Comment by davideas** [comment]
@LuizEdgar, you should read [last part of] my answer some time ago at this question: http://stackoverflow.com/questions/33018788/how-can-i-set-a-listener-inside-a-recyclerview-header-decor

**Comment by gaspar1423** [comment]
Thank you all for the feedback.

LuizEdgar answer was the temporary solution i needed but i'm going to work on that one because i just want to click on half of the header, but for now it will do the work.
