### ISSUE TITLE
question about withOnBindViewHolderListener

### ISSUE THREAD

**Issue by stonecold123** [mikepenz/FastAdapter#149]
Does `withOnBindViewHolderListener` from `fastAdapter`  ignore the method `bindView` from `ItemModel`?

In the following example, When I use `fastAdapter.withOnBindViewHolderListener`, the button doesn't have an on click listener because the `bindView` method in `ItemModel` is ignored. 

Do I need to redo all of the view binding in `fastAdapter.withOnBindViewHolderListener`?

In the activity class:
````
fastAdapter.withOnBindViewHolderListener(new FastAdapter.OnBindViewHolderListener() {
            @Override
            public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {
                if (viewHolder instanceof ItemModel.ViewHolder) {
                    ItemReCyclerFastAdapter.ViewHolder thisViewHolder = (ItemModel.ViewHolder) viewHolder;
                    ItemModel item = itemAdapter.getItem(position);
                    ItemAttribute row = item.getModel();
                    thisViewHolder.title.setText("something");
                }
            }
        });
````

ItemModel class:
````
public void bindView(ViewHolder viewHolder) {
     viewHolder.button.setOnClickListener(new someListener);
    // More view binding 
}

````

**Comment by mikepenz** [comment]
@stonecold123 you create a new implementation of the `OnBindViewHolderListener` which does not call:
```java
getItem(position).bindView(viewHolder);
```
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1651

You could also just extend the `OnBindViewHolderListenerImpl` and add your logic (don't forget to call the `super`)

**Comment by stonecold123** [comment]
Thank you, fixed with your first suggestion. Regarding the second approach `OnBindViewHolderListenerImpl`, what class should I extend the `OnBindViewHolderListenerImpl`?

**Comment by mikepenz** [comment]
@stonecold123 great. 

```java
public class MyOnBindViewHolderListener extends OnBindViewHolderListenerImpl {
...
}
```

**Comment by yolapop** [comment]
@mikepenz `OnBindViewHolderListenerImpl` is not static class, how can I extend that?

**Comment by mikepenz** [comment]
@yolapop why would you need it?

**Comment by yolapop** [comment]
So, this is not valid anymore?

```
public class MyOnBindViewHolderListener extends OnBindViewHolderListenerImpl {
...
}
```

In my case, I want to get the item's identifier and position when bindView

**Comment by mikepenz** [comment]
@yolapop why don't you do this simply in the `item's` onBind method?

**Comment by yolapop** [comment]
Can't.. because all my items are generic.
Anyway I've copied & pasted `OnBindViewHolderListenerImpl`. It works now.
Thank you for the help @mikepenz

**Comment by mikepenz** [comment]
@yolapop sounds interesting. The MaterialDrawer also builds heavily on flexible generic items.
I wonder the specific usecase where the item specific methods do not work
