### ISSUE TITLE
Helper for search/filter items

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/FastAdapter#15]

**Comment by mikepenz** [comment]
coud probably done via a helper class which just calls the correct update methods on the drawer

**Comment by Rainer-Lang** [comment]
Items shouldn't be erased only invisible

**Comment by mikepenz** [comment]
still for the adapter is a remove

**Comment by mikepenz** [comment]
no helper :P

define a `FilterPredicate` which will internally be used to filter out the items
```java
itemAdapter.withFilterPredicate(new IItemAdapter.Predicate<IItem>() {
            @Override
            public boolean filter(IItem item, CharSequence constraint) {
                
                return false;
            }
        })
```

afterwards you can simply do:
```
itemAdapter.filter("test");
```

or to reset
```
itemAdapter.filter();
```

**Comment by Rainer-Lang** [comment]
@mikepenz everytime a pleasure :-)
