### ISSUE TITLE
Click position problem when using MoPubRecyclerAdapter

### ISSUE THREAD

**Issue by waninkoko** [mikepenz/FastAdapter#150]
I'm having an issue when I try to use MoPubRecyclerAdapter (from MoPub SDK) with FastItemAdapter.

MoPubRecyclerAdapter is basically a wrap adapter to allow MoPub's SDK to place some native ads in the stream.

The problem happens when I press on an item that appears below a native ad. The AbstractItem provided in the FastAdapter listeners is incorrect, probably because the adapter gets the wrong index from the item list.

Is there any way to solve this problem, without modifying MoPubRecyclerAdapter or having to implement my own wrap adapter?

**Comment by mikepenz** [comment]
@waninkoko could you please provide a sample app so I could debug this?

**Comment by waninkoko** [comment]
@mikepenz Sure, I'm gonna create a quick sample app right away.

**Comment by waninkoko** [comment]
@mikepenz A sample app that shows the issue: https://www.dropbox.com/s/dvghaanqp1smowa/MoPubRecyclerAdapterFastAdapter.zip?dl=0

**Comment by waninkoko** [comment]
@mikepenz Forgot to say that MoPubRecyclerAdapter provides a getOriginalPosition method that returns the position in the original adapter.

**Comment by waninkoko** [comment]
I was able to solve this issue by overriding ```getRelativeInfo(int position)``` this way:

```
@Override
public RelativeInfo<SongItem> getRelativeInfo(int position) {
    return super.getRelativeInfo(mopubRecyclerAdapter.getOriginalPosition(position));
}
```

**Comment by mikepenz** [comment]
@waninkoko I am not sure if I am able to have a closer look today. Will answer as soon as possible

**Comment by waninkoko** [comment]
@mikepenz Don't worry, thanks!

I was able to fix the issue with ClickListenerHelper by creating my own and getting the item with ```getRelativeInfo(int position)``` instead of ```getItem(int position)```

**Comment by mikepenz** [comment]
@waninkoko the id you used in the sample application is it a demo id or a real one?

**Comment by waninkoko** [comment]
@mikepenz It's a demo id that MoPub provides to test native ads

**Comment by mikepenz** [comment]
@waninkoko great. thank you. added a clean solution to the latest release
