### ISSUE TITLE
using fastadpter.select(position) to set default selected items,  but their colors are not set?

### ISSUE THREAD

**Issue by stonecold123** [mikepenz/FastAdapter#151]
Hi mike,

I just found `fastAdapter.select()` that seems to allow me to set certain items as default selected. But how can I turn the default selected items to red ? I already have               `UIUtils.setBackground(thisViewHolder.layout, FastAdapterUIUtils.getSelectableBackground(context, Color.RED, true));` in place but it isn't working.

````
List<Integer> selectedPositions = new ArrayList<>();
fastAdapter.withOnBindViewHolderListener(new FastAdapter.OnBindViewHolderListener() {
     @Override
      public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {
          if (viewHolder instanceof ItemModel.ViewHolder) {
              ItemModel.ViewHolder thisViewHolder = (ItemModel.ViewHolder) viewHolder;
              ItemModel thisItemAdapter = itemAdapter.getItem(position);
              ItemAttribute row = thisItemAdapter.getModel();             
       
              UIUtils.setBackground(thisViewHolder.layout, FastAdapterUIUtils.getSelectableBackground(context, Color.RED, true));
              if(row.name.contains("something")){
                   selectedPositions.add(position);
              }
           }
      }
});

for(Integer selectedPosition:selectedPositions){
    fastadapter.select(selectedPosition);
}
````

**Comment by mikepenz** [comment]
@stonecold123 if the background does not change color via states and you require a method to change the background you might have to change the behavior to call the update via this:
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L169

```java
FastAdapter.withSelectWithItemUpdate(true)
```

**Comment by stonecold123** [comment]
Thanks. One more question. If I have a headeradapter wrap around the fastadapter, Do I need to +1 in fasteradapter.select(position)?

**Comment by stonecold123** [comment]
Thanks,mike. But I'm still getting problems. My example is a little tricky. I have to get the default selected items' positions first in `withOnBindViewHolderListener` before executing`fastAdapter.select()`. 

I tried the following 
````
     @Override
      public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {
               .............               
               UIUtils.setBackground(thisViewHolder.layout, FastAdapterUIUtils.getSelectableBackground(context, Color.RED, true));
              if(row.name.contains("something")){
                   fastadapter.add(position);
              }
      }
````
But it gave me `java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling`

If I put it outside the listener:
````
List<Integer> selectedPositions = new ArrayList<>();
fastAdapter.withOnBindViewHolderListener(new FastAdapter.OnBindViewHolderListener(){
             ......
             if(row.name.contains("something")){
                   selectedPositions.add(position);
              }
}

for(Integer selectedPosition:selectedPositions){
    fastadapter.select(selectedPosition);
}
````

The fastadapter.select(position) will run before `withOnBindViewHolderListener` returns selectedPosition.

**Comment by mikepenz** [comment]
@stonecold123 one question. why do you do all of this in the `onBindViewHolder` and not in the `bindView` method of your item, where it should go to?

**Comment by stonecold123** [comment]
@mikepenz, okay I have moved the code back to `bindView`. Is fastadapter.select(position) always called before `bindView`? My problem is that the default selected items are dynamic. I need to get their positions in `bindView` before calling `fastadapter.select(position)`

**Comment by mikepenz** [comment]
@stonecold123 `bindView` is always called when an item get's into the visible range or the `notifyAdapterItemChanged` was called. If you have enabled it `select` will trigger an `notifyAdapterItemChanged`. 

You should use the `identifier` for those items, so you can get their positions easily.

**Comment by stonecold123** [comment]
Solved!
Your suggestion leads me to this:
````
for(Model data:collection){
   boolean defaultSelected = false;
   if(data.item.contains('default_select')){
       defaultSelected = true;
   }
   itemAdapter.add(new ItemModel(data).withSetSelected(defaultSelected));
}
````
`withSetSelected` is too late if it's in `bindView`. The color won't change accordingly.

**Comment by mikepenz** [comment]
@stonecold123 great ;)

`withSetSelected` just changes the property of the item. This does NOT yet trigger the `bindView` then. To inform the `Adapter` that the item has changed you have to notify him that an element was updated.
