### ISSUE TITLE
Is it possible to keep filtering after selecting an item in SimpleItemList Sample

### ISSUE THREAD

**Issue by stonecold123** [mikepenz/FastAdapter#154]
I have downloaded your example app on my phone with 4.42 version and there is an issue with the filterable and selectable functions. 
Here are my steps:

Click on the filter Icon. 
Type something like "Test 2" 
Randomly select an item like "B Test 21"
Then add "2" to "Test 2" in the filter field to be "Test 22" 
It stops filtering.
Occasionally the problem is corrected if you swipe up and down the list.
It looks like a list update is needed once you go back typing in the filter input. 

I have implemented default selected items https://github.com/mikepenz/FastAdapter/issues/151 in my app so it is unfilterable at the moment.

**Comment by mikepenz** [comment]
@stonecold123 weird. I also was able to reproduce this on Android N. It gives the exception that only the original thread woh created a view can modify it. But that's weird as both actiosn are done with the main thread. 

To get it working and to also save the selectiosn upon filtering you can use the alternative state management by doing the following:

```java
adapter.withPositionBasedStateManagement(false);
```
