### ISSUE TITLE
how to add item on the top of recyclerView

### ISSUE THREAD

**Issue by SahajRana** [mikepenz/FastAdapter#159]
Hey! Its a great library!
I'm currently using it and got stuck to it..
When New item is added, it pops from bottom but i want to add it at top,
How can i achieve it.
```java
@Override
    public void onFeedsChanged(final Feed_item_for_adapter mFeedSuper) {
        mRecyclerView.post(new Runnable() {`
            `@Override
            public void run() {`
                `mFastItemAdapter.add(mFeedSuper);`
                `mFastItemAdapter.notifyDataSetChanged();`
            }
        });
    }
```

**Comment by mikepenz** [comment]
@SahajRana you don't have to call the `notify` methods if you use the `add`, ... methods from the `FastAdapter` everything is handled for you. 

If you want to add something on top just add it at position `0` 
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L341

`mFastItemAdapter.add(0, mFeedSuper)`

**Comment by SahajRana** [comment]
thanks.. it worked!
