### ISSUE TITLE
Suggestion: get filtered state of adapter

### ISSUE THREAD

**Issue by BobOtike** [mikepenz/FastAdapter#162]
Hello Mike, 

in my implementation certain aspects of the app's behaviour are supposed to change when items are filtered (disable drag, different CAB, etc...). As of now, I have to keep track of whether the items are filtered or not myself, which is, to my mind, an unnecessary source of inconsistencies or bugs. A simple method e.g. `getFilteredState` could prevent that. 

Cheers!

**Comment by mikepenz** [comment]
@BobOtike the easiest way is if you do the following
```
itemAdapter.getItemFilter().getConstraint()
```

If the above is empty or null the adapter is currently not filtered
