### ISSUE TITLE
Select all not working properly without PositionBasedStateManagement

### ISSUE THREAD

**Issue by BobOtike** [mikepenz/FastAdapter#163]
Hi Mike, 

I have the weirdest issue:

When using `PositionBasedStateManagement`,  `FastItemAdapter#select()` works properly. Since I'm using filtering, I have it disabled though. Without it, the items currently visible in the `RecyclerView` are being inverted right after the call, i. e. ones that were already selected become unselected and vice versa,  and only after scrolling them out of view and scrolling them back in, they are all being displayed as selected.

This particular occurence was already being discussed in #122, but it didn't seem there was a solution or another problem and the issue was also rather unorganised, so I'd figured I might ask again. 

I have played around a little and the problem seems to have something to do with `notifyDataSetChamged`. Whenever I retrieve an item from the adapter,  call `withSetSelected(true)` on it and afterwards call `notifyDataSetChanged`, nothing is being updated. If I use `notifyAdapterItemChanged` on that particular item, it is being displayed correctly.  

For only changing one items selected state, this is feesible, but I also have the situation where I use `setNewList` to exchange all items and this in turn calls `notifyDataSetChanged`. If the new list being set contains items which I have already called `withSetSelected(true)` on before putting them in the adapter, their state is also not displayed as selected. 

I don't know where this discrepancy in behaviour could stem from. 

When after setting the new items list I "reconnect" my adapter to the `RecyclerView` (as mentioned in #122)  the selections are being updated, but I don't think there is such a thing as "having lost the connection", it merely forces the `RecyclerView` to scrap all the `ViewHolder`s, which in itself `notifyDataSetChanged` should also do but somehow fails in this scenario. 

Cheers, hope you can help me on this one.

**Comment by mikepenz** [comment]
@BobOtike can you provide a small sample app to showcase this issue?

In general you must not call the `notify*` methods from the adapter just the `notifyAdapter*` ones. Also the `set`, `add`, ... methods all handle this already for you so this also is not really necessary. 

If you change the whole list you have to options either via `setNewList` or via `set`. Have you tried both? 
Also it would be good to know if you provide `identifier`s to your items? Or have enabled the automatic `identifier` util (which will define identifiers for all items) ?

**Comment by BobOtike** [comment]
Sure, I will put something together and let you know once I have finished. 

In the meantime, to answer your questions:

   - I have also tried with `notifyAdapter*`,  same result
   - I have both tried `set` as well as `setNewList`, no change in behaviour
   - I have multiple lists, some use `identifier`s provided by me and others the `idDistributor`, also has no 
     influence

**Comment by BobOtike** [comment]
Hey @mikepenz, here goes the example:

[https://www.dropbox.com/s/jaeak6fheby1r40/SelectedSample.zip?dl=0](url)

**Comment by mikepenz** [comment]
@BobOtike ok after some testing. The issue is realted to the  `ColorDrawable`, more specific to the`FadeDuration` which is defined when you define `animate=true`
```java
states.setEnterFadeDuration(duration);
states.setExitFadeDuration(duration);
```

If you change to not animate in your code (change to false):
```java
UIUtils.setBackground(holder.itemView, FastAdapterUIUtils.getSelectableBackground(context, Color.RED, false));
```

it works without any problems. 

I assume this is a plattform bug, or not properly supported somehow.

**Comment by BobOtike** [comment]
Thanks @mikepenz for the super-fast responses, as always! 

This solved my selection issues when swapping the items in the adapter. 

One minor thing remains though: while the selecting shows the proper change without animation now, when deselecting I get an unclean transition, there is a slight afterglow of the ripple (running Lollipop on my device) to be seen. Do you by any chance have an idea how to get rid of that as well? 

This is really more an aesthetic issue than a functional one :D

**Comment by mikepenz** [comment]
@BobOtike the animation can theoretically be "enabled" when you set that the adapter will update on click (but it has a slight delay) which is also not the proper thing. 

regarding your afterglow of the ripple. not sure where it comes from because the `RecyclerView` does not have ripple's on the views, and the item you sent to me had non either. Do you define it somewhere?

**Comment by BobOtike** [comment]
@mikepenz I think at some point I did it already and if I remember correctly this creates again this kind of blinking effect,  but I will check it out. 

`FastAdapterUIUtils#getSelectableBackground` which is part of assigning the background drawable retrieves `R.attr.selectableItemBackground` which in Lollipops case is a ripple drawable. You can even see it in the sample I've sent you, after deactivating the animation and only when you deselect by clicking the item, not when using `select` or `set`. In the sample it's not very prominent because of the white background and the lack of contrast but in my apps theme you see it very clearly.

**Comment by mikepenz** [comment]
@BobOtike oh completely missed that this bases on the `selectableItemBackground` if you want it without, I would recommend you to create a select background as shown here: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/res/drawable/button_rect_list_normal.xml

**Comment by BobOtike** [comment]
I don't want to completely eliminate the ripple, more like getting the best of both worlds i.e. having ripple when clicking/long clicking but remove only the afterglow when deselecting. 

I will try to figure out a way, if I do I'll let you know. 

Thanks for your sublime support and keep up the good work, your libs are truly amazing, cheers!

**Comment by BobOtike** [comment]
@mikepenz Turns out it was rather easy to achieve:

I have created my own `getSelectableBackground` based off of `FastAdapterUIUtils#getSelectableBackground` and only  commented out this line:
`states.setEnterFadeDuration(duration);`

Instead of removing both animations I only remove the one for entering, result: no bug when setting already selected items and no afterglow since the fadeout animation is still in place.

**Comment by mikepenz** [comment]
@BobOtike oh great :). 

Still weird enough that this is broken in andoird
