### ISSUE TITLE
EndlessRecyclerOnScrollListener triggers 2 pages by 2 pages, not one by one.

### ISSUE THREAD

**Issue by shehabix** [mikepenz/FastAdapter#165]
this is reproducible directly in the sample app.
check it by simply adding:
```java
Log.d("LOAD_MORE", "page:" + currentPage);
```
here:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/EndlessScrollListActivity.java#L100

Testing on Samsung Galaxy S7 and Nexus 5

**Comment by FabianTerhorst** [comment]
@shehabix have you tried to use the other endless scroll listener constructor thats needs the footeradapter? https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnScrollListener.java#L28

```
 recyclerView.addOnScrollListener(new EndlessRecyclerOnScrollListener(footerAdapter) {
            @Override
            public void onLoadMore(final int currentPage) {
                footerAdapter.clear();
                footerAdapter.add(new ProgressItem().withEnabled(false));
                //simulate networking (2 seconds)
                Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        footerAdapter.clear();
                        for (int i = 1; i < 16; i++) {
                            fastItemAdapter.add(fastItemAdapter.getAdapterItemCount(), new SampleItem().withName("Item " + i + " Page " + currentPage));
                        }
                    }
                }, 2000);
            }
        });

```

**Comment by shehabic** [comment]
@FabianTerhorst does this check if the footer adapter is empty or not before calling? cause that's the work-around I created in my app, while keeping track of the currentPage in another place.

**Comment by FabianTerhorst** [comment]
@shehabic its ignoring the item count from the footeradapter to calculate the current page and the page jump.

**Comment by shehabix** [comment]
@FabianTerhorst Just got home and tested it, this seems to be working, thanks.

**Comment by shehabix** [comment]
@FabianTerhorst this seems to be working, thanks
