### ISSUE TITLE
Got UI layout glich on longClick

### ISSUE THREAD

**Issue by Demuss** [mikepenz/FastAdapter#168]
I got glich when selecting items on longClick with fastAdapter, there is 2 toolbars
In first screen is not selected item but on second screen is selected, and as you see 2 toolbars
On kitkat(Phone) is fine, but lollipop+(Emulator) has this glich

```xml
  <?xml version="1.0" encoding="utf-8"?>
 <android.support.design.widget.CoordinatorLayout
     xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:app="http://schemas.android.com/apk/res-auto"
     xmlns:tools="http://schemas.android.com/tools"
     android:layout_width="match_parent"
     android:layout_height="match_parent"
     android:fitsSystemWindows="true"
     tools:context="com.inten.demuss.CoversActivity">
 
     <android.support.design.widget.AppBarLayout
         android:layout_width="match_parent"
         android:layout_height="wrap_content"
         android:theme="@style/AppTheme.AppBarOverlay">
 
         <android.support.v7.widget.Toolbar
             android:id="@+id/toolbar"
             android:layout_width="match_parent"
             android:layout_height="?attr/actionBarSize"
             android:background="?attr/colorPrimary"
             app:popupTheme="@style/OrangeTheme.PopupOverlay"/>
 
     </android.support.design.widget.AppBarLayout>
 
     <include layout="@layout/recycler" />
 ```
 
 </android.support.design.widget.CoordinatorLayout>

and using 

```xml
    <style name="OrangeTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">@color/back</item>
        <item name="windowActionModeOverlay">true</item>
        <item name="android:colorForeground">@color/foreground_material_dark</item>
        <item name="colorPrimary">@color/primary_light</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="colorAccent">@color/accent</item>
        <item name="android:colorBackground">@color/background_material_light</item>
    </style>
```

```java
        toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        recyclerView = (RecyclerView) findViewById(R.id.recyclerView);
```

I'm using  materialDrawer lib in this activity
and code from fastAdapter multiselect example
 

![screenshot_20160730-125729](https://cloud.githubusercontent.com/assets/18263383/17269584/2b324c36-5655-11e6-92bf-32a9b753ea16.png)
![screenshot_20160730-125733](https://cloud.githubusercontent.com/assets/18263383/17269586/3bfb13a4-5655-11e6-8871-232650960807.png)

**Comment by mikepenz** [comment]
@Demuss definitely not related to the `FastAdapter` as it has nothing to do with the `Toolbar` as it is only an adapter providing items to the `RecyclerView` and also not really related to the `MaterialDrawer` as it also does not add / change the `Toolbar`. 

The issues possibly only happens because a redraw occurs and this makes it visible. 

Could you perhaps make a small sample app showcasing this issue, to make it easier to debug it for you.

**Comment by Demuss** [comment]
After 2 day research I found  1 line of code is missing from styles-v22 I think so

>         <item name="windowActionModeOverlay">true</item>

values above are from styles-v19, so it works on kitkat, but lollipop not. It's my mistake.

Thank you, your libs are fantastic, I use nearly all of them. you do great things.

**Comment by mikepenz** [comment]
@Demuss thank you.
