### ISSUE TITLE
notify no response coming across EventBus?

### ISSUE THREAD

**Issue by jp1017** [mikepenz/FastAdapter#169]
Demo:

```
    @Subscribe
    public void postTaxi00E7(Taxi_00E7 taxi_00E7) {
        TradeItem item = new TradeItem();
        item.time = taxi_00E7.getInserviceTime();
        mTradeItems.add(0, item); 

        KLog.w(TAG, "size: " + mTradeItems.size());

        mItemAdapter.notifyItemChanged(0);
        mItemAdapter.notifyAdapterDataSetChanged();
        mItemAdapter.notifyDataSetChanged();
        mItemAdapter.notifyAdapterItemChanged(0);
        mItemAdapter.notifyItemInserted(0);
    }
```

`mTradeItems.size` increasing when  this method(subscribed by EventBus 3) execute every time, but the five `notify` methods don't  response, what's wrong?

**Comment by mikepenz** [comment]
@jp1017 is this method executed on the main thread? If you use the `add` etc methods of the `FastAdapter` you do not have to call nay notify methods.

**Comment by jp1017** [comment]
@mikepenz I checked the thread, it's not the main thread, but when I execute this code:

```
        TradeItem item = new TradeItem();
        item.time = taxi_00E7.getInserviceTime();
        mTradeItems.add(0, item); 
```

in Handler which is created by main thread, but the View didn't update even after adapter.notify.

so, any advice?

**Comment by jp1017** [comment]
@mikepenz 

My View can update when my Adapter extends RecyclerView.Adapter<ViewHolder>.

This can work between main thread and non-main thread.

so, is this a bug?

**Comment by FabianTerhorst** [comment]
@jp1017 every adapter notify and item add has to be in the main thread. The app should throw a exception when this isn´t the case. This behavior is not related with this library.

**Comment by FabianTerhorst** [comment]
The code isn´t enough to identify the bug. This is actually a question for stackoverflow.

**Comment by jp1017** [comment]
@FabianTerhorst 

Yes, but it work well without exception when using the origin adapter.

And, it doesn't work when using this lib in main thread when coming across EventBus. 

Yours work well when using EventBus 3?

**Comment by FabianTerhorst** [comment]
@jp1017 im using RxJava with RxAndroid. And i have changed the subscriber thread to the main thread.

**Comment by jp1017** [comment]
@FabianTerhorst 
:+1:  

I change it to Handler created by main thread, but it doesn't work still. :disappointed:

**Comment by FabianTerhorst** [comment]
what is the name of the current thread. ``` Thread.currentThread.getName() ```

**Comment by jp1017** [comment]
@FabianTerhorst Yes

**Comment by mikepenz** [comment]
@jp1017 what's the output of 
```java
Thread.currentThread().getName()
```

**Comment by jp1017** [comment]
@mikepenz 

main, but it doesn't work when using your fantasitic lib. 

It worked when my Adapter extends RecyclerView.Adapter.

**Comment by mikepenz** [comment]
@jp1017 can you please provide a small sample app showcasing this issue? So we are able to debug what's going on in this case?

**Comment by jp1017** [comment]
@mikepenz @FabianTerhorst 

Demo here: https://github.com/jp1017/FastAdapterIssue

**Comment by mikepenz** [comment]
Fixed with this PR
https://github.com/jp1017/FastAdapterIssue/pull/1/files

**Comment by jp1017** [comment]
cool, thank you very very much. :haha
