### ISSUE TITLE
Multi level nesting

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#171]
This is not supported currently, correct? Having sub items with sub items and sub items and so on...

**Comment by mikepenz** [comment]
@MFlisar depends on the exact thing you need? like the expandable items? or just always visible items within each other?

You can still provide them as flat list and have different items with different paddings?

**Comment by MFlisar** [comment]
All levels should be expandable...

Flat list with padding is not problem, you're right. But I would like to have an expandable solution, where each level can be expanded and collapsed...

Can be done by dynamically adding and removing items + custom padding... Still, wanted to know if this works somehow with your library...

**Comment by mikepenz** [comment]
@MFlisar this is also possible. Even done in the sample app. 

There is just a limitation. If you want to update an item from a sub sub level this is currently not supported. Updating a sub item only works with 1 level. 

Everything else is fine and works

**Comment by MFlisar** [comment]
I tried loading the levels step by step (asynchronously, from top down). Maybe that's why I could not get it working...

I'll recheck that

**Comment by mikepenz** [comment]
@MFlisar the `AdvancedSample` has multiple levels

**Comment by MFlisar** [comment]
I already saw it... I may have made another thing wrong in my first try... Have it working already. Thanks
