### ISSUE TITLE
Strange space in toolbar

### ISSUE THREAD

**Issue by LukA888** [mikepenz/FastAdapter#172]
Hi there!

I have a space between the close icon and the TextView's text on toolbar. It's strange because when I change the version of FastAdapter, changes their padding/margin. I don't know why :/

This is the result that I'm getting (I've pressed the close button to do a screenshot):

**FastAdapter with version 1.5.2**
![screenshot_20160810-155258](https://cloud.githubusercontent.com/assets/18327422/17556240/012a5962-5f13-11e6-98d2-d796f84e12af.png)

**FastAdapter with version 1.5.5 and further**
![screenshot_20160810-155550](https://cloud.githubusercontent.com/assets/18327422/17556241/013013fc-5f13-11e6-8fba-be9fd280a925.png)

I've tried changing app's style, putting app:contentInsetStart="0dp" on toolbar, negative padding, etc.
My problem is being produced on a emulator with API 22 and a real device with API 16.  

I don't know where is the relationship between my toolbars and FastAdapter's version. 

**Thank you!** :)

**Comment by FabianTerhorst** [comment]
It's the update from the support Library that changed this.

**Comment by mattiasbe** [comment]
You are picking up an old appcompat in the support library, perhaps transitive from fastadapter. Make sure you are using the latest version of both fastadapter v1.6.1 (that references the latest) but most of all that you yourself reference appcompat v24.1.1,

**Comment by mikepenz** [comment]
@FabianTerhorst @mattiasbe thanks both for answering

**Comment by LukA888** [comment]
Wow, thank you for the fast answers! :smile: 
I've changed the version of appcompat to 24.1.1 and FastAdapter's to 1.6.1 but the space remains there.
What can I do? I mean, I think the space is ugly but I don't know if it's a correct design or a bug.

**Comment by FabianTerhorst** [comment]
I don't know what's the problem. The old Space was definitely to small.

**Comment by LukA888** [comment]
Hmmmm, in my opinion it looks a little bit strange.

**Comment by mikepenz** [comment]
@LukA888 you might should head over to Stackoverflow as this is definitely a support libs topic and not library related.
