### ISSUE TITLE
Non-static ViewHolder inner class.

### ISSUE THREAD

**Issue by girish3** [mikepenz/FastAdapter#173]
When I extended my inner class with `RecyclerView.ViewHolder`. I was getting runtime exception "You have to provide a ViewHolder with a constructor which takes a view!", even though I had a constructor which takes up a view!! My only problem was I didn't set my inner class **static**. Then I found out in AbstractItem.java that there is no logic for creating new instance for a non-static inner class (in which case getDeclaredConstructor method takes outer class type as first argument). 

Either the inner class should be allowed as non-static, or a meaningful exception message should be given.

**Comment by mikepenz** [comment]
@girish3 this exception also happens when you use proguard or anything and don't have a `ViewHolder` factory:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java#L148
