### ISSUE TITLE
FireBase adapter implementation

### ISSUE THREAD

**Issue by dexion** [mikepenz/FastAdapter#174]
What about Firebase? FastAdapter need a finite set of elements emmidiatly `itemAdapter.addModel(<ModelList>)`. Can we cascade adapters with `.wrap()` for example with this adapter [FireBaseRecyclerAdapter](https://github.com/firebase/FirebaseUI-Android/blob/master/database/src/main/java/com/firebase/ui/database/FirebaseRecyclerAdapter.java)? Can you provide some explanation how to use both tools simultaneously or other way to use your adapter with Firebase?

**Comment by mikepenz** [comment]
@dexion I have added the initial WIP state of a `FirebaseItemAdapter` to the repo. This is untested and may not yet work as expected. 

Feel free to open a Pull request to enhance it. 

https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-firebase/src/main/java/com/mikepenz/fastadapter_extensions/firebase/FirebaseItemAdapter.java

**Comment by mikepenz** [comment]
You can't cascade external adapters as they have to be supported. That means you can only wrap adapters which implement the interface from the `FastAdapter` library. Which the `FirebaseItemAdapter` does. So you can basically use this one (it will definitely need more work and additions, but should be a good start)

But for normal use you can also just load the list of elements from `Firebase` pass it to a normal adapter and you are good to go. Using the `FirebaseAdapter` will just simplify things even further
