### ISSUE TITLE
disable move items for some items

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#177]
how can disable drag and drop sort for some items ?

thanks

**Comment by mikepenz** [comment]
Are you using the `SimpleDragCallback`? 
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/drag/SimpleDragCallback.java#L18

You should be able to check if the move is allowed with an `ItemTouchCallback` and defining a `onMove` method:
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/drag/SimpleDragCallback.java#L65

**Comment by DJafari** [comment]
ok mikenpenz, thanks

i will tried it, thanks for your answer
