### ISSUE TITLE
is filtering items possible based on item variables like name,description etc.

### ISSUE THREAD

**Issue by sumitsahu2207** [mikepenz/FastAdapter#178]
Hi,

I wanted to filter items based on item model ( like name,description etc.)
Is it possible?

Thanks,
Sumit

**Comment by mikepenz** [comment]
@sumitsahu2207 you can implement the filter to take any values from your item:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SimpleItemListActivity.java#L79
Just check out the sample activity

**Comment by sumitsahu2207** [comment]
But if we've price kind of field and we've to filter items based on some price range like $2000-$5000 then how do we do that

**Comment by sumitsahu2207** [comment]
I checked this activity, I think it's filtering item based on the search right?

**Comment by mikepenz** [comment]
@sumitsahu2207 yes it is filtering based on search. but you can alter this. the integrated filter only takes a `CharSequence` as param. 

You can either implement your own filtering and just update the list. Or you use the provided functionality and pass in some pattern you can use in the filter like:

```java
fastItemAdapter.filter("price:2000-5000");
```

**Comment by sumitsahu2207** [comment]
If possible, could you please given an example of implementing this custom filtering based on price range.

**Comment by Rainer-Lang** [comment]
I'm sure it's in the sample app.

**Comment by sumitsahu2207** [comment]
Thanks for your reply.
Is it possible to filter items based on multiple search terms for different fields.
For Example:
if we want to filter based on name and gender then can we use filter method for this case?
fastItemAdapter.filter();

**Comment by mikepenz** [comment]
as mentioned above you just need to have the logic inside the filter to identify on which pattern to search. so for gender and name you would probably add something like:
```java
fastItemAdapter.filter("price:2000-5000;gender:male;name:Max");
```

**Comment by sumitsahu2207** [comment]
Yes, Thanks Mike :)

I was checking your filter code in ItemAdapter and now I got, how I've to implement it in filter logic.

Thanks again Mike for your prompt response.
