### ISSUE TITLE
Parcelable IItems

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#179]
Is it possible to extend the `IItem` class to be parcelable?

I have a dialog library and I want to init dialogs with abstract `IItem` and when I try to implement parcelable I get errors for the tag of `IItem`. Current solution is to make my dialogs abstract and then create the items in the derived class, but I would prefer a more generic solution...

**Comment by Rainer-Lang** [comment]
Use generic where view and model are separated. Model could be parcelable.

**Comment by Rainer-Lang** [comment]
@MFlisar Please let me know if you need further information.

**Comment by mikepenz** [comment]
@MFlisar `IItem` is an interface :D Just make your implementation of the `IItem` to be a `parelable`

**Comment by MFlisar** [comment]
I'll check the generic adapter, looks like it solves the problem.

And I actually meant the `AbstractItem`, just mixed the `IItem` with it, because the adapter in my dialog is working with `IItems`...
