### ISSUE TITLE
Get selected items back

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/FastAdapter#18]
How can I get the selected items back?
Is there a method?

I only found this: `Set<Integer> getSelections()`

**Comment by mikepenz** [comment]
@Rainer-Lang this method will return the positions of the selected items. What do you need?

**Comment by Rainer-Lang** [comment]
I need the items

**Comment by Rainer-Lang** [comment]
Both are interesting: positions and the selected items

**Comment by Rainer-Lang** [comment]
But the result should be parcelable to put it in a bundle.

**Comment by mikepenz** [comment]
@Rainer-Lang i do not have to care about the parcable. i will just return a `Set<Item>` where item = `<Item extends IItem>`
