### ISSUE TITLE
Click listener in item component  

### ISSUE THREAD

**Issue by AhmedDonkl** [mikepenz/FastAdapter#180]

**Comment by Rainer-Lang** [comment]
It's not a good style to delete the question...

**Comment by AhmedDonkl** [comment]
@Rainer-Lang  sorry for that i was mistake in something and i want just to delete issue sorry for distribution.

**Comment by Rainer-Lang** [comment]
@AhmedDonkl Your question was interesting and I even wanted to know if my solution is the "best practice"- or if there is another better one.

**Comment by AhmedDonkl** [comment]
ok @Rainer-Lang  my question was about what is best practice to make click listener on image inside item make it inside item class or callback and the solution i found it depend about what you want to do  the 2 ways is working. 
my problem was about sending activity object to each item object which was bad but i found you can get context inside your item with this 
`      Context ctx = holder.itemView.getContext();`
.

**Comment by Rainer-Lang** [comment]
Thanks. I'm also using the holder context.

**Comment by mikepenz** [comment]
Using
```java
Context ctx = holder.itemView.getContext();
```

is the correct way of getting the context.
