### ISSUE TITLE
Problem with MopubFastItemAdapter in 1.8.0

### ISSUE THREAD

**Issue by waninkoko** [mikepenz/FastAdapter#181]
After upgrading FastAdapter from 1.7.0 to 1.80 in a couple of apps, I'm having an issue in every RecyclerView where I use MopubFastItemAdapter. Basically the problem is that ```bindView(ViewHolder, List)``` is never called in the items.

If I use FastItemAdapter directly, this issue doesn't happen at all.

**Comment by mikepenz** [comment]
@waninkoko have you read the changelog here: https://github.com/mikepenz/FastAdapter/releases

**Comment by mikepenz** [comment]
Hmm I can't test right now but could be related to those changes

**Comment by waninkoko** [comment]
@mikepenz Yes, I read the changelog. 1.8.0 is working fine until I replace FastItemAdapter with MoPubFastItemAdapter.

I didn't have time yet to check this issue deeply, sorry for not being able to give more details.

**Comment by mikepenz** [comment]
@waninkoko just had a look at their code. They have simply implemented the adapter wrong. They just overwrite the `bindViewHolder` without the payloads. 

So the one with payload is never forwarded to the `FastAdapter`. 

They should handle it the same as done in the android recyclerView code to forwarding the call from the bindViewHolder with payload to the other one. 

Either you are able to move out their adapter to your project and implement the payload listener too, or you keep the old version. Or you change the `MopubFastItemAdapter` to look like this:

```java
public class MopubFastItemAdapter<Item extends IItem> extends FastItemAdapter<Item> {
    private MoPubRecyclerAdapter mMoPubAdAdapter;

    public MopubFastItemAdapter withMoPubAdAdapter(MoPubRecyclerAdapter moPubAdAdapter) {
        this.mMoPubAdAdapter = moPubAdAdapter;
        return this;
    }

    @Override
    public int getHolderAdapterPosition(RecyclerView.ViewHolder holder) {
        return mMoPubAdAdapter.getOriginalPosition(super.getHolderAdapterPosition(holder));
    }

    @Override
    public void onBindViewHolder(final RecyclerView.ViewHolder holder, int position) {
        super.onBindViewHolder(holder, position, Collections.EMPTY_LIST);
    }
}
```

**Comment by waninkoko** [comment]
Since FastAdapter 2.6.0, the click listener stops working.

If I set the FastItemAdapter as the RecyclerView adapter, instead of the MoPubRecyclerAdapter, it works well, but obviously I don't get any ads.

I hope I get some free time tomorrow to debug why exactly this happens.

**Comment by mikepenz** [comment]
@waninkoko it also does not work with v2.6.2?

**Comment by waninkoko** [comment]
@mikepenz Yes, I actually tried with 2.6.0 and 2.6.2

**Comment by mikepenz** [comment]
please let me know as soon as you had time to check.
