### ISSUE TITLE
onBindViewHolder(VH, Integer) breaking change on v1.8

### ISSUE THREAD

**Issue by Christophe668** [mikepenz/FastAdapter#184]
Hello,

Since the update 1.8 `onBindHolder(holder, position)` has an empty implementation to force the user of the library to use `onBindHolder(holder, position, payload)` instead.

I understand this change, unfortunately it is breaking a library I'm using [recycleview-animators](https://github.com/wasabeef/recyclerview-animators).
This library is wrapping the Recyclerview adapter (in this case FastAdapter) in order to bind animations into the items. 
Sadly the AnimationAdapter class of this library is calling `onBindHolder(holder, position)` only and not `onBindHolder(holder, position, payload)`. The items are never bound due to this change.

I hope I gave you enough information,

Thank you for your amazing work !

**Comment by mikepenz** [comment]
@Christophe668 in general I would say, that it's a bug by this library and I would say they have to fix it. 

As an alternative you are also able to just extend the `FastAdapter` and overwrite the `onBind` without the payloads. 

On a side node. Having an adapter which animates the items at scroll is not the best idea. And it makes more sense to just have normal `ItemAnimators` in terms of performance etc. (But I understand that some design requirements need this)

I will also probably look, and will add a "legacy" mode to the `FastAdapter` which (when activated) will forward requests to the proper `onBind` method

**Comment by Christophe668** [comment]
I understand your point, I will also look for a better solution on my side. 
Thanks for your feedback !

**Comment by mikepenz** [comment]
But in the end I think legacy mode makes sense because if you check out this issue:
https://github.com/mikepenz/FastAdapter/issues/181#issuecomment-243502324

The problem is that many `Adapter` wrapping `Adapter`s do not correctly override and forward all methods, which leads to these issues

**Comment by waninkoko** [comment]
I think there is an issue with the legacy mode.

When it is enabled, ```onBindViewHolder(ViewHolder, int)``` calls ```onBindViewHolder(ViewHolder, int, List)```, and this method calls ```super.onBindViewHolder(ViewHolder, int, List)```, and this one calls ```onBindViewHolder(ViewHolder, int)``` again and we get an infinite loop of calls.

Maybe ```onBindViewHolder(ViewHolder, int)``` should call the OnBindViewHolderListener directly?

**Comment by mikepenz** [comment]
@waninkoko do you have some more details? As of the code I can't see this inside the `FastAdapter` maybe I am just overlooking something.

**Comment by waninkoko** [comment]
@mikepenz Tomorrow I'll attach the stack trace when the StackOverflowError occurs.

**Comment by waninkoko** [comment]
Well, I just realized that I remember how the stack trace was. It is something like this:

```
java.lang.StackOverflowError
   at android.support.v7.widget.RecyclerView.Adapter.onBindViewHolder
   at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:527)
   at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:513)
   at android.support.v7.widget.RecyclerView.Adapter.onBindViewHolder
   at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:527)
   at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:513)
   at library.with.bad.Adapter.onBindViewHoler
```
