### ISSUE TITLE
DiffUtils

### ISSUE THREAD

**Issue by markus2610** [mikepenz/FastAdapter#185]
Why has the Api not the method?

```java
itemAdapter.setModel(items, new ModelDiffCallback(), false);
```

**Comment by mikepenz** [comment]
It is currently only available on the `ItemAdapter` 
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L299

You can create a PR to add it on the `GenericItemAdapter` for the `Model`s too

**Comment by markus2610** [comment]
The values mItems and items are always the same. I do not see the previous values, empty and add the new list, but where is the copy of the previous list. Have you tested it?

**Comment by mikepenz** [comment]
I have tested it with the normal `ItemAdapter` yes
