### ISSUE TITLE
how to save state of check boxes using adapter

### ISSUE THREAD

**Issue by sumitsahu2207** [mikepenz/FastAdapter#188]
Hi Mike,

How can we save state of check boxes using adapter when we're clearing and adding new data set to adapter.

I saw Checkboxsampleactivity also but couldn't get much idea about this.

Thanks.

**Comment by mikepenz** [comment]
That's up to you. Either your list has the selection or you get the selection and reset it. Enough possibilities but it is up to you how to do it in the end. That's independent of the lib
