### ISSUE TITLE
Sticky header along with filterable fast adapter

### ISSUE THREAD

**Issue by meNESS-RooyeKhat** [mikepenz/FastAdapter#189]
Hi Mike,

Using `FastItemAdapter()` along with sticky header doesn't show items. I have to use `FastAdapter` to make items shown but that's not filterable.

`rv.setAdapter(stickyHeaderAdapter.wrap(itemAdapter.wrap(headerAdapter.wrap(fastAdapter))))`

**Comment by mikepenz** [comment]
Because the sticky adapter is not notified about the changes from the filter. You would have to notify it in your own afterwards

**Comment by meNESS** [comment]
@mikepenz Can you provide an example please?

**Comment by meNESS-RooyeKhat** [comment]
@mikepenz I tried using all adapters notifying methods but didn't help. still items are not showing while using FastItemAdapter (without filtering).

**Comment by meNESS-RooyeKhat** [comment]
I figured out, thanks mike.

**Comment by mikepenz** [comment]
Awesome. Great :)

**Comment by Rainer-Lang** [comment]
Could you post your solution? So others could learn. :-)

**Comment by meNESS** [comment]
@Rainer-Lang I was wrong! I was trying to use `FastItemAdapter` as my base adapter, but `FastAdapter` supports filtering as well. I'm talking about [this line](https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/StickyHeaderSampleActivity.java#L32). To enable filtering along with sticky header, use filtering methods for `fastAdapter` field (in that sample).
