### ISSUE TITLE
Convenient method for updating items

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#192]
I think following is a wide uses use case:

* load a list of data in an "empty" state
* load item per item and update the list

I see, that I'm using following code quite a lot:

    int pos = fastAdapter.getAdapterItems().indexOf(data);
    fastAdapter.set(pos, data);
    fastAdapter.notifyAdapterItemChanged(pos);

What do you think, can (should) their be a `fastAdapter.update(data)` function?

**Comment by mikepenz** [comment]
Just use the `set` method on the `FastItemAdapter` or `ItemAdapter`:

https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/adapters/FastItemAdapter.java#L218

It is also highly recommend to NOT alter the list of items directly. The `FastAdapter` will take care of everything if you use the provided methods. The `getAdapterItems ` method is just there if you want to get the items out again, for nothing else.

**Comment by MFlisar** [comment]
So this is the preferred method:

    int pos = fastAdapter.getAdapterPosition(item);
    fastAdapter.set(pos, item);

One question though, what happens if I pass in a new object with the same identifier? Will this update the position with the new data?

**Comment by mikepenz** [comment]
and yes the above will get the position from the item via it's identifier

For your original question: @MFlisar no this is only supported in the `MaterialDrawer` but might be a handy addition to add a update method for this.

**Comment by MFlisar** [comment]
Question answered, thanks
