### ISSUE TITLE
when swipe to left and delete item, item after swipe get back and remove with flash animation

### ISSUE THREAD

**Issue by SeyedAliFarjaD** [mikepenz/FastAdapter#194]
how can make it with out show it again ?

**Comment by mikepenz** [comment]
@SeyedAliFarjaD could you please be bit more specific about your issue. I am not really sure what you mean

**Comment by SeyedAliFarjaD** [comment]
oh well, first thank for your awesome library.
sorry i'm a rookie!
i solve that problem. when i swipe an item, it will take back; because i dont change ...

**Comment by SeyedAliFarjaD** [comment]
i find another problem now. when i filter list and then insert an item to list, item insert into filter list and when remove filter item will remove too. how can solve this problem.
Thanks Alot ...

**Comment by Rainer-Lang** [comment]
For filter please make a separate issue. It's not related to this issue.

**Comment by SeyedAliFarjaD** [comment]
ok sry

**Comment by seba123neo** [comment]
same here, flash animation when swipe, what is the solution ?
