### ISSUE TITLE
add item when adapter is filtered ...

### ISSUE THREAD

**Issue by SeyedAliFarjaD** [mikepenz/FastAdapter#196]
When i filter list and then insert an item to it, item insert into filter list and when remove filter item will remove too. how can solve this problem.
Thanks alot ...

**Comment by mikepenz** [comment]
@SeyedAliFarjaD how do you filter the list? And how do you add it to the filtered list? Could you please post some code?

**Comment by SeyedAliFarjaD** [comment]
//News_adapter is my model
FastItemAdapter<News_adapter> fastAdapter = new FastItemAdapter<News_adapter>();
//how compare
  fastAdapter.withFilterPredicate(new IItemAdapter.Predicate<News_adapter>() {
            @Override
            public boolean filter(News_adapter item, CharSequence charSequence) {
                return !(item.date.contains(charSequence) || item.title.contains(charSequence));
            }
        });
//filter code
 searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
             @Override
             public boolean onQueryTextSubmit(String query) {
                 return false;
             }
             @Override
             public boolean onQueryTextChange(String newText) {
                 fastAdapter.filter(newText);
                 return false;
             }
         });
//add item by refresherlayout
    fastAdapter.add(item);

//delete item by swap
 fastAdapter.remove(position);

**Comment by SeyedAliFarjaD** [comment]
both romove and add dont work.
i find this bug in your sample app too

**Comment by SeyedAliFarjaD** [comment]
i want add item into main list not filtered list

**Comment by mikepenz** [comment]
@SeyedAliFarjaD you are right this was not possible. I have added this new feature which allows you to add... items when filtered by using the `ItemFilter` provided methods:

```java
((ItemAdapter.ItemFilter)fastItemAdapter.getItemFilter()).add(new SampleItem().withName("Hallo tester testing"));
```

**Comment by mikepenz** [comment]
this will be in the next version

**Comment by SeyedAliFarjaD** [comment]
Thanks :)
👍
