### ISSUE TITLE
Multiselect and filtering - get original items

### ISSUE THREAD

**Issue by rafakob** [mikepenz/FastAdapter#198]
I have list of checkboxes with enabled multiselect and filtering.
Is it possible to retrieve list of "original" items (and list of "selected original" items) when adapter is in filter mode ? Example:

**No filter:**
- [X] `Item 01`
- [ ] `Item 02`
- [X] `Item 03`
- [ ] `Item 21`
- [ ] `Item 22`

`adapter.getSelectedItems()` will return `Item 01` and `Item 03`.

**Filtered:**
- [ ] `Item 21`
- [X] `Item 22`

`adapter.getSelectedItems()` will return only `Item 22` and I want to retrieve list of all selected items, in that case it would be: `Item 01`, `Item 03` and `Item 22`. 

Is there a method for this?

**Comment by mikepenz** [comment]
@rafakob just use the `getSelections()` method of the `FastAdapter`:

```java
fastAdapter.getSelections()
```
