### ISSUE TITLE
Enhancement for convenience - getItemCount(itemTypes)

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#199]
Usecase is following:

You display a list of items and wrap them in header items to group them or to make them collapsible. Now you want to find out how many real items are in your adapter (without the headers). For example, to display the number in the toolbar.

A convenient method for it would be a nice addition...

Example function is following:

    public int getItemCount(List<Class<? extends IItem>> itemTypes)
    {
        int count = 0;
        int adapterItems = mFastAdapter.getItemCount();
        for (int i = 0; i < adapterItems; i++)
        {
            if (itemTypes.contains(mFastAdapter.getAdapterItem(i).getClass()))
                count++;
        }
        return count;
    }

**Comment by mikepenz** [comment]
@MFlisar you don't have to use the `FastItemAdapter` which is in general just a combination of `FastAdapter` and `ItemAdapter`. If you use those on their own you simply can get the `AdapterItemCount` from the `ItemAdapter` which will be the count without the `HeaderAdapter`

Or you use
```java
FastItemAdapter.getItemAdapter().getAdapterItemCount()
```
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L171

**Comment by mikepenz** [comment]
So if you have an `ItemAdapter<IItem>` and you use for example the `HeaderHelper` to group them. you want then know the item count without the headers? Wouldn't you have the count of items before adding the headers anyway? I don't think that the adapter should have the above method.

**Comment by MFlisar** [comment]
I have used expandable headers and wrap them manually... So I create a `List<IItem>` manually, with all headers in it. Currently I disabled expandable for all headers, so all items are shown always... Maybe the above function would even need to be adjusted to traverse all sub items for the collapsed state? Have not tried it yet...

In the end I will allow to have nested headers as well, still I only want to show the number of real items in the toolbar...

**Comment by mikepenz** [comment]
@MFlisar but I am not wrong with my assumption that you already have to know the count of your items prior to adding the expandable sections. 

I think this method can be added to the FAQ --> "How to get item count without expandable parents" 

Thanks
