### ISSUE TITLE
ActionModeHelper - enhancement

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#200]
I use the `ActionModeHelper` with `withSelectOnLongClick`. But I select items manually as well (clicking a header selects or deselects all sub items for example). After selecting items manually, I would need to inform the `ActionModeHelper` about the new selection state.

I think, the `ActionModeHelper` needs a function like following:

	public ActionMode checkActionMode(AppCompatActivity act) {
	    if (mFastAdapter.getSelectedItems().size() == 0) {
			if (mActionMode != null) {
			    mActionMode.finish();
				mActionMode = null;
			}
		}
		else {
		    if (mActionMode == null) {
			    mActionMode = act.startSupportActionMode(mInternalCallback);
			}
		}
		return mActionMode;
	}

Or the `ActionModeHelper` must be bound to the `FastAdapter` and must be notified about selection changes, but I think, the above function is already enough

**Comment by mikepenz** [comment]
@MFlisar oh I see. The problem is that the `ActionModeHelper` hooks in via the `onPreClickListener` which is not fired when setting the selection programatically. 

The question is, what makes more sense. Fireing the event prior to doing the seleciton, which would allow the current implemented mechanisms to work (you would just need to enable fireEvent when done programatically) or adding the above method.

**Comment by MFlisar** [comment]
That's somethnig else I don't really understand. They way you use it, the helper changes selection mode from long click to single click as soon as one item is selected. That's fine. 

I encounter the problem, that afterwards the clicks are not consumed and are propagated to my own click listener. In my case the item click opens the next view which is not what I want.

Therefore I additionally have to change following:

    	mFastAdapter.withOnPreClickListener(new FastAdapter.OnClickListener<IItem>() {
			@Override
			public boolean onClick(View v, IAdapter<IItem> adapter, IItem item, int position) {
				//we handle the default onClick behavior for the actionMode. This will return null if it didn't do anything and you can handle a normal onClick
				Boolean res = mActionModeHelper.onClick(item);
				boolean result = res != null ? res : false;
				return result;
			}
		});
	
To following:

	mFastAdapter.withOnPreClickListener(new FastAdapter.OnClickListener<IItem>() {
		@Override
		public boolean onClick(View v, IAdapter<IItem> adapter, IItem item, int position) {
			boolean result = false;
			{
				if (mFastAdapter.getSelectedItems().size() > 0)
				{
					if (mFastAdapter.isIndexSelectable(position))
					{
						mFastAdapter.toggleSelection(position);
						mActionModeHelper.checkActionMode((AppCompatActivity) mController.getActivity());
						result = true;
					}
				}
			}
			return result;
		}
	});

**Comment by MFlisar** [comment]
So all in all I think using the helper in the `OnClickListener` makes more sense. Because it should consume clicks when the action mode is active...

**Comment by MFlisar** [comment]
PPS: additionally I suggest adding the functionality to show the selection count in the action mode

**Comment by mikepenz** [comment]
@MFlisar no the functionality is already correct in the `onPreItemClickListener` as the item is not yet selected / deselected at this state. Which allows the `ActionModeHelper` to hook into this process and probably even prevent the click event from being further executed. 

Adding the selection cound would be a nice PR ;). 
And I think there is nothing against adding `checkActionMode` to the `ActionModeHelper` could you please also open a PR for this?

**Comment by MFlisar** [comment]
I'll make a PR for it, have it already working...

Still, I need another thing then. If I hook into the `onPreClick` with the `ActionModeHelper`, it makes sure to finish the `ActionMode`, that is fine. But additionally, the `ActionModeHelper` needs to take care to comsume all clicks as long as those will result in a selection.

I could not get this working without the change I posted above.

**Comment by mikepenz** [comment]
So the missing part is that the `select` method does currently not fire the `onPreClick` listener?

**Comment by MFlisar** [comment]
I updated my example here: https://github.com/MFlisar/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/ExpandableMultiselectSampleActivity.java

I added a `withOnClickListener` (that's all I changed). This fires as soon as the selection mode is active and you select/deselect items. If I consume the click with a method like following in the `ActionModeHelper`:

    public Boolean onRealClick(AppCompatActivity activity, IItem item) {
        if (mActionMode != null) {
            checkActionMode(activity);
            return true;
        }
        return false;
    }

And then adjust the click listener to following:

     mFastAdapter.withOnClickListener(new FastAdapter.OnClickListener<IItem>() {
            @Override
            public boolean onClick(View v, IAdapter<IItem> adapter, IItem item, int position) {
                boolean res = mActionModeHelper.onRealClick(ExpandableMultiselectSampleActivity.this, item);
                if (!res)
                    Toast.makeText(ExpandableMultiselectSampleActivity.this, "Item Clicked", Toast.LENGTH_SHORT).show();
                return false;
            }
        });

It works, but the click on the LAST selected item still fires the `onClick`...

The naming `realClick`is bad, I know, but I would rename you `onClick` method in the helper to `onPreClick` and mine to `onClick`. It is necessary to handle the click in the helper to update the `ActionMode` title, because as you said, in the pre click event the selection is not yet updated...

**Comment by MFlisar** [comment]
No I mean any click listener should not be called if the click does select/deselect an item...

Can be solved with something like following though:

    mFastAdapter.withOnClickListener(new FastAdapter.OnClickListener<IItem>() {
            @Override
            public boolean onClick(View v, IAdapter<IItem> adapter, IItem item, int position) {
                // check if the actionMode consumes the click. This returns true, if it does, false if not
                if (mActionModeHelper.getActionMode() == null)
                    onItemClick(v, adapter, item, position);
                return false;
            }
        });

But still, selecting the last item will fire the click event because the action mode is removed in the `onPreClick` listener. So the question comes up:

Why don't you consume the click in the `ActionModeHelper.onClick` function in this case? Changing the `onPreClickListener` to following solves the problem (added some comments for you):

     mFastAdapter.withOnPreClickListener(new FastAdapter.OnClickListener<IItem>() {
            @Override
            public boolean onClick(View v, IAdapter<IItem> adapter, IItem item, int position) {
                //we handle the default onClick behavior for the actionMode. This will return null if it didn't do anything and you can handle a normal onClick
                Boolean res = mActionModeHelper.onClick((AppCompatActivity) mController.getActivity(), item);
                // if the action mode helper will remove the action mode, we consume the click
                // we don't want the click listener to be fired in this case
                if (res != null && !res)
                    return true;
                return res != null ? res : false;
            }
        });

**Comment by MFlisar** [comment]
I've already made a PR, still some additional needs for my usecase came up.

**Question2**

I use view based layouts with a single activity (maybe you know the library conductor) and I therefore have objects that most of the time survive screen rotations adn similar. As the `ActionModeHelper` will as well. This means, when the view is detached, I want to finish the `ActionMode` (to avoid leaking the activity) and when it is attached I call `checkActionMode` (with the new activity). For this szenerio I need to deactivate the automatic deselection in the helper.

I'm not sure how common this is, but for this I would like to add following:

    public ActionModeHelper withAutoDeselect(boolean enabled) {
        this.mAutoDeselect = enabled;
        return this;
    }

Would this method be something you accept in your library?

**Comment by mikepenz** [comment]
@MFlisar withAutoDeselect. where will this property be used afterwards?

**Comment by MFlisar** [comment]
In my case it's more a setter and would be used only here:

    @Override
    protected void onDetach(View view)
    {
        super.onDetach(view);
        if (mActionModeHelper.isActive())
        {
            mActionModeHelper.withAutoDeselect(false);
            mActionModeHelper.getActionMode().finish();
        }
    }

And after rotation I do following to restore the state:

    @Override
    protected void onAttach(View view)
    {
        super.onAttach(view);
        updateViewsLoadedState();
        mActionModeHelper.checkActionMode((AppCompatActivity) mController.getActivity());
    }

Only views have been recreated in my case...

**Comment by mikepenz** [comment]
@MFlisar ok great. 

Yeah that should be fine.
