### ISSUE TITLE
Question regarding withSavedInstanceState

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#201]
I'm always loading my data asynchronous, this means, I will call `setItems` or similar as soon as the data is ready. I'm using rx java observables for this, so I write them in a way that those take care to provide me with fresh and/or cached data and I'm done. This way of asynchronous data loading has a drawback though: I need to save the bundle manually until I can pass it to the `FastAdapter`, because I never know in which lifecycle event my data will be available...

Does anything speak against holding the bundle in the fast adapter and use it after the first `setItems` or `setNewItems` call? Maybe with a custom builder setter like `withSavedInstanceSate(Bundle bundle, boolean cacheUntilFirstListSetterCall)` or similar?

**Comment by mikepenz** [comment]
@MFlisar the bundle should not be held inside the adapter. As this might be the wrong case for most applications. It would be better to hold it on your side. 

Also it might not even be necessary to set the savedInstanceState especially when selection may changed for different data...

**Comment by MFlisar** [comment]
I make it more clear with a real example:

I have a class that manages data loading and this class is notified about lifecycle events of the corresponidng view or activity. The class starts loading data asynchronously in constructor and already creates an instance of a `FastAdapter` and then there are following two bigger possible cases:

1) the data is ready, then it is set to the `FastAdapter` instance and then the lifecycle `onCreate` event occurs, passes the bundle to my class and I pass it on to the `FastAdapter` - here everything works as expected.
2) the lifecycle event `onCreate` occurs and passes the bundle to my class, my class has a instance of the `FastAdapter` but this adapter does not have items yet (so the bundle is not used), then some time later, the data finished loading and is set to the adapter - the bundle is lost.

Because of doing data loading asynchronous, there is no guarantee on when the data is available. I'm sure, I get the same data as I had the last time, so I'm sure I want to restore selection state for example.

How would you solve that? I only see the possibility to save the bundle (or at least the adapters saved state in the bundle) and pass it to the adpater after the data is ready.

**Comment by mikepenz** [comment]
Ok for this usecase the best would be to simply hold the `Bundle` somewhere in your activity, until the data is ready. and then you just call `withSavedInstanceState` and it will take care of expandable states + selections)

**Comment by MFlisar** [comment]
Ok - still I don't understand why the adapter cannot extract the data from the bundle (like selected indizes) from the bundle and use this data after the first `setItems` call... (or similar if you see a problem with that)

**Comment by mikepenz** [comment]
In general there is not a problem why the adapter could not do it. It is just about keeping it as clean as possible, and keep functions out which may be only required quite rare, or are doable quite easy. 

(you also just need 4 lines of code or so)

**Comment by MFlisar** [comment]
Imho, this way of data loading should be a common use case ;-)

But I understand you and it's fine, was just a suggestion...

**Comment by mikepenz** [comment]
@MFlisar I am happy bout your suggestions :) It's great to move the lib forward. 
On the other side I still have to make sure it stays light and maintainable ;). the FastAdapter shouldn't feel heavy :D
