### ISSUE TITLE
Disable automatic animation when adding items

### ISSUE THREAD

**Issue by Marty** [mikepenz/FastAdapter#202]
Hi there,

when I'm setting new data on my FastItemAdapter, I clear() the adapter, and add() all new items.
After that I create a DiffResult from the old and the new list and dispatch the updates to the FastItemAdapter.

Now in the app it looks like every item has been newly added (but just one really was), because FastItemAdapter.add already notifies the RecyclerView of the add-actions which triggers the animation.

Is there a way to disable these automatic notifications to trigger them manually?
I don't really want to translate the DiffResult to add() and remove() calls on the FastItemAdapter myself.
Or is there an easier way that I missed (it's late ...).

Thanks in advance, this is a very neat library :)

**Comment by mattiasbe** [comment]
I haven't started to use it yet, on todo list,  but it was implemented/integrated recently in the ItemAdapter/FastItemAdapter I noted.
You can call set(...) directly with the DiffUtil callback as a parameter and it will be handled it seems.
See:

https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L299
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/adapters/FastItemAdapter.java#L153

**Comment by mikepenz** [comment]
@Marty you can already provide the DiffCallback with the set call, which may does the job for you already. 

As an addition. If you do not want animation, but have an animator set. You will have to set the animation time to 0 or remove the animator during the altering of the list. The FastAdapter itself just notifies the RV about the correct changes.

**Comment by mikepenz** [comment]
@mattiasbe thanks for ansewring
