### ISSUE TITLE
Resetting ALL items (invalidate all ViewHolders)

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#205]
My items are able to render in many difference ways. So if the user changes the style, I want that the adapter invalidates all views, then the items will return a new type id and a new layout id and will render in the new style.

Can I achieve this somehow? I thought this may do the trick:

    List<IItem> items = new ArrayList<>(mFastAdapter.getAdapterItems());
    mFastAdapter.setNewList(items);

But this does not work because this way I get all sub items as well, which then will be shown twice.

Can I somehow get the items from the adapter that I have set via `setNewList` without any temp. items? I use a list of expandable items...

**Comment by mikepenz** [comment]
@MFlisar you shouldn't do the above. Just tell the `Adapter` that he has to recreate all views. 
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1416

**Comment by MFlisar** [comment]
To explain what I do:

I change my `LayoutManager` on-the-fly. Your solution works, if I change between different `LayoutManagers` but not if I don't change them.

My item has following code in it:

    @Override
    public int getType()
    {
        FolderStyle folderStyle = LayoutThemeManager.getFolderStyle();
        FolderGridStyle folderGridStyle = LayoutThemeManager.getFolderGridStyle();
        FolderListStyle folderListStyle = LayoutThemeManager.getFolderListStyle();
        boolean wrapInCards = LayoutThemeManager.getFolderStyleWrapInCards();
        boolean overlappingLabels = LayoutThemeManager.getFolderStyleOverlapLabels();

        int type = -1;
        switch (folderStyle)
        {
            case Grid:
                switch (folderGridStyle)
                {
                    case Simple:
                        type = wrapInCards ?
                                (!overlappingLabels ? R.id.fastadapter_folder_grid_default_cards_nooverlap : R.id.fastadapter_folder_grid_default_cards_overlap) :
                                (!overlappingLabels ? R.id.fastadapter_folder_grid_default_nocards_nooverlap : R.id.fastadapter_folder_grid_default_nocards_overlap);
                        break;
                    case Stack:
                        type = wrapInCards ?
                                (!overlappingLabels ? R.id.fastadapter_folder_stack_default_cards_nooverlap : R.id.fastadapter_folder_stack_default_cards_overlap) :
                                (!overlappingLabels ? R.id.fastadapter_folder_stack_default_nocards_nooverlap : R.id.fastadapter_folder_stack_default_nocards_overlap);
                        break;
                    case Tile:
                        type = wrapInCards ?
                                (!overlappingLabels ? R.id.fastadapter_folder_tile_default_cards_nooverlap : R.id.fastadapter_folder_tile_default_cards_overlap) :
                                (!overlappingLabels ? R.id.fastadapter_folder_tile_default_nocards_nooverlap : R.id.fastadapter_folder_tile_default_nocards_overlap);
                        break;
                }
                break;
            case List:

                switch (folderListStyle)
                {
                    case Simple:
                        // zeigt text NIE als overlapping text!
                        type = wrapInCards ? R.id.fastadapter_folder_list_default_cards_nooverlap : R.id.fastadapter_folder_list_default_nocards_nooverlap;
                        break;
                    case Images:
                        type = wrapInCards ?
                                (!overlappingLabels ? R.id.fastadapter_folder_list_images_default_cards_nooverlap : R.id.fastadapter_folder_list_images_default_cards_overlap) :
                                (!overlappingLabels ? R.id.fastadapter_folder_list_images_default_nocards_nooverlap : R.id.fastadapter_folder_list_images_default_nocards_overlap);
                        break;
                }

                break;
        }
        
        return type;
    }

    @Override
    public int getLayoutRes()
    {
        int layout = -1;
        switch (getType())
        {
            case R.id.fastadapter_folder_grid_default_cards_nooverlap:
                layout = R.layout.adapter_folder_grid_item_simple_nooverlap_card;
                break;
            case R.id.fastadapter_folder_grid_default_cards_overlap:
                layout = R.layout.adapter_folder_grid_item_simple_overlap_card;
                break;
            case R.id.fastadapter_folder_grid_default_nocards_nooverlap:
                layout = R.layout.adapter_folder_grid_item_simple_nooverlap;
                break;
            case R.id.fastadapter_folder_grid_default_nocards_overlap:
                layout = R.layout.adapter_folder_grid_item_simple_overlap;
                break;

            case R.id.fastadapter_folder_stack_default_cards_nooverlap:
                layout = R.layout.adapter_folder_grid_item_stack_nooverlap_card;
                break;
            case R.id.fastadapter_folder_stack_default_cards_overlap:
                layout = R.layout.adapter_folder_grid_item_stack_overlap_card;
                break;
            case R.id.fastadapter_folder_stack_default_nocards_nooverlap:
                layout = R.layout.adapter_folder_grid_item_stack_nooverlap;
                break;
            case R.id.fastadapter_folder_stack_default_nocards_overlap:
                layout = R.layout.adapter_folder_grid_item_stack_overlap;
                break;

            case R.id.fastadapter_folder_tile_default_cards_nooverlap:
                layout = R.layout.adapter_folder_grid_item_tile_nooverlap_card;
                break;
            case R.id.fastadapter_folder_tile_default_cards_overlap:
                layout = R.layout.adapter_folder_grid_item_tile_overlap_card;
                break;
            case R.id.fastadapter_folder_tile_default_nocards_nooverlap:
                layout = R.layout.adapter_folder_grid_item_tile_nooverlap;
                break;
            case R.id.fastadapter_folder_tile_default_nocards_overlap:
                layout = R.layout.adapter_folder_grid_item_tile_overlap;
                break;

            case R.id.fastadapter_folder_list_images_default_cards_nooverlap:
                layout = R.layout.adapter_folder_list_item_images_nooverlap_card;
                break;
            case R.id.fastadapter_folder_list_images_default_cards_overlap:
                layout = R.layout.adapter_folder_list_item_images_overlap_card;
                break;
            case R.id.fastadapter_folder_list_images_default_nocards_nooverlap:
                layout = R.layout.adapter_folder_list_item_images_nooverlap;
                break;
            case R.id.fastadapter_folder_list_images_default_nocards_overlap:
                layout = R.layout.adapter_folder_list_item_images_overlap;
                break;

            case R.id.fastadapter_folder_list_default_cards_nooverlap:
                layout = R.layout.adapter_folder_list_item_simple_card;
                break;
            case R.id.fastadapter_folder_list_default_nocards_nooverlap:
                layout = R.layout.adapter_folder_list_item_simple;
                break;
        }
        return layout;
    }

As you can see, I have a lot of styles in there. I want to FORCE the adapter to validate the above two states again, it will return a new `viewType` and therefore a new layout and therefore it will be rebind...

I update my `RecyclerView` like following if the user changes the style:

    	protected void setLayoutManager(boolean reset)
    {
        // LayoutManager und Adapter null setzen!!! Wichtig! Sonst gibt's ein Layout Event
        if (reset)
        {
			// mController.getRV().setAdapter(null);
            mController.getRV().setLayoutManager(null);
        }

        RecyclerView.LayoutManager lm = getLayoutManager();
        if (lm instanceof GridLayoutManager)
        {
            ((GridLayoutManager)lm).setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
                @Override
                public int getSpanSize(int position) {
                    return mFastAdapter.getItem(position) instanceof ItemHeader ? ((GridLayoutManager)lm).getSpanCount() : 1;
                }
            });
        }

        // LayoutManager setzen und dann Adapter wieder setzen
        mController.getRV().setLayoutManager(lm);

        if (reset)
        {
            // setNewList sorgt dafür, dass items als neu deklariert sind, dadurch berechnen sie ihren Typ wieder neu
            // und alles funktioniert perfekt (leider nicht ganz!)
            // Achtung: geht nur, wenn neue IDs zurückkommen, sonst sind items danach doppelt!
			// List<IItem> items = new ArrayList<>(mFastAdapter.getAdapterItems());
			// L.d(this, "Items: " + items.size());
			// mFastAdapter.setNewList(items);
            mFastAdapter.notifyAdapterDataSetChanged();
        }
    }

Any ideas how to solve that?

**Comment by MFlisar** [comment]
PS: I even get an exeption like the following after changing the layouts (I don't change the `LayoutManager`, but `getType`  and `getLayoutRes` will return new values):

    java.lang.NullPointerException: Attempt to invoke interface method 'android.support.v7.widget.RecyclerView$ViewHolder com.mikepenz.fastadapter.IItem.getViewHolder(android.view.ViewGroup)' on a null object reference
	   at com.mikepenz.fastadapter.FastAdapter$OnCreateViewHolderListenerImpl.onPreCreateViewHolder(FastAdapter.java:1690)
	   at com.mikepenz.fastadapter.FastAdapter.onCreateViewHolder(FastAdapter.java:396)
	   at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5836)
	   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5060)
	   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
	   at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
	   at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:541)
	   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
	   at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1193)
	   at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1043)
	   at android.support.v7.widget.GridLayoutManager.scrollVerticallyBy(GridLayoutManager.java:381)
	   at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1596)
	   at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2704)
          ....

Seems like the `mTypeInstances` cache in the `FastAdapter` is not resetted and therefore holds the old type? Could this be the problem?

**Comment by mikepenz** [comment]
@MFlisar oh yes. You are right (as of the deleted comment) you also should map the new possible types: 
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/AbstractAdapter.java#L230

**Comment by MFlisar** [comment]
I had another problem, some buggy optimisation, so that the adapter update was not called if the `LayoutManager` did not change it's type... That's why I deleted my comments.

It's working now, `notifyAdapterDataSetChanged` is enough. I shortly checked the code and saw it is not directly resetting nor updating the map, but at some place this must happen (maybe when it tries to check the map with the new type id and does not find it, it adds it to the map? Did not search further...). Adapter draws the correct layouts after calling `notifyAdapterDataSetChanged` like following:

    rv.setAdapter(null);
    rv.setLayoutManager(null);
    rv.setLayoutManager(...);
    // change settings, so that adapter will return new layouts and type ids...
    rv.setAdapter(fastAdapter);
    fastAdapter.notifyDataSetchanged();

**Comment by mikepenz** [comment]
@MFlisar ok great

**Comment by MFlisar** [comment]
After adding headers and more item types to my adapter, I see, that I do need to remap everything. I'll add the function for it to my pull request when I'll make one again...

**Comment by mikepenz** [comment]
What exactly do you mean with "remap"?

**Comment by MFlisar** [comment]
See the code here (I added those 3 funtions for easy access):

https://github.com/MFlisar/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/adapters/FastItemAdapter.java#L289
https://github.com/MFlisar/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L405
https://github.com/MFlisar/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L393

**Comment by mikepenz** [comment]
Ah I see :D yes there is no such function at the moment.

**Comment by MFlisar** [comment]
Because the type changes as well. New type + new layout id will lead to the problem, that the new type is not mapped yet (item returns a new type, but when it was registered, it returned a different (old) type)...

My code looks like following:
    
    @Override
    public int getType()
    {
        // return unique type, depending on currently selected layout be the user
    }

    @Override
    public int getLayoutRes()
    {
        int layout = -1;
        switch (getType())
        {
            // correctly map the type to the corresponding layout
        }
        return layout;
    }

Now that you say it, maybe it would be better to use one single type and use another variable to select which layout to use? Remapping helps at least...

**Comment by mikepenz** [comment]
@MFlisar ok for those the normal `mapPossibleTypes` method should already do the job. 

In general. It is really important that you do not have multiple layouts for the same type as the `RecyclerView` will internally cache the views themself.
So if you are going to change the layout used, you will also have to change the type.
