### ISSUE TITLE
How to disable blinking while view updated

### ISSUE THREAD

**Issue by meNESS** [mikepenz/FastAdapter#206]
Hi Mike,

I've search about disabling `RecyclerView` blinking animation while item updated and found something but still getting that animation. I want to know, is there something inside Fastadapter to disable that animation or do you know any good and easy solution to achieve that?

**Comment by mikepenz** [comment]
@meNESS the animation is played by the `ItemAnimator` you define. This has nothing to do with the `FastAdapter` 

you can either set `null` as `ItemAnimator` or you set the animation time to 0 milliseconds

**Comment by meNESS** [comment]
@mikepenz I wrote following codes but still blinking!
```
rv.setItemAnimator(null);
RecyclerView.ItemAnimator animator = rv.getItemAnimator();
animator.setChangeDuration(0L);
animator.setAddDuration(0L);
animator.setMoveDuration(0L);
animator.setRemoveDuration(0L);
```

**Comment by sosite** [comment]
Maybe an old answer but if you want to disable **only** item updating animations you can use below code:
```java
((SimpleItemAnimator) recycler.getItemAnimator()).setSupportsChangeAnimations(false);
```
