### ISSUE TITLE
EndlessRecyclerOnScrollListener when user reaches top not bottom

### ISSUE THREAD

**Issue by meNESS** [mikepenz/FastAdapter#208]
Hi Mike,

`EndlessRecyclerOnScrollListener` currently add loading view when user reaches bottom. I want to implement something like that for when user reached top and add loading item at top. How can I do that?

**Comment by mikepenz** [comment]
@meNESS isn't this something similar to `PullToRefresh`?

**Comment by meNESS** [comment]
@mikepenz No, If you use Telegram, you may have seen, you can scroll top to load more previous messages. I want to implement something like that.

**Comment by mikepenz** [comment]
This is currently not in the lib. There is a PR which adds some support for it, but it is not yet in a 100% useable state. You could probably also contribute for this feature. 

https://github.com/mikepenz/FastAdapter/pull/213

**Comment by meNESS** [comment]
@mikepenz I wrote a better one but I make a PR later, thanks anyway 👍

**Comment by mikepenz** [comment]
Awesome :)

**Comment by AndrazP** [comment]
Hi @meNESS, 
is your improvement of `EndlessRecyclerOnScrollListener` available anywhere to see?
Thanks!

**Comment by FabianTerhorst** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnTopScrollListener.java

**Comment by mikepenz** [comment]
Also included in the `FastAdapter` already: https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnTopScrollListener.java
