### ISSUE TITLE
Bug/Question on ignoring consumed flag in adapter internals click listener

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#217]
I've found a thing I don't understand in your code and I think it's a bug: why are you throwing away the consumed flag here:
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L477

If I attach a `OnLongPressListener`, that does not consume the long press and which returns false, the adapters `OnLongPressListener` returns false as well. That's really bad, because this may result in a click...

I can show an example in my pull request that shows you, what will happen: long press an item, fastly release it as soon as the item changes it's selected state on voila, it will immediately call the `OnClickListener` which will unselect the item again...

I would suggest changing the code to `consumed |= mOnLongClickListener.onLongClick(v, relativeInfo.adapter, relativeInfo.item, pos);` so that you at least don't throw away the consumed flag... But maybe skipping the listener if the flag was consumed is even better? Depends on if you ignore the flag on purpose or not...

**Edit**

Just to mention it, here you ignore and override the consumed flag as well:
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L444

I've not found a problem with this case though, so I'm just mentioning it because it fits here and it may be good to think about the reason for this as well...

**Comment by mikepenz** [comment]
@MFlisar the flags are not used for the normal listeners as I did not want to break the behavior when introducing them. perhaps for v2.0.0 I can try to add them there, and test libs like the `MaterialDrawer` if it will have some bad side effects

**Comment by MFlisar** [comment]
Ok. Then still, a custom `onLongClickListener` should NOT clear a true flag just because the custom `onLongClickListener` does not consume the event and return false... This breaks working code (as it will return true without a custom `onLongClickListener` and false otherwise)

**Comment by mikepenz** [comment]
The flags are now no longer ignored. will be live with v2.x
