### ISSUE TITLE
Multi selection - alternative internal structure to remember order

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#219]
I think it would be nice to have the ability to enable something like a sorted selection mode where the selection is saved in a `LinkedHashSet` instead of a  `HashSet`.

I need this because I'm selecting items that are pushed into a group. And the items can be sorted in their group so the first order should be the one in which the items were selected...

**Comment by mikepenz** [comment]
@MFlisar which count of selected items do you expect in general? if the count is not to much you could simple sort them on your side?

**Comment by MFlisar** [comment]
I need the order of selected items. I can't just sort the set as the data for sorting is missing (the order in which the user selected the items)

**Comment by mikepenz** [comment]
the order in which the user selected the items. You get this, by using your `SelectionListener`

**Comment by MFlisar** [comment]
You're right, the `SelectionListener` could be used for this as soon as it's working correctly

**Comment by MFlisar** [comment]
I think about following change:

    private Set<Integer> mSelections;

    public FastAdapter() {
        this(false);
    }

    public FastAdapter(boolean rememberSelectionOrder) {
        setHasStableIds(true);
       if (rememberSelectionOrder)
           mSelections = new TreeSet();
       else
           mSelection = new LinkedHashSet();
    }

What does actually speak against this from your point of view?

*Changes*

`mSelections` is a `TreeSet` or a `LinkedHashSet` (currently it's always a `TreeSet`).

**Comment by mikepenz** [comment]
@MFlisar I am not 100% sure. What speaks against a `TreeSet` in as your perspective? Also I assume in general that selections (the count of those) is quite minimal in comparision to the amount of items displayed in a list. So having the access as fast as possible is more imprtant than probably some overhead in storing this information

**Comment by MFlisar** [comment]
Do you think a small reusable helper class for this functions make sense?

A custom selection listener that is able to save/restore it's state in a bundle and that internally just remembers the selection order?

Or do you think this is just a rare case, that it should stay a (my) user class?

**Comment by mikepenz** [comment]
As of the current moment it seems to be a really rare usecase. There were no other issues opened for this problem. theoretically it would be ok to allow any list which extends `Set` during creation. Would this already solve your requirement?

**Comment by MFlisar** [comment]
That was my suggestion anyways in the beginning... I now did following:

	public class RememberSelectionOrderSelectionListener<T extends IItem> implements ISelectionListener<T>
	{
		private static final String BUNDLE_SELECTIONS = "bundle_ordered_selections";

		private LinkedHashSet<Long> mSelectedIds;

		public RememberSelectionOrderSelectionListener()
		{
			mSelectedIds = new LinkedHashSet<>();
		}

		@Override
		public void onSelectionChanged(T item, boolean selected)
		{
			if (selected)
				mSelectedIds.add(item.getIdentifier());
			else
				mSelectedIds.remove(item.getIdentifier());
		}

		public Set<Long> getSelection()
		{
			return mSelectedIds;
		}

		public Bundle saveInstanceState(Bundle savedInstanceState) {
			return saveInstanceState(savedInstanceState, "");
		}

		public Bundle saveInstanceState(Bundle savedInstanceState, String prefix) {
			if (savedInstanceState != null)
				savedInstanceState.putSerializable(BUNDLE_SELECTIONS + prefix, mSelectedIds);
			return savedInstanceState;
		}

		public RememberSelectionOrderSelectionListener<T> withSavedInstanceState(Bundle savedInstanceState) {
			return withSavedInstanceState(savedInstanceState, "");
		}

		public RememberSelectionOrderSelectionListener<T> withSavedInstanceState(Bundle savedInstanceState, String prefix) {
			if (savedInstanceState != null && savedInstanceState.containsKey(BUNDLE_SELECTIONS + prefix))
				mSelectedIds = (LinkedHashSet<Long>)savedInstanceState.getSerializable(BUNDLE_SELECTIONS + prefix);
			return this;
		}
	}

And just append this listener and use it...

But I would still be happy with the ability to decide myself, if I take the cost of having a `LinkedHashSet` directly in your adapter...
