### ISSUE TITLE
How to get item's ViewHolder (for specific position) from Adapter

### ISSUE THREAD

**Issue by meNESS** [mikepenz/FastAdapter#221]
Hi Mike,

I wrote a`FastItemAdapter` for my own, I need to get an item's ViewHolder (for specific position). How can I achieve this?

```java
for(Item item : getAdapterItems()){
    int pos = getAdapterItems().indexOf(item);
    // ViewHolder holder = item.getViewHolder(); I need something like this
}
```

I know there're two overloads of `getViewHolder()` method but both of them need an argument (`View` and `ViewGroup`) and I don't know what to pass them exactly.

Thanks

**Comment by mikepenz** [comment]
@meNESS that is not possible, as a `ViewHolder` is reused from the `RecyclerView`

You can just hook into the view creation with the listeners and do some custom stuff if needed. But there is no possibility to get a `ViewHolder` by a position. 

What also would be possible is to directly get the `View` from a position, but that only works if the view is currently visible
