### ISSUE TITLE
Only one item can be selected - dont work with expandables.

### ISSUE THREAD

**Issue by kolorszczak** [mikepenz/FastAdapter#225]
I have NavigationView in DrawerLayout which contains RecyclerView with FastAdapter attached. I'm doing my side menu this way because one item has to be expandable (only one) - all other fragments are normal items. I've done some selectors changing background, text and icon color on all of the items, I added withOnlyOneExpandedItem(true) and (almost) everything works fine:

i'm clicking on item 1 -> next item 2 -> next item 3 thus the item 1 is highlighted, then item 2 and then item 3.

What's not good at all:
My expandable item is 3rd in the row and has 2 sub items. If I click on it - expandable item is highlighted, and group is expanded then if i click on item 4 or 5 then my expandable group collapse and my 4th or 5th item is highlighted. To this moment everything works fine. Now if i click on another item, my 4th or 5th item stays hightlighted.

I've attached GIF, which shows everything: im clicking on any item and everything is ok, if i click on 3rd (expandable) item and then on anything except 4th or 5th item everything is ok. If i click on 3rd (expandable) item and then on 4th or 5th - this clicked item stays highlighted.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/15268028/18876371/be5204f0-84c9-11e6-87c0-1230e15bd5e6.gif)

[GIST WITH THE CODE OF EXPANDABLE ITEM](https://gist.github.com/kolorszczak/0e68c3d15430c501e0f8c070e7acd6db)

**Comment by mikepenz** [comment]
@kolorszczak oh interesting. Do your items have identifiers? Could you try to use the alternative state management? `withPositionBasedStateManagement(false)`

**Comment by kolorszczak** [comment]
I added identifiers to all the item and method of which you wrote. Now everything works as it should. Thank you :)

**Comment by mikepenz** [comment]
@kolorszczak awesome. thanks.
