### ISSUE TITLE
Subclasses don't pass up ViewHolder Type to AbstractItem

### ISSUE THREAD

**Issue by ncapdevi** [mikepenz/FastAdapter#226]
If class A is a subclass of AbstractItem, and Class B is a subclass of A, but doesn't explicitly define it's Viewholder(which it really shouldn't have to, since it's a subclass and can use the same view), it will crash.  The problem arises from this function in AbstractItem

```java
/**
     * gets the viewHolder via the generic superclass
     *
     * @return the class of the ViewHolder
     */
    protected Class<? extends VH> viewHolderType() {
        return ((Class<? extends VH>) ((ParameterizedType) getClass().getGenericSuperclass()).getActualTypeArguments()[1]);
    }
```

It's not getting the type arguments.  You can get around this by specifically overriding  this method in class B, and having it return whatever the ViewHolder Class is in class B, but this is a bit annoying. 

I hope this is clear, but let me know if it's not, and I can clarify with actual class examples.

**Comment by mikepenz** [comment]
@ncapdevi for these cases please provide a `ViewHolderFactory`

https://github.com/mikepenz/FastAdapter

**Comment by ncapdevi** [comment]
Absolutely right. Thanks for the quick help.
