### ISSUE TITLE
how can insert an item to adapter by click on button in Viewholder ?

### ISSUE THREAD

**Issue by SeyedAliFarjaD** [mikepenz/FastAdapter#227]
i use withOnBindViewHolderListener in adapter but not work well.
i need to add or remove some items by clicking on button in my list but i cant put code in Adapter_item onBinding
there is anyway to do that
Thanks

**Comment by mikepenz** [comment]
@SeyedAliFarjaD if your item changes. you should handle this via properties in your item or model. and just call the `set` method to change and update the item at this position:
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L489

Or if it stays the same object you can simply just call:
```java
fastAdapter.notifyAdapterItemChanged(position);
```

**Comment by SeyedAliFarjaD** [comment]
there is anyway get items change in activity ?such row 3 had change and i change total number of my title

**Comment by SeyedAliFarjaD** [comment]
Thank you for your answer but i have 1 checkbox. I want all checked items add in another list.
and when items from main list get checked or uncheck item change in another list.

**Comment by mikepenz** [comment]
you just get the items themself from the list by calling `getSelected()` and then you add them in a different adapter.

**Comment by SeyedAliFarjaD** [comment]
ok, but when do that ?
my items select by button in viewholder

**Comment by Rainer-Lang** [comment]
That's up to your usecase.
