### ISSUE TITLE
Drag handle

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#228]
I've adjusted the `IDraggable` interface a little bit to support a drag handle view directly without any user setup. I would look like following:

	public interface IDraggable<T, VH extends RecyclerView.ViewHolder, Item extends IItem> {
		/**
		 * @return true if draggable
		 */
		boolean isDraggable();

		/**
		 * use this method to set if item is draggable
		 *
		 * @param draggable true if draggable
		 * @return this
		 */
		T withIsDraggable(boolean draggable);

		/**
		 * use this method to set the ItemTouchHelper reference in the item
		 * this is necessary, so that the item can manually start the dragging
		 * i.e when a drag icon within the item is touched
		 *
		 * @param itemTouchHelper the ItemTouchHelper
		 * @return this
		 */
		T withTouchHelper(ItemTouchHelper itemTouchHelper);

		/**
		 * this returns the ItemTouchHelper
		 *
		 * @return the ItemTouchHelper if item has one or null
		 */
		ItemTouchHelper getTouchHelper();

		/**
		 * this method returns the drag view inside the item
		 * use this with (@withTouchHelper) to start dragging when this view is touched
		 *
		 * @param viewHolder the ViewHolder
		 * @return the view that should start the dragging or null
		 */
		View getDragView(VH viewHolder);
	}

Because of the 3 extra methods needed, I wanted to ask you if you think that's ok... Alternative, I could offer an extra interface (`ICustomDraggable`???) that extends ` IDraggable`...

Any thoughts? I've implemented a dragging mode like the one described here: https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-6a6f0c422efd#.azde47cow

**Comment by mikepenz** [comment]
@MFlisar I think it makes more sense to split it up, as many items may not have this feature. 
I am not yet sure about the additional interface's name. 

`IExtendedDraggable`, `IDragDraggable`

**Comment by MFlisar** [comment]
The name is my problem as well... If I split it up, I don't know a good name anymore... `Custom` was my idea because of the custom drag initiator...

But having the 3 ideas, I would choose one of the two `ICustomDraggable` or `IExtendedDraggable`... The other one sounds really weird...

**Comment by mikepenz** [comment]
Ok so let's use `IExtendedDraggable` :D

**Comment by MFlisar** [comment]
Already done ;-)
