### ISSUE TITLE
bindView and bindViewPartial

### ISSUE THREAD

**Issue by FuriousSeraphim** [mikepenz/FastAdapter#231]
Hi Mike!
What you think about separate `AbstractItem::bindView(holder, payloads)` into `AbstractItem::bindView(holder)` and `AbstractItem::bindViewPartial(holder, payloads)`?
Main advantage in that when calling bindView, we don't need worry about checking payloads(empty or not) while when calling bindViewPartial, we know that payloads is not empty and a partial update is required. 

Usually i write something like this in that case(partial update) (snippet on Kotlin):
```kotlin
override fun bindView(holder: Holder, payloads: List<Any?>) {
        super.bindView(holder, payloads)

        if (payloads.isNotEmpty() && payloads[0] is Bundle) {
            bindPartial(holder, payloads[0] as Bundle)
            return
        }

        loadAvatar(holder)
        holder.author.text = author
        holder.comment.text = comment
        holder.date.text = date
    }
```

P.S. Sorry for my English :)

**Comment by mikepenz** [comment]
Hello @FuriousSeraphim 

Thank you for your suggestion. 

In general the payloads are already not null so you don't need this check. It is also a problem as this could cause more confusions and problems as it will help. I want to keep the API as simple as possible. It should also be very very similar to the normal adapters api. 

And adding such an method would cause confusions if and if not the method would be called on the initial call or not. 

You can still do this for your project if you create your own `AbstractItem` class which will overwrite the `bindView` and adds the additional abstract method for you
