### ISSUE TITLE
Using existing Data Model as Adapter

### ISSUE THREAD

**Issue by rakesh1988** [mikepenz/FastAdapter#232]
This is an implementation question and not a bug.
I would like to know how to use existing Model Class (used to fetch data via retrofit2) as an adapter. 
One option I can think of is to make my Model Class to extend ```AbstractItem``` . The reason I am hesitant is that the object becomes heavy (my thoughts) when I parcel the object from one activity to other. Please correct me if I am wrong with the above sentence.

Please let me know if there are any other options to implement the same. My objective is not to touch the model that my retrofit is using.

**Comment by mikepenz** [comment]
Check out the `GenericItemAdapter` it is showcased in the `GenericItemActivity` allowing you to use your exisiting model and combine it with an item:

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/GenericItemActivity.java
