### ISSUE TITLE
Changing FooterAdapter dynamically

### ISSUE THREAD

**Issue by rakesh1988** [mikepenz/FastAdapter#233]
I wanted to know if it is possible to change the FooterAdapter dynamically based on business logic. For example let's assume I have Adapters  as follows, ```FooterProgressItem``` , ```FooterNetworkErrorItem``` , ```FooterEndOfDataItem``` I would like to change these footers based on the given situation. What I have understood from this library is, to bind footer, I need to wrap the footer with the actual data adapter and set it as an adapter to the recyclerview. 

    someRecyclerView.setAdapter(progressItemFooterAdapter.wrap(fastAdapter));

How should I change the adapters dynamically??

**Comment by mikepenz** [comment]
@rakesh1988 I do not understand why you need to change the footers? Just set and switch out the items in your footer. A adapter does not have to be strictly typed. You can have an adapter which goes against `IItem`

The sample app showcases many uses of the adapter with multiple item types in one adapter. 

You will then just add the items to the footer and depeding on the current case you remove them and readd them to the adapter. 

Also one hint. Why do you add `Footer` to your items? It makes more sense to keep them general, and reuse them wherever possible

**Comment by rakesh1988** [comment]
Sorry I did not understand how to implement "set and switch out the items in your footer". As per my understanding once I set the footer, the getType() would  return the same layout every time. How can I show different layouts on need basis? Sorry if this question looks dumb.

**Comment by mikepenz** [comment]
@rakesh1988 perhaps you misunderstand how a `RecyclerView` works or how you add / remove items.

You have items. Which are meant to display one type of information. You can then provide this item to the `FooterAdapter` with `.add()` you can remove and readd this item at anytime. That's the same with the others.
