### ISSUE TITLE
Handling Click event on FooterAdapter

### ISSUE THREAD

**Issue by rakesh1988** [mikepenz/FastAdapter#236]
Hi Mike, 
Thank you for your quick replies for all my queries. I was finally able to switch the footer items based on my business logic.
I have another question on handling click event on header/footer adapters 

How should i return the Correct ViewHolder from the ```onPreCreateViewHolder()``` method? 
```return fastAdapter.getTypeInstance(viewType).getViewHolder(parent); ``` always returns the fastAdapter's viewholder.

My code snippet is as below
```
FooterAdapter<IItem> genericFooterAapter = new FooterAdapter<>();
mRecyclerView.setAdapter(genericFooterAapter.wrap(fastAdapter));
mClickListenerHelper = new ClickListenerHelper<>(fastAdapter);

fastAdapter.withOnCreateViewHolderListener(new FastAdapter.OnCreateViewHolderListener()
{
	@Override
	public RecyclerView.ViewHolder onPreCreateViewHolder(ViewGroup parent, int viewType)
	{
		Timber.d("creating a recycler view holder");
		return fastAdapter.getTypeInstance(viewType).getViewHolder(parent);
	}
	@Override
	public RecyclerView.ViewHolder onPostCreateViewHolder(RecyclerView.ViewHolder viewHolder)
	{
		if (viewHolder instanceof FooterNetworkErrorItem.ViewHolder)
		{
			mClickListenerHelper.listen(viewHolder,
					((FooterNetworkErrorItem.ViewHolder) viewHolder).btnReload,
					new ClickListenerHelper.OnClickListener<FooterNetworkErrorItem>()
					{
						@Override
						public void onClick(View v, int position, FooterNetworkErrorItem item)
						{
							Toast.makeText(getActivity(), "reload clicked", Toast.LENGTH_SHORT).show();
						}
					}
			);
		}
		return viewHolder;
	}
});
```

**Comment by mikepenz** [comment]
@rakesh1988 what's wrong with returning it as shown above? `GetViewHolder` will create a new viewholder for the given `viewType` which is the correct behavior

**Comment by rakesh1988** [comment]
When my ```RecyclerView``` is trying to show the ```FooterAdapter```, it gives a casting exception. This is because ```return fastAdapter.getTypeInstance(viewType).getViewHolder(parent);``` always returns item of type what ever was bound to ```fastAdapter``` object. How can I return the ```ViewHolder``` of my ```FooterAdapter```

**Comment by mikepenz** [comment]
@rakesh1988 which type does your `FastAdapter` have? If an item handling adapter has a different type your `FastAdapter` must also use `IItem`

**Comment by rakesh1988** [comment]
I think I found out what I was looking for...

```
	@Override
	public RecyclerView.ViewHolder onPreCreateViewHolder(ViewGroup parent, int viewType) {
		switch (viewType) {
			case R.id.footer_type:
				//return footer view holder
			default:
				//return default item type
		}
	}
```

**Comment by mikepenz** [comment]
If it works for you it's fine. 

But I don't think this is necessary. the fastAdapter.getTypeInstance will always return the correct ViewHolder based on the `viewType` accross all `ItemAdapter`s provided.

**Comment by mikepenz** [comment]
That's even the default implementation if you don't provide a OnCreateViewHolderListener:

https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1764

But if the above works for you it's fine ;)
