### ISSUE TITLE
how know my fastadapter is in fillter ?

### ISSUE THREAD

**Issue by SeyedAliFarjaD** [mikepenz/FastAdapter#238]
There is any way to know list is in filltering ?
i want to add item to list only when user close all search.
Thanks

**Comment by mikepenz** [comment]
@SeyedAliFarjaD the easiest is to just get the `ItemFilter` from the `ItemAdapter` and check if the `constraint` is `null` or `empty`

**Comment by mikepenz** [comment]
something like this
`TextUtils.isEmpty(((ItemAdapter.ItemFilter)fastItemAdapter.getItemFilter()).getConstraint().toString())`

**Comment by SeyedAliFarjaD** [comment]
Thank you.
