### ISSUE TITLE
unbind with ButterKnife

### ISSUE THREAD

**Issue by markus2610** [mikepenz/FastAdapter#239]
Is there a special reason why unbind is not used in the sample code?

**Comment by mikepenz** [comment]
@markus2610 I think unbind is for a bit a different usecase. In our case in `unbind` we just reset the views to the values we want them by default

**Comment by FabianTerhorst** [comment]
There is no reason for unbinding butterknife, because the viewholder is reused, even when an item that is using this viewholder got recycled.
