### ISSUE TITLE
AbstractItem error

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/FastAdapter#24]
I'm using your simple implementation, but when I rename the class I get this error on bindView method.
`'bindView(ViewHolder)' in 'com.test.orion.sample.HistoryItem' clashes with 'bindView(VH)'` in
`'com.mikepenz.fastadapter.items.AbstractItem'`; both methods have same erasure yet neither overrides the other. How can I solve this?

**Comment by mikepenz** [comment]
@EpsilonOrionis could you please provide some code? Which version are you using?

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java#L93
The `bindView()` takes the `ViewHolder` type which was defined for the `AbstractItem<YourItem, YourViewHolder>` 
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java#L27

So you don't have to cast the `RecyclerView.ViewHolder` to the specific `ViewHolder` used for this item

**Comment by EpsilonOrionis** [comment]
I'm using your sample, still that message...

**Comment by FabianTerhorst** [comment]
@EpsilonOrionis the readme is not updated to version 0.9.0 . Should be ```@Override
    public void bindView(final ViewHolder holder) {``` instead of ```@Override
    public void bindView(final RecyclerView.ViewHolder holder) {```

**Comment by EpsilonOrionis** [comment]
It works, thank u :+1:
