### ISSUE TITLE
Interactive items and state retention in FastAdapter

### ISSUE THREAD

**Issue by gotev** [mikepenz/FastAdapter#240]
Hi Mike and thank you for this huge time-saver!
I've digged a bit in the examples and issues here, but I haven't found a recommended way to have "interactive" items in my list which retains their state. My list has multiple item types. I'll make an example:

I have a model like this:
```java
public class MyModel {
    private String title;
    private boolean actionPerformed

    // getters and setters
}
```

Then I have a layout for each item like this:
![item](https://cloud.githubusercontent.com/assets/16792495/19234254/ab0091f2-8eea-11e6-9bbf-4dcefdaba270.png)

And the FastAdapter item implementation:
```java
public class MyModelItem extends AbstractItem<MyModelItem, MyModelItem.ViewHolder> {

    private MyModel model;

    public MyModelItem(MyModel model) {
        this.model = model;
    }

    @Override
    public int getType() {
        return R.id.myitem;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.myitem;
    }

    @Override
    public void bindView(ViewHolder holder, List payloads) {
        super.bindView(holder, payloads);
        holder.title.setText(model.getTitle());

        holder.button.setVisibility(model.isActionPerformed() ? View.GONE : View.VISIBLE);
    }

    protected static class ViewHolder extends RecyclerView.ViewHolder {
        TextView title;
        Button button

        public ViewHolder(View itemView) {
            super(itemView);
            title = (TextView) itemView.findViewById(R.id.title);
            button = (Button) itemView.findViewById(R.id.button);

            button.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    // do something and notify the model that an action was
                    // performed on this item
                }
            });
        }
    }
}
```
Which is the best way in FastAdapter to notify the model that there were changes, from a click performed in an item's view holder listener? In this example, I need to set `actionPerformed = true` on the model item in fast adapter after that the click was performed, to know whether or not to show the button inside the item.

Also, are there better ways to implement click listeners inside each view holder, which performs different things based on the view I've clicked on?

**Comment by mikepenz** [comment]
@gotev in general you should not put listeners in the viewHolder as you do above, as we do not have access to the `item`s inside the adapter. 

Instead we do this when a `ViewHolder` is created. 
See this answer here: http://stackoverflow.com/a/39845532/325479

This is also the proper way of doing the listener at the moment. But the plan is to simplify this for v2.x.x

**Comment by gotev** [comment]
@mikepenz thank you for the quick response. I've already seen that post on stackoverflow, but my problem is that I have complex items inside the fast adapter, and I also have many different kinds of items, so the above method is not suitable in my case, because I need to do different things based on the view on which I click on. Example:
![example](https://cloud.githubusercontent.com/assets/16792495/19243120/8d7e8f86-8f16-11e6-9644-0164e92a7d88.png)

If you have further suggestions, you're welcome. Also, can you tell me what you intend to do to simplify this for 2.x.x? Maybe I can help with some ideas or implementations

**Comment by mikepenz** [comment]
You can see the changes here: https://github.com/mikepenz/FastAdapter/pull/241/files

**Comment by Rainer-Lang** [comment]
@mikepenz So and what could I do if I want my ClickListener within my item?
And what's about: https://github.com/mikepenz/FastAdapter/blob/3b5f1af9702762e84cef8e6b9d8abcbf93fd1958/app/src/main/java/com/mikepenz/fastadapter/app/items/SwipeableItem.java#L169

Is there already something in v2 to look at?

**Comment by mikepenz** [comment]
For the `SwipeableItem` it is fine as it is just used internally, no need to externally access this listener. 

You can have the implementation of this `Event` inside your item, and just pass it outside. This will only work if you do not have to access anything outside of this item, and just do internal stuff. I have adjusted the PR and changed this
