### ISSUE TITLE
Update adapter items with multiple ViewHolders

### ISSUE THREAD

**Issue by rafakob** [mikepenz/FastAdapter#244]
[Question]

Hello Mike!
I love FastAdapter but I feel like I'm not using it effectively. I have doubts regarding a usecase where you have a list of multiple types and you want to update it partially with new data set. Example code:

```java
// ListActivity.java

FastItemAdapter<IItem> adapter = new FastItemAdapter<>();

// Download initial data from webservice using Rx Retrofit
void onDataDownloaded(...){
    adapter.add(new TitleItem("Section 1"));
    adapter.add(new ItemTypeA(...));
    adapter.add(new ItemTypeA(...));

    adapter.add(new TitleItem("Section 2"));
    adapter.add(new ItemTypeB(...));
    adapter.add(new ItemTypeB(...));

    adapter.add(new TitleItem("Section 3"));
    adapter.add(new ItemTypeC(...));
    adapter.add(new ItemTypeC(...));
}
```

Let's say I refresh data using `SwipeRefreshLayout`. I may receive a new data set where some of the old items where changed, some removed, and some added. I have function that scans items one by and add new ones under the right section. I'm assuming it may be replaced with `set(List<Item> items, final DiffCallback<Item> callback, boolean detectMoves)`. Is there any example how to use DiffUtil with payloads?

And what if I have a separate endpoint that returns only items `ItemTypeB` which are in `Section 2`. How to effectively (and smoothly) apply those changes to the whole list?

**Comment by mikepenz** [comment]
@rafakob I am not yet 100% sure what you mean with `changes to the whole list` 

If you have an endpoint which gives you items for section 2, the best would be that you just remove  the item range from section 2 -> section 3 and readd the new list of items at this position. This won't change any other items other than those. 

For the rest. If you refresh the whole list, and get a `new` (new is important, don't update the items in the list you set in the beginning of the adapter, as it will not allow the diffutil to work), and then you just use the `set` method which takes the `DiffCallback`. Implement the methods, and you are good to go. The interface of this is very similar to the one from the `DiffUtils` themself so just look up totorials regarding this one. Nothing special to handle here

**Comment by rafakob** [comment]
> If you have an endpoint which gives you items for section 2, the best would be that you just remove the item range from section 2 -> section 3 and readd the new list of items at this position. This won't change any other items other than those.

Yes, that's what I'm currently doing (remove items from section 2 and add there new ones). The problem is that I have to iterate through the whole adapter and find where section 2 starts and ends (using `instanceof`). I thought about adding expandable interface to `TitleItem` and just replace subitems there (`TitleItem` would be always expanded). What do you think about it?



> For the rest. If you refresh the whole list, and get a new (new is important, don't update the items in the list you set in the beginning of the adapter, as it will not allow the diffutil to work)

Let's take for instance a download manager application. On main screen you have a list of files that you are downloading and you have to automatically refresh it every 5 seconds (to update download percentage value). Should I use `adapter.set(List)` on every refresh? I want to avoid "blinking" effect, on change animation. Also scroll position should be retained on each refresh (don't scroll at the top of the list).

**Comment by mikepenz** [comment]
@rafakob 

for the first part. Yeah I think having this solved via expandables would work. Or you just remember the amount of items you have per section. and then just remove the specific range
(By the way I think the `HeaderHelper` could simplify the grouping for you: https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/HeaderHelper.java)

For the later. It depends. You can have 2 different cases here.
1.) You know which item (so which identifier) was changed. So I would recommend just change the object (if you have the same reference which as in the list) and then call `notifyAdapterItemChanged` (https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1617)  for this element. You can pass any payload you want, and just hae to react in the `bind` method for it, and may change only a specific view value
2.) As an alternative if you always get the full list (make sure it is not the same list (talking about its reference) which was added to the adapter before. And then use the `set` method using the `DiffCallback` in there implement the methods, and the rest will be handled for you. it will make sure the correct notify methods are called for the correct positions

**Comment by rafakob** [comment]
Ok, thanks for the tips! 👍
