### ISSUE TITLE
notifyDatasetChanged

### ISSUE THREAD

**Issue by dexion** [mikepenz/FastAdapter#245]
Hi!
I have recyclerview with
```JAVA
private FastAdapter<GenericShiftTypeItem> fastAdapter;
GenericItemAdapter<ShiftType, GenericShiftTypeItem> itemAdapter;
```
in ListActivity code I notify
```JAVA
    @Override
    protected void onResume() {
        super.onResume();
        itemAdapter.notifyDataSetChanged();
    }
```

I have other EditActivity for create\edit new entities. If I press arrow on actionBar marked as `getSupportActionBar().setDisplayHomeAsUpEnabled(true);` all work fine. If I press back button on my phone function `onResume` fired but dataset not changed (existed entities reloaded and all changes showed, but new entity not shown in list. When I reload activity all entities shown right). What I do wrong?

**Comment by mikepenz** [comment]
@dexion please use the `FastAdapter` specific notify methods:

`notifyAdapterDataSetChanged()`

**Comment by dexion** [comment]
I tried, this has no effect in my case.

**Comment by mikepenz** [comment]
So maybe you have some code in your activity breaking the logic. 

Or perhaps the list is not yet refreshed. Also you should just use the `set` methods on the `GenericItemAdapter` which allows you to set a new list

**Comment by dexion** [comment]
I think if I use `fastAdapter.notifyAdapterDataSetChanged();` listView should be refreshed automatically - it is a basic logic. Why I should reseting all items in listView by `GenericItemAdapter#set`?

> if you know the position of the changed element

Changed element shown right. New created element doesn't showed. It is always last element in listview.

If you want, you may try my app [ListShiftType](https://github.com/dexion/SalaryCounter/blob/master/app/src/main/java/com/snake/salarycounter/activities/ShiftType/ListShiftTypeActivity.java#L61) If you will try, you should turn off `Instant run` in Android Studio due some problems in libraries.

Scripts:
`A` 
1. add new entity (just click FAB +), no need other actions
2. Click back arrow in top left corner toolbar
All works fine.

1. add another new entity (just click FAB +)
2. Click back arrow in your phone (hard button or system arrow at bottom)

List view should be refreshed but it doesn't.

`B`
1. Click any item in list view. New activity will be shown.
2. Change something, like `name`
3. Click back arrow in top left corner toolbar
All works fine. Item show changed info

1. Click any item in list view. New activity will be shown.
2. Change something, like `name`
3. Click back arrow in your phone (hard button or system arrow at bottom)

All works fine. Item show changed info

**Comment by mikepenz** [comment]
What happens in the `onBackPressed` or `onOptionsItemClick` listeners in the activity where you add the new item?
You have to somewhere add the new item to the `Model`s / `Item`'s which are currently displayed inside the list?

**Comment by dexion** [comment]
I create new item: 
[call activity with params from `ListActivity`](https://github.com/dexion/SalaryCounter/blob/master/app/src/main/java/com/snake/salarycounter/activities/ShiftType/ListShiftTypeActivity.java#L136) 
[save new entity into DB in `ShowActivity`](https://github.com/dexion/SalaryCounter/blob/master/app/src/main/java/com/snake/salarycounter/activities/ShiftType/ShowShiftTypeActivity.java#L42)
after that if click back arrow in toolbar - work
after that if click back button - doesn't work (I can't figure out difference between back arrow in toolbar methods and back button methods)
[try reload adapter `onResume`](https://github.com/dexion/SalaryCounter/blob/master/app/src/main/java/com/snake/salarycounter/activities/ShiftType/ListShiftTypeActivity.java#L63)

`ShowActivity` didn't have any overriden functions like `onBackPressed` or `onOptionsItemClick`

**Comment by dexion** [comment]
Ok. If click back arrow calls `onCreate` `ListActivity` so adapter fully refill. If click back button calls `onResume` `ListActivity` so adapter change only already added items. I think this is not quite right, but i understand. In my case I should clear and fully refill adapter `onResume`, no other choice, isn't it?

**Comment by mikepenz** [comment]
@dexion if you can not find out or notify the main activity about which items you have changed, the best is to get the list of items new, and use the method to set a new list of items. (The best would probably be the one with the DiffCallback, so the UI just updates new / modified / removed items)

**Comment by dexion** [comment]
Thanks for help!
