### ISSUE TITLE
Java Interoperability Policy for Major Version Updates for version 2.0

### ISSUE THREAD

**Issue by ravidsrk** [mikepenz/FastAdapter#246]
It would be great if you can adopt package structure using http://jakewharton.com/java-interoperability-policy-for-major-version-updates/

**Comment by mikepenz** [comment]
@ravidsrk there are no plans to change the package name. Migration steps will be documented in a separate readme and in the release notes. Also the changes required will be rather easy to implement. 

It also does not make sense to have v1 and v2 at the same time inside the project. 

Thanks for your suggestion
