### ISSUE TITLE
bindView(VH holder, List payloads) makes task error: References to generic type List<E> should be parameterized

### ISSUE THREAD

**Issue by jp1017** [mikepenz/FastAdapter#247]
This error created when using greenDAO 3.2.0 and FastAdapter 1.8.2

May add generics or other solves.

**Comment by mikepenz** [comment]
@jp1017 please add more details. Sample showing the issue? adding some code?

**Comment by jp1017** [comment]
## gradle：

```
classpath 'com.android.tools.build:gradle:2.2.1'
classpath 'org.greenrobot:greendao-gradle-plugin:3.2.0'
```

```
compile 'org.greenrobot:greendao:3.2.0'
compile('com.mikepenz:fastadapter:1.8.2@aar') {
    transitive = true
}
compile 'com.mikepenz:fastadapter-extensions:1.8.0@aar'
compile 'com.mikepenz:materialize:1.0.0@aar'
```

## Entity:

```
@Entity
public class TradeItems extends AbstractItem<TradeItems, TradeItems.ViewHolder> {
    @Id
    private Long id;
    public int no;            
    public String beginTime;      // yyMMddHHmm

    @Generated(hash = 44254941)
    public TradeItems(Long id, int no, String beginTime) {
        this.id = id;
        this.no = no;
        this.beginTime = beginTime;
    }

    @Generated(hash = 84211957)
    public TradeItems() {
    }

    @Override
    public int getType() {
        return R.id.ll_trade;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_rv_trade;
    }

    @Override
   public void bindView(ViewHolder holder, List payloads) {
        super.bindView(holder, payloads);
        holder.mTvNo.setText(no + "");
        holder.mTvTime.setText(beginTime);
    }

    public String getBeginTime() {
        return this.beginTime;
    }

    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    public int getNo() {
        return this.no;
    }

    public void setNo(int no) {
        this.no = no;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    protected static class ViewHolder extends RecyclerView.ViewHolder {
        protected final View view;
        @BindView(R.id.tv_item_trade_no)
        TextView mTvNo;           
        @BindView(R.id.tv_item_trade_time)
        TextView mTvTime;        

        public ViewHolder(View itemView) {
            super(itemView);
            view = itemView;
            ButterKnife.bind(this, view);
        }
    }
}

```

**Comment by mikepenz** [comment]
@jp1017 any other libs like the `MaterialDrawer` or the `AboutLibraries` in use which may refer to an older version of the `FastAdapter`?

**Comment by jp1017** [comment]
Neither MaterialDrawer nor AboutLibraries. May be generics of the List:

```
    @Override
    public void bindView(ViewHolder holder, List payloads) {
        super.bindView(holder, payloads);
        holder.mTvNo.setText(no + "");
        holder.mTvTime.setText(beginTime);
    }
```

**Comment by mikepenz** [comment]
@jp1017 it is no problem in the sample's. As I also use it that way, and the adapter interface is the same. 

You can try `List<Object> payloads` if you want

**Comment by jp1017** [comment]
> You can try List<Object> payloads if you want

I try this, but how to callSuper:

```
    @Override
    @CallSuper
    public void bindView(VH holder, List payloads) {
        //set the selected state of this item. force this otherwise it may is missed when implementing an item
        holder.itemView.setSelected(isSelected());
        //set the tag of this item to this object (can be used when retrieving the view)
        holder.itemView.setTag(this);
    }
```

**Comment by mikepenz** [comment]
@jp1017 that's what I meant. the List without any types is correct. It works in the smaple etc. there must be some other issues. 

Can you please provide a small sample app which has this issue. so I can compile and test myself?

**Comment by jp1017** [comment]
@mikepenz https://github.com/jp1017/FastAdapterIssue/issues/2

**Comment by mikepenz** [comment]
@jp1017 after looking at the code. 
It is no issue of the `FastAdapter` it is a limitation of the `GreenDAO` library you use. 
I suggest you, to use the `GenericItemAdapter` instead, which allows you to have a model class and a separate item class.

Check out:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/GenericItemActivity.java

Or:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeGenericItemActivity.java

**Comment by jp1017** [comment]
@mikepenz 
I got it.
Seperate model and item, it certainly works.
Thanks you.

**Comment by jp1017** [comment]
@mikepenz 
But, how to click the item?

>mFastAdapter.withOnClickListener 

can't make it.

**Comment by mikepenz** [comment]
@jp1017 I do not understand what you meant. The `GenericFastItemAdapter` has the same methods as the `FastItemAdapter`

**Comment by jp1017** [comment]
`GenericFastItemAdapter` makes it.

Thanks.
