### ISSUE TITLE
Parceler with fastadapter item

### ISSUE THREAD

**Issue by sumitsahu2207** [mikepenz/FastAdapter#248]
Hi Mike,

Hope you're doing well.

I'm facing issue when sending fastadapter item object(which is extending Abstractitem) to fragment using Parceler. As I understand, parcel doesn't send inherited objects. So I guess, this may be causing issue.

Please correct me, I may be asking silly question. 

If I've to use any generic item or so, how do I do that. Currently, I need this for Expandable item functionality

Thanks in advance.

Best Regards,
Sumit

**Comment by Rainer-Lang** [comment]
@sumitsahu2207 I only could take about myself.... But "normally" I use GenericItems (there are samples in this repo here), so I split my View-item and Model-item. My models are AutoValue classes ( https://github.com/google/auto/tree/master/value ) with usage of Auto-Value-Parcel ( https://github.com/rharter/auto-value-parcel ).
Maybe you could give some code examples what are you doing and where the problem occurs.

**Comment by mikepenz** [comment]
@sumitsahu2207 I also recommend to implement it via the `GenericItems` just take a look at the samples for implementations which split model and item apart. 

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/GenericItemActivity.java

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeGenericItemActivity.java
