### ISSUE TITLE
How to assume whether the Adapter contains one item.

### ISSUE THREAD

**Issue by jp1017** [mikepenz/FastAdapter#251]
I used this method:

```
mItemAdapter.getAdapterPosition(addItem)
```

But, it always return -1. so, any ideas? Thank you.

**Comment by Rainer-Lang** [comment]
What do you mean with "addItem"? 
First add your item, then retrieve the position.

**Comment by jp1017** [comment]
Add item first??

I want to add one item this way: if Adapter doesn't contain this item, then add the item.

**Comment by mikepenz** [comment]
@jp1017 the above method is correct, but I assume your item does not have an `identifier` set which is required to search if the same is already in the adapter

**Comment by jp1017** [comment]
@mikepenz 

what `identifier`?  `filter` maybe ??

I add this method:

```
mItemAdapter.withFilterPredicate
```

but don't work.

**Comment by mikepenz** [comment]
`withIdentifier` on the item. as shown here:
https://github.com/mikepenz/FastAdapter/blob/8f2c8e37bf81238035cd84989b19b1b5527f7534/app/src/main/java/com/mikepenz/fastadapter/app/dummy/ImageDummyData.java#L17
