### ISSUE TITLE
How to highlight one item at a time of fastadapter

### ISSUE THREAD

**Issue by sumitsahu2207** [mikepenz/FastAdapter#252]
Hi Mike,

How can we highlight one item at a time.
That means deselect all other items of adapter and select(highlight) currently selected item

Thanks,
Sumit

**Comment by sumitsahu2207** [comment]
I'm just trying to do something like ImageList Sample in which 'Heart' icon gets selected by clicking it. But in that sample all Heart icon's of items can be selected or deselected all together.

I need to select and highlight one image at a time and deselect others.

**Comment by mikepenz** [comment]
@sumitsahu2207 check out the `RadioButton` sample which could be the thing you are searching for

**Comment by sumitsahu2207** [comment]
oh, ok. Let me see If that can fit in there. Thanks

Also would you be able to tell me, how should we save state of these selected items once we move to other activities and come back again.

I'm doing fastAdapterService.saveInstanceState(outState); in onsaveInstancestate but that doesn't restore items selection state.

**Comment by mikepenz** [comment]
@sumitsahu2207 do you have this line too: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SampleActivity.java#L172 ?
