### ISSUE TITLE
Raw type usage

### ISSUE THREAD

**Issue by WonderCsabo** [mikepenz/FastAdapter#253]
`IItem` currently has this method:
```java
void bindView(VH holder, List payloads);
```

The second parameter is a raw type, because no generic type parameter is given. This is bad practice, and will also result in warnings when compiling with `-Xlint:all` flag. The method signature should be this, like [the method](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#onBindViewHolder(VH, int, java.util.List<java.lang.Object>)) in `RecyclerView.Adapter`:

```java
void bindView(VH holder, List<Object> payloads);
```

**Comment by mikepenz** [comment]
will be fixed in the next method

**Comment by WonderCsabo** [comment]
Thanks! However there are still [lots if places](https://github.com/mikepenz/FastAdapter/search?p=3&q=List+payloads&utf8=%E2%9C%93) where you should fix this. Most importantly, `IItem` and its subtypes (i was actually referring to those in the OP).

**Comment by Rainer-Lang** [comment]
Fid you try v2?

**Comment by WonderCsabo** [comment]
@Rainer-Lang i did, but i do not understand why are you asking this here?

**Comment by Rainer-Lang** [comment]
In v2 there are really a lot of changes. I don't know exactly which ones.

**Comment by WonderCsabo** [comment]
Yes, i know, and my comment is valid.

**Comment by Rainer-Lang** [comment]
@WonderCsabo OK. Then let's wait for Mike. :)

**Comment by mikepenz** [comment]
@WonderCsabo I will have to take a closer look at all of them. but yeah you may be right. 

I also prepare for the release of 2.1 which will introduce a even smaller core dependency. 

You may also open a PR to change this?

**Comment by WonderCsabo** [comment]
Yep, I can implement this.

**Comment by WonderCsabo** [comment]
However i can only start on Wednesday, i do not know when do you want to release 2.1.
