### ISSUE TITLE
Sample CheckBoxSampleActivity replace withOnClickListener  with withSelectionListener

### ISSUE THREAD

**Issue by tengma** [mikepenz/FastAdapter#254]
Thank your for this great work. Following your sample,  it seems to me that we should use withSelectionListener instead of withOnClickListener  here.  Line 52.

**Comment by mikepenz** [comment]
@tengma it depends on what you are going to implement. 

this sample has a click listener on the checkbox which will trigger the onItemClick event: 
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/CheckBoxSampleItem.java#L143

So in this case it is a bit different. It always really depends on your usecase

**Comment by tengma** [comment]
Thank you, I may not understand completely at first, but CheckBoxClickEvent  works fine for me.
