### ISSUE TITLE
Multiple layouts for a single item

### ISSUE THREAD

**Issue by ncapdevi** [mikepenz/FastAdapter#255]
Hopefully a quick question, but just wanted your opinion on this. What is the best way to have multiple layouts for a single item? More specifically, it's easy enough to have a switch statement within the getLayoutRes() function, and return a different layout given some sort of criteria, but in this situation is it best to also use that same switch statement to provide a different int in the getType or is that not necessary/preferred?

E.G.,  If I have layouts A, B, and C, when using those layouts, should I also return a_id, b_id, and c_id respectively in getType()?

Thanks for your work and help.

**Comment by FabianTerhorst** [comment]
Should the items that have different layouts be the same recyclerview, or is it a static setting for example that is affecting all items?

**Comment by FabianTerhorst** [comment]
An example for an static setting would be to override the adapter and set the correct adapter for the correct setting 
``` 
public class FastSmallItemAdapter<Item extends IItem> extends FastItemAdapter<Item> {

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return ((AbstractItem) getTypeInstance(viewType)).getViewHolder(LayoutInflater.from(context).inflate(getLayoutRes((getTypeInstance(viewType)).getLayoutRes()), parent, false));
    }

    private static int getLayoutRes(@LayoutRes int layoutRes) {
        if (layoutRes == R.layout....)
            return R.layout....;
        else...
        return layoutRes;
    }
}
```

**Comment by ncapdevi** [comment]
It's actually something that happens per Item, so an example of it would be

`    @Override
    public int getType(){
        if(mAttributes != null){
            if(mAttributes.sStyle != null){
                switch(mAttributes.sStyle){
                    case STYLE_VOLUME:
                        return R.id.row_player_controls_volume;
                    case STYLE_PAUSE_SKIP:
                        return R.id.row_player_controls_pause_skip;
                }
            }
        }
        return R.id.row_player_controls;
    }

    @Override
    public int getLayoutRes(){
        if(mAttributes != null){
            if(mAttributes.sStyle != null){
                switch(mAttributes.sStyle){
                    case STYLE_VOLUME:
                        return R.layout.row_player_controls_volume;
                    case STYLE_PAUSE_SKIP:
                        return R.layout.row_player_controls_pause_skip;
                }
            }
        }
        return R.layout.row_player_controls;
    }
`

My question is 1, is this an acceptable way of doing it, and also is the getType() override necessary/correct.

**Comment by FabianTerhorst** [comment]
The item should have an different id, but when you don´t override the id this shouldn´t be a problem for your case. You should also use different types when you use different layouts for the same item.

**Comment by FabianTerhorst** [comment]
> is this an acceptable way of doing it?
I had created a superclass with the bind method and two subclasses that are overriding the type and layout.

**Comment by ncapdevi** [comment]
Sorry, I think I'm a little confused by your first sentence. I am providing a different ID  in the getType method, thus those should be recognized as different types, correct?  Those different types should correspond to grabbing the correct layout resource, per the code above.

 For the second sentence, It looks like I am providing both different types and layouts even though the class is the same.

**Comment by ncapdevi** [comment]
To your second post. That is essentially the same thing that I'm doing here, just in a single class, correct?

**Comment by FabianTerhorst** [comment]
yes, its the same. Just a little bit cleaner. When im talking about the id, im talking about the identifier and with type the typeid.

**Comment by ncapdevi** [comment]
Okay, just wanted to make sure and get total clarification.  I would agree that it's a bit cleaner, however in my case, I won't know which subclass it's going to be until the parent class is actually created, so I am forced to do it this way (unless I make a structural change.)  Thanks for your feedback and help.
