### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by MatthieuFereyre** [mikepenz/FastAdapter#257]
Hello,

I have a java.lang.ClassCastException on item click with a footer adapter.

Wrap a fastAdapter with a footer adapter and register for click (withOnClickListener).
Item for fastAdapter is type Item1 and footer type is Item2. No inheritance between them.

If you click on the footer you have an exception, cannot cast Item2 to Item1.

Thanks for your help.

**Comment by mikepenz** [comment]
Your `FastAdapter` needs to have the parent type of all sub-adapters defined. 

So if you have a `NormalItem` and a `FooterItem` and both implement the `IItem` interface. the `FastAdapter` needs to have the type `IItem` defined, and the `FooterAdapter` can have `FooterItem`,  and the `ItemAdapter`, `NormalItem`

**Comment by MatthieuFereyre** [comment]
A big thanks ! It works perfectly !
