### ISSUE TITLE
inject dependencies with dagger2 into GenericAbstractItem

### ISSUE THREAD

**Issue by stonecold123** [mikepenz/FastAdapter#259]
How can I inject dependencies into `GenericAbstractItem`? The dependencies are usually injected into the constructor of a class but with `GenericAbstractItem`,  there is no way to pass `Context` to the constructor so it doesn't work.

````
public class SimpleItem extends GenericAbstractItem<ItemModel, ItemFastAdapter, ItemFastAdapter.ViewHolder> {

    @Inject
    Retrofit retrofit;

    public SimpleItem(ItemModel itemModel) {
        super(itemModel);
        ((MyApp) context.getApplicationContext()).getSingletonComponent().inject(this); << 
    }
}
````

**Comment by FabianTerhorst** [comment]
You can use the ```Function``` interface to initiate the Item objects yourself as an constructor parameter of the generic adapter.

**Comment by stonecold123** [comment]
I'm following the example of `MultiTypeGenericItemActivity`, but it doesn't seem to work. 
Using your example, Is it possible to pass an extra parameter to `RightGenericIconItem`, for example:
````
public class RightGenericIconItem extends GenericIconItem {
    String extra;
    public RightGenericIconItem(IconModel icon) {
        super(icon);
    }
    public RightGenericIconItem(IconModel icon,String extra) {
        super(icon);
        this.extra = extra;
    }
}
````

**Comment by mikepenz** [comment]
@stonecold123 if you check the sample, you can see that it initiates the adapter with the function:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeGenericItemActivity.java#L58

And the function defines how the items specific for a model are initiated. You can there use any ctor those items provide.
