### ISSUE TITLE
Remove item

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/FastAdapter#26]
When I remove an item, it appears again...

**Comment by mikepenz** [comment]
@EpsilonOrionis what was the issue?

**Comment by EpsilonOrionis** [comment]
I was removing the item in a LongClickListener, and without any explaination it was reappearing. I was using: fastAdapter.notifyItemRemoved(int position), I solved it using insted MyItemAdapter.remove(int position)
