### ISSUE TITLE
Method does not override method from its superclass

### ISSUE THREAD

**Issue by franci22** [mikepenz/FastAdapter#263]
Hi!
When I copy and paste [SampleItem class](https://github.com/mikepenz/FastAdapter#1-implement-your-item-the-easy-way) Android Studio returns me this error:
![image](https://cloud.githubusercontent.com/assets/5649257/20119790/34f66ca2-a60a-11e6-808a-533f40ffb209.png)
I've only changed name of the class.
```
package com.franci22.supersecureencryption.items;

import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.TextView;

import com.franci22.supersecureencryption.R;
import com.mikepenz.fastadapter.items.AbstractItem;

import java.util.List;

public class ListItem extends AbstractItem<ListItem, ListItem.ViewHolder> {

    public String name;
    public String description;

    //The unique ID for this type of item
    @Override
    public int getType() {
        return R.id.list_item_id;
    }

    //The layout to be used for this type of item
    @Override
    public int getLayoutRes() {
        return R.layout.list_item;
    }

    //The logic to bind your data to the view
    @Override
    public void bindView(ViewHolder viewHolder, List<Object> payloads) {
        //call super so the selection is already handled for you
        super.bindView(viewHolder, payloads);

        //bind our data
        //set the text for the name
        viewHolder.name.setText(name);
        //set the text for the description or hide
        viewHolder.description.setText(description);
    }

    //reset the view here (this is an optional method, but recommended)
    @Override
    public void unbindView(ViewHolder holder) {
        super.unbindView(holder);
        holder.name.setText(null);
        holder.description.setText(null);
    }

    //The viewHolder used for this item. This viewHolder is always reused by the RecyclerView so scrolling is blazing fast
    protected static class ViewHolder extends RecyclerView.ViewHolder {
        protected TextView name;
        protected TextView description;

        public ViewHolder(View view) {
            super(view);
            this.name = (TextView) view.findViewById(R.id.material_drawer_name);
            this.description = (TextView) view.findViewById(R.id.material_drawer_description);
        }
    }
}
```

Why? Thanks!

**Comment by mikepenz** [comment]
@franci22 2.1 will slightly alter this method. So for 2.0 you should have just `List` without the `<Object>` in the `bindView`  method

**Comment by mikepenz** [comment]
You can always look at the source code for a specific tag: https://github.com/mikepenz/FastAdapter/blob/v2.0.0/app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleItem.java

**Comment by franci22** [comment]
Thanks! And what about unbindView?

**Comment by mikepenz** [comment]
What do you mean? 
https://github.com/mikepenz/FastAdapter/blob/v2.0.0/app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleItem.java#L114

**Comment by franci22** [comment]
![image](https://cloud.githubusercontent.com/assets/5649257/20192483/5fe20940-a78a-11e6-879d-a718705b7f5d.png)

**Comment by mikepenz** [comment]
Do you have a wrong ViewHolder import? not the one defined in the class definition?

**Comment by francescotarantino** [comment]
This is my code right now:

```
import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.TextView;

import com.mikepenz.fastadapter.items.AbstractItem;

import java.util.List;

public class ListItem extends AbstractItem<ListItem, ListItem.ViewHolder> {

    public String name;
    public String description;

    //The unique ID for this type of item
    @Override
    public int getType() {
        return R.id.list_item_id;
    }

    //The layout to be used for this type of item
    @Override
    public int getLayoutRes() {
        return R.layout.list_item;
    }

    //The logic to bind your data to the view
    @Override
    public void bindView(ViewHolder viewHolder, List payloads) {
        //call super so the selection is already handled for you
        super.bindView(viewHolder, payloads);

        //bind our data
        //set the text for the name
        viewHolder.name.setText(name);
        //set the text for the description or hide
        viewHolder.description.setText(description);
    }

    @Override
    public void unbindView(ViewHolder holder) {

        super.unbindView(holder);
        holder.name.setText(null);
        holder.description.setText(null);
    }


    //The viewHolder used for this item. This viewHolder is always reused by the RecyclerView so scrolling is blazing fast
    protected static class ViewHolder extends RecyclerView.ViewHolder {
        protected TextView name;
        protected TextView description;

        public ViewHolder(View view) {
            super(view);
            this.name = (TextView) view.findViewById(R.id.material_drawer_name);
            this.description = (TextView) view.findViewById(R.id.material_drawer_description);
        }
    }
}
```

**Comment by mikepenz** [comment]
@franci22 could you just remove the unbind method and use Android Studio to generate the override method for you? I can't see the issue in your sample

**Comment by mikepenz** [comment]
please answer back. close this for now

**Comment by akhilps** [comment]
Error:(25, 5) error: method does not override or implement a method from a supertype i have an error woud you pls help

**Comment by akhilps** [comment]
@Override
    public Map<String,String> getparams(){
        return paramas;
    }
}


the above is my code

**Comment by mikepenz** [comment]
@akhilps I do not see code which is related to the FastAdapter

**Comment by akhilps** [comment]
i cannot understand plz help me whats
 i have to do

**Comment by mikepenz** [comment]
@akhilps you did not post the full error log, not the code which is not compiling, nor a detailed description what's going on. Please create a new issue, with proper description, with proper code, otherwise I can't help you

**Comment by akhilps** [comment]
package com.example.akhil.loginregister;

/**
 * Created by AKHIL on 21-Apr-17.
 */
import com.android.volley.Response;
import com.android.volley.toolbox.StringRequest;
import java.util.HashMap;
import java.util.Map;


class RegisterRequest extends StringRequest{

    private static final String REGISTER_REQUEST_URL="";
    private Map<String,String> paramas;

    public RegisterRequest(String name,String username,int age,String password,Response.Listener<String> listener) {
        super(Method.POST,REGISTER_REQUEST_URL, listener,null);
        paramas=new HashMap<>();
        paramas.put("name",name);
        paramas.put("username",username);
        paramas.put("password",password);
        paramas.put("age",age+"");
    }
    @Override
    public Map<String,String>getparams(){
        return paramas;
    }
}



this is my code and i have an error in @override the error

**Comment by mikepenz** [comment]
This has nothing to do with the FastAdapter library. Please use Google or StackOverFlow...

**Comment by akhilps** [comment]
ok thanku

**Comment by darsanpatel8311** [comment]
![capture](https://user-images.githubusercontent.com/35891278/35788749-550a5202-0a5d-11e8-8fd4-8c8e9dd4254b.PNG)
Please Solve This Error

**Comment by mikepenz** [comment]
This issue has nothing to do with this library.

**Comment by ayankhan2415** [comment]
please help me and solve above problem

**Comment by ayankhan2415** [comment]
beacause i have same problm

**Comment by davit-zakaryan** [comment]
@ayankhan2415, I had the same issue when updating to the new version '5.0.0 '. Just change the bindView signature from this : 
 `override fun bindView(holder: ViewHolder, payloads: MutableList<Any>) `
to this : 
 `override fun bindView(holder: ViewHolder, payloads: List<Any>) `
