### ISSUE TITLE
mClickListenerHelper.listen deprecated 

### ISSUE THREAD

**Issue by hmedat2008** [mikepenz/FastAdapter#264]
I have upgrade the library from 1.0.6@aar to 2.0.0@aar
I found this code is deprecated, i don't know why? what is the correct ode?

```
  mClickListenerHelper.listen(viewHolder, ((PendingRequest.ViewHolder) viewHolder).imgRemoveMember, (v, position, item) -> {
                acceptRequest(position, false);
 });
```

**Comment by mikepenz** [comment]
@hmedat2008 this was deprecated in favor of the new `EventHook' s you can find it here in the sample:
https://github.com/mikepenz/FastAdapter/blob/b8467b6c9850f1c2e7c0b42810e455ae9f888dcf/app/src/main/java/com/mikepenz/fastadapter/app/CheckBoxSampleActivity.java#L69
https://github.com/mikepenz/FastAdapter/blob/a060aca5105eda89d02cced1a7da6e20077dba2f/app/src/main/java/com/mikepenz/fastadapter/app/items/CheckBoxSampleItem.java#L143

**Comment by hmedat2008** [comment]
Thank you, but i prefer to put it in your deprecated function

**Comment by mikepenz** [comment]
@hmedat2008 the deprecated function will be removed in v2.1 and it is highly recommend to use the new more flexible eventhook system.

**Comment by Rainer-Lang** [comment]
I also migrated and it's fine.

**Comment by hmedat2008** [comment]
Ok Thank  you
