### ISSUE TITLE
onClick event not fired on item

### ISSUE THREAD

**Issue by rakesh1988** [mikepenz/FastAdapter#265]
Hi Mike,
I must definitely be doing something wrong. Somehow the click events are not getting triggered.
```
fastAdapter.withSelectable(true);
fastAdapter.withOnClickListener(new FastAdapter.OnClickListener<IItem>()
{
	@Override
	public boolean onClick(View v, IAdapter<IItem> adapter, IItem item, int position)
	{
		Timber.d("clicked");
		return true;
	}
});
```

```fastAdapter.withSelectable(true);``` enables the click effect, but the onClick method never gets triggered. 
What is it that I am doing wrong?

Also what is the significance of return true/false from this onClick event?

**Comment by mikepenz** [comment]
@rakesh1988 do you have any other events or anything else which might prevent the click event from being forwarded?

**Comment by mikepenz** [comment]
`true` -> event was consumed
`false` -> event was not consumed

**Comment by rakesh1988** [comment]
@mikepenz as always thanks for your prompt reply.
I have a button in my activity and i have registered an onClick event on this button using ButterKnife.
Also this item has a checkbox whose visibility is hidden. I had registered a click event on this checkbox. 

Now that I have disabled every click even in the activity. Still the onClick event is not fired.

**Comment by mikepenz** [comment]
@rakesh1988 weird. It seems something is preventing the `onClick` event being triggered on the `viewHolder`'s `itemView`

Basically the `FastAdapter` has to maintain a `OnClickListener` on the `itemView` (once per viewHolder` to allow an efficient handling of these events)

How does your `Item` look like?

**Comment by rakesh1988** [comment]
gist here https://gist.github.com/anonymous/c82484f631d8ac743aff61015feb8ac4
I have removed business logic to make it look simpler

**Comment by rakesh1988** [comment]
@mikepenz you are totally right.. problem was in my layout XML 👍 I had a image which was clickable

**Comment by AliYusuf95** [comment]
Hi @mikepenz,
I face same problem, when I click on item nothing happen.
This is my code:
```
servicesList.setHasFixedSize(true);
servicesList.setItemAnimator(new DefaultItemAnimator());
servicesList.setLayoutManager(new LinearLayoutManager(this));
fastAdapter.withSelectable(true);
fastAdapter.withOnClickListener(new FastAdapter.OnClickListener<Service>() {
    @Override
    public boolean onClick(View v, IAdapter<Service> adapter, Service item, int position) {
        Logger.d(position);
        return true;
    }
});
fastAdapter.clear().add(groupOfServices.getServices());
servicesList.setAdapter(fastAdapter);
```
Service model:
```
public static class Service extends AbstractItem<Service, Service.ViewHolder> {

        @SerializedName("_id")
        @Expose
        private String id;
        @SerializedName("name")
        @Expose
        private String name;

        public Service(String id, String name) {
            this.id = id;
            this.name = name;
        }

        public String getId() {
            return id;
        }

        public String getName() {
            return name;
        }

        @Override
        public int getType() {
            return 0;
        }

        @Override
        public int getLayoutRes() {
            return R.layout.row_service;
        }

        @Override
        public void bindView(ViewHolder viewHolder, List<Object> payloads) {
            super.bindView(viewHolder, payloads);
            viewHolder.name.setText(name);
        }

        @Override
        public void unbindView(ViewHolder holder) {
            super.unbindView(holder);
            holder.name.setText(null);
        }

        public static class ViewHolder extends RecyclerView.ViewHolder {
            protected @BindView(R.id.service_name) TextView name;

            public ViewHolder(View view) {
                super(view);
                ButterKnife.bind(this, view);
            }
        }

        /**
         * Override this variable from {@link AbstractItem} to make {@link Gson}
         * works perfectly.
         */
        private transient ViewHolderFactory<? extends ViewHolder> mFactory;

        /**
         * Override this method to use {@link #mFactory}
         */
        @Override
        public Service withFactory(ViewHolderFactory<? extends ViewHolder> factory) {
            this.mFactory = factory;
            return this;
        }

        /**
         * Override this method to use {@link #mFactory}
         */
        @Override
        public ViewHolderFactory<? extends ViewHolder> getFactory() {
            if (mFactory == null) {
                try {
                    this.mFactory = new ReflectionBasedViewHolderFactory<>(viewHolderType());
                } catch (Exception e) {
                    throw new RuntimeException("please set a ViewHolderFactory");
                }
            }
            return mFactory;
        }

    }
```
and this is the XML layout:
```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <TextView
        android:id="@+id/service_name"
        android:layout_width="match_parent"
        android:layout_height="80dp"
        android:textAppearance="?android:attr/textAppearanceMedium"
        android:text="Medium Text"
        android:textColor="@color/colorPrimary"
        android:background="@drawable/edittextme2"
        android:gravity="center"
        android:layout_margin="20dp"
        android:textSize="37sp"
        />

</LinearLayout>
```

**Comment by mikepenz** [comment]
@AliYusuf95 what do you expect to happen?

**Comment by AliYusuf95** [comment]
@mikepenz  A debug log with position number, Even if I put a Toast message nothing shown to me.

**Comment by androideen** [comment]
I had the same issue. onClick is never trigged. And, how to know if a checkbox is clicked? 

fastItemAdapter.withOnClickListener(new FastAdapter.OnClickListener<CheckBoxFeedItem>() {
            @Override
            public boolean onClick(View v, IAdapter<CheckBoxFeedItem> adapter, CheckBoxFeedItem item, int position) {
                Log.d("CHECKBOX", item.isSelected() + "");
                return false;
            }
        });

**Comment by AliYusuf95** [comment]
I had test the adapter in other app that's implements [SuperRecyclerView ](https://github.com/Malinskiy/SuperRecyclerView), it's work perfectly with same overrides and even without set `withSelectable` to `true`.

Can you tell me what are the cases that would prevent `withOnClickListener` from fired so I find the reason from my side.

**Comment by AliYusuf95** [comment]
@mikepenz I found what's wrong with my approach, a just add a default constructor and make mSelectable true.
