### ISSUE TITLE
Setting TouchListener in ViewHolder constructor

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#267]
I think following SHOULD work, but it does not. Any ideas why?

    public class Item
    {
        @Override
        public void bindView(ViewHolder viewHolder, List payloads)
        {
            super.bindView(viewHolder, payloads);

            // place 1: here it works as expected
            ViewUtil.addTouchResize(viewHolder.itemView);
        }

        @Override
        public void unbindView(ViewHolder viewHolder)
        {
            super.unbindView(viewHolder);
            viewHolder.reset();
        }

        public static class ViewHolder extends RecyclerView.ViewHolder
        {
            public ViewHolder(View view)
            {
                super(view);
                // place 2: here it does NOT work
                ViewUtil.addTouchResize(view);
            }
            
            public void reset()
            {
                ViewUtil.clearAnimation(itemView);
            }
        }
    }

My `ViewUtil` calls `view.setOnTouchListener(...)` in `addTouchResize` and restores all views settings and cancels all animations in `clearAnimation`.

I should set the `onTouchListener` only when I create the `ViewHolder` not everytime it gets bound. Any ideas why this is not working in the `ViewHolders` constructor?

**Comment by mikepenz** [comment]
@MFlisar in general. please never set listeners inside the `bindView` method. This method is called many many many times and such operations will just make things slower. 

In general the best place to attach the listeners is when the viewholders are created. 

To simplify this, v2.0 comes with the `EventHooks` 


So how does it work. In general you implement one of the provided `hook`'s or you can implement a custom one. using a predefined one looks like:
https://github.com/mikepenz/FastAdapter/blob/a060aca5105eda89d02cced1a7da6e20077dba2f/app/src/main/java/com/mikepenz/fastadapter/app/items/ImageItem.java#L211

And afterwards you just need to give the `FastAdapter` this eventhook. It will automatically handle everything else for you:
https://github.com/mikepenz/FastAdapter/blob/b8467b6c9850f1c2e7c0b42810e455ae9f888dcf/app/src/main/java/com/mikepenz/fastadapter/app/ImageListActivity.java#L80

**Comment by MFlisar** [comment]
I tried setting the listener once only in the constructor of the `ViewHolder` ;-)

I would not have looked for something like the hooks and it's unclear for me, why the manual setter in the `ViewHolders` constructor is not working (I would still prefer this actually).

I'll try the `TouchEventHook` though..

**Comment by mikepenz** [comment]
@MFlisar you can reuse the `EventHook` for different types if you implement the support for it in the `onBind` here: https://github.com/mikepenz/FastAdapter/blob/a060aca5105eda89d02cced1a7da6e20077dba2f/app/src/main/java/com/mikepenz/fastadapter/app/items/ImageItem.java#L214

Good idea.

**Comment by MFlisar** [comment]
I'm doing that already and seems to work fine.

What do say to my second question about the `unbindView`? Or does the "good idea" belong to this point?

**Comment by mikepenz** [comment]
Ok great. 

The "good idea" was about this :D

**Comment by mikepenz** [comment]
@MFlisar just had a deeper look into this topic. 

I think it is not a good idea to have the unbind trigger the EventHook. as unbind is called many many times. The EventHook on the other side is just created once per ViewHolder. The RV does not provide a similar method like onViewHolderDestroyed. 

It is still the best idea to just implement it in the views `unbindView` method

**Comment by or-dvir** [comment]
hi @mikepenz.
i just ran into a similar issue: i wish to add a click listener to one of my items (not the standard clickListener of the recyclerView, but an inner listener for a view my item has) and i was wondering what is the best place to put it in, and i came across this post.
my click listener opens a dialog and the problem is that i need to pass this dialog some data which the item holds. but if i put my click listener in the viewHolder constructor how would i access the item data? (these are 2 different classes so i dont have access to the members).

is it only possible via event hooks or is there some other way i could do that?

thanks

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter#4-click-listeners-for-views-inside-your-item

**Comment by or-dvir** [comment]
*face palm*
how did i not see this?! i feel so dumb... sorry, ill give this a try

**Comment by mikepenz** [comment]
@or-dvir you can define multiple views at once. see the `onBindMany` you can implement. 

And you can also define not only a `ClickEventHook` but also a `TouchEventHook` or a `CustomEventHook`

And yes it is the most efficient, as it will create the listener only once, instead of multiple times. it will also prevent you from passing in the adapter to the ViewHolder and set the listener there. and the cast isn't that expensive as you may think

**Comment by or-dvir** [comment]
@mikepenz im afriad i dont understand how custom event hooks work.
lets take my example, i have a spinner and i need to use "setOnItemSelectedListener ()".
in the case of click event hook or touch event hook it's very clear what the event is, however by looking at the code, customEventHook doesnt seem to be related to any specific event(e.g. spinner item selected). so... how would i know which event happened? how would i access this event's data (i.e. all the parameters of the standard android listener callback)?

unfortunately there is no documentation for CustomEventHook, and i couldn't find an example of it in the sample app.

**Comment by mikepenz** [comment]
so basically you would provide an `EventHook` per action you want to implement. 

That means you would have for example a ClickEventHook defined for 2 views which will launch an activity
you will have an additional ClickEventHook for a view which will like a user. The main idea is to bundle the logic of this into re-useable components

And for the `CustomEventHook` you would have one per listener. so youc an have one for your spinner, one for your progressBar, ... whatever. 

In the `onEvent` you get passed in the view: 
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/listeners/CustomEventHook.java#L14

There you would then just implement your listener you want to attach to that view

**Comment by or-dvir** [comment]
@mikepenz thanks for the reply, but what im still confused about is the method "onEvent". when is it triggered? what triggers it?

i think im starting to get it... please correct me if im wrong:
-onBind (or onBindmany) is where i would return the view(s) to which i want to attach an event to?
-onEvent will be called whenever the view is created in the viewHolder?

let me use an example:
lets say i have 2 views, a check box and a spinner. for the spinner i want to attach "itemSelectedListener", and for the check box i want to attach both "checkedChangedListener" and "clickListener" (forget that there is a clickEventHook, i want to make sure i understand the customEventHook).
would it look like this? (doesn't look right to me, but maybe it is?)

```
public static class MymEventHook extends CustomEventHook<MyItem>
	{
		@Nullable
		@Override
		public List<View> onBindMany(@NonNull RecyclerView.ViewHolder viewHolder)
		{
			if (viewHolder instanceof MyItem.ViewHolder)
			{
				ArrayList<View> list = new ArrayList<>();

				list.add(((MyItem.ViewHolder) viewHolder).checkBox);
				list.add(((MyItem.ViewHolder) viewHolder).spinner);

				return list;
			}

			return null;
		}

		@Override
		public void onEvent(View v, RecyclerView.ViewHolder viewHolder, int position, FastAdapter<MyItem> fastAdapter, MyItem item)
		{
			if(v instanceof CheckBox)
			{
				((CheckBox)v).setOnClickListener(...);
				((CheckBox)v).setOnCheckedChangeListener(...);
			}
			
			else if(v instanceof Spinner)
			{
				((Spinner)v).setOnItemSelectedListener(...);
			}
		}
	}
```

**Comment by mikepenz** [comment]
@or-dvir you can do it as your code sample shows. But the better solution would be to have it's own EventHook per listener. So you can simply re-use it in different items. 

Sure it is possible to use one and put everything together, but having multiple makes it easier to re-use and splits apart the different logics. 

And the EventHook prevents you from creating the listener for each onBind call. At least that's the thought behind.

**Comment by or-dvir** [comment]
@mikepenz but i could only reuse the eventHook if i have another layout with the same views in it with the same names.... no?

**Comment by mikepenz** [comment]
It is anyways clever to have the same names for views doing the same. 

If you do not feel comfortable with all of this. You can do it differently too. You could provide your own `BindViewListener` and set the listeners there. You can do it inside the `ViewHolder` but then you have to somehow pass in the `Adapter`'s reference to the item. 

The FastAdapter does not really limit you from doing anything as you may would do. It just tries to prevent you from doing the "wrong" thing

**Comment by or-dvir** [comment]
@mikepenz ok i guess ill play around with it see what works best for me... THANK YOU SO MUCH FOR YOU HELP!

p.s.
will you please add a sample use case of this to the sample app? i think that could be very helpful

**Comment by or-dvir** [comment]
@mikepenz i have a new problem. i am trying to implement the way you said but `if (position != RecyclerView.NO_POSITION)` always returns false (meaning position is always -1), so my listeners are not being set.

here is my onEvent:

```
@Override
		public void onEvent(View view,
							final RecyclerView.ViewHolder viewHolder,
							FastAdapter<MyItem> fastAdapter)
		{
			//we get the adapterPosition from the viewHolder
			final int position = fastAdapter.getHolderAdapterPosition(viewHolder);

			Log.i("aaaaa", "position " + position);

			//make sure the click was done on a valid item
			if (position != RecyclerView.NO_POSITION)
			{
				final MyItem item = fastAdapter.getItem(position);

				if (view instanceof CheckBox)
				{
					//noinspection RedundantCast
					((CheckBox) view).setOnClickListener(new View.OnClickListener()
					{
						@Override
						public void onClick(View view)
						{
							item.setChecked(!item.isChecked);

							String checked = item.isChecked ? "checked" : "unchecked";

							Toast.makeText(viewHolder.itemView.getContext(),
										   "item " + (position + 1) + checked,
										   Toast.LENGTH_SHORT)
								 .show();
						}
					});
				}
			}
		}
```

**Comment by FabianTerhorst** [comment]
You have to fetch the position when you actually need it.

**Comment by or-dvir** [comment]
@FabianTerhorst well i need it there... when the view is triggering the listener (in this case a checkbox is triggering "onclick") i need access to the properties of MyItem (which is on the same line as the checkbox being clicked)

**Comment by FabianTerhorst** [comment]
Fetch the position in the callback

**Comment by or-dvir** [comment]
@FabianTerhorst thank you it works!

please please please add a small code sample in the sample app for this kind of a thing... would have saved me a lot of time

**Comment by mochadwi** [comment]
did you mean fetching the position on the callback inside "if (view instanceof CheckBox)"?

@FabianTerhorst @or-dvir
