### ISSUE TITLE
[Question] What does EventHook exactly do? and how to use it correctly?

### ISSUE THREAD

**Issue by eskandarpour** [mikepenz/FastAdapter#271]
Hi Mike,

I found there is a new file named `EventHook` but I didn't find any guides on the repo, can you give me some good explanations about it please?

Thanks,
Alireza

**Comment by Rainer-Lang** [comment]
There are examples in the demo app

**Comment by mikepenz** [comment]
@eskandarpour a `EventHook`s will hook events on views inside your items. In some cases you want to have different stuff to happen when a person clicks on a view. (not the whole item) for exmaple an small image inside a list element. For these cases you will create an Eventhook which you will hook onto this view. This is done once when the viewholder is created the first time. so it is very fast. 

Afterwards it will call this eventhook when the user clicks on the view and you can react on it
