### ISSUE TITLE
notifyAdapterDataSetChanged adds new item with expandable item

### ISSUE THREAD

**Issue by niyasmohaideen** [mikepenz/FastAdapter#272]
Hi MikePenz,

Thanks for your great library which saves my development time. I also use your Material drawer library as well.

 I am using expandable item fastadapter and updates the subitems in OnResume(..) method. After updating the items I use fastItemAdapter.notifyAdapterDataSetChanged() to reflect the changes made to adapter. Everything I call notifyAdapterDataSetChanged() new set of sub items is getting added and don't no why new items are being added instead of just updating the items. 

Please help me resolving this issue.
[ProductFragment.txt](https://github.com/mikepenz/FastAdapter/files/608876/ProductFragment.txt)

Attached ProductFragment file where doing expandable item update.

**Comment by mikepenz** [comment]
@niyasmohaideen please do not use the general `notifyAdapterDataSetChanged` if you just update items. 

Especially when working with subitems you should use the specific notify methods to update the subitems. 
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1672

**Comment by niyasmohaideen** [comment]
Thanks Mike for the quick reply. Let me try with specific notify methods.

**Comment by mikepenz** [comment]
ok great
