### ISSUE TITLE
WithOnlyOneExpandedItem and nested Expanded lists

### ISSUE THREAD

**Issue by gromiloff** [mikepenz/FastAdapter#273]
Hi!

I try to implement some logic, when need show list with 2 lvls of lists:

Root 1
> Category 11
>> Item 111
>> Item 112

> Category 12
>> Item 121
>> Item 122

Root 2
> Category 21
>> Item 211
>> Item 212
...

So, all work fine if not use WithOnlyOneExpandedItem for adapter. If I set the flag to true then categories subitems unable to open.

But i need only one expanded root item. So, what I can do it ?

Thanks.

**Comment by mikepenz** [comment]
@gromiloff this is not possible with this flag as it will prevent any additional hirachies of being opened, no matter about the level. 
In this case you will have to check the selected items count when a new element is opened and perhaps close other parents.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L882
might help. 

Or also this:
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/utilities/SubItemUtil.java
