### ISSUE TITLE
IndexOutOfBoundsException when i used AbstractWrapAdapter

### ISSUE THREAD

**Issue by steventxc** [mikepenz/FastAdapter#275]
Hi Mike Penz:
Thanks for your library first.

when i used `AbstractWrapAdapter`, i added another dataset, but when i clicked the last item, will caused
`java.lang.IndexOutOfBoundsException`. i noticed array size just equals to the original data which added in `FastItemAdapter`, but not include the appended data that added in the `AbstractWrapAdapter` , that's why caused the error. 
i'm confusing about below two methods too
```
    public abstract boolean shouldInsertItemAtPosition(int position);

    public abstract int itemInsertedBeforeCount(int position);
```

in the first function, the pram `position` is as the same as the list, but in the second, the `position` is include the data before inserted as the function name.

so, any suggestion to handler the clicked event error ?

**Comment by mikepenz** [comment]
@steventxc a `WrapAdapter` wraps around normal adapters and will not change or being visible for the `FastAdapter` in general it modifies the positions of the internal adapters and just inflates new items within your list without your main list knowing about those. 

There is a sample application here: https://github.com/mikepenz/FastAdapter/blob/b8467b6c9850f1c2e7c0b42810e455ae9f888dcf/app/src/main/java/com/mikepenz/fastadapter/app/adapters/SampleWrapAdapter.java
which will add an item at position 10

There is also a more complex implementation:
https://github.com/mikepenz/FastAdapter/blob/b8467b6c9850f1c2e7c0b42810e455ae9f888dcf/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/adapters/WrapAdapter.java

Which will equaly split up the list you provide accross your main items.

**Comment by steventxc** [comment]
@mikepenz  
[here is my demo code](https://github.com/steventxc/AbstractWrapAdapterTest)

**Comment by mikepenz** [comment]
@steventxc you are right. there is a real problem. the click listener inside the FastAdapter does get the real position of the click and not the adjusted persion which is caused by the movage through the wrapadapter. I have to check what would be the best way to improve this behavior

**Comment by mikepenz** [comment]
@steventxc oh I remembered how this can be solved. Simply extend the `FAstItemAdapter` and implement the `getHolderAdapterPosition` make sure to use the same logic as in the wrapadapter there. 

I have done the following adjustments.
In the `MyAbstractWrapAdapter`
```java
@Override
    public int itemInsertedBeforeCount(int position) {
        return getItemInsertedBeforeCount(position);
    }

    public static int getItemInsertedBeforeCount(int position) {
        // TODO: 16/11/25  I'm not sure this is the best way

        for (int i = 0; ; i++) {
            int span = SPAN * (i + 1) + i;
            if (position < span) {

                Log.e("ERROR", "" + i);
                return i;
            }
        }
    }
```

and I implemented a `CustomFastItemAdapter`
```java
public class CustomFastItemAdapter<Item extends IItem> extends FastItemAdapter<Item> {
    public static final int SPAN = 10;

    @Override
    public int getHolderAdapterPosition(RecyclerView.ViewHolder holder) {
        int pos = super.getHolderAdapterPosition(holder);
        return pos - MyAbstractWrapAdapter.getItemInsertedBeforeCount(pos);
    }
}
```

**Comment by steventxc** [comment]
@mikepenz Thanks for your help! 
but there is a bug. I found the last element always be omitted. 
in class `AbstractWrapAdapter`, I think the below method caused the bug. here passed the original adapter's dataset size, but it not always equals to the position of the last item.
```
    @Override
    public int getItemCount() {
        int itemCount = mAdapter.getItemCount();
        return itemCount + itemInsertedBeforeCount(itemCount);
    }
```
