### ISSUE TITLE
Eventhooks for more than one view.

### ISSUE THREAD

**Issue by ontherunvaro** [mikepenz/FastAdapter#276]
Hello, is it possible to set more than one eventhook in a FastItemAdapter?
My use case is: my items have two imagebuttons within them, and each of them should do different things when clicked.

**Comment by mikepenz** [comment]
@ontherunvaro this is on the todo for the next update. I hope I will be able to release this weekend

**Comment by mikepenz** [comment]
is now possible in v2.1.5

**Comment by ontherunvaro** [comment]
How would one go about implementing this? I guess I have to override the "onBindMany" method in ClickEventHook, and then check for view id in onClick?
