### ISSUE TITLE
In ExpandableSampleActivity 

### ISSUE THREAD

**Issue by nikitamarysoloman** [mikepenz/FastAdapter#280]
onclick of a particular widget  i want to expand and collapse  the subitem list also want to remove the existing feature (expand on click of the list item). Please help

**Comment by FabianTerhorst** [comment]
Can you post some code snippets what you have tried and explain what doesn´t work.

**Comment by nikitamarysoloman** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/ExpandableSampleActivity.java

when iam clicking on the items in the list with subitem it is getting expanded iam not able to stop this. Instead of this I want to expand its subitems on click of the rotating button in your design. Which is not working. So Please suggest how do expanding and collapsing of sub items in expandableitems on click of a button or view inside the item.

**Comment by mikepenz** [comment]
So if you item looks similar as the one used in this sample app. Do the following:

Remove these methods:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/expandable/SimpleSubExpandableItem.java#L98
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/expandable/SimpleSubExpandableItem.java#L67
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/expandable/SimpleSubExpandableItem.java#L71

and also remove this class you don't need it. just keep the logic:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/expandable/SimpleSubExpandableItem.java#L77

now there won't be expanding / collapsing on item click. 

So to get it now if you click on the view. Just move (and adjust the code) to work inside a normal click event hook
https://github.com/mikepenz/FastAdapter#4-click-listeners-for-views-inside-your-item

**Comment by nikitamarysoloman** [comment]
Thank you for the reply
 fastItemAdapter.withOnCreateViewHolderListener(new FastAdapter.OnCreateViewHolderListener() {
            @Override
            public RecyclerView.ViewHolder onPreCreateViewHolder(ViewGroup parent, int viewType) {

                return fastItemAdapter.getTypeInstance(viewType).getViewHolder(parent);
            }

            @Override
            public RecyclerView.ViewHolder onPostCreateViewHolder(RecyclerView.ViewHolder viewHolder) {
                viewHolder.itemView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        Log.e("removed","expand on item click");
                    }
                });
//                viewHolder.itemView.performClick();

                return viewHolder;
            }
        });
I hav stopped the it.
now it is not expanding / collapsing on item click.
but i want on click of that rotating icon your code.
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/expandable/SimpleSubExpandableItem.java#L77
want to expand  / collapsing on that icon (rotating up and down arrow)click.
Please help.
your code for expand  / collapsing if iam not wrong is the below one in fast adapter. Can i set a view on click of which this should happen..?
```
  holder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                int pos = getHolderAdapterPosition(holder);
                if (pos != RecyclerView.NO_POSITION) {
                    boolean consumed = false;
                    RelativeInfo<Item> relativeInfo = getRelativeInfo(pos);
                    Item item = relativeInfo.item;
                    if (item != null && item.isEnabled()) {
                        //on the very first we call the click listener from the item itself (if defined)
                        if (item instanceof IClickable && ((IClickable) item).getOnPreItemClickListener() != null) {
                            consumed = ((IClickable<Item>) item).getOnPreItemClickListener().onClick(v, relativeInfo.adapter, item, pos);
                        }

                        //first call the onPreClickListener which would allow to prevent executing of any following code, including selection
                        if (!consumed && mOnPreClickListener != null) {
                            consumed = mOnPreClickListener.onClick(v, relativeInfo.adapter, item, pos);
                        }

                        //handle the selection if the event was not yet consumed, and we are allowed to select an item (only occurs when we select with long click only)
                        //this has to happen before expand or collapse. otherwise the position is wrong which is used to select
                        if (!consumed && !mSelectOnLongClick && mSelectable) {
                            handleSelection(v, item, pos);
                        }

                        //if this is a expandable item :D (this has to happen after we handled the selection as we refer to the position)
                        if (!consumed && item instanceof IExpandable) {
                            if (((IExpandable) item).isAutoExpanding() && ((IExpandable) item).getSubItems() != null) {
                                toggleExpandable(pos);
                            }
                        }

                        //if there should be only one expanded item we want to collapse all the others but the current one (this has to happen after we handled the selection as we refer to the position)
                        if (!consumed && mOnlyOneExpandedItem) {
                            int[] expandedItems = getExpandedItems();
                            for (int i = expandedItems.length - 1; i >= 0; i--) {
                                if (expandedItems[i] != pos) {
                                    collapse(expandedItems[i], true);
                                }
                            }
                        }

                        //before calling the global adapter onClick listener call the item specific onClickListener
                        if (!consumed && item instanceof IClickable && ((IClickable) item).getOnItemClickListener() != null) {
                            consumed = ((IClickable<Item>) item).getOnItemClickListener().onClick(v, relativeInfo.adapter, item, pos);
                        }

                        //call the normal click listener after selection was handlded
                        if (!consumed && mOnClickListener != null) {
                            mOnClickListener.onClick(v, relativeInfo.adapter, item, pos);
                        }
                    }
                }
            }
        });

please reply
[Untitled Document 1.docx](https://github.com/mikepenz/FastAdapter/files/623966/Untitled.Document.1.docx)

**Comment by nikitamarysoloman** [comment]
[Untitled Document 1.docx](https://github.com/mikepenz/FastAdapter/files/623981/Untitled.Document.1.docx)
according to your reply I have commented those on click codes but still the expand and collapse where working

**Comment by mikepenz** [comment]
for the animation to happen you should set a click listener on the view with the arrow via the event hook:
https://github.com/mikepenz/FastAdapter#4-click-listeners-for-views-inside-your-item

and in there you just check the current state and then you do the animation. (you should be able to use the code from the sample item)
