### ISSUE TITLE
setAlpha doesn't work on first BindView

### ISSUE THREAD

**Issue by ncapdevi** [mikepenz/FastAdapter#282]
Not entirely sure if this is a problem with the library or RecyclerView. If you run the following code:
```
    @Override
    public void bindView(VH holder, List<Object> payloads){
        super.bindView(holder, payloads);
       holder.itemView.setAlpha(0.5f);
    }
```

Alpha will not be shown the first time the item is shown. However, if you leave the screen and come back, Alpha is then accurately shown.  The value is being set, but not displayed until it's shown again.

**Comment by mikepenz** [comment]
@ncapdevi it is no problem of the `FastAdapter` 

could you please check to also set the alpha in the `ViewHolder` and perhaps also in the `unbind` method? 

if it is set but not shown. I assume it is some API issue? it is definitely something android specific. sorry

**Comment by ncapdevi** [comment]
Thought so. Same issue persists if I set it in the `ViewHolder` constructor or in `unbind`. If I find a solution I can post it back in this thread. Thanks for the help.

**Comment by mikepenz** [comment]
@ncapdevi ok thanks

**Comment by ncapdevi** [comment]
Think I came up with what the problem is, and it actually does have to do with FastAdapter, but more specifically with the itemanimators.  In DefaultAnimator, line 23, the code 

`        ViewCompat.setAlpha(holder.itemView, 1);
`
is executed. This means that while I am setting the alpha in my bind method, this method is overwriting it. Then, next time I come to the screen, this animation isn't being ran , and the onBind method hold the setAlpha value that is set.  Any ideas for ways around this?

**Comment by ncapdevi** [comment]
This also happens if you don't set any Item Adapter and the `RecyclerView` uses `android.support.v7.widget.DefaultItemAnimator` . Only way to retain Alpha set in original onBind is to set: `recyclerView.setItemAnimator(null); `

It would be ideal for the alpha animator to return back to a set value, not always return to 1. 
The other alternative would be to disable it for certain items during creation or onBind. Worst case would be to get a callback to the item after item animation

**Comment by mikepenz** [comment]
@ncapdevi writing your own item animator ;) or using provided ones. Or setting the alpha on a different view element instead of the `itemView` 

And no it does not have to do with the `FastAdapter` the `ItemAnimator` is from the android system ;)

**Comment by ncapdevi** [comment]
You're right, it goes up the the DefaultItemAnimator. I realized that after further investigation. Thanks for the help.

**Comment by mikepenz** [comment]
@ncapdevi you can for exmample use my `ItemAnimators` lib and have your own `DefaultAnimator` class written: https://github.com/mikepenz/ItemAnimators/blob/develop/library/src/main/java/com/mikepenz/itemanimators/DefaultAnimator.java which will then for example animate not on the `itemView` (still not sure which other view you would use. 

a different solution for you would be to have one additional layout (would deepen the layout structure)

or you jsut set the alpha on the texts / views etc which should have it
