### ISSUE TITLE
Predicate.filter should return true if item must stay

### ISSUE THREAD

**Issue by IlyaGulya** [mikepenz/FastAdapter#285]
Hi! I've just began using this awesome library, thanks for it!
But, i've found some strange thing: method `Predicate.filter(Item, CharSequence)` should return false, if item must stay in adapter.
This behaviour is opposite to same named methods in such default things, like RxJava, or Stream API and more others. I think it is not obvious for most of people. Shouldn't behaviour of adapter be the same as default in all other Java world?

**Comment by mikepenz** [comment]
@IlyaGulya thank you very much. 

Hmmm I was referring to the methods name itself `filter` so true --> filter out. false don't filter out 

But I see what you mean. I am not sure if it is such a good idea to change this behaviour at this point of the project

**Comment by IlyaGulya** [comment]
@mikepenz I think you can add this to roadmap for next major release, for example

**Comment by FabianTerhorst** [comment]
@IlyaGulya you can add suggestions to the #294 pr.

**Comment by FabianTerhorst** [comment]
You can take a look into the latest commits from the pr. Filter should have the correct behavior now.

**Comment by IlyaGulya** [comment]
Yeah, i've already seen them. Cool, thank you!
