### ISSUE TITLE
Handling click events on an IItem which has multiple buttons

### ISSUE THREAD

**Issue by rakesh1988** [mikepenz/FastAdapter#286]
I updated the library version and i am missing something on how to handle the scenario. 
Previously, I used to have a mClickListenerHelper.listen which was defined inside onPostCreateViewHolder. now i am not sure how to use it with  fastAdapter.withItemEvent().

How can i specify different click events inside the class that extends ClickEventHook<>

**Comment by mikepenz** [comment]
@rakesh1988 there is the method `onBindMany` which allows you to return a list of views which will be reacting to this hook:

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/listeners/EventHook.java#L17

**Comment by rakesh1988** [comment]
so the 
onClick(View view, int position, FastAdapter<IItem> fastAdapter, IItem item)
will react only for those that i return via onBindMany() ?

How do i differentiate view inside onClick? because I dont have a viewHolder object to compare with

**Comment by mikepenz** [comment]
exactly. you just define on which views the even hook is bound and then you will get back the event. 

and if you have different eventhooks you just add more to the `FastAdapter`

**Comment by rakesh1988** [comment]
so, if i have 5 buttons in my IItem, I need to do a  mFastAdapter.withItemEvent 5 times?
Sorry if I am asking dumb questions

**Comment by mikepenz** [comment]
@rakesh1988 if those 5 buttons have different actions. yes.

**Comment by rakesh1988** [comment]
Thank you very much..
was there any rationale behind deprecating the mClickListenerHelper.listen method?

**Comment by mikepenz** [comment]
@rakesh1988 as it was not so flexible, and not reuseable. The eventhook can be defined in the item so it can be encapsuled and you clean up the activity.
