### ISSUE TITLE
There are no articles on fastAdapter design..

### ISSUE THREAD

**Issue by zhangle1** [mikepenz/FastAdapter#288]
I try to understand the code, but I do not seem to grasp the focus,Thanks for your code.→_→

**Comment by mikepenz** [comment]
@zhangle1 sorry I am not sure about your question. What do you need?

**Comment by tilmanginzel** [comment]
Here's a blog article, maybe it will help: http://blog.grafixartist.com/recyclerview-adapter-android-made-fast-easy/

**Comment by hamdache202** [comment]
try adding "rv.setLayoutManager(new LinearLayoutManager(this));" before setting adapter.

**Comment by mikepenz** [comment]
@tilmanginzel @hamdache202 thanks for answering
