### ISSUE TITLE
GenericItemAdapter and FooterAdapter, OnClickListener

### ISSUE THREAD

**Issue by hannta** [mikepenz/FastAdapter#289]
Thanks for the great library! I have issues setting click listener when I have different types of items.

```
mItemAdapter = new GenericItemAdapter<>(new Function<Location, LocationItem>() {
  @Override
    public LocationItem.apply(location) {
      return new LocationItem(location);
    }
  });

mFooterAdapter = new FooterAdapter<IItem>();
mFooterAdapter.add(new LocationFooterItem());
mLocationsFastAdapter.withOnClickListener(this);

...

@Override
public boolean onClick(View v, IAdapter<RouteLocationInputItem> adapter, RouteLocationInputItem item, int position) {
  ...
}

```

With this, I get java.lang.ClassCastException when I click the footer item, as it is not type of RouteLocationInputItem. How should I set onClick listener types (and GenericItemAdapter types?) to make this work?

**Comment by mikepenz** [comment]
@hannta if you have different item types you will have to make sure your `FastAdapter` is typed with the most common type. which will in all cases be at least `IItem`- 

So your `onClick` will then also come with `IAdapter<IItem>`, and an `IItem item`

**Comment by hannta** [comment]
Thanks @mikepenz
