### ISSUE TITLE
difference between FastAdapter and FastItemAdapter

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#290]
Hi.
this library looks awesome and im trying to start playing around with it, but i immediately ran into something i dont understand and cant seem to find explanation for:
can you please provide some information about "core", "commons", and "extensions"?
it is not explained what functionality each one includes and i dont want to load all of them into my app if i dont have to.

for example:
in the "How to use" section you are using FastItemAdapter which is **not** part of "core"... 
what is the difference between FastAdapter and FastItemAdapter? why should i use FastItemAdapter and not just FastAdapter?

i'm sure ill run into more questions in the future, and i really wish i didnt have to open a new issue every time, however there is no link to documentation of this library and scenarios where i should use one thing over another (e.g. FastItemAdapter over FastAdapter)

many thanks!

**Comment by FabianTerhorst** [comment]
@or-dvir the FastItemAdapter is extending the FastAdapter and holding / wrapping the ItemAdapter. https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/commons/adapters/FastItemAdapter.java#L24

**Comment by FabianTerhorst** [comment]
The FastItemAdapter contains basically all methods from ItemAdapter and ofc from FastAdapter.

**Comment by or-dvir** [comment]
@FabianTerhorst yes i saw that, but i dont understand why. in order to use FastItemAdapter i need to also add "commons" to my dependencies.. i wonder if thats really necessary. what "Extra" features does FastItemAdapter offer that are not included in FastAdapter?

**Comment by FabianTerhorst** [comment]
You just need less code.

**Comment by mikepenz** [comment]
@FabianTerhorst thanks for answering. 

@or-dvir as @FabianTerhorst already pointed out correctly. It just simplifies what you have to write for a very easy setup. the commons library in general provides classes which simplify things. in general the core dependency is capable of doing everything (some thing might just need a few more lines)

**Comment by or-dvir** [comment]
@mikepenz thank you for your answer.
is it possible to provide a more details explanation about which features are available in each of the dependencies? is there a guide somewhere that i missed?

**Comment by mikepenz** [comment]
@or-dvir you can use the javadoc to see which dependency contains what:
http://javadoc.io/doc/com.mikepenz/fastadapter/2.1.5
http://javadoc.io/doc/com.mikepenz/fastadapter-commons/2.1.0
http://javadoc.io/doc/com.mikepenz/fastadapter-extensions/2.1.0

**Comment by or-dvir** [comment]
@mikepenz thank you. i missed those somehow... will you please add those links to the readme.md?
