### ISSUE TITLE
Displaying placeholder for a RecyclerView

### ISSUE THREAD

**Issue by rakesh1988** [mikepenz/FastAdapter#292]
How can I set my RecyclerView to show a skeleton structure of the View, before it gets the data from API and display the contents.

**Comment by mikepenz** [comment]
@rakesh1988 in general that's no task for the adapter. 

You could create a `PlaceHolderItem` for your project though, which just has "match_parent" as height, and fills up the whole RV with your information

**Comment by FabianTerhorst** [comment]
You can take a look at https://github.com/florent37/FiftyShadesOf

**Comment by FabianTerhorst** [comment]
or https://github.com/elye/loaderviewlibrary

**Comment by rakesh1988** [comment]
OMG!!!! this is exactly what I was looking for :)
