### ISSUE TITLE
OnClick() is also triggering when doing long click

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#293]
hi.
im exploring this awesome library and i have noticed some behavior which i think is weird.
the method OnClick() is triggering also if i long-click an item. is this by design?

shouldn't click and long-click be 2 completely separate events?
i mean, a user (in my opinion) should either clicks an item or long click an item and these 2 events should be handled separately ("regular" clicks should only trigger OnClick(), and long-clicks should only trigger OnLongClick()).

**Comment by mikepenz** [comment]
@or-dvir it depends. how did you implement your listeners?

**Comment by or-dvir** [comment]
i just have withOnClickListener() and withSelectOnLongClick(true).

my intention is that OnClick would be triggered when a user taps an item, and an item would be selected when a user long-clicks an item. however, if i user selects an item by long-clicking it, i do not want OnClick to be triggered.

i could very easily go around this issue by implementing an empty long click listener, but it feels unnecessary.

**Comment by mikepenz** [comment]
@or-dvir ah I see what you mean.

**Comment by or-dvir** [comment]
@mikepenz so is this a bug or by design? is it going to be fixed?

**Comment by mikepenz** [comment]
it was never considered as an issue as it's also the normal behavior of the click listeners. if there is no longlick the single click will trigger. 

it could have bad impact if I change it at this time

**Comment by mikepenz** [comment]
After some more thoughts about this, I came to the conclusion that it would be not a good idea to automatically prevent the onClick event from happening, as some devs may want to have their own logic inside the click event.

Your solution with the longClick listener was the proper fix I think
