### ISSUE TITLE
Right way to load data to recylerview

### ISSUE THREAD

**Issue by rakesh1988** [mikepenz/FastAdapter#295]
This question is more on implementation. I have a BottomSheet which has two recyclerview. Data to these recyclerview is loaded from two different API's. 

Initially I had split the initialization and data load into two methods. 

```
//pseudo code
init(){
//recyclerview has fixedsize
//recyclerview set layout manager
//recyclerview set adapter
}
```

every time i have to change data of the recyclerview i used to call below method
```
//pseudo code again
loadData(){
//fastAapter.clear()
//make a retrofit api call and on success do fastAapter.add()
}
```
For some strange reason, data never used to populate into the recyclerview. Then i merged both the methods. and every time i load data, i initialise recyclerview. 

Am I doing it right, or I need to debug why the data is not loading in the first setup.?

**Comment by mikepenz** [comment]
It is important that the LayoutManager is set before items are added to the adapter. Also make sure to set the adapter to the RV first. 

other than this it's fine. 
better would be if you would know what changes and do not do a clear everytime you get new data

**Comment by rakesh1988** [comment]
Thank you very much for the quick reply. In continuation to the doubt, I have another problem. I need your help in debugging further. Once I do a ```adapter.add(new Item(item));``` ,  ```getLayoutRes()``` method in my Item class never gets called. Only ```getType()``` is called. What can be the reason. Due to this, my recyclerview never shows up.

**Comment by mikepenz** [comment]
your adpater is bound to the RV?
the layout manager was set before?
the RV is visible
the item is added in the main thread?

**Comment by rakesh1988** [comment]
This is how I am initialising and adding data to RV.
RV is visible and is declared as 
```
 <android.support.v4.widget.NestedScrollView
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <android.support.v7.widget.RecyclerView
                    android:id="@+id/rv_bottom_sheet_store_comments"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    />
            </android.support.v4.widget.NestedScrollView>
```

```
    private void loadLatestCommentsToRecyclerView(String storeId)
    {
        
        mCommentRecyclerView.setHasFixedSize(true);

        mCommentRecyclerView.setLayoutManager(new LinearLayoutManager(getApplicationContext(), LinearLayoutManager.VERTICAL, false));
        mCommentRecyclerView.setItemAnimator(new DefaultItemAnimator());
        mCommentRecyclerView.setAdapter(mStoreCommentFastAdapter);

        Call<List<StoreComment>> call = new D2hApiHelper().
                getStoreComments(storeId);
        call.enqueue(new Callback<List<StoreComment>>()
        {

            @Override
            public void onResponse(Call<List<StoreComment>> call, Response<List<StoreComment>> response)
            {
                Timber.d("I got all comments");
                for (StoreComment comment :
                        response.body())
                {
                    mStoreCommentFastAdapter.add(new StoreCommentItem(comment));
                }
            }

            @Override
            public void onFailure(Call<List<StoreComment>> call, Throwable t)
            {
                if (t instanceof HttpException)
                {

                }
                Timber.e("unable to get data");
                Timber.e(t);
            }
        });
    }
```
