### ISSUE TITLE
notifyAdapterSubItemsChanged - does not reset withExpanded

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#296]
`notifyAdapterSubItemsChanged` is apperently collapsing the item and therefore it should update the items state as well. Otherwise calling `adapter.expand(...)` won't work with this item anymore...

It should call `parent.withIsExpanded(false)`... And the adapters list of expanded items should be updated as well

**Comment by MFlisar** [comment]
**EDIT**

Seems I was wrong, calling `notifyAdapterItemChanged` does collapse the header.

**Here's a code example that brings up some questions**

Following works, if I want to add a sub item to a header:

    int displayedHeaderIndex = fastAdapter.getAdapterPosition(header);
	header.addSubItem(relSubItemIndex, itemToAdd);
	if (header.isExpanded())
	{
		fastAdapter.notifyAdapterSubItemsChanged(displayedHeaderIndex, header.getSubItems().size() - 1);
		fastAdapter.notifyAdapterItemChanged(displayedHeaderIndex);
		fastAdapter.expand(displayedHeaderIndex);
	}
	else
		fastAdapter.notifyAdapterItemChanged(displayedHeaderIndex);

**Question**

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1679 will update `mExpanded`, but the function I use (https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1706) with my ID based position state management does NOT update. Is this intended?

**Comment by mikepenz** [comment]
@MFlisar yes this is intended. As with the ID based state management we do no longer depend on the position, but will just check the items and their current internal state. (with the position based we always check via the mExpanded map)

**Comment by MFlisar** [comment]
Thanks for the clarification
