### ISSUE TITLE
Wrapping adapters with the AbstractWrapAdapter

### ISSUE THREAD

**Issue by YuriHeupa** [mikepenz/FastAdapter#298]
I'm trying to combine all of the AbstractWrapAdapter, HeaderAdapter, FooterAdapter and FastItemAdapter together, but there's a bug when I try to insert items on the FastItemAdapter, currently I use the FooterAdapter as a loader for a endless scroller, and the AbstractWrapAdapter to show ads between items, but I'm facing a weird issue that I couldn't manage to fix, when I insert items to the FastItemAdapter it notifies wrong positions changes to the recyclerview, making the animations offsets behave strange. I already tried to override the `notifyAdapterItemRangeInserted` from my FastItemAdapter, to change the positions with another ones, but I got no success.
Looks like the AbstractWrapAdapter isn't a type of ItemAdapter, so it doesn't get registered on the adapters queue on the FastAdapter after wraping them all. This difficults the AbstractWrapAdapter info tracking.. Is there an easy way to fix this?

**Comment by FabianTerhorst** [comment]
@YuriHeupa could you please show the code where you are wrapping the adapters together?

**Comment by YuriHeupa** [comment]
Surely, here's the code where I define the adapters:

```java
HeaderAdapter<HeaderItem> headerAdapter = new HeaderAdapter<>();
FooterAdapter<ProgressLoaderItem> footerAdapter = new FooterAdapter<>();
AdmobAdapter adAdapter = new AdmobAdapter();
FastItemAdapter<SimpleItem> fastItemAdapter = new FastItemAdapter<SimpleItem>() {
    @Override
    public int getHolderAdapterPosition(RecyclerView.ViewHolder holder) {
        int pos = super.getHolderAdapterPosition(holder);
        return pos - adAdapter.itemInsertedBeforeCount(pos);
    }
};
mRecyclerView.addOnScrollListener(new EndlessRecyclerOnScrollListener(footerAdapter, adAdapter) {
    @Override
    public void onLoadMore(final int currentPage) {
        mRecyclerView.post(() -> {
            footerAdapter.clear();
            footerAdapter.add(new ProgressLoaderItem());
        });
        ...some long job with currentPage(items) {
                footerAdapter.clear();
        fastItemAdapter.add(items);
        }
    }
};
mRecyclerView.setHasFixedSize(true);
mRecyclerView.setAdapter(adAdapter.wrap(footerAdapter.wrap(headerAdapter.wrap(fastItemAdapter))));
```
And for reference, here's my AdMobAdapter:
```java

public class AdmobAdapter extends AbstractWrapAdapter<AdItem> {
    private static final int SPAN = 10;

    public AdmobAdapter() {
        super(Collections.singletonList(new AdItem()));
    }

    @Override
    public boolean shouldInsertItemAtPosition(int position) {
        return ((position + 1) % SPAN) == 0;
    }

    @Override
    public int itemInsertedBeforeCount(int position) {
        return position/SPAN;
    }

    @Override
    public AdItem getItem(int position) {
        if (shouldInsertItemAtPosition(position)) {
            return getItems().get(0);
        }
        return null;
    }

}
```
As you can see, my Ad adapter reuses the first Item through all SPANS, which occur between each 10 items.

**Comment by FabianTerhorst** [comment]
could you test
 ```java
mRecyclerView.setAdapter(adAdapter.wrap(footerAdapter.wrap(headerAdapter.wrap(fastItemAdaper.getItemAdapter)))); 
```
?

**Comment by YuriHeupa** [comment]
@FabianTerhorst same problem.. here's a gif demonstrating what's happening:
![](https://media.giphy.com/media/l0HlQPLkXolHG3sSk/source.gif)

Notice that the animation starts to get weird throughout the items loading

**Comment by TheMaxCoder** [comment]
@YuriHeupa I'm wrapping `FastItemAdapter` in an ad adapter just like you doing but when implementing the search filter on `FastItemAdapter` app is crashing with
 `java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 4(offset:0).state:8`

any idea how can I resolve this? without `AbstractWrapAdapter` filter works just fine!

Thanks

**Comment by YuriHeupa** [comment]
@TheMaxCoder please provide some code of how you are dealing with items on your adapters, maybe you're missing some `notify` calls to the ads adapter or whatever..

**Comment by TheMaxCoder** [comment]
```
mFastAdapter = new FastItemAdapter<>();
@Override
public boolean onQueryTextChange(String newText) {
        mFastAdapter.filter(newText);
        mFastAdapter.withFilterPredicate(new IItemAdapter.Predicate<SimpleItem>() {
         @Override
          public boolean filter(SimpleItem item, CharSequence constraint) {
                        return !item.getName().toLowerCase().contains(constraint);
                    }
                });
                return true;
            }
```

This works just as expected, Now if I wrap `FastItemAdapter` with a let's say your `AdMobAdapter` like this

`mRecyclerView.setAdapter(admobAdapter.wrap(mFastAdapter));`

it throws an above-mentioned exception on searching, I don't know how can I make search filter work, Ads are not important to be visible when a user is searching for the items so I should clear it or something?

**Comment by YuriHeupa** [comment]
First of all, it's a bit weird that the filter predicate is being defined inside the `onQueryTextChange` callback, it's gonna be better if you define it once outer of the callback scope.
Since AbstractWrapAdapter doesn't implement an ItemAdapter, any others Item Adapters will not keep track of it, so the wrap adapter doesn't get notified about any changes. You need to explicit notify the ads adapter when the list get filtered by calling `admobAdapter.notifyDataSetChanged()`, you need to do it right after the items get filtered.

There's a listener that you can set in the ItemAdapter through `withItemFilterListener(ItemFilterListener)`, this will provide you a `itemsFiltered()` callback, which you can use to notify the ads adapter. Something like:

```java
mFastAdapter.getItemAdapter().withItemFilterListener(new ItemAdapter.ItemFilterListener() {
    @Override
    public void itemsFiltered() {
        admobAdapter.notifyDataSetChanged();
    }
});
```

Or if you don't want to shows ads while searching for the items you could use a solution like [this gist](https://gist.github.com/YuriHeupa/926bae29c1b687b0725c5680380f0780), with this you must call `setShowAds(boolean show)` to hide/show ads when wanted.

**Comment by YuriHeupa** [comment]
But its worth remembering that this is an AbstractWrapAdapter issue, when this get fixed we'll not need this workaround.

**Comment by TheMaxCoder** [comment]
Yeah, that makes sense, Thank you so much for the explanation, I was kinda blind there.
Really appreciated.

**Comment by mikepenz** [comment]
@TheMaxCoder @YuriHeupa sorry for the late answer. 

Could you please try the following: 
https://github.com/mikepenz/FastAdapter/issues/275#issuecomment-263085653

This will make sure the fastAdapter internally will also reference the correct positions, as a wrapAdapter moves all around and may lead to issues like the one above

**Comment by TheMaxCoder** [comment]
@YuriHeupa can you please confirm `mFastAdapter.clear()` works when wrapped it in `AdmobAdapter `?
For me, it doesn't work, neither the `UndoHelper`. 
For the workaround,  I have to `setShowAd(false)` right before performing these two actions.

Though I have set the `FilterListener` as you suggested above and it works with the filter just fine.

**Comment by YuriHeupa** [comment]
@TheMaxCoder You should notify the AdmobAdapter whenever you make changes to the FastAdapter items, so when you call `mFastAdapter.clear()` you need also to issue `admobAdapter.notifyDataSetChanged()`

@mikepenz Does this issue have any date estimate to be fixed?

**Comment by FabianTerhorst** [comment]
@YuriHeupa could you provide a test case where the item count calculation failes? https://github.com/mikepenz/FastAdapter/blob/develop/library/src/test/java/com/mikepenz/fastadapter/FastAdapterTest.java

**Comment by mikepenz** [comment]
I close this as there was no more activity since over a month. Please report back to re-open
