### ISSUE TITLE
¿ listen equivalent ?

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/FastAdapter#299]
I already know it exists the new ClickEventHook, it's works but... i need to handle the click of a specific view (button), outside of the adapter, like the old listen....because  I need to call a function that is in the activity

how do I do that ?

**Comment by YuriHeupa** [comment]
@seba123neo there is a method called [onBindMany](https://github.com/mikepenz/FastAdapter/blob/caaa4d435d64173dcfbd7c65aef9caca38091097/library-core/src/main/java/com/mikepenz/fastadapter/listeners/EventHook.java#L17) on the ClickEventHook which allows you to return a list of views which will be reacting to this hook.

You can follow this implementation example https://github.com/mikepenz/FastAdapter/blob/caaa4d435d64173dcfbd7c65aef9caca38091097/app/src/main/java/com/mikepenz/fastadapter/app/items/ImageItem.java#L216-L221.

**Comment by seba123neo** [comment]
yes, but i need the code to move outside of the adapter, i need to move to the appcompatactivity....
i need call a function from the activity...

is possible to move the code of the entire ClickEventHook class to the activity ?

**Comment by mikepenz** [comment]
@seba123neo you can still do this. you can just implement the `ClickEventHook` as a anonymous class and pass it to the `FastAdapter` as you would do with any other listener too

**Comment by seba123neo** [comment]
Excellent, it's working now, thanks to both !!!
