### ISSUE TITLE
Set Span For FooterAdapter

### ISSUE THREAD

**Issue by tomeroto** [mikepenz/FastAdapter#301]
Hi everyone,

I have problem to use grid layout with 3 columns with footer for progressbar.

new GridLayoutManager(this, 3);

But i don't know how to make the footer is span to 3 like this:

----------
| 1 | 2 | 3 |
| Footer  |

**Comment by FabianTerhorst** [comment]
you can set the SpanSizeLookup to change the span size for an item.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/b8467b6c9850f1c2e7c0b42810e455ae9f888dcf/app/src/main/java/com/mikepenz/fastadapter/app/IconGridActivity.java#L57
