### ISSUE TITLE
Delay In Adapter

### ISSUE THREAD

**Issue by saeedrooyekhat** [mikepenz/FastAdapter#303]
when i scroll views and run bindView , between running two bind view is about 120 to 260 millisecond time!
i just show some text , like "1" , "2" , "3" , ...

12-27 15:49:33.600 4813-4813/ I/WWW: 12
12-27 15:49:33.860 4813-4813/ I/WWW: 1

or

12-27 15:49:33.430 4813-4813/ I/WWW: 12
12-27 15:49:33.590 4813-4813/ I/WWW: 1

this time what is for that and how can decrease this time? 
because this make a delay in my scroll for show each item. my phone is Huawei P6

**Comment by mikepenz** [comment]
@saeedrooyekhat depends on what you are doing inside the `onBind` method

**Comment by saeedrooyekhat** [comment]
in bindView from run first line of code to end is about 10 millisecond , but after finish codes from one bindview and start other it takes about 150 milliseconds

**Comment by saeedrooyekhat** [comment]
my bindView Codes

`
public void bindView(final VH holder, List<Object> payloads) {
        super.bindView(holder, payloads);

        /**
         * this use for select foreground in activity chat for search item and hash item
         */
        Log.i("WWW", "1");
        mMessage.view = holder.itemView;

        /**
         * noinspection RedundantCast
         */
        if (!isSelected() && ((FrameLayout) holder.itemView).getForeground() != null) {
            /**
             * noinspection RedundantCast
             */
            ((FrameLayout) holder.itemView).setForeground(null);
        }
        Log.i("WWW", "2");
        /**
         * only will be called when message layout is directional-base (e.g. single chat)
         */
        if (directionalBased) {
            if ((mMessage.sendType == MyType.SendType.recvive) || type == ProtoGlobal.Room.Type.CHANNEL) {
                updateLayoutForReceive(holder);
            } else if (mMessage.sendType == MyType.SendType.send) {
                updateLayoutForSend(holder);
            }
        }

        Log.i("WWW", "3");
        if (!mMessage.isTimeOrLogMessage()) {
            AppUtils.rightMessageStatus((ImageView) holder.itemView.findViewById(R.id.cslr_txt_tic), ProtoGlobal.RoomMessageStatus.valueOf(mMessage.status), mMessage.forwardedFrom != null ? mMessage.forwardedFrom.getMessageType() : mMessage.messageType, mMessage.isSenderMe());
        }
        Log.i("WWW", "4");
        /**
         * display 'edited' indicator beside message time if message was edited
         */
        if (holder.itemView.findViewById(R.id.txtEditedIndicator) != null) {
            if (mMessage.isEdited) {
                holder.itemView.findViewById(R.id.txtEditedIndicator).setVisibility(View.VISIBLE);
            } else {
                holder.itemView.findViewById(R.id.txtEditedIndicator).setVisibility(View.GONE);
            }
        }
        Log.i("WWW", "5");
        /**
         * display user avatar only if chat type is GROUP
         */
        if (type == ProtoGlobal.Room.Type.GROUP) {
            if (!mMessage.isSenderMe()) {
                holder.itemView.findViewById(R.id.messageSenderAvatar).setVisibility(View.VISIBLE);

                holder.itemView.findViewById(R.id.messageSenderAvatar).setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        messageClickListener.onSenderAvatarClick(v, mMessage, holder.getAdapterPosition());
                    }
                });


                HelperAvatar.getAvatar(Long.parseLong(mMessage.senderID), HelperAvatar.AvatarType.USER, new OnAvatarGet() {
                    @Override
                    public void onAvatarGet(final String avatarPath, long ownerId) {
                        G.handler.post(new Runnable() {
                            @Override
                            public void run() {
                                ImageLoader.getInstance().displayImage(AndroidUtils.suitablePath(avatarPath), (ImageView) holder.itemView.findViewById(R.id.messageSenderAvatar));
                            }
                        });
                    }

                    @Override
                    public void onShowInitials(final String initials, final String color) {
                        G.handler.post(new Runnable() {
                            @Override
                            public void run() {
                                ((ImageView) holder.itemView.findViewById(R.id.messageSenderAvatar)).setImageBitmap(com.iGap.helper.HelperImageBackColor.drawAlphabetOnPicture((int) holder.itemView.getContext().getResources().getDimension(R.dimen.dp60), initials, color));
                            }
                        });
                    }
                });

            } else {
                holder.itemView.findViewById(R.id.messageSenderAvatar).setVisibility(View.GONE);
            }
        } else {
            if (!mMessage.isTimeOrLogMessage()) {
                //holder.itemView.findViewById(R.id.messageSenderAvatar).setVisibility(View.GONE);
            }
        }
        Log.i("WWW", "6");
        /**
         * set message time
         */
        if (holder.itemView.findViewById(R.id.cslr_txt_time) != null) {
            ((TextView) holder.itemView.findViewById(R.id.cslr_txt_time)).setText(formatTime());
        }
        Log.i("WWW", "7");
        replyMessageIfNeeded(holder);
        Log.i("WWW", "8");
        forwardMessageIfNeeded(holder);
        Log.i("WWW", "9");

        Realm realm = Realm.getDefaultInstance();
        RealmRoomMessage roomMessage = realm.where(RealmRoomMessage.class).equalTo(RealmRoomMessageFields.MESSAGE_ID, Long.parseLong(mMessage.messageID)).findFirst();
        if (roomMessage != null) {
            prepareAttachmentIfNeeded(holder, roomMessage.getForwardMessage() != null ? roomMessage.getForwardMessage().getAttachment() : roomMessage.getAttachment(), mMessage.forwardedFrom != null ? mMessage.forwardedFrom.getMessageType() : mMessage.messageType);
        }
        realm.close();
        Log.i("WWW", "10");
        TextView messageText = (TextView) holder.itemView.findViewById(R.id.messageText);
        if (messageText != null) {
            if (messageText.getParent() instanceof LinearLayout) {
                ((LinearLayout.LayoutParams) ((LinearLayout) messageText.getParent()).getLayoutParams()).gravity = AndroidUtils.isTextRtl(mMessage.forwardedFrom != null ? mMessage.forwardedFrom.getMessage() : mMessage.messageText) ? Gravity.RIGHT : Gravity.LEFT;
            }
        }
        Log.i("WWW", "11");

        /**
         * show vote layout for channel otherwise hide layout
         * also get message state for channel
         */
        if ((type == ProtoGlobal.Room.Type.CHANNEL)) {
            showVote(holder);
        } else {
            if (mMessage.forwardedFrom != null) {
                RealmRoom realmRoom = realm.where(RealmRoom.class).equalTo(RealmRoomFields.ID, mMessage.forwardedFrom.getRoomId()).findFirst();
                if (realmRoom != null && realmRoom.getType() == ProtoGlobal.Room.Type.CHANNEL) {
                    showVote(holder);
                } else {
                    hideVote(holder);
                }
            } else {
                hideVote(holder);
            }
        }
        Log.i("WWW", "12");
    }
`

**Comment by saeedrooyekhat** [comment]
i use multiple item in adapter , my code in abstract class is

```java
 public void bindView(final VH holder, List<Object> payloads) {
        super.bindView(holder, payloads);

        mMessage.view = holder.itemView;
        if (!isSelected() && ((FrameLayout) holder.itemView).getForeground() != null) {
            ((FrameLayout) holder.itemView).setForeground(null);
        }
        if (directionalBased) {
            if ((mMessage.sendType == MyType.SendType.recvive) || type == ProtoGlobal.Room.Type.CHANNEL) {
                updateLayoutForReceive(holder);
            } else if (mMessage.sendType == MyType.SendType.send) {
                updateLayoutForSend(holder);
            }
        }

        if (!mMessage.isTimeOrLogMessage()) {
            AppUtils.rightMessageStatus((ImageView) holder.itemView.findViewById(R.id.cslr_txt_tic), ProtoGlobal.RoomMessageStatus.valueOf(mMessage.status), mMessage.forwardedFrom != null ? mMessage.forwardedFrom.getMessageType() : mMessage.messageType, mMessage.isSenderMe());
        }
        if (holder.itemView.findViewById(R.id.txtEditedIndicator) != null) {
            if (mMessage.isEdited) {
                holder.itemView.findViewById(R.id.txtEditedIndicator).setVisibility(View.VISIBLE);
            } else {
                holder.itemView.findViewById(R.id.txtEditedIndicator).setVisibility(View.GONE);
            }
        }
        if (type == ProtoGlobal.Room.Type.GROUP) {
            if (!mMessage.isSenderMe()) {
                holder.itemView.findViewById(R.id.messageSenderAvatar).setVisibility(View.VISIBLE);

                holder.itemView.findViewById(R.id.messageSenderAvatar).setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        messageClickListener.onSenderAvatarClick(v, mMessage, holder.getAdapterPosition());
                    }
                });


                HelperAvatar.getAvatar(Long.parseLong(mMessage.senderID), HelperAvatar.AvatarType.USER, new OnAvatarGet() {
                    @Override
                    public void onAvatarGet(final String avatarPath, long ownerId) {
                        G.handler.post(new Runnable() {
                            @Override
                            public void run() {
                                ImageLoader.getInstance().displayImage(AndroidUtils.suitablePath(avatarPath), (ImageView) holder.itemView.findViewById(R.id.messageSenderAvatar));
                            }
                        });
                    }

                    @Override
                    public void onShowInitials(final String initials, final String color) {
                        G.handler.post(new Runnable() {
                            @Override
                            public void run() {
                                ((ImageView) holder.itemView.findViewById(R.id.messageSenderAvatar)).setImageBitmap(com.iGap.helper.HelperImageBackColor.drawAlphabetOnPicture((int) holder.itemView.getContext().getResources().getDimension(R.dimen.dp60), initials, color));
                            }
                        });
                    }
                });

            } else {
                holder.itemView.findViewById(R.id.messageSenderAvatar).setVisibility(View.GONE);
            }
        } else {
            if (!mMessage.isTimeOrLogMessage()) {
                holder.itemView.findViewById(R.id.messageSenderAvatar).setVisibility(View.GONE);
            }
        }
        if (holder.itemView.findViewById(R.id.cslr_txt_time) != null) {
            ((TextView) holder.itemView.findViewById(R.id.cslr_txt_time)).setText(formatTime());
        }
        replyMessageIfNeeded(holder);
        forwardMessageIfNeeded(holder);

        Realm realm = Realm.getDefaultInstance();
        RealmRoomMessage roomMessage = realm.where(RealmRoomMessage.class).equalTo(RealmRoomMessageFields.MESSAGE_ID, Long.parseLong(mMessage.messageID)).findFirst();
        if (roomMessage != null) {
            prepareAttachmentIfNeeded(holder, roomMessage.getForwardMessage() != null ? roomMessage.getForwardMessage().getAttachment() : roomMessage.getAttachment(), mMessage.forwardedFrom != null ? mMessage.forwardedFrom.getMessageType() : mMessage.messageType);
        }
        realm.close();
        TextView messageText = (TextView) holder.itemView.findViewById(R.id.messageText);
        if (messageText != null) {
            if (messageText.getParent() instanceof LinearLayout) {
                ((LinearLayout.LayoutParams) ((LinearLayout) messageText.getParent()).getLayoutParams()).gravity = AndroidUtils.isTextRtl(mMessage.forwardedFrom != null ? mMessage.forwardedFrom.getMessage() : mMessage.messageText) ? Gravity.RIGHT : Gravity.LEFT;
            }
        }

        if ((type == ProtoGlobal.Room.Type.CHANNEL)) {
            showVote(holder);
        } else {
            if (mMessage.forwardedFrom != null) {
                RealmRoom realmRoom = realm.where(RealmRoom.class).equalTo(RealmRoomFields.ID, mMessage.forwardedFrom.getRoomId()).findFirst();
                if (realmRoom != null && realmRoom.getType() == ProtoGlobal.Room.Type.CHANNEL) {
                    showVote(holder);
                } else {
                    hideVote(holder);
                }
            } else {
                hideVote(holder);
            }
        }
    }
```

and for exmaple one of the my items is TextItem

```java
public void bindView(final ViewHolder holder, List payloads) {
        super.bindView(holder, payloads);

        String text;
        if (mMessage.forwardedFrom != null) {
            text = mMessage.forwardedFrom.getMessage();
        } else {
            text = mMessage.messageText;
        }
        setTextIfNeeded(holder.messageText, text);
    }
```

also i use the following codes for TextItem xml layout

```java
<?xml version="1.0" encoding="utf-8"?>

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:tools="http://schemas.android.com/tools"
             android:id="@+id/chatSubLayoutMessage"
             android:layout_width="match_parent"
             android:layout_height="wrap_content"
             android:maxWidth="@dimen/chatBoxMaxWidth"
             android:textDirection="firstStrong">

    <RelativeLayout
        android:id="@+id/mainContainer"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        tools:ignore="UselessParent">

        <com.iGap.module.CircleImageView
            android:id="@+id/messageSenderAvatar"
            android:layout_width="@dimen/dp52"
            android:layout_height="@dimen/dp52"
            android:layout_marginRight="@dimen/dp8"
            android:src="@mipmap/empty"/>

        <LinearLayout
            android:id="@+id/middleLayout"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_toEndOf="@+id/messageSenderAvatar"
            android:layout_toRightOf="@+id/messageSenderAvatar"
            android:orientation="vertical">

            <android.support.v7.widget.CardView
                android:id="@+id/contentContainer"
                style="@style/ChatMessages.CardView"
                android:minWidth="150dp">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:minWidth="150dp"
                    android:orientation="vertical">

                    <include
                        android:id="@+id/replayLayout"
                        layout="@layout/chat_sub_layout_reply"/>

                    <include
                        android:id="@+id/cslr_ll_forward"
                        layout="@layout/chat_sub_layout_forward"/>

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:orientation="vertical"
                        >

                        <io.github.meness.emoji.EmojiTextView
                            android:id="@+id/messageText"
                            style="@style/ChatMessages.EmojiTextView"
                            android:text="SAMPLE TEXT"/>

                    </LinearLayout>

                    <include layout="@layout/chat_sub_layout_messages_time"/>
                </LinearLayout>
            </android.support.v7.widget.CardView>
        </LinearLayout>

        <RelativeLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignLeft="@+id/middleLayout"
            android:layout_alignStart="@+id/middleLayout"
            android:layout_below="@+id/middleLayout">

            <include layout="@layout/chat_sub_layout_messages_vote"/>

        </RelativeLayout>
    </RelativeLayout>
</FrameLayout>
```

i have a forward and reply layout that included in TextItem xml layout and setVisibiliy Gone if message is not forwarded or replied and also have a chat_sub_layout_messages_vote that setVisibility Gone in a large number of items like forward and reply layout.

when i scroll items , bind view in abstract class run lower than 10 milliseconds , but for execute other bind view have a delay about 150 milliseconds.

Where is my mistake in this Code ?

**Comment by FabianTerhorst** [comment]
Its not related to the library, the default RecyclerView.Adapter would have the exact same result.

**Comment by saeedrooyekhat** [comment]
is there any way for call bindView before see item?
i set cacheSize 1000,

**Comment by mikepenz** [comment]
https://medium.com/google-developers/recyclerview-prefetch-c2f269075710#.26zcdl7jy
