### ISSUE TITLE
Ripple in checkbox sample ?

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/FastAdapter#304]
Hi, in the checkbox sample of the library, 

how activate the ripple in the item click ?

thanks.

**Comment by mikepenz** [comment]
@seba123neo which ripple for what?

**Comment by seba123neo** [comment]
I mean the "ripple effect" when a row is "pressed", in the Checkbox activity from the fastadapter sample....

Nothing happens when i press the item...only when press the checkbox...

**Comment by FabianTerhorst** [comment]
```java holder.itemView.setBackgroundResource(FastAdapterUIUtils.getSelectableBackground(holder.itemView.getContext())); 
```

**Comment by seba123neo** [comment]
Thanks, that's what I wanted !!!
