### ISSUE TITLE
Unable to write an algorithm for filtering out items in a RecyclerView based on a long saved with each item. How to do this using FastAdapter?

### ISSUE THREAD

**Issue by HammadNasir** [mikepenz/FastAdapter#305]
I have several items in a RecyclerView and each item has a long value saved with it. I'm using FastAdapter as the adapter for my recyclerview.

Suppose there are 7 items in the recyclerview with the long values: 11122, 12321, -98811, 8870, -88009, 3398, and -22113.

So, what I want to do is, I want to filter the items based on the above given long values using this logic:

```
if (l <= 1000) {
  // show items with long value <=1000
} else if (l > 1000) {
  // show items with long value >1000
}
```

I tried various things, but nothing worked out.

Please help me with this issue and suggest some algorithm or code with which I can achieve this.

**Comment by HammadNasir** [comment]
@mikepenz please help, dude.

**Comment by Rainer-Lang** [comment]
See sample with predicate.filter

**Comment by HammadNasir** [comment]
@Rainer-Lang please write an example as per my needs... I'm confused!

**Comment by HammadNasir** [comment]
@Rainer-Lang @mikepenz please guys.. please help with this!

**Comment by mikepenz** [comment]
@HammadNasir the sample contains exactly what you need. It showcases how you can use the Filter to filter out items depending on a specific rule. 

The `FastAdapter` provides the interfaces, and the features, the implementation is up to you. 

We can't help you writing code 1:1. 

-------

As a different note. I understand that it is important for you, but we already guided you into the right direction. This is a open source project, and @Rainer-Lang and me doing this for free, we have regular jobs, we have regular lives, and do this in our free time. There is new year now and we want to spend time with our families and have some vacation, even from open source. Never ask for ETAs, you have not bought a service or anything. I do this for free. Please remember this!
