### ISSUE TITLE
RV is not showing data if activity is opened second time

### ISSUE THREAD

**Issue by rakesh1988** [mikepenz/FastAdapter#307]
I am very sure that this is an implementation issue. I have been stuck with this issue from almost a week and it is not leading me anywhere. I created a similar app at https://github.com/rakesh1988/FastAdapterTester.git which also has the same issue. 

When I click on the button in first activity, second activity opens and RV is shown. When I go back and press the button again, for some strange reason, RV is never displayed even though the data is loaded to adapter successfully.

**Comment by mikepenz** [comment]
@rakesh1988 it is definitely unrelated to the `FastAdapter` and has to be a implementation issue at some place. 
Have you tried it with a normal LayoutManager already? 
Could it be some butterknife issue?

**Comment by rakesh1988** [comment]
I have tried without butterknife. it is the same behavior. I'm perplexed.

**Comment by mikepenz** [comment]
@rakesh1988 seems weird. Some activity behaviour or something. Have you debugged, is it calling all method correctly. Can you try to set the data via a handler?

**Comment by rakesh1988** [comment]
I got the issue. I created another plain old adapter and it worked perfectly. only difference was i was setting "setHasFixedSize(true)" on the RV when using fast adapter. I removed it and it works fine now. But how can setHasFixedSize affect this behavior? I am not understanding

**Comment by mikepenz** [comment]
@rakesh1988 make the RV `match_parent` 
https://github.com/rakesh1988/FastAdapterTester/blob/master/app/src/main/res/layout/activity_rv_holder.xml#L11

http://stackoverflow.com/a/28709795/325479
