### ISSUE TITLE
Happy new year! 

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/FastAdapter#308]
And thanks for your hard work on this and your other great libs.

**Comment by FabianTerhorst** [comment]
@mikepenz @Rainer-Lang Happy new year. :tada:

**Comment by mikepenz** [comment]
@FabianTerhorst @Rainer-Lang Thank you very much :) 

Happy new year. Thank you both for all the contributions, and for the help running all the open source projects. 

Looking for an awesome open source 2017 🎉

**Comment by Rainer-Lang** [comment]
@mikepenz Do you remember the starting of FastAdapter and our talk about the "stars" of this lib? :)
You didn't believe..... Now this lib has 1,240 STARS 👍 👍 👍
