### ISSUE TITLE
View Holder Call

### ISSUE THREAD

**Issue by saeedrooyekhat** [mikepenz/FastAdapter#309]
why call viewholder for each item?
i think view holder call just for items that filling page in first item and when scroll item another items not calling view holder, but in my code when i scrolling , viewholder calling for each items.

**Comment by mikepenz** [comment]
@saeedrooyekhat the `RecyclerView` handles and decides how many `ViewHolder`s need to be created, that's nothing the adapter decides.

**Comment by saeedrooyekhat** [comment]
how can avoid from calling ViewHolder for each item?
also is there any way for calling bind view for items that not showing yet in view and when comming this items to the view do no action?

**Comment by mikepenz** [comment]
you have to get more comfortable with the `RecyclerView` APIs. For prefetching I think there is now a new method in the latsest support libraries which allow you to do this. 

for the first issue, it sounds like something in your code causes this issue.

**Comment by saeedrooyekhat** [comment]
@mikepenz Thank you for the time you gave me.

i have a question about fastadapter view holder.

in a simple code for RecyclerView Adapter i write following code

```java


public class MyAdapter extends RecyclerView.Adapter<MyAdapter.ViewHolder> {

    private ArrayList<String> mDataSet;

    public class ViewHolder extends RecyclerView.ViewHolder {

        public TextView txtHeader;
        public TextView txtFooter;
        public ImageView img;


        public ViewHolder(View v) {
            super(v);
            Log.i("WWW", "ViewHolder");
            txtHeader = (TextView) v.findViewById(R.id.firstLine);
            txtFooter = (TextView) v.findViewById(R.id.secondLine);
            img = (ImageView) v.findViewById(R.id.icon);
        }
    }


    public MyAdapter(ArrayList<String> myDataSet) {
        mDataSet = myDataSet;
    }


    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        Log.i("WWW", "onCreateViewHolder");
        View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_recycler_view, parent, false);
        ViewHolder vh = new ViewHolder(v);
        return vh;
    }

    @Override
    public void onBindViewHolder(final ViewHolder holder, final int position) {
        Log.i("WWW", "onBindViewHolder");
        int imageId = G.context.getResources().getIdentifier("image" + (position + 1), "drawable", G.context.getPackageName());
        holder.img.setImageResource(imageId);
    }

    @Override
    public int getItemCount() {
        return mDataSet.size();
    }

}

```

in this code ViewHolder Call just for items that showing in first view and when another views comming to page just onBindViewHolder called, but when i using fastadapter for showing different item, ViewHolder calling for each item, this is a common occurrence or i have problem in my codes?

**Comment by FabianTerhorst** [comment]
Your RecyclerView.Adapter doesn´t use stable ids.

**Comment by saeedrooyekhat** [comment]
i detect why ViewHolder Called in fastadapter sample in my code.

when i using setCacheSize for RecyclerView , ViewHolder called as many set cache size , and when back to see that items don't run any thing , even bindView. 

also when don't use setCacheSize ViewHolder just called for items that exist in view for first time and for another items just called bindView.
