### ISSUE TITLE
add items : several same items displaying

### ISSUE THREAD

**Issue by Calion54** [mikepenz/FastAdapter#310]
Hello,

I have a list of object (there are 20 objects) but when I add in the adapter with `fastAdapter.add(result.getResults())` I got the 5 first items several times (There are 20 objects displaying)
I don't understand why I obtain this result.
I noticed that the ViewHolder is instanced and bindview is call just 5 times...

Thank you in advance for your answer.

**Comment by mikepenz** [comment]
do your items have unique identifiers?

**Comment by Calion54** [comment]
Yes, I sure because I have the same image, description. Before I used the base adapter and it worked...

My Set class :

`public class Set extends AbstractItem<Set, Set.ViewHolder> implements Parcelable {
    public String theme;
    public String year;
    public String idSet;
    public String name;
    public String image;
    public String nbParts;

    public Set(String name, String year, String idSet, String image, String theme, String nbParts) {
        this.name = name;
        this.year = year;
        this.idSet = idSet;
        this.theme = theme;
        this.image = image;
        this.nbParts = nbParts;
    }

    protected Set(Parcel in) {
        theme = in.readString();
        year = in.readString();
        idSet = in.readString();
        name = in.readString();
        image = in.readString();
        nbParts = in.readString();
    }

    public static final Creator<Set> CREATOR = new Creator<Set>() {
        @Override
        public Set createFromParcel(Parcel in) {
            return new Set(in);
        }

        @Override
        public Set[] newArray(int size) {
            return new Set[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(theme);
        dest.writeString(year);
        dest.writeString(idSet);
        dest.writeString(name);
        dest.writeString(image);
        dest.writeString(nbParts);
    }

    @Override
    public int getType() {
        return R.id.rv_recycler_view;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.list_set;
    }

    @Override
    public void bindView(ViewHolder viewHolder, List<Object> payloads) {
        super.bindView(viewHolder, payloads);

        viewHolder.name.setText(idSet + " : " + name);
        viewHolder.year.setText(year);
        viewHolder.theme.setText(theme);
        viewHolder.nbParts.setText(nbParts);
        Ion.with(viewHolder.image)
                .load(image);
    }

    @Override
    public void unbindView(ViewHolder holder) {
        super.unbindView(holder);
        holder.name.setText(null);
        holder.year.setText(null);
        holder.theme.setText(null);
        holder.nbParts.setText(null);
        holder.image.setImageResource(0);
    }

    protected static class ViewHolder extends RecyclerView.ViewHolder {
        public ImageView image;
        public TextView year;
        public TextView name;
        public TextView theme;
        public TextView nbParts;

        public ViewHolder(View itemView) {
            super(itemView);

            theme = (TextView) itemView.findViewById(R.id.theme_set);
            year = (TextView) itemView.findViewById(R.id.year_set);
            name = (TextView) itemView.findViewById(R.id.name_set);
            nbParts = (TextView) itemView.findViewById(R.id.nb_parts_set);
            image = (ImageView) itemView.findViewById(R.id.image_set);
        }
    }
}`

**Comment by mikepenz** [comment]
caling the `bindView` method is done by the `RecyclerView` nothing of the lib. 

You are sure the elements inside your `result.getResult()` is correct?

**Comment by mikepenz** [comment]
Close for inactivity. Please report back to re-open
