### ISSUE TITLE
Pagination error handling

### ISSUE THREAD

**Issue by nimaa77** [mikepenz/FastAdapter#311]
Hi,

Is There Any Feature to add Some Error Handling System Like Instagram + Default Loading Animator at  Footer Adapter ?!

I Tried Many Way's I just Found That to just remove footerAdapter and add items to main fastAdapter ...

![image](https://cloud.githubusercontent.com/assets/25016067/21780956/b642e658-d6c2-11e6-8777-0dceb4ae161f.png)

**Comment by mikepenz** [comment]
just have a `footerAdapter` wrapped and add the item in there. it will be a normal list item, just make sure you are scrolled down far enough to make it visible

**Comment by nimaa77** [comment]
I done that like it was in examples Some How This : 
`       
        FooterAdapter<ProgressItem> footerAdapter;
        FastItemAdapter<Product> fastAdapter;
        .....

        mRecyclerView.setLayoutManager(new LinearLayoutManager(view.getContext()));
        mRecyclerView.setItemAnimator(new DefaultItemAnimator());
        mRecyclerView.setHasFixedSize(true);

        mRecyclerView.setItemViewCacheSize(10);
        mRecyclerView.setDrawingCacheEnabled(true);
        mRecyclerView.setDrawingCacheQuality(View.DRAWING_CACHE_QUALITY_HIGH);

        mRecyclerView.setLayerType(View.LAYER_TYPE_HARDWARE, null);

        fastAdapter = new FastItemAdapter<>();
        mRecyclerView.setAdapter(fastAdapter);
        footerAdapter = new FooterAdapter<>();

        mRecyclerView.setAdapter(footerAdapter.wrap(fastAdapter));

        mRecyclerView.addOnScrollListener(new EndlessRecyclerOnScrollListener(footerAdapter) {
            @Override
            public void onLoadMore(final int currentPage) {

                //check if it's not last page
                if (total_page >= page) {

                    footerAdapter.clear();
                    footerAdapter.add(new ProgressItem().withEnabled(true));

                    loadData();

                }
            }
        });`

So I just Have To Create A new Footer Adapter Item With two View Holders (I Wish If U Could Have Some Examples) or There Is Some Way To set Two Items to FooterAdapter or have only one FooterAdapter With Error View And Progress so the Error View is in GONE Visibility ...

**Comment by mikepenz** [comment]
@nimaa77 a `FooterAdapter` can have as many items as you want to have. 
Basically adapters allow you to define a type. but you can also choose to use it without a type like this: 
`new FooterAdapter()` --> which will allow you to add in any item. 
It is more or less the same as `new FooterAdapter<IItem>()`

There is one important thing to remember. The `FastAdapter` is managing all items, so it has to have the super class of all the included items. in your case I think it would / should be `IItem` 

So after you keep the above in mind, you can handle a `FooterAdapter` as any normal `ItemAdapter` and add as many elements as you want to. 

Like in the below sample: 
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/StickyHeaderSampleActivity.java#L55
