### ISSUE TITLE
how can i implement different item type with different view?

### ISSUE THREAD

**Issue by aliab** [mikepenz/FastAdapter#315]
is there any way to implement different view of different item type?
now I use different ViewHolder in 1 recycler view to support item type.

**Comment by Rainer-Lang** [comment]
In the sample code you should find something.

**Comment by mikepenz** [comment]
@aliab as already noted by @Rainer-Lang the sample app shows most cases :D
Please have a look in there first. 

You can by the way provide an unlimited (MAX_INT) number of items (different items) to the fastadapter.
