### ISSUE TITLE
Handling FooterAdapter click event

### ISSUE THREAD

**Issue by aRusenov** [mikepenz/FastAdapter#317]
Hello,
I am trying to set a click event listener on an item from `FooterAdapter`. I'm following the sample app [here](https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/EndlessScrollListActivity.java). 

`withOnClickListener` appears to be available only on `FastAdapter`. What's the alternative for `FooterAdapter`?

**Comment by mikepenz** [comment]
@aRusenov the `FastAdapter` is the parent of all subadapters. so the `FastAdapter` will also get the event of the `FooterAdapter` just listen in the `FastAdapter`'s click listener and react on the event

**Comment by aRusenov** [comment]
Thanks, @mikepenz 
I already tried that and it appears I forgot to set `withEnabled(true)` when adding the footer item:
`footerAdapter.add(new RetryItem().withEnabled(true))`

I also noticed I could individually chain `withOnItemClickListener(...)` to my footer items. That helps avoid generifying my FastAdapter.
