### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tasomaniac** [mikepenz/FastAdapter#32]
It is a great library. 
I tried to use it but it is almost impossible to do without reading the source code of the sample app. 
JavaDocs should also have example usages and descriptions.

**Comment by Rainer-Lang** [comment]
The source of the sample is great! There are more ideas and possibilities to use this lib than in docu could be. ;-) 
I NEVER saw another lib with such a lot of examples - especially with the use of other libs.

**Comment by tasomaniac** [comment]
Yeah that's true. Sample app is great. But wouldn't it be also great to see some text when you press F1 and see some info for the classes.

**Comment by Rainer-Lang** [comment]
True :-D
I had a few discussions with Mike about docu in past....  ;-) 
But.... to be honest - we other devs could help here too. PRs.... ;-)

**Comment by tasomaniac** [comment]
That's also true :) I didn't open this for Mark to add it. I just opened it to indicate the need of it.

**Comment by mikepenz** [comment]
hi @tasomaniac thank you so much :). 

I know that the README and the javadoc still can be approved. For v1.0.0 my goal was to jave at least a description for most public interfaces and methods people will use. 

I had some troubles in the past with code in the javadoc comments. Somehow the build always failed with characters like ">", ..
I am really happy about all suggesitons which will make this lib even better :). 

I will try to improve it :), I hopw with the help of others like you and Rainer.

Thanks again :)

**Comment by Rainer-Lang** [comment]
It's Mike, not Mark ;-)

Actually I tried and used a lot of other RV-libs out there..... Tried the with the usage/in combination of other libs (header, search/filter, actionmode, swipetorefresh,...).
I'm glad to have this lib now!
All is now so - easy... :-D

**Comment by Rainer-Lang** [comment]
Why closed?

**Comment by mikepenz** [comment]
@Rainer-Lang because there is javadoc. You can even look at the javadoc here: http://www.javadoc.io/doc/com.mikepenz/fastadapter/1.0.3
There are code samples, and if someone wants to create a wiki he can do so. I also take all pull request improving the descriptions, documentations etc. :D 

And this will be a never closeable issue (like the one on MaterialDrawer) and to be fair i do not like issues. :D
