### ISSUE TITLE
Integrating 3rd Party Sorted Adapter

### ISSUE THREAD

**Issue by eygraber** [mikepenz/FastAdapter#321]
Just found your library, awesome work!

I created a [`SortedAdapter` (it's written in Kotlin)](https://github.com/eygraber/recycler-view-utils/blob/master/adapters/src/main/java/com/staticbloc/recyclerview/utils/SortedAdapter.kt) and I'd like to integrate it with your library. It basically uses a `SortedList` for efficient sorting on mutation and handles `RecyclerView.Adapter` notifications (there's some stuff in there for locking and filtering, but that would go away if I could use this library 😄 ).

What would be the best way to do this? Extract the `SortedList` functionality into another class and wrap an adapter in it, or is there a way to integrate the functionality directly into a `FastAdapter`?

**Comment by mikepenz** [comment]
@eygraber very interesting work. 

So your `SortedAdapter` sorts and then uses the `DiffUtil` to display the changes? 

The best would be to have this functionality as it's own component, and just use the `FastAdapter` class as is. So it would be a util class or so inside the `library-extensions` module 

So I assume it would be some API like `SortedUtil.sort(FastAdapter, SortFunction)`

**Comment by eygraber** [comment]
@mikepenz it only uses `DiffUtil` for filtering. It actually uses `SortedList.Callback` to do an insertion binary sort, and notify the adapter about insertions, removals, etc... It also has the ability to sort across view types. Because the list is always guaranteed to be sorted, it also provides an optimized way to:

* replace all items
* replace all items of a certain view type
* update and remove an item without knowing its position

while keeping track of what to notify the adapter about (`notifyDataSetChanged` is never used).

There is also an `UnsortedAdapter` that uses `DiffUtil` but the only really useful feature there is notifying the adapter on `replace` calls.

**Comment by mikepenz** [comment]
@eygraber as already mentioned if you wish to add this, please wrapt this into it's own component and just wrap the `FastAdapter` in it. 

Just open a PR if you still wish to do this

**Comment by eygraber** [comment]
@mikepenz I started looking into this, and I think the most correct solution would be for me to create a `SortedFastItemAdapter` and `SortedItemAdapter`. The problem is that `SortedItemAdapter` would have to recreate the whole `ItemAdapter` class because the list is an implementation detail.

Would you be open to a PR that abstract the list out of `ItemAdapter` and puts it behind a `ItemList` interface? Then it would make it easy to swap out list behavior in `ItemAdapter`.

**Comment by mikepenz** [comment]
@eygraber I'd prefer that there is a different `IItemAdapter` implementation (and/or extending `AbstractAdapter`) for the `SortedItemAdapter` which you would like to implement. As having an additional `ItemList` interface would just result in an additional amount of methods, even though the general `ItemAdapter` can already be extended or the `IItemAdapter` implemented

**Comment by eygraber** [comment]
@mikepenz what about making `ItemAdapter.mItems` protected? The issue with a separate `IItemAdapter` is that `SortedItemAdapter` would have to re-implement things like filtering, etc... that `ItemAdapter` already does.

**Comment by eygraber** [comment]
@mikepenz congrats on the v3 release!

Now that I don't have to worry about large scale breaking changes, would you be open to a PR making the list in `ModelAdapter` pluggable? It would make things like auto sorting lists easier.

In my app I've basically created my own version of `FastAdapter` and `FastItemAdapter` to suit my needs, and I use this to store the items:

```
interface ItemListStrategy<Item : IItem<*, *>> {
  var listCallback: ListUpdateCallback?

  val size: Int

  operator fun get(position: Int): Item
  fun getAll(): List<Item>

  fun add(item: Item)
  fun add(position: Int, item: Item)
  fun addAll(items: List<Item>)
  fun addAll(position: Int, items: List<Item>)

  fun set(position: Int, item: Item)
  fun set(items: List<Item>)

  fun update(item: Item)
  fun update(oldItem: Item, newItem: Item)

  fun remove(item: Item): Boolean
  fun remove(position: Int): Item
  fun clear()

  fun getAdapterPosition(item: Item): Int
  fun getAdapterPosition(identifier: Long): Int
}
```

That allows me to specify a standard implementation:

```
class SimpleItemListStrategy<Item : IItem<*, *>>(
    initialList: List<Item>? = null
) : ItemListStrategy<Item> {
  private val items = if(initialList == null) ArrayList() else ArrayList<Item>(initialList)

  override var listCallback: ListUpdateCallback? = null

  override val size get() = items.size

  override fun get(position: Int) = items[position]

  override fun getAll() = ArrayList(items)

  override fun add(item: Item) {
    val insertionPos = items.size
    items.add(item)
    listCallback?.onInserted(insertionPos, 1)
  }

  override fun add(position: Int, item: Item) {
    items.add(position, item)
    listCallback?.onInserted(position, 1)
  }

  override fun addAll(items: List<Item>) {
    val insertionPos = this.items.size
    if(this.items.addAll(items)) {
      listCallback?.onInserted(insertionPos, items.size)
    }
  }

  override fun addAll(position: Int, items: List<Item>) {
    if(this.items.addAll(position, items)) {
      listCallback?.onInserted(position, items.size)
    }
  }

  override fun set(position: Int, item: Item) {
    items[position] = item
    listCallback?.onChanged(position, 1, null)
  }

  override fun set(items: List<Item>) {
    val newItemsCount = items.size
    val currentItemsCount = this.items.size

    this.items.clear()
    this.items.addAll(items)

    listCallback?.let { listCallback ->
      when {
        newItemsCount > currentItemsCount -> {
          if (currentItemsCount > 0) {
            listCallback.onChanged(0, currentItemsCount, null)
          }
          listCallback.onInserted(currentItemsCount, newItemsCount - currentItemsCount)
        }
        newItemsCount == 0 -> listCallback.onRemoved(0, currentItemsCount)
        newItemsCount < currentItemsCount -> {
          listCallback.onChanged(0, newItemsCount, null)
          listCallback.onRemoved(newItemsCount, currentItemsCount - newItemsCount)
        }
        else -> listCallback.onChanged(0, newItemsCount, null)
      }
    }
  }

  override fun update(item: Item) {
    val pos = getAdapterPosition(item)
    if(pos >= 0) {
      items[pos] = item
      listCallback?.onChanged(pos, 1, null)
    }
  }

  override fun update(oldItem: Item, newItem: Item) {
    val pos = getAdapterPosition(oldItem)
    if(pos >= 0) {
      items[pos] = newItem
      listCallback?.onChanged(pos, 1, null)
    }
  }

  override fun remove(item: Item): Boolean {
    val pos = getAdapterPosition(item)
    return if (pos >= 0) {
      items.removeAt(pos)
      listCallback?.onRemoved(pos, 1)
      true
    } else {
      false
    }
  }

  override fun remove(position: Int): Item {
    return items.removeAt(position).apply {
      listCallback?.onRemoved(position, 1)
    }
  }

  override fun clear() {
    val size = items.size
    items.clear()
    listCallback?.onRemoved(0, size)
  }

  override fun getAdapterPosition(item: Item) = getAdapterPosition(item.identifier)

  override fun getAdapterPosition(identifier: Long): Int {
    items.forEachIndexed { index, item ->
      if(item.identifier == identifier) return index
    }

    return -1
  }
}
```

and a sorted one:

```
class SortedItemListStrategy<Item : IItem<*, *>>(
    initialList: List<Item>? = null,
    clazz: Class<Item>,
    private val callback: Callback<Item>
) : ItemListStrategy<Item> {
  interface Callback<in Item : IItem<*, *>> {
    fun compare(lhs: Item, rhs: Item): Int

    fun isChanged(oldItem: Item, newItem: Item): Boolean

    fun areEqual(o1: Item, o2: Item): Boolean
  }

  private val sortedListCallback = object : SortedList.Callback<Item>() {
    override fun areContentsTheSame(oldItem: Item, newItem: Item) = !callback.isChanged(oldItem, newItem)

    override fun areItemsTheSame(item1: Item, item2: Item) = callback.areEqual(item1, item2)

    override fun compare(o1: Item, o2: Item) = callback.compare(o1, o2)

    override fun onInserted(position: Int, count: Int) { listCallback?.onInserted(position, count) }

    override fun onChanged(position: Int, count: Int) { listCallback?.onChanged(position, count, null) }

    override fun onChanged(position: Int, count: Int, payload: Any?) { listCallback?.onChanged(position, count, payload) }

    override fun onMoved(fromPosition: Int, toPosition: Int) { listCallback?.onMoved(fromPosition, toPosition) }

    override fun onRemoved(position: Int, count: Int) { listCallback?.onRemoved(position, count) }
  }

  private val items: SortedList<Item> =
      if(initialList == null) SortedList<Item>(clazz, sortedListCallback) else { SortedList(clazz, sortedListCallback, initialList.size) }

  override var listCallback: ListUpdateCallback? = null

  override val size get() = items.size()

  override fun get(position: Int): Item = items[position]

  override fun getAll() = items.toList()

  override fun add(item: Item) {
    items.add(item)
  }

  override fun add(position: Int, item: Item) =
      throw IllegalArgumentException("You can't add at a position for a sorted adapter")

  override fun addAll(items: List<Item>) = this.items.addAll(items)

  override fun addAll(position: Int, items: List<Item>) =
      throw IllegalArgumentException("You can't add at a position for a sorted adapter")

  override fun set(position: Int, item: Item) =
      throw IllegalArgumentException("You can't set at a position for a sorted adapter")

  override fun set(items: List<Item>) = this.items.batchUpdate {
    clear()
    addAll(items)
  }

  override fun update(item: Item) {
    items.update(item)
  }

  override fun update(oldItem: Item, newItem: Item) {
    items.update(oldItem, newItem)
  }

  override fun remove(item: Item) = items.remove(item)

  override fun remove(position: Int): Item = items.removeItemAt(position)

  override fun clear() {
    items.clear()
  }

  override fun getAdapterPosition(item: Item) = items.indexOf(item)

  override fun getAdapterPosition(identifier: Long): Int {
    items.toList().forEachIndexed { index, item ->
      if(item.identifier == identifier) return index
    }

    return -1
  }

  private fun <T> SortedList<T>.toList(): List<T> {
    val size = size()
    return (0 until size).mapTo(ArrayList(size)) { this[it] }
  }

  private fun <T> SortedList<T>.batchUpdate(op: SortedList<T>.() -> Unit) {
    beginBatchedUpdates()
    try {
      this.op()
    }
    finally {
      endBatchedUpdates()
    }
  }

  private fun <T> SortedList<T>.update(item: T): Int {
    return indexOf(item).also {
      if(it != SortedList.INVALID_POSITION) {
        updateItemAt(it, item)
      }
    }
  }

  private fun <T> SortedList<T>.update(oldItem: T, newItem: T): Int {
    return indexOf(oldItem).also {
      if(it != SortedList.INVALID_POSITION) {
        updateItemAt(it, newItem)
      }
    }
  }
}
```

**Comment by mikepenz** [comment]
@eygraber I think it would be ok to have a custom implementation of the `List` available for the `ModelAdapter` I still assume that this might cause issues when you add an item, then the `ModelAdapter` instantly notifies for that position, but in the same moment that list would re-sort?

**Comment by eygraber** [comment]
In the case of `SortedItemListStrategy`, calling `add` would call through to `SortedList.add` which uses a binary search to add the item at the proper index, and returns that index. That way only one notification is needed. 

I can make a PR for this if you want. I just forked the repo yesterday 😁

**Comment by mikepenz** [comment]
@eygraber well doesn't that mean that you will also have to adjust all list related functions from the `ModelAdapter` and that only allowing a different list implementation is not enough.

So basically it would be a completely different `IItemAdapter` implementation?

Related your question of `Kotlin` policy. The core modules can't contain it, as I still want to support people who can't or don't want to use `Kotlin` a new additional module though can be in `Kotling` though

**Comment by eygraber** [comment]
I barely had to adjust the `ModelAdapter` because the "list strategy" gets a `ListUpdateCallback` which takes care of notifying the adapter that something changed. 

I did change some stuff related to setting lists, but maybe we could discuss in the PR (which I'll push soon).

For Kotlin, are you referring to people using the library, or contributors? Because for the former, the interop is so good they wouldn't know that the library is using Kotlin unless they checked the source.

**Comment by mikepenz** [comment]
v3.1.1 launched with the new `IItemList` interface :)
