### ISSUE TITLE
Listener for expand/collapse event

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#327]
Does this exist? Could this be added?

I've written the utility helper for the fast scroller (https://github.com/turing-tech/MaterialScrollBar/blob/master/lib/src/main/java/com/turingtechnologies/materialscrollbar/FastScrollerUtil.java) and I want to write an improved version for your adapter. Many calculations can be improved and the usage can be simplified, but I would need listeners for a changed expand/collapse state for an advanced and fast calculation algorithm...

**Comment by mikepenz** [comment]
@MFlisar I think the normal click listener should be fine already.

**Comment by MFlisar** [comment]
That's probably true for any user initialised event. But many functions that update the adapter do automatically collapse headers for example which must be considered as well...

**Comment by mikepenz** [comment]
that's true though. But it must already go through the events somehow because it should also update the arrow for example

**Comment by mikepenz** [comment]
@MFlisar if you wish to improve this behaviour, please open an PR. Close this issue for inactivity.

**Comment by fikr4n** [comment]
> I think the normal click listener should be fine already.

It does't work for expandable items. Did you mean **pre**-click listener?
