### ISSUE TITLE
Check row by index from button

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/FastAdapter#328]
I have a list with checkbox inside, like the demo, works perfect
simply i need to check the row 2 in the list, with a button click

how to do that ? what method of the adapter i can use to check by index ?
thanks

**Comment by mikepenz** [comment]
I am not sure what you mean. As the checkbox in general would be just a flag in your item, you update your item and then notify the drawer about the changed element?

**Comment by seba123neo** [comment]
i found mFastItemAdapter.toggleSelection(2);

thanks !!!
