### ISSUE TITLE
Add item at runtime

### ISSUE THREAD

**Issue by bfayette** [mikepenz/FastAdapter#329]
Fast adapter seems really fast and intuitive. Simple and clear examples. But all examples use one time adapter initialization. Do you have some examples where the adapters are fed from observers at some point in the timeline. Any share of the design will also be helpful.

**Comment by mikepenz** [comment]
@bfayette it is the same, just use the `itemAdapter` and add your items. The only important part is, that this happens on the UI Thread as the adapter will notify the RecyclerView

**Comment by bfayette** [comment]
Thx for your time. Adding new items happened in my case on the UI thread. Maybe I missed something. I ll try later with a smaller example.

**Comment by mikepenz** [comment]
Ok great. Please report back
