### ISSUE TITLE
Handling onClick in Heterogenous Layouts inside RecyclerView

### ISSUE THREAD

**Issue by ItsAnubhav** [mikepenz/FastAdapter#331]
I am adding items to my adapter like this

```
for(int i=0;i<30;i++){
            if(i==4)
                fastAdapter.add(new RecyclerItem4(getContext(),"Awesome Title "+i,"Category "+i,"Author "+i));
            else
                fastAdapter.add(new Cheese(getContext(),"Awesome Title "+i,"Category "+i));
}

```
and adding the **OnClickListener** like this

        fastAdapter.withOnClickListener(new FastAdapter.OnClickListener<Cheese>() {
            @Override
            public boolean onClick(View v, IAdapter<Cheese> adapter, Cheese item, int position) {
                Intent intent = new Intent(getContext(),CheeseDetailActivity.class);
                intent.putExtra("name","Static Title");
                startActivity(intent);
                return true;
            }
        });

        fastAdapter.withOnClickListener(new FastAdapter.OnClickListener<RecyclerItem4>() {
            @Override
            public boolean onClick(View v, IAdapter<RecyclerItem4> adapter, RecyclerItem4 item, int position) {
                Intent intent = new Intent(getContext(),CheeseDetailActivity.class);
                intent.putExtra("name","Static Title");
                startActivity(intent);
                return true;
            }
        });
I want the app to respond to clicks on both types of item. But the **Recycleritem4 is working** and the first one ( **Cheese** ) is not working. Please help me out. Here is a screenshot of the app.
![whatsapp image 2017-02-07 at 10 26 32](https://cloud.githubusercontent.com/assets/11605916/22678426/0196a022-ed20-11e6-96a0-3a466198d19b.jpeg)

**Comment by mikepenz** [comment]
@ItsAnubhav please see the following section:
https://github.com/mikepenz/FastAdapter/blob/b45d10c0959ccf0b80909eaf6eb527c5bb372e11/README.md#4-click-listeners-for-views-inside-your-item

**Comment by ItsAnubhav** [comment]
That worked pal. Thank you.

**Comment by judemanutd** [comment]
@ItsAnubhav  i am having a little trouble creating an adapter with heterogenous views,could you tell me how exactly you did it please.

**Comment by ItsAnubhav** [comment]
@judemanutd Hope this helps
https://gist.github.com/ItsAnubhav/9b4fbd4a1fc482e30089cd32985d76e6
