### ISSUE TITLE
How to set a color for selected items?

### ISSUE THREAD

**Issue by danielpassos** [mikepenz/FastAdapter#332]
Sorry to opened a issue for this, but I could not figured out where the color for the selected items are coming from in [Multiselect Sample](https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiselectSampleActivity.java)

**Comment by mikepenz** [comment]
the `SimpleItem` has a ColorStateList as background
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleItem.java#L106
