### ISSUE TITLE
Not notify for update after item was selected

### ISSUE THREAD

**Issue by gromiloff** [mikepenz/FastAdapter#333]
in function FastAdapter->handleSelection after item.withSetSelected(!selected); adapter is not refresh the selected item

PS: adapter is notified if item was deselected (in function deselect()). So why it not happaned if item is selected ?

**Comment by mikepenz** [comment]
I think you mix 2 things. 

item.withSetSelected() just changes the boolean inside an item. It will not do anything with the adapter. Only if you manually notify it. 

the `deselect()` function is done on the `FastAdapter` itself, so this will handle it. There is also a `select()` method directly on the adapter, just in case

**Comment by gromiloff** [comment]
@mikepenz the main problem in case when user click to item, so all deselected items are updated, but all selected - not updated. How I can update selected items ?

PS: my case is applicable for drawer menu list.

**Comment by gromiloff** [comment]
getAdapter().withSelectWithItemUpdate(true)
is wokr for my case, So closing issue.
