### ISSUE TITLE
dragging\switching items AND select on long click?

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#337]
hi.
first i'd like to apologize if this question has already been asked - i have tried to search but couldn't find any similar issues.

in my app i would like to enable switching between items AND selecting items via long click.
the problem is that (as you might have guessed by now) i need to differentiate between a long click that was meant for a drag\switch operation and a long click that was meant for selecting an item.
if i enable both of these features, i often select an item whereas my intention was to drag/switch it.

i of course understand why this is happening and i also understand that the basis for this problem is that i'm linking 2 operations to the same gesture (long-click).

so, is there any way of getting this scenario to work? from what i understand there is a way to "attach" the dragging\switching operation to a different gesture but i don't think this is what im looking for (like what would be a different gesture? the user moving his fingers in a specific way?)

the best solution i can think of is to link the drag\switch operation to a specific area or view. for example, i could add a button/image/whatever to the end of my item and when the user long-clicks i, that will trigger the drag\switch operation, whereas long-clicking anywhere else on the item would trigger the "select" feature.
-is this possible? if so, how would i do that?
-any other ideas on how to combine these 2 features together?

thanks

**Comment by mikepenz** [comment]
@or-dvir it may be possible, but I am not really sure, as the provided helper classes are just included to simplify such cases, but are not supposed to do everything which may be possible. 

I suggest you to take a close look on the available Android APIs and check directly with these. It should be independent of the FastAdapter. 

If you figure it out, you may want to open a PR with a sample for other devs

**Comment by or-dvir** [comment]
alright. thanks
