### ISSUE TITLE
Drag and Drop with GridLayoutManager scrolls only in Verticle direction

### ISSUE THREAD

**Issue by LadwaAditya** [mikepenz/FastAdapter#339]
The drag and drop feature only works with verticle direction. Is there any way to make my items draggable in both horizontal and Verticle direction?

**Comment by LadwaAditya** [comment]
Solved it myself 
Sometimes you need to look into the source code
`SimpleDragCallback dragCallback = new SimpleDragCallback(SimpleDragCallback.ALL, this);`

**Comment by adrielcafe** [comment]
@LadwaAditya you save my day. Thanks!
