### ISSUE TITLE
how to style the UndoHelper (snackbar)

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#340]
Hi.
i am using the UndoHelper and would like to style it (e.g background color, button color, text color etc.).

how would i do that?

**Comment by mikepenz** [comment]
@or-dvir you can only (possibly) change the `Snackbar` style for the whole application (please google this) but not the single one here. If you need this you possibly need to use the code of the `UndoHelper` and modify it to your needs:

https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/UndoHelper.java#L66

**Comment by or-dvir** [comment]
i found a solution.
i realized that the method "remove" in UndoHelper returns the snackbar - so i can use that to style it.

this solution however isn't the best in terms of flow, because it means i am styling the snackbar **after** showing it ("show()" is called right before the method returns).

suggestion: perhaps you could add a small function "withSnackBar"? this would only require a small modification to the current "remove" function (if the user provided a snackbar, use it. otherwise, create a default one).

**Comment by mikepenz** [comment]
@or-dvir perhaps you would like to open a PR for this :)

**Comment by or-dvir** [comment]
alright i will :). when i have time to work on my app again (god knows when that would be)

**Comment by or-dvir** [comment]
pull request created.
https://github.com/mikepenz/FastAdapter/pull/347

this is my first pull request... i hope i did ok (just left everything default)
