### ISSUE TITLE
 "undo" - small improvement suggestion

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#341]
hi.
i have noticed that after deleting an item and then clicking "undo" the position of the list does not change.
if the deleted (and then "restored") item is either the first or last in the list, this (in my opinion) is confusing to the user. ill explain:
when deleting the **first** item in the list, the entire list moves up (bringing the **second** item to the top of the screen). however after clicking "undo", while the **first** item is returned to the top of the list, the list itself does not move down again thus creating a situation where the top of the screen is still showing the **second** item even though the first item was restored above it. this could be confusing since there is no indication that the item has been restored and the user might think that clicking the "undo" button didn't do anything (only by scrolling up the user will see the first item again).

the same situation occurs when the item deleted is the last in the list (in this case the problem is reversed of course)

**Comment by mikepenz** [comment]
@or-dvir I would suggest you scroll just up or down depending on the position. 
The UndoHelper can't do this as it does not know about the `RecyclerView` so it can't do the scroll for you.
