### ISSUE TITLE
ActionModeHelper - manually start selection mode

### ISSUE THREAD

**Issue by Shakezulla57** [mikepenz/FastAdapter#343]
Is there a way to trigger selection mode other than with the `onClick()` or `onLongClick()` methods? I'd like to be able to start the selection mode from a menu button without automatically selecting an item. You can do `setSupportActionBar()` but that obviously won't do the same stuff behind the scenes to our adapter.

**Comment by mikepenz** [comment]
@Shakezulla57 you can directly interact with the `mActionMode`
