### ISSUE TITLE
Expand items may not work after restoring view

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#344]
Consider following use case:

* expandable items are created
* they are added to the adapter
* adapter.expand() is called, which works, as every item was initialised with the state `withIsExpanded(false)`

Now the view is destroyed and recreated and the adapter is retained, the existing adapter data is reused, BUT it's in an invalid state (all items "think" they are expanded, but they aren't). Following will fail:

* setting the already existing adapter to the new `RecyclerView`:    

        fastAdapter.setNewList(viewState.rvData());
        fastAdapter.withSavedInstanceState(lastSavedInstanceState);
        fastAdapter.expand();

This means, I always have to manually check if I'm reusing data, if yes, I have to check all items and set their state to collapsed in a loop (`((IExpandable)items.get(i)).withIsExpanded(false);`) and only afterwards the adapter is useable again.

I'm not saying this is a big problem, but it's a very bad user experience imho...

As I MUST call `expand` after setting the adapters list, it may be a good thing, if the `fastAdapter().withSavedInstanceState(...)` call, which must be called after setting the adapter's items, checks if all items have the correct expanded state (which should be `false` imho, always).

What do you think?

**Comment by Rainer-Lang** [comment]
What do you suggest?

**Comment by MFlisar** [comment]
The easiest and fastest fix would be to extend the `expand()` function with a parameter like "force expand" which will disable the "is item expanded" check...

Alternatively, the builder could be extended with a `withResetState()` function, which will reset each items state to collapsed (as the adapter will render any item as collapsed after setting it's items, not respecting any items expanded state).

The most beautiful solution is more work and if I remember correctly, there are points speaking against it (speed and other side effects, but currently I don't remember): when setting items of the adapter, this should always respect the expanded state of each item automatically.

As I'm already used to the "always expand items manually" usage, I would be fine with the first two options.

For now, I just iterate over all items and set their state to collapsed and then call `fastAdapter.expand()`...

**Comment by mikepenz** [comment]
@MFlisar basically it is a thing the developer has to do. If the activity is recreated the I have to assume that the items which come in will also be new (not retained). So all the logic which happens inside the `withSavedInstanceState` will work. 

I would like to prevent the need of iterating over each item just to set it back. 

Having to iterate over each item when they are added to the adapter, and expand them if necessary would be very bad in performance and we shouldn't do this :/

**Comment by MFlisar** [comment]
I still think the logic for sub items produces a lot of inconsistencies with a lot of special treatments necessary. They are no big problem at all, but they are nearly impossible to guess and you just avoid problems if you know all the special things you have to do. I know it would be a lot of work, but something like `withSupportSubItems` and then handling them correctly would be much more intuitive than what is necessary now, its just an idea though.

At least, the `withResetState` would be nice. It may only expand all items or it may do other things as well (maybe some other special things don't work as well if you retain your adapter?). At least this function would indicate to the user that some things must be reverted to a initial state after restoring the adapter...

And I think with all the MVP and similar in android which is quite popular now (I'm using MVI for example) it will be quite common to retain all your data but your views and just attach your data to your new views as well.

**Comment by mikepenz** [comment]
It's possibly something for v3: https://github.com/mikepenz/FastAdapter/pull/294

**Comment by mikepenz** [comment]
Close as it should get improved in v3
