### ISSUE TITLE
bind view before appearing

### ISSUE THREAD

**Issue by saeedrooyekhat** [mikepenz/FastAdapter#345]
Is there a way for bind view in recyclerView before appearing?
i want do this action for load item faster. Such as when set cache size and to see previous item return, not perform any process.

**Comment by mikepenz** [comment]
@saeedrooyekhat this is completely handled by the `RecyclerView` + it's `LayoutManager` nothing I can do about it. 

You can have a look on the RecyclerView's API and might want to check out it's feature to define a prefetch amount (or whatever it's called)
