### ISSUE TITLE
How to extend model class?

### ISSUE THREAD

**Issue by judemanutd** [mikepenz/FastAdapter#348]
I have a model class that already extends realm object , how exactly can i integrate fast adapter into my app considering a class in java cannot extend multiple classes.

**Comment by mikepenz** [comment]
@judemanutd please have a look on the `GenericItemAdapter` samples. Basically it will allow you to have your model class, and a different item class used to display your model

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/GenericItemActivity.java#L58

**Comment by judemanutd** [comment]
@mikepenz  thank you,will take a look at it.
