### ISSUE TITLE
Recycler View showing a warning

### ISSUE THREAD

**Issue by judemanutd** [mikepenz/FastAdapter#350]
`Cannot call this method in a scroll callback. Scroll callbacks might be run during a measure & layout pass where you cannot change the RecyclerView data. Any method call that might change the structure of the RecyclerView or the adapter contents should be postponed to the next frame`

I get this warning in my logcat,is there a problem here?

**Comment by mikepenz** [comment]
@judemanutd the messages states exactly what's going on. It's unrelated to the `FastAdapter` too.

**Comment by judemanutd** [comment]
@mikepenz i wasn't getting this warning in my log cat up until the point where i added endless scrolling for the fast adapter.
Is there a way i can rectify this?

**Comment by mikepenz** [comment]
just call the thing you are doing inside the scroll callback via a handler, as written in the error message above
