### ISSUE TITLE
Multiple View Holders of GenericAbstractItem

### ISSUE THREAD

**Issue by judemanutd** [mikepenz/FastAdapter#351]
I need to include multiple viewholders into my list of GenericAbstractItem,how do i do that?These arent headers or footers,they are part of the list.

**Comment by mikepenz** [comment]
Please have a look on the `MultiTypeGenericItemActivity`
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeGenericItemActivity.java#L60

**Comment by mikepenz** [comment]
Basically just define a parent class which is true for all your items (if non exists then just use `IItem`) 
Define the logic how your model (model's) define your item 
```java
GenericItemAdapter<IconModel, GenericIconItem> itemAdapter = new GenericItemAdapter<>(new Function<IconModel, GenericIconItem>() {
            @Override
            public GenericIconItem apply(IconModel o) {
                if (o instanceof RightIconModel) {
                    return new RightGenericIconItem(o);
                } else {
                    return new GenericIconItem(o);
                }
            }
        });
```

And then fill the list.

**Comment by judemanutd** [comment]
That did the job,thank you @mikepenz

**Comment by judemanutd** [comment]
Is it possible to have two separate viewholder with different views in them?

**Comment by mikepenz** [comment]
2 ViewHolders --> 2 Items

Mike Penz
__________________________________________
*Mike Penz*
Android | Backend | Open Source | Web Developer
mikepenz.com
lanora.eu

**Comment by judemanutd** [comment]
ReceiverChat_ViewHolder

     public class ReceiverChat_ViewHolder extends RecyclerView.ViewHolder {
    private TextView message;
    private ImageView imageView;

    public ReceiverChat_ViewHolder(View itemView) {
        super(itemView);
        message = (TextView) itemView.findViewById(R.id.message);
        imageView = (ImageView) itemView.findViewById(R.id.image_receiver);
    }

    public TextView getMessage() {
        return message;
    }

    public ImageView getImageView() {
        return imageView;
    }
}`

ChatSender_ViewHolder

    `public class ChatSender_ViewHolder extends RecyclerView.ViewHolder {
    private TextView message;
    private ImageView imageView;

    public ChatSender_ViewHolder(View itemView) {
        super(itemView);
        message = (TextView) itemView.findViewById(R.id.message);
        imageView = (ImageView) itemView.findViewById(R.id.image_sender);
    }

    public TextView getMessage() {
        return message;
    }

    public ImageView getImageView() {
        return imageView;
    }
}`

GenericChatMessageItem

    `public class GenericChatMessageItem extends GenericAbstractItem<ChatMessage, 
    GenericChatMessageItem, ChatSender_ViewHolder> {

    private static final ViewHolderFactory<? extends ChatSender_ViewHolder> FACTORY = new 
    GenericChatMessageItem.ItemFactory();

    public GenericChatMessageItem(ChatMessage chatMessage) {
        super(chatMessage);
    }

    @Override
    public int getType() {
        return R.id.fastadapter_generic_senderMessage_item_id;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_sender_message;
    }

    @Override
    public void bindView(ChatSender_ViewHolder holder, List<Object> payloads) {
        super.bindView(holder, payloads);
        Log.i("bindSender", "Here");
        ChatMessage chatMessage = getModel();

        holder.getMessage().setText(chatMessage.getMessage());
            Log.i("imagebindSender", chatMessage.getImage() + " " + chatMessage.getId_chat_msg());


            if (chatMessage.getImage() != null) {
                Log.i("imagebindSender", chatMessage.getImage());
                Glide.with(holder.itemView.getContext())
                        .load(chatMessage.getImage())
                        .into(holder.getImageView());
            }
    }

    @Override
    public void unbindView(ChatSender_ViewHolder holder) {
        super.unbindView(holder);
        holder.getMessage().setText(null);
        holder.getImageView().setImageDrawable(null);
    }

    @Override
    public ViewHolderFactory<? extends ChatSender_ViewHolder> getFactory() {
        return FACTORY;
    }

    private static class ItemFactory implements ViewHolderFactory<ChatSender_ViewHolder> {
        public ChatSender_ViewHolder create(View v) {
            return new ChatSender_ViewHolder(v);
        }
    }
   }


ReceiverChatMessageItem

    `public class ReceiverChatMessageItem extends GenericChatMessageItem {

    public ReceiverChatMessageItem(ChatMessage chatMessage) {
        super(chatMessage);
    }

    @Override
    public int getType() {
        return R.id.fastadapter_generic_receiverMessage_item_id;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_receiver_message;
    }

    @Override
    public void bindView(ChatSender_ViewHolder holder, List<Object> payloads) {
        super.bindView(holder, payloads);
        Log.i("bindReceiver", "Here");

        ChatMessage chatMessage = getModel();
            Log.i("imagebindReceiver", chatMessage.getImage() + " " + chatMessage.getId_chat_msg());

            holder.getMessage().setText(chatMessage.getMessage());

            if (chatMessage.getImage() != null) {
                Log.i("imagebindReceiver", chatMessage.getImage());
                Glide.with(holder.itemView.getContext())
                        .load(chatMessage.getImage())
                        .into(holder.getImageView());
            }
    }

    @Override
    public void unbindView(ChatSender_ViewHolder holder) {
        super.unbindView(holder);
        holder.getMessage().setText(null);
        holder.getImageView().setImageDrawable(null);
    }
     }`

in the activity


     ` itemAdapter = new GenericItemAdapter<>(chatMessage -> {

            if (chatMessage.getUser_type() == 1) {
                return new GenericChatMessageItem(chatMessage);
            }
            return new ReceiverChatMessageItem(chatMessage);


        });`

The layout files each contain an image view and a text view but the ids for the the 2 image views or the 2  text views are not the same.

**Comment by PN1019** [comment]
@judemanutd [gist.github.com/Suleiman19/…](url) 

As you have mentioned you have 2 textview views and  imageview...this code actually works almost same way like the code you have written.......hope this helps!!!

**Comment by judemanutd** [comment]
@PN1019 link does not open

**Comment by PN1019** [comment]
@judemanutd  try again now it's working

**Comment by judemanutd** [comment]
@PN1019  it worked thanks but this seems like the item is a header,i am doing a chat app so i want 1 view for sender and 1 for receiver but no headers in the list.Will this still work?

**Comment by FabianTerhorst** [comment]
@judemanutd your ReceiverChatMessageItem should not extend the GenericChatMessageItem. Otherwise you could not specify a different viewholder. You should use ```ReceiverChatMessageItem extends  GenericAbstractItem<ChatMessage, ReceiverChatMessageItem, ReceiverChat_ViewHolder>```. When you need the same superclass for both create one that is extending GenericAbstractItem without an viewholder requirement.

**Comment by judemanutd** [comment]
@FabianTerhorst  i got that part but then what how should i declare my GenericItemAdapter if i want to include two different view holders?I was confused about that part.Any help would be appreciated.

       ` private GenericItemAdapter<ChatMessage, GenericChatMessageItem> itemAdapter;
         final RecyclerView recyclerView = (RecyclerView) findViewById(R.id.chats);
         final LinearLayoutManager linearLayoutManager = new 
         LinearLayoutManager(getApplicationContext());
         final FastAdapter<GenericChatMessageItem> fastAdapter = new FastAdapter<>();

        linearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        fastAdapter.withSelectable(true);


        itemAdapter = new GenericItemAdapter<>(chatMessage -> {

            if (chatMessage.getUser_type() == 3) {
                return new ReceiverChatMessageItem(chatMessage);
            }
            return new GenericChatMessageItem(chatMessage);


        });

        recyclerView.setAdapter(itemAdapter.wrap(fastAdapter));
        recyclerView.setLayoutManager(linearLayoutManager);`

**Comment by FabianTerhorst** [comment]
You could use GenericAbstractItem as a type or you are going to create an own class that is extending GenericAbstractItem.

**Comment by judemanutd** [comment]
@FabianTerhorst  when i try declaring the adapter like so
`private GenericItemAdapter<ChatMessage,AbstractItem> adapter;`
lint complains saying that abstract item is not within its bounds and i should implement IGenericItem

**Comment by FabianTerhorst** [comment]
private GenericItemAdapter<ChatMessage, GenericAbstractItem > adapter;

**Comment by judemanutd** [comment]
@FabianTerhorst tried that lint throws the same error.
