### ISSUE TITLE
databse/cursor based adapter?

### ISSUE THREAD

**Issue by k3b** [mikepenz/FastAdapter#352]
According to your example the adapter is build around a list similar to an ArrayAdapter.

		@Override
		public void bindView(ViewHolder viewHolder, List<Object> payloads) {
		}

Is there an api that allow database or cursor based adapters that load on demand similar to a CursorAdapter?

For may gallery app I donot want to pre-load a list into memory because only few items are visible at a time (20 visible out of 17000)

**Comment by mikepenz** [comment]
Non was implemented yet, but it is probably similar to something like the `RealmAdapter`
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-realm/src/main/java/io/realm/RealmItemAdapter.java

**Comment by mikepenz** [comment]
It would be nice if you would like to do a PR if you implement something like this

**Comment by k3b** [comment]
My cursor adapter implementation does not use the FastAdapter so i assume it will not add any value to your lib

**Comment by mikepenz** [comment]
@k3b I meant if you at any point decide to do a FastAdapter based implementation :)

**Comment by Rainer-Lang** [comment]
@k3b It would be cool.
