### ISSUE TITLE
Adding an item did not animate the view

### ISSUE THREAD

**Issue by judemanutd** [mikepenz/FastAdapter#355]
I used the following code to insert an item at the start of the list ie, position 0 `      itemAdapter.addModel(arr, news);` ,the item got added but i had to scroll to view the item that just got added.There was no animation that took place that pushed all other elements down like it would with the default implementation of the recycler view.Am i missing a piece of code that enables animations?

**Comment by ankitbatra11** [comment]
Did you set an item animator on RecyclerView?

**Comment by judemanutd** [comment]
@ankitbatra11 I have not,i was under the impression that addModel was internally calling `notifyiteminserted` which would automatically animate the view using the default animator of the recycler view.Do i need to set a default animator ,if so how?

**Comment by ankitbatra11** [comment]
I can't access my Mac right now but it must be recyclerview.addItemAnimator(new DefaultItemAnimator())

**Comment by mikepenz** [comment]
@judemanutd yes the `add` methods will automatically call the internal notify methods. Just make sure you call these methods on the UI thread. If it happens on any other thread it won't work. 

I think the RV has already by default the animator set, but you can define it again and make sure. (Thanks @ankitbatra11 )

**Comment by judemanutd** [comment]
I am using rxjava and this i my current code.


                                      `Observable.fromIterable(newses)
                                      .subscribeOn(Schedulers.computation())
                                     .observeOn(AndroidSchedulers.mainThread())
                                     .subscribe(news -> UserDataRepository.getUser(news.getPosterId())
                                    .doFinally(() -> {

                                        // Updating Ui here
                                    })
                                    .observeOn(AndroidSchedulers.mainThread())
                                    .subscribe(User -> {
                                        count++;
                                        dataRepository.addUserToNews(news, User);

                                        final List<News> arrayList = itemAdapter.getModels();

                                        if (arrayList.size() > 0) {

                                            for (int arr = 0; arr < arrayList.size(); arr++) {
                                                if (news.getPostDate() > arrayList.get(arr).getPostDate()) {
                                                    itemAdapter.addModel(arr, news);
                                                    break;
                                                } else if (arr == arrayList.size() - 1) {
                                                    itemAdapter.addModel(news);
                                                    break;
                                                }
                                            }
                                        } else {
                                            itemAdapter.addModel(news);
                                        }

                                    }, throwable -> Log.i("retrofit", throwable.getLocalizedMessage())));`

I even manually set the default animator to the recycler view but the item did not animate.

**Comment by mikepenz** [comment]
@judemanutd have you tried doing it via an handler to make sure doing it via rx is not the problem? 
Android is very unpredictable if things were not done on the correct thread (and yes I have seen that you would do it via the mainThread scheduler)

**Comment by judemanutd** [comment]
I added the following code 
`Handler handler = new Handler();
        handler.post(new Runnable() {
        @Override
        public void run() {
			itemAdapter.addModel(chatMessages.get(position));
        }
        });`

but it didn't make a difference.
There was also another part similar to this that was casuing an issue where i am notifying the adapter that an item was changed but it wouldn't reflect the changes.
`Handler handler = new Handler();
                        handler.post(() -> itemAdapter.setModel(position, chat));`

I am notifying the adapter that a specific item was changed but the changes don't reflect.

**Comment by FabianTerhorst** [comment]
try ```Handler handler = new Handler(context.getMainLooper());```

**Comment by judemanutd** [comment]
@FabianTerhorst tried that ,did not work,for now i am using this workaround.
` linearLayoutManager.smoothScrollToPosition(recyclerView, null, itemAdapter.getItemCount());`

@mikepenz @FabianTerhorst Is there a way to notify the adapter that only a single item in the view is modified rather than updating all items of that specific item.
For example if my viewHolder contains 2 text views and only 1 of them needs to be changed while the other kept the same,is there a way to do that?As of now when a notify function is called then the onBind is called which updates all items of the view.

**Comment by mikepenz** [comment]
@judemanutd you do not have to notify the adapter or anything. The FastAdapter / and it's ItemAdapter already takes care of this. 

So if you call `.add()` it will automatically call the correct notify method for this
