### ISSUE TITLE
I get an error about mixing android support library versions with 2.1.7

### ISSUE THREAD

**Issue by ankitbatra11** [mikepenz/FastAdapter#356]
Hi,

@mikepenz You may need to bump up the android library support version being used in this awesome library. I am using android support library 25.2.0 and getting an error for mixing android support library version 25.2.0 and 25.1.1.

**Comment by mikepenz** [comment]
@ankitbatra11 you can exclude the support libraries via gradle, so it won'T cause issues. 

http://stackoverflow.com/a/21765656/325479
