### ISSUE TITLE
Support fine grained notifications in realm

### ISSUE THREAD

**Issue by eygraber** [mikepenz/FastAdapter#358]
Realm recently added support for fine grained notifications, and updated their adapter library to make use of them - https://github.com/realm/realm-android-adapters/pull/83

**Comment by FabianTerhorst** [comment]
this is part of https://github.com/mikepenz/FastAdapter/pull/294

**Comment by RJFares** [comment]
+1

**Comment by mikepenz** [comment]
Close as it will be solved in v3
