### ISSUE TITLE
Groups and Group Headers

### ISSUE THREAD

**Issue by Shakezulla57** [mikepenz/FastAdapter#359]
I'm hoping I can use this library (since I'm already using it) to group items in the adapter.

What I'm looking to do is have groups with a header and a four column grid.

I have a data structure that is already grouped.

```
{
    groups: [
        {
            title: "Group 1",
            items: [] // array of items
        },
        {
            title: "Group 2",
            items: []
        },
        ...
    ]
}
```
I've looked at #175 at that looks promising using the `HeaderHelper` by my data is already grouped. I could also probably modify the expanding items example, but I don't need the expanding functionality. Is there something simpler I'm missing? I've been reading through the examples and source, I'm just a bit confused about which adapter I should be using and when. Any nudge in the right direction is appreciated.

**Comment by mikepenz** [comment]
So you have your data already grouped, which means you do not have it as a flat list? 

If you flatten your list, it would be very easy again, where the flattening logic would create something like:

```
List
   groupitem
   item
   item
   groupitem
   item
   item
   item
   groupitem
   item
   item
```

Then you could simply add the items to the FastAdapter and it would just work

**Comment by Shakezulla57** [comment]
Thanks for getting back to me. Ok I just discovered `setSpanSizeLookup` so that solves one portion of it for me. Since I have two different types of objects in my adapter do I need to use `GenericItemAdapter` with `GenericAbstractItem`?

**Comment by Shakezulla57** [comment]
I might have found what I'm looking for in #48

**Comment by mikepenz** [comment]
@Shakezulla57 you can use as many different items with any adapter you like. You just have to soften the constraint defined via the type you set to the adapter. So basically you can also just create a `GenericItemAdapter` with the lowest possible type which is `GenericAbstractItem` (the same is possible for normal items via the `IItem` interface)

yes :)
