### ISSUE TITLE
AbstractItem exception on ViewHolder instantiation exception is misleading

### ISSUE THREAD

**Issue by Vlad-M-1** [mikepenz/FastAdapter#361]
Exceptions that are thrown by ViewHolder constructor lead to [this line](https://github.com/mikepenz/FastAdapter/blob/a060aca5105eda89d02cced1a7da6e20077dba2f/library-core/src/main/java/com/mikepenz/fastadapter/items/AbstractItem.java#L349) which says:
`throw new RuntimeException("You have to provide a ViewHolder with a constructor which takes a view!");` which is not the cause in this situation.

Currently to get the real reason of a problem there's a need to set a breakpoint at this line to check `e` variable value. It would be good for a faster debugging to change that line.

**Comment by FabianTerhorst** [comment]
There could be no need for this anymore in a newer version. 
https://github.com/mikepenz/FastAdapter/pull/353

**Comment by mikepenz** [comment]
I close this issue as it will be completely fixed in v3 and is no real problem in v2.
