### ISSUE TITLE
How to add FastAdapter V3 to the project

### ISSUE THREAD

**Issue by judemanutd** [mikepenz/FastAdapter#365]
I am currently on v2.1.7 and i want to try out V3
The current dependencies i have are 
compile 'com.mikepenz:fastadapter-extensions:2.1.7@aar'
compile('com.mikepenz:fastadapter:2.1.7@aar') {
        transitive = true
    }

I added the following to my porject but i get an error while syncing which says that the library depends on one or more android libraries but is a jar.
`allprojects {
	repositories {
	    maven { url 'https://jitpack.io' }
        }
}

dependencies {
        compile 'com.github.mikepenz:fastadapter:v3-SNAPSHOT'
}`

**Comment by FabianTerhorst** [comment]
Its because Jitpack is providing a jar instead of an aar. You should better wait for the merge.

**Comment by mikepenz** [comment]
@judemanutd currently there are not yet v3 builds as it is in development, and things are subject to change. I suggest you either build the dependency from source manually (you will find solutions how to do this on Stackoverflow) Or you include the library as module in your project. Or you just try around the sourcecode with the sample app directly in Android Studio. I will provide alpha builds as soon as we feel it's ready
