### ISSUE TITLE
Creating an Animation Finished Listener

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#366]
This isn't a bug with your adapter, but since I'm using your adapter and it's so extensive, I was wondering if you would know the solution to the following problem:

I am trying to disable scrolling when animations are running. The `dispatchAnimationsFinished()` method works, but if I add a listener through `isRunning(...)` right after adding items to the adapter:

```java
@Override
public FastItemAdapter<Item> add(int position, List<Item> items) {
	...
	super.add(position, items);
	triggerListener(getAnimFinishedListener(ADD));
	return this;
}
```

 it will still run before any animations start. As a result, the listener will end itself then, rather than when all the animations are finished. My solution was to add a handler to wait 100ms before adding the listener, but I was hoping for a better solution.

Here is my implementation:

```java
private void triggerListener(@NonNull final RecyclerView.ItemAnimator.ItemAnimatorFinishedListener listener) {
	if (mRecyclerView == null) return;
	final RecyclerView.ItemAnimator itemAnimator = mRecyclerView.getItemAnimator();
	if (itemAnimator == null) {
		listener.onAnimationsFinished();
		return;
	}
        //isRunning is false here; so a listener would be executed immediately
	final Handler handler = new Handler();
	handler.postDelayed(new Runnable() {
		@Override
		public void run() {
			itemAnimator.isRunning(listener);
		}
	}, 100);
}
```

and [Here](https://github.com/AllanWang/SwipeRecyclerView/blob/303d71080af8da9a0c271bf3fb4fe129941a1f83/swiperecyclerview/src/main/java/ca/allanwang/swiperecyclerview/library/adapters/AnimationAdapter.java#L149) is the complete source

**Comment by mikepenz** [comment]
@AllanWang this is something the adapter can't handle for you, as the adapter itself also does not know when the `RecyclerView` finished updating it's view. Basically the adapter adds the items to the managed list of items, and will notify the recyclerview (via the adapter's method) about the changed items (added, removed, ...) 

So then the `RecyclerView` will kick in, use it's `Animator` + `LayoutManager` to draw and display the new items. All of this happens beside the adapter, and is not interacting with it (it just binds the views) 

A quick google showed the following:
http://stackoverflow.com/a/33710606/325479

**Comment by AllanWang** [comment]
@mikepenz thanks for the response. I came across that answer, but that's a listener for each viewholder, whereas I am looking for a callback once all the views finish animating. The implementation I have now is similar to that, with the only issue being the time between calling `add()` in the adapter to the time adding the views actually take place.

I will continue looking for a better solution elsewhere.
