### ISSUE TITLE
ActionModeHelper.isActive() returns false while it shouldn't?

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#368]
hi.
i have a list of items and when one of them is clicked i need invoke some method. however, if action mode is active, i do not want to invoke that method and instead a click should select that item. basically my onclick looks like this:

```
@Override
	public boolean onClick(View v, IAdapter<BaseItem> adapter, BaseItem item, int position)
	{
		if (mActionModeHelper.isActive() == false)
		{
			doSomething();
		}

		return true;
	}
```

i have successfully set up my list to select items on long click, and after the first item is selected, selecting additional items is done via regular click. so far so good.

the problem is after selecting the first item (by long clicking), when i click (tap) another item in the list in order to select it, mActionModeHelper.isActive() return false and therefore doSomething() is invoked, which i don't want. why does isActive() return false? action mode is clearly active.

thanks

**Comment by FabianTerhorst** [comment]
You could try to call the reset method, because active is checking if the mode is null or not.

**Comment by or-dvir** [comment]
@FabianTerhorst thanks for your reply.
where should i call the reset method? what will it do exactly and how would it fit my needs? why would action mode be null once i click an item on my list? (**not** on the CAB)

**Comment by or-dvir** [comment]
i figured it out! kind of...
if you came across the same issue as me and found this thread, please keep in mind that while this works for my app logic, it may not work for yours

my original onPreClickListener was simply copied from the sample project, however i still don't fully understand the flow of the click events of this library.

```
@Override
			public boolean onClick(View v, IAdapter<BaseItem> adapter, BaseItem item, int position)
			{
				Boolean res = mActionModeHelper.onClick(item);
				return res != null ? res : false;
			}
```

anyways, i figured out that while in actionMode, when the last selected item is clicked, the "behind the scenes" onClick (triggered by mActionModeHelper.onClick(item)) is finishing the actionMode (as it should, since the last item was de-selected) and thats why when i reach my on onClick actionMode is not active anymore!

i came up with a fix but it feels kind of like a hack to me... @mikepenz @FabianTerhorst please tell me if you think this is a bad solution, and you have a better idea (like i said, i still don't fully understand the flow of the click events in the library).

this is my new onPreClickListener and so far it seems to work.

```
@Override
			public boolean onClick(View v, IAdapter<BaseItem> adapter, BaseItem item, int position)
			{
				Boolean res = mActionModeHelper.onClick(item);

				//if actionMode is no longer active,
				//it means that this click event was performed on the last
				//selected item (which ended actionMode).
				//in this case, we do not want to pass the event on
				//to the activity's onClick method because this click
				//was intended to de-select an item, and not to
				//perform the click action of the item.
				if(isActionModeActive() == false)
				{
					return true;
				}

				return res != null ? res : false;
			}
```

**Comment by mikepenz** [comment]
@or-dvir do you use `mSupportSubItems`? of the `ActionModeHelper`?

Can you please debug the locations where the `mActionMode` is set to null:
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/ActionModeHelper.java#L149
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/ActionModeHelper.java#L156
and what triggers them?

That's the only reason for it to return `false`

**Comment by or-dvir** [comment]
@mikepenz no i am not using supportSubItems (ive seen it mentioned in some places in the source but havent looked into what it even means yet).
after further investigation i believe it was happening only with regards to the last item (i have since fixed the issue so i don't remember exactly) and it just had to do with the library's order of calls to the onClick and/or selection process. if i remember correctly, when i de-selected the last item, the library first finished action mode, and only then invoked onClick() - therefore by that time action mode was indeed closed. i dont fully understand the order of calls regarding click events, so i am assuming that the situation i just described makes sense to you and to the library's operation.

the way i fixed it was to give up and handle action mode myself and then i had control on whenever to finish it. i would have much preferred to save all that time (and potential future bugs) though by using the library's inner logic but as i said, i couldnt figure out the way click events are handled and forwarded :(

**Comment by mikepenz** [comment]
@or-dvir I really wonder what was going on here. I was testing and debugging it myself and was not able to see it. but possibly your use-case just results in this issue

**Comment by or-dvir** [comment]
Like I said, it just has to do with the order of event handling in the library.
I.e. First it closes action mode, then invokes on click. Therefore in my onClick, action mode is not active
