### ISSUE TITLE
Realm 3.0 support

### ISSUE THREAD

**Issue by Chuckytuh** [mikepenz/FastAdapter#369]
Enhancement suggestion, realm has released version 3.0 that has fine-grained notifications over collections which means we there's more control over notify*Changed methods on the adapter.

See: https://realm.io/news/realm-java-3-0-collection-notifications/

Cheers

**Comment by FabianTerhorst** [comment]
It's already part of #294.

**Comment by mikepenz** [comment]
Close as it is already part of that PR
