### ISSUE TITLE
isRecyclable decremented below 0

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#370]
I'm testing the Checkbox Sample you have through my own app (we have essentially the same code). It works fine without animators, but as soon as I add one (ie [FadeIn](https://github.com/wasabeef/recyclerview-animators/blob/master/animators/src/main/java/jp/wasabeef/recyclerview/animators/FadeInAnimator.java)), I start receiving the following error:

```isRecyclable decremented below 0: unmatched pair of setIsRecyable() calls for ViewHolder{1534c69 position=2 id=102, oldPos=-1, pLpos:-1}```

The checkbox toggle still works, but it also seems to call the animation used for adding an object rather than simply setting the checkbox to checked or unchecked. Do you have any insight on this?

[Here](https://github.com/AllanWang/SwipeRecyclerView/blob/master/sample/src/main/java/ca/allanwang/swiperecyclerview/sample/fragments/HomeFragment.java) is the fragment used to implement this; it's essentially the same as your sample activity, apart from the itemanimator

**Comment by mikepenz** [comment]
@AllanWang the `isRecycleable` error comes from the `RecyclerView` the `FastAdapter` itself nor the `IItem` interface do not makr the items as recycleable or not. That's all handled by the RV itself

**Comment by mikepenz** [comment]
I think that's an issue caused by the animation you use. Please head over there. (you can also try the `ItemAnimators` library from me, perhaps it is different)

**Comment by AllanWang** [comment]
I found the solution and am linking it [here](https://github.com/wasabeef/recyclerview-animators/issues/85#issuecomment-294960198) in case someone stumbles across it while using FastAdapter

The solution was to add 

```java
if (oldHolder == newHolder) {
    // Don't know how to run change animations when the same view holder is re-used.
    // run a move animation to handle position changes.
    return animateMove(oldHolder, fromX, fromY, toX, toY);
}
```

in animateChangeImpl

**Comment by mikepenz** [comment]
Thanks for adding this info :)
