### ISSUE TITLE
onSelectionChanged bug

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#371]
hi.
im pretty sure i found a bug in the function onSelectionChanged().

in that function, if the first item is being selected, calling mAdapter.getSelections().size() returns 1 (i.e. the newly selected item has been added to the "selections" list).
however when selecting another item (i.e. the second item) it **still returns 1** (i.e. the newly selected item is **not yet** added to the "Selections" list).

the opposite bug happens when de-selecting the last item.
if i have 2 items selected, and i de-select one of them, mAdapter.getSelections().size() would return 2 (i.e. the item is **not** removed from the "Selection" list).
and when i de-select the first item (which is the last item selected) it would return 0 (i.e. the item **is** removed from the "Selections" list).

**Comment by mikepenz** [comment]
@or-dvir at which point of time do you check for the selection count?

**Comment by or-dvir** [comment]
@mikepenz it was one of the first calls in the method "onSelectionChanged()". but does it really matter at which point inside that method i called "getSelections()"? unless you are using multiple threads to handle selection this shouldn't happen. what i **believe** is happening (did not check) is that the library must be calling this method ("onSelectionChanged()") in multiple places (which relate to the checked item being the first/last/in the middle) and somehow the order of the calls is being messed up. what i mean is for example (again, only my opinion without checking source code) if the item is the first one being selected the library is first adding it to the "Selections" list, and then calling onSelectionChanged(), but when selecting another item, it first calls onSelectionChanged() and **afterwards** adding it to the "selections" list

**Comment by mikepenz** [comment]
You can see in this sample that the correct popup (and the correct count) is returned by the methods:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiselectSampleActivity.java#L88


With at which point you ask for the count I meant if it's the normal Click listener, or the `withOnPreClickListener` (which would have not the correct value yet), ... ?

**Comment by or-dvir** [comment]
@mikepenz neither. im talking about onSelectionChanged()

**Comment by mikepenz** [comment]
Well stupid me. Makes totally sense. (This only happens for the positionBasedStateManagement):
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1028
