### ISSUE TITLE
Is it possible to have sticky behavior on expandable cells?

### ISSUE THREAD

**Issue by bmarty** [mikepenz/FastAdapter#372]
Hi Mike,

This is not an issue but more a question.

I'm using FastItemAdapter with items extending AbstractExpandableItem. It works like a charm ;-)

I want the expandable items to be sticky. I checked in your sample, and only the sub items seem to have the scticky behavior. By applying the sample to my code, the headers are duplicated.

Do you know if it is possible to have the expandable items to be sticky (a simple answer "Yes" or "No" may be enough)?

Thanks for any advice

Benoit

**Comment by mikepenz** [comment]
What exactly do you mean with sticky? Like the `StickyHeaders`? 

This is not possible for normal items. sorry. The sticky headers are not items, but it's an ItemDecoration

**Comment by FabianTerhorst** [comment]
It possible with a Layout Manager to Stick Items at the top. For example https://github.com/ShamylZakariya/StickyHeaders/tree/master/stickyheaders/src/main/java/org/zakariya/stickyheaders

**Comment by bmarty** [comment]
Ok, thank you for your quick feedback. Finally I managed to draw a sticky header manually, by registering a scroll listener on the RecyclerView. It is not fully optimized or reusable, but it works ;-)

**Comment by mikepenz** [comment]
@bmarty great :)

**Comment by marbat87** [comment]
@bmarty Could you please provide a sample code?

Thanks in advance
