### ISSUE TITLE
wrap multiple viewholders with MoPubRecyclerAdapter

### ISSUE THREAD

**Issue by urob0ros** [mikepenz/FastAdapter#374]
Im trying to get mopub ads with stick headers but i'm a bit stuck. Here is what im currently doing: 

`recyclerView.setAdapter(stickyHeaderAdapter.wrap(headerAdapter.wrap(**mopubItemAdapter**)));`

Its working great except im not getting any ads. Ands its because im wrapping MopubFastItemAdapter<IItem> in the end and not MoPubRecyclerAdapter (where the ads are stored).
How do i get around this? the .wrap doesnt accept MoPubRecyclerAdapter

Any ideas?

thank you!

**Comment by mikepenz** [comment]
@urob0ros the `MoPubRecyclerAdapter` has to be set to the `RecyclerView` and all other adapters are just it's childs

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MopubAdsActivity.java#L62

**Comment by urob0ros** [comment]
i love you.
