### ISSUE TITLE
withSelectOnLongClick not working while filtered

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#375]
hi.
i have noticed some weird behavior:
in my adapter i have called "withSelectOnLongClick(true)", and when i long click an item it does indeed get selected (the background color changes and "onSelectionChanged()" is invoked). however if the list is filtered, the item does **not** get selected (background color does **not** change and "onSelectionChanged()" is **not** invoked). 

this does not happen on the sample app so it must somehow be my fault, but i have not idea what i have done wrong (given that with an unfiltered list it works just fine).

i would attach some code but im not sure which part would be relevant... please advise

**Comment by or-dvir** [comment]
nevermind i found what i was doing wrong...
i used setOnActionExpandListener on my search button and there i called withSelectable(false)

**Comment by mikepenz** [comment]
ok thanks :)
