### ISSUE TITLE
how to implement shared viewHolder?

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#376]
hi.
i would like to implement a shared ViewHolder for all my items because all of my items share a TextView and a CheckBox, and then every other object (item) type may add other views to the layout (e.g. Spinner).

this is my BaseItem.ViewHolder. all other objects in my app extend BaseItem and their respective ViewHolders extend this BaseItem.ViewHolder:

```java
static class ViewHolder extends RecyclerView.ViewHolder
	{
		protected TextView textView;
		protected CheckBox checkBox;

		public ViewHolder(View view)
		{
			super(view);
			textView = (TextView) view.findViewById(R.id.textView);
			checkBox = (CheckBox) view.findViewById(R.id.checkBox);
		}
	}
```

this is an example of a layout for one of my items (the most basic one which only includes the TextView and the CheckBox):
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:descendantFocusability="blocksDescendants"
                android:padding="16dp">

    <TextView
        android:id="@+id/textView"
        style="?android:textAppearanceListItemSmall"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentLeft="true"
        android:text="place holder"
        tools:ignore="HardcodedText,RtlHardcoded"/>

    <CheckBox
        android:id="@+id/checkBox"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:layout_centerVertical="true"
        tools:ignore="RtlHardcoded"/>

</RelativeLayout>
```
the problem is the findViewById method in BaseItem.ViewHolder return null.

if i add findViewById calls to each individual ViewHolder (instead of extending a shared one) everything works fine, but this is just a hassle and isn't very object-oriented.

how can i fix this?

**Comment by mikepenz** [comment]
@or-dvir hmmm I am not really sure why the `FindViewById method would return null. 

I use a base `ViewHolder` in a project and it works without problems. 

What layout id is defined for the base/implementing class?

**Comment by or-dvir** [comment]
@mikepenz the BaseItem actually does not have any layout as i am just using it as a shared object all other objects inherit from, so it doesn't really need a layout. but according to object oriented programming that shouldn't matter because the "getLayoutRes()" method of the inherited item should be called (for example the one that returns the layout i posted in my question).

i also tried separating the viewHolder from BaseItem and making it a separate class and that didn't work either

**Comment by mikepenz** [comment]
that's weird. 

For example you can have a loook on `SimpleSubItem` and `SimpleSubExpandableItem` where `SimpleSubExpandableItem extends SimpleSubItem`

**Comment by or-dvir** [comment]
@mikepenz ill try when i have time (whenever that may be...)

**Comment by mikepenz** [comment]
Ok. I'll close this now, as I am sure this is possible (as I use it multiple times already)
