### ISSUE TITLE
Listener for ViewHolder bound to RecyclerView

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#378]
I've written following adapter:

    public class MyFastAdapter<Item extends IItem> extends FastItemAdapter<Item>
	{
		private HashSet<IDataReadyListener> mListeners = new HashSet<>();
		private boolean mReady = false;

		public MyFastAdapter()
		{
			super();
		}

		public void addDataReadyListener(IDataReadyListener listener)
		{
			mListeners.add(listener);
		}

		public void removeDataReadyListener(IDataReadyListener listener)
		{
			mListeners.remove(listener);
		}

		public void notifyDataReadyListener(int position)
		{
			mReady = true;
			for (IDataReadyListener listener : mListeners)
				listener.onDataReady(position);
		}

		public void onBindViewHolder(RecyclerView.ViewHolder holder, int position)
		{
			super.onBindViewHolder(holder, position);
			notifyDataReadyListener(position);
		}

		// -----------------------
		// IDataReadyListener
		// -----------------------

		public interface IDataReadyListener
		{
			void onDataReady(int position);
		}
	}

And in my activity I use following:

	mFastAdapter.addDataReadyListener(new MyFastAdapter.IDataReadyListener()
	{
		private long mReadyPositions = 0;

		@Override
		public void onDataReady(int position)
		{
			if (position < 4)
			{
				mReadyPositions = BitUtil.setBit(mReadyPositions, position, true);
				if (BitUtil.areBitsSet(mReadyPositions, 0, 1, 2, 3))
				{
					TutorialManager.checkTutorial(false, savedInstanceState, MainActivity.this, mBinding);
					mFastAdapter.removeDataReadyListener(this);
				}
			}
		}
	});

**What I want**

* I want the first 4 views to be bound to the `RecyclerView` because I want to show some tutorial views
* I get the views for my tutorials with the help of `recyclerView.findViewHolderForAdapterPosition(pos).itemView`, so I need to know when it's save to call this function

Any ideas why above is not working? Do you have an alternative idea/solution? Even after 4 views are bound, not all of them are available yet via `findViewHolderForAdapterPosition`...

**Comment by mikepenz** [comment]
@MFlisar I would not depend on the adapter for this, as it is not the adapters function to display the element. It just creates the view. But it is no guarantee that it is then displayed already 

I think maybe the RV has listeners or the LayoutManager which give you a better control over this. 


In addition why don't you simply set the items to the adapter, and then display the tutorial?
