### ISSUE TITLE
Filter - does not reset it's internal state correctly

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#379]
The default `ItemFilter` does not reset it's internal `mOriginalItems` if I for example set new items to my adapter with `.setNewList(items)`.

If I see it correctly, there are more cases where this happens (`ItemAdapter.clear()` for example, ...)

I stumbled over this problem by initialising an adapter with an empty list and then filtering the adapter, then the data is loaded in the background, the adapter is updated with `setNewList` and then the filtering is not working---

**Comment by mikepenz** [comment]
@MFlisar simply reset the filter prior to changing the items should solve this

**Comment by Rainer-Lang** [comment]
But is this the expected behavior... to reset the filter?

**Comment by MFlisar** [comment]
Not for me. Solution is following:

* save filter
* reset filter
* update list
* reset filter

**Comment by mikepenz** [comment]
@MFlisar resetting after the list was updated?

**Comment by MFlisar** [comment]
Then I'll lose the filter. I want that it does not matter if the user starts filtering before the data is loaded or vice versa. Above is working though

**Comment by mikepenz** [comment]
Ah ok. for this case it makes sense. In general for the adapter itself it shouldn't be the case. as new data-set should result in a new filtering.

**Comment by MFlisar** [comment]
That's what I expected, but in this case, I have to manually reset the filter as well, imho this should happen via the `setNewList`...
