### ISSUE TITLE
Wrong click position in recyclerview

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/FastAdapter#38]
Hi, Mike, i have tested the library with a simple example of a list in a recyclerview, only 2 items in the list.

I created a new proyect with the class and layout of your example, class "SampleItem" and the layout "sample_item"

The layout of the list item is the same as the example of the library, the only difference is i add a cardview around the items (name and description).

the list shows fine, with only 2 cardview, but when i click in the first item, the click event shows in the second item, is like add +1 position to the item i click, and viceversa, when i click in the second, the click shows in the first XD:

**Comment by mikepenz** [comment]
@seba123neo could you please provide the issue as a small sample so I could debug it?

**Comment by seba123neo** [comment]
it's probably my mistake, I'm missing something, I need to know what I'm missing.

now I upload the code I'm using.

**Comment by seba123neo** [comment]
This is the code of the example
[app.zip](https://github.com/mikepenz/FastAdapter/files/120394/app.zip)

**Comment by mikepenz** [comment]
@seba123neo I can't see the issue with your sample either. If I click on the first item the toast will show "Item1" and if i click on the second it will show "Item2"

**Comment by seba123neo** [comment]
yes, the toast works fine, but the "click effect" is show in the other item.

**Comment by seba123neo** [comment]
Look the video
[20160206_161547.zip](https://github.com/mikepenz/FastAdapter/files/120416/20160206_161547.zip)

**Comment by mikepenz** [comment]
@seba123neo seems like a weird issue of the `CardView`. Somehow it does not show the click, neither does it show the ripple by default. seems like you would have to apply the ripple on your own. 

I have modified your demo to show a touch effect. 

[demo.zip](https://github.com/mikepenz/FastAdapter/files/120420/demo.zip)

I also have the description why it looked like the effect was always one off. If you click, the default behavior is that the FastAdater selects this item. So the view is in a selected state. (i disabled this now with withSelectable(false), so there will be no selected state, you can enable it again if you want)
If you now select the second item, the previous item is deselected, and this sometimes displayed the ripple. 

So what I've done. I added a background to the CardView which has a touch color state, and a selected state. it will now probably display those things

**Comment by seba123neo** [comment]
now works, thanks for the explanation !!! thanks for your time 
keep it up
