### ISSUE TITLE
withOnlyOneExpandedItem causes clicks on SubItems to collapse all sections

### ISSUE THREAD

**Issue by marbat87** [mikepenz/FastAdapter#383]
Hi,

I implemented expandable sections with items provided in the example application:
SimpleSubExpandableItem, SimpleSubItem

Adding withOnlyOneExpandedItem to the adapter, causes that any click, on a SimpleSubItem item, collapses the opened section.

Regards.

**Comment by mikepenz** [comment]
@marbat87 the `withOnlyOneExpandedItem` was properly designed for a single level. If you have deeper nesting you may want to do some logic on your side, as handling all those scenario in the lib would make it to huge. And I believe the FastAdapter itself should be as slim as possible.

**Comment by marbat87** [comment]
I was talking about a single level implementation.
Step to reproduce:
- Click on a SimpleSubExpandableItem >> the section is expanded
- Click on  SimpleSubItem >> the previously expanded section is collapsed!

I think you can replicate  the issue, just adding withOnlyOneExpandedItem(true)  on your adapter in ExpandableSampleActivity.

**Comment by marbat87** [comment]
@mikepenz When will you release a new version with this fix?

Regards

**Comment by mikepenz** [comment]
I have no ETA for it. 
If you already need it jitpack might work, or building the library from source
