### ISSUE TITLE
Issues with filter

### ISSUE THREAD

**Issue by jelther** [mikepenz/FastAdapter#384]
Hi Mike,

I'm trying to implement a simple adapter with a filter but looking at your examples (specially SimpleList) I can't figure out how you restore your list after filtering.

Based on your example, I've built a adapter but after filtering my items have gone.

I'm sorry if this is a dumb question but the way I see you only populate your adapter once at your example.

Thanks!

**Comment by mikepenz** [comment]
@jelther so basically the `ItemAdapter` provides the `Filter` functionality built in. For this it has a inner class... the `ItemFilter`. 

So after you set a list to the `ItemAdapter` you are good to go. 
You just need to define how filtering works based on your items:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SimpleItemListActivity.java#L79

Afterwards just use the `filter` method:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SimpleItemListActivity.java#L163

As soon as the `constraint==null` or `constraint=""` it will reset to the initial list.

**Comment by jelther** [comment]
Mike,

Here is my code. I guess the only difference is that I'm using a Fragment instead of an Activity.

https://github.com/jelther/DiceWareBr/blob/master/app/src/main/java/com/jetolgon/dicewarebr/ListaFragment.java

And my Item:

https://github.com/jelther/DiceWareBr/blob/master/app/src/main/java/com/jetolgon/dicewarebr/DicewareItem.java

I've debugged your code and I've saw your SimpleItem doesn't lose its size. But my code the size of my adapter goes to 0 after the filtering.

Thanks!

**Comment by mikepenz** [comment]
@jelther I just tried. It is indeed an issue (also reproduceable) in the sample of v2.5.0

**Comment by jelther** [comment]
@mikepenz , I'm relieved. I thought it's was a code error since I'm still a beginner on Android Dev. Thanks!

**Comment by mikepenz** [comment]
@jelther thanks for reporting. And sorry for the trouble. 

I am already uploading and releasing v2.5.1 with this issue fixed.

**Comment by jelther** [comment]
@mikepenz , I've downgraded my gradle version to 2.1.7 and it worked.
Your work is great and thank you for creating this library. There is no need to apologize.

I'll upgrade to the lastest version as soon as possible.

**Comment by mikepenz** [comment]
@jelther thank you very much. 

I have also re-released v2.5.0 (to limit the reach of this bug) 
Thank you very much. 

As for v2.1.7 vs v2.5.0 there were some changes in the item interface. So you may want to directly use v2.5.0.

**Comment by jelther** [comment]
Mike,

I've upgraded to the 2.5.1 version but now I'm getting the following error when I try to run the app:

> java.lang.NoClassDefFoundError: com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem$ItemFactory

I've already added the method `getViewHolder(View v)`. 

Do I need to do something extra?

**Comment by mikepenz** [comment]
please read the Migration steps :D 
https://github.com/mikepenz/FastAdapter/releases/tag/v2.5.0

**Comment by mikepenz** [comment]
The drawer version you use needs to match. https://github.com/mikepenz/MaterialDrawer

**Comment by jelther** [comment]
My bad. I've read 2.0.0 but now I paid more attention and it's clearly 2.5.0. Thanks!
