### ISSUE TITLE
UndoHelper snackbar text issue

### ISSUE THREAD

**Issue by marbat87** [mikepenz/FastAdapter#386]
Calling UndoHelper.remove multiple times with different messages, causes that always the first message used is shown.
This is because in UndoHelper.java class, the setAction method is called only when mSnackBar  is null.
So it is called only the first time.

Regards.

**Comment by marbat87** [comment]
In order to avoid this issue, actually the solution is to create a new UndoHelper, each time.

**Comment by mikepenz** [comment]
@marbat87 thank you for the report. you may want to open a PR enhancing it's behavior

**Comment by marbat87** [comment]
@mikepenz  done with #387 

Regards

**Comment by mikepenz** [comment]
Thanks
