### ISSUE TITLE
Is there a way to trigger itemTouchOnMove only when item move finished?

### ISSUE THREAD

**Issue by dcgavril** [mikepenz/FastAdapter#390]
Hello,

I want to implement the "itemTouchOnMove" / SimpleDragCallback - but the problem is that the method is triggered on each movement, even if the user hasn't finished dragging the list item and I want to do a single API request on an item move (ex: moving item from position 5 to 1, currently makes 4 requests instead of 1, imagine a longer list...).
Do you have an idea on how to deal with this?

Thank you!

**Comment by mikepenz** [comment]
@dcgavril this case is not provided by the simple drag callback helper class. I think you will make faster progress if you implement this for your special case, by directly using the functions of the support library. 

Or you implement your own implementation of SimpleCallback based on what we provide:
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/drag/SimpleDragCallback.java#L65

**Comment by dcgavril** [comment]
@mikepenz thank you for your answer. I know that this is useful to be able to update the adapter and the list view, but what I'm asking is not a custom case, it should be taken into consideration by anyone who implements this method because even if you don't do network requests but only database updates, you need to be careful about the number of triggers you set off for an item move, like I've said, currently it triggers N calls instead of 1. 

I've tried to use the onLongClick listener with MotionEvent in order to know when the user has released the item, but I haven't managed to get that notification, instead, the event goes very quickly from ACTION_MOVE to ACTION_CANCEL without notifying about a release event.

**Comment by mikepenz** [comment]
@dcgavril I understand your suggestion. And I totally back it. I just meant that the provided callback is the most simple case. I am more than happy to take a PR to improve this. But some of these helper classes were more meant to provide the most basic functionality for quick access of this, and more advanced cases, with more focus on detail. Is not covered by this Callback, as it would mean we have to implement a various range of configurations. 

If you want to improve it. I am more than happy to accept your PR though :)
