### ISSUE TITLE
How to get the realm data stored 

### ISSUE THREAD

**Issue by veeranath** [mikepenz/FastAdapter#391]
Hi,
how can i get the stored data saved using realm of the fast adapter? please help me

i had always using this method to get the data stored in the realm db without fast adapter and it works good but when i try using it with fast adapter i am getting null pointer exception

```
Realm invoicerealm=Realm.getDefaultInstance();
        Upcoming_requests_adapter upcomingrequest=invoicerealm.where(Upcoming_requests_adapter.class).equalTo("userid",getIntent().getStringExtra("userid")).findFirst();
```

**Comment by mikepenz** [comment]
@veeranath this is not a `FastAdapter` related question. Please see the Realm documentation on how to save data. 

Also I am really sure the nullpointer already tells you what's going on
