### ISSUE TITLE
Conflict with support library version

### ISSUE THREAD

**Issue by engi** [mikepenz/FastAdapter#392]
Hi Mike,
When I update my project with the FastAdapter last version (from 2.1.7 to 2.5.1) in graddle app module, AS tells me that I'm including two different support library versions.
There is no problem with FastAdapter 2.1.7 !
Do you have any idea where the problem may come from?
TIA,
Nicolas

**Comment by mikepenz** [comment]
As usual I updated the support libraries with the update of the library. 

You can exclude the included support libraries from the `FastAdapter` 
Like shown here: http://stackoverflow.com/a/21765656/325479

**Comment by engi** [comment]
I have done that :
```
 compile('com.mikepenz:fastadapter:2.5.1@aar') {
        transitive = true
        exclude group: 'com.android.support'
    }
```
but same problem ...
don't worry, app works anyway

**Comment by mikepenz** [comment]
you might also just overwrite it for all:

```
configurations.all {
    resolutionStrategy.force "com.android.support:appcompat-v7:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:cardview-v7:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:recyclerview-v7:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:design:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:percent:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:preference-v14:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:customtabs:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:support-annotations:${versions.supportLib}"
}
```

**Comment by engi** [comment]
It's ok now, thanks a lot :o)
