### ISSUE TITLE
Use of FastAdapter with sqlite data

### ISSUE THREAD

**Issue by engi** [mikepenz/FastAdapter#393]
Mike, another question :
I'm trying to use your FastAdapter lib to fill an expandable recyclerview (from two master/detail tables).
Usuallly, with classic recyclerview, I'm used to read data with cursor loaders.
In your sample app, your expandable recyclerview is filled with two array in an iteration.
Is there a way to do the same thing with cursor loaders ?
If not, i'll fill arrays but i'm afraid this is not very safe !
What do you think about this ?

**Comment by mikepenz** [comment]
@engi there is no adapter which directly accesses a cursor. So this doesn't exist yet. It should be possible to implement a `CursorAdapter` implementing the `IAdapter` interface, but will require some code. 

If you want to add such a functionality to the library it will be great.
