### ISSUE TITLE
undo helper bug

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#395]
hi.
i found a bug in UndoHelper.
full disclosure: it may be my fault as i submitted a pull request for UndoHelper regarding the snackbar (sorry!)

the bug is that once a snackbar is created for the first time, it is never reinitialized. so, when i call `remove(final View view, final String text, final String actionText, @Snackbar.Duration int duration, final Set<Integer> positions)`, snackbar is NOT null, and therefore simply shown, ignoring "text", "action text", and "duration".

ill see if i have time to submit another pull request soon, but can't promise

**Comment by mikepenz** [comment]
That's definitely not the case. The `Snackbar` is recreated no matter of the fact if it's null or not:

https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/UndoHelper.java#L121

**Comment by or-dvir** [comment]
@mikepenz my bad... wasn't using the latest version
