### ISSUE TITLE
FirebaseItemAdapter usage

### ISSUE THREAD

**Issue by dthib** [mikepenz/FastAdapter#397]
Hi,
I am using the FastAdapter library for the first time and I can't manage making the FirebaseItemAdapter work. I know that it's very experimental but I get a NullReferenceException inside onAttachedToRecyclerView. Do I have to use it alone or as a wrapper of FastAdapter? I am interested in a usage sample.
Thank you for your help and sorry for the naive question,
Best

**Comment by mikepenz** [comment]
@dthib the firebase adapter is very very experimental and was created a long time ago. So it might already be incompatible with the latest firebase version. It is also not mentioned in the README as I do not directly support it anymore. You might get it running, but it may require some changes from your side. If you figure out, I would be happy about a PR though

I am sorry for this.
