### ISSUE TITLE
Need OrderedRealmCollectionChangeListener

### ISSUE THREAD

**Issue by HanSeungYong** [mikepenz/FastAdapter#398]
Hi

https://realm.io/news/realm-java-3-0-collection-notifications/

Could you update "library-extensions-realm" project by OrderedRealmCollectionChangeListener?

Thank you

**Comment by mikepenz** [comment]
See v3 preview. This might help: https://github.com/mikepenz/FastAdapter/blob/0e82274356ce9cb7bc894ac957decd2642f19c95/app/src/main/java/com/mikepenz/fastadapter/app/RealmActivity.java
