### ISSUE TITLE
EndlessScroll - Current page value

### ISSUE THREAD

**Issue by rafakob** [mikepenz/FastAdapter#399]
Why in `EndlessRecyclerOnTopScrollListener` initial current page value is set to 0 and in `EndlessRecyclerOnScrollListener` is set to 1?

https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnTopScrollListener.java#L13

https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnScrollListener.java#L19

Can't find any reason for that.

**Comment by mikepenz** [comment]
This will be fixed with v3
