### ISSUE TITLE
Maintain a Sorted List

### ISSUE THREAD

**Issue by judemanutd** [mikepenz/FastAdapter#400]
I am pulling all my data from realm and displaying initially in a sorted list.Whenever items are added or removed or modified to this list i would like it to still be sorted.Is there a way realm can manage this sorted list internally and update the adapter or do i need a change listener and then manually sort it?

**Comment by mikepenz** [comment]
@judemanutd in the first place you should already make sure the items are added to the correct position. so you would not run into a sorted issue. if this is not possible. You have to sort it manually before stetting and then possibly applying it with the diffutil of the recyclerview or so. 

This seems to be no library issue.
