### ISSUE TITLE
Mopub ads causing stickheaderadapter items to be mis-grouped

### ISSUE THREAD

**Issue by urob0ros** [mikepenz/FastAdapter#401]
The ads are pushing the items to the next group.
Its as if the grouping and comparator is ignored.
When i remove the ads, it works fine. I thought it was a UI refresh issue, but its not.

How would you recommend i resolve this? Seems like i need to subtract an ID counter or something. So it ignores the ads and simple ads them within each grouped section.

Thanks again for your help!

**Comment by mikepenz** [comment]
@urob0ros I guess the issue with the ads + sticky header is that the `StickyHeader` goes to the absolute position, which is no longer true when different items were added inbetween (so the ads). 

You might solve it by modifying the positions the sticky header attaches to, or you just add the ad items inside your drawer manually. and handle the whole combination manually.

**Comment by urob0ros** [comment]
How do I modify the position of the sticky header? Or the position of the ads? Im assuming i have to modify the sticky header adapter

**Comment by mikepenz** [comment]
@urob0ros to be honest, as the sticky header is an external library and the the `MopubAdapter` too, I do not know. 

I guess it needs some adjustment of the `StickyHeaderAdapter`, or of the `MoPubAdAdapter`. 

Basically it is not a `FastAdapter` issue :D

**Comment by urob0ros** [comment]
I have this resolved. I can commit the code if you'd like.

**Comment by mikepenz** [comment]
@urob0ros sure :)
