### ISSUE TITLE
ItemAdapter add at 0 throws IndexOutOfBoundsException for index -1

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#403]
With your drawer I'm doing following:

    int posLoading = mDrawer.getPosition(ID_PROGRESS_LOADING_NETWORKS);
	if (posLoading == -1)
	{
		mDrawer.addItemAtPosition(new ProgressDrawerItem().withIdentifier(ID_PROGRESS_LOADING_NETWORKS).withName(R.string.status_loading_data), 0);
		mDrawer.getAdapter().notifyDataSetChanged();
	}
	
I got a crash report that looks like following:

    Caused by: java.lang.IndexOutOfBoundsException: Invalid index -1, size is 11
		at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260)
		at java.util.ArrayList.addAll(ArrayList.java:231)
		at com.mikepenz.fastadapter.adapters.ItemAdapter.b(ItemAdapter.java:396)
		at com.mikepenz.fastadapter.adapters.ItemAdapter.b(ItemAdapter.java:382)
		at com.mikepenz.fastadapter.adapters.ItemAdapter.a(ItemAdapter.java:26)
		at com.mikepenz.materialdrawer.Drawer.a(Drawer.java:700)
		at ....MainActivity.a(MainActivity.java:477) <= this line is the mDrawer.addItemAtPosition line above
	
Any ideas how this could be? I checked the code and as far as I see the index can't be < 0... As following is called:

- This line, it must be called with `position = 0` as this value is passed as fixed value in my function
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L396
- Then this line, which does only return values >= 0, doesn't it?
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L749

So the above exception should not happen. I must oversee something, any ideas?

PS: I'm using the newest FastAdapter and MaterialDrawer versions...

**Comment by mikepenz** [comment]
@MFlisar the methods require the GLOBAL position. if you have a header then position "0" is not in the item list. position 0 is in the header. 

so if you do something on the `itemadapter` and have a `headeradapter` you need to make sure the positions you use in the headeradapter are the global positions. The `ItemAdapter` provides a method to get the proper adjusted position if you need it

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L213

**Comment by MFlisar** [comment]
I'm not using header adapters, just a simple one with items. But I use the `AccountHeader` which I recently added, does this one use a `HeaderAdapter`?

**Comment by mikepenz** [comment]
exactly the `AccountHeader` is displayed in a `HeaderAdapter`. The javadoc of the methods mention that you should use the `globalPosition`

**Comment by MFlisar** [comment]
Then I have to check how `HeaderAdapter` works, have skipped this thing until now and used only my own defined headers yet

**Comment by mikepenz** [comment]
@MFlisar not sure why?
it is basically an adapter before the itemadapter. that means it shifts the GlobalPosition next per item you add to the adapter before. Basically the `FastAdapter` allows you to have as many adapters as you want to. Even though in most cases you will just have 1 or 2 or 3 (header item footer). The HeaderAdapter is exactly the same like an ItemAdapter just with a different order value (making it display it's items before the itemadapter)

Just use the above mentioned method which will return the proper global position if you know the relative position

**Comment by MFlisar** [comment]
With my headers I meant groups... Now I see what your headers are, I thought of something else. They are anyway something different. And your explainations made it clear now. Thanks
