### ISSUE TITLE
DiffUtils for the adapter

### ISSUE THREAD

**Issue by judemanutd** [mikepenz/FastAdapter#404]
I am using a GenericItemAdapter and i wanted to know if the setNewModel() function internatlly runs a diffutil callback or does it just refresh the entire list?

If not then would it work if i wrote my own diffutil class and dispatched the updates to the generic adapter?

I did end up writing my diffutil class but it doesn't seem to have any effect on the adapter.

**Comment by mikepenz** [comment]
@judemanutd `setNewModel` just sets the full new list. 

There is this util which would work for normal item's: https://github.com/mikepenz/FastAdapter/blob/a0d22ee7a483cbbda46038e04f387f81971666d5/library/src/main/java/com/mikepenz/fastadapter/commons/utils/FastAdapterDiffUtil.java 

It doesn't work for model's though. 

How does your diffutil class look like?

**Comment by judemanutd** [comment]
public class ChatDiffUtil extends DiffUtil.Callback {
    
    private List<Chat> mOldList, mNewList;

    public ChatDiffUtil(List<Chat> mOldList, List<Chat> mNewList) {
        this.mOldList = mOldList;
        this.mNewList = mNewList;
    }

    @Override
    public int getOldListSize() {
        return mOldList == null ? 0 : mOldList.size();
    }

    @Override
    public int getNewListSize() {
        return mNewList == null ? 0 : mNewList.size();
    }

    @Override
    public boolean areItemsTheSame(int oldItemPosition, int newItemPosition) {
        return mOldList.get(oldItemPosition).getChat_id() == mNewList.get(newItemPosition).getChat_id();
    }

    @Override
    public boolean areContentsTheSame(int oldItemPosition, int newItemPosition) {
        Chat oldChat = mOldList.get(oldItemPosition);
        Chat newChat = mNewList.get(newItemPosition);

        return oldChat.getLatest_message_time() == newChat.getLatest_message_time()
                && oldChat.getPolitico().getLast_updated() == newChat.getPolitico().getLast_updated();
    }

    @Nullable
    @Override
    public Object getChangePayload(int oldItemPosition, int newItemPosition) {

        Chat oldChat = mOldList.get(oldItemPosition);
        Chat newChat = mNewList.get(newItemPosition);

        if (oldChat.getLatest_message_time() != newChat.getLatest_message_time())
            return 1;

        if (oldChat.getPolitico().getLast_updated() != newChat.getPolitico().getLast_updated())
            return 2;

        return super.getChangePayload(oldItemPosition, newItemPosition);
    }
    }

**Comment by mikepenz** [comment]
How do you dispatchUpdatesTo to the adapter?

**Comment by judemanutd** [comment]
`final DiffUtil.DiffResult result = DiffUtil.calculateDiff(
                new ChatDiffUtil(oldList, newList), false);
    oldList= newList;
    result.dispatchUpdatesTo(itemAdapter);`

**Comment by mikepenz** [comment]
Well you should dispatch the items like shown here:
https://github.com/mikepenz/FastAdapter/blob/a0d22ee7a483cbbda46038e04f387f81971666d5/library/src/main/java/com/mikepenz/fastadapter/commons/utils/FastAdapterDiffUtil.java#L78

by default it does use the notify methods of the RecyclerView.Adapter, which won't allow the FastAdapter to do anything (the notify methods are final, so it's not possible for me to overwrite them)

**Comment by judemanutd** [comment]
@mikepenz will give it a try , thank you.
