### ISSUE TITLE
ActionMode is placed over the ActionBar (Toolbar)

### ISSUE THREAD

**Issue by filipebezerra** [mikepenz/FastAdapter#409]
I'm using the latest version of the FastAdapter and app-compat libraries and implementing the multi-selection feature in my app but I got this undesired behavior.

![actionmode](https://cloud.githubusercontent.com/assets/1006095/25623189/e97db346-2f2c-11e7-9da1-28f0ecee0c9d.png)

Activity theme:

    <style name="App.Theme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/color_primary</item>
        <item name="colorPrimaryDark">@color/color_primary_dark</item>
        <item name="colorAccent">@color/color_accent</item>
        <item name="android:windowBackground">@color/color_window_background</item>
        <item name="textColorError">@color/color_error</item>
    </style>

    <style name="App.Theme.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
    </style>

I'm also using MaterialDrawer but none of the `MaterialDrawerTheme` themes

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/res/values/styles.xml#L6

**Comment by filipebezerra** [comment]
Solved using `<item name="windowActionModeOverlay">true</item>`. Also to set statusBar color in ActionMode:

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
    getActivity().getWindow()
            .setStatusBarColor(getColor(getContext(), R.color.color_primary_dark));
}
```

Thanks @mikepenz
