### ISSUE TITLE
Questions to the devs/users of this lib

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/FastAdapter#41]
I would like to make this really great lib a bit more popular.
Therefore it would be great if the "users" of the FastAdapter could write a few reasons why they like this lib, what's special about,...

I like:
- the generic-adapter (separation of view and model)
- the chaining of other adapters fastscroller (MaterialScrollBar)
- that I simply could through every item (AbstractItem)
- the FastAdapter because it's SO EASY and FAST

Could you please help to find arguments/reasons to help so other devs are able to recognize that FastAdapter is GREAT! :)

Thanks.

**Comment by Rainer-Lang** [comment]
@mikepenz If no one else answers or writes....
I have to tell you: THANKS - your libs (all of them!) are really great - and you spend so much time for making others devs lifes easier. Your support is indeed superb and exceptional!
Thanks.

**Comment by mikepenz** [comment]
@Rainer-Lang thank you for opening this issue. I am really glad about the try to get some feedback :D 

And as long as I help others, I think, I have reached exactly the goal i was striving for ;)

**Comment by mattiasbe** [comment]
- Focused library, tries to do one/a few things well.
- Implements all minor tips/tweaks android devs have stated (creating listeners at creation time -not bind time, checking for no_position, etc etc)
- High quality in general, nice API.
- While a single developer, one with a good track record and stability
- Chaining of other adapters fastscroller (MaterialScrollBar)

**Comment by FabianTerhorst** [comment]
- time saver, you don´t have to create a new Adapter class for every new object that has to be in a recyclerview
- no need to use getItemViewType anymore, just create a object, the layout and add it to the list
- easy to migrate and less code, from a project with 20 and more entity objects which had to be in the same recylcerview, could fast migrate the entities to adapter items and after the migration i could remove thousands useless lines of code and classes.
- very good code documented and self understanding api
- useful FooterAdapter to add a progress bar to the end of the list
- better performance, the scroll performance is way better then a normal recyclerview adapter
- library size, the library is very small and doesn´t make the app noticeable bigger
- expendable items are easy to add in a few minutes
- production ready and safe to use

**Comment by Rainer-Lang** [comment]
Could you please make an example of this:
"useful FooterAdapter to add a progress bar to the end of the list"

And thank you for helping Mike.

**Comment by FabianTerhorst** [comment]
@Rainer-Lang thats a great idea,i will take a look into this tomorrow. I could also add a endless scroll listener.

**Comment by Rainer-Lang** [comment]
That's really great! 
I like how FastAdapter is growing. 
I'm also waiting for the swipe feature.

**Comment by hungcv92** [comment]
My english very bad! I hope you can know my mine!
I have problem like "how to changer RED color highlight when clicked Item recyclerview" in SimpleItemListActivity! Please tell me how to do this?

**Comment by Rainer-Lang** [comment]
Please this make a new issue. This issue is for other things. Thanks.

**Comment by hungcv92** [comment]
@Rainer-Lang oops sorry bro, im a newbie! Thanks for your recommend :D

**Comment by mikepenz** [comment]
Thanks everyone for the kind words ;)

**Comment by SMontiel** [comment]
Thanks @mikepenz. 
This library is great.

**Comment by mikepenz** [comment]
@SMontiel thanks :)

**Comment by hsdmiranda** [comment]
One thing that I would like to highlight about this library is that you guys work super fast and answer every question. That is for sure the biggest plus. Congratulation for the amazing work.

**Comment by mikepenz** [comment]
@hsdmiranda thanks ;)

**Comment by mikepenz** [comment]
Thanks everyone for the answers. It's really great to hear that people like this lib. 

Will close this now in the progress of cleaning up a few issues ;)
