### ISSUE TITLE
Duplicated items w/ simpleItem

### ISSUE THREAD

**Issue by jelther** [mikepenz/FastAdapter#411]
Hello Mike,

I'm adding some items to a simple adapter and I've realized there are some duplicated items when I scroll the recycler view down.

To avoid this behavior , I had to add the items using a loop and , for each one, instantiate a new object.

I can't post the code here (it's confidential)  but down below I'll post the specific portion:

```
f.enqueue(new Callback<List<Employee>>() {
            @Override
            public void onResponse(Call<List<Employee>> call, Response<List<Employee>> response) {

                mLoadingDialogFragment.dismiss();

                List<Employee> ret = response.body();

               /* using this method I get duplicated items */
                fastItemAdapterEmployee.add(ret);

                /* with this the recycler view behaves correctly */
               for (Employee employee: ret){
                    fastItemAdapterEmployee.add(
                            new Employee(employee.getMa(),employee.getName())
                    );
                }

```

Is it always necessary to instantiate a new object for each new item ?
By the way, I'm using Retrofit2 to get all this info.

Thanks!

**Comment by mikepenz** [comment]
@jelther no creation a new object should not be necessary. 

If I am correct the `onResponse` from Retrofit is not on the main thread. Please move the code to the main thread and it should be fine.

**Comment by jelther** [comment]
@mikepenz , doesn't Android block all Http tasks on MainThread? I'm pretty sure I can't. I've tried to make the request synchronous (a.k.a. not creating other thread) and my code raises an Exception. Using other approach like Asynctask would lead me to the same problem, I think.

**Comment by mikepenz** [comment]
@jelther it does. But I didn't talk about the request. I just talked about the result. All UI interactions have to happen on the Main Thread! Adding items to a RV adapter and notifying on any thread other than the UI thread will cause problems.

**Comment by jelther** [comment]
@mikepenz , I found the solution. My objects returned from Retrofit request were with the identifier set to 0. When I instantiate a new object, the Identifier is set to -1.

Adding this to the code `employee.withIdentifier(-1);` solved the issue.

**Comment by mikepenz** [comment]
@jelther ah yeah. didn't think of something like this. But the RecyclerView uses the identifier to optimize the display of items, and to speed things up. Great find.

**Comment by jelther** [comment]
@mikepenz , other detail: the attribute "mSelected" is also set to false and mess with onClick event. Maybe that should be in documentation.

**Comment by mikepenz** [comment]
@jelther in such cases there is the `GenericItemAdapter`. It splits up model and item so you do not run into these problems
