### ISSUE TITLE
FastAdapter doesn't work with android-map-utils library

### ISSUE THREAD

**Issue by avs20** [mikepenz/FastAdapter#412]
HI, 

I created an AdapterItem using the FastAdapter as I need to show the data in both RecyclerView and MapFragment.

I am using the android-map-utils library to cluster the pins on the map. 
But with the AbstractItem which my model extends is used the pins are not shown and clustered on the map as expected. 
When I do that with a simple POJO model it is rendered and clustered correctly. 

This may happen due to the implementation of the hashcode and equals in the AbstractItem which is not what the android-map-utils expect. 

Is there a way to use the AbstractItem with the android map utils?

**Comment by mikepenz** [comment]
@avs20 then you can simply use the `GenericItemAdapter` which allows you to have a model and an item...

See a sample in action here: 
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/GenericItemActivity.java

**Comment by avs20** [comment]
Thanks @mikepenz for such a fast response. Will there be any effects of using GenericItemAdapter?

**Comment by mikepenz** [comment]
@avs20 it is a little bit different as you have to call getModel() inside your item to access the fields of the model. but in general it's almost the same.

**Comment by avs20** [comment]
@mikepenz I extended my model with a GenericAbstractItem but it's still not rendering. May be I didn't understood it. What's the difference between a model and and Item? Is the model the POJO model and and  Item a FastAdapterItem? 
Do I have to keep two different classes one for the RecyclerView and the other for the map(which will be POJO)?

Thanks for replying to the basic questions.

**Comment by mikepenz** [comment]
model is a simple POJO
item is defining how to display that model


exactly

**Comment by avs20** [comment]
hi mike, 
I tried different versions but GenericAbstractItem also didn't worked. What worked was that I override the equals and hashCode method in the ItemClass (can be Abstract or GenericAbstract both) and then it started clustering. I went through this route because I wanted to have the same class object for both the map and the recyclerview. 
Now I have one question, by overriding these methods am I messing with some performance for the FastAdapter? I went through the code for the AbstractItem and I saw that you use some mIdentifier to distinguish between the objects.  I have overriden it with my object's unique Id. 
So If messing with the equals and hashCode degrade the performance or some other benefits provided by FastAdapter.

**Comment by mikepenz** [comment]
If your object has a unique ID it's totally fine. You can do this. It's only important that it's unique as it is used for some functions like remembering the position of a selected item, and it's also used by the RV to properly animate and display items. 

If your implementations are not super slow it's totally fine

**Comment by avs20** [comment]
Thanks Mike for the quick responses. 
You have been very helpful. You can close this issue/Question now.

**Comment by mikepenz** [comment]
Awesome :) Thank you very much
