### ISSUE TITLE
How to use sticky header as expandable items

### ISSUE THREAD

**Issue by Alex293** [mikepenz/FastAdapter#413]
Hi I'd like to use sticky headers as sections headers that could be expanded to show item inside the section. Could this be easily done with this lib ? I know there are sticky headers and expandable items but I'd like both to be the same item.

**Comment by mikepenz** [comment]
@Alex293 that's not possible. Item's are not sticky

**Comment by mikepenz** [comment]
There are possible ways via a custom LayoutManager. But you'd have to write it on your own, or find one supporting this

**Comment by mikepenz** [comment]
As @FabianTerhorst just told me. It's possible using for example this one: https://github.com/Doist/RecyclerViewExtensions/blob/master/StickyHeaders/src/main/java/io/doist/recyclerviewext/sticky_headers/StickyHeadersLinearLayoutManager.java

**Comment by Alex293** [comment]
Nice thanks for you quick answer gonna check that tomorrow
