### ISSUE TITLE
how to show empty view when there is no data

### ISSUE THREAD

**Issue by anton-khansa** [mikepenz/FastAdapter#415]
hi mike,
i have search on google about how to view ampty view but i didnt found it, i found 1 link https://github.com/mikepenz/FastAdapter/issues/102

but i dont understand what you mean u have do that with progressitem, could you help me please?i just want to show text " No Data" when there is no data found

**Comment by mikepenz** [comment]
@anton-khansa this is nothing the `Adapter` normally handles. In general empty views are separate views which are shown instead the `RecyclerView`. 

It is possible though to have an item which is displayed full height, and you can re-use it accross your app. Just create an item with a layout having "match_parent" as height
