### ISSUE TITLE
Drag and Drop shuffles items in the middle

### ISSUE THREAD

**Issue by LadwaAditya** [mikepenz/FastAdapter#419]
Is there a way to switch two items in a grid layout with the `SimpleDragCallback` when I try to drag an item the items in between are also rearranged. Is there a way to switch only two items in the view?

**Comment by FabianTerhorst** [comment]
The library is using the default recyclerview behavior.

**Comment by mikepenz** [comment]
@LadwaAditya you'd have to implement this on your own. The provided `SimpleDragCallback` is like @FabianTerhorst already pointed out using the default list behaviour. 

As far as I remember someone else already opened an issue similar to this, to only notify the RV about the position change after the item is dropped. you'd need to do something similar and then switch the 2 items.

**Comment by LadwaAditya** [comment]
@mikepenz  @FabianTerhorst  on version 2.6.2 of fastadapter and 2.6.0 of fastadapter-extensions the callback `itemTouchDropped` isn't called

**Comment by FabianTerhorst** [comment]
The most recent code change was in #425 .

**Comment by LadwaAditya** [comment]
@mikepenz @FabianTerhorst It worked. I actually hadn't implemented the `IDraggable` interface. 
Also the README needs an update
