### ISSUE TITLE
Kotlin compatibility: Reflection fails for ViewHolder with initializer blocks

### ISSUE THREAD

**Issue by timusus** [mikepenz/FastAdapter#42]
So this may be well beyond the scope of this library, but I'm not able to get the adapter to work when writing my implementation of `AbstractItem` in Kotlin, and using an initializer block ( `init{}` ) in the `AbstractItem.ViewHolder` class.

If `init{}` is used, the `ReflectionBasedViewHolderFactory` `constructor.newInstance()` call fails with an `InvocationTargetException`.

So, by way of example:

This is all within my 'AbstractItem' subclass, 
```
class EventCard(val event: Event) : AbstractItem<EventCard, EventCard.ViewHolder>() {
...
```

This code is OK, and will run just fine:
```
   class ViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
        var imageView: ImageView = itemView?.findViewById(R.id.imageView) as ImageView
   ....
```

But this code will fail, with the above-mentioned `InvocationTargetException`:
```
    class ViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
        var imageView: ImageView 
        init{
            imageView = itemView?.findViewById(R.id.imageView) as ImageView
        }
```

So it's not possible to do any sort of initialisation in the ViewHolder, when written in Kotlin, due to some sort of reflection issue, which I am not able to understand!! I've tried subclassing `AbstractItem` and looking at the `ReflectionBasedViewHolderFactory.create(View v)` method, but I just don't understand enough about Kotlin or reflection to figure out the problem.

Thanks in anticipation of your assistance!

**Comment by mikepenz** [comment]
@timusus will it also fail if you provide the factory for your item? See the following two methods:

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java#L130
```java
    /**
     * our ItemFactory implementation which creates the ViewHolder for our adapter.
     * It is highly recommended to implement a ViewHolderFactory as it is 0-1ms faster for ViewHolder creation,
     * and it is also many many times more efficient if you define custom listeners on views within your item.
     */
    protected static class ItemFactory implements ViewHolderFactory<ViewHolder> {
        public ViewHolder create(View v) {
            return new ViewHolder(v);
        }
    }
```

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java#L142
```java    
    //the static ViewHolderFactory which will be used to generate the ViewHolder for this Item
    private static final ViewHolderFactory<? extends ViewHolder> FACTORY = new ItemFactory();
    /**
     * return our ViewHolderFactory implementation here
     *
     * @return
     */
    @Override
    public ViewHolderFactory<? extends ViewHolder> getFactory() {
        return FACTORY;
    }
```

**Comment by timusus** [comment]
No, once I realised I could just create a factory which in turn creates the VieeHolder without using reflection, I was able to get it working just fine. 

Sorry, I didn't realise this was the recommended approach.

**Comment by mikepenz** [comment]
@timusus it is my fault as i haven't yet written this in the README just showcased in the sample app.
The solution via reflection was just created as the factory may confuse beginners so they can do it without reflection. For devs with more programming experience the factory is the way to go ;). 

Great that it solved your issue. 

If you have thoughts about the `FastAdapter` please let me know. Or answer in the other issue a friend opened. ;) Thank you
