### ISSUE TITLE
Actionmode helper is not functioning properly

### ISSUE THREAD

**Issue by EladKeyshawn** [mikepenz/FastAdapter#420]
ActionModeHelper doesn't work as expected, it's really frustrating especially after I moved some of my activities to use FastAdapter and now I'm wasting a long time for simple functionality.

**Comment by FabianTerhorst** [comment]
Could you provide some code and describe the behavior you don´t like.

**Comment by EladKeyshawn** [comment]
The procedure of prelongclick listener and preclicklistener are not handling properly the chain of events or the idea of handling is not explained well at all.

**Comment by EladKeyshawn** [comment]
@FabianTerhorst I'd be glad if you could help me with implementing the basic functionality of actionmode with fastadapter, thanks!

**Comment by mikepenz** [comment]
@EladKeyshawn you do not have to use the ActionModeHelper if it does not work as you expect. It's just a small helper to simplify things, but it is in no way necessary to implement a contextual actionbar
