### ISSUE TITLE
How to use this library ? please help

### ISSUE THREAD

**Issue by baadillahnabil** [mikepenz/FastAdapter#422]
hi, i am very newbie in recyclerview, i'm totally don't know how to start with this library. i followed your tutorial in readme.md , but i still don't understand the step by step to use this library.
what i don't understand is : 
1. in section **1. Implement your item (the easy way)** i don't know what that class is what that for especially the method `getType()`  i don't know what should i return 
2. in section **2. Set the Adapter to the RecyclerView** i don't know how this means `fastAdapter.add(ITEMS);` . i don't know what is `ITEMS` parameter in there and what exactly is `ITEMS` is ?

please add some more explanations in details so that a newbie like me can understand how to use this library. or (if you don't mind) you can create a video explanations about how to use this library (because i'm type a video learner guy) 

thank you before, for this great library 👍

**Comment by Rainer-Lang** [comment]
@baadillahnabil Please have a look at the included sample app.

**Comment by or-dvir** [comment]
@baadillahnabil 
1) create a file called "ids.xml" and put it in the "values" folder. in that file you define your item type id's. 
here is an example:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item name="fastadapter_id_checkedItem" type="id"/>
    <item name="fastadapter_id_dateTimeItem" type="id"/>
    <item name="fastadapter_id_personalNoteItem" type="id"/>
    <item name="fastadapter_id_spinnerCheckedItem" type="id"/>
    <item name="fastadapter_id_spinnerItem" type="id"/>
    <item name="fastadapter_id_mainItem" type="id"/>
    <item name="fastadapter_id_regularItem" type="id"/>
</resources>
```
and then:
```
	@Override
	public int getType()
	{
		return R.id.fastadapter_id_spinnerItem;
	}
```

2) the "add()" method has several variations - for simplicity i will refer to this one: `public FastItemAdapter<Item> add(List<Item> items)`.
"ITEMS", as you call it, is a list of objects that you wish to add to the adapter and display to the user.
for example lets say i have a class called "Item" and it contains 1 variable `String itemName;` (and the rest of the necessary codefor this library as described in the ReadMe file).

so here is an example of how i would use it:
```
Item item1 = new Item("first");
Item item2 = new Item("second");
Item item3 = new Item("third");

ArrayList<Item> itemList = new ArrayList();
itemList.add(item1);
itemList.add(item2);
itemList.add(item3);

FastItemAdapter<Item> adapter = new FastItemAdapter<>();
adapter.add(itemList);
```

**Comment by baadillahnabil** [comment]
**@Rainer-Lang** i did, but i'm confused in from where should i start looking because i really new on RecyclerView and i'm still learning it, but i do appreciate your answer. Thanks

**@or-dvir** Thank you very much man, i do now understand how it works, i'll try it. 
your explanation seems good to me, i think tutorial in readme.md should be added more explanation like your answer (just my opinion).. appreciate it man, Thanks 👍

**Comment by mikepenz** [comment]
@baadillahnabil glad that you figured out with the help of @or-dvir . 

In general the code + the APIs + the javaDoc + annotations make the whole library very self describing. So using the code + reading the code + looking at the JavaDoc should be quite obvious. 

I know the documentation is not written for beginners, but with a bit of experience in Java programming it should be fine.

In any case. as @Rainer-Lang pointed out, you can at any point check out the sample application which shows full working samples how to use the FastAdapter.
