### ISSUE TITLE
ActionModeHelper inconsistancy

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#423]
I'm refering to this line https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/ActionModeHelper.java#L108

Shouldn't it return true in this case as well? The documentation says `@return null if nothing was done, or a boolean to inform if the event was consumed` so I would expect this function to return true, if the click is changing the selection

**Comment by mikepenz** [comment]
the `null` info might not be true anymore.
But the event was not consumed, that's why nothing is returned. 

Do you have any problems because of this?

**Comment by MFlisar** [comment]
I'm always suprised when using the fast adapter in a new project and only see the problem when testing...

What is unexpecting is that I have to do following:

    .withOnClickListener(new FastAdapter.OnClickListener<Item>()
                {
                    @Override
                    public boolean onClick(View v, IAdapter<Item> adapter, Item item, int position)
                    {
                        // THIS LINE is unexpected!
                        if (mActionModeHelper.isActive())
                            return true;

                        onItemClick(v, adapter, item, position);
                        return false;
                    }
                })
                .withOnPreClickListener(new FastAdapter.OnClickListener<Item>() {
                    @Override
                    public boolean onClick(View v, IAdapter<Item> adapter, Item item, int position) {
                        //we handle the default onClick behavior for the actionMode. This will return null if it didn't do anything and you can handle a normal onClick
                        Boolean res = mActionModeHelper.onClick(item);
                        return res != null ? res : false;
                    }
                })
                .withOnPreLongClickListener(new FastAdapter.OnLongClickListener<Item>() {
                    @Override
                    public boolean onLongClick(View v, IAdapter<Item> adapter, Item item, int position) {
                        ActionMode actionMode = mActionModeHelper.onLongClick((AppCompatActivity) getActivity(), position);
                        //if we have no actionMode we do not consume the event
                        return actionMode != null;
                    }
                });

What I expect is that the `onPreItemClick` consumes the event if the adapter is in multi selection mode, but it does not currently. 

What I would prefer is following:

    * `mActionModeHelper.onClick(item);` should consume the pre click event and change the selection as well internally
    * then I don't need the ` if (mActionModeHelper.isActive())` in the `onClickListener`

At least I would change the doc of the method, I would add this to my pull request. Just telling you what is confusing for me, maybe you think it should be improved as well.

**Comment by mikepenz** [comment]
@MFlisar well there was a reason for the change, as it was preventing a special use-case. I think it had something to do with selecting the first time and/or the last time.

**Comment by mikepenz** [comment]
Just looked in the changes :D I have no idea to be honest. These lines were last changed by you :P

**Comment by mikepenz** [comment]
<img width="1218" alt="screen shot 2017-05-23 at 19 40 47" src="https://cloud.githubusercontent.com/assets/1476232/26384676/bf42a31a-3fef-11e7-8a0b-33a5be1e87b0.png">

**Comment by MFlisar** [comment]
Actually, I was wrong, the function does not do anything, I miss read it... It does not select items, so null is totally fine (so that's why I changed it ;-) )

It may be possible to consume the click and do the selection in the method though...
