### ISSUE TITLE
[QUESTION] StickyHeaders lib update/change

### ISSUE THREAD

**Issue by gaspar1423** [mikepenz/FastAdapter#424]
Hi,

i've been using this lib for a while and i works great for what a need but i have some problems with the StickyHeaders. I know you're using an external lib to achieve this effect but this lib as an issues with recycling the headers. Is the any change to use a different lib to achieve this feature?

To better explain my issue, i have a recycler view with clickable sticky headers to group items and swipe on the items. The swipe action on each item, can remove the item from the adapter or add it to a diferente position. This works great but some time, the header click gets passed to the first item of the group and i can't find a way to overcome this issue because the StickyHeaderAdapter assumes the item is a header item.

**Comment by mikepenz** [comment]
@gaspar1423 you can use whatever lib you want, as long as it does not require to extend the adapter.

Basically the FastAdapter is very open and flexible, so it allows almost any lib to be used in addition. The only limitation is that extending is not possible, if the lib provides an interface or similar it will work to extend the FastAdapter and implement that interface

**Comment by gaspar1423** [comment]
Hi,

I've fixed my issue by importing a fork of the timehop lib you are using and imported the .aar generated by that fork. (https://github.com/djdmbrwsk/sticky-headers-recyclerview)

Thank you for the help and your lib ;)
