### ISSUE TITLE
Use FastAdapter with non XML views

### ISSUE THREAD

**Issue by frmz** [mikepenz/FastAdapter#426]
For some reasons i am not able to create my views from XML but i need to create them runtime calling a constructure MyView(Context, Foo), how can i use FastItemAdapter with this? I have tried overriding GenerateView methods in AbstractItem without success, is this supported?

**Comment by FabianTerhorst** [comment]
You have to override getViewHolder and insert your custom view inside the viewholder constructor.

**Comment by FabianTerhorst** [comment]
Getviewholder result is already cached. Just create the viewholder every time the method is called.

**Comment by frmz** [comment]
Great! Thanks!!

**Comment by FabianTerhorst** [comment]
But there is still need for improvement, because your item has to provide an dummy layout inside getLayout. The viewinflater still tries to inflate the view even when you don't need it.

**Comment by FabianTerhorst** [comment]
Maybe we could add an getView() method that normally calls the layout inflater but can be overridden to return an custom view instead.

**Comment by frmz** [comment]
That would be mouch cleaner! Reopening the issue. Just noticed that returning 0 for the layout res will correctly make it crash

**Comment by FabianTerhorst** [comment]
In the meantime you could also override https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/items/AbstractItem.java#L232 and https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/items/AbstractItem.java#L250
but you have to remember binding the item and using getViewHolder for initialization of the viewholder.
