### ISSUE TITLE
How to get index in bindView callback

### ISSUE THREAD

**Issue by tariqul-islam1** [mikepenz/FastAdapter#429]
I am changing background color of grid items of my recyclerview. I have three colors to set according the index of the items. Here's which index to get which color:

- index: 0, color1
- index: 1, color2
- index: 2, color3
- index: 3, color1
- index: 4, color2
- index: 5, color3
- and so on

So I need to get index number in **bindView** callback

**Comment by mikepenz** [comment]
you need the position...

```java
//we get the adapterPosition from the viewHolder
                    int pos = mFastAdapter.getHolderAdapterPosition(viewHolder);
                    //make sure the click was done on a valid item
                    if (pos != RecyclerView.NO_POSITION) {
                        //do whatever you need to do in here :)
                    }
```

**Comment by tariqul-islam1** [comment]
Thanks
