### ISSUE TITLE
I want to remove this Chopping Animation 

### ISSUE THREAD

**Issue by surindersinghbindra** [mikepenz/FastAdapter#430]
![device-2017-05-23-163921](https://cloud.githubusercontent.com/assets/12382618/26388667/5dc969be-4073-11e7-8cc7-f4230752b72a.png)
I want to remove this Animation when i scroll down with the Keyboard Down Arrow Button on emulator. 
when i focus to next child of RecyclerView , it slowly Fad out. 
Please help.

**Comment by mikepenz** [comment]
You can disable the animation either by setting the animator to null, or by setting the animation duration very low. (the coresponding methods are used here: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SampleActivity.java#L163)

That's a `RecyclerView` functionality, and not a `FastAdapter` thing.

**Comment by surindersinghbindra** [comment]
Hi Mike , Can you please help me out from this issue. this doesn't look like the issue of item decorator. Do you have TeamViewer?
![device-2017-05-23-163921](https://cloud.githubusercontent.com/assets/12382618/26390911/3ad25f5a-407e-11e7-89aa-afa0b3e884b9.png)

**Comment by mikepenz** [comment]
@surindersinghbindra as mentioned the adapter does not handle the animations, that's done by the RecyclerView's ItemAnimator. And it also does not handle decorations. That's done by an ItemDecoration. 

Please refer to the corresponding docs. 

In addition. If you item uses a AnimatedStateListDrawable or so, it's your item which animates the background :D
