### ISSUE TITLE
HeaderHelper not creating group for last item

### ISSUE THREAD

**Issue by gpulido** [mikepenz/FastAdapter#431]
Hello!
I'm trying to use the HeaderHelper and I have found a probably bug on the header generation logic.
If you list only have 4 elements (I think that the problem will appears with 3 also), which each of the elements belongs to a different group the apply code is not creating the group header for the last element.
So if I have:
i1, i2, i3, i4 
I expect G1-i1 , G2-i2, G3-i3, G4-i4
but I obtain G1-i1 , G2-i2, G3-i3, i4
Reviewing the code and debuggin the iterator:
```java
 for (int i = -1; i < size; i++) {
                HeaderItem headerItem;
                if (i == -1) {
                    headerItem = groupingFunction.group(null, (Item) items.get(i + 1), i);
                } else if (i == items.size() - 1) {
                    headerItem = groupingFunction.group((Item) items.get(i), null, i);
                } else {
                    headerItem = groupingFunction.group((Item) items.get(i), (Item) items.get(i + 1), i);
                }

                if (headerItem != null) {
                    items.add(i + 1, headerItem);
                    i = i + 1;
                }
            }
```
is skipping the last pair check.
I'm trying to find the right logic.

**Comment by mikepenz** [comment]
@gpulido have you found out what the right logic would be?

**Comment by gpulido** [comment]
@mikepenz not yet, althought to be honest  I didn't have time to reviewied it properly. I expect to do it soon. Sorry for the delay, I'll keep you informed.

**Comment by mikepenz** [comment]
Don't worry :) Was just curious

**Comment by gpulido** [comment]
@mikepenz This is the changes that I've made to the apply code, instead of adding elements to the items list I just create a new list that I fill and use it instead. The problem is the last element,
```Java
  public void apply(List items) {
        //If the list is empty avoid sorting and adding headers.
        List newList = new ArrayList();
        if (items.size() > 0) {
            //sort beforehand
            if (comparator != null) {
                Collections.sort(items, comparator);
            }
            for (int i = 0; i < items.size(); i++) {
                HeaderItem headerItem;
                if (i == 0) {
                    headerItem = groupingFunction.group(null, (Item) items.get(0), -1);
                } else if (i == items.size() - 1) {
                    headerItem = groupingFunction.group((Item) items.get(i-1), (Item) items.get(i), i);
                } else {
                    headerItem = groupingFunction.group((Item) items.get(i), (Item) items.get(i + 1), i);
                }
                if (headerItem != null) {
                    newList.add(headerItem);
                }
                newList.add(items.get(i));
            }
        }

        /**
         * set the sorted list to the itemAdapter if provided
         */
        if (itemAdapter != null) {
            itemAdapter.set(newList);
        }
        if (genericItemAdapter != null) {
            genericItemAdapter.setModel(newList);
        }
    }
```
In the old code when the last element is used on the groupingFunction, that group doesn't have any way to know that i has to create a new group as it doesn't have information about the previous element. Maybe I'm missing something.
Please review it and let me know.
Regards,
Gabriel

**Comment by gpulido** [comment]
I made an error, to know which element are processing on the last item, the group method must be called with the parameters reversed:
```Java
 for (int i = 0; i < items.size(); i++) {
                HeaderItem headerItem;
                if (i == 0) {
                    headerItem = groupingFunction.group(null, (Item) items.get(0), -1);
                } else if (i == items.size() - 1) {
                    headerItem = groupingFunction.group((Item) items.get(i), (Item) items.get(i-1), i);
                } else {
                    headerItem = groupingFunction.group((Item) items.get(i), (Item) items.get(i + 1), i);
                }
                if (headerItem != null) {
                    newList.add(headerItem);
                }
                newList.add(items.get(i));
            }
```
The problem is that then the group is not receiving the "currentItem" and the "nextItem" in that case.
I'm not very happy with such solution, I will try to improve it.

**Comment by mikepenz** [comment]
@gpulido I have adjusted the code of the `HeaderHelper` can you please try if it is now working fine for you?

https://github.com/mikepenz/FastAdapter/commit/f9e8b4f828bf92616f0344c0066b8e8d57945c3b

**Comment by gpulido** [comment]
@mikepenz It works! 
I have just revert back the changes that I made to the grouping function and it works perfectly.
In which version of the adapter will be the changes available?
Thank you again for your amazing work and awesome feedback.
Gabriel

**Comment by mikepenz** [comment]
in v2.6.0. Sadly I can't give you and ETA yet.
