### ISSUE TITLE
Filter based on Item property not a constraint

### ISSUE THREAD

**Issue by frmz** [mikepenz/FastAdapter#432]
I am using FastAdapter to create a preference list, a few preferences needs to be visible only if others have a specific value, my current strategy to do this is the following:

- In the "Item" i provide a "isVisible()" method
- I am creating a Filter predicate that just ignores that ignores the costraint and uses Item.isVisible() instead
- I call Adapter.filter(random) every time i need to invalidate this

So, question is, can i safely call filter with an empty string or do i need to ensure i invalidate the constrain every time? Right now it looks like Filter is not checking if constrain changed but i wanted to be future proof. Also, is this a good approach?

**Comment by mikepenz** [comment]
@frmz the FastAdapter can not automatically check if some field on the item changed. The Adapter always needs to be notified about changes. 

well it is always a bit tricky in that case. You can look at the current filter implementation:
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L488

You might want to implement your own filter, more optimised for your case. A different option would also be (depending on your list length) to just supply the new list with the new amount of items and notify the adapter (you might even use the diff-util for that)

**Comment by frmz** [comment]
My implementation works well, i am just invalidating the filter with a random string when i know it needs to be changed. The only "annoying" thing is that if i start with a filtered list then the list first appears with all the items and then animates the filtering, while, in theory, it should never show the filtered items when doing the following:

- Adapter.clear()
- Adapter.filter("foo")
- Adapter.add(List<IItem>)

I have the same problem calling set every time the list changes since it blinks so visually is not the best idea either.

**Comment by frmz** [comment]
I just tested this a bit more and even disabling animations on the List wont solve this problem. From my point of view this is a bug, i would expect the items to never show up if i add them to a filtered list, not to show up and then be hidden after (from a thread since filtering is done on a thread thus not allowing animations to be disabled). Not sure how complex it is to check the filter when adding items.

**Comment by mikepenz** [comment]
It's not a bug, it's just how this specific thing was thought to work.
Well the chosen behaviour of setting a new list in the adapter will also reset the filter as this is the most common use-case. 

If you have a different use-case you could like I said just filter outside without using the constraint provided. You can also overwrite any of these methods from the ItemAdapter and change it's behaviours.

**Comment by frmz** [comment]
I understand "setting" a new list will reset the filter and i agree on that, however if clear, set a filter and then, after setting the filter, add an item i would expect that filter is checked against added items and they are not shown at all instead of being shown and then being hidden (without the ability to disable the animator since its called with an handler), or at least it would be useful to have a way to force the filter in a synchronous way so a dev could disable the animations, add items, force filter update and then enable them back

Anyway, Its just a thought, I found a few ways to do that already, library is really powerful, also, i always forget to thank you for this really awesome work, saves a lot of time, really really well done

**Comment by Rainer-Lang** [comment]
@frmz I think the same was like you. 

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mikepenz** [comment]
@frmz if you can think of a short solution to achieve this. I am always more than happy to see a pull request from people 😄 

thank you very much :). You are welcome.

**Comment by frmz** [comment]
Yeah sure, if we agree on the approach i can look into this

**Comment by frmz** [comment]
Issue is not solved, setNewList will call filter that will create a thread instead of just setting a filtered list, i will try to fork and fixed but current behavior is still the same as before

**Comment by mikepenz** [comment]
well then I suppose it just needs to be replaced with:

```
getItemFilter().publishResults(filter, getItemFilter().performFiltering(filter));
```

That would do everything synchron

**Comment by frmz** [comment]
yes you are right and that pointed me to a way to make it work with current release (and probably also with the one before), that is:

        mAdapter.clear();
        // Will set the constraint without creating a thread
        mAdapter.getItemFilter().performFiltering("asd");
        // Will set the items with filtering sync
        mAdapter.getItemFilter().add(items);

**Comment by mikepenz** [comment]
;)
