### ISSUE TITLE
Footer Loading view problem

### ISSUE THREAD

**Issue by noam2** [mikepenz/FastAdapter#433]
I've been struggling with a problem for over 2 weeks now, and couldn't manage to find a solution in the Github Project or Anywhere else.
Everything worked for me so far, except one thing

i have a loading animation of my own , just like the one that @mikepenz provided to me a while ago - 'ProgressItem'. When i add it to my footer adapter in gets stuck on  the first frame (Total 15) ,
and the frames won't change. The animation completely works in different scenarios, but not on the adapter. i'm using an AnimationDrawable , and calling start method in onBindView, but still isn't starting the animation

**Comment by mikepenz** [comment]
How do you add the `ProgressItem`? 
How do you start the animation, please provide some more code

**Comment by noam2** [comment]
here is my progress item class

`public class ProgressLoadingBunnyBlue extends AbstractItem<ProgressLoadingBunnyBlue, ProgressLoadingBunnyBlue.ViewHolder> {

    private AnimationDrawable animationDrawable;

    @Override
    public int getType() {
        return R.id.loading_bunny_blue;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.bunny_loading_view;
    }

    @Override
    public void bindView(ProgressLoadingBunnyBlue.ViewHolder viewHolderItem, List<Object> payloads) {
        super.bindView(viewHolderItem, payloads);

        viewHolderItem.loadingBunnyImg.setBackgroundResource(R.drawable.bunny_loading_blue_animation);
        // Get the background, which has been compiled to an AnimationDrawable object.

        AnimationDrawable animationDrawable = (AnimationDrawable) viewHolderItem.loadingBunnyImg.getBackground();
        animationDrawable.start();
    }

    @Override
    public void unbindView(ProgressLoadingBunnyBlue.ViewHolder holder) {

    }

    @Override
    public ProgressLoadingBunnyBlue.ViewHolder getViewHolder(View v) {
        return new ProgressLoadingBunnyBlue.ViewHolder(v);
    }

    protected static class ViewHolder extends RecyclerView.ViewHolder {

        ImageView loadingBunnyImg;

        public ViewHolder(View view) {
            super(view);
            loadingBunnyImg = (ImageView) view.findViewById(R.id.loadingBunnyImg);

        }
    }
}
`

and here's how i add it to footer adapter  :

    // initialize adapters for RecyclerView
        fastItemAdapter = new FastItemAdapter<>();
        footerAdapter = new FooterAdapter<>();

        recyclerView.setLayoutManager(new GridLayoutManager(getActivity(), 1));
        recyclerView.setItemAnimator(new DefaultItemAnimator());

        recyclerView.setAdapter(footerAdapter.wrap(fastItemAdapter));

        footerAdapter.add(new ProgressLoadingBunnyBlue().withEnabled(false));

**Comment by mikepenz** [comment]
@noam2 I think `AnimatedDrawable`s are quite expensive, and using it in the RV when `bindView` may be called many times it could slow down things. if you do not use an `AnimatedDrawable you do not have any problems at all right?

you might also stop the animation when the item is unbound.

**Comment by noam2** [comment]
i tried stopping the animation in unBound. 
The problem is that frame gets stuck, how would you suggest doing this without AnimationDrawable ? i'm trying to run an animation here of 15 frames

**Comment by mikepenz** [comment]
it's not really related to this library. That's a general `AnimatedDrawable` displaying. Have you looked on StackOverflow or so if anyone else has problems with displaying an animation like this in the RV? 

How does the animation look like? 15 different images? perhaps the single frames are too huge

**Comment by noam2** [comment]
no They are not and sometimes it works fine in the rv. Its not related al all to the animation itself cause i use it in many other non- recyclerView places in my app, plus each frame is about 100x200, times 15

**Comment by mikepenz** [comment]
@noam2 well sorry I can't really help with that. The RecyclerView itself is displaying the element, the FastAdapter is only the adapter providing the calls to bind the data. not more. 

Closing this now as it is something the adapter can't change or handle. 

The FastAdapter provides all the methods a normal RecyclerView.Adapter would provide so of the core logic it's the same. 

Sorry that we were not able to solve your issue. 

I guess it is a good idea to check if other people had similar issues with such an animation in a RecyclerView. 

(The RV is base android, nothing is handled here from the adapter)
