### ISSUE TITLE
Action mode activation using "icon" click

### ISSUE THREAD

**Issue by gpulido** [mikepenz/FastAdapter#434]
Hello,
I would like to reproduce the selection fucntionally that is shown in Gmail:

- The action mode is activated If the user either clicks on the icon of a mail either longclick on the item.
- When an item is selected in action mode, the icon changes.

I have managed to handle the activation of the actionmode using the longclick, but I don't know how to achieve the rest:
1) I've added a withItemEvent and an eventhook to the "imageview" on the itemholder, but once I receive the click I don't know how to just activate the action mode and select the item.
2) I haven't found the way to "change" the image icon when the item it is selected on actionmode.

I have reviewed the documentation, the examples and the issues with no luck :(
Any help would be apreciated.

Thank you!!

**Comment by mikepenz** [comment]
@gpulido isn't the `MultiSelect Sample` more or less what you need? Long click starts the CAB and then you can select. 

The only thing you have to add is the fact that also a single click on the "icon" starts the selection. 
Basically you would just select your item and then call that: https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/ActionModeHelper.java#L142

**Comment by gpulido** [comment]
@mikepenz I have reviewed the multiselect example, but I still don't understand which method I need to call to start the "cab" mode. It is probably my fault, but what should I write in the onclick?
```Java
 fastAdapter.withItemEvent(new ClickEventHook() {
            @Nullable
            @Override
            public View onBind(@NonNull RecyclerView.ViewHolder viewHolder) {
                if (viewHolder instanceof ContenderItem.ViewHolder)
                    return ((ContenderItem.ViewHolder)viewHolder).avatar;
                return null;
            }


            @Override
            public void onClick(View v, int position, FastAdapter fastAdapter, IItem item) {
               ///????

            }
        });
```

Also, I want to change the icon of the selected cab objects alongside with the item background. The item background is changed as the actionmodehelpr sets the "item" as selected state so the statedrawable knows that it has to use the selected part. But for the icon that is a imageview as a child of the itemview I don't know how to get the right instance to do the same.

**Comment by mikepenz** [comment]
@gpulido well the helper is in theory designed to automatically handle it in the longClick. So as mentioned in my previous message. You have to select that item in the onClick. and afterwards you call that method I linked you to. 

If I'm not wrong the selection listener is called so you should be able to notify the adapter about the changed element there. Pass a payload so you know that you just have to change the icon

**Comment by gpulido** [comment]
@mikepenz 
Ok 1 of 2 done:
```Java
  @Override
            public void onClick(View v, int position, FastAdapter fastAdapter, IItem item) {
                fastAdapter.select(position);
                actionModeHelper.checkActionMode((AppCompatActivity)getActivity());
            }
```
Now about the listener, probably is a very silly question but the selectionchangedlistener provides me to the item instance, but how I can access the viewholder to change the views?
```Java
 fastAdapter.withSelectionListener(new ISelectionListener<ContenderItem>() {
            @Override
            public void onSelectionChanged(ContenderItem item, boolean selected) {
              //I need to access a ImageVIew inside the ViewHolder for the item
            }
        });
```

**Comment by mikepenz** [comment]
@gpulido you never access the view directly in a RV. You never do that :D

You will adjust the item, (if needed) and then you call the notifyAdapterItemSetChanged (hopefully I did not write the name wrong) with a payload which is then calling the bindView with that payload. So you can react at that place

**Comment by gpulido** [comment]
@mikepenz You are absolute right. I knew that the question was silly, sorry for that.
I just added a check on the bindholder of the IItem:
```Java
  @Override
    public void bindView(ViewHolder holder, List payloads) {
        super.bindView(holder, payloads);
        holder.bindModel(getModel());
        holder.avatar.setActivated(isSelected());
    }
```
and just to finish the whole example:
```Java
 fastAdapter.withItemEvent(new ClickEventHook() {
            @Nullable
            @Override
            public View onBind(@NonNull RecyclerView.ViewHolder viewHolder) {
                if (viewHolder instanceof ContenderItem.ViewHolder)
                    return ((ContenderItem.ViewHolder)viewHolder).avatar;
                return null;
            }

            @Override
            public void onClick(View v, int position, FastAdapter fastAdapter, IItem item) {
                if (item.isSelected())
                    fastAdapter.deselect(position);
                else
                    fastAdapter.select(position);
                actionModeHelper.checkActionMode((AppCompatActivity)getActivity());
            }
        });
        fastAdapter.withSelectionListener(new ISelectionListener<ContenderItem>() {
            @Override
            public void onSelectionChanged(ContenderItem item, boolean selected) {

               fastAdapter.notifyAdapterItemChanged(fastAdapter.getPosition(item));
            }
        });
```
Again, thank you for the help and the library!

**Comment by mikepenz** [comment]
Glad you made it work :). 

As mentioned. Have a look on notifying + a payload as you can just update the specific view :)
