### ISSUE TITLE
Filter after empty string

### ISSUE THREAD

**Issue by gromiloff** [mikepenz/FastAdapter#435]
Hi,

I'm try to create search in list with next additional functionality:
1. filtering list by input symbols
2. mark the input symbols (bols text) in filtered items

so all works fine, but in case when I input one letter and remove it, callback for filter(Item item, CharSequence constraint) not called, becase adapter only reset filtred list.

So, how I can detect what input sctring was cleared ?

**Comment by mikepenz** [comment]
@gromiloff that's true there is currently no callback for the clear:
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L509

You might react at the point where you pass in the constraint on your side. At least for now. It would definitely make sense to have an additional callback for the reset/clear event.

**Comment by mikepenz** [comment]
This will be provided in the upcoming release. v2.6.0
https://github.com/mikepenz/FastAdapter/commit/7314d50e53ba19df54a1dc576b0f0e628ee02000

**Comment by mikepenz** [comment]
You can test this using the preview release of `v2.6.0-SNAPSHOT`

**Comment by gromiloff** [comment]
Thanks a lot!

**Comment by mikepenz** [comment]
You are welcome :)
