### ISSUE TITLE
Handling of dynamic Item type

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#437]
I have an item and does support different item types. I change a value in an item and call `mFastItemAdapter.notifyAdapterItemChanged(pos);` and then the app crashes because the new item type is not mapped yet.

I solve that by using `mFastItemAdapter.remapMappedTypes(); mFastItemAdapter.notifyAdapterItemChanged(pos);` after updating the item. This means, I have to always think about it.

I think it would be nice to extend the adapter to support such a thing, maybe via a function like `mFastAdapter.withSupportChangingItemType(boolean)` which only does following: whenever an item is updated, the adapter has to make sure that this item is mapped (as it does when adding items). So I only have to think about this once when creating an adapter.

Any thoughts on that?

**Comment by mikepenz** [comment]
@MFlisar no this will not be supported as this is a really bad implementation and should not be done. 

There should always be 1 item -> mapping to exactly 1 identifier. And this should never be changed dynamically

**Comment by MFlisar** [comment]
So if you allow the user to theme your app (think about a launcher and a folder item) and the user can select between a few layouts and all layouts offer mainly the same thing (1 to n images, a label, a background, ...) and the data allows to simply call `data.changeLayout(...)` how would you handle that?

Creating different items is imho too much extra work and updating the data of an item means I MUST replace the item with a new item - just because my data underneath an item has changed.

In this case what would be the *good* implementation in your opinion?

**Comment by MFlisar** [comment]
You really think this is better than supporting changing ids for items - for one reason only, changing the underlying layout for theming:

    // updating items => we change the display type of a folder item
	BaseFolderItem item = mFastItemAdapter.getAdapterItem(pos);
    item.getFolder().setType(newType);
    BaseFolderItem newItem = null;
	switch (newType)
	{
		case Simple:
			newItem = new SimpleFolderItem(item.getFolder());
			break;
	   case Grid:
			newItem = new GridFolderItem(item.getFolder());
			break;
	   case Stack:
			newItem = new StackFolderItem(item.getFolder());
			break;
	   case Grid:
			newItem = new GridFolderItem(item.getFolder());
			break;
	   case Action:
			newItem = new ActionFolderItem(item.getFolder());
			break;
	   // and so on, I offer quite a few possible layouts
    }
	 mFastItemAdapter.remove(pos);
	 mFastItemAdapter.add(pos, newItem);

Instead of simply doing following:

    BaseFolderItem item = mFastItemAdapter.getAdapterItem(pos);
    mFastItemAdapter.getAdapterItem(pos).setType(newType);
	mFastItemAdapter.remapMappedTypes(); // could be replaced by offering a function to map a single type like mFastItemAdapter.mapType(item);
	mFastItemAdapter.notifyAdapterItemChanged(pos);

**Comment by FabianTerhorst** [comment]
You could use the generic item to reduce some boilerplate of the first code snippet you posted.

**Comment by MFlisar** [comment]
Thanks, I'll check that. Using the generic adapter, will I be able to update an item or will I still need to remove + readd a model? This has the drawback of add/remove animations instead of an update animation...

**Comment by FabianTerhorst** [comment]
The generic item adapter needs to create the different item object.
