### ISSUE TITLE
Setting title on FastAdapterBottomSheetDialog will/does not work.

### ISSUE THREAD

**Issue by ankitbatra11** [mikepenz/FastAdapter#438]
Why do we have title setters in FastAdapterBottomSheetDialog class when the functionality will not work? Below code is taken from android source code:

```
public BottomSheetDialog(@NonNull Context context, @StyleRes int theme) {
        super(context, getThemeResId(context, theme));
        // We hide the title bar for any style configuration. Otherwise, there will be a gap
        // above the bottom sheet when it is expanded.
        supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
    }
```

If we want to set title on a bottom sheet dialog, we may need to include a text view (for the title) in the custom view.

**Comment by FabianTerhorst** [comment]
Feel free to open a pr that removes the setTitle methods inside the FastAdapterBottomSheetDialog. The code of the FastAdapterBottomSheetDialog used the FastAdapterDialog as an base.

**Comment by mikepenz** [comment]
Please open a PR.
