### ISSUE TITLE
can i have Endless RecyclerView and StickyHeader at same time. 

### ISSUE THREAD

**Issue by surindersinghbindra** [mikepenz/FastAdapter#445]
I want to add a StickyHeader and Pagination to RecylerView(Endless Recylerview) in one Recylerview. Is there any way to come out of this problem with the help of FastAdapter.
Attached the Design for which i need this. Please suggest .
![endless](https://cloud.githubusercontent.com/assets/12382618/26823814/9fa990c6-4acc-11e7-8e5a-c19ef4571de3.PNG)

**Comment by mikepenz** [comment]
@surindersinghbindra I don't see a point why this shouldn't be possible. Have you tried it already?

**Comment by surindersinghbindra** [comment]
like  this        **recyclerView.setAdapter(stickyHeaderAdapter.wrap(itemAdapter.wrap(headerAdapter.wrap(footerAdapter.wrap(fastItemAdapter)))));**
 is my wrapping in right order?

**Comment by mikepenz** [comment]
You should either use a `FastItemAdapter` or a `FastAdapter` and an `ItemAdapter`. you can't have a  `FastItemAdapter` + another `ItemAdapter` at the same time. 

as for the order. yes. the `StickyHeaderAdapter` is the outside one. The sample shows this:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/StickyHeaderSampleActivity.java#L65

(The Sticky header is an external library, and just included in the sample to show compatiblity)

**Comment by surindersinghbindra** [comment]
Thanks Mike

**Comment by monishkamble** [comment]
@surindersinghbindra Could you help me out with the approach you used to achieve it.

**Comment by surindersinghbindra** [comment]
@monishkamble should I show you a gist?

**Comment by surindersinghbindra** [comment]
I will send you in morning

**Comment by judemanutd** [comment]
Thanks much appreciated.

**Comment by surindersinghbindra** [comment]
https://github.com/surindersinghbindra/SoSimpli/blob/master/app/src/main/java/com/think360/sosimply/ui/fragments/AvailabilityFragment.java
