### ISSUE TITLE
EndlessRecyclerOnScrollListener hide progress bar

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#446]
Hi.
when using EndlessRecyclerOnScrollListener, how would i hide the progress bar that appears in the bottom of the list?
in my app i am posting a paginated request to my server, and everything seems to be working fine except for the last page. if there is no more data (i.e. the data contains 5 pages and the user requests page 6), the server returns "404-not found". i have noticed that in this case the progress bar at the end of the list continues to be visible. how can i hide it? i assume it has to do with the ProgressItem but i can't figure it out...

here is my code:

```
mrvScrollListener = new EndlessRecyclerOnScrollListener(mFooterAdapter)
		{
			@Override
			public void onLoadMore(final int currentPage)
			{
				mCurrentPage++;

				mRecyclerView.post(new Runnable()
				{
					@Override
					public void run()
					{
						mFooterAdapter.clear();
						mFooterAdapter.add(new ProgressItem().withEnabled(false));

                                                //make server call 
                                        }
				});
			}
		};
```
if the response from the server is valid, then i do `mAdapter.add(mAdapter.getAdapterItemCount(), serverResponse.body());`.

if there is no more data (response is "404-not found") i simply show a toast

**Comment by mikepenz** [comment]
@or-dvir I made the experience that using `post` on a view in some cases does not call the runnable. Please use a handler for example which run's on the `UIThread` or `runOnUIThread` of the `Activity`

**Comment by or-dvir** [comment]
@mikepenz if i dont use `post` i get an exception saying something about the recyclerview not being in the correct state (will post the exception when ill be in front of the code)... can you please post a snippet of how you mean im supposed to use the handler?

**Comment by mikepenz** [comment]
@or-dvir that's why you should have either using the `runOnUi` thing of the activity or a handler which is posting to the activity. 

something like that. and you can reuse that handler for other cases too
```java
Handler mainHandler;

    public Handler getMainHandler() {
        if(mainHandler == null) {
            mainHandler = new Handler(Looper.getMainLooper());
        }
        return mainHandler;
    }

```

**Comment by or-dvir** [comment]
@mikepenz  this does not work. progress bar remains visible.

```
mrvScrollListener = new EndlessRecyclerOnScrollListener(mFooterAdapter)
		{
			@Override
			public void onLoadMore(final int currentPage)
			{
				mCurrentPage++;

				runOnUiThread(new Runnable()
				{
					@Override
					public void run()
					{
						mFooterAdapter.clear();
						mFooterAdapter.add(new ProgressItem().withEnabled(false));

                                                //make server call 
                                        }
				});
			}
		};
```

**Comment by mikepenz** [comment]
oh by the way. you are adding a progressbar in the code sample :D only now that I realized that. 

wouldn't you want to just clear?

**Comment by or-dvir** [comment]
is that what `mFooterAdapter.clear` does? i just copy-pasted from the sample

**Comment by mikepenz** [comment]
`mFooterAdapter.clear` removes the element
but the line below you directly add it again with `mFooterAdapter.add(new ProgressItem().withEnabled(false));`

**Comment by or-dvir** [comment]
yep. all i needed was to call `clear()`!
i wasn't thinking too much...
thanks :)
