### ISSUE TITLE
recyclerview inside nestedscrollview with EndlessRecyclerScroll is buggy

### ISSUE THREAD

**Issue by baadillahnabil** [mikepenz/FastAdapter#447]
my recyclerview is inside nestedscrollview, i want to add endless scroll in the recyclerview with data from realm database. i tried with the example in this repo but my case is little bit weird.

this is what happen : 
1. i run the code below inside onViewCreated fragment
2. the weird things is i just don't do anything (not touching my phone) and the fragment is not even scroll down but the list is updating (this is not supposed to happen until i scroll to very bottom of the list)
3. another weird things is it's only load more once (i want endless or until my data is showing all) even i scroll to very bottom the loading indicator is not showing up (like the 'endless' is stop) 

i managed to solved issue number 3 , but issue number 2 is keep repeating it self until my recyclerview is have very long long list

this is my code :

```
long itemsCount = realm.where(RiwayatKendali.class).count();
final RealmResults<RiwayatKendali> resultsFilter = realm.where(RiwayatKendali.class)
        .between("id", itemsCount - LIMIT_HISTORY + 1, itemsCount)
        .findAllSorted("id", Sort.DESCENDING);

fastItemAdapter.withSelectable(false);
fastItemAdapter.withPositionBasedStateManagement(true);
fastItemAdapter.setNewList(resultsFilter);

rvRiwayatKendali.setLayoutManager(new LinearLayoutManager(getContext()));
rvRiwayatKendali.setItemAnimator(new DefaultItemAnimator());
rvRiwayatKendali.setNestedScrollingEnabled(true);
rvRiwayatKendali.setAdapter(footerAdapter.wrap(fastItemAdapter));

rvRiwayatKendali.addOnScrollListener(new EndlessRecyclerOnScrollListener() {
    @Override
    public void onLoadMore(int currentPage) {
        footerAdapter.clear();
        footerAdapter.add(new ProgressItem().withEnabled(false));

        new Handler().postDelayed(() -> {
            footerAdapter.clear();
            final RealmResults<RiwayatKendali> resultsFilterMore = realm.where(RiwayatKendali.class)
                    .between("id", itemsCount - LIMIT_HISTORY + 1, itemsCount)
                    .findAllSorted("id", Sort.DESCENDING);
            fastItemAdapter.add(fastItemAdapter.getAdapterItemCount(), resultsFilterMore);
        }, 2000);

    }
});

```

please help :)

**Comment by mikepenz** [comment]
@baadillahnabil what's the height of the `RecyclerView` inside the `NestedScrollView`?

**Comment by baadillahnabil** [comment]
`wrap_content`

this is my layout code : 
`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
       xmlns:android="http://schemas.android.com/apk/res/android"
       xmlns:app="http://schemas.android.com/apk/res-auto"
       xmlns:tools="http://schemas.android.com/tools"
       android:id="@+id/parentLayout"
       android:layout_width="match_parent"
       android:layout_height="match_parent"
       >

    <com.github.nitrico.stickyscrollview.StickyScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

        <android.support.constraint.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:descendantFocusability="blocksDescendants"
            android:focusableInTouchMode="true"
            >

            <android.support.v7.widget.AppCompatTextView
                android:id="@+id/textView3"
                fontPath="fonts/Raleway-Bold.ttf"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:background="@drawable/left_border"
                android:text="@string/status"
                android:textSize="18sp"
                app:layout_constraintHorizontal_bias="0.0"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                tools:ignore="MissingPrefix"
                />

            <android.support.v7.widget.AppCompatTextView
                android:id="@+id/statusKendali"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginEnd="16dp"
                android:layout_marginStart="32dp"
                android:layout_marginTop="16dp"
                android:text="@string/status_kendali_on"
                android:textSize="15sp"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/textView3"
                />

            <android.support.v7.widget.AppCompatTextView
                android:id="@+id/textView7"
                fontPath="fonts/Raleway-Bold.ttf"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="24dp"
                android:background="@drawable/left_border"
                android:text="@string/kendali"
                android:textSize="18sp"
                app:layout_constraintHorizontal_bias="0.0"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/statusKendali"
                tools:ignore="MissingPrefix"
                />

            <de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/btnSwitchKendali"
                android:layout_width="150dp"
                android:layout_height="150dp"
                android:layout_marginLeft="8dp"
                android:layout_marginRight="8dp"
                android:layout_marginTop="8dp"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/textView7"
                />

            <android.support.v7.widget.AppCompatTextView
                android:id="@+id/textView8"
                fontPath="fonts/Raleway-Bold.ttf"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                android:background="@drawable/left_border"
                android:tag="sticky"
                android:text="@string/riwayat_kendali"
                android:textSize="18sp"
                app:layout_constraintHorizontal_bias="0.0"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/btnSwitchKendali"
                tools:ignore="MissingPrefix"
                />

            <android.support.v7.widget.AppCompatTextView
                android:id="@+id/txtNoRiwayatKendali"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginBottom="8dp"
                android:layout_marginLeft="8dp"
                android:layout_marginRight="8dp"
                android:layout_marginTop="8dp"
                android:text="@string/no_riwayat_kendali"
                android:textAlignment="center"
                android:textColor="#64000000"
                android:textSize="20sp"
                android:visibility="invisible"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintHorizontal_bias="0.0"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toTopOf="@+id/rvRiwayatKendali"
                />

            <android.support.v7.widget.RecyclerView
                android:id="@+id/rvRiwayatKendali"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="0dp"
                android:descendantFocusability="blocksDescendants"
                android:focusableInTouchMode="true"
                app:layout_behavior="@string/appbar_scrolling_view_behavior"
                app:layout_constraintHorizontal_bias="1.0"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/textView8"
                />

        </android.support.constraint.ConstraintLayout>

    </com.github.nitrico.stickyscrollview.StickyScrollView>

</android.support.design.widget.CoordinatorLayout>`

**Comment by mikepenz** [comment]
@baadillahnabil have you already debugged into it, because I assume that due to the nature of that setup (RV inside a ScrollView, and no defined height) causes that problem. 

And if that's the case it's not the FastAdapter's fault, as the FastAdapter library itself is just the adapter. 

Can you please provide a sample application which showcases the issue, perhaps this helps a bit better to investigate the issue

**Comment by CyberpunkPsychonaut** [comment]
I just ran into issue number 2, where the recycler continuously reloads itself even without scrolling. This only happened inside a nestedscrollview, the behavior stopped when I changed it to a regular ScrollView. My recyclerView's height is just match_parent, how should we be defining its height?

**Comment by nirwannursabda** [comment]
Yes its reload again and again even when im not scrolling it down
Im using recycler view inside nested scroll view
Can we hack fast adapter to prevent this endless scroll without scrolling? :)
my setup

`
<?xml version="1.0" encoding="utf-8"?>
<layout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    >
    <data>
        <import type="android.view.View"/>
    </data>

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/refresh_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@android:color/white"
            >

            <EditText
                android:id="@+id/inputSearch"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="@string/find_customer"
                android:inputType="text"
                android:drawableLeft="@android:drawable/ic_menu_search"
                android:drawableStart="@android:drawable/ic_menu_search"
                android:padding="16dp"
                android:drawablePadding="10dp"
                android:layout_alignParentTop="true"
                android:focusable="true"
                android:focusableInTouchMode="true"
                android:imeOptions="actionSearch"
                />

            <android.support.v4.widget.NestedScrollView
                android:id="@+id/container"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_below="@+id/inputSearch"
                >
                <RelativeLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:background="@android:color/white"
                    >

                    <android.support.v7.widget.RecyclerView
                        android:id="@+id/list_history"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:background="@android:color/white"
                        />

                    <ScrollView
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:fillViewport="true"
                        android:id="@+id/empty"
                        android:visibility="gone"
                        >

                        <RelativeLayout
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:padding="10dp">

                            <LinearLayout
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:layout_centerVertical="true"
                                android:id="@+id/mainLayout"
                                android:orientation="vertical">

                                <TextView
                                    android:layout_width="match_parent"
                                    android:layout_height="match_parent"
                                    android:text="@string/no_data"
                                    android:textColor="@color/common_text_color"
                                    android:textSize="14sp"
                                    android:gravity="center"
                                    />

                            </LinearLayout>
                        </RelativeLayout>

                    </ScrollView>

                </RelativeLayout>
            </android.support.v4.widget.NestedScrollView>
        </RelativeLayout>
    </android.support.v4.widget.SwipeRefreshLayout>
</layout>
`

**Comment by naseemali925** [comment]
Has anyone got any solution for this? @dcalano @nirwannursabda @baadillahnabil

**Comment by Morteza-Rastgoo** [comment]
Is there a solution to this?

**Comment by Ankit0080** [comment]
has anyone found solutions to this problem ? then share please.

**Comment by fukemy** [comment]
no solution, finding other lib
