### ISSUE TITLE
Child Items Not Collapsing

### ISSUE THREAD

**Issue by CodyEngel** [mikepenz/FastAdapter#448]
My team is using this library for handling collapsing and expanding items in a list but we noticed that the child items from the last parent item in a list will not collapse. Example:

- Parent Item One
  - Child Item One
  - Child Item Two
    - Baby Item One
    - Baby Item Two
    - Baby Item Three

If I were expand "Child Item Two" to reveal the baby items and then collapse "Parent Item One" then "Child Item Two" will collapse however the Baby Items will not collapse, they remain open. This is only a problem if position based state management is set to false, however if it's set to true we lose the ability to manage the state of the child items when they collapse.

I was able to do a work around for this by extending from FastAdapter and copying the code from the collapse method (and other internal methods that it relies on) and updating the the first for loop within the else block to add one to the index. So essentially it looks something like this:

    //first we find out how many items were added in total
    //also counting subitems
    int totalAddedItems = expandable.getSubItems().size();
    for (int i = position + 1; i < position + totalAddedItems + 1; i++) { // +1 so we get the last item in the list
       Item tmp = getItem(i);
       if (tmp instanceof IExpandable) {
           IExpandable tmpExpandable = ((IExpandable) tmp);
           if (tmpExpandable.getSubItems() != null && tmpExpandable.isExpanded()) {
               totalAddedItems = totalAddedItems + tmpExpandable.getSubItems().size();
           }
       }
    }

If you'd like I can take a look at the internals of the collapse method a little more closely sometime this week and see if I can resolve this bug in perhaps a less messy way than the above code snippet I'm using currently.

**Comment by mikepenz** [comment]
@CodyEngel thank you very much for the report. 

Thanks for the very detailed report. I'll also have a look into this sometimes this or next week. 
Something possibly interesting. The positionBasedStateManagement will be removed in v3, and there will only be the newer approach. (This allows me to remove code base related to the old original approach) 

I am a little bit surprised that the issue only happens for the new approach. 

I'll report back if I found something.

**Comment by CodyEngel** [comment]
@mikepenz, thank you! Let me know if I can help out at all.

**Comment by mikepenz** [comment]
@CodyEngel the `+1` fixed it :D 

I have released v1.6.2 with that fix :) thanks you very much
