### ISSUE TITLE
[Question] getType & getLayoutRes difference

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#449]
From what I understand, getType should return a unique id for every layout, but isn't the layoutRes itself already unique? Is there ever a situation in which two items have different layouts but the same type, or vice versa? And if not, can we simply use our layout res for both functions rather than defining another one for id?

The only thing I can think of is if two different items will bind data to the same layout res in different ways.

**Comment by FabianTerhorst** [comment]
There is a possibility that you can reuse an layout for multiple items.

**Comment by mikepenz** [comment]
@AllanWang well the layoutRes might be unique, but there is a possibility that you may re-use it. in addition it's no "identifier". 
You can use it, and it will be fine for most cases, but I just wanted to make it clear that there is a difference.

**Comment by AllanWang** [comment]
I see. Thanks
