### ISSUE TITLE
Wrong description of SimpleItemList Sample in navigation drawer from sample project

### ISSUE THREAD

**Issue by hendrawd** [mikepenz/FastAdapter#450]
<img src="https://user-images.githubusercontent.com/9481791/26880977-4c79f590-4bc0-11e7-81f8-00f215de83af.jpg" alt="screen shot" width="300px"/>
It stated has FastScroller functionality, but actually it is not anymore. So to make sure there is no confusion among people who test the functionality of this library, it is better to either remove the FastScroller description or re-implement it to the adapter.

**Comment by mikepenz** [comment]
Thanks. this will be solved in a future release of the app
