### ISSUE TITLE
StickyHeaders for GridLayoutManager

### ISSUE THREAD

**Issue by hendrawd** [mikepenz/FastAdapter#452]
How to categorize StickyHeaders for GridLayoutManager? So the header will be match parent and content span count will be 3

Result:
<img src="https://user-images.githubusercontent.com/9481791/26925677-e61cef54-4c74-11e7-9fd1-88ea20466c8e.png" width="300px"/>

Expected:
<img src="https://user-images.githubusercontent.com/9481791/26925762-323a465c-4c75-11e7-9568-80fa12045205.png" width="300px"/>

And is it possible to combine sticky header and fast scroller with this library?

**Comment by mikepenz** [comment]
@hendrawd as noted the `StickyHeadeR` is a external library. I do not think they have support currently for grids.

**Comment by mikepenz** [comment]
And yes it is possible to combine the two

**Comment by hendrawd** [comment]
Yes actually https://github.com/timehop/sticky-headers-recyclerview/pull/106 has fix for gridview, i am trying it now

**Comment by mikepenz** [comment]
Ok great :)

**Comment by ClarkXP** [comment]
@hendrawd I'm having the same issue, what was your workaround for this?

**Comment by hendrawd** [comment]
@ClarkXP To be honest my attempt to fix that failed, and I changed to https://github.com/FutureMind/recycler-fast-scroll and implement https://github.com/FutureMind/recycler-fast-scroll/blob/master/fastscroll/src/main/java/com/futuremind/recyclerviewfastscroll/SectionTitleProvider.java , but the library is not active(last update 2 years ago), you might want to consider that.

**Comment by ClarkXP** [comment]
@hendrawd I did successfully implement stickyheader with fastadapter, My workaround was fill the grid with empty items after section's end.
