### ISSUE TITLE
endless scroll - onLoadMore() only called first time when no more data is available

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#453]
Hello again.
sorry for the probably confusing title... hopefully i explain it well enough in this post.

i am trying to implement endless scroll and `onLoadMore` is not called anymore after i have reached the end of the list (as in no more data is available).

in my app i receive paginated results from a server, and when there is no more data the server returns "404-not found". when this happens i want to show a toast to the user saying "no more data".
the endless scroll seems to be working fine and when i do get that "404" from the server **for the first time**, the toast indeed shows. however, if i now go to the top of the list and back down to the end of the list, `onLoadMore` is **not** called anymore and therefore the toast only shows the first time.
i would like to show the toast **every time** the user scrolls to the end of the list (or in other words, i would like `onLoadMore`  to be called every time i reach the end of the list, even if the previous call did not yield any results.
i assume there is some "trigger" that determines whether `onLoadMore` will be called or not and it is turned off when no more results are available. this is because if, for example, i have 5 pages, it is successfully called for pages 1,2,3,4,5 and 6 (which does not return any result and displays the toast). but now if i go to the top of the list and back to the end, i would expect `onLoadMore` to be called again and i would try to get page 6 again, fail, and show the toast.

am i correct about the existence of this "trigger"? if so, how can i reset it? how can i make `onLoadMore` be called **again**, even if the last call did not have a result?

**Comment by mikepenz** [comment]
@or-dvir the loadmorelistener basically checks when a specific threshold is reached if there is the need to call the listener, this happens for example if new items were added, if there are no new item's added this condition will never fire again, as the set did not change, --> there won't be new items. 

The check is here: 
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnScrollListener.java#L117

The existing `EndlessRecyclerOnScrollListener` can not achieve what you need, and you will have to adjust it for your needs.

**Comment by or-dvir** [comment]
@mikepenz thank you for your quick answer! i guess i have 2 options:
1) add an item and immidietly remove it (will that work?)
2) implement a custom view and add it to the footerAdapter when the end of the list is reached.

**Comment by mikepenz** [comment]
@or-dvir well I don't think one of those 2 options are the best, I think you could just extend the listener and add a method which is called in case the items didn't change

**Comment by or-dvir** [comment]
ill give it some thought... moving on to other aspects of the project for now :)

**Comment by mikepenz** [comment]
@or-dvir ok great. You can come back to this topic later. As far as I can tell it's no general issue of the `FastAdapter`, but more or less an implementation detail for your usecase
