### ISSUE TITLE
Filter with sticky adapter

### ISSUE THREAD

**Issue by noam2** [mikepenz/FastAdapter#454]
i'm using A FastAdapter with ItemAdapter and  StickyAdapter. Everything wotrks good and i have the sticky headers.
when i try to filter it doesnt work good. there isn't a method to filter a FastAdapter or stickyAdapter, but only to filter An Item Adapter. I did that but items are not getting filtered in my item Adapter.
Much appereciation

**Comment by noam2** [comment]
called filter on itemAdapter and it works Fine

**Comment by mikepenz** [comment]
@noam2 well the `filter` only always works on a `ItemAdapter` the `StickyAdapter` is an external library basically, and the `FastAdapter` is managing the `adapter`s defined (so all adapters implementing the `IAdapter` interface)
