### ISSUE TITLE
setItems notification of changes

### ISSUE THREAD

**Issue by gpulido** [mikepenz/FastAdapter#455]
I've realized that the setItems of the adapters is just replacing the already items list without doing any notification (added-removed-updated).
Maybe a DiffUtils (https://developer.android.com/reference/android/support/v7/util/DiffUtil.html) could be used to just know what changed and allow the adapter to launch visual animations.

This is needed when using HeaderHelper for example, as the only way to rearrange the data is by using the setitems that would redraw the entire adapter.

**Comment by mikepenz** [comment]
@gpulido you can use the `DiffUtil` but it depends on your item, and is something the FastAdapter shouldn't depend on. You can try the DiffUtilHelper or how I called that class from the extensions. 

The `set` does by the way notifications, but only on section basis and not on per item basis. 
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L257
