### ISSUE TITLE
filtering issues

### ISSUE THREAD

**Issue by Abdurrahmanjun** [mikepenz/FastAdapter#456]
Goodday mike, im just using this bulletproof lib and really excited with features that you make. i wonder how to use search item with some condition, for example if the query that user type is not match with all **sortname** then look to they **fullname** if it give another zero list then look to they **motherName**. it probably a list of object User which User have some properties (string sortname, string fullname, string mothername). i notice in https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SimpleItemListActivity.java#L79 filter procedure just depend on one property (item.name) any idea how to implement that usecase with this procedure? did i missed something? 

Thanks..

**Comment by mikepenz** [comment]
@Abdurrahmanjun well the `Filter` class I depend on (which is from Android) provides only one method, which allows you to pass in a `CharSequence` 

For your case, you can either use the provided one, or you just use your own one. Basically it does not matter. 

If you want to use the provided one, simply pass in all your values seperated with a delimiter and split it apart. 

So you could pass in `sortname;fullname;mothername` and filter all of them.

**Comment by Abdurrahmanjun** [comment]
```
searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
                @Override
                public boolean onQueryTextSubmit(String s) {
                    fastItemAdapter.filter("mStringShortname:s;mStringFullname:s;mStringMothername:s");
                    return true;
                }
                @Override
                public boolean onQueryTextChange(String s) {
                    fastItemAdapter.filter("mStringShortname:s;mStringFullname:s;mStringMothername:s");
                    return true;
                }
            });
```
where the filter procedure,

**Comment by Abdurrahmanjun** [comment]
Thanks for the response mike! okay am i doing it wrong? i try to still using the provided one
```
searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
                @Override
                public boolean onQueryTextSubmit(String s) {
                    fastItemAdapter.filter("mStringShortname:s;mStringFullname:s;mStringMothername:s");
                    return true;
                }
                @Override
                public boolean onQueryTextChange(String s) {
                    fastItemAdapter.filter("mStringShortname:s;mStringFullname:s;mStringMothername:s");
                    return true;
                }
            });
```
where the filter procedure still, 
```
fastItemAdapter.withFilterPredicate(new IItemAdapter.Predicate<AirportItem>() {
            @Override
            public boolean filter(AirportItem item, CharSequence constraint) {
                return !item.mStringShortname.toLowerCase().contains(constraint.toString().toLowerCase());
            }
        });
```
but it still not working.

**Comment by mikepenz** [comment]
@Abdurrahmanjun you have to split apart the string again, and apply it. It was just a proposed solution so you can pass in multiple fields :D 

You are anyways writing the filter code, so if you know how the `constraint` which is passed in, is structured your can also split it apart again, and do whatever you have to do to properly filter.

**Comment by Abdurrahmanjun** [comment]
haha ok then atleast i should findout how to using that CharSequence, thanks mike :D
