### ISSUE TITLE
Quick clarification between dettach/attach and bind/unbind

### ISSUE THREAD

**Issue by ncapdevi** [mikepenz/FastAdapter#458]
I wast just hoping I could get some quick clarification and possible elaboration of the difference between detachFromWindow/attachToWindow and bindView/unbindView.  Specifically, the lifecycle order of the two as well as their overall functional difference of when they're called?  Thanks!

**Comment by mikepenz** [comment]
@ncapdevi basically the `FastAdapter` makes the methods normally called from the `RecyclerView.Adapter` accessible in the item. 

I suggest you directly check out the lifecycle of the `RecyclerView.Adapter`

**Comment by ncapdevi** [comment]
Ah, didn't realize this was a method directly from the adapter.  Fully explained here, sorry for the bother!
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#onViewDetachedFromWindow(VH)

**Comment by mikepenz** [comment]
- bindViewHolder (bindView)
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#bindViewHolder(VH, int)
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#onBindViewHolder(VH, int, java.util.List<java.lang.Object>)

- onViewRecycled (unbindView)
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#onViewRecycled(VH)

...
