### ISSUE TITLE
deselect without calling onSelection

### ISSUE THREAD

**Issue by noam2** [mikepenz/FastAdapter#459]
Hey
i've got selecatble enabled  on my items. is there a way to enable selection/deselection without calling the onSelection method ? sometimes this is needed , when a condition happens. fastadapter.withSelectble doesn't help in this case

**Comment by mikepenz** [comment]
@noam2 not 100% sure about the case. but the `FastAdapter` has all methods like `select()`, `deselect()`, ... and those have to be used, just changing the selection on the item itself won't work properly
