### ISSUE TITLE
Qestion about different adapters

### ISSUE THREAD

**Issue by AlexTip** [mikepenz/FastAdapter#461]
Hi, I have recycler with 3 types of items
1. Header in HeaderAdapter<item>
2. Item type 1 in OwnAdapterType1<ItemType1>
3. Native admob in AbstractWrapAdapter

I create own adapter "OwnAdapterType1" witch extends ItemAdapter and ovverides onBindViewHolder methods.

I'm setting adapter like this `recycler.setAdapter(adAdapter.wrap(ownAdapterType1.wrap(headerAdapter.wrap(fastAdapter))));`
When recycler is binding header item onBindViewHolder is called for OwnAdapterType1. 
Is it okay?

When I changed adapter setup like this
`recycler.setAdapter(adAdapter.wrap(headerAdapter.wrap(ownAdapterType1.wrap(fastAdapter))));`
I'm not getting any binds for OwnAdapterType1

I don't understand how does wrap work and which class should be extended by my adapter (with additional logics)

**Comment by AllanWang** [comment]
You'll have different adapters for different view types. The adapters for all the view types except for the last one will be HeaderAdapters, and the last one will be a ItemAdapter.

When you wrap it, wrap it in the order that they will appear (so the ItemAdapter will be last).

What happens is that you should be able to add items to each of those adapters the way you normally would, but in the end all the items are added in the last ItemAdapter.

(This is from my understanding; I'm trying this as well)

**Comment by mikepenz** [comment]
@AlexTip without taking to much time first regarding the other questions. 

WHY do you need to do this: `I create own adapter "OwnAdapterType1" witch extends ItemAdapter and ovverides onBindViewHolder methods`

**Comment by AlexTip** [comment]
@mikepenz Thanks for your answer.

`WHY do you need to do this: I create own adapter "OwnAdapterType1" witch extends ItemAdapter and ovverides onBindViewHolder methods`
I have aditional logics in this adapter, each item is getting address by lat&lng, and after I'we got address I want to update item.

And by the way what is the common logics of adapters wrapping sequence?

**Comment by mikepenz** [comment]
@AlexTip but you should not do this by overwriting the `onBindViewHolder` method. That is definitely the wrong approach. 

If you want to update an item at a later time, you should change the object, (set the values) and notify the `FastAdapter` that the items were changed. 

Well `WrapAdapter`s have to be the outer ones, so this one. (basically that's not really `FastAdapter` specific, as the `WrapAdapter` were just added to simplify, but yeah :D)

and then for the normal `ItemAdapter`'s here the `wrapping does not matter, as the `order` value which is defined within the `ItemAdapter` and `HeadeAdapter` anyways defines their order ;)

**Comment by AlexTip** [comment]
So there is no designed way to append any logics while item binding?

**Comment by mikepenz** [comment]
@AlexTip I am just saying that the proper approach is to handle the `bindView` inside the item, and if data changes you notify the adapter. 

You can do what you did, but it seems just not the best approach

**Comment by AlexTip** [comment]
@mikepenz Thank you, and the last thing, is there a common way to access adapter from item or should I implement some kind of listeners?

**Comment by mikepenz** [comment]
@AlexTip the `FastAdapter` is set on the `itemView` as tag: 
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L605
