### ISSUE TITLE
Wrapped HeaderAdapter not showing added item

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#462]
I have a chained list of header adapters that wrap each other up until a generic FastItemAdapter (like in the readme). However, if I add an item in the first header, it doesn't show in the UI. The logs show that the header does contain one item, but the next item's first global position is still 0, implying that nothing is before it.

The relevant code for setting up the adapter is as follows:
```kotlin
chain.map { it.second }.forEachReversedWithIndex { i, headerAdapter ->
            if (i == chain.size - 1) headerAdapter.wrap(baseAdapter)
            else headerAdapter.wrap(chain[i + 1].second)
            if (i < chain.size - 1) KL.e("${chain[i].first} ${chain[i + 1].first}")
        }
        recycler = recyclerView
        indexStack.push(0)
        with(recyclerView) {
            layoutManager = LinearLayoutManager(context)
            adapter = chain.first().second
            ...
```

This is in kotlin, and chain.map{ it.second } is the ordered list of headeradapters.
The full code is [here].

Adding items to the last headeradapter works, and I"ve tried adding items to the first headeradapter both before and after adding to the last one. I've also tried `notifyDataSetChanged` and `withUseIdDistributor` (seen from another issue), but they don't make a difference.

Update 1: The two headers were updated quite close to each other so there was no change. If I add a delay of 2 seconds before adding to the first header, the number of items correctly appears, but they are duplicates of the items in the next header adapter rather than the items I want. The two adapters have different iitem ids and layouts

Update 2: Adding items just to the first header and not the second header will not show anything. Adding items to the second header and the base fastitemadapter displays everything. So perhaps I am not implementing things properly by wrapping a headeradapter in a headeradapter.

Update 3: The issue was that the header adapter orders were all 100. My current workaround is to extend it so I can modify it later; maybe this could be added to the library or maybe there is a better way

```kotlin
class SectionAdapter<Item : IItem<*, *>>(var sectionOrder: Int = 100) : HeaderAdapter<Item>() {
    override fun getOrder(): Int = sectionOrder
}
```

**Comment by mikepenz** [comment]
@AllanWang the problem is that the `Order` of all the `HeaderAdapter`'s is the same, which results in just one `HeaderAdapter` being `known` by the `FastAdapter` .

Extend the `HeaderAdapter` and make the `Order` configurable, something like this:

```java
public class CustomItemAdapter<Item extends IItem> extends ItemAdapter<Item> {

    public CustomItemAdapter(int order) {
        this.order = order;
    }

    private int order;

    public CustomItemAdapter<Item> Order(int order) {
        this.order = order;
        return this;
    }

    @Override
    public int getOrder() {
        return order;
    }
}
``` 

I am sorry that this is not mentioned in the README. It will be solved in v3, as I'll eliminate the `order` definition
