### ISSUE TITLE
EndlessScrollListener scroll up

### ISSUE THREAD

**Issue by noam2** [mikepenz/FastAdapter#464]
hey, 
is there a way in any of the utilities provided, or library itself to have an EndlessScrollListener when scrolling up like in a chat messaging page ? i'm aware of the EndlessRecyclerOnScrollListener, but this is only for scrolling down.

**Comment by AllanWang** [comment]
The source is [here](https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnScrollListener.java) so it should be pretty easy to change it for scrolling up.  Have a go at it

**Comment by AllanWang** [comment]
Nevermind, it seems like this will be implemented in v3 of FastAdapter.  The source is [here](https://github.com/mikepenz/FastAdapter/blob/cb882d92add6e683bb38f22071ee333dbfaa7ebc/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnTopScrollListener.java)

and the branch reference is [here](https://github.com/mikepenz/FastAdapter/pull/443)

**Comment by noam2** [comment]
@AllanWang - Thank u so much you are the man

**Comment by mikepenz** [comment]
@AllanWang thanks for answering
