### ISSUE TITLE
On click event not call when item has gridview inside

### ISSUE THREAD

**Issue by ssppgit** [mikepenz/FastAdapter#465]
Hi!

I'm having problems with on item click from adapter. My item has a GridView and when i click over this in the screen, the gridview click event is called instead of Recycler Item. Is possible to only call the recycler item and prevent the gridview item click?

my layout is this one:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:paddingTop="12dp"
    android:paddingBottom="12dp"
    android:paddingLeft="16dp"
    android:paddingRight="16dp"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="?android:attr/selectableItemBackground">

    <TextView
        android:id="@+id/asq"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:background="@drawable/background_bber"
        android:gravity="center"
        android:textSize="@dimen/text_body_1_regular"
        tools:text="12"
        tools:textColor="@color/white" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:layout_marginLeft="16dp">

        <TextView
            android:id="@+id/name_fs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:textColor="@color/color_text"
            android:textSize="@dimen/text_subhead_regular"
            android:maxLines="1"
            android:ellipsize="end"
            tools:text="Texto principal"/>

        <GridView
            android:id="@+id/gv_grid"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:columnWidth="32dp"
            android:scrollbars="none"
            android:horizontalSpacing="4dp"
            android:verticalSpacing="4dp"
            android:numColumns="auto_fit"/>

    </LinearLayout>

</LinearLayout>

my gridview item is a simple textview:

```
<TextView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
```
    android:id="@+id/line_number"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    tools:text="12"
    tools:textColor="@color/white"
    android:gravity="center"
    android:maxLines="1"
    android:ellipsize="end"
    android:minWidth="36dp"
    android:padding="2dp"
    android:textSize="@dimen/text_caption_regular"
    android:textStyle="bold"
    android:background="@drawable/background_line">

</TextView>

Thanks!

**Comment by mikepenz** [comment]
make the gridview not clickable, remove the click listeners

**Comment by ssppgit** [comment]
Hi @mikepenz thanks for your answer.

I've tried to set my gridview not clickable with android:clickable="false" but it doesn't work. I remove click listener for GridView but the adapter item not get the click when i click in the gridview

**Comment by mikepenz** [comment]
@ssppgit well sadly the item itself has not much control about the views inside, if it catches the click the item can't do anything. 

in the worst case you can just pass on the click to the parent, within the item, or manually moving on the click. :/ or attaching a 
EventHook as (a click listener on a specific view)

**Comment by ssppgit** [comment]
Thanks @mikepenz !

At the end i got the solution. I've override dispatchTouchEvent in a custom gridview and return always false. Adapter item get item click now.

Thanks a lot for your time and your great library :)

**Comment by mikepenz** [comment]
Thank you very much :)
Great to hear that it's solved
