### ISSUE TITLE
multiple types of items: using "wrap" vs shared object model

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#467]
hi
i need to have a list combined of different types of items where each item has its own layout and event hooks and so on (for example one item contains an editText, another contains a Spinner, and another contains an imageView).

whats the best way to do this? should i have a separate adapter for each type of item and use "wrap" on all of them, or have all of these items extend a "BaseItem" and just use a single adapter with "BaseItem" as its' type?
in the sample app i see that you use "wrap" for things like headers, but in the expandable sample you use a single adapter with IItem as a shared type.

at the moment i am using the "BaseItem" method and it seems to be working, but im not sure if this is the best (or "right") way to do this.

can you please clarify under which circumstances i would use each method?

thanks

**Comment by mikepenz** [comment]
@or-dvir well there is no clear use this, or use the other definition. If you can handle and order all items within one adapter, go this route. If you need to specifically handle them in different adapters, use multiple. 

In any case. You can always use the FastAdapter without a specific `type` by just using it as `FastAdapter` and not `FastAdapter<Type>`

**Comment by mikepenz** [comment]
Basically the biggest advantage of having type specific `ItemAdapter`s is, that you will have type safety for this specific `ItemAdapter` this is not true for the `FastAdapter` though as it needs to have the parent type defined. In the worst case this is simply `IItem` so you'd have `FastAdapter<IItem>`. 

Your approach is definitely correct and working. And as long as you do not need to have any diversion of the item (and you can handle this on your own) then it is totally fine.

**Comment by or-dvir** [comment]
@mikepenz ok thanks a lot.
so what is "wrap" for? when will it be better to use that instead? why when it comes to headers you use wrap and not a "BaseItem"?
