### ISSUE TITLE
withItemEvent is deprecated

### ISSUE THREAD

**Issue by veeranath** [mikepenz/FastAdapter#468]
Hi Sir,

 I am getting the withItemEvent listerner as the deprecated when click the button i am not getting any response please help sir I had updated to this version and also find the Screenshot

**compile('com.mikepenz:fastadapter:2.6.2@aar') {
        transitive = true
    }
    compile 'com.mikepenz:fastadapter-commons:2.6.0@aar'
    compile 'com.mikepenz:fastadapter-extensions:2.6.0@aar'**

![screenshot_1](https://user-images.githubusercontent.com/15996564/27778275-34349e24-5fd7-11e7-8d70-18b59e81c0b0.png)

**Comment by FabianTerhorst** [comment]
Hi,

```withItemEvent``` got deprecated in favor of ```withEventHook```. Any breaking changes between versions are documented in the migration notes. https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md

**Comment by mikepenz** [comment]
@FabianTerhorst thanks for answering
