### ISSUE TITLE
Filtering on 2.6.2 is not working. 

### ISSUE THREAD

**Issue by jelther** [mikepenz/FastAdapter#469]
Mike,

I guess the filtering is broken in this new version (2.6.2). Setting my adapter to mAdapter.filter("") doesn't bring my list back. I've managed to revert the filtering if the library version was 2.5.1.

You can see my code here in this gist : https://gist.github.com/jelther/9c0bf03c34a47110c6484cfc2750ed5e

There are some comments because it looks you've changed the way to access the filtering methods.

I'll check my code again but I've rolledback to a previous version and my code worked.

@mikepenz , posting here 'cause I've previous posted in your other project.

**Comment by jelther** [comment]
@mikepenz , there has been an exception right here, in ItemFilter.java, line 87.

`if (mItemFilterListener != null) {
                mItemFilterListener.onReset();
            }`

Inside my OnReset implementation, I'm cleaning a simple TextView. Doing that is making the code break.

**Comment by mikepenz** [comment]
@jelther which exception. sounds like it's an issue on your side, and not on `FastAdapter` side.

**Comment by jelther** [comment]
@mikepenz , I've done a review and my code looked cleaned.
Decided to clean all cache from Android Studio 2.3 and rebuild Gradle, things got working again.

Maybe an issue with my computer, Idk. I'll keep an eye on it to see if it happens again and I'll report you!

Thanks!

**Comment by mikepenz** [comment]
Very interesting. Thanks for letting me know. 

Regards,

**Comment by jelther** [comment]
@mikepenz , I got the "error" now:

I'm trying to update a View (a simple TextView) inside onReset at ItemFilterListener and the error is the folowing:

> android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

Does this method runs in a separated thread? What's it purpose?

**Comment by mikepenz** [comment]
Yes it runs in a seperate thread. That's how Android has implement the
ItemFitler class.
The reason for this is that filtering is with a high chance a long running
task. so it should not block the UI

Mike Penz
__________________________________________
*Mike Penz*
Android | Backend | Open Source | Web Developer
mikepenz.com
lanora.eu

**Comment by jelther** [comment]
@mikepenz , okay.

I'll try to find other approach to manage the UI. Do you have any tip?

**Comment by mikepenz** [comment]
post it on a handler which has the UI thread
oruse runOnUiThread from the activity

Mike Penz
__________________________________________
*Mike Penz*
Android | Backend | Open Source | Web Developer
mikepenz.com
lanora.eu
