### ISSUE TITLE
Wrapped FastAdapter without animation changes

### ISSUE THREAD

**Issue by sosite** [mikepenz/FastAdapter#470]
When I use `FastAdapter` without wrapping them in another one then Recycler animation changes works fine.
```java
FastItemAdapter fastAdapter = new FastItemAdapter();
recyclerView.setAdapter(fastAdapter);

item1 = new ListItem(new Item(1));
item2 = new ListItem(new Item(2));

list1 = Arrays.asList(item1, item2);
list2 = Arrays.asList(item2, item1);

// on click button 1
fastAdapter.set(list1);

// on click button 2
fastAdapter.set(list2);
```

But when I wrap `FastAdapter` to any other `AbstractAdapter` then animation changes doesn't work:
```java
FastItemAdapter fastAdapter = new FastItemAdapter();
HeaderAdapter<ListItem> headerAdapter = new HeaderAdapter<>();
headerAdapter.wrap(fastAdapter);
recyclerView.setAdapter(headerAdapter);
...
```
Did I miss something?

Overriding `getIdentifier()` in `ListItem extends AbstractItem` doesn't work too.

**Comment by sosite** [comment]
May be simillar to https://github.com/mikepenz/FastAdapter/issues/298

**Comment by mikepenz** [comment]
@sosite which animation would you use?

**Comment by sosite** [comment]
Default recycler animations (like position changes)

6 lip 2017 15:38 "Mike Penz" <notifications@github.com> napisał(a):

**Comment by mikepenz** [comment]
Hmm that's really weird. 

If you try the `AdvancedSampleActivity` you will see that animations are stilll working in it:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/AdvancedSampleActivity.java

**Comment by mikepenz** [comment]
Any updates Did you check the sample? 

Please report back. closing for now
