### ISSUE TITLE
Use the master branch for the Github Page

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#474]
Why not move the _config file to master and use the master Readme for the github page? There are some formatting errors in index.md in gh-pages, and with upcoming changes, the documentation there might not apply.

There is a [gem "jekyll-readme-index"](https://github.com/benbalter/jekyll-readme-index) option if the md name is an issue.

**Comment by FabianTerhorst** [comment]
Normally the github pages shouldnt be exactly the same as the readme, that would make it obsolet. Instead it should better describe the project and contain more organized content thats not possible with an readme.

**Comment by mikepenz** [comment]
Well I basically always used the auto site generator for the gh-pages. I did not really invest any time at all in this as there is the main github page already available anyways :)
