### ISSUE TITLE
Single object, multiple viewholders

### ISSUE THREAD

**Issue by Shakezulla57** [mikepenz/FastAdapter#477]
I'm retrofitting a current implementation to use fastadapter for the added benefits. I have one object that depending on the value of a property should use a certain viewholder. I have this currently working without using fastadapter by overriding `getItemViewType` and then returning the correct viewholder from `onCreateViewholder`, but what you end up with is a giant ugly mess of an `if/else` in your `onBindViewHolder`.

I'd like to have several objects that extend the main object to encapsulate their own viewholder functionality. What's the most fastadapter idiomatic way of doing this? I looked at the GenericItems example, but I feel that might be overkill for this situation. Any help in pointing me onto the right path would be appreciated.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeGenericItemActivity.java#L58

**Comment by mikepenz** [comment]
The sent link is exactly what you need. 

1 Model class. 
Many Item classes .

**Comment by Shakezulla57** [comment]
@mikepenz Thanks, that got me on the right track.
