### ISSUE TITLE
Dependency causing Layout Preview Error in Android Studio

### ISSUE THREAD

**Issue by andreluizreis** [mikepenz/FastAdapter#478]
When I add the dependency: 
```
compile('com.mikepenz:fastadapter:2.6.2@aar') {
    transitive = true
}
```
My Android Studio 2.3.3 stops showing the layout preview for all files. 
![screen shot 2017-07-14 at 4 25 49 pm](https://user-images.githubusercontent.com/8194164/28229603-5f4ce16a-68b1-11e7-8c5f-df9e08732a30.png)

My dependencies: 
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile group: 'org.apache.httpcomponents', name: 'httpclient-android', version: '4.3.5.1'
    compile('org.apache.httpcomponents:httpmime:4.3') {
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
    }
    compile('com.mikepenz:fastadapter:2.6.2@aar') {
        transitive = true
    }
    compile 'com.mikepenz:fastadapter-commons:2.6.0@aar'
    compile 'com.mikepenz:fastadapter-extensions:2.6.0@aar'
    compile 'com.mikepenz:materialize:1.0.2@aar'
    testCompile 'junit:junit:' + rootProject.junitVersion;
    testCompile 'org.mockito:mockito-core:' + rootProject.mockitoVersion;
    compile 'com.android.support:appcompat-v7:25.4.0'
    compile 'com.android.support:design:25.4.0'
    compile 'com.android.support:support-v4:25.4.0'
    compile 'com.android.support:support-vector-drawable:25.4.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.segment.analytics.android:analytics:4.2.6'
    compile 'com.getsentry.raven:raven-android:8.0.3'
    compile 'com.google.dagger:dagger:2.9'
    compile 'com.jakewharton:butterknife:8.6.0'
    compile 'com.readystatesoftware.systembartint:systembartint:1.0.3'
    compile 'com.mobsandgeeks:android-saripaar:2.0.3'
    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:converter-gson:2.3.0'
    compile 'com.auth0.android:jwtdecode:1.1.1'
    compile 'com.cloudinary:cloudinary-android:1.13.0'
    compile 'io.michaelrocks:libphonenumber-android:8.4.1'
    compile('com.marshalchen.ultimaterecyclerview:library:0.7.2') {
        exclude group: 'com.android.support'
    }
    annotationProcessor 'com.google.dagger:dagger-compiler:2.9'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.6.0'
}

**Comment by FabianTerhorst** [comment]
Which android studio version are you using?

**Comment by andreluizreis** [comment]
Android Studio 2.3.3

**Comment by carvaldo** [comment]
The same applies to dependency
`compile('com.mikepenz:materialdrawer:5.9.4@aar') { 
        transitive = true 
    } `

**Comment by Schinizer** [comment]
Support library `25.4.0` causes `ConstraintLayout` to fail rendering. I'm using `25.3.1` to render the preview

**Comment by mikepenz** [comment]
Seems to work for me. 

Android Studio 3.0.0 Canary 8
Support libs 26.x
Build Tools 26
Target 26
Compile 26
...

**Comment by zaihuishou** [comment]
@mikepenz  Me too
