### ISSUE TITLE
[Question] Modifying view on select

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#479]
What is the best practice to modify an iitem view when it is selected/deselected?

The checkbox example makes use of the click event to animate the checkbox automatically.

My current method is to have an onClickListener, and to change the view based on if the item is selected. This is on the basis that the selection toggle happens before it, but it also means that I don't get activities for items that are deselected without user input.

For my implementation, I have a grid of images, and selecting an item will blur it. Deselecting it will unblur it. Another thing I've noticed is that selecting an item will automatically unblur another. This might be because there is a selection limit, and that the other item is redrawn.

**Comment by AllanWang** [comment]
The solution works fine now with multi select available. However if there are better options that the onClickListener I'd like to hear it.

**Comment by mikepenz** [comment]
@AllanWang well you can also enable that the `FastAdapter` updates automatically and calls `onBind` again

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L249

But your solution is as good
