### ISSUE TITLE
sample for multi model with own ItemView in single list

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#48]
can you give an example to show multi model with own ItemView in single recylcerview ?
in your sample app, you have one model with 2 itemView

thanks

**Comment by Rainer-Lang** [comment]
Simply make 2 models with views for each. Put them both in the ItemAdapter.
It's really easy - just try it. :) :+1:

**Comment by DJafari** [comment]
tested it, but only one item 
sample :

```java
this.list = (RecyclerView) findViewById(R.id.list);
        this.list.setLayoutManager(new LinearLayoutManager(this));
        this.list.setItemAnimator(new DefaultItemAnimator());
        this.list.setHasFixedSize(true);

        this.fastAdapter = new FastAdapter();
        GenericItemAdapter<Text, GenericText> itemAdapter = new GenericItemAdapter<>(GenericText.class, Text.class);
        GenericItemAdapter<Pic, GenericPic> itemAdapter2 = new GenericItemAdapter<>(GenericPic.class, Pic.class);
        this.list.setAdapter(itemAdapter2.wrap(itemAdapter.wrap(fastAdapter)));

        itemAdapter.addModel(new Text("Test 1"));
        itemAdapter2.addModel(new Pic("Test 1"));
```

**Comment by Rainer-Lang** [comment]
You only have to use one adapter.

**Comment by mikepenz** [comment]
@DJafari there is a sample showcasing multiple models, for different items. Head over here:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeGenericItemActivity.java

**Comment by mikepenz** [comment]
@Rainer-Lang thanks for answering

**Comment by DJafari** [comment]
@Rainer-Lang  tnx for your reply, but if you can, give an example to me

@mikepenz in your example you have one model (`IconModel`) with 2 different ItemView ( `GenericIconItem` and `RightGenericIconItem` )

i have 2 model ( `Text` and `Pic` ) with own's ItemView ( `TextViewItem` and `PicViewItem` )

**Comment by Rainer-Lang** [comment]
Something like that:

```
this.fastAdapter = new FastAdapter();

GenericItemAdapter itemAdapter mItemAdapter = 
new GenericItemAdapter(o -> {
	//depending on your logic you can now decide which model maps to which item.
	if (o instanceof Pic) {
		return new GenericPic((Pic) o);
	} else if (o instanceof Text) {
		return new GenericText((Text) o);
	} else {
		throw new IllegalArgumentException("The passed model can't be created within this Factory");
	}
});

this.list.setAdapter(itemAdapter.wrap(fastAdapter));

itemAdapter.addModel(new Text("TEXT"));
itemAdapter.addModel(new Pic("PIC"));
```

**Comment by DJafari** [comment]
@Rainer-Lang realy tnx !
and last question, why android studio highlight this section of code ? where is problem ?
![screen shot 2016-02-19 at 23 23 03](https://cloud.githubusercontent.com/assets/1963047/13187355/dbe26248-d75f-11e5-92bd-e2b8967c9dad.png)

**Comment by FabianTerhorst** [comment]
@DJafari you have to define a generic type to the adapter. Your adapter items has to extend this type. For example GenericItemAdapter<IItem> itemAdapter = 
new GenericItemAdapter<IItem>...

**Comment by Rainer-Lang** [comment]
@DJafari It's ok - it works.

**Comment by DJafari** [comment]
@FabianTerhorst thanks for your reply,
but i have multiple type of model, and i can't define a model type to `GenericItemAdapter`

**Comment by DJafari** [comment]
@Rainer-Lang yes it works, but how can remove it ?

**Comment by Rainer-Lang** [comment]
no way - you "wanted" this ;-)

**Comment by FabianTerhorst** [comment]
@DJafari your models has to extend from the same object, like the adapter items.

**Comment by Rainer-Lang** [comment]
But this is "normally" not possible... Like in my situation.

**Comment by DJafari** [comment]
@Rainer-Lang ok tanks :-)

@FabianTerhorst my models yes, already extends from object, but my `GenericItems` is different :

`public class GenericText extends GenericAbstractItem<Text, GenericText, GenericText.ViewHolder>`
`public class GenericPic extends GenericAbstractItem<Pic, GenericPic, GenericPic.ViewHolder>`

**Comment by FabianTerhorst** [comment]
@DJafari ok, when your GenericItems cant extend from the same object you just have to ignore the warning.@SuppressWarnings("unchecked")

**Comment by DJafari** [comment]
@FabianTerhorst exactly must be ignored this warning .

thanks for your reply

**Comment by Rainer-Lang** [comment]
@FabianTerhorst @DJafari Please have a look at https://github.com/mikepenz/FastAdapter/issues/41
