### ISSUE TITLE
[V3][V3][V3] TEST, API, SUGGESTIONS

### ISSUE THREAD

**Issue by mikepenz** [mikepenz/FastAdapter#483]
We are currently in the progress of finalising the API changes and a huge refactor for the `FastAdapter`. 

As it is really important for us to make the library as easy to use, but also as powerful and flexible as possible, we want to hear your feedback. 

You can follow the current progress here: 
https://github.com/mikepenz/FastAdapter/pull/443
and also use the SNAPSHOT to include it into your app, and test it out. Currently the only documentation for V3 is the commit changelog + the sample application. 

Please check it out, and give us suggestions, review the changes, and contribute and help to make v3 the best release ever.

Please keep general discussion here, and do code reviews on the PR. 

-----------------

## OVERVIEW
- Adapter `wrapping`  was removed
  - `FastAdapter.with()`  is the new way to go
- `HeaderAdapter`, `FooterAdapter` were removed, just use multiple `ItemAdapter`s instead
- Extension support
  - Selection (currently still in the core lib) and Expandable's are no longer a core functionality, but instead use the Extension interface, to add their functionality to the library
- `GenericItemAdapter`'s will be removed and replaced in favour of the new `ModelAdapter`
- The `ItemAdapter` is now based on the `ModelAdapter` (this sadly required a second generic type to be defined)
- ...

**Comment by mikepenz** [comment]
@Rainer-Lang, @tehfonsi

**Comment by sosite** [comment]
In my project I created something that join adding items with adding adapters. I can also in one place add my initial items (where normal `beforeAdapter.add(...)` doesn't work until `FastAdapter.with()`.

So my final usage version looks like this:
```java
@Override
public void prepareCustomStructure(StructurePopulator populator) {
    populator.addItem(new DummyModel("header 1"));
    populator.addItem(new DummyItem2(new DummyModel("header 2")));
    beforeAdapter = populator.addItemAdapter();
    populator.addBaseItemAdapter();
    afterAdapter = populator.addAdapter(new ItemAdapter<>(), new DummyModel("after 1"), new DummyItem2(new DummyModel("after 2"))));
    populator.addItem(new DummyItem1(new DummyModel("footer")));
}

@Override
protected void prepareConverters(ConvertersPopulator populator) {
    populator.add(DummyModel.class, DummyItem1::new);
}
```
Maybe some kind of this addition will be nice in your lib?

**Comment by mikepenz** [comment]
@sosite it did not work in previous versions because `ItemAdapter`'s had a fixed order --> a second itemAdapter is ignored as the order was already taken. This is no longer the case with v3.

I am not yet sure why you need multiple adapters in your case?

**Comment by sosite** [comment]
I also simplify usage of `AbstractItem` for the simplest form as I found. I also prefer to bound views directly in `ViewHolder`:

```java
class DummyModel implements Identifiable {
    private final long someId;

    DummyModel(long someId) {
        this.someId = someId;
    }

    public String getStringValue() {
        return String.valueOf(someId);
    }

    @Override
    public long getId() {
        return someId;
    }
}
```
```java
class DummyItem extends ListItem<DummyModel> {
    public DummyItem(DummyModel dummyModel) {
        super(dummyModel);
    }

    @Override
    public ItemHolder<DummyModel> getViewHolder(View view) {
        return new ViewHolder(view);
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_dummy;
    }

    class ViewHolder extends ItemHolder<DummyModel> {
        public ViewHolder(View itemView) {
            super(itemView);
        }

        @Override
        protected void bindView(DummyModel dummyModel) {
            ((TextView) getView()).setText(dummyModel.getStringValue());
        }
    }
}
```

**Comment by sosite** [comment]
@mikepenz In my activity I have many nested lists so if I want to all items works perfectly fine and will be easy to maintenance I prefer then create few adapters for them:

![image](https://user-images.githubusercontent.com/2025949/28312518-ba8b7988-6bb3-11e7-898d-b62cda2e3051.png)

**Comment by mikepenz** [comment]
@sosite do those "header" (divider,... whatever you want to call those section headers :D) allow collapsing? 

Because if not there is a small helper class which would combine items into groups and add a header in front of them:
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/HeaderHelper.java

**Comment by sosite** [comment]
@mikepenz `HeaderHelper` looks nice and it's almost what I need but I love to simplify this kind of stuff - so In place of custom management of additional type of class I just created `HeaderAdapter` 😉

btw - you can simplify this expression in `HeaderHelper` from:
```java
if (headerItem != null) {
    items.add(i + 1, headerItem);
    i = i + 1;
    size = size + 1;
}
```
to:
```java
if (headerItem != null) {
    items.add(++i, headerItem);
    size++; // or ++size; or size += 1;
}

**Comment by mikepenz** [comment]
yeah I know that I could simplify it like that. :D I always prefer the "longer" style to keep it easy for devs who are not used to this notation :P

Management of additional type of class? 
the `HeaderHelper` keeps everything flat within one `ItemAdapter` and just adds a header before the items

**Comment by sosite** [comment]
_Management of additional type of class_ - I mean some Juniors in our team prefer to learn as small type of classes as possible. So I think that it's better to use `HeaderAdapter` (which do the same) but you can forget  then about `HeaderHelper` which is some kind of _wrapper_ and save it to simple `IItemAdapter` field.

**Comment by mikepenz** [comment]
@sosite ah ok I understand. ;). 

I am currently thinking of providing the "clever" `ViewHolder` like you do too. But I'd like this without really breaking current APIs

**Comment by sosite** [comment]
When I forgot and return `null` in place of `RecyclerView.ViewHolder` in `AbstractItem.getViewHolder(View)` then I received this error message:
```
java.lang.NullPointerException: Attempt to read from field 'android.view.View android.support.v7.widget.RecyclerView$ViewHolder.itemView' on a null object reference
    at com.mikepenz.fastadapter.FastAdapter.onCreateViewHolder(FastAdapter.java:620)
```

It will be better if we can received there more unambiguous message like
> You forget to return specific ViewHolder in class.getSimpleName()

**Comment by mikepenz** [comment]
@sosite v3 is `NonNull` by default. So lint will inform you that this is wrong

**Comment by sosite** [comment]
@mikepenz You are sure about that? [AbstractItem.java#L302](https://github.com/mikepenz/FastAdapter/blob/feature/v3_new/library-core/src/main/java/com/mikepenz/fastadapter/items/AbstractItem.java#L302)

**Comment by mikepenz** [comment]
yes: https://github.com/mikepenz/FastAdapter/blob/feature/v3_new/library-core/src/main/java/com/mikepenz/fastadapter/items/package-info.java

**Comment by mikepenz** [comment]
So perhaps a bit more info to the previous message. 
With v3 we use the jsr findbugs bundle to make everything nonNull by default: https://github.com/mikepenz/FastAdapter/pull/485/files

**Comment by sir-gawain** [comment]
Will it be possible to use Android Databinding with the FastAdapter items?
I tried it with the current 2.6.x branch but did not get it working, but i cannot remember, why exactly not.

**Comment by FabianTerhorst** [comment]
I don´t see a reason why it shouldn´t work.
```java
public class MyViewHolder extends RecyclerView.ViewHolder {
    private final ViewDataBinding binding;

    public MyViewHolder(ViewDataBinding binding) {
        super(binding.getRoot());
        this.binding = binding;
    }

    public void bind(Object obj) {
        binding.setVariable(BR.obj, obj);
        binding.executePendingBindings();
    }
}
```

**Comment by FabianTerhorst** [comment]
You just have to override getViewHolder(ViewGroup parent) and init the viewholder with the binding.
```java
LayoutInflater layoutInflater =
        LayoutInflater.from(parent.getContext());
    ItemBinding itemBinding = 
        ItemBinding.inflate(layoutInflater, parent, false);
    return new MyViewHolder(itemBinding);
```

**Comment by sir-gawain** [comment]
Thanks for your hint, i will try that. I remember i tried to override some method, but some parameters were missing. I followed some tutorial but cannot find it again :(

**Comment by Rainer-Lang** [comment]
@FabianTerhorst Will be the examples like EndlessScroll even updated to v3, eg with the new EndlessScrollHelper?

**Comment by FabianTerhorst** [comment]
First, the top and bottom scroll listener must be merged into one.

**Comment by FabianTerhorst** [comment]
the top scroll listener is just the bottom one with an small logic change.

**Comment by sagrawal2002** [comment]
my suggestion can't in this adapter we can add option to show data in slide (flip). so it will add more flexibility on this adapter. and can be used in news blog type apps also. right now this adapter has only top down scroll view to show data.

**Comment by FabianTerhorst** [comment]
The scroll direction and the scroll in general is not handled by the adapter. You have to use an layout manager for that.

**Comment by mikepenz** [comment]
@sagrawal2002 that's nothing related to the adapter. orientation etc is controlled by the `LayoutManager`

**Comment by sir-gawain** [comment]
I'm currently porting my app to v3_new and have some issues, where i'm not sure, if its my fault or not.
I have 2 ModelAdapters: AAdapter<A,AItem> and BAdapter<B,BItem>. I chain them together by FastAdapter.with(). Later i add some Headers with two HeaderHelpers. That works that far. Now i want to add swipe. AItem can be swiped left/right, BItem can only be swiped left. So i add a SimpleSwipeDragCallback with a ItemTouchHelper to the recyclerview. 
As first step, only AItem was swipeable and implemented ISwipeable, BItem did not. Nevertheless, BItem was swipeable, because SimpleSwipeCallback handles items as swipeable if they do not implement ISwipeable (getSwipeDirs()). Is that on purpose? It surprised me.
Now the directions: SimpleSwipeDragCallback has a method getSwipeDirs(RV, RV.ViewHolder), but the VH is never asked, which directions it allows to be swiped. It always returns the default directions. 
Is that on purpose? Unfortunately SimpleSwipeDragCallback also hardcodes the use of SimpleSwipeCallback so i cannot override this behaviour without overriding two classes...
What are your proposed solutions to these problems? Thx!

**Comment by mikepenz** [comment]
@sir-gawain you had similar issues with v2?

**Comment by mikepenz** [comment]
closing this as v3 will soon reach stable ;)

**Comment by sir-gawain** [comment]
I never got so far with 2.x branch, so i cannot say, if these issues were also in v2.

**Comment by AllanWang** [comment]
@mikepenz For the record, I don't think lint warns  you if getViewHolder returns null. Your annotation is for parameter values, and it didn't show for me for return values when I tried it.

I'm also getting the following error:

```java
java.lang.NullPointerException: Attempt to invoke interface method 'android.support.v7.widget.RecyclerView$ViewHolder com.mikepenz.fastadapter.IItem.getViewHolder(android.view.ViewGroup)' on a null object reference
                                         at com.mikepenz.fastadapter.listeners.OnCreateViewHolderListenerImpl.onPreCreateViewHolder
```
Which is similar to one mentioned above after updating `FastAdapter`. I will post any fix once I find the issue.

**Comment by FabianTerhorst** [comment]
Thats already fixed in #585.

**Comment by FabianTerhorst** [comment]
The package Info was missing in the adapter package.

**Comment by AllanWang** [comment]
@FabianTerhorst that doesn't seem to be merged yet. Is there a version to test it?

**Comment by FabianTerhorst** [comment]
But the ParametersAreNonnullByDefault wont give info about non nullable methods. Not sure if there is one for methods are non nullable by default.

**Comment by AllanWang** [comment]
Oh I thought you were referring to the onPreCreateViewHolder issue. I see the annotation in the PR

**Comment by AllanWang** [comment]
Given that that's a very widely used method, you may consider annotating the return type

**Comment by FabianTerhorst** [comment]
Adding an non null annotation on almost every method seems a bit to redundant for me.

**Comment by AllanWang** [comment]
I'm not advocating it for every method. Namely the abstract ones like `getViewHolder`, where the default code import will make it return null

**Comment by FabianTerhorst** [comment]
Doesnt sounds like an good solution.

**Comment by FabianTerhorst** [comment]
Ok seems like there was just one method in the entire project that is abstract and returns an object that is not nullable, so it should be fine to annotate it.
