### ISSUE TITLE
problem with collapsing in Expandable

### ISSUE THREAD

**Issue by noam2** [mikepenz/FastAdapter#490]
Hey, 
ive manage to set the expandable adapter, and it animates nicely when expanding, but it doesn't animate when collapsing on the way up.
Another issue - is there a way to scroll down while expanding an item ? the problem is the click is handled within the adapter, and scrolling a recycler view should be handled from Activity/fragment, but it's not possible to catch both events right ?

**Comment by mikepenz** [comment]
@noam2 you can still attach a normal `mOnClickListener` to the adapter and listen for the event when a user expanded (so clicked on the parent) item. And youc an then do whatever is necessary

**Comment by noam2** [comment]
ok thanks. and what about the collapsing issue ?

**Comment by mikepenz** [comment]
@noam2 well do you collapse using the correct thread? what and how do you do it? You can check the sample app, there it works (for example for the IconGrid sample)

**Comment by noam2** [comment]
i just used the same sample, defined slide down animator like you did. didn't understand what icongrid is

**Comment by mikepenz** [comment]
That's the activity visible int he Sample app: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/IconGridActivity.java

containing a collapse open / close animation

**Comment by noam2** [comment]
@mikepenz yeah did the same thing. tell me, how to add an expandable item ? couldn't use add or notifydatachange. when i add it just adds it alone without expanadablity

**Comment by mikepenz** [comment]
@noam2 you mean you want to notify if a sub item is added? 

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1817

**Comment by mikepenz** [comment]
Closing for now. Please report back
