### ISSUE TITLE
Error:This Gradle plugin requires Studio 3.0 minimum

### ISSUE THREAD

**Issue by henengel** [mikepenz/FastAdapter#493]
Hi there,
I'm trying to download your repository to inspect your sample code.
When trying to do so, I get an error from Android Studio:
"Error:This Gradle plugin requires Studio 3.0 minimum".
I tried checking for updates, and Android Studio says that I have the latest version: 2.3.3.
What am I supposed to do in order to get things working?
Thank you.

**Comment by mikepenz** [comment]
@henengel https://developer.android.com/studio/preview/index.html

If that'S no option for you, you can modify all the stuff localy to be compatible again with the old toolings. 

But the source itself is supposed to be only AS 3 compatible

**Comment by mikepenz** [comment]
1) well I use Android Studio 3.0 for all my development, and it only makes sense to use the same tooling for my libs too then. in addition it does not prevent people to use the built *.aar, so just include the maven dependency and you are fine, it does not matter which version you use 
2) well not really. you'll probably have to compare with older projects. or do it with knowledge. 
3) reading reading reading, trying trying trying, coffee :D, keep trying and keep going, keep learning. never stop. 

Android Studio 3 will be soon final and it has huge advantages like a improved build setup, better profilers, faster, support for all the new stuff from Android. See the Android sites for this please

**Comment by henengel** [comment]
@mikepenz Thank you for taking the time to help and advise.
Have a good one!

**Comment by mikepenz** [comment]
You are welcome ;)
