### ISSUE TITLE
global position vs relative position

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#494]
hi
i cant understand the difference between global position and relative position.

can you please clarify?

**Comment by mikepenz** [comment]
Let's say you have 3 adapters. 

1. adapters (10 items)
2. adapters (10 items)
3. adapters (10 items)

So if you then use the adapter 2 and get it's second item, you will say. adapter.get(1). In this case you will use the relative position. (Position relative to this adapters list) 

But If you use the FastAdapter it will give you possibility to access any item from any adapter. 

So if you say give me the item at position 5 (that's the global position) it will return the item with position 5 from adapter 1 (as adapter 1 has 10 items)
If you want the 15th (global position) item (you can do this as the fastadapter can access all 30 items) then it will give you the 5th (which would be the relative position seen for adapter 2) of adapter 2.

**Comment by or-dvir** [comment]
@mikepenz  thanks for your fast reply.
so this is only relevant in case i wrap adapters together right? as in `recyclerView.setAdapter(adapter1.wrap(adapter2.wrap(adapter3)));`
and in case i only have 1 adapter then global position and relative position are the same?

**Comment by mikepenz** [comment]
exactly :)
