### ISSUE TITLE
items turn invisible when trying to set selectable background

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#495]
hi
i want to add item selections, however when i add the following lines to my `onBind()`, all the items become invisible.

```
StateListDrawable stateListDrawable =
				FastAdapterUIUtils.getSelectableBackground(context, context.getResources().getColor(R.color.primary), true);

UIUtils.setBackground(viewHolder.itemView, stateListDrawable);
```

i dont know if that matters but my item is a cardview.

**Comment by mikepenz** [comment]
@or-dvir that's very interesting. Can you reproduce this with the sample?

**Comment by or-dvir** [comment]
@mikepenz  i could try but im having a little trouble finding which list items in the sample use a cardView...

**Comment by FabianTerhorst** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/res/layout/simple_image_item.xml#L2
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleImageItem.java

**Comment by mikepenz** [comment]
@or-dvir any new updates?

**Comment by or-dvir** [comment]
@mikepenz sorry havnt had time to check it yet :( last week and this week are very busy. hopefully ill have time by the end of the week

**Comment by or-dvir** [comment]
@mikepenz ok i have reproduced this on the sample activity.

in this class: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleImageItem.java

you need to change the `bindView` method to this:

```
@Override
    public void bindView(SimpleImageItem.ViewHolder viewHolder, List<Object> payloads) {
        super.bindView(viewHolder, payloads);

        //get the context
        Context ctx = viewHolder.itemView.getContext();

        //define our data for the view
        viewHolder.imageName.setText(mName);
        viewHolder.imageDescription.setText(mDescription);
        viewHolder.imageView.setImageBitmap(null);

        //////////////////////////////////////////////////////////////////////////////
        //lines in between these "markers" have been changed 
        
        
        //original code:
//        int color = UIUtils.getThemeColor(ctx, R.attr.colorPrimary);
//        viewHolder.view.setForeground(FastAdapterUIUtils.getSelectablePressedBackground(ctx, FastAdapterUIUtils.adjustAlpha(color, 100), 50, true));
        
        //my code that makes the items invisible:
        StateListDrawable stateListDrawable =
                FastAdapterUIUtils.getSelectableBackground(ctx, ctx.getResources().getColor(R.color.primary), true);
        UIUtils.setBackground(viewHolder.itemView, stateListDrawable);
        //////////////////////////////////////////////////////////////////////////////

        //load glide
        Glide.clear(viewHolder.imageView);
        Glide.with(ctx).load(mImageUrl).animate(R.anim.alpha_on).into(viewHolder.imageView);
    }
```

as you can see the original code and the code i posted are a little different:
- original code sets the **foreground** of the view **which is cast into FrameLayout in the viewHolder**)
- my code sets the **background** of the view **without casting**.

if i copy the original code of SimpleImageItem (the one with the foreground and frameLayout) i get the results i originally wanted - so i don't know if this is an actual problem you need (and want) to look into or not (if you do, you can reproduce it now in the sample app).

this must be a CardView thing where the standard ways don't work...

**Comment by mikepenz** [comment]
@or-dvir thanks for reporting back with such a detailed report. 

I think it may be really a result out of foreground vs background. 

I am 99.9999% sure it is not an FastAdapter issue but rather a problem of the `RV` and how it handles such a `CardView` view
