### ISSUE TITLE
Unable to get view in onClick

### ISSUE THREAD

**Issue by judemanutd** [mikepenz/FastAdapter#496]
I was using the following code to detect a click event and do some processing but for some reason the event did not fire if the viewholder contained a checkbox and only the checkbox was clicked.

    fastAdapter.withOnClickListener(new FastAdapter.OnClickListener<Item>() {
    @Override
    public boolean onClick(View v, IAdapter<Item> adapter, Item item, int position) {
       // Handle click here
	return true;
    }
    });

So i switched to the  the following code where i have set up an onclick for multiple views.Everything is working fine but the problem is that if any view was clicked i would like to check the checkbox but if i try to get a hold of the checkbox in the onclick it returns null.

    selectionItemFastAdapter.withEventHook(new ClickEventHook<ChannelSelectionItem>() {

            @Nullable
            @Override
            public List<View> onBindMany(@android.support.annotation.NonNull RecyclerView.ViewHolder 
    viewHolder) {
                List<View> views = new ArrayList<>();
                if (viewHolder instanceof ChannelSelection_ViewHolder) {
                    ChannelSelection_ViewHolder holder = (ChannelSelection_ViewHolder) viewHolder;
                    views.add(holder.getName());
                    views.add(holder.getSubscribed());
                    views.add(holder.getNewTag());
                    views.add(holder.getHolder());
                    return views;
                }
                return super.onBindMany(viewHolder);
            }

            @Override
            public void onClick(View v, int position, FastAdapter<ChannelSelectionItem> fastAdapter, 
    ChannelSelectionItem itemChannel) {

    //trying to get hold of a view [ holder.getSubscribed() ] but it is null.
            }
        });

**Comment by mikepenz** [comment]
@judemanutd the first code will not work if:
your item is not clickable
your item is not enabled
you consume the click event somewhere else
your view has clickable false somewhere
some other listener consumes the click event
some view is above your recyclerview and consomes the event

**Comment by judemanutd** [comment]
The way the code works is that i have a list view who's onclick generates a dialog box.
I am using [https://github.com/afollestad/material-dialogs](url) which lets me specify my own adapter for the list in the dialog box.
The inner list is where the checkbox lies.I have posted my xml layout,clicking on the text view fires the event but the checkbox does not fire for some reason.

    <?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/holder"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_margin="10dp"
    android:clickable="true">

    <ImageView
        android:id="@+id/new_tag"
        android:layout_width="25dp"
        android:layout_height="25dp"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:layout_centerVertical="true"
        android:src="@drawable/new_box"
        android:visibility="gone" />

    <CheckBox
        android:id="@+id/subscribed"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_centerVertical="true"
        android:clickable="true" />

    <TextView
        android:id="@+id/channel_name"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignWithParentIfMissing="true"
        android:layout_centerVertical="true"
        android:layout_marginEnd="5dp"
        android:layout_marginLeft="5dp"
        android:layout_marginRight="5dp"
        android:layout_marginStart="5dp"
        android:layout_toEndOf="@id/new_tag"
        android:layout_toLeftOf="@id/subscribed"
        android:layout_toRightOf="@id/new_tag"
        android:layout_toStartOf="@id/subscribed"
        android:ellipsize="marquee"
        android:focusable="true"
        android:focusableInTouchMode="true"
        android:marqueeRepeatLimit="marquee_forever"
        android:maxLines="1"
        android:scrollHorizontally="true"
        android:singleLine="true"
        android:textSize="18sp" />

    </RelativeLayout>

**Comment by mikepenz** [comment]
@judemanutd I do not know the code of the material-dialogs. if this one applies it's own click logic, or listeners then it might overwrite and prevent any listeners of the `FastAdapter` 

try your adapter code and item with a `RecyclerView` somewhere else in the app, if it works you know that the material dialogs are preventing it
