### ISSUE TITLE
ItemTouchDropped not called

### ISSUE THREAD

**Issue by sparkitny** [mikepenz/FastAdapter#499]
Hi,

I migrated to the latest version and wanted to change the reaction of a Drag'n Drop, so that the code of finally storing the positions of the items when the callback itemTouchDropped has been called. I scanned posible issues in your project, but didn't find any clues of what the problem might be. Do you have an idea of what my issue is?

Thanks in advance.

PS.: Maybe it's important to state that I use EventHooks to initiate the drag

**Comment by mikepenz** [comment]
@sparkitny did it work before? Did you have a look into the samples?

**Comment by sparkitny** [comment]
Hi,

no, it didn't work before. I tried it you first introduce it, but I thought it may be a bug or my fault. Here you see my code, where I try to to use it. I deleted unnecessary code

`public class RoutineDetail extends Fragment implements
        EditTextView.OnTextChangeListener, ItemTouchCallback {


    private static final String TAG = "RoutineDetail";
    @BindView(R.id.routine_detail_view_routine_name_value)
    protected EditTextView routineName;
    @BindView(R.id.exercise_list)
    protected RecyclerView exerciseList;
    private FastItemAdapter<ExerciseItem> adapter;
    private ItemTouchHelper touchHelper;
    private SimpleDragCallback dragCallback;
    private boolean dirty = false;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.fragment_routine_detail, container, false);

        ButterKnife.bind(this, view);

        routine = FitNavDrawer.db.getRoutineById(routineId);

        adapter = new FastItemAdapter<>();

        exerciseList.setAdapter(adapter);
        exerciseList.setLayoutManager(new LinearLayoutManager(getActivity()));
        exerciseList.setItemAnimator(new ScaleUpAnimator());

        dragCallback = new SimpleDragCallback(this);
        dragCallback.setIsDragEnabled(true);

        touchHelper = new ItemTouchHelper(dragCallback);
        touchHelper.attachToRecyclerView(exerciseList);

        adapter.withEventHook(getMoveHook());

        return view;
    }


    private TouchEventHook<ExerciseItem> getMoveHook() {
        return new TouchEventHook<ExerciseItem>() {

            public boolean onTouch(View v, MotionEvent event, int position, FastAdapter<ExerciseItem> fastAdapter, ExerciseItem item) {

               ExerciseItem.ViewHolder viewHolder = item.getCurrentViewHolder();


                touchHelper.startDrag(viewHolder);
                return true;
            }

            public View onBind(RecyclerView.ViewHolder viewHolder) {
                if (viewHolder instanceof ExerciseItem.ViewHolder) {

                    return ((ExerciseItem.ViewHolder) viewHolder).moveButton;
                }
                return null;
            }
        };
    }
    public boolean itemTouchOnMove(int oldPosition, int newPosition) {

        Collections.swap(adapter.getAdapterItems(), oldPosition, newPosition);

        adapter.notifyAdapterItemMoved(oldPosition, newPosition);

        dirty = true;

        return true;
    }

    public void itemTouchDropped(int oldPosition, int newPosition) {

        Log.d(TAG, String.format("Stored routine %s", routine.getName()));
        Log.d(TAG, String.format("Old: %s New: %s", oldPosition, newPosition));

        storeRoutine();
    }
}
`

**Comment by sparkitny** [comment]
Hi Mike,

I figured out my fault. I forgot to implement the interface IDraggable<,>. Now, it works smoothly.

Thanks anyway

Sebastian
