### ISSUE TITLE
Expandable items init state not working

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#502]
I'm creating items and set the expandable state manually via `withIsExpanded(true)` and then I call `adapter.setNewList(items)`. If I do this all my headers show up collapsed (but internally they think they are not) and when clicking them the adapter get's confused and thinks the headers below the clicked header are the clicked headers children and hides them. This happens because the item says it's expanded but the adapter does not have the children in it.

I've disabled positon based state management of course.

If I init all headers in collapsed state and call `adapter.expand()` everything works fine. I can collapse headers afterwards manually again but I think it should work like above as well.

**Edit**

I think the `setNewList` should check if items are expanded and add it's children as well, it does not do this yet (like `adapter.expand()` does it for example)

**Comment by mikepenz** [comment]
@MFlisar as of the current behaviour this is expected, and you should use the `expand()` methods to expand.

It might be different in the future. Someone might write a `extension` for the FastAdapter v3 which allows this

**Comment by MFlisar** [comment]
What would you suggest for selective initial expandable states?

* set items of adapter (`adaptersetNewList(items)`
* expand all items (`adapter.expand()`)
* expand items via `adapter.collapse(index)` selectively with the indizes starting from top to bottom?

**Comment by mikepenz** [comment]
hmmm well you could theoretically use the "savedInstanceState" too :D and define the "id's" you want to expand

**Comment by MFlisar** [comment]
I thought about this as well ;-)

**Comment by mikepenz** [comment]
Well it would definitely simplify your code. at least for the time being.

for v3 someone might want to improve the expandable extension though

the thing with expandables simply is they have to be added to the RV (added to the main list of items) and get displayed, and removed there again. 
I have not yet thought of a nice (and fast) solution to display them without modifying the main displayed item list. (and I am afraid there is no real good alternative, as to the current solution)

**Comment by MFlisar** [comment]
I understand. For now, if someone else needs it, here's my helper function:

I understand. For now, if someone else needs it, here's my helper function:

	public static void setNewList(FastItemAdapter<IItem> adapter, List<IItem> items) {
        Bundle expandedStates = getExpandedIdsBundleAndResetExpanded(items, "");
        adapter.setNewList(items);
        adapter.withSavedInstanceState(expandedStates);
    }

    private static Bundle getExpandedIdsBundleAndResetExpanded(List<IItem> items, String prefix) {
        Bundle b = new Bundle();
        ArrayList<String> ids = getExpandedIdsListAndResetExpanded(items);
        b.putStringArrayList("bundle_expanded" + prefix, ids);
        return b;
    }

    private static ArrayList<String> getExpandedIdsListAndResetExpanded(List<IItem> items) {
        ArrayList<String> ids = new ArrayList<>();
        for (IItem item : items) {
            if (item instanceof IExpandable && ((IExpandable)item).isExpanded()) {
                ids.add(String.valueOf(item.getIdentifier()));
                ids.addAll(getExpandedIdsListAndResetExpanded(((IExpandable) item).getSubItems()));
                ((IExpandable) item).withIsExpanded(false);
            }
        }
        return ids;
    }

**Comment by mikepenz** [comment]
Thanks

**Comment by MFlisar** [comment]
In v4 the adapter is finally saving it's ids as long, so you must use following helper methods:

    private fun getFastAdapterBundle(bundle: Bundle?, fastAdapterBundlePrefix: String): Bundle? {
        return if (bundle?.containsKey("bundle_expanded$fastAdapterBundlePrefix") == true) {
            bundle
        } else null
    }

    private fun getExpandedIdsBundleAndResetExpanded(items: List<IItem<*>>, fastAdapterBundlePrefix: String): Bundle {
        val ids = getExpandedIdsListAndResetExpanded(items)
        return Bundle().apply {
            putLongArray("bundle_expanded$fastAdapterBundlePrefix", ids)
        }
    }

    private fun getExpandedIdsListAndResetExpanded(items: List<IItem<*>>?): LongArray {
        val ids = ArrayList<Long>()
        items?.forEach {
            if (it is IExpandable<*> && it.isExpanded) {
                ids.add(it.identifier)
                ids.addAll(getExpandedIdsListAndResetExpanded(it.subItems).toList())
                it.isExpanded = false
            }
        }
        return ids.toLongArray()
    }

Took me some time to find this after migration...

**Comment by mikepenz** [comment]
@MFlisar can you add some more details why or where you need those helper methods?

**Comment by MFlisar** [comment]
I use it for my settings library in which I have normal settings and advanced settings and I want to initially only expand default settings.

So when I create my settings I also define groups and I define if this group is expanded or not by default and I need the methods to handle those initial state

**Comment by MFlisar** [comment]
I again came to my own issue and want to add an example to make clear what the ordering should be:

Example to expand all items by default:

	val expandableExtension = fastAdapter.getExpandableExtension()

	val items = <...>
	itemAdapter.add(items)
	// AFTERWARDS expand items, e.g. expand ALL like following:
    expandableExtension.withSavedInstanceState(getAllExpandableIdsBundle(items, ""), "")
	
Functions to expand all items:

	private fun getAllExpandableIdsBundle(items: List<IItem<*>>, fastAdapterBundlePrefix: String): Bundle {
        val ids = getAllExpandableIds(items)
        return Bundle().apply {
            putLongArray("bundle_expanded$fastAdapterBundlePrefix", ids.toLongArray())
        }
    }

    private fun getAllExpandableIds(items: List<IItem<*>>?): ArrayList<Long> {
        val ids = ArrayList<Long>()
        items?.forEach {
            if (it is IExpandable<*>) {
                ids.add(it.identifier)
                ids.addAll(getAllExpandableIds(it.subItems).toList())
            }
        }
        return ids
    }
	
@mikepenz 
it would still be nice to at least get access to a function to create such a bundle so that I don't have to hardcode this part: `putLongArray("bundle_expanded$fastAdapterBundlePrefix", ids.toLongArray())`
