### ISSUE TITLE
Avatar issue 

### ISSUE THREAD

**Issue by geniusforapp** [mikepenz/FastAdapter#503]
please can you update the avatar issue am trying to add the item without the avatar image but it does not work I want to add the item without showing the avatar I mean to change the status to Gone if it's not valid URL or empty

**Comment by mikepenz** [comment]
@geniusforapp I have no idea what you are talking about

**Comment by geniusforapp** [comment]
@mikepenz       fastItemAdapter.add(new SingleLineItem().withName("Country (Kuwait)"));
iam ading this item and i dont want to add avatar image or icon but it show the space of the avatar image is there any way to hide this space 
![20623699_10210050218388266_1203024747_o](https://user-images.githubusercontent.com/7538171/28935841-74ca96a8-788e-11e7-9808-d14544d32b32.png)

**Comment by FabianTerhorst** [comment]
Will fix soon.

**Comment by FabianTerhorst** [comment]
Fixed in #504
