### ISSUE TITLE
[Question] Clickable links in textviews

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#506]
It seems like the adapter overrides all touch events, and that we can only add them through the event hooks. Consequently, with a textview that contains a spanned html content, we can't enable the movement method to enable clickable links.

Is there any way around this?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter#4-click-listeners-for-views-inside-your-item

**Comment by mikepenz** [comment]
the thing is that the FastAdapter makes sure that listeners are only bound once during viewHolder creation as everything else would slow down the RV's performance and result in unnecessary created objects.

I use the FastAdapter in a setup myself with clickable spans in `TextView`s and it works quite fine.

**Comment by AllanWang** [comment]
@mikepenz does that work in this case?

To make links clickable, we define

```java
setMovementMethod(LinkMovementMethod.getInstance());
```

When we create the textview. We don't really handle the clicks ourselves afterwards.

Do you have a link to a working sample? I know you use this with AboutLibraries but I see clickable links there.

I will test some other methods

**Comment by mikepenz** [comment]
well we do this in the `bindView` method:

```
tv.setText(spannableString);
tv.setLinksClickable(true);
tv.setFocusable(false);
tv.setLinkTextColor(highlightColor);
tv.setMovementMethod(LinkMovementMethod.getInstance());
```

**Comment by mikepenz** [comment]
and the span has the `ClickableSpan`s applied.

**Comment by AllanWang** [comment]
Hm. Maybe I wasn't clicking properly. I tried what I did before again (setting the movement method on the viewholder creation) and it worked. Thanks
