### ISSUE TITLE
Feature request: Sorting

### ISSUE THREAD

**Issue by rubengees** [mikepenz/FastAdapter#51]
So I just started to try this lib. One thing I am missing is sorting of items.
Sure we could sort our datasets ourself every time but it would be very handy to have something like `withComperator(Comparator comparator)` or `withEnableNaturalSorting(boolean enable)`.
This could also allow to later just throw a new comparator in and have the data resorted.
I think this would be a very nice feature as most modern apps feature something like "Sort entries by label" and "Sort entries by modification time" like my App does.

**Comment by mikepenz** [comment]
@rubengees I think this is out of scope. You can provide a new list to the `FastAdapter` at any time. And sorting is as easy as 

```java
Collections.sort()
```
http://docs.oracle.com/javase/6/docs/api/java/util/Collections.html#sort(java.util.List)

No need to add more methods here, as it would just call this single method. I prefer this library to stay really focused.

**Comment by rubengees** [comment]
Yeah sure I know that I can sort myself, but it would be really handy if I won't have to. When I read the description of FastAdapter I thought it was some kind of All-in-one adapter which does all the common things you do with lists without the need for you to write the boilerplate yourself. So I don't think this is out of scope. The lists of other languages like C# offer such functionality out of the box.
And even if it easy, I think it just belongs to the adapter to do such tasks and not into the activity or wherever the adapter is used.

**Comment by Rainer-Lang** [comment]
@mikepenz In your way I have to get all items from adapter, sort them and then put them back in the adapter? Is this correct?

**Comment by mikepenz** [comment]
@Rainer-Lang normally you know about your items. You have to add them at some point. So I assume that you still know about the items at the point of time when you want to sort them

**Comment by Rainer-Lang** [comment]
@mikepenz And for "only" re-sorting, which method would you suggest?
1) ```set()```
2) ```setNewList()```

**Comment by Rainer-Lang** [comment]
@rubengees Please take a look at the newest version.

**Comment by rubengees** [comment]
Great! Thank you.

**Comment by Rainer-Lang** [comment]
@rubengees Would you like to provide this project with a little sample to this feature?

**Comment by Rainer-Lang** [comment]
@rubengees https://github.com/mikepenz/FastAdapter/blob/develop/CONTRIBUTORS.md :+1:

**Comment by rubengees** [comment]
Nice, thank you for adding me 👌

**Comment by Rainer-Lang** [comment]
Thanks for contributing.
