### ISSUE TITLE
how to cancel onclick on adapter

### ISSUE THREAD

**Issue by noam2** [mikepenz/FastAdapter#510]
hey ,
if i don't set withItemevent() on adapter, it sets an onclick listener on every item. i would like to cancel this so it doesn't trigger onclick (and that all views will stay disabled)

**Comment by mikepenz** [comment]
@noam2 you can set a item `enabled` or `disabled` 
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/IItem.java#L45

Disabling the attaching of the listener itself to the item is not supporteD:
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L608

**Comment by mikepenz** [comment]
Closing as answered. Please report back in case this was not helping
