### ISSUE TITLE
Views not updated when using DiffUtils with fastAdapter

### ISSUE THREAD

**Issue by ndrdmarshmallow** [mikepenz/FastAdapter#511]
Hi Mike,

I am using DiffUtils with fast adapter to update the views with updates. But when am updating the data like below the data is not updated in views though all methods are called properly. I observed that while calling the bindView adapter is still holding old data.

Below is my code :    

                List<LibraryItem> yLibraries = loadLibraries();
                DiffUtil.DiffResult diffResult = DiffUtil.calculateDiff(new LibrariesDiffCallback(libraries,yLibraries),true);

                libraries.clear();
                libraries.addAll(yLibraries);

                diffResult.dispatchUpdatesTo(new ListUpdateCallback() {
                    @Override
                    public void onInserted(int position, int count) {
                        fastAdapter.notifyAdapterItemRangeInserted(fastAdapter.getPreItemCountByOrder(fastAdapter.getOrder()) + position, count);
                    }

                    @Override
                    public void onRemoved(int position, int count) {
                        fastAdapter.notifyAdapterItemRangeRemoved(fastAdapter.getPreItemCountByOrder(fastAdapter.getOrder()) + position, count);
                    }

                    @Override
                    public void onMoved(int fromPosition, int toPosition) {
                        fastAdapter.notifyAdapterItemMoved(fastAdapter.getPreItemCountByOrder(fastAdapter.getOrder()) + fromPosition, toPosition);
                    }

                    @Override
                    public void onChanged(int position, int count, Object payload) {
                        fastAdapter.notifyAdapterItemRangeChanged(fastAdapter.getPreItemCountByOrder(fastAdapter.getOrder()) + position, count ,payload);
                    }
                });

and my DiffUtil class -

```
public class LibrariesDiffCallback extends DiffUtil.Callback {

    private List<LibraryItem> mOldList;
    private List<LibraryItem> mNewList;

    public LibrariesDiffCallback(List<LibraryItem> mOldList, List<LibraryItem> mNewList) {
        this.mOldList = mOldList;
        this.mNewList = mNewList;
    }

    @Override
    public int getOldListSize() {
        return mOldList != null ? mOldList.size() : 0;
    }

    @Override
    public int getNewListSize() {
        return mNewList != null ? mNewList.size() : 0;
    }

    @Override
    public boolean areItemsTheSame(int oldItemPosition, int newItemPosition) {
        return mNewList.get(newItemPosition).getKey().equals(mOldList.get(oldItemPosition).getKey());
    }

    @Override
    public boolean areContentsTheSame(int oldItemPosition, int newItemPosition) {
        LibraryItem oldItem = mOldList.get(oldItemPosition);
        LibraryItem newItem = mNewList.get(newItemPosition);

        return oldItem.getAuthor().equals(newItem.getAuthor())
                && oldItem.getTitle().equals(newItem.getTitle())
                && oldItem.getDescription().equals(newItem.getDescription())
                && oldItem.getFav() == newItem.getFav();

    }

    @Nullable
    @Override
    public Object getChangePayload(int oldItemPosition, int newItemPosition) {
        return super.getChangePayload(oldItemPosition, newItemPosition);
    }
}
```

**Comment by mikepenz** [comment]
@ndrdmarshmallow might be unrelated, but there was a PR to improve the `FastAdapterDiffUtil` here: https://github.com/mikepenz/FastAdapter/pull/509/files (for v3.x) 
You might want to have a look on it's implementation

**Comment by mikepenz** [comment]
@ndrdmarshmallow have you had a chance to check it out from v3?

**Comment by mikepenz** [comment]
Closing this for now. Please report back
