### ISSUE TITLE
Q : each item must query to database

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#512]
hi
this is not issue, it's just a question
i using this library in my projects, thanks for your great library

my list items have a icon to show if this item is stared or not ?
when i click on each item, i saved integrated model of my AbstractItem in database

what's your idea to know if is item read or not ? for best optimize

sorry for my english, thanks in advanced

**Comment by DJafari** [comment]
@mikepenz if you havn't any idea about this, please close this issue

**Comment by FabianTerhorst** [comment]
See the generic item sample in the sample app. You should create own data classes that aren´t items.

**Comment by mikepenz** [comment]
@DJafari as @FabianTerhorst already pointed out properly. You should have a look into th e`GenericItem` sample. which basically splits apart item and model. This approach allows you to have the model handled in the database and the item to just define how the model is displayed in your UI. 

other than that there is no special thing regarding the FastAdapter. that basically depends on the database you use, and what the best approach and most performant approach with that one will be.
