### ISSUE TITLE
Question: Clearing adapter does not clear selector items

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#513]
Example:

```java
adapter.add(items);
adapter.select(1);
Timber.d("CCC %d", adapter.getSelectedItems().size());
adapter.clear();
Timber.d("CCC1 %d", adapter.getSelectedItems().size());
```

Both items return 1.

Is this expected behaviour? Especially with the position based selection, the selected set will likely be void when the list changes.

Using FastAdapter 2.6.3

**Comment by mikepenz** [comment]
@AllanWang you use the position based state management? 
Seems to be only related to that one. It will be no more issue with v3.x as it will remove that state management completely. (as of it's complexity) 

but yes seems like an issue for 2.x.

**Comment by AllanWang** [comment]
Yup using position based. Thanks for the info.
