### ISSUE TITLE
Multi Selection: using multiple views in simple item.

### ISSUE THREAD

**Issue by manid2** [mikepenz/FastAdapter#514]
Hi, 
Please give me a code snippet showing.

1. How to apply ClickListener for views within an item?
2. How to Toggle the view colors on selected item, in onSelectionChanged() method?

Currently I can get the selected item and selection state, when clicked on outside of a card view.
But when I click on the card view the item is not selected.
The card view has a TextView within it, the user can either click on the card view or the text view to select an item but not outside the card view. 

When clicked I want to toggle the color of the card view and text color of TextView.

I have gone through the sample code and the blog post, but unable to figure out how to implement the above two actions.

Thank you,
Mani

**Comment by FabianTerhorst** [comment]
Hi,
For your first question take a look at the sample in the readme. 
https://github.com/mikepenz/FastAdapter#4-click-listeners-for-views-inside-your-item
You can add as many event hooks as you need to.
To toggle the view color when an item gets selected, just use the isSelected() to check if the item is selected or not inside onBind. When you have click listeners in your item, make sure there don´t stop intercepting the click event to the itemView.

**Comment by manid2** [comment]
Hi,
Thank you for the quick reply.

Here is the code snippet, i tried as per your answer:
`mFastAdapter.withEventHook(new ClickEventHook<VccMaterialItem>() {
            private CardView cardView;
            private TextView textView;

            @Nullable
            @Override
            public View onBind(@NonNull RecyclerView.ViewHolder viewHolder) {
                //return the views on which you want to bind this event
                if (viewHolder instanceof VccMaterialItem.ViewHolder) {
                    cardView = ((VccMaterialItem.ViewHolder) viewHolder).mCardView;
                    textView = ((VccMaterialItem.ViewHolder) viewHolder).mTextView;

                    if (cardView.isSelected()) {
                        cardView.setCardBackgroundColor(getActivity().getResources().getColor(R.color.app_green_dark));
                        textView.setTextColor(getActivity().getResources().getColor(R.color.app_white));
                    } else {
                        cardView.setCardBackgroundColor(getActivity().getResources().getColor(R.color.app_light_blue_50));
                        textView.setTextColor(getActivity().getResources().getColor(R.color.primary_text));
                    }
                    return cardView;
                } else {
                    return null;
                }
            }

            @Override
            public void onClick(View v, int position, FastAdapter<VccMaterialItem> fastAdapter, VccMaterialItem item) {
                //react on the click event
                Logger.i("Clicked [%s]", item.getText());
            }
        });`

I m getting the logger output when clicked on the cardview, but i m not able to toggle the color inside the onBind() method.

**Comment by FabianTerhorst** [comment]
The onBind of the event hook is only there to return the view the click listener should bind to and nothing more.

**Comment by manid2** [comment]
I am sorry, I do not understand how it is implemented in code. 
Kindly show me a code snippet to toggle the view color on select/unselect.

**Comment by manid2** [comment]
Now I have moved the view color toggling to onClick() method,

```java
@Override
            public void onClick(View v, int position, FastAdapter<VccMaterialItem> fastAdapter, VccMaterialItem item) {
                //react on the click event
                Logger.i("Clicked [%s]", item.getText());
                if (cardView.isSelected()) {
                    cardView.setCardBackgroundColor(getActivity().getResources().getColor(R.color.app_green_dark));
                    textView.setTextColor(getActivity().getResources().getColor(R.color.app_white));
                } else {
                    cardView.setCardBackgroundColor(getActivity().getResources().getColor(R.color.app_light_blue_50));
                    textView.setTextColor(getActivity().getResources().getColor(R.color.primary_text));
                }
            }
```

Still no luck. Please help, I need to make a great app.

Thank you,
Mani

**Comment by FabianTerhorst** [comment]
like i said use for your normal viewbindings the bind of the item and for click handling the onClick.

**Comment by manid2** [comment]
Accessing any view inside `onClick` affects another view in the list since the views are recycled. I found out that this line is responsible for setting the background to ***RED*** color in the **FastAdapter sample**.
```java
//set the background for the item
UIUtils.setBackground(viewHolder.view, FastAdapterUIUtils.getSelectableBackground(ctx, Color.RED, true)); 
```

Similarly I tried in my app, 
```java
UIUtils.setBackground(viewHolder.mCardView, FastAdapterUIUtils.getSelectableBackground(ctx, Color.GREEN, true));
```
It will set the background for the card view to ***GREEN*** in selected state with the ripple effect which is the desired result, in unselected state the view is invisible. 

It would be very grateful if you can explain why it is invisible in unselected state? Is it something do with the LinearLayout within which the card view is placed?

Thank you,

**Comment by mikepenz** [comment]
@manid2 seems to be related to the CardView or so. It is not really related to this library. 
There might be some weird behaviour of a CardView in a RecyclerView... 

Please see here: https://github.com/mikepenz/FastAdapter/issues/495

**Comment by manid2** [comment]
@mikepenz Thank you for pointing me to post #495. I will try this method to see if it works in my app.
Thank you for the good support. :relaxed:

**Comment by manid2** [comment]
Hi @mikepenz , I tried the method in #495, it works in my app. I used `FrameLayout` and set its foreground as it is implemented in the sample app.

```java
viewHolder.view.setForeground(FastAdapterUIUtils.getSelectablePressedBackground(ctx, FastAdapterUIUtils.adjustAlpha(color, 100), 50, true));
```

Thank you for the answers, I am happy 😃.
