### ISSUE TITLE
Q: Is there a way to get a view in EventHook?

### ISSUE THREAD

**Issue by guuilp** [mikepenz/FastAdapter#515]
This is my event Hook:

```
        groupOneTimePlayers.withEventHook(new ClickEventHook<GroupOneTimePlayers>() {
            @Nullable
            @Override
            public View onBind(@NonNull RecyclerView.ViewHolder viewHolder) {
                if (viewHolder instanceof GroupOneTimePlayers.ViewHolder) {
                    return ((GroupOneTimePlayers.ViewHolder) viewHolder).changePlayerToRecurring;
                }
                return null;
            }

            @Override
            public void onClick(View v, int position, FastAdapter<GroupOneTimePlayers> fastAdapter, GroupOneTimePlayers item) {
                changePlayerToRecurring(item.getPlayer().getUserId(), item, position);
            }
        });
```

Inside of this, I'd like to change the visibility of my ProgressBar and hide another ImageView (both of these views are on the View Holder). Is there a way to accomplish this inside EventHook from Fast Adapter?

**Comment by FabianTerhorst** [comment]
You can use v.getParent() and so on, to find the other views inside the item layout

**Comment by guuilp** [comment]
getChildren, instead, verifying if the instanceof is ProgressBar or ImageView?

**Comment by FabianTerhorst** [comment]
You could just check the view id.

**Comment by guuilp** [comment]
I'll give it a try. Thanks for the help, @FabianTerhorst !

**Comment by mikepenz** [comment]
@guuilp another way would be (as you have the item + the position and the adapter) to notify the adapter about the change with a payload. so you could only to a partial view update (which would be the preferred solution as of the android docs)

**Comment by guuilp** [comment]
@mikepenz do you have any doc about the payload to send me? I got what you said, but I don't know how to implement this payload. Like: 

playersInFastAdapter.notifyItemChanged(position, payload);

I know payload is a list of objects, but how do I identify this inside my FastAdapterItem and then update the view visibility?

**Comment by mikepenz** [comment]
the payload is a standard `RecyclerView.Adapter` thing. nothing special. 

you notify with the payload. 

then you get the bindView called with that payload. You go through the list of payloads and just update the view you have to update.

all mentioned in the official Android javadoc. 

(fastAdapter.notifyAdapterItemChanged())

**Comment by guuilp** [comment]
I've found the problem: https://stackoverflow.com/a/33451317/3394588

I'm using your library to include animations into my RecyclerView.

Do you have any sugestions in this specific case?

**Comment by mikepenz** [comment]
well if you have an animator and the partial update is not possible, 

just use the `view` you get in the eventHook, and get the parent, or child whatever you are searching for
