### ISSUE TITLE
Questions: How to let a groupItem have different subItems?

### ISSUE THREAD

**Issue by fly7632785** [mikepenz/FastAdapter#518]
Hi, May I ask a question?
Is there a way to let a groupItem have different subItems?
I tried some ways , can't work.
If it can, any sample?

**Comment by fly7632785** [comment]
I saw GenericItemActivity in the sample.
But the two subItems have same Model(super relationship ) and same ViewHolder,  
But how to deal with that I have two different subItems with different ViewHolders in same ExpanableGroupItem? 

And  I found the GenericAbstractExpandableItem, so is there any sample of it ?
Thank you.

**Comment by mikepenz** [comment]
@fly7632785 you simply use the `IItem` interface as type, which will allow you to pass in any item you want to use.

**Comment by mikepenz** [comment]
See for example this sample: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/IconGridActivity.java

(the sub items have a different type than the parent)
