### ISSUE TITLE
Expected release of V3 ?

### ISSUE THREAD

**Issue by Pantkowsky** [mikepenz/FastAdapter#519]
Hey @mikepenz !

Just a quick question - when are you expecting to have the V3 of FastAdapter released (approximately) ? As I understood from reading one of the topics (issues), there are some major changescoming up with V3. I'm leaning towards using FastAdapter for one of the projects I'm working on and therefore would like to find out when the V3 is coming out - mainly to see if I can avoid refactoring and migration to the newest version of the library.

Cheers!

**Comment by Rainer-Lang** [comment]
@Pantkowsky Have a look here: https://github.com/mikepenz/FastAdapter/issues/483
Maybe you want to test a bit and help to get v3 "faster" released. ;-)
v2 is already really AWESOME!

**Comment by Pantkowsky** [comment]
@Rainer-Lang I did, but didn't find any info in regards to timeline. I realize that v2 is amazing, I just wanted to estimate whether or not it makes more sense to wait for v3 (if the release is right around the corner) or go ahead and start implementing v2 for my project. 

I don't mind testing. I'm considering going with the snapshot version and refactor if needed later on. If I stumble upon anything in the process I will most definitely let you guys know about that!

**Comment by mikepenz** [comment]
@Pantkowsky at the moment there is no ETA available, as we want to make sure the new version is as stable as v2. and that everything works as expected. 

Just follow the open branch and the commits + dicussion happening in the PRs ;)

**Comment by bernaferrari** [comment]
I am using it in my release apps and it is working fine..

**Comment by mikepenz** [comment]
@bernaferrari thanks for the feedback. v3 is already pretty stable for the core functions I'd say.

**Comment by bernaferrari** [comment]
I have a question, since you are here. While I love Fast Adapter, it doesn't works PERFECTLY with viewpager or anything that needs to swipe it horizontally (even in your example, swiping right/left is hard, compared to the standard android and to other libraries). Is there a way for me to change this or an api for customizing?

**Comment by mikepenz** [comment]
@bernaferrari the `FastAdapter` does not change anything on that behaviour at all. It is just the adapter code. I am wondering why it would differ

**Comment by bernaferrari** [comment]
Weird... Me too.. With ViewPager it captures the touch and tries to scroll down 80% of the time. With the swipe to delete in demo, I found the BRVAH as standard as could be (but I still prefer fast adapter for the other 99% usages 😛 ) https://github.com/CymChad/BaseRecyclerViewAdapterHelper
