### ISSUE TITLE
Changer RED color highlight when clicked item 

### ISSUE THREAD

**Issue by hungcv92** [mikepenz/FastAdapter#52]
My english very bad! I hope you can know my mine! I have problem like "how to changer RED color highlight when clicked Item recyclerview" in SimpleItemListActivity! Please tell me how to do this?

**Comment by Rainer-Lang** [comment]
Did you look in the examples - there should be 2: One at the starting (with images) and the other one SimpleItemListAcitivity (you already found it).
Please have a look into the layout-xml files and in the bindView() of these examples.

First of all I would suggest to use a FrameLayout and in bindView() use this:
```viewHolder.view.setForeground(FastAdapterUIUtils.getSelectablePressedBackground(ctx, FastAdapterUIUtils.adjustAlpha(<the color you want to show for selection>, 100), 50, true));```

**Comment by hungcv92** [comment]
Thanks so much for your support @Rainer-Lang @mikepenz  :D Thanks so much again!
