### ISSUE TITLE
FastAdapter populated by different view types

### ISSUE THREAD

**Issue by Pantkowsky** [mikepenz/FastAdapter#520]
I was going through your docs and already closed issues, as well as the sample app. I wanted to ask (double check) about having the FastAdapter work with different types of items. For my use case, I need to have a recyclerView that works with a set of "items", each being a completely different one. Let me visualize:

![mock](https://user-images.githubusercontent.com/9194725/29367148-41932738-829c-11e7-94a1-4cdf6b6cc04d.png)

Lets say that my first item is a view composed of a ViewPager and two Text Views. It is in position 0 in the recyclerView (which has a linear layout manager with vertical direction). The second item is recyclerview/gridview (with scrolling disabled) displaying a grid of custom objects, being at position 1. The third item is another recycleriew or listview (with scrolling disabled) having its first object as a textview/spinner or else, and its following items being custom objects.

For the purpose of my question, the layouts presented and view components used are arbitrary. It does not mean I need the exemplary list views specifically. It serves me the purpose of asking whether or not it is possible to have the FastAdapter work with items each being of different type (lets actually call them sections for clarity, like you could have in an app with user profile screen).

**Comment by mikepenz** [comment]
@Pantkowsky the `FastAdapter`  as managing instance has to have the upper "type" defined. so if the only parent class combining those items is the `IItem` interface, use this one as type for the `FastAdapter`. 

Basically you also do not have to define the type of the adapter, you will loose the type safety, and your listeners will no longer pre cast to the type you expect (So you have to cast and use instanceOf more oftne :D) but in general ther eis no requirement to just use the same type of item. 

the sample shows this already a few times.

**Comment by mikepenz** [comment]
Please see my answer. if there are more questions. re-open
