### ISSUE TITLE
Weird EventHook

### ISSUE THREAD

**Issue by bernaferrari** [mikepenz/FastAdapter#522]
Hi!

I am trying to make something like the https://play.google.com/store/apps/details?id=com.google.android.contacts, where when adding a contact, when the user taps the first letter or number in keyboard, it adds another field. In FastAdapter, I am using an EventHook to grab everything and then the v.findViewById<EditText>(R.id.name) to grab the EditText view.

Problem is, when I tap the EditText first, the withEventHook is never called. I need to tap in the recycler background (or anything that is not the EditText) and then the EditText for it to work. I tried to Log it and found out onClick is never called when I tap the EditText first; in any case, I put my usage below.

fastFA.withSelectable(true) didn't change the output. I tested in 3.0.0.8-SNAPSHOT and 3.0.0.7.

Can someone help me? Thanks!!

```
fastFA.withEventHook(object :ClickEventHook<FAItem>(){
            override fun onBind(viewHolder: RecyclerView.ViewHolder): View? {
                return viewHolder.itemView
            }

            override fun onClick(v: View, position: Int, fastAdapter: FastAdapter<FAItem>, item: FAItem) {
                if (item.kind == 2) {
                        v.findViewById<EditText>(R.id.name).addTextChangedListener(object:TextWatcher{
                            override fun afterTextChanged(p0: Editable?) {
                                fastFA.add(position+1,FAItem("12345678", 2))
                           }

                            override fun beforeTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {}

                            override fun onTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {}
                        })
                }
            }
        })
```

**Comment by FabianTerhorst** [comment]
Hi,

you have to create an custom event hook and use viewHolder.yourEditText instead of itemView. Then you register inside attachEvent the text change listener

**Comment by bernaferrari** [comment]
Ok.. but each row shall have 3 items that will need listener: an EditText, a Spinner, and an ImageView. I thought using ItemView was smart, since using viewholder.yourEditText will forbid the others, won't it?

**Comment by mikepenz** [comment]
@bernaferrari you can define as many hooks inside an item as you want, you can also hook up the same eventhook to multiple views within the same item.

**Comment by bernaferrari** [comment]
Thanks! All your ideas have made my constructor way better. However, the same issue persists. The 'onClick' method is never called when I tap the EditText at the first time, without anything else.

@FabianTerhorst  mentioned about 'attachEvent' but I'm not sure I understand this part.

**Comment by FabianTerhorst** [comment]
As i said earlier use an custom event hook when you want to set an custom listener.

**Comment by bernaferrari** [comment]
Ok, I was dumb.. I put the listener inside the onBind instead of onClick.. everything works now... thanks for all the help!!!
