### ISSUE TITLE
Expandable item - update header

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#523]
I think it would make sense to have a setting for enabling notifying the header item of expandable items. I have following use case:

* a custom `RecyclerView.ItemDecoration` that takes care to add margins around items and that also adds a margin below the last item

If the last item is a collapsed header, it gets a margin from my `ItemDecoration`. If I now expand the last item, this margin stays because the adapter is not notifying the header so that it invalidates it's view and recalculates it's state.

My solution is to manually notify the `RecyclerView` to update the header in a custom click listener, but that's cumbersome. A simple flag for the builder would be nicer.

**Comment by FabianTerhorst** [comment]
Not sure if this is in the scope of the library, since it's not an common use case.

**Comment by MFlisar** [comment]
Actually, it's my second use case for something like this after showing a counter of sub items in the header...
