### ISSUE TITLE
Multi Selection: Select all option in menu item.

### ISSUE THREAD

**Issue by manid2** [mikepenz/FastAdapter#525]
Hi,

I want to include select all feature in the CAB,
Here is the code i have implemented:

```java
switch (item.getItemId()) {
	case R.id.menu_item_select_all:
		// TODO: Select all items.
		for (int position = 0; position < mMaterialItemCount; position++) {
			mFastAdapter.select(position);
		}
		mode.finish(); // Action picked, so close the CAB
		consumed = true;
		Logger.d("Menu item select all clicked!");
	default:
		consumed = false;
}
```
But it is **not selecting anything**, it simply goes back **deselected state** on clicking the select all button in CAB. Can you please explain why it is doing that?

Thank you,
Mani

**Comment by mikepenz** [comment]
@manid2 di you use the `ActionModeHelper`? or do you handle the CAB manually, if you handle it manually I see no reason why it would do that. for the `ActionModeHelper` that's expected behaviour if you end the CAB state

**Comment by manid2** [comment]
Hi @mikepenz 
Yes I am using `ActionModeHelper`. I understood the issue clearly, I have changed the above code as follows:
``` java
public boolean onActionItemClicked(ActionMode mode, MenuItem item) {
	boolean consumed = false;  // true - Indicates the event is consumed.
	switch (item.getItemId()) {
		case R.id.menu_item_select_all:
			// TODO: Select all items.
			mFastAdapter.select();
			consumed = true;
			Logger.d("Menu item select all clicked!, mMaterialItemCount = %d", mMaterialItemCount);
	}
	mode.finish(); // Action picked, so close the CAB
	return consumed;
}
```
All items are selected as expected on clicking `select all`, but due to `mode.finish()` it closes the CAB and hence deselects all the items.

If I omit `mode.finish()` then on clicking `select all`, it erases the fragment contents or the adapter contents. I m unable to tell why it is erasing the contents of the adapter itself or the fragment' contents.

Do you know anything about this?  I just want to implement select all feature in the CAB. Any approach would be fine.

Thank you,
Mani

**Comment by manid2** [comment]
@mikepenz Note: **To avoid any confusion**, the code I posted above `onActionItemClicked()` belongs to my custom class that handles the `select all` click and few other buttons on CAB.

The following lines from `ActionModeHelper`'s `ActionBarCallBack` class, calls my method `onActionItemClicked` in which I have implemented `select all`.
```java
if (mCallback != null) {
     consumed = mCallback.onActionItemClicked(mode, item);
}
```

I hope I made the issue clear. If you need any information please let me know.

Thank you,
Mani

**Comment by mikepenz** [comment]
Well that's default behaviour of the helper as you can see here: 
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/ActionModeHelper.java#L92

just do not forward the `onClick` in this case.
