### ISSUE TITLE
Problem with listAdapter.withOnClickListener 

### ISSUE THREAD

**Issue by carmas123** [mikepenz/FastAdapter#526]
Hi Mike, I've a problem with adapter withOnClickListener event listener.
It will never fired.
If I use onClick event on `holder.itemView` it's work, but if I want to use adapter event it doesn't work.
What can I check?

**Comment by Rainer-Lang** [comment]
Did you try EventHook? 
https://github.com/mikepenz/FastAdapter/blob/78e4608042a8b44c1be5fb0e634ae074ef498a97/README.md#4-click-listeners-for-views-inside-your-item 
and see here:
https://github.com/mikepenz/FastAdapter/blob/edf6154d0183f72e7352cef5c382e3af7dcc5531/app/src/main/java/com/mikepenz/fastadapter/app/ImageListActivity.java#L74

Hope this helps.

**Comment by carmas123** [comment]
Yes this can work, but it cannot solve my problem.
If withOnClickListener is not fired it means that I cannot use functionality like AutoExpand and auto collapse all other item.

**Comment by carmas123** [comment]
However this event is not fired

**Comment by carmas123** [comment]
The problem could be because I use AsyncListUtil to load my items into my adapter...I investigate.

**Comment by carmas123** [comment]
Solved.
The problem is when use a custom `FastAdapter.OnBindViewHolderListener`.
When you use this method you need to specify the tag used by FastAdapter to identify the item, you need to add a think like this:

```
  override fun onBindViewHolder(viewHolder: RecyclerView.ViewHolder, position: Int, payloads: MutableList<Any>?) {
            val item = listAdapter?.getItem(position)
            if (item != null) {
                //set the R.id.fastadapter_item tag of this item to the item object (can be used when retrieving the view)
                viewHolder.itemView.setTag(R.id.fastadapter_item, item)
            }
            this@BaseModelListFragment.listItemBindView(viewHolder, position)
        }
```

Regards, and thank you to all.

**Comment by FabianTerhorst** [comment]
You could simply override ```OnBindViewHolderListenerImpl``` and use your own class in ```withOnBindViewHolderListener```

**Comment by carmas123** [comment]
Yes this is true but when I try to inherit it I got this error:
![image](https://user-images.githubusercontent.com/6574219/29602102-f74eb7da-87de-11e7-956b-067ab506ae34.png)

Unresolved reference: OnBindViewHolderListenerImpl

**Comment by TheMaxCoder** [comment]
I had the same problem. withOnClickListener or any other clicklisteners were not getting fired at all.
But clickListener inside viewHolder was working fine. Spent hours trying to figure out what's wrong an then I found I had 
```
android:clickable="true"
android:focusable="true"
android:background="?attr/selectableItemBackground"
```
set to recycler view item. Removing these solved the issue for me.

**Comment by kalyandechiraju** [comment]
> I had the same problem. withOnClickListener or any other clicklisteners were not getting fired at all.
> But clickListener inside viewHolder was working fine. Spent hours trying to figure out what's wrong an then I found I had
> 
> ```
> android:clickable="true"
> android:focusable="true"
> android:background="?attr/selectableItemBackground"
> ```
> set to recycler view item. Removing these solved the issue for me.

```
android:clickable="true"
android:focusable="true"
```
are the culprits
