### ISSUE TITLE
cant put state list drawable with onitemclick

### ISSUE THREAD

**Issue by noam2** [mikepenz/FastAdapter#527]
hey,
i have an item in xml that i put a drawable background selector to it, to change the background color of whole item when its clicked : 

```xml
android:clickable="true"
android:background="@drawable/back1"
```

when i add in java fastAdapter.withOnClickListener - it doesn't work , i guess  beacuse of selector in xml :
```java
     fastAdapter.withOnClickListener(new FastAdapter.OnClickListener<AdapterMobyList>() {
            @Override
            public boolean onClick(View v, IAdapter adapter, AdapterMobyList item, int position) {
                return false;
            }
        });
```
i have also another case of this but only instead of fastAdapter i use fastItemAdapter and it works.. so how i can i fix this ?????

**Comment by mikepenz** [comment]
@noam2 I use `DrawableStateList`s myself and they do not prevent click listeners or anything. 

Anything else in your code which might prevent this?

**Comment by mikepenz** [comment]
@noam2 please report back. close for now
