### ISSUE TITLE
Infinite loop adapter

### ISSUE THREAD

**Issue by gpulido** [mikepenz/FastAdapter#528]
Hello,
I want to create an adapter that would scroll a list in a cycle.
The list is a classification for a tournament that I will show on a TV on an endless loop using some kind of animation to do the scrolling.
Is there any easy way to implement an adapter that would just simulate the effect ?

Thank you!!

**Comment by mikepenz** [comment]
@gpulido well you can simply add elements at the end and remove elements from the top. there is nothing in the adapter doing something like this. 

seems like a very specific usecase

**Comment by gpulido** [comment]
@mikepenz I know that is very specific, but not unusual, 
For example it could be useful to implement an image carrousel showcase.
I was thinking if a "fastadapter wrapper" could be created to just generate the effect (no the animation, just the infinite loop).
Something like: InfiniteLooperAdapter that would wrap a fastadapter to just add the functionallity.
Seems that could be done manipulating the getItemCount and getItem methods for an Adapter:

https://stackoverflow.com/questions/31253555/how-do-i-create-a-circular-endless-recyclerview

Do you think it could be done that way using fastadapter?

**Comment by mikepenz** [comment]
@gpulido there is nothing preventing it, as basically everything is build upon the `RecyclerView.Adapter` interface. just add/remove the items, I don't see a problem with this. 
you can also just move them for example which would be even better

**Comment by gpulido** [comment]
@mikepenz I've tried to use that trick, for example with a list of just one element. And the adapter creates the viewholder for the element, but then it fills the screen with empty holders. Only when you scroll up a new element is shown.
Seems like it is no capable of reuse the holder until it disapears from the screen.

The test code that I use was just an extension of the GenericItemAdapter on which I override the getItemType and just "transforms" all positions:
```Java
    @Override
    public int getItemCount() {
        return Integer.MAX_VALUE;
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        super.onBindViewHolder(holder,  getAdjustedPosition(position));
    }

    @Override
    public int getItemViewType(int position) {
        return super.getItemViewType( getAdjustedPosition(position));
    }


    public int getAdjustedPosition(int position)
    {
        return position % super.getItemCount();
    }

```
This is what is happening:
![image](https://user-images.githubusercontent.com/1540727/29708741-135a2b7e-898a-11e7-82bd-6153c111edab.png?s=1)![image](https://user-images.githubusercontent.com/1540727/29708944-dc049686-898a-11e7-9a2a-816ea56c68b6.png)

**Comment by mikepenz** [comment]
sure it is not able to re-use a viewholder if it is still used. 

I also don't think that it's clever to have MAX_INT items. just listen in the scroll and move items from the top to the bottom and visa vers. (it should theoreitcally work) 

but the whole thing is not FastAdapter related. as it behaves and acts like a normal adapter.

**Comment by gpulido** [comment]
Thank for the tip, I know that at this point is not just "fasteradapter". Sorry for the inconvenience.

I will try to do as you say and add items dinamically on the onScroll event. Probably I will take a look to your EndlessScroll example.
My main concern is that the list represents a "live" classification on a tournament that is being shown at any time but that is being refreshed (the order of elements) several times. So any time the "classification" changes I'm clearing the adapter data and refilling, and I don't know how it would work with the scroll adding.
But as you say, this is not just fasteradapter.
Again thank you for your help.
You can close this issue if you want.
Gabriel

**Comment by MFlisar** [comment]
@gpulido 
Have you managed to implement this in meantime? If so, would you share your solution please? Thanks
