### ISSUE TITLE
2.6.3 is causing all items to reanimate (even with same IDs)

### ISSUE THREAD

**Issue by ncapdevi** [mikepenz/FastAdapter#529]
Trying to track down exactly what changed, but I can verify that it doesn't happen with 2.6.2, but does with 2.6.3, where when I set new data, all the items seem to renimate, and I believe are all being recreated. This is able to be replicated without making any changes in my codebase and just changing between version 2.6.2 to 2.6.3  Any ideas? I believe it's related to the fix in #451

**Comment by mikepenz** [comment]
@ncapdevi do you have stableIds? identifiers set for your items? 

The rv should normally be clever enough if the items do not change that it does not do an animation

**Comment by ncapdevi** [comment]
Yup, stableIDs set, correct identifiers for all the items. Has always worked  (have been using the library for quite some time now) before this previous update and definitely seems to be related to the changes in the previously mentioned commit, although I'm not really sure why that's the case. It seems to re-animate/layout all the items though.

**Comment by Rainer-Lang** [comment]
Same here. Maybe change in the support libs...

**Comment by mikepenz** [comment]
@ncapdevi @Rainer-Lang is this reproduceable int he sample?

**Comment by ncapdevi** [comment]
@mikepenz I Believe it would be replicated by calling `set()` with the same data set. This could be done, say, `onResume()`? If that doesn't work immediately, I'll trying replicating it by modifying some sample code in the repo.

**Comment by waninkoko** [comment]
I have observed the same here.

The commit that caused this behavior change is the following: https://github.com/mikepenz/FastAdapter/commit/f70f732582581a026b1b2097e0974e7565316ad6

**Comment by mikepenz** [comment]
@ncapdevi @waninkoko looking at the code seems super weird that this should change it. 

before it would have done a complete notify. Which I guess should have done the same

**Comment by mikepenz** [comment]
I see the re-animating also with the old variant. 

Perhaps a few more details would help:
- Is it the same list or did you create a new one
- Are those the same items (same reference) or just the same content but the item was generated new

Did you also try the `setNewList` call?

**Comment by waninkoko** [comment]
@mikepenz In my case I call ```set``` with a new list that contains new generated items that use the same IDs as the previous items.

I don't remember but I think I tried to call ```setNewList``` with no success.

**Comment by ncapdevi** [comment]
@mikepenz  Happy to add more info to this one if there's anything I can do to help. I've been sticking to 2.6.2 and accidentally updated to 2.6.3 and immediately noticed that it would happen.

**Comment by Rainer-Lang** [comment]
I'm even stuck to 2.6.2

**Comment by Rainer-Lang** [comment]
Other way around - does this also happen in v3?

**Comment by mikepenz** [comment]
v3 will allow providing custom logic on how the notify happens. this will allow the new and the old behaviour:
https://github.com/mikepenz/FastAdapter/pull/443/commits/278c590f8a4f11632bc414af94ccb64d14ab5fe4

**Comment by mikepenz** [comment]
for v2.x releases please stay on v2.6.2 if it is causing troubles
with v3.x we will over a solution to adjust this behaviour.

**Comment by ncapdevi** [comment]
Sounds good, will try to get a version working with 3.0 shortly and let you know. Thanks.

**Comment by ncapdevi** [comment]
@mikepenz  Was finally able to get around to testing a branch with 3.0.1 and using 
 `set` with  `IAdapterNotifier.LEGACY_DEFAULT` does seem to work properly. Thanks for the help!
