### ISSUE TITLE
Expandable RecyclerView

### ISSUE THREAD

**Issue by brittonjg** [mikepenz/FastAdapter#53]
Hi,

Thanks for the great library.

I am trying to implement the Expandable view, but within a fragment instead of an Activity. I had the expansion and contraction working without issue within an Activity, but when moving it to a Fragment it stops expanding.

On some tests, I set the expansion to true initially and that has the list expanded, but upon setting it back to false initially. The list returns to not expanding.

Have you ever implemented this sample within an Activity Fragment model? I have a feeling it is to do with the Fragment not expanding, but I wanted to see what others have experienced.

**Comment by mikepenz** [comment]
@brittonjg I am sure it has nothing to do with the `Fragment` I assume your listener misses the required call for the expandable function. I will loook if I can simplify this step, so the listener does not have to handle it.

**Comment by brittonjg** [comment]
Unbelievable mistake on my part. I was just missing - `fastItemAdapter.toggleExpandable(position);`

I'd just been looking in the wrong place for a couple of hours. Is that the missing bit you were talking about?

**Comment by mikepenz** [comment]
@brittonjg yes. this will be done by the lib in the next version

**Comment by brittonjg** [comment]
@mikepenz Awesome! Thanks for your quick reply and work. Much appreciated.

**Comment by brittonjg** [comment]
@mikepenz Update looks good. Only issue is your arrow starts down in the example, when I guess it should start up and then rotate as necessary.

Thanks for the super quick change though!

**Comment by mikepenz** [comment]
@brittonjg great :). So it is correct :D

**Comment by mikepenz** [comment]
@brittonjg with v1.2.0 it is now even cleaner to have the animation. See the latest changes. With the listener within an item you can now move the animation to the item itself.

**Comment by brittonjg** [comment]
You're totally correct! Ignore my inaccuracies :D

Nice update, the endless scroll is another great addition too :+1:
