### ISSUE TITLE
refresh a single view without affecting other.

### ISSUE THREAD

**Issue by rraikarnvi** [mikepenz/FastAdapter#530]
i have a image view with count number text and a +- when incremented or decremented wht whole item view is refreshed. this is noticed as the image gets flickered. Is there a way to target a single view and not refresh item.?

**Comment by mikepenz** [comment]
@rraikarnvi that's the animator of the `RecyclerView` which is automatically doing this with the `notifyItemChanged`. 

You can either remove the animator, or the better solution is you use the `payload` when notifying, so you can have just a partial update of an element
