### ISSUE TITLE
width="match_parent" not working

### ISSUE THREAD

**Issue by shymmq** [mikepenz/FastAdapter#533]
I have an expandable list in which parent layout looks like this:
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="56dp"
    android:orientation="vertical">

    <TextView
        android:id="@+id/grade_header_item_title"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center_vertical"
        android:paddingStart="16dp"
        android:textColor="?android:attr/textColorPrimary" />
</LinearLayout>
```
it seems correct in Android Studio, but on device it renders like this:
![image](https://user-images.githubusercontent.com/8517017/29723374-a7d539b2-89c4-11e7-9675-8cc68f659c16.png)

also when I expand any of the items everything starts working as expected:
![image](https://user-images.githubusercontent.com/8517017/29723363-9d9e125c-89c4-11e7-911c-9d805a6bbba3.png)
A quick google search leads me to [this](https://stackoverflow.com/questions/24503760/cardview-layout-width-match-parent-does-not-match-parent-recyclerview-width) but unfortunately I can't do anything about it because inflating the views is handled by the library.
Any help would be appreciated.

**Comment by FabianTerhorst** [comment]
Firstawall you could change how the inflate works by simply overriding ```getViewHolder(Viewgroup parent)```, but thats not the topic in this question because the library already uses the correct way to inflate the item layout in the implementation. Which layout manager are you using?

**Comment by shymmq** [comment]
I'm using LinearLayoutManager

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FabianTerhorst** [comment]
I don´t think this is fast adapter related. You would get the same behavior when using just the recyclerview default adapter.

**Comment by mikepenz** [comment]
Yes that's the same I think. 

I think it's just how the RV + the LM lays out the views. That's done by those classes not by the adapter. 

and it is also unrelated to the expandable thing.

**Comment by shymmq** [comment]
I got it to work by changing LinearLayout to RelativeLayout, I wonder why that was the problem.

**Comment by FabianTerhorst** [comment]
You can take a look at ```https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/res/layout/single_line_item.xml``` for an working example.
