### ISSUE TITLE
Remove an item from view holder

### ISSUE THREAD

**Issue by siyanew** [mikepenz/FastAdapter#534]
I have a button in my viewHolder and I want when someone click on this button, the item remove from fast adapter. How can I do that ? Actually I think there must be a bridge between my fragment and viewHolder !

**Comment by mikepenz** [comment]
@siyanew please try to read up more infos on how the `RecyclerView` works. 

a `ViewHolder` is re-used. which means you can not directly access it. if you want to remove an item in the list, just remove it from the `adapter` with the `remove` method. 

If you want to update the current displayed things of a `ViewHolder` change the item, and notify the adapter that the item was modified.
