### ISSUE TITLE
how to control fast adapter to single scroll(flip) 

### ISSUE THREAD

**Issue by sagrawal2002** [mikepenz/FastAdapter#535]
Hi,
I want to use fast adapter on my news app. but my requirement is one news scroll (flip) at once (i don't want any fancy animations) . one news item will have (image+text) and like, share and save offline option. i want user can scroll one item at a time right to left. so that i can add admob add after each 8-10 slide my biggest problem is i can't user admob industrial ads if recycler view has infinite scroll as i can't count news items. if possible can i control scroll to one at a time scroll. 

Can you please suugest starting point .

Thanks
Saurabh

**Comment by mikepenz** [comment]
@sagrawal2002 that's nothing related to the adapter. orientation etc is controlled by the LayoutManager

**Comment by mikepenz** [comment]
hmmm I think you may look for the `SnapHelper`
https://developer.android.com/reference/android/support/v7/widget/SnapHelper.html

It's unrelated to the `Adapter` the adapter only provides the items. 

Everything else like scroll behaviour, snapping, animations, is all controlled by the RV which is not scope of this lib

**Comment by sagrawal2002** [comment]
Hi Mike,
Thanks for reopening this query again   you are very helpful. Sorry for asking too much but i am stuck on this from 15-20 days and i don't have solution for this. so can you please help me on this. i am new in android. below is issue.

In  Sampleactivity.java we have added below code to fetch data from parse  (we have setup parse open source on AWS server):

new Handler().postDelayed(new Runnable() {
        @Override
        public void run() {
            //add some dummy data
            final List<SimpleImageItem> list = new ArrayList<SimpleImageItem>();

            ParseQuery<ParseObject> query = ParseQuery.getQuery("Photo");
            query.findInBackground(new FindCallback<ParseObject>() {
                @Override
                public void done(List<ParseObject> lists, ParseException e) {
                    if (lists!= null && lists.size() > 0) {
                        for (int i = 0; i < lists.size(); i++) {
                            String url = lists.get(i).getParseFile("image").getUrl();
                            SimpleImageItem sii = new SimpleImageItem().withIdentifier(1L).withName("Yang Zhuo Yong Cuo, Tibet China").withDescription("#100063").withImage(url);
                            list.add(sii);
                        }
                    }
                    mItemAdapter.add(list);
                }
            });
            //mItemAdapter.add(ImageDummyData.getSimpleImageItems());
            //restore selections (this has to be done after the items were added
            mFastAdapter.withSavedInstanceState(savedInstanceState);
        }
    }, 50);
}


But the data we are fetching is in recycler vertical view using your adapter in sample activity. Can we view the same data in horizontal slide view so that we can view only one data(post) in one screen and change the data on slide, or in other way I want to ask can we use recyclerview in horizontal slide view not horizontal scroll view. From the below code we are getting scroll horizontal recyclerview but not horizontal slide view.



public class PostQueryAdapterHorizontal extends RecyclerView.Adapter<PostViewHolder> {
    private final String TAG = "PostQueryAdapterHorizontal";
    private List<String> mPostPaths;
    private OnSetupViewListener mOnSetupViewListener;

    public PostQueryAdapterHorizontal(List<String> paths, OnSetupViewListener onSetupViewListener) {
        if (paths == null || paths.isEmpty()) {
            mPostPaths = new ArrayList<>();
        } else {
            mPostPaths = paths;
        }

        mOnSetupViewListener = onSetupViewListener;
    }

    @Override
    public PostViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        // create a new view
        View v = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.post_item_horizontal, parent, false);
        return new PostViewHolder(v);
    }


Below is the screen short to show what we want.

![screenshot](https://user-images.githubusercontent.com/2997551/29968630-34e26d3c-8f3a-11e7-8814-92bfaa221a97.png)



one more query we want to save all data from parse server to local DB and from locale db we want to show the data. can you please help us how to save data locally using your adapter on relem DB.

**Comment by mikepenz** [comment]
@sagrawal2002 this issue is not related to this library. (as mentioned in my earlier answer) please had to StackOverflow or to a different place to get help. 

the `Adapter` (so here FastAdapter)  is not responsible on how the items are displayed in the list (horizontal, vertical, grid, ...) that's the thing of the LayoutManager. If you want to have a sticky effect the SnapHelper could help (but also not related to this lib) 

Saving to the db is definitely not related to this library.
