### ISSUE TITLE
Generic FastItemAdapter and Kotlin

### ISSUE THREAD

**Issue by guuilp** [mikepenz/FastAdapter#537]
I'm trying to migrate some codes to Kotlin, but I got stuck when it get to the fast adapter.

Sometimes I use the generic FastItemAdapter, to accept any kind of FastAdapter Item. When I tried to do this: val fastAdapter = FastItemAdapter()
I received this error: "Type instance failed: Not enough information to infer parameter Item".

So I tried: var fastAdapter = FastItemAdapter<*>()
And I received this error: Projections are not allowed on type arguments of function or properties

Does anyone already handled this problem and could help me?

**Comment by mikepenz** [comment]
Try to set `IItem` as generic type

**Comment by guuilp** [comment]
var fastAdapter = FastItemAdapter<IItem>()

Error:
2 type arguments expected for interface lItem<T: Any!, VH: RecyclerView.ViewHolder!> : Ildentifyable<T!> defined in com.mikepenz.fastadapter in file lItem.class

**Comment by guuilp** [comment]
`var fastAdapter = FastItemAdapter<IItem<*, *>>()`

This way worked, but I don't know if it is right

**Comment by mikepenz** [comment]
I think it is. How else would you define that the type does not matter.

**Comment by guuilp** [comment]
Thanks @mikepenz !
