### ISSUE TITLE
sticky header item

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#539]
i use this pattern to generate GenericFastItemAdapter :

```java
GenericFastItemAdapter myAdapter = new GenericFastItemAdapter(o -> {
	if(o instanceof Simple) {
		return new SimpleItem((Simple) o);
	} else if(o instanceof Header) {
		return new HeaderItem((Header) o);
	}
	return null;
});
```

in this pattern, how can sticky all `Header` objects ( or all `HeaderItem` objects ) ?

i see example module of library, but this sample must have separate `onCreateHeaderViewHolder` and `onBindHeaderViewHolder` for each header type. 

i want header items like of other items have own `GenericAbstractItem` because when i have multiple sticky type ( for example `Header1`, `Header2`, `Header3` ... ) i should add it in custom `AbstractAdapter` that caused hard to handle it

thanks

**Comment by mikepenz** [comment]
@DJafari sticky headers are not part (and most likely won't be part) of the core library. 
Sticky headers showcased in the sample with some external sticky header libs.

**Comment by DJafari** [comment]
@mikepenz it's mean can not possible handle it with fast adapter ? even in v3 ?

**Comment by mikepenz** [comment]
@DJafari it it is compatible, and you can make it to support FastAdapter item's but it is a different lib.

**Comment by DJafari** [comment]
can you tell me how can i achieve to this ?
i have want add object to adapter and sticky automatically, without define `onCreateHeaderViewHolder` and `onBindHeaderViewHolder` for each sticky header type
