### ISSUE TITLE
Pagination feature

### ISSUE THREAD

**Issue by jlelse** [mikepenz/FastAdapter#54]
Could you add something like a "pagination listener",something that invokes a method when bottom or for example 3 items before bottom is reached?

**Comment by mikepenz** [comment]
@jlelse please check the new sample added by @FabianTerhorst https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/EndlessScrollListActivity.java

**Comment by Rainer-Lang** [comment]
@jlelse Does the sample of @FabianTerhorst helped you?

**Comment by jlelse** [comment]
@Rainer-Lang I didn't use it

**Comment by Rainer-Lang** [comment]
@jlelse Could I ask you how you solved it?

**Comment by jlelse** [comment]
@Rainer-Lang I did it without FastAdapter
