### ISSUE TITLE
Animation/Transition in Sticky Headers?

### ISSUE THREAD

**Issue by bernaferrari** [mikepenz/FastAdapter#541]
Hi!

I love this library and I put StickyHeaders all over my apps. However, in certain places, I want to reorder my RecyclerView and would love to see animations. I'm not sure why, but they are disabled when I use StickyHeaders.

I am initiating like this:
```
        val stickyHeaderAdapter = StickyHeaders<Um_Encontro_FA>()
        recyclerView.adapter = stickyHeaderAdapter.wrap(fastFA)

        val decoration = StickyRecyclerHeadersDecoration(stickyHeaderAdapter)
        recyclerView.addItemDecoration(decoration)

        recyclerView.itemAnimator = DefaultItemAnimator()
```

If it is not a bug in my code, this is probably something expected. So, I would love to include the non-sticky-header, but I haven't found a lot of documentation, or even sample code, even at version 3.

So, my basic question is: how do I go from sticky to non sticky header in the most simple way?

**Comment by mikepenz** [comment]
@bernaferrari please refer to the library providing sticky headers

**Comment by bernaferrari** [comment]
I agree with you.. My question was really, is there an easy way to convert from sticky to non sticky header?

**Comment by mikepenz** [comment]
if you don'T want to sticky header you just need to add the items in-between. you can also use the `HeaderHelper` https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/HeaderHelper.java 

(basically headerItem, normalItem, normalItem, headerItem ,... )
