### ISSUE TITLE
Generic Adapter using kotlin

### ISSUE THREAD

**Issue by markuspaschi** [mikepenz/FastAdapter#543]
Love your library so far, a small question:

I'm trying to implement a generic Adapter. I got several Generic Items and would love to combine them.
Imagine if HeaderItem is a generic Item too. / or just a normal Header Item
What i tried so far ist this:

        val itemAdapter = GenericItemAdapter(Function<Any, Any> { o ->
            //depending on your logic you can now decide which model maps to which item.
            if (o is Cantonment) {
                GenericCantonmentList(o)
            } else if (o is HeaderItem) {
                HeaderItem()
            } else {
                throw IllegalArgumentException("The passed model can't be created within this Factory")
            }
        })

But I'm missing something here is guess: 
```
Type parameter bound for Item in constructor GenericItemAdapter<Model : Any!, Item : IGenericItem<out Model!, *, *>!>(itemFactory: Function<Model!, Item!>!)
 is not satisfied: inferred type Any! is not a subtype of IGenericItem<out Any!, *, *>!

```
Help is appreciated :)

**Comment by mikepenz** [comment]
@markuspaschi if you have a `GenericItemAdapter` you should use the `model` methods. 
If you want to work only with items then use the `ItemAdapter`
