### ISSUE TITLE
notifyAdapterItemChanged (with payload) not working after itemAdapter.withComparator

### ISSUE THREAD

**Issue by guuilp** [mikepenz/FastAdapter#544]
This is my code: 

```
radioGroup.setOnClickedButtonListener(RadioRealButtonGroup.OnClickedButtonListener {
            button, position ->
            when(button){
                ratingButton -> {
                    playersInFastAdapter.itemAdapter.withComparator(compareBy({ it.player.overallScorePosition }), true)

                    for(i in 0 .. playersInFastAdapter.adapterItemCount){
                        playersInFastAdapter.notifyAdapterItemChanged(i, App.PAYLOAD_RANKING_RATING_LIST)
                    }
                }
                goalsButton -> {
                    playersInFastAdapter.itemAdapter.withComparator(compareBy({ it.player.goalsPosition }), true)

                    for (i in 0..playersInFastAdapter.adapterItemCount) {
                        playersInFastAdapter.notifyAdapterItemChanged(i, App.PAYLOAD_RANKING_GOALS_LIST)
                    }
                }
            }
        })
```

If I comment this line: `playersInFastAdapter.itemAdapter.withComparator(compareBy({ it.player.overallScorePosition }), true)`, the notifyAdapterItemChanged with payload (inside for) works fine.

Any idea of what I may be missing?

**Comment by mikepenz** [comment]
@guuilp well `withComparator` sorts your items when added, and triggers a complete notify. The `Adapter` + `RecyclerView` of Android is clever enough to not execute the single notifies after this, because it's not necessary

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L103

**Comment by guuilp** [comment]
Is there any way of know when this complete notify is triggered?

**Comment by mikepenz** [comment]
well you trigger it with the sort now. 

no listener though I think

**Comment by guuilp** [comment]
This is a necessity of my scenario... That's because, first I need to change the order of items on recycler view and after that, change the layout of my items.

**Comment by mikepenz** [comment]
well why not change the layout when the full notify is triggered?

**Comment by guuilp** [comment]
You mean after I change the order, using the withComparator? If there's any way of knowing, inside my FastAdapterItem, when the notify came from a withComparator, it may be solve my problem.

**Comment by mikepenz** [comment]
well either you sort your list from the beginning and then you just notify. 
if you have to change the comparator, you can somewhere define the type of the items. 
or you do the sorting manually

**Comment by guuilp** [comment]
Explaining a little better my scenario:

I have four buttons on the screen. When the user clicks in one them, it changes the order of the list and should change (just a textview value, actually) the items layout.

Now I'm sorting when the user clicks in one of the four buttons, as I showed in the first code block of this issue. The sorting with Fast Adapter has a smooth animation that I'd like to keep.

If I sort the list from the begining, I should have four lists actually, already sorted, and then change them in the fast adapter (maybe a clear and then addAll). This would cause a blink effect, and not a reordering, talking about animation.

If sorting manually is the only option, could you give me some advice of how could I achieve that, please?

**Comment by mikepenz** [comment]
Well or a better method. you extend the `ItemAdapter` (as the usecase you have is a bit special, usually you want it to notify the whole list) and override the `withComparator` method, and simply do not call the `notifyAdapterDataSetChanged()`

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L107

**Comment by guuilp** [comment]
Wouldn't this be the same as sorting manually? Like:

```
                    Collections.sort(playersInFastAdapter.adapterItems, compareBy{ it.player.overallScorePosition })

                    for(i in 0 .. playersInFastAdapter.adapterItemCount){
                        playersInFastAdapter.notifyAdapterItemChanged(i, App.PAYLOAD_RANKING_RATING_LIST)
                    }
```

**Comment by mikepenz** [comment]
@guuilp well you could keep the same mechanisms but only notify then manually. yeah.

**Comment by guuilp** [comment]
@mikepenz I thanks a lot your effort to help me, but I think my case it's too specific and no options seems to work. I don't blame you, it's my awkward usecase. I'm going to follow with fast adapter.clear and fastAdapter.add on the already sorted list... Unfortunately is not the most beautiful animation, but works. Anyway, thanks again for your library, it's awesome!

**Comment by mikepenz** [comment]
@guuilp in addition you might just want to disable the animation while doing this? 

You might also just want to use a field which is accessible from the item from the adapter or so, defining how it should look like. so you handle it when the complete list is re-drawn
