### ISSUE TITLE
Item clipping

### ISSUE THREAD

**Issue by kolorszczak** [mikepenz/FastAdapter#545]
Hello!
In my app I have a component with a RecyclerView. It's a horizontally scrolling list with a charts (lines) showing daily progress of a user:
![list](https://user-images.githubusercontent.com/15268028/31007031-5efd54ee-a4ff-11e7-8fb8-efed2b44db9f.PNG)

If user click on single char it becomes orange (selected):
![listselected](https://user-images.githubusercontent.com/15268028/31007168-dd7a3d96-a4ff-11e7-9f43-2e5e7cc3a106.PNG)

As you can see label on the top of chart is wider that chart itselft. If user click on chart - label's width and height is animated. 

If i set item width to wrap_content then while animation the width of whole item is wrapping to label width like this:
![wrap](https://user-images.githubusercontent.com/15268028/31008360-2295d60c-a504-11e7-9d70-d8d86af84a05.gif)

On the other hand if i set item width to specific size then during the animation when label comes to item edges it looks like its covered and whole label finnaly appears when animations is done. It looks like this:
![stala](https://user-images.githubusercontent.com/15268028/31008426-61423fbc-a504-11e7-8cf4-d706df2bce4b.gif)

I have set 

```
android:clipChildren="false"
android:clipToPadding="false"
```
in label item to parent layout, label text view - also to the recycler view.

I am using ValueAnimator to animate width layout params.

```
private static ValueAnimator setupWidthAnimator(View viewToAnimate, int finalWidth, int duration) {
        ValueAnimator animator = ValueAnimator.ofInt(viewToAnimate.getMeasuredWidth(), finalWidth);
        animator.addUpdateListener(valueAnimator -> {
            int val = (Integer) valueAnimator.getAnimatedValue();
            ViewGroup.LayoutParams layoutParams = viewToAnimate.getLayoutParams();
            layoutParams.width = val;
            viewToAnimate.setLayoutParams(layoutParams);
        });
        animator.setDuration(duration);

        return animator;
    }
```

**Comment by FabianTerhorst** [comment]
I don´t see any fastadapter related issue here.

**Comment by mikepenz** [comment]
@kolorszczak as @FabianTerhorst already pointed out. it's not an adapter issue. the adapter is only providing the data + the view for a single item. the whole drawing is handled by the layoutmanager + rv
