### ISSUE TITLE
AbstractAdapter hasStableIDs

### ISSUE THREAD

**Issue by ncapdevi** [mikepenz/FastAdapter#546]
Maybe I'm misunderstanding something, but I've restructured my code a bit to have my adapter extend the `ItemAdapter`, and I'm no longer getting animations.  Following the code, when you call `setHasStableIDs` it forwards the call onto the FastAdapter, but when you cal `hasStableIDs()` you will get back false, since it's not forwarding the call back from the fastAdapter, is this correct? If it isn't correct, is that what's causing the loss of my animations  using the `ItemAdapter`?

**Comment by mikepenz** [comment]
@ncapdevi I am not 100% sure what you mean. animations work fine in the sample. anything else which might prevent it in your case?

**Comment by mikepenz** [comment]
@ncapdevi can you please report back. close for now
