### ISSUE TITLE
When to extend FastItemAdapter vs ItemAdapter

### ISSUE THREAD

**Issue by ncapdevi** [mikepenz/FastAdapter#547]
I'm just looking for some general clarification of when to extend/use FastItemAdapter vs ItemAdapter. The documentation is a bit lacking and it's a touch confusing. To add to that specific documented clarification of `FastAdapter` vs `AbstractAdapter`  The general use cases are confusing

**Comment by mikepenz** [comment]
@ncapdevi there will be a huge refactor with v3 of this. 

regarding `FastItemAdapter` vs `ItemAdapter` 

`FastItemAdapter` == `ItemAdapter` + `FastAdapter` wrapped in one

**Comment by Shakezulla57** [comment]
@mikepenz Do you have your own rule for when you'd use a `FastAdapter` and an `ItemAdapter` versus when you'd use a single `FastItemAdapter`?

**Comment by mikepenz** [comment]
@Shakezulla57 in general. as soon as you use multiple sub adapters I would say don'T use a `FastItemAdapter`

**Comment by ncapdevi** [comment]
That general rule was roughly was I was looking for, thanks!
