### ISSUE TITLE
withOnClickListener example code doesn't compile

### ISSUE THREAD

**Issue by JuhaniLehtimaeki** [mikepenz/FastAdapter#548]
Hey, the following code in the docs does not compile

```
fastAdapter.withSelectable(true);
fastAdapter.withOnClickListener(new FastAdapter.OnClickListener<Item>() {
    @Override
    public boolean onClick(View v, IAdapter<Item> adapter, Item item, int position) {
       // Handle click here
	return true;
    }
});
```
FastAdapter.OnClickListener does not exist.

**Comment by JuhaniLehtimaeki** [comment]
Ah. Nevermind. Sorry. My mistake in migrating to 3.0.

**Comment by bernaferrari** [comment]
Could you give more information?

**Comment by mikepenz** [comment]
@JuhaniLehtimaeki what was causing the issue. 
It would be a great help so we can improve the migration guide :) 

(The v3 release was a work over the last few months, so some migration steps might got lost in my head while writing them yesterday)
