### ISSUE TITLE
How to use ModelAdapter with EndlessScroller like FooterAdapter by v3.0.0

### ISSUE THREAD

**Issue by jp1017** [mikepenz/FastAdapter#549]

**Comment by mikepenz** [comment]
@jp1017 just use multiple `ItemAdapter` 

```java
ItemAdapter header = ..
ItemAdapter items = 
ItemAdapter footer = 
FastAdapter fastAdapter = FastAdapter.with(header, items, footer);
```

and the you just use the `footer` one then. (the order on which the adapters are passed to the `FastAdapter` defines the order of it's items)

**Comment by jp1017** [comment]
but multi generics?

    private FastAdapter<TradeItem> mFastAdapter;
    private ModelAdapter<TradeEntity, TradeItem> mModelAdapter;
    private ItemAdapter<ProgressItem> mFooterAdapter;

init:
        mFooterAdapter = ItemAdapter.items();
        mModelAdapter = new ModelAdapter<>(new IInterceptor<TradeEntity, TradeItem>() {
            @Override
            public TradeItem intercept(TradeEntity tradeEntity) {
                return new TradeItem(tradeEntity);
            }
        });
        mFastAdapter = FastAdapter.with(mModelAdapter, mFooterAdapter);

**Comment by mikepenz** [comment]
@jp1017 your `FastAdapter` shouldn't use `TradeItem` if you have a different type somewhere anyways. The `FastAdapter` should always work with the parent type which is in your case I guess `IItem`

**Comment by jp1017** [comment]
Sorry, the same issue. :cry:

**Comment by mikepenz** [comment]
@jp1017 what's the issue?

**Comment by jp1017** [comment]
`FastAdapter.with(mModelAdapter, mFooterAdapter);` can't find the method.

**Comment by mikepenz** [comment]
@jp1017 oops sorry. it is:

```java
FastAdapter.with(Arrays.asList(mModelAdapter, mFooterAdapter));
```

**Comment by jp1017** [comment]
Yes, you make it. but another issue: 

```
Caused by: java.lang.RuntimeException: please provide a reverseInterceptor
at com.mikepenz.fastadapter.adapters.ModelAdapter.getModels(ModelAdapter.java:206)
```

when add the model: 

```
mModelAdapter.add(mModelAdapter.getModels().size(), new TradeEntity());
```

**Comment by mikepenz** [comment]
@jp1017 well for `getModels()` a reverseInterceptor is needed. 

but as you just need the size in your case. you should simply use `getAdapterItemCount()`

**Comment by jp1017** [comment]
Well done. Thank you.! :+1: :smile:
