### ISSUE TITLE
[Support] ModelAdapter & DiffUtil 

### ISSUE THREAD

**Issue by 1110101** [mikepenz/FastAdapter#554]
I'm trying to use [DiffUtil](https://developer.android.com/reference/android/support/v7/util/DiffUtil.html) to calculate diffs between a List from Network and the Adaptermodel. 
To add more detail, the Network API is very limited. I can't fetch updates/changes, just the whole list.

It looks like this:

    // Initialization
    mModelAdapter = new ModelAdapter<>(FailureMessageItem::new);
    mFastAdapter = FastAdapter.with(mModelAdapter);

    // [..]

    DiffUtil.DiffResult result = DiffUtil.calculateDiff(new MyDiffCallback(newlist, mModelAdapter.getModels()), false);

        mModelAdapter.clear();
        mModelAdapter.set(newlist);

        result.dispatchUpdatesTo(new ListUpdateCallback() {
            @Override
            public void onInserted(int position, int count) {
                mModelAdapter.getFastAdapter().notifyItemRangeInserted(position, count);
            }

            @Override
            public void onRemoved(int position, int count) {
                mModelAdapter.getFastAdapter().notifyItemRangeRemoved(position, count);
            }

            @Override
            public void onMoved(int fromPosition, int toPosition) {
                mModelAdapter.getFastAdapter().notifyItemMoved(fromPosition, toPosition);
            }

            @Override
            public void onChanged(int position, int count, Object payload) {
                mModelAdapter.getFastAdapter().notifyItemRangeChanged(position, count, payload);
            }
        });`

Unfortunately modelAdapter.set(List) includes adapter notifications, so i've tried to include a noop adapterNotifier:

    mModelAdapter.set(newlist, false, (fastAdapter, newItemsCount, previousItemsCount, itemsBeforeThisAdapter) -> false);

With above line, no updates at all happen, even if `result.dispatchUpdatesTo()` runs.

Do you have any idea how to handle this usecase?

**Comment by FabianTerhorst** [comment]
You can try to use https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/commons/utils/FastAdapterDiffUtil.java

**Comment by 1110101** [comment]
Unfortunately FastAdapterDiffUtil does not work with ModelAdapter.

**Comment by mikepenz** [comment]
The next version will also support the `ModelAdapter`

**Comment by 1110101** [comment]
Thanks for your effort mike.
I've copied FastAdapterDiffUtil and tried it out.
Unfortunately it's not working yet (well, at least in my usecase). 
I still need to set the new model somehow and 
`mModelAdapter.set(newlist, false, (fastAdapter, newItemsCount, previousItemsCount, itemsBeforeThisAdapter) -> false);` still does nothing and `mModelAdapter.set(newlist)` does trigger a full refresh.
