### ISSUE TITLE
Another Proguard error with 3.0.1

### ISSUE THREAD

**Issue by engi** [mikepenz/FastAdapter#556]
My test is done with Android Studio 3.0, from a new virgin project.

Graddle module :

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
        }
    }

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:recyclerview-v7:26.1.0'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'

    implementation 'com.mikepenz:fastadapter:3.0.1@aar'
    implementation 'com.mikepenz:fastadapter-commons:3.0.1@aar'
}

In debug release, all is ok, but release give me this messages :

`Information:Gradle tasks [:app:assembleRelease]
Warning:com.mikepenz.fastadapter.AbstractAdapter: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.FastAdapter: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.IAdapterExtension: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.IInterceptor: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.IItemAdapter$Predicate: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.ISelectionListener: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.adapters.ItemFilter: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.adapters.ModelAdapter: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.items.AbstractItem: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.items.package-info: can't find referenced class javax.annotation.ParametersAreNonnullByDefault
Warning:com.mikepenz.fastadapter.listeners.ClickEventHook: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.listeners.CustomEventHook: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.listeners.EventHook: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.listeners.ItemFilterListener: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.listeners.LongClickEventHook: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.listeners.TouchEventHook: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.listeners.package-info: can't find referenced class javax.annotation.ParametersAreNonnullByDefault
Warning:com.mikepenz.fastadapter.package-info: can't find referenced class javax.annotation.ParametersAreNonnullByDefault
Warning:com.mikepenz.fastadapter.select.SelectExtension: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.select.package-info: can't find referenced class javax.annotation.ParametersAreNonnullByDefault
Warning:com.mikepenz.fastadapter.utils.EventHookUtil: can't find referenced class javax.annotation.Nullable
Warning:com.mikepenz.fastadapter.utils.package-info: can't find referenced class javax.annotation.ParametersAreNonnullByDefault
Warning:there were 50 unresolved references to classes or interfaces.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details
Information:BUILD FAILED in 2s
Information:1 error
Information:24 warnings
Information:See complete output in console`

**Comment by engi** [comment]
[MyApplication.zip](https://github.com/mikepenz/FastAdapter/files/1451542/MyApplication.zip)

**Comment by FabianTerhorst** [comment]
You have to add ```
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.ParametersAreNonnullByDefault
```
to your proguard file

**Comment by engi** [comment]
Well, it is ok when I add this two lines, but is it normal to have all this warnings ?
