### ISSUE TITLE
problem with FastAdapter

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#557]
why all of items is clickable ?
i dont define any ClickListener in adapter, but Items have a clickable feedback ( vibrate and touch sound )

i think when there is no ClickListener in adapter, why FastAdapter set a ClickListener for items ?

**Comment by DJafari** [comment]
@mikepenz : this is correct ?

```

**Comment by DJafari** [comment]
@mikepenz : this is correct :

```
public class NewsDividerItem extends ModelAbstractItem<NewsDivider, NewsDividerItem, NewsDividerItem.ViewHolder> {
	@Override
    public boolean isEnabled() {
        return false;
    }
}
```

if correct, always item is clickable yet

**Comment by DJafari** [comment]
@mikepenz : this trick is work :

```java
@Override
public void bindView(ViewHolder holder, List<Object> payloads) {
    super.bindView(holder, payloads);
    holder.itemView.setOnClickListener(null);
}
```

but it's to better if possible solve this problem without this hardcode

**Comment by mikepenz** [comment]
Well basically adding a boolean to disable it would work: 
not executing this:
https://github.com/mikepenz/FastAdapter/blob/b77477ec100e27e31ffba16dade9fa5031e5cb6c/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L641

it is just important to note that only a complete recreation of the viewholders would attach the listeners then

**Comment by DJafari** [comment]
@mikepenz yes you say right, i use it in simple items such headers and ... that there is no click listener
