### ISSUE TITLE
Bad support for Kotlin

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#558]
Maybe I'm doing this wrong, but with the generic typings, creating a FastAdapter is abysmal:

```
val fulladapter = FastAdapter.with<IItem<*,*>,IAdapter<out IItem<*,*>>>(listOf(adapterWrapper, adapter))
```

Kotlin requires defined types, so we can't just ignore generics like in Java.

Consider making another call that simply converts it to a recyclerview's adapter?

Half the time, the only thing we need it to help assign it to a recyclerview.

There are ways of doing this natively in kotlin to help wrap it as well. For now I have the following global function:

```
fun fastAdapter(vararg adapter: IAdapter<*>) =
        FastAdapter.with<IItem<*, *>, IAdapter<out IItem<*, *>>>(adapter.toList())
```

**Comment by FabianTerhorst** [comment]
You should always specify an type, java just doesn´t require it. Im using it in a few kotlin projects as well, you just have to specify the types correctly and build your items and models  object oriented.

**Comment by AllanWang** [comment]
I guess what I mean is that if two adapters have separate item types, kotlin can't seem to infer that the fast adapter has a generic type iitem. Part of the reason may be from not using `? extends IItem` which represents out

**Comment by AllanWang** [comment]
That is correct. Technically, all the adapters should implement `out`, but a lot of times we can avoid that if we have just one iitem class per adapter. Why not also allow for outer types in the static creator? See this:

```java
public class Test {

    public static <T extends IItem> FastAdapter<T> with(Collection<IAdapter<? extends T>> adapters) {
        return FastAdapter.with(adapters);
    }
}
```

and the comparison

```
val adapter1: IAdapter<CardIItem> = ItemAdapter()
val adapter2: IAdapter<HeaderIItem> = ItemAdapter()

val fast1 = FastAdapter.with<IItem<*, *>, IAdapter<out IItem<*, *>>>(listOf(adapter1, adapter2))
val fast2 = Test.with(listOf(adapter1, adapter2))
```

**Comment by AllanWang** [comment]
To add onto this, why require a specific type for the `IAdapter`? Wouldn't another extension suffice?

```
public static <T extends IItem> FastAdapter<T> with(Collection<? extends IAdapter<? extends T>> adapters) {
        return FastAdapter.with(adapters);
    }
```

**Comment by mikepenz** [comment]
Any update to this topic?
The type for the `IAdapter` is to have proper typesafety through the whole code and all implementations

You can allways fallback to the interface which is the smallest equal thing for all possible items

**Comment by AllanWang** [comment]
This is what I've noticed. Feel free to correct me where I'm wrong, as the use of generics here is much more extensive than what I usually do.

For a lot of the methods, we take in `Item extends IItem` for the item type and some `A extends IAdapter` for the adapter type. The goal is that any adapter we have is an `IAdapter`, and our output wraps around `Item`. 

1. This isn't type safe, because there is no check between my adapter type and the type I actually want. I can easily assign `Item` to be of type `CheckboxIItem` and pass in whatever I want as the content.

2. The use of `A` doesn't really solve anything. All we care about is that we are taking in `IAdapter`. `Collections<IAdapter>` can already take in anything that extends that when you are adding another collection. In other words:

```Java
public static <Item extends IItem, A extends IAdapter> FastAdapter<Item> with(@Nullable Collection<A> adapters)
```

should not be any different from

```Java
public static <Item extends IItem> FastAdapter<Item> with(@Nullable Collection<IAdapter> adapters)
```

This is also why Kotlin has a very hard time inferring types. In reality, things should be

```Java
public static <Item extends IItem> FastAdapter<Item> with(@Nullable Collection<IAdapter<? extends Item>> adapters)
```

To ensure that all adapters actually provide the proper items. 

I tried to address this myself, but unfortunately, this would result in too many changes. The issue is that a lot of interactions is under the assumption that all adapters are exactly of type `IAdapter<T>`. (A `FastAdapter<IItem>` should not be able to hold a `FastAdapter<CheckboxIItem>`).

Example of type erasure:

* Generate a `FastAdapter<IItem>` and take in `IAdapter<CheckboxIItem>`. 
* Return the first adapter in the `FastAdapter`, which would be `IAdapter<IItem>`.
* Wrap that adapter in a `FastItemAdapter`, leading to `FastItemAdapter<IItem>`.
* Add any other adapter you want, because every iitem extends `IItem`, when in reality, the adapter is backed by `CheckboxIItem`.

So from here, I'm not sure how you would like to continue this. You could just change the signature of the static methods since the actual types aren't checked anyways, just so languages like Kotlin can infer it.

**Comment by mikepenz** [comment]
@AllanWang thank you for the very detailed message. 

The issue with 
```java
public static <Item extends IItem> FastAdapter<Item> with(@Nullable Collection<IAdapter> adapters)
``` 
is. that for java it is not acceptable to identify the type for something like
```java
Arrays.asList(headerAdapter, itemAdapter)
```
So you will be needed to work with a `Collection<IAdapter>` anything else with the specific type won't work.

Related to the return type. As of the design of the `FastAdapter` it is only important that the `FastAdapter` you use to manage your `IAdapter` uses a parent type of the `IAdapter`'s you added. It is still totally fine if one of the `IAdapter` is a specific version just dealing with `CheckboxItem`s. This will give the developer the proper types, and he can just add `CheckboxItem`'s. 

the `FastAdapter` with the parent type will just not cast the items returned in the listeners for the developer. but that's ok it will cast to the defined parent type.

**Comment by AllanWang** [comment]
I think this can be closed. The only improvement I can think of is perhaps making `A extends IAdapter` become `A extends IAdapter<? extends IItem>` (or the first generic specified). Regardless, people can always add an extension method themselves to avoid writing the generics all the time

**Comment by mikepenz** [comment]
@AllanWang thank you very much for all the good input. 

You might also want to start a tiny kotlin extension library for the `FastAdapter` for people who already have the luck to work in Kotlin ;)

**Comment by AllanWang** [comment]
I already do :)

https://github.com/AllanWang/KAU/tree/dev/adapter

It's not purely for FastAdapter though as it contains some extra iitems.

If you'd like to have a submodule in this repo, I'd be happy to add only the core methods that will help everyone
