### ISSUE TITLE
Click events for chained adapters

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#559]
Before, everything was a FastAdapter, so we can provide click listeners with the proper types for an individual adapter and then have them all linked together elsewhere.

Now, things are `IAdapter`s, which don't have listeners. And we can only add adapters of the same type. How are we supposed to add listeners then?

Imagine we have an `adapter<A>` and `adapter<B>` and we want to add click listeners for B only.

I'm sure there's a way but I don't see it yet.

I'm looking for a way where the type isn't generalized like it is [here](https://github.com/mikepenz/FastAdapter/blob/11ecfbe4107c9c7db8c3036afe0da6881128714b/app/src/main/java/com/mikepenz/fastadapter/app/AdvancedSampleActivity.java#L103)

**Comment by AllanWang** [comment]
(I stand corrected. It seems like you can retrieve the `ItemAdapter` from `FastItemAdapter`. I will give that a try for now

**Comment by mikepenz** [comment]
@AllanWang if you have adapter's of different types you need to use the parent type for the `FastAdapter` 

in the click listener you can then simply check for the type instance. 

A different option is to provide `EventHooks`s to the adapter allowing you to define specific click events for a specific view of an item. 

Another possibility is to implement the `IHookable` interface in the item and just have the listeners attached from within the item.

**Comment by AllanWang** [comment]
I want to avoid checking for type instance. My click event will check the number of selected items, so I feel weird having to get the items themselves and filter out the ones of the wrong type.

Wrapping the other adapter as fast item adapter worked for me. I will also take a look at the hookable. I like that more

**Comment by mikepenz** [comment]
If you have a suggestion how to improve this without breaking type safety for Java please let me know.

**Comment by AllanWang** [comment]
I'm going to move conversation for type safety to #558 since that's the topic there.

The solutions above already provide a way of addressing this. (Wrapping any `IAdapter` within a `FastItemAdapter` is my solution)
