### ISSUE TITLE
Recyclerview with videos

### ISSUE THREAD

**Issue by brittonjg** [mikepenz/FastAdapter#56]
Note: If this is out of scope, then close and I'll find another way.

I am attempting to improve my apps video playback with multiple videos in a RecyclerView. I came across another great library https://github.com/danylovolokh/VideoPlayerManager, but the issue is getting hold of the items that that have an additional couple of extends.

I have tried getting hold of the items via the ItemAdapter.getAdapterItems(), but it returns List<Item>.

The question, is it best for me to create an ItemAdapter of my own, for my item type or is it best to come up with a more generic approach (of which I am yet to think of). I am thinking that for the future it maybe be beneficial to others as well if they need the list returned in another form that isn't of type Item. Or at least a way of further customisation.

**Comment by FabianTerhorst** [comment]
@brittonjg you could create a `recyclerview on scroll listener` to calculate the current visible item and start the video on this one.

**Comment by brittonjg** [comment]
@FabianTerhorst thanks for that. I will have a look into it. Seems way more promising that altering the ItemAdapter.
