### ISSUE TITLE
[Minor] Doc does not reflect OnClickListener refactoring

### ISSUE THREAD

**Issue by frmz** [mikepenz/FastAdapter#560]
OnClickListener has been moved out of class FastAdapter and is now in the interfaces package, this is not mentioned in the 3.0 migration and its also not reflected in the OnClickListener example on the main README

**Comment by mikepenz** [comment]
@frmz it would be amazing if you could do a PR to fix this :)

**Comment by frmz** [comment]
Sorry i was lazy, will do a PR next time
