### ISSUE TITLE
isSwipeable for left/right side only

### ISSUE THREAD

**Issue by alashow** [mikepenz/FastAdapter#563]
Is there a way to disable left or right side swipeability of each item?

For example, if my app allows deleting an item when swiped right, and to archiving when swiped left: 
some items can be both deleted and archived, some only deleted, and some only archived.

**Comment by mikepenz** [comment]
You would have to overwrite the `SimpleSwipeCallback` and define that the only swipe direction is either left or right, depending on the item:

https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/swipe/SimpleSwipeCallback.java#L92
