### ISSUE TITLE
Realm in V3

### ISSUE THREAD

**Issue by r748** [mikepenz/FastAdapter#564]
Hi Mike,

Any specific reason, why Realm support was removed in V3? Are you planning to add this again?

Cheers!
Rob

**Comment by mikepenz** [comment]
The effort to keep it updated was not worth the time. 

Currently I have plans to add it back. If somebody would like to do a PR for it I am more than happy to accept it

**Comment by r748** [comment]
That would be great, thanks!

**Comment by mikepenz** [comment]
You might want to do a realm implementation on your own and open a PR or you are lucky somebody else does one. 

You might also just stick to v2.x

**Comment by r748** [comment]
Ok, thanks. I will see, if I can come up with something...
