### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by marbat87** [mikepenz/FastAdapter#565]
Hi

I'm getting the following error in logcat:
> The bindView method of this item should set the `Tag` on its itemView

It is not clear how should I fix it.

I tryed with this inside my item implementing AbstractItem:
```java
public void bindView(ViewHolder viewHolder, List<Object> payloads) {
 super.bindView(viewHolder, payloads);
viewHolder.itemView.setTag(R.id.fastadapter_history_item_id, this);
```

.. but I get the same error

Any suggestion?

Thanks in advance

**Comment by mikepenz** [comment]
@marbat87 yes already figured that on my own. I introduced this with the update v3.0.3 

Stick with v3.0.2 until I figured out a proper way to resolve this
