### ISSUE TITLE
FastAdapter withEventHook

### ISSUE THREAD

**Issue by ipetu** [mikepenz/FastAdapter#567]
i'm need Using different ViewHolders but FastAdapter.withEventHook(Eventhook) not apply class extends ClickEventHook method.

**Comment by mikepenz** [comment]
@ipetu please be a bit more specific. What do you need?

**Comment by ipetu** [comment]
![image](https://user-images.githubusercontent.com/5442932/33104530-aa1a9534-cf63-11e7-8a18-9fca2c6aa20f.png)

**Comment by ipetu** [comment]
how to use withEventHook Method to different ViewHolders?
