### ISSUE TITLE
Shouldn't this code return true?

### ISSUE THREAD

**Issue by SharonAlexander** [mikepenz/FastAdapter#569]
```
if (mActionMode != null) {
            // calculate the selection count for the action mode
            // because current selection is not reflecting the future state yet!
            int selected = mExpandableExtension != null ? SubItemUtil.getSelectedItems(mFastAdapter).size() : mFastAdapter.getSelections().size();
            if (item.isSelected())
                selected--;
            else if (item.isSelectable())
                selected++;
            checkActionMode(act, selected);
        }
```

On clicking the item in _withOnPreClickListener_ is giving null on actionModeHelper.onClick(item).

And this will enable regular withOnClickListener also. Or is there any other way to stop calling regular withOnClickListener when action mode is enabled.

The problem is there in app published in playstore too.

**Comment by mikepenz** [comment]
@SharonAlexander you talk about the sample app?

**Comment by SharonAlexander** [comment]
Yes  the sample app.
What I'm observing is even when the action mode is enabled, it is returning value _actionModeHelper.onClick()_ is returning null and normal on click listener is fired.

In my app also i don't want to fire the normal click listener when the actionmode is enabled.

**Comment by mikepenz** [comment]
@SharonAlexander sorry for the super late answer. 

The behaviour is as expected. I think for your use case it's best that you either implement your own cab logic (so don't use that helper) or you overwrite the logic (or you add that class to your project and adjust it to your needs)
