### ISSUE TITLE
Sticky Header Problem After Update to 3.0.4

### ISSUE THREAD

**Issue by saeedmozaffari** [mikepenz/FastAdapter#571]
i update fastAdapter from 2.6.3 to 3.0.4;
i used from StickyHeader, but in this update some of methods not exist.
for example like your sample code we should use [following code](https://github.com/mikepenz/FastAdapter/blob/61286b638886707d8918cc4530b0701574acf080/app/src/main/java/com/mikepenz/fastadapter/app/StickyHeaderSampleActivity.java#L66)
```java
rv.setAdapter(stickyHeaderAdapter.wrap(fastAdapter));
```

but in new update `wrap` no exist. how can i use from sticky header in new version?

**Comment by mikepenz** [comment]
@saeedmozaffari wrap still exists in the `StickyHeader` see the code on `develop`:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/StickyHeaderSampleActivity.java#L66

**Comment by saeedrooyekhat** [comment]
I update my StickyHeaderAdapter class with your project, it works fine! Thanks!

**Comment by saeedmozaffari** [comment]
I update my StickyHeaderAdapter class with your project, it works fine, Thanks!
