### ISSUE TITLE
DiffUtil not working at 3.0.4

### ISSUE THREAD

**Issue by dezarion** [mikepenz/FastAdapter#572]
I replaced GenericItemAdapter by new Model adapter according migration guide, but since I did it, something strange happened with diffutil algorithms. My DiffCallback, as in past, correctly compares items and computes payloads, but method `bindView(holder: VH, payloads: MutableList<Any>)` always invokes with empty `payloads` list. What should I do to restore payloads?

**Comment by mikepenz** [comment]
@dezarion which previous version did you have which worked?

**Comment by dezarion** [comment]
2.6.3

**Comment by mikepenz** [comment]
which support library version did you have before?

**Comment by dezarion** [comment]
@mikepenz 26.0.2

**Comment by mikepenz** [comment]
@dezarion any other changes you did? 
It's hard to guess, especially as the main code related the `DiffUtil` did not change, just the method signature (different `Adapter` type) 

Perhaps a change in the support libraries :/

**Comment by dezarion** [comment]
@mikepenz updating of GenericItemAdapter to ModelAdapter is only change I did. I decreased back to 2.6.3  version for a while

**Comment by AllanWang** [comment]
If you update to FastAdapter to 3.0.+, you should definitely update your support libraries. I had some crashes (unrelated to diffutils) without updated support libraries, so there could be an incompatibility here as well

**Comment by mikepenz** [comment]
@dezarion any update on this? did you try it with the latest support libs too?

**Comment by mikepenz** [comment]
Closing until new report
