### ISSUE TITLE
[Request] Drag and drop between two recyclerviews

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#574]
The default implementation is based primarily on views, so I believe it would be a good fit for this adapter. Perhaps this could be a toggle for `AbstractIItem`?

**Comment by mikepenz** [comment]
@AllanWang I don't think this needs any adjustments in the `FastAdapter` as you can just add it to your project or items.

**Comment by AllanWang** [comment]
I got things to work so I'll just make a comment here for future users.

My implementation didn't involve two recyclerviews as I expected. That implementation would involve drag and drop beyond what FastAdapter contains. To implement something similar to the gif below and to quick tiles in the system ui, you only need on recycler, and optionally have a divider set to span the entire width. That way, one container may have gaps.

To properly showcase movements in grids, I needed `notifyDataSetChanged`. Just specifying the two indices had improper animations, and using a range didn't seem to work either.

![giphy](https://user-images.githubusercontent.com/6251823/33900936-237d326c-df3e-11e7-96dd-2acc925acf25.gif)

Full code is [here](https://github.com/AllanWang/Frost-for-Facebook/blob/dev/app/src/main/kotlin/com/pitchedapps/frost/activities/TabCustomizerActivity.kt), to refer to scaling up on drag.
