### ISSUE TITLE
[Question] "Smart" divider implementation

### ISSUE THREAD

**Issue by DummyCo** [mikepenz/FastAdapter#575]
Hi there!
Imagine I have adapters stack with 4 next adapter types:

- header
- item
- footer
- load more (footer)

So that 

- header always stays first
- footer always stays last or last but one depending on loadmore item
- load more itself is spawning on demand as last item

Pretty typical rules here.
Now I'm trying to come up with elegant solution to implement simple dividers between items that are managed by _item_ adapter so that dividers will not spawn above the _first item_ and below the _last one_.
Should I use _AbstractWrapAdapter_? It has a bit scary for that case performance and needs precreated divider items as far as I can see.
Should I implement divider logic and layout in _item_ itself and control its visibility while performing operations with _items_ like inserting, moving or deleting? That does not seems pretty and easy.
Should I manually insert and control divider items as model _items_ along with true _items_ within same adapter?
Do you have some common approaches or ideas for that case? Thank you in advance!

**Comment by AllanWang** [comment]
Haven't tried it, but essentially, if the items all had dividers at the bottom, the only thing you want to avoid is the last item having that divider correct?

In that case, I don't think it will be too hard for you to override add, remove, and change. In each step, just check if the last item will be modified, and if so, let the originally last item show its divider and let the new last item hide its divider.

Another hacky trick that I haven't tried is to shift the footer layout up by 1dp, or whatever the thickness of your divider is. That way it will always hide the divider of  the last item. (Not sure if this will hold true for ViewHolders or if they will just cut off at the start position.

**Comment by DummyCo** [comment]
Hey, @AllanWang 
Thank you for your response.
Well, that approach will work as last resort I think but it would be so nice to come up with solution consolidating separate smart item type or DividerItemDecoration-like approach with flexible settings cause imagine that you can reuse that item layout/wrapper in places where no divider is needed and it will just cause more and more logic to maintain. Or talking for instance about cases with high/wide divider overlapping/item shifting in some cases where you will need to control whole item height or apply containers height wrap what is not acceptable sometimes.

**Comment by AllanWang** [comment]
I think a boolean to toggle divider display is as simple as you can get. As mentioned, you can override the adapter to toggle the booleans when necessary

**Comment by DummyCo** [comment]
Resolved with AdapterDataObserver and RecyclerView.ItemDecoration, thanks!
