### ISSUE TITLE
IModelItem Model bounds

### ISSUE THREAD

**Issue by eygraber** [mikepenz/FastAdapter#576]
Would there be any issue with adding an upper bounds of `Object` on the `Model` parameter of `IModelItem`? Something like:

```
public interface IModelItem<Model extends Object, Item extends IModelItem<?, ?, ?>, VH extends RecyclerView.ViewHolder> extends IItem<Item, VH>
```

I believe this would help with handling multiple model item types in certain situations.

**Comment by FabianTerhorst** [comment]
Are you sure its needed there, because <?> and <? extends Object> are synonymous in most cases. You have an sample where it improves the usability?

**Comment by eygraber** [comment]
Yup, I have an example but it's convoluted and hard to simplify right now. [But in general upper bounds are good for API flexibility] (http://thefinestartist.com/effective-java/28)

**Comment by FabianTerhorst** [comment]
I was talking about an sample for the fastadapter usecase.

**Comment by eygraber** [comment]
Brainfart on my end 😄
