### ISSUE TITLE
Endless Scrolling + Search not working

### ISSUE THREAD

**Issue by Debjyotinath** [mikepenz/FastAdapter#578]
## About this issue

In the sample code once you perform search in EndlessScroll, after that when you remove the search criteria it does not perform endless scroll anymore. Please help solve this issue.

**Comment by TooLazyy** [comment]
same bug

**Comment by mikepenz** [comment]
The solution in this case would be disabling the endless scroll during the `search` case. it is not really possible to have loading more + search. at least not how the built in search functions. you might consider a different approach for filtering + endless scroll.

**Comment by nikitamarysoloman** [comment]
through API call, this issue is fixed by initially using adapterFastItemAdapter.setnewlist(list) and then on scroll adapterFastItemAdapter.add(list);

**Comment by Debjyotinath** [comment]
@nikitamarysoloman :Earlier when search was performed on a list. It would not call the onScroll method for a lazy loaded list. That was the issue. If that was possible then your solution was viable.
