### ISSUE TITLE
[Request] Add nullability annotations where possible

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#579]
This again is meant to help with kotlin method imports, but is helpful for java as well.

Where possible, ambiguous inputs should be annotated with `@Nullable` or `@NonNull`.

A notable part is the payload, but I will check with my builds when I have time to see which spots kotlin will recognize as potentially null.

This is up for discussion, as you may not want annotations everywhere, but I can submit a PR for this if this is approved.

**Comment by mikepenz** [comment]
@AllanWang that's already the case for the core module as you can see here:

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/package-info.java

everything is nonnull by default. 

It might be missing for some extension module

**Comment by AllanWang** [comment]
Okay that is great. I recently saw the warning in my lint and was wondering whether it was enforced. Good to know that it is.

**Comment by AllanWang** [comment]
I'm closing this for now, but given that this change was made in July and I've used FastAdapter after, that annotation may not have been compatible with the auto import.

(Pressing ctrl + o will open a list of overridable methods, and Kotlin will set parameters as nullable if it isn't explicitly declared otherwise)

If this is still an issue I will reopen it

**Comment by AllanWang** [comment]
@FabianTerhorst does this work for you? I tried enabling the flag and importing `bindView` still results in a null payload.

[Relevant post](https://discuss.kotlinlang.org/t/annotating-java-api-with-notnull-to-be-kotlin-friendly-preferably-at-type-level-rather-than-method-level/5209)
