### ISSUE TITLE
Combined with RecyclerViewPreloader

### ISSUE THREAD

**Issue by alphater** [mikepenz/FastAdapter#581]
## Combined with RecyclerViewPreloader

FastAdapter is the best adapter library I've found so far, but I've found some awkward issues with it:

1，Since I used a lot of webpages in my project, I used the [RecyclerViewPreloader] (https://bumptech.github.io/glide/int/recyclerview.html) in Glidev4 to get better performance and needed to implement the ListPreloader.PreloadModelProvider <> method in the RecyclerViewPreloader when used in conjunction with the RecyclerViewPreloader, but the FastItemAdapter Encapsulation based on RecyclerView.Adapter, I can not directly achieve ListPreloader.PreloadModelProvider <>, Is there any way to solve this problem?

2，GlideRequest <> is also used when using RecyclerViewPreloader in Glidev4 WebPhotos are loaded in RecyclerView because the footpad needs to be explicitly manipulated in the fragment and RecyclerViewPreloader <> is set for RecyclerView.addOnScrollListener () so it can not be done alone Declare and create in the project.

Looking forward to solve, thank you very much.

**Comment by FabianTerhorst** [comment]
Hi,

will take a look into it, since it would be an useful feature to make an fast recyclerview. But as always, feel free to suggest an specific implementation or make a pull request for it.

**Comment by alphater** [comment]
@FabianTerhorst Thank you very much for your reply. But I have not found a specific program, will find the first time to assist pull.
thank you very much

**Comment by mikepenz** [comment]
I think we can close this as it seems to be not very bound to the adapter implementation itself. In any case it should be rather straight forwarded to extend the `FastAdapter` and add custom logic if required.

**Comment by alphater** [comment]
@mikepenz  
I'm sorry, some time ago, more busy, did not reply in time.
Thank you very much for your reply.

You mentioned the extension FastAdapter is a good suggestion, but I try to fail, perhaps I did not extend successfully, can I give a RecyclerViewPreloader related demo? This should be a lot of people need, thank you very much.

**Comment by mikepenz** [comment]
@alphater yes sure. a demo activity in the sample app will also help :)
