### ISSUE TITLE
when I use  ` modelAdapter.clear();`, the RecyclerView scroll to the last item.

### ISSUE THREAD

**Issue by littlezan** [mikepenz/FastAdapter#583]
this situation happens when I use [android-Ultra-Pull-To-Refresh](https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh).

when I pull down to refresh data,  I did below:
```
       modelAdapter.clear();
        modelAdapter.add(createDataList());
```

It's weird, the RecyclerView scroll to the last item,

**Comment by mikepenz** [comment]
@littlezan not related to this library. that's how the `RecyclerView` handles it if you first delete all items and then add a new set of items (with possibly the same id's too?) 
you can tell it to scroll to top

**Comment by littlezan** [comment]
Yes, I had to manual RecyclerView scroll to top, after ` modelAdapter.clear();` like this:
```
modelAdapter.clear();
layoutManager.scrollToPosition(0);
modelAdapter.add(createDataList());
```
and it's perform good.

**Comment by mikepenz** [comment]
The adapter is only providing the items, and notifying the rv about changes. Whatever is displayed and where it is scrolled to is controlled by the RV and it's LayoutManager.

Glad that approach works for you

**Comment by littlezan** [comment]
as use
```
modelAdapter.clear();
layoutManager.scrollToPosition(0);
modelAdapter.add(createDataList());
```
I found a method can complete solve my problem, it's to use ` modelAdapter.setNewList();`
