### ISSUE TITLE
Communicate from Item to Adapter

### ISSUE THREAD

**Issue by Shakezulla57** [mikepenz/FastAdapter#586]
Is there any mechanism (I couldn't find anything) to communicate from an `AbstractItem` to its `FastAdapter`? I have a few use cases where I'm using Glide to load some images. I'd like to create one instance of the Glide `RequestManager` and make it available to all the items in the adpater. Currently what I'm doing in a different situation is just passing the resource to my items when I instantiate them. `new MyItem(SomeResource resource)` which I can then use in those items. Is there a better way to do this?

Anyway to extend FastAdapter to include a reference to my `RequestManager` whose items then have access to it?

**Comment by FabianTerhorst** [comment]
You could use an ModelAdapter and create your own IInterceptor. Inside the interceptor you get back each item you want to add to your adapter. The easiest solution would be to call an setter there to set the reference for the RequestManager.

**Comment by Shakezulla57** [comment]
Thanks for the feedback @FabianTerhorst. The places where I'm injecting a dependency like this are already ModelAdapters with generic items. So I'll just keep doing it that way.
