### ISSUE TITLE
OnLoadMore is being called on initialize

### ISSUE THREAD

**Issue by mori-honest** [mikepenz/FastAdapter#587]
I used your sample code and added a toast when data is loaded in EndlessScrollListActivity.java, and when the page initializes, the load more is called and unnecessary data is loaded even if user is not scrolled down to bottom of list :(
and also if you try to scroll fast (up and down) and get near to end of the list, you may get stuck into infinite load more!

**Comment by mikepenz** [comment]
if there are not enough items, and the end is already in range of loading the next page it will already trigger. 

if you scroll really fast. either you load the next page on a much earlier "threshold".

**Comment by mori-honest** [comment]
But this is not something that makes sense in production.
Think about a list which is empty and no item is inserted and even if the first request is not made to get first items from server, the second page is triggered to be called and request for the second page data :D

**Comment by mikepenz** [comment]
The `OnLoadMore` listener integrated is a very minimal solution which is ok for most cases. You can easily tweak it or overwrite some logic to adjust it to your needs. You might also want to check out other such listeners, as it is rather independent of the adapter logic itself. 


Anyways if you have ideas how to improve it for others, you might want to open a PR

**Comment by mikepenz** [comment]
Please open a PR if you would love to improve this. Closing this ticket for the time being

**Comment by souvikhazra1** [comment]
I had the same issue. Solved with a simple tweak.
Initially I disables the listener with `disable()` method. And called `enable()` after my data has been loaded in the adapter.
