### ISSUE TITLE
[Suggestion] Is abstract unbindView() in FastAdapter.ViewHolder necessary?

### ISSUE THREAD

**Issue by aksinghnet** [mikepenz/FastAdapter#592]
## About this issue

Hi Mike,

Thanks for writing FastAdapter. After a few hiccups, I find it really helpful. 👍 

I have a suggestion, which you may find as a question. I read [here](https://stackoverflow.com/a/43656611) that unbinding is only required or important for fragments and not RecyclerView items. If it is correct, may be you can make unbindView() in FastAdapter.ViewHolder as non-abstract so that one overrides it only if one really wants to, else it's okay.

Thank you.

## Details
- [ 3.0.5 ] Used library version

**Comment by mikepenz** [comment]
@aksinghnet unbind is super important, depending on what you do. I chose to make it abstract to make the developer aware of the existence of this method, and to raise awareness in developing and implementing a good `RecyclerView` item
