### ISSUE TITLE
Make sticky rows part of view hierarchy.

### ISSUE THREAD

**Issue by RussellZornes** [mikepenz/FastAdapter#595]
The sticky header support uses a ghost image as the sticky header which means its not really part of the view hierarchy and therefore can't contain clickable things.

This greatly limits what you can do with sticky headers as they are not always just static things.

**Comment by bernaferrari** [comment]
As far as I know, this is limited to sticky-header's library, not Fast Adapter. But.. you may check Google I/O app, which has buttons in the sticky headers, in their implementation:
https://github.com/google/iosched

**Comment by mikepenz** [comment]
@bernaferrari thanks for answering

@RussellZornes yes the sticky headers are not part of the fastAdapter.
