### ISSUE TITLE
Implementing a good adapter.remove(Set<Int>)

### ISSUE THREAD

**Issue by bernaferrari** [mikepenz/FastAdapter#596]
I am using FastAdapter to select items, then remove them. I noticed there is no method for adapter.remove(adapter.selections), not sure if by design or because no one ever needed it.

I am currently doing this:

```
    fastFA.selections.reversed().forEach {
        fastFA.remove(it)
    }
```

Is this a good implementation? Works fine, but I'm still not safe if it is the best way. The biggest problem is that it is iterating over a list that is changing, so I did the reversed().

**Comment by mikepenz** [comment]
Not sure but I think you were searching for: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1154

**Comment by bernaferrari** [comment]
Wow, it was exactly this. I was searching for remove/set.. thanks!!
