### ISSUE TITLE
Only one item appears

### ISSUE THREAD

**Issue by Dahnark** [mikepenz/FastAdapter#597]
I am testing this library and I am trying to show two items with the same content, but only one item appears

```
recyclerView.setLayoutManager(new LinearLayoutManager(context, LinearLayoutManager.VERTICAL, false));
FastItemAdapter<FastItem> fastAdapter = new FastItemAdapter<>();
recyclerView.setAdapter(fastAdapter);

List<FastItem> items = new ArrayList<>();
FastItem fastItem = new FastItem()
                .valueExampleOne("1")
                .valueExampleTwo("2");
items.add(fastItem);
items.add(fastItem);

fastAdapter.add(items);
```
What am I doing wrong?

**Comment by Dahnark** [comment]
Well, the problem is caused by wrap_content, it is not working, if I use a specific measure in DPs it is working...

**Comment by mikepenz** [comment]
@Dahnark that seems to be not related to the adapter, but to the general behaviour of the `RecyclerView`
