### ISSUE TITLE
Basic Base-Implementations

### ISSUE THREAD

**Issue by mikepenz** [mikepenz/FastAdapter#6]
* provide some base implementations which should speed up developement

**Comment by Rainer-Lang** [comment]
What do you mean with this?

**Comment by mikepenz** [comment]
@Rainer-Lang some basic items you can base your items on. --> Default behavior for background as example

**Comment by mikepenz** [comment]
There is the https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/items/AbstractItem.java which implements all the base stuff :D
