### ISSUE TITLE
ExpandableExtension suggestion

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#600]
What do you think of following extension:

    ExpandableExtension expandableExtension = mFastItemAdapter.getSingleExtension(ExpandableExtension.class); // useful, if the extension can only be added once or only makes sense if it is only added once
    List<ExpandableExtension> expandableExtensions = mFastItemAdapter.getExtensions(ExpandableExtension.class); // useful if an extension can be added mutliple times

So that I can get installed extension in a convenient way from the adapter

**Comment by mikepenz** [comment]
@MFlisar I like the idea. and the extension can only be provided once. I don't know of a usecase where a extension would possibly be added multiple times. 

Really nice idea ;)

**Comment by MFlisar** [comment]
I this case following is sufficiant:

    ExpandableExtension expandableExtension = mFastItemAdapter.getExtension(ExpandableExtension.class);

I've not checked it, but in this case adding an extension should throw an exception if one of the same type was added already (as a precaution) if it does not do this yet

**Comment by mikepenz** [comment]
I think I use a `Set` for the extensions If I am not mistaken

**Comment by mikepenz** [comment]
I am more than happy to take a PR for that :)

**Comment by mikepenz** [comment]
Included here :D https://github.com/mikepenz/FastAdapter/pull/607
