### ISSUE TITLE
Frames skipped on a VERY specific case

### ISSUE THREAD

**Issue by bernaferrari** [mikepenz/FastAdapter#601]
Hi!

I'm having a problem with FastAdapter and I'm not sure what is the best solution. This is what is going on:

![performance issues fast adapter](https://user-images.githubusercontent.com/351125/34730603-0668fb60-f547-11e7-9a8e-e7e66e830ef6.gif)

I have 3 fragments, one of them containing a ViewPager ("main"), the other two are the two pages from it (frag "a" and frag "b"). When I tap on frag "a", it sends a value (int) to frag "b" (previously via EventBus, now via LiveData) AND asks for frag "main" to change the page, i.e. go from page "a" to page "b". Problem is, when the value arrives at frag "b", it fetches from the server and updates the RecyclerView.. but since this is a light transaction, it is happening EXACTLY the same time as the ViewPager animation, causing delay/frames skipped/not a great feeling, as the gif above.

I did try:

- Change the recyclerView visibility before the transaction to GONE, and after to VISIBLE (gif above is doing this, so you can see well what is going on).
- Clear the adapter before the transaction, then adapter.add( ) on every item.
- Make a list with all adapter values, then adapter.set( ) everything at once.
- Make the list on a different thread (via rx), set/add the resulting value on the main thread.

Worst case scenario is like 150 items, not a lot.
None worked.

I also tried to profile the app, and even remove the fastAdapter instruction to see if it wasn't something before it eating too much resources.. yeah, it is what is causing the performance issue.

Any ideas how I could improve on this? Thanks!!

**Comment by mikepenz** [comment]
I don't think it's really related to the FastAdapter. You will most likely have that problem with your own recyclerview adapter too. 

you might want to load the items async after the fragment is ready. to remove lag. 

you might also want to check that your items are not too heavy. the recyclerview has to initially create a few instances of the viewholder until it can reuse them, that's taking time.

**Comment by bernaferrari** [comment]
Oh, thanks! I thought there were some hidden magical method that could help me. Thanks for the answer!!
