### ISSUE TITLE
Q : how can remove last item of ModelAdapter

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#604]
for delete last item of ModelAdapter which one is correct in fastAdapter ?

1.
```java
int c = modelAdapter.getAdapterItemCount();
modelAdapter.remove(c-1);
```

2.
```java
int c = modelAdapter.getAdapterItemCount();
modelAdapter.remove(c);
```

main problem is :

```java
int c = this.itemAdapter.getAdapterItemCount() - 1;
if(this.itemAdapter.getAdapterItem(c) instanceof LazyLoadingItem) {
    this.itemAdapter.remove(c);
}
```

when i call this, when condition is true, adapter deleted before item of (LazyLoadingItem)

**Comment by mikepenz** [comment]
@DJafari the remove method takes the `global` position so it is the position of the whole set of items across all items in the adapter. 

a `ModelAdapter` has the `getGlobalPosition` method which gives you the correct position to delete based on the relative position.

**Comment by mikepenz** [comment]
For this case. You could use it's own `ItemAdapter` for this single item, and then you just clear this adapter

**Comment by DJafari** [comment]
@mikepenz thanks for your help

if i want use one adapter this is correct ?

```java
int c = this.itemAdapter.getAdapterItemCount() - 1;
if(this.itemAdapter.getAdapterItem(c) instanceof LazyLoadingItem) {
    this.itemAdapter.remove(this.itemAdapter.getGlobalPosition(c));
}
```

**Comment by mikepenz** [comment]
Looking at the code, yes it should be. 
Even though you don't need to get the `globalPosition` with one single adapter, as global position == relative position in this case.
