### ISSUE TITLE
How to get all items in ExpandableList [Question]

### ISSUE THREAD

**Issue by maloz** [mikepenz/FastAdapter#605]
## About this issue
I want to save the items in my list. I have a liste of items that may have sub items and so on.

Item 1
-- Sub item 1
-- Sub item 2
-- Sub item 3
-- -- Sub Sub item 1
-- -- Sub Sub item 2
-- -- -- Sub Sub Sub item 1
Item 2
-- Sub item 2
.....

Doing: itemAdapter.getAdapterItems() will only give me showed item (so if Sub Item 3 is collapsed, I won't get the sub sub items).

How can I get all the items in the list, so I have a way to save them ? I wish the user can, and the end: -
- Open the app, add items/sub items, close it and come back with the same state and items.

Thanks for your help and your great library !

## Details
- [3.0.5 ] Used library version
- [3.0.1 ] Used gradle build tools version
- [3.0.1 ]  Android Studio version

## Checklist

- [Done ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [Done ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ Done] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [Done ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [Done ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/utils/AdapterUtil.java#L60

**Comment by mikepenz** [comment]
The fastadapter offers if the same item list was applied that the items are expanded again, and the selections are reset. it's up to you though to supply the same set of items (including their identifiers)

**Comment by maloz** [comment]
Oh thank you, didn't saw the method. 
But, when trying to save the list (by example parse it) when it contains some sub-items, I always get some StackOverflowError because  it's to big. Wich way would you propose to save everything ?
 
For now, I have another class for my items that contain only the datas, their UUID + a UUID for the parent. So with that, I'm able to reconstruct the list with the sub items, but it's not really straightforward. If you have another method to propose, it would be helpfull :)

**Comment by mikepenz** [comment]
How many items do you have? 

Could it be that you somehow created a endless parent / child recursion?

**Comment by maloz** [comment]
I start with no item but let the user add as much item as he need. And he can add item at the root of the list or make it child as any item.
With that, I allow multilevel sub items. 

In a way yes because a parent have a child, the child have a parent and this parent have again the child, and so on.. So this is maybe why I can't parse it or save it directly

I can send code or app screenshot if needed!

**Comment by mikepenz** [comment]
Well as mentioned keeping the data itself and putting it into a database or so is up to you, The `FastAdapter` itself already contains some logic to provide a `withSavedInstanceState` functionality, automatically expanding / collapsing / selecting items when the configuration changes. you can also use the same to store it accross app relaunches

**Comment by mikepenz** [comment]
I think this can be closed. as it can be resolved already with the current version. and I think the new utils which will come with v3.2.0 will even further enhance things :)
