### ISSUE TITLE
How to load AdMob Advance ads inside the RecyclerView

### ISSUE THREAD

**Issue by ItsAnubhav** [mikepenz/FastAdapter#606]
## I tried to implement the AdMob Advance Ads from [https://developers.google.com/admob/android/native-advanced](url) but I can't figure out how to add it in FastAdapter.

- I tried to follow this codelab [https://codelabs.developers.google.com/codelabs/admob-native-advanced-feed-android/index.html](url) but no luck.

**Comment by mikepenz** [comment]
@ItsAnubhav check out the sample application it showcases the use of `Admob`

**Comment by mikepenz** [comment]
Looking at this tutorial. It is possible to implement this, similar to the mopubs usecase. 
This is a very advanced coding topic, and will require some knowledge of the Android system. 

But this is not related to the `FastAdapter` and I can sadly not give support for some external libraries.
