### ISSUE TITLE
How to expand/collapse expandable item correctly?

### ISSUE THREAD

**Issue by Bringoff** [mikepenz/FastAdapter#608]
## About this issue
My list looks like a tree. And the same items may be presented on different levels. Like this:
item1
-item2
--item3
_ _ 
item2
-item3
_ _
So, if item1 is expanded and I click to expand the second occurrence of item2 (the one is at the tree root, not the item1 descendant), descendant item2 is expanded, not the one I've clicked. I expand items like this:
```
val adapterPosition = getAdapterPosition(itemListItem)
val expandableExtension = (fastAdapter.extensions.firstOrNull { it is ExpandableExtension } as ExpandableExtension?)
expandableExtension?.toggleExpandable(adapterPosition)
```
I understand that `getAdapterPosition` must have been searching for the first object instance passed as a parameter. But I need a different behavior, I want to expand exactly the item user clicked. How to explain an adapter to expand correct item?

## Details
- [ 3.1.2 ] Used library version
- [ 27.0.2 ] Used support library version

**Comment by Bringoff** [comment]
Any suggestions how to make a unique id? :) Because models used for that list have the same id. Default id distributor helps with this, but list begins to blink on updates (obviously).

**Comment by mikepenz** [comment]
@Bringoff well there are different options. either your application comes with one, or you generate a (almost definite unique id) via a string (if those strings are unique), or you use the `IdDistributor` built into the lib. 

the thing is. A RecyclerView uses those identifiers to optimize animations, and other things so it is super important to have them unique and not duplicated

**Comment by Bringoff** [comment]
Yes, I understand why id should be unique. Default id distributor didn't work well. But ok, I invented a cludge for my case. I add indentation to model id. Looks like it works.
Actually, the lib might have an optional inspection of duplicated ids in one adapter. What do you think about it?

**Comment by mikepenz** [comment]
the default ID distributor will always provide a new unique ID when a new item is created. so it is definitely unique. but it doesn't know or check that one item always gets the same id. 

Well a inspection is adding some overhead. I guess you can implement something like this on your side super easy by just using a `HashSet<Long>` 

and then you fill it up with the identifiers, and if an identifier is already contained it is duplicated
