### ISSUE TITLE
support sticky item

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#609]
purpose of FastAdapter is `simplify adapter creation`, it's true ?

but using sticky items is too hard

i have multiple adapter and view type, and i want some of them be sticky, it's can not using your approach in example, for example i have some `NewsItem`, and i want some of them be sticky (not all)

if possible support it in library by a interface ( Ex : `boolean isSticky();` ) and handle it in library

i think [RecyclerStickyHeaderView](https://github.com/TellH/RecyclerStickyHeaderView) using better way than other libraries

i hope finally stickyHeaders be simplify

**Comment by mikepenz** [comment]
Well there are currently no plans to implement something like this inside the FastAdapter itself. nothing prevents using a third party library for this purpose (as you can see in the sample app)

**Comment by DJafari** [comment]
> Well there are currently no plans to implement something like this inside the FastAdapter itself

bad news :(

> nothing prevents using a third party library for this purpose (as you can see in the sample app)

in your approach you have a header for some items, but i want some of my items be sticky when reached, i think there is no way to implement this in FastAdapter with outbox library

**Comment by mikepenz** [comment]
I didn't look to closely in the lib you sent above. but most of those sticky implementations somehow use the ItemDecorator. 

Actually the best implementation would still be a custom `LayoutManager` which just listens for an interface. but I am not sure if somebody took the time and effort to come up with something like this

**Comment by DJafari** [comment]
i think better person to support this is you
please when you got a free time, add it to your library, it is popular feature and useful in all apps

thanks

**Comment by mikepenz** [comment]
Perhaps some day. :D currently there are no plans to do so :)

Perhaps you write it some day ;)

**Comment by AllanWang** [comment]
Couldn't you just split up sticky and nonsticky items as two classes extending the base implementation class? The id will be different, but the layouts and bindings will be the same.

**Comment by DJafari** [comment]
@mikepenz 
ok i will tried to implement this

please answer my question to help me in this way :

1. how can get generated view for example at adapterPosition: 10 ?

2. how can get item viewHolder for example at adapterPosition: 10 ?

**Comment by mikepenz** [comment]
@DJafari you never can get (for sure) a view for a position. A `RecyclerView` reuses views, and it has no view for a item which is out of visibility. So that should not be done. 

The exact same happens for the `ViewHolder` which is re-used during scrolling. so accessing it will lead to issues.
