### ISSUE TITLE
[Question] Calling DiffUtils for one item only

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#610]
Looking at the sample, I understand that we can set a new list and use the diff callback to map the differences and load using payloads. However, can we do that with a single item?

From things like marking an item as read, toggles, etc, having it reuse the view will allow for animations, which would be quite nice. This also has applications to some of the sample activities.

This application is namely just for changing an item at a given position. As anything else will likely be easier to just apply to the entire list.

I understand that one option may be to take out the list, modify the item, then calculate the difference, but that seems quite expensive.

FastAdapter: 3.0.5

**Comment by mikepenz** [comment]
@AllanWang for toggling etc. I highly recommend to simply notify the `Adapter` about the item being changed, and you provide a payload with this. 

The payload could be something like `toggled` this allows you to just update that single view inside this item. 

You can theoretically also simply put that single item in a list and provide this as new dataset. it should work exactly the same.

**Comment by AllanWang** [comment]
Do you have a reference/link to a code snippet I can look at? Doesn't look like any of the examples uses the payloads. Things like CheckBoxIItem are toggled by selection, and it only seems to notify the change

**Comment by mikepenz** [comment]
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyItemChanged(int, java.lang.Object)
https://developer.android.com/reference/android/support/v7/util/DiffUtil.Callback.html#getChangePayload(int, int)

**Comment by mikepenz** [comment]
So basically that's not something special to the `FastAdapter` but some functionality of the `RecyclerView.Adapter` :)
