### ISSUE TITLE
fastadapter cannot be resolved after update to 3.2.0

### ISSUE THREAD

**Issue by eakteam** [mikepenz/FastAdapter#613]
## About this issue

This happen after im trying to get the latest library : 3.2.0

Failed to resolve: com.mikepenz:fastadapter:3.2.0

    implementation 'com.mikepenz:fastadapter:3.2.0@aar' --- THIS CANNOT BE RESOLVED
    implementation 'com.mikepenz:fastadapter-commons:3.2.0@aar' ---- THIS IS OK

repositories {
            google()
            jcenter()
            mavenCentral()
            maven { url "https://maven.google.com" }
            maven { url "https://jitpack.io" }
        }

**Comment by mikepenz** [comment]
Oh sorry. Javadoc had an issue and blocked the upload. and I totally missed it. 

Released it again. will take ~30mins to be available

**Comment by eakteam** [comment]
haha , It's ok we'r waiting 👍

**Comment by mikepenz** [comment]
thanks :)

it should be available via jCenter already though

**Comment by eakteam** [comment]
I have just checked , and now is working :) :) ... Thank you !
