### ISSUE TITLE
Program type already present: com.mikepenz.fastadapter.IExpandable

### ISSUE THREAD

**Issue by DummyCo** [mikepenz/FastAdapter#614]
## About this issue

Hi there! Facing D8 build problem with 3.2.0:
`AGPBI: {"kind":"error","text":"Program type already present: com.mikepenz.fastadapter.IExpandable","sources":[{}],"tool":"D8"}`

## Details
- [3.2.0] Used library version
- [27.0.2] Used support library version
- [3.1.0-alpha08] Used gradle build tools version
- [3.1 Canary 8] Used tooling / Android Studio version
- [Iconics 3.0.1/3.0.2] Other used libraries, potential conflicting libraries

**Comment by mikepenz** [comment]
@DummyCo do you use `AboutLibraries`, or `MaterialDrawer`?

can you print out the dependency tree? 

It seems a older version of the `FastAdapter` is somewhere present. Do you use the `Expandable` extension in an older version ?

**Comment by mikepenz** [comment]
Well the `MaterialDrawer` uses a different version, which conflicts. 

Use a resolutionstrategy to force 3.2.0 of the `FastAdapter` 

Similar like here (change the version)

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/build.gradle#L83
