### ISSUE TITLE
[Feature Enhance] AbstractItem's bindView method

### ISSUE THREAD

**Issue by johnwatsondev** [mikepenz/FastAdapter#615]
## About this issue

We invoked the `setSelected` method directly in the current codebase.

```java
@Override
    @CallSuper
    public void bindView(final VH holder, List<Object> payloads) {
        //set the selected state of this item. force this otherwise it may is missed when implementing an item
        holder.itemView.setSelected(isSelected());
    }
```

We should change it in a more reasonable way shown below.

```java
@Override
    @CallSuper
    public void bindView(final VH holder, List<Object> payloads) {
        holder.itemView.setEnabled(isEnabled());
        if(isEnabled()){
            //set the selected state of this item. force this otherwise it may is missed when implementing an item
            holder.itemView.setSelected(isSelected());
        }
    }
```

## Reason

Our item maybe has three different states in business.
e.g.
1. selected
2. not selected
3. cannot selected == disabled

## Last
Thanks for hard work. :)

**Comment by mikepenz** [comment]
@johnwatsondev for this usecase I'd recommend to create your own `AbstractItem` implementation which does this. 

I see why it might be clever, but it would definitely break existing apps which I think is not good to do :D

**Comment by johnwatsondev** [comment]
Yep. I got your point. Thanks again. 👍
