### ISSUE TITLE
[Bug] Single choice with quick switch selected item

### ISSUE THREAD

**Issue by johnwatsondev** [mikepenz/FastAdapter#616]
## About this issue
I use the `MultiselectSampleActivity` to test the behavior. The code is below:

```java
        // ... as same as our sample ...

        mFastAdapter.setHasStableIds(true);
        mFastAdapter.withSelectable(true);
        //mFastAdapter.withMultiSelect(true);
        //mFastAdapter.withSelectOnLongClick(true);
        mFastAdapter.withSelectionListener(new ISelectionListener<SimpleItem>() {
            @Override
            public void onSelectionChanged(SimpleItem item, boolean selected) {
                Log.i("FastAdapter", "SelectedCount: " + mFastAdapter.getSelections().size() + " ItemsCount: " + mFastAdapter.getSelectedItems().size());
            }
        });
        mFastAdapter.withOnPreClickListener(new OnClickListener<SimpleItem>() {
            @Override
            public boolean onClick(View v, IAdapter<SimpleItem> adapter, @NonNull SimpleItem item, int position) {
                //we handle the default onClick behavior for the actionMode. This will return null if it didn't do anything and you can handle a normal onClick
                Boolean res = mActionModeHelper.onClick(item);
                return res != null ? res : false;
            }
        });
        mFastAdapter.withOnClickListener(new OnClickListener<SimpleItem>() {
            @Override
            public boolean onClick(View v, IAdapter<SimpleItem> adapter, @NonNull SimpleItem item, int position) {
                //Toast.makeText(v.getContext(), "SelectedCount: " + mFastAdapter.getSelections().size() + " ItemsCount: " + mFastAdapter.getSelectedItems().size(), Toast.LENGTH_SHORT).show();
                return false;
            }
        });
        //mFastAdapter.withOnPreLongClickListener(new OnLongClickListener<SimpleItem>() {
        //    @Override
        //    public boolean onLongClick(View v, IAdapter<SimpleItem> adapter, SimpleItem item, int position) {
        //        ActionMode actionMode = mActionModeHelper.onLongClick(MultiselectSampleActivity.this, position);
        //
        //        if (actionMode != null) {
        //            //we want color our CAB
        //            findViewById(R.id.action_mode_bar).setBackgroundColor(UIUtils.getThemeColorFromAttrOrRes(MultiselectSampleActivity.this, R.attr.colorPrimary, R.color.material_drawer_primary));
        //        }
        //
        //        //if we have no actionMode we do not consume the event
        //        return actionMode != null;
        //    }
        //});

        // ... as same as our sample ...
```

## Screen Record
![singlechoicebug](https://user-images.githubusercontent.com/12760754/35275155-be3b3f22-0079-11e8-9e62-985abc36b449.gif)

## Reproduceable Step
I selected the item 3 firstly. I selected the item 4 quickly and pressed the item 3 again.
The magic happened as the gif shows. The item 3 's background is mismatched as normal drawable.

## Why This Happened
I can't figure it out. Let me know if you solved this problem. Thanks very much.

**Comment by mikepenz** [comment]
@johnwatsondev it's the animated background. :/ 

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleItem.java#L118 

if you disable the animation, (the `true` at the end) then it will most likely work

**Comment by johnwatsondev** [comment]
@mikepenz It's not just the animated effect. The background of item 3 should be the color of red because I selected it finally in the gif. But It showed the normal background. You can test it yourself. :)

**Comment by mikepenz** [comment]
What I mean is, the `animation` on that background will cause it look not selected as the animation will not finish the second time. even though it is.

**Comment by johnwatsondev** [comment]
Well. I have disabled the animation. I still didn't work.

**Comment by mikepenz** [comment]
@johnwatsondev so this is basically caused by the android framework's "slow" state handling. Not sure if it is exactly the state handling, or the `StateListDrawable`.

Which leads to this visual issue. Checking the selected items via the `FastAdapter` will return the correct selections . 

So the `SimpleItem` uses the state on the view to automatically handle the selection. This is the default behaviour of the `FastAdapter` an will not trigger a `notify` on this position on selection change. 

You can change this behaviour by defining
```java
mFastAdapter.withSelectWithItemUpdate(true);
```
and replace the background setting of the `SimpleItem` with something like:
```java
if(item.isSelected()) {
     view.setBackgroundColor(Color.RED);
} else {
    view.setBackgroundColor(Color.WHITE);
}
```

This will result in instant updates of the item via the `notify` method
