### ISSUE TITLE
EndlessRecyclerOnScrollListener is called when recyclerview is loaded

### ISSUE THREAD

**Issue by Dahnark** [mikepenz/FastAdapter#617]
The method is called when the recyclerview is loaded instead of wait until I scroll down to the end of the list.

**Comment by mikepenz** [comment]
Duplicate: https://github.com/mikepenz/FastAdapter/issues/587

**Comment by Dahnark** [comment]
The problem was the nested scroll view. I changed it to a linear layout and the problem is solved.
