### ISSUE TITLE
Item click duplicated

### ISSUE THREAD

**Issue by Dahnark** [mikepenz/FastAdapter#620]
When I click an item, this item changes its size. I have 20 items, then the problem is when I click the item 1, the item 10 and 19 duplicate this behavior. If I click the item 2, 11 and 20 duplicate the behavior.

This problem is caused by all items, is like all items were paired.

I think the problem is "view" is being duplicated because that item is clicked one time and only one position is showed in the log.

```
fastAdapter.withOnClickListener((v, adapter, item, position) -> {
                final View view= v.findViewById(R.id.view);
                ... change view parameters ...
        });
```

**Comment by mikepenz** [comment]
@Dahnark you definitely should not change the view within a listener. 

Notify the adapter if the item changed (possibly with a payload) and act accordingly in the `bindView` method of the item.

**Comment by Dahnark** [comment]
I am trying to change it, do you have an example of it?

Is there any way to avoid the item blinking when I notify the item is changing?

**Comment by mikepenz** [comment]
well the blinking happens if the item updates. that's controlled by the `ItemAnimator` of the `RecyclerView` 

Something in your code must cause this, as the issue does not exist in the sample, and also not in any of the apps in which I use it

**Comment by AllanWang** [comment]
I believe blinking in many cases is the [default behaviour](https://chromium.googlesource.com/android_tools/+/refs/heads/master/sdk/sources/android-25/android/support/v7/widget/DefaultItemAnimator.java#334) as changing items have their alphas set to 0.
You may have a look at Mike's item animator [here](https://github.com/mikepenz/ItemAnimators) or my set [here](https://github.com/AllanWang/KAU/tree/dev/adapter) in Kotlin

**Comment by Dahnark** [comment]
Well, the problem of the "paired items" was solved, it is not related to this library. Blinking is caused, I think, when Android animates changes automatically.
