### ISSUE TITLE
[Question] Failed to resolve FastAdapter

### ISSUE THREAD

**Issue by Seidak** [mikepenz/FastAdapter#622]
First thanks for awesome library!

I had no problem until version 3.0.4, but when I tried to update to newer version (higher than 3.0.4) I got this error:

```
Error:Failed to resolve: com.mikepenz:library-core:3.1.1
Error:Failed to resolve: com.mikepenz:library:unspecified
```

I tried 3.1.0, 3.1.1, 3.1.2, 3.2.0 and still got this error. 

My gradle:

```
...

repositories {
    google()
    jcenter()
    mavenCentral()
    maven { url "https://maven.google.com" }
    maven { url "https://jitpack.io" }
}

...

implementation 'com.mikepenz:fastadapter:3.2.0@aar'
implementation 'com.mikepenz:fastadapter-commons:3.2.0@aar'
implementation 'com.mikepenz:fastadapter-extensions-expandable:3.2.0@aar'
```

I tried to clear project, invalidate cache and nothing helped me. Haven't you experienced something like this? I have no idea what can be wrong. If I downgrade back to old version, then its working again.

Thank you

**Comment by AllanWang** [comment]
Did you update your support libs as well? Don't see how that would cause a build to fail, but it is necessary to get fast adapter working properly. You can so remove mavenCentral() as that's included in jcenter and remove the maven.google.com as that's the old alternative of google()

**Comment by kusyjan** [comment]
I have got the same issue 😏 😞

**Comment by mikepenz** [comment]
Should be fine in the next update

**Comment by Seidak** [comment]
@mikepenz @AllanWang thanks for reply, today I tried new version I got the same error still except now it's showing 

```
Error:Failed to resolve: com.mikepenz:library-core:3.2.2
Error:Failed to resolve: com.mikepenz:library:unspecified
```

before that it was always 3.1.1. I have newest support library.

**Comment by mikepenz** [comment]
@Seidak any other lib which you have? 

The pom files are correct:

core
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mikepenz</groupId>
  <artifactId>fastadapter</artifactId>
  <version>3.2.2</version>
  <packaging>aar</packaging>
</project>
```
commons
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mikepenz</groupId>
  <artifactId>fastadapter-commons</artifactId>
  <version>3.2.2</version>
  <packaging>aar</packaging>
</project>

```
extension-expandable
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mikepenz</groupId>
  <artifactId>fastadapter-extensions-expandable</artifactId>
  <version>3.2.2</version>
  <packaging>aar</packaging>
</project>
```

**Comment by AllanWang** [comment]
Have you tried invalidating cache? And is it supposed to be trying to fetch library-core? You could try it through jitpack as a last resort

**Comment by amorenew** [comment]
I have same Isuue on 3.2.5

**Comment by amorenew** [comment]
Update:
I added @arr and it works
    implementation 'com.mikepenz:fastadapter-extensions:3.2.5@aar'

**Comment by ramanadv** [comment]
Same issue , works when I add @aar to the dependency line in gradle.

**Comment by mikepenz** [comment]
seems changes in gradle resulted in it suddenly believing the sub module's name is:

```
<dependency>
<groupId>com.mikepenz</groupId>
<artifactId>library-core</artifactId>
<version>3.2.6</version>
<scope>compile</scope>
</dependency>
```

nice :D ^^ oh gosh...
