### ISSUE TITLE
Expandable Recycler View using Kotlin (Question)

### ISSUE THREAD

**Issue by Kaz32** [mikepenz/FastAdapter#623]
hi Mike, 

Thanks for this wonderful library

I try expandable recyclerView(using Kotlin) based on your ExpandableSampleActivity
but fail when add the item 

Fail in this line
items.add(SimpleSubItem()

```
val items = ArrayList<IItem<*, *>>()

items.add(SimpleSubItem()
.withName("Test " + i)
.withIdentifier(identifier.getAndIncrement().toLong()))
```

SimpleSubItem class : 
```
open class SimpleSubItem<Parent> 
: AbstractExpandableItem<Parent, SimpleSubItem.ViewHolder,  SimpleSubItem<Parent>>()
, IDraggable<SimpleSubItem<*>, IItem<*, *>>
where Parent : IItem<*, *>,  Parent: IExpandable<*, *>,  Parent: ISubItem<*, *>,  Parent: IClickable<*> {

...

}
```

Type inference failed: Not enough information to infer parameter Parent in constructor SimpleSubItem

Question : How to add SimpleSubItem on Kotlin?
Sorry I'm still new on Kotlin

Thanks,
Eric

**Comment by mikepenz** [comment]
@Kaz32 sorry no support for kotlin questions. seems to be kotlin specific, and you might want to look up the kotlin documentation on these generic questions.

**Comment by mikepenz** [comment]
perhaps @AllanWang or @FabianTerhorst have suggestions as they use kotlin

**Comment by AllanWang** [comment]
Similar to #624. If I find anything I will post there

**Comment by Kaz32** [comment]
Thanks @mikepenz. @AllanWang , read your reply on #623 -- thanks

**Comment by Kaz32** [comment]
`
val items = ArrayList<IItem<*, *>>()

items.add(SimpleSubItem<SimpleSubItem<*>>()
.withName("Test " + i)
.withIdentifier(identifier.getAndIncrement().toLong()))

`
