### ISSUE TITLE
why FastAdapterDiffUtil can't use ModelAbstractItem instead of ModelItem?

### ISSUE THREAD

**Issue by gpulido** [mikepenz/FastAdapter#625]
I'm trying to use the FastAdapterDiffUtil and I realized that it only work with ModelItem descendant.
I've reviewed the code and I didn't found any reason to not make it work with ModelAbstractItem descendant. Is there any specific reason that forbid it?

Thank you in advance,
Gabriel

**Comment by mikepenz** [comment]
@gpulido the `FastAdapterDiffUtil` uses generics. it does not force any specific model or any specific item. 

and `ModelAbstractItem` by the way anyways implements `IModelItem` 

So I am not sure about the issue?

**Comment by gpulido** [comment]
Hello,
It is my fault I didn't read right the error of the compiler. My problem is that I'm trying to pass a list of models not items. So the question changes.
I have the following:
```Kotlin
private lateinit var fastAdapter: FastAdapter<IItem<*,*>>
val itemAdapter = ModelAdapter(IInterceptor<Any, IItem<*,*>> { o ->
        if (o is String) {
            HeaderItem(o)
        } else
            ArcherItem(o as Archer)
    })
```
where ArcherItem is just:
```Kotlin

class ArcherItem(val archer:Archer): ModelAbstractItem<Archer, ArcherItem, ArcherItem.ViewHolder>(archer)
{...}
```
and HeaderItem
```Kotlin
open class HeaderItem<T>(val model2: T):  ModelAbstractItem<T, HeaderItem<T>, HeaderItem.ViewHolder>(model2)
{}
```

And I trying to dinamically create header items using the following code:
```Kotlin
 archerListViewModel.results.observe(this, Observer {
            val a = it?.toList()!!.groupBy { it.name }.map{ listOf(it.key).union(it.value)}.flatten()
            FastAdapterDiffUtil.set(itemAdapter, a)          
        })
```
(where `it` is is a RealmLiveData<List<Archer>>)
if I just do a "itemAdapter.set(a)" it works
