### ISSUE TITLE
Multi-type viewholder in concrete position support

### ISSUE THREAD

**Issue by ebabenskas** [mikepenz/FastAdapter#627]
I’m searching library for multi type viewholder adapter and I found your library. It looks promising so I have question if it is possible to do with your library. 
Now I have adapter with a lot of different view types. 
For example: A, B, C views, but those views should be in concrete different position in list. 
For example: 
A - in header (position 0),
B -  in he middle  and in the end of list (in 15 position if list size > 30 and  always in the end) 
and C - in the other position of the list. 
Now the logic is complex and I want simplify this part. I searched for some examples of your library but I didn't completely understand if it is possible.
So if it is possible to do with you library if I need to create different “ItemAdapter” for each views? But how I could specify concrete item position for each “item adapter” ? 
Thanks for any help!

**Comment by AllanWang** [comment]
From my experience, you typically add multiple ItemAdapters if you have defined sections containing an arbitrary number of items. In your case, you namely hae items of type `C`, with some special item `A` and `B`.

I recommend you just use a generic `ItemAdapter` taking the superclass, add items of the type you need at the position you want, and then checking type instance when you need to handle an event. 

Note that the generic level only needs to be as specific as you need it to be. If you don't handle events through fastadapter, you don't need to worry about the generic.

**Comment by AllanWang** [comment]
If your items are more related and have the same input, you may consider looking at the [ModelIItems](https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/ModelItemActivity.java)

**Comment by ebabenskas** [comment]
@AllanWang Thanks for answer. The views are different so I think the best option would be to use different adapters.

**Comment by mikepenz** [comment]
@ebabenskas theoretically you can also have a generic adapter which will just handle all items type of `IItem` you simply have to cast then in the listeners for example
