### ISSUE TITLE
How to select all parent if child selected

### ISSUE THREAD

**Issue by Kaz32** [mikepenz/FastAdapter#629]
Hi Mike,

I'm using expandable list item

How to select all parent if child selected?

I'm add check image so if item selected -> show check image (from isSelected)
I can check on child item (the bottom level)

But how to select all of it parent? (want to add check image also on it parent, if all child unselected -- parent also unselect)
 Any tips?

Thanks,
Eric

**Comment by mikepenz** [comment]
@Kaz32 nothing like this is inside the library itself you will have to implement it. 

you might be able to use the new `recursive` functionality. 

Or you look into the `SubItemUtil` there is a sample which has some things which might help you. 

`Expandable MultiSelect Delete Sample` of the sample app ;)

**Comment by Kaz32** [comment]
Thanks @mikepenz , I will try your suggestion
