### ISSUE TITLE
Expandable with 3 level child

### ISSUE THREAD

**Issue by Kaz32** [mikepenz/FastAdapter#630]
Hi,

I try use expandable list view with 3 level child, there is problem if expand to the bottom child -- then collapse the top parent. Then not all child closed.

Thanks,
Eric

**Comment by mikepenz** [comment]
@Kaz32 can you reproduce this in the sample?
I tested something with at least 3 levels :O

**Comment by Kaz32** [comment]
@mikepenz yes I add 1 level base on your sample (ExpandableSampleActivity)
