### ISSUE TITLE
Payload not passed to items

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#631]
## About this issue

I don't get the payloads in my items. So far I made sure that following preconditions are met:

* items have a stable id
* no `ItemAnimator` is set

*Setup*

	mAdapter = new EndlessFastItemAdapter<IItem>();
	mAdapter
			.withEndlessScroll(endlessScroll)
			//.withPositionBasedStateManagement(false)
			.withEventHook(new DisplayedItem.ItemEvent(this, true));
	mAdapter.set(SidebarUtil.getDisplayedSidebarItems(mSidebarItemsFiltered, showSections, showSectionsCounter, mHandle, mSidebar, mFilter, mSidebarCalculator));

	int rowHeight = (getScreen().y - mSidebar.calcPagePaddingTop(getContext()) - mSidebar.calcPagePaddingBottom(getContext())) / pageRows;
	int headerHeight = (int) getContext().getResources().getDimension(R.dimen.header_height);
	mFastScrollAdapter = new FastScrollIndicatorAdapter<>(pageCols, rowHeight, headerHeight);
	// make sure adapters has stable ids
	mAdapter.setHasStableIds(true);
	rvSidebar.setAdapter(mFastScrollAdapter.wrap(mAdapter));

    rvSidebar.setItemAnimator(null);
    rvSidebar.setAnimation(null);
    rvSidebar.setLayoutAnimation(null);
	
*Item*

	public class DisplayedItem extends AbstractItem<DisplayedItem, DisplayedItem.ViewHolder> implements IDraggable<DisplayedItem, DisplayedItem> {
	
		private DisplayedItem(IFolderOrSidebarItem data, ...) {

			// make sur ewe have stable ids even for new items with the same data
			withIdentifier(data.getRowId());
		}
	}
	
*Filtering*

	public void onFilter(FilterJob.FilterEvent event) {
		mAdapter.set(event.items);
		
		// first time filtering, we notify all items without payload
		if (event.init) {
			mFastScrollAdapter.notifyDataSetChanged();
		} else {
			mFastScrollAdapter.notifyItemRangeChanged(0, mFastScrollAdapter.getItemCount(), DisplayedItem.SELECTED_TEXT_CHANGED_ONLY);
		}
    }

So don't see any reason why the `RecyclerView` should not reuse my views. I'm filtering in a background job manually, create new items (data items) in there and then update my adapter. Any ideas what else could break the payload here?

## Details
- Used library version: 3.2.2
- Used support library version: 26.1.0
- Used gradle build tools version: 4.4.1
- Used tooling / Android Studio version: 3.0.1
- Other used libraries, potential conflicting libraries

**Comment by mikepenz** [comment]
@MFlisar does the `notify` also happen on the background job? This might be the cause of the issue. 

Otherwise. usually the `ItemAnimator` could alter that behaviour. (but you already disabled it) 

Other than this I don't see a reason why the `RecyclerView` shouldn't forward it. 

This is a RecyclerView "problem" though, as the `FastAdapter` itself only forwards the payload to the notify method, and then forwards it in the item. So it actually does not adjust any of this behaviour :) 


Please let me know if you figure out more. Would be interesting

**Comment by MFlisar** [comment]
Notification is done on main thread

It looks like `FastItemAdapter.set` already triggers notifications, because my `RecyclerView` is updating if I change my filter code to following:

    public void onFilter(FilterJob.FilterEvent event) {
        mAdapter.set(event.items);
        // no notifying here!
    }

No need for notifying the adapter. Is this the normal behaviour? I thought if I use `set` instead of `setNew` I'm responsible to to notify the adapter about changes manually

**Comment by mikepenz** [comment]
@MFlisar no all methods of the `adapter` call the notify methods accordingly

**Comment by MFlisar** [comment]
If I want to replace all items with a new list AND use a payload, is this possible?

**Comment by mikepenz** [comment]
@MFlisar no. The `RecyclerView.Adapter` does not provide a `notify` method with payload.

**Comment by mikepenz** [comment]
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyDataSetChanged()
