### ISSUE TITLE
Custom DiffUtils Class

### ISSUE THREAD

**Issue by judemanutd** [mikepenz/FastAdapter#632]
I have written my custom DiffUtils class and would like to use it with fast adapter, i have followed this snippet [https://github.com/mikepenz/FastAdapter/blob/bd47e4e990f8c266441c8def10c6337012461947/app/src/main/java/com/mikepenz/fastadapter/app/DiffUtilActivity.java#L129](url) .
I would like to know if it is possible to dispatch the DiffResult to the adapter by just supplying the fastAdapter like so
`result.dispatchUpdatesTo(fastAdapter);`
or do i have to include the commons library and use that to dispatch DiffUtils events.

**Comment by mikepenz** [comment]
For best support you should use the `FastAdapterDiffUtil` as it will work properly in a case with multiple child adapters. 

If you only have 1 adapter managing the items in your `FastAdapter` `dispatchUpdatesTo` should be working fine.

**Comment by judemanutd** [comment]
@mikepenz does it work even if i am using a custom data type adapter ie, a model adapter?

**Comment by mikepenz** [comment]
The FastAdapterDiffUtil will work with a `ModelAdapter` 

the default one from the support libs not.

**Comment by judemanutd** [comment]
Thanks.
