### ISSUE TITLE
Proguard problem

### ISSUE THREAD

**Issue by Dahnark** [mikepenz/FastAdapter#633]
```
Warning:com.mikepenz.fastadapter.commons.utils.FastAdapterDiffUtil: can't find referenced method 'com.mikepenz.fastadapter.IItemList getItemList()' in program class com.mikepenz.fastadapter.adapters.ModelAdapter
Warning:com.mikepenz.fastadapter.commons.utils.FastAdapterDiffUtil: can't find referenced class com.mikepenz.fastadapter.utils.ComparableItemListImpl
```

My proguard file:

```
-keep class butterknife.*
-keepclasseswithmembernames class * { @butterknife.* <methods>; }
-keepclasseswithmembernames class * { @butterknife.* <fields>; }

-keep class com.crashlytics.** { *; }
-dontwarn com.crashlytics.*

-dontwarn com.mikepenz.fastadapter_extensions.items.*
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.ParametersAreNonnullByDefault
```

I added the three last lines to try to resolve this problem. Without them, it is not working too.

**Comment by AllanWang** [comment]
What version are you using for the fastadapter dependencies and for appcompat? Does this work in debug mode without proguard?

**Comment by Dahnark** [comment]
I have the latest version of all fastadapter dependencies and appcompat.

`-dontwarn com.mikepenz.fastadapter.**`

This fixes the problem in release mode, debug mode is working perfectly

**Comment by Dahnark** [comment]
@mikepenz the last update fixes the problem?

**Comment by mikepenz** [comment]
@Dahnark it adds a `-dontwarn` for the package which contains the DiffUtils so it should yes.
