### ISSUE TITLE
Can't get the selected items from long click

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/FastAdapter#634]
Hi, i use the example from **MultiSelectSampleActivity**, works fine, but when i use the selectedExtension to get the selected items, all the items are **selected = false**

i use the selectedExtension like this :
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SampleActivity.java

## Details
- [3.2.2 ] Used library version
- [ 27.0.2] Used support library version
- [3.0.1 ] Used gradle build tools version
- [ 3.0.1] Used tooling / Android Studio version

**Comment by mikepenz** [comment]
Thanks @AllanWang for answering.

@seba123neo the sample as you linked works correctly. 

See the line it returns the proper selections:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiselectSampleActivity.java#L87

+ they are selected and are `mSelected` == true

<img width="1233" alt="screen shot 2018-02-04 at 12 35 04" src="https://user-images.githubusercontent.com/1476232/35777092-0f81eb60-09a8-11e8-86b2-b058d8ebc776.png">

**Comment by seba123neo** [comment]
Sorry, thanks for answering, I was a couple of hours until I realized I had the mode.finish() in the function what made me deselect all the items !!!
