### ISSUE TITLE
Add a non sticky header element 

### ISSUE THREAD

**Issue by judemanutd** [mikepenz/FastAdapter#635]
I want to display a viewpager always as the first element of the recycler view and then a list of elements after the viewpager but i do not want the viewpager to be sticky.
Is it possible to do such a thing with the adapter.

**Comment by mikepenz** [comment]
@judemanutd I do not really understand the question. 

The FastAdapter does NOT contain sticky items. 

You can have a item at the first position. nothing prevents you from putting different items at different positions. You can also for example work with multiple adapters. the first adapter has an item at position 1. 

check out the sample. It has a demo which include multiple adapters. 

You can at any point use different items in the same adapter without issues.

**Comment by judemanutd** [comment]
My current implementation of the recyclers view includes fetching data from a realm list and populating the adapter, which works fine.
The list contains views of different types which I have handled using the model adapter.
Now instead of adding a special view at the first element every time the data set changes, is it possible to fix the first element such that it is always of a particular type and the rest of the elements are populated from he dataset. I hope I was able to make things clearer.

**Comment by judemanutd** [comment]
![screenshot_2018-02-03-21-58-59-491_com abc abcnews](https://user-images.githubusercontent.com/12494890/35769218-d6531280-092d-11e8-8b12-5317aa3139d5.png)


Basically  i am trying to replicate a view like this. My default data set does not contain the big size image element type, I do not want to add it everytime the dataset changes, which can be costly since i will have to move every element by 1 to accommodate the new big size element.

**Comment by judemanutd** [comment]
@mikepenz This is my code so far, i am using a ModelAbstractItem for NewsAdapterModel since it consists of views of different types.

`    public class NewsAdapterModel extends ModelAbstractItem<News, NewsAdapterModel, 
    NewsItem_VH>
     {
...
    }`

In my main activity
   ` //This is a pageradapter that i want to use for the viewpager`
   ` PinnedArticlesAdapter picturesAdapter = new PinnedArticlesAdapter();`
    `final ItemAdapter headerAdapter = new ItemAdapter();`
    `headerAdapter.add(new HeaderAdapter(picturesAdapter).withIdentifier(1));`
    `FastAdapter<NewsAdapterModel> fastAdapter = = FastAdapter.with(Arrays.asList(headerAdapter, itemAdapter));`

The HeaderAdapter is a class that looks like this

`public class HeaderAdapter extends AbstractItem<HeaderAdapter, Header_VH> {....}`

The HeaderAdapter contains the viewpager who's adapter is being passed in the HeaderAdapter constructor.

Following this method i get an error in the logcat at the line `headerAdapter.add(new HeaderAdapter(picturesAdapter).withIdentifier(1));`

`java.lang.NullPointerException: Attempt to invoke virtual method 'int com.mikepenz.fastadapter.FastAdapter.getPreItemCountByOrder(int)' on a null object reference`

What exactly am I doing wrong here?

**Comment by mikepenz** [comment]
@judemanutd for the above view you might also just consider nested scrolling, where the recyclerview with the items is just a child in a `ScrollView` for example. 
So you can use a normal view on top with the viewPager, and a normal RecyclerView on the bottom. 

As for the crash you see. I am not sure what exactly you are doing. 

But the `MultiselectSample` showcases exactly this case. 

1 Header item. 
X Items

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiselectSampleActivity.java#L58

**Comment by judemanutd** [comment]
@mikepenz had tried the nested scroll solution but failed since the nested scroll can only have a singe child and that would mean i needed to put the recyclerview and the children in a linear or relative layout because of which i lost the endless scrolling events.
Will take a look at the multiselect sample.

**Comment by mikepenz** [comment]
You would have 

```xml
<ScrollView>
   <LinearLayout>
      <HeaderView />
      <RecyclerView>
          <RVItem/>
       <RecyclerView/>
   <LinearLayout>
<ScrollView/>
```

That will consume the endless scroll events on the RecyclerView?

**Comment by judemanutd** [comment]
That wasn't really working but managed to get it working with this layout for now.

       `<android.support.design.widget.CoordinatorLayout 
                     xmlns:android="http://schemas.android.com/apk/res/android"
	  	    xmlns:app="http://schemas.android.com/apk/res-auto"
		    xmlns:tools="http://schemas.android.com/tools"
		     android:layout_width="match_parent"
		    android:layout_height="match_parent">

		<android.support.design.widget.AppBarLayout
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:background="@android:color/transparent">

			<android.support.design.widget.CollapsingToolbarLayout
				android:layout_width="match_parent"
				android:layout_height="wrap_content"
				app:layout_scrollFlags="scroll|exitUntilCollapsed">

				<android.support.v4.view.ViewPager
					android:id="@+id/viewpager"
					android:layout_width="match_parent"
					android:layout_height="200dp"
					android:layout_marginTop="?attr/actionBarSize" />

				<android.support.v7.widget.Toolbar
					android:layout_width="match_parent"
					android:layout_height="wrap_content"
					app:contentInsetLeft="0dp"
					app:contentInsetStart="0dp"
					app:layout_collapseMode="pin"/>

			</android.support.design.widget.CollapsingToolbarLayout>

		</android.support.design.widget.AppBarLayout>

		<android.support.v4.widget.SwipeRefreshLayout
			android:id="@+id/swipeContainer"
			android:layout_width="match_parent"
			android:layout_height="match_parent"
			app:layout_behavior="@string/appbar_scrolling_view_behavior">

			<android.support.v7.widget.RecyclerView
				android:id="@+id/newsList"
				android:layout_width="match_parent"
				android:layout_height="match_parent"
				tools:listitem="@layout/item_news" />

		</android.support.v4.widget.SwipeRefreshLayout>

	</android.support.design.widget.CoordinatorLayout>`
