### ISSUE TITLE
getSelections and getSelectedItems deprecated on Sample

### ISSUE THREAD

**Issue by bernaferrari** [mikepenz/FastAdapter#636]
I updated FastAdapter in my apps and suddenly all "getSelections" got deprecated. I got confused with  which parameter "getExtension" needs, so went ahead to Sample app and.. it is also showing the warning deprecated messages.
Could someone please update it, so I can fully understand the changes?

**Comment by mikepenz** [comment]
@bernaferrari you can still use it. I am not removing it before v3. And until then I will slowly migrate in the process. 

As noted in the deprecation note: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1083

Use `getExtension()` and retrieve the `SelectExtension` which offers exact the same functions as the proxy methods on the `FastAdapter`

**Comment by bernaferrari** [comment]
It took me a while to remember/figure out I should use SelectExtension**.class**. Sorry/Thanks!
