### ISSUE TITLE
Cannot call this method while RecyclerView is computing a layout or scrolling

### ISSUE THREAD

**Issue by Dahnark** [mikepenz/FastAdapter#638]
```
fastAdapter.withOnClickListener((v, adapter, item, position) -> {
                ...
            });
```

This is caused when this is running (OnPostExecute method from my AsyncTask):

```
for (int i = fastAdapter.getAdapterItemCount(); i < items.size(); i++) {
                    fastAdapter.add(items.get(i));
                    fastAdapter.notifyItemInserted(i);
                }
```

**Comment by Dahnark** [comment]
I "solved" it moving this `fastAdapter.withOnClickListener...` to the onPostExecute method.

**Comment by mikepenz** [comment]
@Dahnark yeah makes sense. a notify is not possible while you adjust the list. 

so a selection is not supposed to happen. 

That's basically a limitation of the `RecyclerView`'s approach
