### ISSUE TITLE
Proguard Duplicate zip entry IExpandable.class

### ISSUE THREAD

**Issue by Shakezulla57** [mikepenz/FastAdapter#640]
Getting proguard warning with new version. I saw that `IExpandable` was added in the FastAdapter library, so I'm assuming there is some conflict with MaterialDrawer.

Here's how I'm including the libraries.
```
   implementation('com.mikepenz:materialdrawer:6.0.0@aar') {
        transitive = true
        exclude module: "fastadapter"
    }
    implementation("com.mikepenz:fastadapter:3.2.4@aar") {
        transitive = true
    }
    implementation "com.mikepenz:fastadapter-commons:3.2.4@aar"
    implementation "com.mikepenz:fastadapter-extensions:3.2.4@aar"
    implementation 'com.mikepenz:materialize:1.1.2@aar'

   configurations.all {
      resolutionStrategy.force "com.mikepenz:fastadapter:3.2.4"
   }
```

```
#fastadapter
-dontwarn com.mikepenz.fastadapter.**
-dontwarn com.mikepenz.fastadapter_extensions.items.**
```
What's the best method of avoiding this collision?

**Comment by mikepenz** [comment]
You have a conflict with `MaterialDrawer` v6.0.0 

Please either use the latest `MaterialDrawer` which uses the latest `FastAdapter` 

Or add all modules of the fastadapter to the `resolutionStrategy` :)
