### ISSUE TITLE
EndlessRecyclerOnScrollListener causes binding to not occur until scroll

### ISSUE THREAD

**Issue by eygraber** [mikepenz/FastAdapter#643]
## About this issue

- Briefly describe the issue - If I add a `EndlessRecyclerOnScrollListener` to the `RecyclerView`, when the fast adapter calls `notifyItemRangeChanged(0, 1, null)`, `bindView` isn't called until I scroll the `RecyclerView` a little bit

Everything is getting called on the thread it's supposed to, and I can get this to stop by either commenting out my `addScrollListener`, or not adding a `ProgressItem` in the `EndlessRecyclerOnScrollListener`.

```
private val endlessScrollListener = object : EndlessRecyclerOnScrollListener(endlessScrollAdapter) {
    override fun onLoadMore(currentPage: Int) {
//      endlessScrollAdapter.clear()
//      endlessScrollAdapter.add(ProgressItem())

      observeSessions(page = currentPage.toLong() + 1)
    }
  }
```

## Details
- [ ] Used library version - 3.2.4
- [ ] Used support library version - 27.0.2

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@eygraber independent of the issue you should use the `FastAdapter` provided notify methods. (like notifyAdapterItemChanged...) 

It sounds strange. can it be that the item 0 and 1 are not really visible? 

As you can see herE: https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnScrollListener.java it is just a default scroll listener which will not prevent default behaviour. only in addition trigger the according listeners when a specific limit is reached

**Comment by eygraber** [comment]
I do, I was just referring to what `FastAdapter` calls internally. 

They're definitely visible on the screen; I stared at them for a good 5 minutes waiting for updates to bind, but they never did. I also verified that the backing items data changed. It just never got bound.

**Comment by mikepenz** [comment]
@eygraber do you have a item animator set. that one might also fool the layoutmanager of giving the RV the proper info to rebind. 

Do you have an equals implementation: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/items/AbstractItem.java#L323 ? perhaps there is something going on because it is still equal to before?

Do you items have proper identifiers?

**Comment by mikepenz** [comment]
Was this also related to the other issue you had in that hackathon? 

Is this still relevant? Please comment if we need to re-open it.

**Comment by atulgoswami21** [comment]
Same Issue here.
