### ISSUE TITLE
Trying to set visibility of row items when entering multiselect mode

### ISSUE THREAD

**Issue by dev2961io** [mikepenz/FastAdapter#645]
So for now each of my rows also has a checkbox with visibility gone. What I am trying to achieve is to change the visibility of all checkboxes when entering multiselect mode and when the multiselect is done hide them. For now what I have achieved is this
```
invoicesAdapter.withOnClickListener(new OnClickListener<InvoiceItem>() {
            @Override
            public boolean onClick(@Nullable View v, IAdapter<InvoiceItem> adapter, InvoiceItem item, int position) {
                invoicesAdapter.notifyItemChanged(position);
                return false;
            }
        });
```
So each time an item is clicked I rerender it
```
@Override
    public void bindView(InvoiceViewHolder holder, List<Object> payloads) {
        super.bindView(holder, payloads);

        //get the context
        Context context = holder.itemView.getContext();

        //set the background for the item
        StateListDrawable stateListDrawable =
                FastAdapterUIUtils.getSelectableBackground(context, context.getResources().getColor(R.color.listItemSelectedState), true);

        UIUtils.setBackground(holder.itemView, stateListDrawable);

        holder.selectInvoice.setChecked(isSelected());
        holder.invoiceNumber.setText(invoiceNumber);
        holder.invoiceAmount.setText(invoiceAmount);
        holder.invoiceStatus.setText(invoiceStatus);


        setStatusColor(invoiceStatus, context, holder);
    }
```
Any ideas on the best way to display all checkboxes and hide them on multiselect mode changes?
Thank you for your time!

**Comment by mikepenz** [comment]
@dev2961io so instead for a single item you want to do it for all items?

By the way you should use the `notifyAdapter*` methods if you use the fastAdapter. :D

but independent of this, the best solution would be to notifyItemRangeChanged and pass over a `payload` so you only change the visibility of this view and don't update the whole item

**Comment by dev2961io** [comment]
@mikepenz the issue is not checking the item's checkbox when the item is selected in multiselect. The issue is that by default the checkbox is hidden, but I do not know how to go about making all the checkboxes visible when the multiselect mode starts (onlongclick) and after the last item has been unselected to hide all the checkboxes. I mean how can I send a flag in in the viewholder to check if multiselect mode is on? or what should i do?

**Comment by dev2961io** [comment]
Also instead of firing actionmode when multiselect mode starts how can I listen for the event so I can show icons in my current options menu (I want to do this because my current toolbar has a drawable as background and I cannot achieve this in actionmode)

**Comment by mikepenz** [comment]
If you can't use an actionMode for your case. then don't? 

This is not really related to this library then. It's simple handling of a Toolbar :P

But coming to the main question. you notify that the items chagne diwth a payload (standard android adpater feature) and then you react on this notify with the payload. 

Otherwise you can add some flag to the items which you ahve to set. or you have some global flag which is known. there are many solutions which will lead to your targeted result

**Comment by dev2961io** [comment]
Ok but in case of the flag on items when entering multiselect mode I will have to loop through all the items and change the flag. My question is in the case of a global flag where should I put it and how to change it's value. Because in this case I cannot access an adapter on which to set variables, I only have the item mode. Plus in orderd to hide all of the checkboxes when the multiselect mode is on I need to know when multiselect event ends. Is there any way of finding that out?

**Comment by mikepenz** [comment]
@dev2961io the same as for a normal adapter applies. either you have the information in all items, or you have it global (as static variable somewhere) or you extend the adapter, so that one is aware of it and will act accordingly in the bind methods.
