### ISSUE TITLE
Should I update fast adapter or item adapter

### ISSUE THREAD

**Issue by judemanutd** [mikepenz/FastAdapter#646]
## About this issue

I am using realm to populate and maintain changes to the list using the `OrderedRealmCollectionChangeListener` but i am not sure which adapter i need to be sending the updates to once realm notifies me.

This is my code

Class variables

	private OrderedRealmCollectionChangeListener<RealmResults<News>> changeListener;
	private RealmResults<News> newsRealmResults;
	private ModelAdapter<News, ModelAbstractItem<News, ?, ?>> itemAdapter;
	private ItemAdapter footerAdapter;
	private FastAdapter<NewsAdapterModel> fastAdapter;

Change listener

		changeListener = (collection, changeSet) -> {
					if (changeSet == null) {
						return;
					}
		
					OrderedCollectionChangeSet.Range[] insertions = changeSet.getInsertionRanges();
            for (OrderedCollectionChangeSet.Range range : insertions) {
                int position = range.startIndex;

                for (int i = 0; i < range.length; i++) {
                    if (adapterPositions.indexOfKey(collection.get(position).getId()) < 0) {
                        itemAdapter.add(position, collection.get(position));
                        updateAdapterPositions();
                    } else {
                        int oldPosition = adapterPositions.get(collection.get(position).getId());
                        Log.i("Realm", "inserting exists " + collection.get(position).getId() + " old position=" + oldPosition);
                        //fastAdapter.notifyItemChanged(oldPosition);
                        itemAdapter.move(oldPosition, position);
                        updateAdapterPositions();
                    }
                    position++;
                }

            }

            OrderedCollectionChangeSet.Range[] modifications = changeSet.getChangeRanges();
            for (OrderedCollectionChangeSet.Range range : modifications) {
                int position = range.startIndex;
                for (int i = 0; i < range.length; i++) {
                    //fastAdapter.notifyItemChanged(position);
                    position++;
                }
            }

            OrderedCollectionChangeSet.Range[] deletions = changeSet.getDeletionRanges();
            for (int i = deletions.length - 1; i >= 0; i--) {
                OrderedCollectionChangeSet.Range range = deletions[i];
                //itemAdapter.removeRange(range.startIndex, range.length);
                fastAdapter.notifyAdapterItemRangeRemoved(range.startIndex, range.length);
            }

        };

The initialization of the adapter is as follows

 		itemAdapter = new ModelAdapter<>(news -> new NewsAdapterModel(news, GlideApp.with(getCustomContext())));

        fastAdapter = FastAdapter.with(itemAdapter);
        footerAdapter = items();
        fastAdapter.addAdapter(1, footerAdapter);
        fastAdapter.withSelectable(true);
        linearLayoutManager = new LinearLayoutManager(getCustomContext());
        linearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        recyclerView.setLayoutManager(linearLayoutManager);
        recyclerView.setItemAnimator(new DefaultItemAnimator());
        DividerItemDecoration itemDecoration = new DividerItemDecoration(getCustomContext(), DividerItemDecoration.VERTICAL);
        itemDecoration.setDrawable(ContextCompat.getDrawable(getCustomContext(), R.drawable.news_list_divider));
        recyclerView.addItemDecoration(itemDecoration);

        fastAdapter.withOnClickListener(this);

        recyclerView.setAdapter(fastAdapter);
		
		final Handler handler = new Handler();

        final EndlessRecyclerOnScrollListener endlessRecyclerOnScrollListener = new EndlessRecyclerOnScrollListener(footerAdapter) {
            @Override
            public void onLoadMore(final int currentPage) {
                handler.post(() -> {
                    footerAdapter.clear();
                    footerAdapter.add(new ProgressItem().withEnabled(false).withIdentifier(Long.MAX_VALUE - 1));
                });
                fetchNews();
            }
        };
        recyclerView.addOnScrollListener(endlessRecyclerOnScrollListener);
        refreshLayout.setOnRefreshListener(this);

Should i be notifying just the fast adapter for the changes that are made or just the item adapter or both? The item adapter is the one that i add the data to.

## Details
- [ 3.2.4 ] Used library version
- [ 27.0.2 ] Used support library version
- [ 3.0.1 ] Used gradle build tools version
- [ 3.0.1 ] Used tooling / Android Studio version
- [ none ] Other used libraries, potential conflicting libraries

**Comment by mikepenz** [comment]
The `ItemAdapter` will call the correct notify methods on the adapter accordingly. 

(A add will notify about new items, remove about removed items, ....)
