### ISSUE TITLE
method does not override method from its superclass

### ISSUE THREAD

**Issue by rajarockz** [mikepenz/FastAdapter#649]
## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Please write a proper github issue. Close until all the requested details are filled out

**Comment by rraikarnvi** [comment]
This happens when I try to override bindview or unbindview in class item which extends AbstractExpandableItem.  As soon as I override bindview/unbindview this pops up
Error:(41, 5) error: method does not override or implement a method from a supertype

**Comment by rraikarnvi** [comment]
I have found a way to reproduce it. change the view holder class from static to normal. Thats what gives. the issue. idk y but this gives error @mikepenz
