### ISSUE TITLE
How to use Multiple ItemAdapter

### ISSUE THREAD

**Issue by suryaadiputra** [mikepenz/FastAdapter#652]
## Problem using Multiple Item Adapter
Im using FastAdapter to create RecycleView with Header and Content. Header layout using Item with Sliding View Pager, and content with list. But when process adding item always show an error..
ContentItem$ContentViewHolder cannot be cast to HeaderItem$HeaderViewHolder.
What wrong with the code??

```
FastAdapter fastAdapter;
private ItemAdapter<ContentItem> mItemAdapter;
private ItemAdapter<HeaderItem> headerAdapter;

headerAdapter = items();
mItemAdapter = items();
fastAdapter = FastAdapter.with(Arrays.asList(headerAdapter, `mItemAdapter));

```
sorry for bad English..

**Comment by suryaadiputra** [comment]
same #644

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiselectSampleActivity.java#L62
