### ISSUE TITLE
How scroll to header (with stickyHeaderAdapter) [question]

### ISSUE THREAD

**Issue by Kaz32** [mikepenz/FastAdapter#653]
Hi Mike,

I'm using header with stickyHeaderAdapter, how to programmatically scroll to specific header? 

Thanks,
Eric

**Comment by mikepenz** [comment]
@Kaz32 that's not a `Adapter` specific issue. Scrolling and scroll to position is related to the `LayoutManager` 

See here: https://developer.android.com/reference/android/support/v7/widget/LinearLayoutManager.html#scrollToPosition(int)

**Comment by Kaz32** [comment]
@mikepenz thanks for the reply, 
For getting header position -> I should loop the list items and get first occur of header text on item?
