### ISSUE TITLE
fastAdapter.withOnClickListener Type mismatch in Kotlin

### ISSUE THREAD

**Issue by Chrylo** [mikepenz/FastAdapter#654]
## About this issue

Hi Mike, I am trying to use a custom OnClickListener to remove the element clicked on. I currently have a problem with this which is probably "only" Kotlin related.

I want to use withOnClickListener with a concrete Item implementation but always get:
**Type mismatch:
Required: OnClickListener<IItem<*,*>!>!
Found: NotificationsFragment.NotificationItemClickListener**

But the OnClickListener should support that interface?

```
itemAdapter = FastAdapterExtension.createDefaultItemAdapter()
val fastAdapter = FastAdapterExtension.createDefaultAdapter(itemAdapter)
recyclerView.adapter = fastAdapter
fastAdapter.withOnClickListener(
       { v, adapter, item, position ->
               Log.d(TAG, "Clicked on item position: $position")
               itemAdapter.remove(position)
               fastAdapter.notifyAdapterItemRemoved(position)
               true
       })

  showNotification()
  showNotification()
  ...

private fun showNotification()
{
     val notificationItem = NotificationItem()
     itemAdapter.add(notificationItem)
     itemAdapter.fastAdapter.notifyAdapterItemInserted(itemAdapter.adapterItemCount)
}

class FastAdapterExtension
{
    companion object
    {
        fun createDefaultItemAdapter(): ItemAdapter<IItem<*, *>>
        {
            return ItemAdapter()
        }

        @JvmOverloads
        fun createDefaultAdapter(itemAdapter: IAdapter<out IItem<*, *>> = createDefaultItemAdapter())
                : FastAdapter<IItem<*, *>>
        {
            return FastAdapter.with<IItem<*, *>, IAdapter<out IItem<*, *>>>(itemAdapter)
        }
    }
}

   fastAdapter.withOnClickListener(NotificationItemClickListener())
   inner class NotificationItemClickListener : OnClickListener<NotificationItem>
    {
        override fun onClick(
                v: View?,
                adapter: IAdapter<NotificationItem>,
                item: NotificationItem,
                position: Int): Boolean
        {
            itemAdapter.remove(position)
            adapter.fastAdapter.notifyAdapterItemRemoved(position)
            return true
        }
    }

class NotificationItem() : AbstractItem<NotificationItem, NotificationItem.NotificationViewHolder>()
```

## Details
- [3.2.4 ] Used library version
- [27.0.2] Used support library version
- [3.2.0-alpha05] Used gradle build tools version
- [3.1-RC1] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist
I found the following discussion: https://github.com/mikepenz/FastAdapter/issues/558
I hopefully just overlooked something, thanks in advance! :)

**Comment by Chrylo** [comment]
I think this has something to do with initilaizing the FastAdapter.
It should probably be something with NotificationItem as generic type.

`FastAdapter.with<IItem<*, *>, IAdapter<out IItem<*, *>>>(itemAdapter)`

**Comment by FabianTerhorst** [comment]
Your OnClickListener type has to match the type of the FastAdapter. You probably need an type that fits for your NotificationItem and when you have several item types, to them as well. When you just need one item type you can use the notification item as an type for the fast adapter as well. Read more here: https://kotlinlang.org/docs/reference/generics.html

**Comment by Chrylo** [comment]
Thanks for the fast reply, you helped me get on the right track. My helper class looks like this now and fixes the problem:

```
class FastAdapterExtension
{
    companion object
    {
        fun <Item : IItem<*, *>> createDefaultItemAdapter() = ItemAdapter<Item>()

        @JvmOverloads
        fun <Item : IItem<*, *>> createDefaultAdapter(itemAdapter: IAdapter<out Item> = createDefaultItemAdapter()) =
                FastAdapter.with<Item, IAdapter<out Item>>(itemAdapter)!!

        fun <Item : IItem<*, *>> createAdapter(vararg adapter: IAdapter<out Item>) =
                FastAdapter.with<Item, IAdapter<out Item>>(adapter.toList())
    }
}
```
