### ISSUE TITLE
How to use FastAdapter to implement a photo grid view with headers (non sticky)? Like Google Photos app?

### ISSUE THREAD

**Issue by smarques84** [mikepenz/FastAdapter#655]
Like i said something like Google Photos app. I tried modifying your MultiselectSampleActivity but when i add more headers all headers show on the top of list and then the content shows after the list of headers, so how do i group them without using your StickyHeader example?

Edit: Okay just found that i can use the same ItemAdapter for both Header and Item and identify them withIdentifier() but how do i add a new photo for that particular section easily?

**Comment by mikepenz** [comment]
It highly depends on the way how you want to manage everything. 

You can go with sticky headers which will automatically group (you need a different lib doing the sticky stuff headers :D)

or you use a itemAdapter per section, (if there are more items than sections). then you can simply have the header at position 0 per section, and the rest items. 

Or you simply keep track on the position of a header and add it as child. 

Or you work with expandable itmes but keep the sections open. 

See the sample app for more infos :)
