### ISSUE TITLE
FastItemAdapter comparator with Generic Item

### ISSUE THREAD

**Issue by guuilp** [mikepenz/FastAdapter#656]
When using header in a recycler view with Fast Adapter, we should declare the FastItemAdapter as Generic, right? Something like this:
`private var playersInFastAdapter = FastItemAdapter<IItem<*, *>>()`

Then I can add more than one type of AbstractItem to the FastItemAdapter.

The question is: Is there any way of using "withComparator" when using generic FastItemAdapter?

**Comment by FabianTerhorst** [comment]
Read https://github.com/mikepenz/FastAdapter/issues/654. Its basically the same question.

**Comment by guuilp** [comment]
I've read #654 but I couldn't understand how it is basically the same question. Sorry.

**Comment by FabianTerhorst** [comment]
Because you have to use an type for your adapter that fits all items that you are going to add to it. This type must also be the same as the comparator type.

**Comment by guuilp** [comment]
What about this?

`playersInFastAdapter.itemAdapter.withComparator(compareBy{ (it as? MatchPlayersIn)?.player?.fullName })`

**Comment by FabianTerhorst** [comment]
When you don´t specify an comparator type, kotlin will most likely use the type of the adapter for the comparator.

**Comment by mikepenz** [comment]
I think this is solved. Please reopen otherwise
