### ISSUE TITLE
Flash item (come back) when swiped ?

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/FastAdapter#658]
See the video Mike

https://1drv.ms/v/s!AmS3ISKApIAigmHujFfOFgazYTNA

the item is removed but "come back"....

**Comment by mikepenz** [comment]
@seba123neo can you please be a bit more precise on what you are doing? 

Code samples?

It does not happen like this in the sample.  I assume it is something related to your implementation, resulting in the item being reset after the swipe happened showing the "standard" state for a blink moment.

**Comment by seba123neo** [comment]
this is the entire adapter item code, (is only a cardview with a few textview inside)

```
public class EstadosAdapter extends AbstractItem<EstadosAdapter, EstadosAdapter.ViewHolder> implements ISwipeable<EstadosAdapter, IItem> {

    public int idCortesia;
    public String fecha;
    public String hora;
    public String dominio;
    public String idCuadra;
    public String idCalle;
    public String nombreCalle;
    public String altura;
    public String cruceCalle;
    public String nombreCruceCalle;
    public String bis;
    public String coordenadaGPS;
    public String enviada;
    public String cerrada;
    public String horaCierre;
    public String motivo;

    public String status;
    public String amo;
    public String zon;
    public String mod;
    public String usu;
    public String veh;

    public String tipo;

    public boolean tieneActa;
    public String horaActa;
    public String zonaDescarga;
    public boolean verificado;

    public int swipedDirection;
    private Runnable swipedAction;
    public boolean swipeable = true;

    @Override
    public int getType() {
        return R.id.fastadapter_estados_id;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.listaestados;
    }

    @Override
    public boolean isSwipeable() {
        return swipeable;
    }

    @Override
    public EstadosAdapter withIsSwipeable(boolean swipeable) {
        this.swipeable = swipeable;
        return this;
    }

    public void setSwipedDirection(int swipedDirection) {
        this.swipedDirection = swipedDirection;
    }

    public void setSwipedAction(Runnable action) {
        this.swipedAction = action;
    }

    public EstadosAdapter() {
        this.idCortesia = 0;
        this.fecha = "";
        this.hora = "";
        this.dominio = "";
        this.idCuadra = "";
        this.idCalle = "";
        this.nombreCalle = "";
        this.altura = "";
        this.cruceCalle = "";
        this.nombreCruceCalle = "";
        this.bis = "";
        this.coordenadaGPS = "";
        this.enviada = "";
        this.cerrada = "";
        this.horaCierre = "";
        this.motivo = "";
        this.status = "";
        this.amo = "";
        this.zon = "";
        this.mod = "";
        this.usu = "";
        this.veh = "";
        this.tipo = "";
        this.tieneActa = false;
        this.horaActa = "00:00";
        this.zonaDescarga = "";
        this.verificado = false;
    }

    @Override
    public void bindView(ViewHolder viewHolder, List<Object> payloads) {
        super.bindView(viewHolder, payloads);

        Context ctx = viewHolder.itemView.getContext();

        String vHora, vMinExp, vMinExpActa = "";
        String vEstado = status;
        String vTipo = tipo;

        if (vTipo.equals("C")) {

            if (zonaDescarga.equals("S")) {
                vHora = Utiles.sumarMinutos(hora, true);
            } else {
                vHora = Utiles.sumarMinutos(hora, false);
            }

            viewHolder.lblMonto.setVisibility(View.GONE);
        } else {
            vHora = hora;

            viewHolder.lblMonto.setText("$ " + amo);
            viewHolder.lblMonto.setVisibility(View.VISIBLE);
        }

        int color;

        if (vEstado.equals("EXP")) {

            if (cerrada.equals("S")) {
                color = ContextCompat.getColor(ctx, R.color.md_green_500);
            } else {
                color = ContextCompat.getColor(ctx, R.color.md_red_500);
            }

            if (tieneActa) {
                color = ContextCompat.getColor(ctx, R.color.md_blue_500);
                vMinExpActa = " (" + Utiles.traeDiferenciaMinutos(horaActa, Utiles.traeHoraActual()) + " min.)";
            } else {
                vMinExpActa = " (" + Utiles.traeDiferenciaMinutos(vHora, Utiles.traeHoraActual()) + " min.)";
            }

            vMinExp = " (" + Utiles.traeDiferenciaMinutos(vHora, Utiles.traeHoraActual()) + " min.)";
            viewHolder.lblHora.setText(vHora + vMinExp);

            new BadgeStyle().withTextColor(Color.WHITE).withColor(ContextCompat.getColor(ctx, R.color.md_red_500)).style(viewHolder.lblEstado);
            viewHolder.lblEstado.setText(vEstado);
        } else {
            color = ContextCompat.getColor(ctx, R.color.md_green_500);

            if (!vTipo.equals("C")) {
                viewHolder.lblHora.setText(Utiles.traeDiferenciaHoras(Utiles.traeHoraActual(), vHora));
            } else {
                viewHolder.lblHora.setText(hora + " (" + Utiles.traeDiferenciaHoras(Utiles.traeHoraActual(), vHora) + ")");
            }

            new BadgeStyle().withTextColor(Color.WHITE).withColor(ContextCompat.getColor(ctx, R.color.md_green_500)).style(viewHolder.lblEstado);
            viewHolder.lblEstado.setText(vEstado);
        }

        if (verificado) {
            viewHolder.lblVerificado.setVisibility(View.VISIBLE);
            viewHolder.lblVerificado.setText("verif");
            new BadgeStyle().withTextColor(Color.WHITE).withColor(ContextCompat.getColor(ctx, R.color.md_deep_orange_500)).style(viewHolder.lblVerificado);
        } else {
            viewHolder.lblVerificado.setVisibility(View.GONE);
        }

        if (tieneActa) {
            viewHolder.picTieneActa.setVisibility(View.VISIBLE);
        } else {
            viewHolder.picTieneActa.setVisibility(View.GONE);
        }

        TextDrawable drawable = TextDrawable.builder().buildRound(vTipo, color);
        viewHolder.ivTipo.setImageDrawable(drawable);

        viewHolder.lblDominio.setText(dominio);
        viewHolder.lblDireccion.setText(nombreCalle + " " + altura);

        if (Utiles.cStrNull(motivo)) {
            viewHolder.lblMotivo.setVisibility(View.GONE);
        } else {
            viewHolder.lblMotivo.setVisibility(View.VISIBLE);

            if (!tieneActa) {
                vMinExpActa = " (" + Utiles.traeDiferenciaMinutos(horaCierre, Utiles.traeHoraActual()) + " min.)";
            }

            viewHolder.lblMotivo.setText(motivo + vMinExpActa);
        }

        viewHolder.lblTipoVehiculo.setText(veh.toUpperCase());
        viewHolder.lblTipoUsuario.setText(usu.toUpperCase());
        viewHolder.lblFormaPago.setText(mod.equals("A") ? "ADELANTADO" : "DIFERIDO");

        if (cerrada.equals("S")) {
            viewHolder.lblEstado.setVisibility(View.GONE);
        } else {
            viewHolder.lblEstado.setVisibility(View.VISIBLE);
        }
    }

    @Override
    public void unbindView(ViewHolder holder) {
        super.unbindView(holder);
        holder.lblVerificado.setText(null);
        holder.lblDominio.setText(null);
        holder.lblHora.setText(null);
        holder.lblDireccion.setText(null);
        holder.lblMonto.setText(null);
        holder.lblTipoVehiculo.setText(null);
        holder.lblTipoUsuario.setText(null);
        holder.lblFormaPago.setText(null);
        holder.lblMotivo.setText(null);
    }

    @Override
    public ViewHolder getViewHolder(View v) {
        return new ViewHolder(v);
    }

    protected static class ViewHolder extends RecyclerView.ViewHolder {

        protected View view;

        ImageView ivTipo;
        TextView lblVerificado;
        TextView lblDominio;
        TextView lblHora;
        TextView lblEstado;
        TextView lblDireccion;
        TextView lblMonto;
        TextView lblTipoVehiculo;
        TextView lblTipoUsuario;
        TextView lblFormaPago;
        TextView lblMotivo;
        ImageView picTieneActa;

        public ViewHolder(View v) {
            super(v);
            this.view = v;

            ivTipo = (ImageView) v.findViewById(R.id.ivTipo);
            lblVerificado = (TextView) v.findViewById(R.id.lblVerificado);
            lblDominio = (TextView) v.findViewById(R.id.lblDominio);
            lblHora = (TextView) v.findViewById(R.id.lblHora);
            lblEstado = (TextView) v.findViewById(R.id.lblEstado);
            lblDireccion = (TextView) v.findViewById(R.id.lblDireccion);
            lblMonto = (TextView) v.findViewById(R.id.lblMonto);
            lblTipoVehiculo = (TextView) v.findViewById(R.id.lblTipoVehiculo);
            lblTipoUsuario = (TextView) v.findViewById(R.id.lblTipoUsuario);
            lblFormaPago = (TextView) v.findViewById(R.id.lblFormaPago);
            lblMotivo = (TextView) v.findViewById(R.id.lblMotivo);
            picTieneActa = (ImageView) v.findViewById(R.id.picTieneActa);
        }
    }
}
```

`public class ControlPorCuadra extends AppCompatActivity implements SimpleSwipeCallback.ItemSwipeCallback, ItemTouchCallback {

    private FastItemAdapter<EstadosAdapter> fastItemAdapter;

    private RecyclerView rvEstados;
    private List<EstadosAdapter> arrEstados;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.fconsultaestado);

        Toolbar mToolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(mToolbar);

        getSupportActionBar().setTitle("");
        getSupportActionBar().setSubtitle("Sin cuadra");
        getSupportActionBar().setHomeButtonEnabled(false);

        fastItemAdapter = new FastItemAdapter<>();

        fastItemAdapter.withSelectionListener(new ISelectionListener<EstadosAdapter>() {
            @Override
            public void onSelectionChanged(EstadosAdapter item, boolean selected) {
            }
        });

        fastItemAdapter.withOnPreClickListener(new OnClickListener<EstadosAdapter>() {
            @Override
            public boolean onClick(View v, IAdapter<EstadosAdapter> adapter, EstadosAdapter item, int position) {
                return false;
            }
        });

        fastItemAdapter.withOnPreLongClickListener(new OnLongClickListener<EstadosAdapter>() {
            @Override
            public boolean onLongClick(View v, IAdapter<EstadosAdapter> adapter, EstadosAdapter item, int position) {
                return false;
            }
        });

        rvEstados = (RecyclerView) findViewById(R.id.rvEstados);
        rvEstados.setLayoutManager(new LinearLayoutManager(this));
        rvEstados.setAdapter(fastItemAdapter);

		ThreadBuscarCuadra task = new ThreadBuscarCuadra(this);
		task.execute("");
    }

    private class ThreadBuscarCuadra extends AsyncTask<String, String, String> {

        private Context ctx;

        private MaterialDialog dlgBuscar;

        public ThreadBuscarCuadra(Context ctx) {
            this.ctx = ctx;
        }

        protected void onPreExecute() {
            fastItemAdapter.clear();
        }

        protected String doInBackground(String... params) {
			// Fill array with data from web
            Sync oSync = new Sync();
            arrEstados = oSync.controlPorCuadra();

            return "";
        }

        protected void onPostExecute(String result) {
			fastItemAdapter.add(arrEstados);

			SimpleSwipeCallback touchCallback = new SimpleSwipeCallback(ControlPorCuadra.this, null, ItemTouchHelper.RIGHT);

			ItemTouchHelper touchHelper = new ItemTouchHelper(touchCallback);
			touchHelper.attachToRecyclerView(rvEstados);
        }
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                onBackPressed();
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    @Override
    public boolean itemTouchOnMove(int oldPosition, int newPosition) {
        Collections.swap(fastItemAdapter.getAdapterItems(), oldPosition, newPosition);
        fastItemAdapter.notifyItemMoved(oldPosition, newPosition);
        return false;
    }

    @Override
    public void itemTouchDropped(int oldPosition, int newPosition) {
    }

    @Override
    public void itemSwiped(int position, int direction) {

        final EstadosAdapter item = fastItemAdapter.getItem(position);
        item.setSwipedDirection(direction);

        final Runnable removeRunnable = new Runnable() {
            @Override
            public void run() {
                item.setSwipedAction(null);
                int position = fastItemAdapter.getAdapterPosition(item);
                if (position != RecyclerView.NO_POSITION) {
                    fastItemAdapter.remove(position);
                }
            }
        };

        final View rv = findViewById(R.id.rvEstados);
        rv.postDelayed(removeRunnable, 0);

        item.setSwipedAction(new Runnable() {
            @Override
            public void run() {
                rvEstados.removeCallbacks(removeRunnable);
                item.setSwipedDirection(0);
                int position = fastItemAdapter.getAdapterPosition(item);
                if (position != RecyclerView.NO_POSITION) {
                    fastItemAdapter.notifyItemChanged(position);
                }
            }
        });

        fastItemAdapter.notifyItemChanged(position);
    }
}`

this is te activity, only has a asynctask, only search data from the web and fill the array...

**Comment by mikepenz** [comment]
@seba123neo were you able to solve the issue?

**Comment by mikepenz** [comment]
Closing for now. please re-open if necessary
