### ISSUE TITLE
getExtension generics fail for Kotlin

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#660]
## About this issue

Relates to #626 

Due to Kotlin's limitations, `SelectExtension::class.java` cannot be used because it does not represent `SelectExtension<Item>`.

It is a bit more strict, and also makes sense because passing in a class extending `SelectExtension<Item>` is effectively the same as passing a class extending `SelectExtension` due to type erasure.

If the number of implemented extensions within FastAdapter is limited, would you mind adding back the non generic based methods to resolve this? Eg `getSelectionExtension() = mExtensions.get(SelectExtension.class)`, etc.

You may also want to annotate getExtensions as returning a nullable variable.

## Details
- [ ] Used library version - 3.2.5
- [ ] Used support library version - 27.1.1
- [ ] Used gradle build tools version - 27.0.3
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

(I have searched for duplicate issues)

**Comment by AllanWang** [comment]
Interesting. I didn't consider casting. I will get back to you if I find an elegant inline function for this

**Comment by FabianTerhorst** [comment]
A good inline function could look like
```kotlin
public inline fun <reified T : IAdapterExtension<Item>, Item : IItem<Item, out RecyclerView.ViewHolder>> FastAdapter<Item>.getExtension(): T? =
        getExtension(T::class.java)

public inline fun <reified T : IAdapterExtension<out IItem<*, out RecyclerView.ViewHolder>>> FastAdapter<out IItem<*, out RecyclerView.ViewHolder>>.getExtension2(): T? =
        getExtension(T::class.java)
```

The first one is type save and doesn´t allow AdapterExtension request with the wrong item type, the second one is type save, but you have to specifiy both types on call.

```kotlin
fastAdapter.getExtension<ExpandableExtension<ProductItem>, ProductItem>()
fastAdapter.getExtension2<ExpandableExtension<ProductItem>>()
```

**Comment by AllanWang** [comment]
Thanks! I ended up using your suggestion

```kotlin
inline fun <reified T : IAdapterExtension<Item>, Item : IItem<*, *>> FastAdapter<Item>.getExtension(): T? =
        getExtension(T::class.java)

/**
 * Returns selection size, or -1 if selection is disabled
 */
inline val <Item : IItem<*, *>> IAdapter<Item>.selectionSize: Int
    get() = fastAdapter.getExtension<SelectExtension<Item>, Item>()?.selections?.size ?: -1

inline val <Item : IItem<*, *>> IAdapter<Item>.selectedItems: Set<Item>
    get() = fastAdapter.getExtension<SelectExtension<Item>, Item>()?.selectedItems ?: emptySet()
```
