### ISSUE TITLE
Items added to filtered adapter are lost after changing filter

### ISSUE THREAD

**Issue by dya-tel** [mikepenz/FastAdapter#667]
FastAdapter 3.2.5

Reproduction steps:
1) Take a new adapter: `adapter = new ItemAdapter<Foo>()`
2) Fill it with items (or not, doesn't really matter)
3) Apply a filter; for example, `adapter.filter("123")`
4) Add data to adapter: `adapter.add(items)` (tested only with data which passes the filter)
5) Change filter to anything else: `adapter.filter("12")`

Expected behavior:
All items which pass the new filter are shown.

Actual behavior:
Only initial items which pass the new filter are shown.

-----

There is also a mistake in the readme file - it says that filter() should return false for keeped items, while in reality it is the opposite. Javadoc is fine.

And is there any way to enable animations for filtering? By default (if I'm not insane) it looks like the whole list is being redrawn, without inserting/collapsing items and whatnot (like DiffUtil). Though it would be pretty easy if I just reimplement filtering by myself.

**Comment by mikepenz** [comment]
While filtered use the methods provided by the filter to add items:

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemFilter.java#L209

Please open a PR to fix the javadoc issue :)

Please check out the sample app, this one does only animate the change elements. (A redraw might happen of the whole list depending on what the rv decides to do)

**Comment by dya-tel** [comment]
Sorry for troubling you, but it seems I'm having a problem with finding an easy/proper way to make filtering and FastAdapterDiffUtil work together.

What I want to do is while having a filtered adapter, calculate the diff between visible items and new data and then apply it.

**Comment by mikepenz** [comment]
@dya-tel there should not much difference using this than the default android classes. 

Have you checked out this sample for example: https://github.com/mikepenz/FastAdapter/blob/6ca81ab1d584b901d1102c3fd096dcf4fb9bb3d9/app/src/main/java/com/mikepenz/fastadapter/app/DiffUtilActivity.java

Also you don't necessarily have to use DiffUtil as the filtering will animate accordingly too. 

https://github.com/mikepenz/FastAdapter/blob/6ca81ab1d584b901d1102c3fd096dcf4fb9bb3d9/app/src/main/java/com/mikepenz/fastadapter/app/SimpleItemListActivity.java

Please report back if you solved it or need additional guidance
