### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [mikepenz/FastAdapter#668]
Hello Sir. I'm a UI/UX and Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your application as my Open Source Contribution?

Thanks before.

**Comment by Mkurbanov** [comment]
Hi . It  will be good . Wich ideas are you have?

2018-04-24 10:48 GMT+03:00 Anhar Ismail <notifications@github.com>:

**Comment by anharismail** [comment]
Hello, Sir @Mkurbanov. These are my logo proposal for your application.
I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.
I'll provide all file types and sizes you needed.
Hope you like it.

 ### Version 1.
![fastadapter ver 1](https://user-images.githubusercontent.com/37614260/39634010-d21e7a0e-4fe3-11e8-8149-d8c0c0a1a366.png)

 ### Version 2.
![fastadapter ver 2](https://user-images.githubusercontent.com/37614260/39634078-04701d5a-4fe4-11e8-8dc1-3df7c47ba99b.png)

**Comment by mikepenz** [comment]
Thank you very much :) Really nice to see such work provided :)

**Comment by anharismail** [comment]
Thanks. Will you use it? What size you need for your application?

**Comment by anharismail** [comment]
Hi @mkurbanov. How about the logo proposal? What sizes I should provide?

**Comment by anharismail** [comment]
Hi @Mkurbanov, are there any progress about my logo proposal? :)

**Comment by mikepenz** [comment]
@anharismail thank you very much. Currently I do not have plans to rebrand, but I really like the design and logo proposal. and that's the reason why I keep the issue around and open so people can see it ;)

**Comment by mikepenz** [comment]
Closing as I think there was a lot of visibility for it :)

Thank you again for the great work!
