### ISSUE TITLE
Change text font

### ISSUE THREAD

**Issue by piersky** [mikepenz/FastAdapter#671]
Hi, I don't find a way to change text font in the fastadapter item, nor the color or the size. How can I choose a different text font?

Thanks a lot.

**Comment by mikepenz** [comment]
The fastadapter does not contain UI. the sample code just showcases how to use it.

**Comment by piersky** [comment]
Ok, but where exactly in the sample code? In your app I see always the same fonts.

Cheers

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleItem.java#L113 here you bind the view. and the xml defines how the view looks like

**Comment by piersky** [comment]
Great, I fixed it! Thanks a lot.
