### ISSUE TITLE
How to use the same model with different view holders ?

### ISSUE THREAD

**Issue by debjitk** [mikepenz/FastAdapter#674]
While using FastAdapter every model is bounded with a single view holder. How can I use the same model with different view holders for different adapters ?

**Comment by mikepenz** [comment]
I do not understand. if you provide a list with model elements then they will be in items. nothing prevents you to use the same model in a different list.

**Comment by mikepenz** [comment]
Perhaps you mean this: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeModelItemActivity.java
