### ISSUE TITLE
How to use comparator in 3.2.5?

### ISSUE THREAD

**Issue by guuilp** [mikepenz/FastAdapter#675]
I just upgraded from 3.0.5 to 3.2.5 and my Fast Adapter comparators stopped working.

I used to implement like this: playersInvitedFastAdapter.itemAdapter.withComparator(compareBy{ it.player.fullName })

But it no longer works. I tried to go on release notes from 3.0.5 until 3.2.5 but I haven't found anything helpful about this question.

How should I use comparator on fast adapter 3.2.5?

**Comment by FabianTerhorst** [comment]
You can use:
```java
((ComparableItemListImpl) adapter.getItemList()).withComparator
```
