### ISSUE TITLE
Error: Unable to merge dex

### ISSUE THREAD

**Issue by azizarc88** [mikepenz/FastAdapter#676]
I got unable to merge dex when run application

here my build.gradle

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildToolsVersion '28.0.0 rc1'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    dexOptions {
    }
    productFlavors {
    }
}

configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-annotations:27.1.0'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //begin user implementation
    implementation 'com.facebook.android:audience-network-sdk:4.28.1'
    implementation 'com.mikepenz:fastadapter:3.2.5'
    //end user implementation
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.google.firebase:firebase-config:15.0.0'
    implementation 'com.google.firebase:firebase-core:15.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support:support-annotations:27.1.0'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    compile project(':floatingsearchview')
}

apply plugin: 'com.google.gms.google-services'`

**Comment by FabianTerhorst** [comment]
Please post the build log.

**Comment by FabianTerhorst** [comment]
Feel free to answer when your issue isn't resolved.
