### ISSUE TITLE
not compatible with androidx

### ISSUE THREAD

**Issue by anajar** [mikepenz/FastAdapter#677]
this library not compatible with androidx is there any new version make it support with android x libs
and if there is kotlin version will be very helpful and ktx version @mikepenz

**Comment by mikepenz** [comment]
as long as the android x libraries are not in a final version there won't be an update yet.

**Comment by anajar** [comment]
@mikepenz :( that disappoint me

**Comment by mikepenz** [comment]
it will be updated as soon as it is stable. until then you can always create a PR or build it for yourself to make it compatible

**Comment by anajar** [comment]
@mikepenz thanks a lot your library help me a lot most of my developers asking me about my secret of the the adapter i always say it's @mikepenz 👍 🥇

**Comment by mikepenz** [comment]
Thank you very much.

**Comment by mikepenz** [comment]
Closing this for the time being. Please open a new ticket as soon as androidx is final ;)
