### ISSUE TITLE
FastAdapterDiffUtil documentation

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#678]
please add documentation (either javadoc or in the readme file) for FastAdapterDiffUtil.
i don't really understand how to use it or what each method does.

**Comment by FabianTerhorst** [comment]
Take a look at the sample code: 
https://github.com/mikepenz/FastAdapter/blob/6ca81ab1d584b901d1102c3fd096dcf4fb9bb3d9/app/src/main/java/com/mikepenz/fastadapter/app/DiffUtilActivity.java
Feel free to add documentation for it (in the readme for example).

**Comment by or-dvir** [comment]
@FabianTerhorst the sample code doesn't really explain anything.
i cant write documentation for it because as the questions suggests, i don't really understood how it works and what each method does and what my possibilities are.

**Comment by FabianTerhorst** [comment]
Most important part of the sample:
1.) It creates new data (background thread)
```java
createData();
```
2.) It calculates the difference between the new and old data (background thread)
```java
FastAdapterDiffUtil.calculateDiff(fastItemAdapter, simpleItems);
```
3.) It sets the difference record to the adapter (main thread)
```java
FastAdapterDiffUtil.set(fastItemAdapter, result);
```
```java
disposables.add(Single.fromCallable(new Callable<List<SimpleItem>>() {
            @Override
            public List<SimpleItem> call() throws Exception {
                return createData();
            }
        }).map(new Function<List<SimpleItem>, DiffUtil.DiffResult>() {
            @Override
            public DiffUtil.DiffResult apply(List<SimpleItem> simpleItems) throws Exception {
                return FastAdapterDiffUtil.calculateDiff(fastItemAdapter, simpleItems);
            }
        }).subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<DiffUtil.DiffResult>() {
                    @Override
                    public void accept(DiffUtil.DiffResult result) throws Exception {
                        FastAdapterDiffUtil.set(fastItemAdapter, result);
                    }
                }));
```
So there are just two important methods, calculate and set.

**Comment by or-dvir** [comment]
@FabianTerhorst thanks for the reply

1.  does `calculateDiff()` automatically run in background or is it because its wrapper inside the `apply ()` method? i am not familiar with rxJava so i don't really understand those methods/callbacks in the sample activity.
2. it looks like `set()` automatically applies all the changes and there is nothing else i need to do. is that correct?
3, its not very clear what `detectMoves` does. please tell me if my assumption is correct or not:
lets say i have an array of 3 items and i switch between the first and last items and then call `calculeDiff()`. if `detectMoves` is false, the `DiffResult ` object will return as if nothing has changed? and if `detectMoves` is true it will return the changes? if this is correct, then what if i want to detect changes AND have a `DiffCallback`? there is no method that accepts both. does that mean that if i want to have a `DiffCallback ` i dont have a way of detecting moves?
4. if `Set()` is used to apply changes to the adapter, then what is the purpose of `displatchUpdateTo()`?
5. looking at `ListUpdateCallback()` i see that `onInserted` for example only tells me how many items have been inserted into `int position`... but what if i need to know **which** items were inserted? my use case is that the user can add an item to a list but that item is being represented only by its id, then i need to get that item from the server using the inserted id - so i need to know which items (which ids) have been inserted. how can i do that?

**Comment by mikepenz** [comment]
@or-dvir I have added javadoc. most things you see in the FastAdapterDiffUtil are simply convenient functions to make it easier to use the default DiffUtil provided by the appcompat support libraries. 

Please see these docs for the different functionalities provided.

**Comment by or-dvir** [comment]
ok thanks @mikepenz
