### ISSUE TITLE
How to add a footer at the end and execute code when it is clicked?

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/FastAdapter#68]

**Comment by mikepenz** [comment]
@EpsilonOrionis are you talking about the `StickyFooter` which is available in the `MaterialDrawer` this can't be done via a normal `RecyclerView` and is out of scope for the `FastAdapter` 

In the MaterialDrawer this is implemented via an additional `LinearLayout` at the end of the `Drawer` (lowering the size of the RecyclerView) and adding items in it. Those items there have a normal `OnClickListener` and in the onClick it will then execute the code. 

(The responsible code within the `MaterialDrawer`  https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L386)

**Comment by EpsilonOrionis** [comment]
Mike maybe I'm wrong, but i read in the FastAdapter .md that it supports the footer

**Comment by FabianTerhorst** [comment]
@EpsilonOrionis you can add a footer adapter 
```
footeradapter.wrap(itemadapter.wrap(fastadapter));
footeradapter(new Item());
```
footer items are added at the bottom of the list.

**Comment by EpsilonOrionis** [comment]
How can I handle the click?

**Comment by FabianTerhorst** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/ExpandableItem.java#L109

**Comment by mikepenz** [comment]
@EpsilonOrionis that's why I asked if you talk about the `StickyFooter` which is different from a normal `Footer` 

The click of an `FooterAdapter` item is triggered the same as of normal items

**Comment by Rainer-Lang** [comment]
@EpsilonOrionis Is your question answered? All works fine?
