### ISSUE TITLE
3.2.6 artifacts missing/causing issues

### ISSUE THREAD

**Issue by eygraber** [mikepenz/FastAdapter#686]
I updated my build.gradle to depend on 3.2.6 (from 3.2.5):

```
implementation("com.mikepenz:fastadapter:3.2.6@aar") {
  transitive = false
}

implementation "com.mikepenz:fastadapter-commons:3.2.6@aar"
```

but the gradle sync fails unless commons is 3.2.5 (no error message, just fails).

I looked in maven central and jcenter, and there are no artifacts for 3.2.6

Do they come from somewhere else, or were they not deployed successfully?

**Comment by eygraber** [comment]
Have you considered jcenter? I've had a much easier time with them than maven central (and they sync to maven central nightly I believe).

**Comment by mikepenz** [comment]
I upload it to both. not sure why jcenter was not getting it yesterday
