### ISSUE TITLE
Subclassing FastAdapter

### ISSUE THREAD

**Issue by debjitk** [mikepenz/FastAdapter#688]
How can I subclass FastAdapter and hold the section or header adapter and item adapter within it ?
Also, I am loading a few thousand of items in the adapter and holding so many AbstractItem in the memory. So was wondering about the memory usage ?

**Comment by mikepenz** [comment]
@debjitk please follow the issue template. please provider useful information

**Comment by mikepenz** [comment]
Memory usage is simple the data size in object. the fastadapter only keeps the reference of your elements so it's not duplicating the data. 

you can subclass not sure what would prevent that?

**Comment by debjitk** [comment]
@mikepenz "Memory usage is simple the data size in object" - Right now I am passing a list of long integers to the recyclerview adapter. Switching to FastAdapter i have to pass in an AbstractItem. What I am asking is there would be a memory pressure when the items are in thousands. Its a photo gallery app.
