### ISSUE TITLE
Failed to update to v.3.2.7

### ISSUE THREAD

**Issue by eakteam** [mikepenz/FastAdapter#689]
implementation 'com.mikepenz:fastadapter-commons:3.2.7@aar'
This is causing problems, it cannot be found ...

But this is ok : implementation 'com.mikepenz:fastadapter:3.2.7@aar'

Missing artifact

**Comment by mikepenz** [comment]
I am having issues with jcenter. will try to get it up as soon as I was able to resolve the problem with them: http://jcenter.bintray.com/com/mikepenz/fastadapter-commons/

use 3.2.6 for now (it's equal beside the pom issue, .. (so use @aar with it))

**Comment by mikepenz** [comment]
Finally resolved the issues :)

**Comment by eakteam** [comment]
2 minutes ago i just updated my app to production with unresolved issueeeee :D :D :D :D ....
There are about 200K users that using your library in my app, i can't upload another update in short time :D :D :D :D , thanks anyway

**Comment by mikepenz** [comment]
With which unresolved issue?

**Comment by eakteam** [comment]
In fact no issue :) , but without v. 3.2.7 of fast-adapter-commons. No problem bro, just when you reply here that you resolved the artifact for 3.2.7 , 2 minutes before i published an update without new atrifact :) , it's ok, i don't see any new crash on my Crashlytics ....
Have a nice day
