### ISSUE TITLE
Q: Best Practice For Handling List to Grid Switching? 

### ISSUE THREAD

**Issue by EpiphX** [mikepenz/FastAdapter#691]
## About this issue
**Q**: I am curious on what is the best practice for handling a list/grid toggle with this library. 

I noticed that this was discussed briefly in [Issue #145], but it wasn't clear to me what the ideal method of implementation would be.

### Current Solution ###
Since different view types for the same item is discouraged, my current solution would involve having GridItems and ListItems that each define their own layout.

However, this would require clearing out the existing items and replacing them with the desired items each time the user wants to toggle the layouts.

Also, I think an example on how to implement this behavior would be a great addition to the sample 
app since it is a common requirement. 

Thanks and great job on the library!

## Details
- [v3.2.7] Used library version
- [v27.1.1] Used support library version
- [3.0.1] Used gradle build tools version
- [AS 3.1.1] Used tooling / Android Studio version
- [N/A] Other used libraries, potential conflicting libraries

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [X] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@EpiphX sorry to keep it short. What about using a `GridLayoutManager` and adjusting the amount of columns? 

Basically the adapter (and also the views themself) are not really the component handling this. 

The `RecyclerView` in combination of the `LayoutManager` is handling this, and these components are standard support libraries (and completely independent of this library) 

Thank you very much (and I hope my short answer helps)

**Comment by FabianTerhorst** [comment]
Hi,

thats actually not related to the fast adapter because thats handled by the layout manager.
You could use the StaggeredGridLayoutManager and toggle between span count 1 and 2 for example.
https://developer.android.com/reference/android/support/v7/widget/StaggeredGridLayoutManager.html#setSpanCount(int)

**Comment by EpiphX** [comment]
Hi guys, thanks for getting back to me so quickly!

First, I apologize if I didn't communicate my question correctly. 

We are already utilizing StaggeredGridLayoutManager. My problem is that the xml is unique if you are in list mode vs grid mode. It is not a matter of just span size.

Previously I utilized viewtype to handle this, swapping out a different viewholder if the user switches to grid mode, but I'm not sure how to handle this with FastAdapter.

Thanks again.

**Comment by mikepenz** [comment]
@EpiphX you'd do the exactly the same. if you switch you need to basically match a different item type with the model. see the generic example showing how to match a model with an item. you should be able to use this to change the type and fill up the rv newly

**Comment by Mkurbanov** [comment]
Oww cool

сб, 14 Июл 2018 г., 16:00 Mike Penz <notifications@github.com>:
