### ISSUE TITLE
Realtime FastAdapter sort feature

### ISSUE THREAD

**Issue by eakteam** [mikepenz/FastAdapter#695]
Hello, i have read this : https://github.com/mikepenz/FastAdapter/issues/51 , truly understand Sort() of arrays, but in some cases the fast adapter should not be clear() , and add new sorted array of items to it, i just wonder if something can be make to support this feature in realtime when we add an item, when delete or when move ... This is very important when some app have really big list of items and they modify the content of adapter. Thanks

**Comment by FabianTerhorst** [comment]
Hi,

you can provide your own item list implementation to any model adapter. https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.java#L42

**Comment by eakteam** [comment]
@FabianTerhorst , any documentation for that or how to use in more detail ? Thank you
For example we have a AbstractItem with three data : Title, Signal, Capacity ect ....
Just need when make changes to adapter to have the ability to automatic sort by : signal for example or anything else.
How can we do that ?

**Comment by FabianTerhorst** [comment]
Its basically the interface for the implementation that is managing the items list. You could for example add an own add implementation and call own calculated adapter callbacks. There is currently no documentation for it, thats true. Your implementation would look similar to the default one but without the default behavior you don't want to have. https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/utils/DefaultItemListImpl.java

**Comment by eakteam** [comment]
I understand that and really thanks for your explanation. Can you help a little to understand it better if you can...

So i have implemented : 
1) `FastItemAdapter<SampleItem> fastadapter;`
2) `class SampleItem extends AbstractItem<SampleItem, SampleItem.ViewHolder>`

in the SampleItem class there are some variables like : 
Name, Signal, Width , etc....

How to make some modification to this to be able to make the adapter to sort the items inside it by Signal e.x ? So when new items added, deleted or moved, the adapter to be able to resort they ?
It would be really great help if someone provide help for this, because i have writed my self hundred of lines to manually make this but sometime it not working or produce bugs like : https://github.com/mikepenz/FastAdapter/issues/694

**Comment by FabianTerhorst** [comment]
There is already an implementation that is sorting the items after adding moving ect. https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/utils/ComparableItemListImpl.java

**Comment by FabianTerhorst** [comment]
And you won't be able to use FastItemAdapter for that, better use the FastAdapter and add the model adapters to it.

**Comment by eakteam** [comment]
I see, so this is how i use it : 

This is the item class : 

```
private class SampleItem extends AbstractItem<SampleItem, SampleItem.ViewHolder> {

        String capabilities;
        String signal;
        String security;

        public SampleItem() {
        }

        SampleItem(String ssid, String kanali, String frekuenca, String gjeresia_e_kanalit, String bssid, String capabilities, String signal, String security) {
            this.capabilities = capabilities;
            this.signal = signal;
            this.security = security;
        }

        //The unique ID for this type of item
        @Override
        public synchronized int getType() {
            return 0;
        }

        //The layout to be used for this type of item
        @Override
        public synchronized int getLayoutRes() {
            return R.layout.wifi_scanner_view_list;
        }

        //The logic to bind your data to the view
        @Override
        public synchronized void bindView(@NonNull ViewHolder viewHolder, @NonNull List<Object> payloads) {
            //call super so the selection is already handled for you
            super.bindView(viewHolder, payloads);
            //viewHolder.setIsRecyclable(false);
            //bind our data
            //set the text for the name
            viewHolder.capabilities.setText(capabilities);
            viewHolder.signal.setText(signal);
			viewHolder.security.setText(security);
            }

        }

        //reset the view here (this is an optional method, but recommended)
        @Override
        public synchronized void unbindView(@NonNull ViewHolder holder) {
            super.unbindView(holder);
            holder.capabilities.setText(null);
            holder.signal.setText(null);
        }

        //Init the viewHolder for this Item
        @NonNull
        @Override
        public synchronized ViewHolder getViewHolder(@NonNull View v) {
            return new ViewHolder(v);
        }

        //The viewHolder used for this item. This viewHolder is always reused by the RecyclerView so scrolling is blazing fast
        class ViewHolder extends RecyclerView.ViewHolder {
            TextView capabilities;
            TextView signal;
            TextView security;

            ViewHolder(View view) {
                super(view);
                capabilities = view.findViewById(R.id.wifi_capabilities);
                signal = view.findViewById(R.id.signal_text);
                security = view.findViewById(R.id.wifi_security);
            }
        }
    }
```

FastAdapter : 

`private FastItemAdapter<SampleItem> fastadapter;`

and for adding item i use :  
`fastadapter.add(new SampleItem("TKIP","-45","WPA");`

can you help how to modify the class to automatic sort by signal please, sorry my low English, Best regards.

**Comment by FabianTerhorst** [comment]
```java
FastAdapter<SampleItem> fastadapter;
fastAdapter.addAdapter(0, new ModelAdapter<SampleItem>(itemListImpl, interceptor));
``´

**Comment by eakteam** [comment]
@FabianTerhorst , Without making any modification in the SampleItem class ? Just to call this method ?
And how we build `itemListImpl` or `interceptor` because no documentation for that i'm sorry ...

**Comment by FabianTerhorst** [comment]
you have to store the reference of the ModelAdapter somewhere ofc to add item to it. No modification of the items is required for that.  An sample for the interceptor is https://github.com/mikepenz/FastAdapter/blob/b77477ec100e27e31ffba16dade9fa5031e5cb6c/app/src/main/java/com/mikepenz/fastadapter/app/ModelItemActivity.java#L51 for example, but in your case the interceptor will return the value without nay changes. The item list impl is the class i posted before
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/utils/ComparableItemListImpl.java

**Comment by FabianTerhorst** [comment]
This isn't stackoverflow.

**Comment by eakteam** [comment]
@FabianTerhorst , I just make a joke, i know that no need for clarification, i just need when add item, delete or move in real time (not added to array first) to make the adapter automatically sort those damn items , i am really sad with that.
