### ISSUE TITLE
Animation issue when click item continuously at selection mode

### ISSUE THREAD

**Issue by gmavenis** [mikepenz/FastAdapter#700]
## About this issue

- Animation issue when click item continuously at selection mode
- Selected 2 items, then click many times on item 2, shadow of item fly up

## Details
- Using latest source code + sample from Google Play

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
What do you mean by 'shadow of item fly up'?

**Comment by gmavenis** [comment]
![1531881064275](https://user-images.githubusercontent.com/853527/42855991-5b3d1232-8a6d-11e8-8ebb-47d981fca0bb.JPEG)

At Edit mode, please tap many times on any item

**Comment by gmavenis** [comment]
@mikepenz : Do you have any idea?

**Comment by FabianTerhorst** [comment]
Im not able to reproduce it on 8.1 and p vanilla android. When you talk about the jumping parent item, thats an default recyclerview animation that can be changed individually.

**Comment by mikepenz** [comment]
@gmavenis some devices have an issue with the default animation from the `StateListDrawable`  (can't reproduce on my Pixel 2 XL with 9)

If you do: 
```java
ViewCompat.setBackground(viewHolder.view, FastAdapterUIUtils.getSelectableBackground(ctx, Color.RED, false)); //see thef alse for animation)
```

then it should work.

I pushed one commit which might (or might not) improve this too: https://github.com/mikepenz/FastAdapter/commit/56ad394d2c5eeec50b5bbcc7b7f9a34fb50464a2

**Comment by gmavenis** [comment]
Tks so much
