### ISSUE TITLE
withOnlyOneExpandedItem - not working

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#701]
## About this issue

I've set up the adpater in a quite simply way, single sub items level only and each item has a unique id. Shouldn't this be enough to get this working?

Should it work with auto expanding items?

## Setup 

*It looks like following, whereas `HandleItem` is `IExpandable` and contains children that are `AbstractExpandableItem`:*

        expandableExtension = ExpandableExtension<HandleItem>()
                .withOnlyOneExpandedItem(autoExpand)
        itemAdapter = ItemAdapter()
        fastAdapter = FastAdapter.with<HandleItem, ItemAdapter<HandleItem>>(itemAdapter)
                .addExtension(expandableExtension)
                .withEventHook(object : ClickEventHook<HandleItem>() {
                    @Nullable
                    override fun onBind(@NonNull viewHolder: RecyclerView.ViewHolder): View? {
                        //return the views on which you want to bind this event
                        return if (viewHolder is HandleItem.ViewHolder) {
                            (viewHolder as HandleItem.ViewHolder).binding.ivMenu
                        } else null
                    }

                    override fun onClick(v: View, position: Int, fastAdapter: FastAdapter<HandleItem>, item: HandleItem) {
                        // react on the click event
                    }
                })

    // add items
    // itemAdapter.add(...);

    // expand first item by default
    expandableExtension.expand(0)

## Details
- [ ] Used library version: 3.2.7
- [ ] Used support library version. 27.1.1
- [ ] Used gradle build tools version: 27.0.3
- [ ] Used tooling / Android Studio version: 3.1.3
- [ ] Other used libraries, potential conflicting libraries

**Comment by FabianTerhorst** [comment]
Hi,

im using withOnlyOneExpandedItem in some apps and can confirm that it is working. But im only using it with an single depth.

**Comment by mikepenz** [comment]
@MFlisar it should work. I found a tiny bug with auto collapsing with more than 2 sub levels but other than that it works in the sample "Expandable Sample". 

Also tried to expand one by default like you did, and click a different and that collapses things. 

Make sure that your items properly implement the interface. Or extend from `AbstractExpandableItem` (it's important that the parent is hooked up properly

**Comment by mikepenz** [comment]
Please report back :) close for the time being as it works in the sample ;)

**Comment by MFlisar** [comment]
I must "open" this issue again. For me, based from the interface namings and from the readme ("Expandable items have to implement the IExpandable interface, and the sub items the ISubItem interface"), following should work in a setup with one hierarchy:

* parent items implement `IExpandable`
* child items implement `ISubItem`

BUT both items (parent + child) must implement `IExpandable` to get the `isOnlyOneExpandedItem` flag working. Is this really necessary? My child items now implement `IExpandable` instead of `ISubItem` only and I must add following code to it to get this flag working:

     override val isAutoExpanding: Boolean = false
     override var isExpanded: Boolean = false
     override var subItems: MutableList<ISubItem<*>> = ArrayList()

This seems unnecessary for me, can you handle `ISubItems` just as an `IExpandable` without further sub items in the expandable functions?

If you keep this logic, can you please add this detail to the readme?
