### ISSUE TITLE
possible bug: duplicate images when scrolling

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/FastAdapter#702]
## Details
- [ ] Used library version 3.2.5
- [ ] Used support library version 27.1.1
- [ ] Used gradle build tools version 3.1.3
- [ ] Used tooling / Android Studio version 3.1.3

## About this issue
i am not sure if this is a bug in the library or somewhere else or if im somehow missing something...
the issue is that some views do not seem to be binded/unbinded properly and i am getting duplicate images. here is an example:

![capture _2018-07-18-14-55-45](https://user-images.githubusercontent.com/17179542/42879957-1b71c9e4-8a9b-11e8-8f60-ae7e701a4880.png)

as you can see, "Madam Secretary" and "Nashville" have the same image.
this seems to be happening at random - if i scroll up and down a few times, this would happen to different items.

things to note (in case they matter):
* i am using kotlin
* i am using ModelAdapter
* the adapter is filtered while this is happening

here are my bindView and unbindView:

```
override fun bindView(holder: ViewHolder, payloads: MutableList<Any>)
    {
        super.bindView(holder, payloads)

        val view = holder.view
        val context = view.context

        Picasso.with(context)
            .load(model._imageUrl)
            .placeholder(R.drawable.image_loading)
            .error(R.drawable.image_error)
            .fit()
            .centerInside()
            .into(view.iv_showImage)

        (view as FrameLayout).foreground =
                FastAdapterUIUtils.getSelectablePressedBackground(context,
                                                                  context.resources.getColor(R.color.colorPrimaryTransparent),
                                                                  255,
                                                                  true)
        val nameAndYear = "${model._name}\n(${model._year})"
        view.tv_nameAndYear.text = nameAndYear

        if (model.isRunning())
            view.tv_status.visibility = View.GONE
        else
            view.tv_status.apply {
                visibility = View.VISIBLE
                setText(R.string.showEnded)
            }
    }

override fun unbindView(holder: ViewHolder)
    {
        super.unbindView(holder)

        holder.view.apply {
            tv_status.text = ""
            tv_nameAndYear.text = ""
            iv_showImage.setImageDrawable(null)
        }
    }
```

## Things i have tried (inside `unbindView` method)
i found a few suggested solutions on StackOverflow but none of them work for me
* `imageView.setImageDrawable(null)`
* `imageView.setImageBitmap(null)`
* `imageView.setImageResource(0)`
* `imageView.setImageResource(android.R.color.transparent)`

up until today `imageView.setImageDrawable(null) `has been working just fine but not anymore for some reason...
is my code wrong somehow? is anybody else experiencing this issue?

**Comment by FabianTerhorst** [comment]
Hi,

its not an bug in the library because the bind is called correctly otherwise the text would be the same as well.

**Comment by FabianTerhorst** [comment]
I Would recommend you to save the picasso target inside the imageview tag and cancel it inside the unbind.

**Comment by or-dvir** [comment]
@FabianTerhorst i am not sure what you mean... can you provide a code sample?

**Comment by or-dvir** [comment]
@FabianTerhorst doesnt sound like a good solution... what if the request has already been completed? calling cancel will have no affect

**Comment by FabianTerhorst** [comment]
Its the recommended way for picasso.

**Comment by or-dvir** [comment]
yes. id is unique

**Comment by or-dvir** [comment]
it seems to have stopped happening (at least for now). i didnt change anything. dont know what to tell you

**Comment by mikepenz** [comment]
@or-dvir you definitely should add the picasso "cancelRequest" to the `unbind` of the item. 
It is basically called when the RV sees that the element goes out of range, and when it reuses it. 

If you don't do this. picasso will still have the reference to the imageView and might load the previous loading image into it.

**Comment by or-dvir** [comment]
ok i added it. but all it says in the docs is "cancel any existing requests for the specified ImageView"
according to what you guys are saying, it does more than just cancel the request... if you have some source explaining more about it please post a link

**Comment by FabianTerhorst** [comment]
Canceling is already enough. Otherwise it could happen that bind happens while an other request is already happening. I don't think Picasso supports more then one simultaneous request for each image view.

**Comment by or-dvir** [comment]
@FabianTerhorst @mikepenz calling `Picasso.cancel()` is not working. still getting duplicates

**Comment by FabianTerhorst** [comment]
Does the bug happens as well when you remove all placeholder, error, fit, centerInside options in load?

**Comment by FabianTerhorst** [comment]
And don't forget to set the imagedrawable to null in unbind

**Comment by or-dvir** [comment]
@FabianTerhorst i havent checked... but i do need to use all these options so even if it does work its not an option for me

**Comment by FabianTerhorst** [comment]
you could try to update picasso because the version you are using is 3 years old.

**Comment by mikepenz** [comment]
@or-dvir I work on applications myself using picasso in a grid layout similar like yours. 

If I make sure that:
- identifier is definitely unique
- the loading request is canceled on unbind (SUPER IMPORTANT)
- no other async things are not canceled on unbind
- views are not directly used via some code and do not respect recycling 

then everything works great.

You always need to keep in mind how recyclerView's work and how the views are re-used during scrolling

**Comment by or-dvir** [comment]
> you could try to update picasso because the version you are using is 3 years old.

@FabianTerhorst when i first read that i was "what the f***?! i started working on this app a few months ago..." and i went on picassos' github page and saw that im using only the second latest version so again i thought "what the hell are you talking about?!" and then i noticed it **really is** 3 years old! hahahah
in my defense the latest version only came out in march!. anyways... ill update it and report back if it happens again

> * identifier is definitely unique
> * the loading request is canceled on unbind (SUPER IMPORTANT)
> * no other async things are not canceled on unbind
> * views are not directly used via some code and do not respect recycling

@mikepenz 
* identifiers are unique.
* as i mentioned i added `Picasso...cancel()` and its still hapennig
* my `bind` and `unbind` are posted above. my items only have a couple of text views and an image. so unless `FastAdapterUIUtils.getSelectablePressedBackground` does some work in background, then i should be good.
* im not sure what you mean by "views are not directly used via some code". where?

**Comment by mikepenz** [comment]
Well you should never access a view of an item directly as view's are re-used only do everything in the bindView, and then reset in unbindView. that's super important.

**Comment by or-dvir** [comment]
yes i understand that. what i dont understand is where else i could even do that... i access the views in bind/unbind/viewholder constructor.

it hasnt happened since updating picasso version... but that doesnt necessarily mean its fixed

**Comment by mikepenz** [comment]
Closing this as I am almost 99.9% sure that the glide clear fixes it
