### ISSUE TITLE
Glide Preload images with FastAdapter on infinite load 

### ISSUE THREAD

**Issue by InvertedX** [mikepenz/FastAdapter#704]
## How to Use fastAdapter with Glide Preload 

- How can we use Glides preload feature with FastAdapter  [PreloadModel](https://bumptech.github.io/glide/int/recyclerview.html#preloadmodelprovider)
i am using FastAdapter with infinite load

## Details
- [3.2.7] Used library version
- [27.1.1 ] Used support library version
- [ 28.0.1] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [*] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [*] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by FabianTerhorst** [comment]
The preload listener only requires an scroll listener and since you can add an unlimited amount of scroll listeners to an recyclerview, the library doesn't change the needed code to implement it.

**Comment by InvertedX** [comment]
in there example they implemented it in adapter. but i am using FastItemAdapter. so how can i tackle with this

**Comment by FabianTerhorst** [comment]
The faatadapter doesnt control the scroll listeners so it should just work.

**Comment by InvertedX** [comment]
ok thank you. btw FastAdapter is amazing . excellant work
