### ISSUE TITLE
Simplest way to integrate facebook native ads?

### ISSUE THREAD

**Issue by TheMaxCoder** [mikepenz/FastAdapter#705]
What is the best way to integrate native ads? 
Can we please have a sample with facebook native ads?
I find it very hard to implement native ads with fast adapter and a sample would be great.

and if we have a sample with facebook native ads, same could be used with Admob native ads in future.

**Comment by TheMaxCoder** [comment]
and if we have a sample with facebook native ads, same could be used with Admob native ads in future.

**Comment by mikepenz** [comment]
@TheMaxCoder that's a unrelated question. 

You simply need to create a item for these. And then you have the usual ViewHolder for them, which will be displayed in the list.

**Comment by TheMaxCoder** [comment]
Hi Mike!

I'm sorry if my question seems completely noob but actually I couldn't get my head around it. 

I have a working `FastAdapter` with `ItemAdapter` for let's say `BlueItem`
Now I want to add let's say an `AdItem` (Native Ad)
My question was, which adapter we can use to add these two different items to the list?

I tried using `AbstractWraperAdapter` but it was very confusing so I thought maybe you can show some simpler way to achieve this?

Thanks
Max

**Comment by TheMaxCoder** [comment]
Yeah, it makes sense. I will stop being lazy and will play around WraperAdapter and see.
Thank you so much for the explanations :)
Have a great day!
