### ISSUE TITLE
AbstractMethodError withOnClickListener

### ISSUE THREAD

**Issue by tentenponce** [mikepenz/FastAdapter#706]
## Crash upon implementing withOnClickListener.
Hi, Good day,

Turning on proguard makes it crash upon clicking:
```
      fastItemAdapter.withOnClickListener((v, adapter, item, position) -> {
            //function here to jump to activity
            return true;
        });
```
Logcat:
```
07-30 16:04:21.795 28904-28904/com.unionbankph.oneuhub.uat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.unionbankph.oneuhub.uat, PID: 28904
    java.lang.AbstractMethodError: abstract method "boolean com.mikepenz.a.e.g.onClick$7c4067ea(android.view.View, com.mikepenz.a.e, com.mikepenz.a.l, int)"
        at com.mikepenz.a.b$1.a(Unknown Source:116)
        at com.mikepenz.a.g.h.onClick(Unknown Source:36)
        at android.view.View.performClick(View.java:6891)
        at android.view.View$PerformClick.run(View.java:26083)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

But if I add this line:
`-keep class com.mikepenz.fastadapter.**`

It fixes the problem, but I know that it actually doesn't fix the problem, I just prevent the proguard on touching the library.

## Details
- FastAdapter version 3.2.8
- Support version 27.1.1
- BuildTools Version 27.0.3
- Android Studio 3.1.3
- Potential conflicting libraries `implementation "com.mikepenz:materialize:1.1.2@aar"`

I've also check this issues but neither has the same issue encountered like mine: #256 #237 #197 #270

**Comment by mikepenz** [comment]
which proguard configuration do you use? any special definition like more optimisation than suggested by the android team? 

I use the adapter in many libs with proguard enabled too but have never faced this issue

**Comment by tentenponce** [comment]
Hi sir, here's my proguard main project config:

```
-keep class com.shockwave.** #pdf

-keep class com.itsgmobility.hrbenefits.BuildConfig { *; }

-keep public class android.support.v7.widget.** { *; }
-keep public class android.support.v7.internal.widget.** { *; }
-keep public class android.support.v7.internal.view.menu.** { *; }

-keep public class * extends android.support.v4.view.ActionProvider {
    public <init>(android.content.Context);
}

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-dontwarn java.lang.invoke.** #can't find referenced class java.lang.invoke.LambdaMetafactory

#dynamically reference classes
-dontnote com.bumptech.glide.GeneratedAppGlideModuleImpl #com.bumptech.glide.Glide
-dontnote sun.misc.Unsafe #com.google.gson.internal.UnsafeAllocator
-dontnote android.os.SystemProperties #com.scottyab.rootbeer.utils.Utils
-dontnote com.android.org.conscrypt.SSLParametersImpl #okhttp3.internal.AndroidPlatform
-dontnote org.apache.harmony.xnet.provider.jsse.SSLParametersImpl #okhttp3.internal.AndroidPlatform
-dontnote sun.security.ssl.SSLContextImpl #okhttp3.internal.Platform
-dontnote org.robovm.apple.foundation.NSObject #retrofit2.Platform
-dontnote org.robovm.apple.foundation.NSOperationQueue #retrofit2.Platform$IOS$MainThreadExecutor

#duplicate library classes
-dontnote com.google.auto.value.AutoAnnotation
-dontnote com.google.auto.value.AutoValue$Builder
-dontnote com.google.auto.value.AutoValue
-dontnote org.apache.http.params.HttpConnectionParams
-dontnote org.apache.http.params.HttpParams
-dontnote org.apache.http.params.CoreConnectionPNames
-dontnote org.apache.http.conn.ConnectTimeoutException
-dontnote org.apache.http.conn.scheme.HostNameResolver
-dontnote org.apache.http.conn.scheme.SocketFactory
-dontnote org.apache.http.conn.scheme.LayeredSocketFactory
-dontnote android.net.http.SslCertificate$DName
-dontnote android.net.http.SslCertificate
-dontnote android.net.http.HttpResponseCache
-dontnote android.net.http.SslError
-dontnote okhttp3.logging.HttpLoggingInterceptor$Level
-dontnote okhttp3.logging.HttpLoggingInterceptor$Logger$1
-dontnote okhttp3.logging.HttpLoggingInterceptor$Logger
-dontnote okhttp3.logging.HttpLoggingInterceptor

#disable shifting mode in BottomNavigationView
-keepclassmembers class android.support.design.internal.BottomNavigationMenuView {
    boolean mShiftingMode;
}
```

And here's my `build.gradle` release config:

```
release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
            proguardFiles fileTree('proguard').asList().toArray()
}
```

I do have many proguard files, but I guess the proguard for the main project is what you're looking for, the other proguard config are from their corresponding libraries.

<img width="380" alt="screen shot 2018-07-30 at 5 08 39 pm" src="https://user-images.githubusercontent.com/5518758/43388283-4c8b8568-941b-11e8-9592-a19768dc12a5.png">

**Comment by FabianTerhorst** [comment]
Are you using any other library that depends on fast adapter? (```./gradlew app:dependencies```)

**Comment by tentenponce** [comment]
Hi sir @FabianTerhorst, I did run that command, I've checked the response and there's no library that depends on fast adapter. I also can't remember that I include a library that depends on fast adapter. By the way, here's the summary of my libraries:

https://github.com/pwittchen/ReactiveNetwork v0.11.0
https://github.com/f2prateek/rx-preferences v2.0.0
https://github.com/scottyab/secure-preferences v0.1.4
rxjava v2.1.10
rxandroid v2.0.2
rxbinding v2.1.1
glide v4.0.0
https://github.com/hdodenhof/CircleImageView v2.2.0
gson v2.8.2
autovalue v1.3
https://github.com/code-troopers/android-betterpickers v3.1
firebase

From this list, I don' think they depend on fastadapter.

**Comment by tentenponce** [comment]
Hi sirs, have you successfully recreated the issue? Do you need any additional info other than this to recreate it?

**Comment by mikepenz** [comment]
No we sadly haven't in the sample app it works perfectly and also in other apps where we use proguard including advanced optimizations it works great. 

you'd probably need to create and provide us a sample to showcase the issue as it is otherwise hard to assume anything

**Comment by mikepenz** [comment]
Please report back :). You can reopen if still relevant. close for now.
