### ISSUE TITLE
3.2.5 java.lang.IndexOutOfBoundsException: Inconsistency detected

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#709]
## About this issue

(Similar report at #602 (fixed))

The implemented diff callback checks if items are the same using the identifier. This works fine, but if I set the comparator to check for the identifier, I get an OOB exception. The log is very similar to #602

To give more context, my adapter currently cycles through 2 item types. For one of them, the identifier works fine, whereas the other has inconsistent identifiers (which is why I wanted to use types). If I simply override that item creation to set the identifier to the hash of its data model and continue comparing by identifier, everything works fine. However, this moreso emulates the `areContentsTheSame` method. Is there something I'm not understanding here as to why comparing by type doesn't work? 

## Details
- [3.2.5] Used library version
- [28.0.0-alpha3] Used support library version
- [3.1.3] Used gradle build tools version
- [3.1.3] Used tooling / Android Studio version
- [NA] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by FabianTerhorst** [comment]
The identifier must be unique inside an adapter. Two items can't have the same identifier even when there type id is different.
