### ISSUE TITLE
Click and LongClick animation

### ISSUE THREAD

**Issue by sparkitny** [mikepenz/FastAdapter#71]
Hello Mike,

I use your lib for my app and it works fine. One thing I noticed is that if I use FastAdapter.OnClickListener or the LongClickListener the items don't show any click or long click animations. Am I missing something? The ItemAnimators are only used when moving, deleting something I guess.

Best Regards,

Sebastian

**Comment by mikepenz** [comment]
@sparkitny your item needs a background (or foreground) which has the `selected` state. 

I use the following in the sample items:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java#L131

Best, 
Mike
