### ISSUE TITLE
select only two item with Checkbox

### ISSUE THREAD

**Issue by bkhezry** [mikepenz/FastAdapter#710]
Hi Mike,
who can I prevent user from selecting more than two Checkbox? I change `CheckBoxSampleItem.java` in many way but not success.

**Comment by mikepenz** [comment]
@bkhezry you will need to write some logic to detect how many items are selected and prevent any further selection. or automatically unselect a previous selection. 

You'd most likely have to listen for the current selections and hook up s listener when a new selection is made. and in the case there are already 2 selections you would then consume this event and prevent so the new item to get selected

**Comment by bkhezry** [comment]
@mikepenz thanks for your response. I used LinkedList to hold selected items position and check size of it before select new item. add in the Last(new select) and remove(deselect) from the First of LinkedList is the answer :+1:
