### ISSUE TITLE
Expandable Recyclerview and Firebase

### ISSUE THREAD

**Issue by KeesNijenhuis** [mikepenz/FastAdapter#712]
I was following your expandable example, and everything is working now except the most important thing. 
In your example you use dummy data made in those for loops. I use Firebase Realtime database for my data which I fetch with this code:

```java
 private void fetchItems() {
        bookItems.clear();

        reference.orderByChild("isbn").addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                if (dataSnapshot.hasChildren()) {
                    Iterator<DataSnapshot> iter = dataSnapshot.getChildren().iterator();
                    while (iter.hasNext()) {
                        DataSnapshot snap = iter.next();

                        String title = (String) snap.child("bookTitle").getValue();
                        String author = (String) snap.child("bookAuthor").getValue();
                        String isbn = (String) snap.child("bookIsbn").getValue();
                        String date = (String) snap.child("date").getValue();
                        boolean owned = (boolean) snap.child("owned").getValue();
                        boolean read = (boolean) snap.child("read").getValue();

                        bookItems.add(new ExpandableBookItem(title, author, isbn));

                    }
                    fastItemAdapter.add(bookItems);
                }
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });

    }
```

Now the ExpandableBookItem shows those three values, I also have an ExpandedBookItem which is supposed to display the other values you can see in the code. How would I go abou this

## Details
- [3.2.8 ] Used library version
- [ 27.1.1] Used support library version
- [3.1.4 ] Used gradle build tools version

## Checklist

- [Yes ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ Yes] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ Yes] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ Yes] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ No] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
I am not sure what you mean. sounds like this question is not fully related to the fastadapter itself. perhaps some firebase question?
