### ISSUE TITLE
FastAdapter Item sending useless information to Firebase database

### ISSUE THREAD

**Issue by KeesNijenhuis** [mikepenz/FastAdapter#714]
Hi,
Im using Firebase to store the users data, but since I started using FA a bunch of useless date has been getting sent to the database:

![capture](https://user-images.githubusercontent.com/8082532/44212770-8550b900-a16c-11e8-831a-5be54e528c48.PNG)
 I'm talking about the enabled/identifier/layoutRes fields.

Here is my Item class:

`public class BookItem extends AbstractItem<BookItem, BookItem.ViewHolder> {
    private static final String TAG = "Booklist";

    private String bookTitle, bookAuthor, bookIsbn, date;
    private boolean owned, read;
    private String base64, description;

    public BookItem(String title, String author, String isbn, String date, boolean owned, boolean read, String base64, String description) {
        bookTitle = title;
        bookAuthor = author;
        bookIsbn = isbn;
        this.date = date;
        this.owned = owned;
        this.read = read;
        this.base64 = base64;
        this.description = description;
    }

    public BookItem() {

    }

 @Override
    public int getType() {
        return R.id.singleMessageContainer;
    }

     @Override
    public int getLayoutRes() {
        return R.layout.book_item;
    }

    @NonNull
    @Override
    public ViewHolder getViewHolder(View v) {
        return new ViewHolder(v);
    }

    protected static class ViewHolder extends FastAdapter.ViewHolder<BookItem> {
        @BindView(R.id.bookTitle)
        TextView title;
        @BindView(R.id.bookAuthor)
        TextView author;
        @BindView(R.id.bookISBN)
        TextView isbn;
        @BindView(R.id.coverImage)
        ImageView cover;

        View view;

        String uri;

        public ViewHolder(View v) {
            super(v);
            view = v;
            ButterKnife.bind(this, v);

        }

        @Override
        public void bindView(BookItem item, List<Object> payloads) {

            title.setText(item.bookTitle);
            author.setText(item.bookAuthor);
            isbn.setText(item.bookIsbn);
            uri = item.getBase64();

            if (uri != null) {
                byte[] bytes = android.util.Base64.decode(uri, android.util.Base64.DEFAULT);

                Glide.with(view).load(bytes).into(cover);
            } else {
                uri = view.getContext().getString(R.string.no_cover);

                byte[] bytes = android.util.Base64.decode(uri, android.util.Base64.DEFAULT);

                Glide.with(view).load(bytes).into(cover);

            }
        }

        @Override
        public void unbindView(BookItem item) {
            title.setText(null);
            author.setText(null);
            isbn.setText(null);
        }
    }

`

I left all the auto-generated getters and setters out.

And here is the code where I send the BookItem to the database:

```
private void sendToDatabase(String userId) {
        author = bookAuthor.getText().toString();
        title = bookTitle.getText().toString();
        isbn = bookIsbn.getText().toString();
        date = dateText.getText().toString();
        owned = ownedCheckbox.isChecked();
        read = readCheckbox.isChecked();


        BookItem book = new BookItem(title, author, isbn, date, owned, read, base64, description);

        reference.child(userId).child("readBooks").child(isbn).setValue(book);
    }
```

Now my question: Is there a way for this information not to be sent to the database?

Cheers.

**Comment by FabianTerhorst** [comment]
Hi,
take a look at https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/model/ModelIconItem.java and https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/ModelItemActivity.java to split your item and model object.

**Comment by KeesNijenhuis** [comment]
Never mind the last post. I have figured it out. It is all working now.

Thanks for the help!

**Comment by FabianTerhorst** [comment]
You need to insert your list of models not your list of items.

**Comment by KeesNijenhuis** [comment]
Yeah that is what i figured out :)
