### ISSUE TITLE
Get view holder in event hooks, e.g. on click

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#716]
## About this issue

I need to get the `ViewHolder` in my `OnClickListener`. Is this somehow possible? If not, could the `EventHookUtil.attachToView` and the `ClickEventHook` be changed to also pass the `ViewHolder`?

If someone uses `DataBinding` in the `ViewHolders` I don't want the view in my events but the `ViewHolder` to get access to the `DataBinding` so that I can access the sub views efficiently...

## Details
- [x] Used library version: 3.2.7
- [x] Used support library version: 27.1.1
- [x] Used gradle build tools version: 4.6

**Comment by mikepenz** [comment]
you get the `view` via the event hook here: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/listeners/ClickEventHook.java#L14

you can set the `ViewHolder` as tag to that view and then just retrieve it. 

Be careful though accessing it, as during scrolling things can always be reycled and no longer active
