### ISSUE TITLE
FastItemAdapter when adding new items, losing the previous list

### ISSUE THREAD

**Issue by lim996** [mikepenz/FastAdapter#717]
## About this issue

I'm working on a chat room list fragment. From my API I'm getting the List<ChatRoom> divided in pages of 10 items, so when I'm loading data I'm waiting for 1 or more lists of elements in different moments.
What happens is that with the first call I'm getting 10 items, and they are correctly shown. Then I'm receiving another list of 5 elements, and when I try to add them to my FastItemAdapter it seems like that the list is cleared and now there are only the last 5 ones. 
       
        List items = new ArrayList();
        for (ChatRoom chatRoom : chatRoomList) {
            items.add(new 
                   ChatRoomItemAdapter().withIdentifier(chatRoom.getChatRoomId()).withItem(chatRoom));
        }

        `if(addData){
            mFastItemAdapter.add(items);

        }
        else{
            mFastItemAdapter.clear();
            mFastItemAdapter.setNewList(items);
        }
        mFastItemAdapter.notifyDataSetChanged();       
    
I'm not a problem due to old version because in other similar fragments, the "add" function, appends to the previous list of items, while in this fragment I don't know why I'm losing the previous list.

## Details
- ['2.6.3@aar'] Used library version

## Checklist
- [ Y ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ Y ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ Y ] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ Y ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
As you can see `add` does not clear: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.java#L395

I am pretty sure your flag `addData` is false and you call:

```
mFastItemAdapter.clear(); //not really needed as you already use set new list
mFastItemAdapter.setNewList(items);
```

**Comment by lim996** [comment]
Unfortunately I've to say that I've tried also with this:

       `List items = new ArrayList();
        for (JobOffer offer : jobOfferList)
            items.add(new JobItemAdapter().withIdentifier(offer.getJobId()).withItem(offer));

        
            mFastItemAdapter.add(items);
        
        mFastItemAdapter.notifyDataSetChanged();`

**Comment by FabianTerhorst** [comment]
```Add``` also calls the notifies internally, so you don't need to call the notifyDataSetChanged.

**Comment by lim996** [comment]
Ok, thanks.
But it is only a redundant call and it doesn't solve the problem.

What I'm trying to understand is if I have to save the instance (or something similar) of my FastItemAdapter, cause in the other activities if I have 3 or 4 more group of items to add, in each function the FastItemAdapter.getAdapterItems() is updated with the group of items appended. While here it seems everytime I call add, getAdapterItems() is clear. So the items are added, and not appended.

**Comment by mikepenz** [comment]
Also in v2.6.3 of the `FastAdapter` the code did not clear when calling `add`:
https://github.com/mikepenz/FastAdapter/blob/v2.6.3/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L345

You might want to ensure no other part of your code causes a clear. debug through it and see where the items get lost

**Comment by lim996** [comment]
I just found the line of code that what causing a clear().
Finally I solved the problem.

So It was only a line of code which i forgot to comment, that was calling clear() before each time I was adding data to my FastItemAdapter.

Really thanks for the help!
