### ISSUE TITLE
get models from GenericItemAdapter

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#72]
if possible, add method to get models from GenericItemAdapter.
`getAdapterItems` return GenericItems of adapter, i want all models

p.s : i can't sync 1.2.4 version with gradle, stuck too many time and not successful, please check .

thanks

**Comment by mikepenz** [comment]
@DJafari good point. will add that method. 

v1.2.4 should be fine. Everything looks ok on maven central:
http://search.maven.org/#artifactdetails%7Ccom.mikepenz%7Cfastadapter%7C1.2.4%7Caar

**Comment by DJafari** [comment]
thanks @mikepenz :)

in maven everything is ok, but when i add in my gradle file not synced, i don't know why
can you test it at new sample project ?

**Comment by mikepenz** [comment]
@DJafari I also use it in the `MaterialDrawer` and in many other projects. Also some friends use it. 

Are you on the latest support libraries? You might need to check what the exact exception is

**Comment by DJafari** [comment]
@mikepenz i waiting 20 minute , sync not completed and no error, but version 1.2.3 synced with 10 second time .

**Comment by mikepenz** [comment]
@DJafari weird. do you have proper connection to the maven repo? perhaps v1.2.3 is already cached on your machine.

**Comment by DJafari** [comment]
@mikepenz i tested it with v1.0.5, in the statusbar shows downloading ... so it's not cache and ok

**Comment by DJafari** [comment]
@mikepenz if possible, create builder api for adapter creation, see [SmartAdapter](https://github.com/mrmans0n/smart-adapters)

```SmartAdapter.items(myObjectList).map(Tweet.class, TweetView.class).into(myListView);
```

**Comment by mikepenz** [comment]
@DJafari ok great it's working now. 

For the second thing. please open a new issue.

**Comment by DJafari** [comment]
@mikepenz  ok thanks

#74
