### ISSUE TITLE
Expandable list on NestedScroll view

### ISSUE THREAD

**Issue by 8kt8** [mikepenz/FastAdapter#720]
## About this issue

Hello, I try to implement your Expandable extension on Nested Scroll view with some buttons under list. Issue exist only if recycle view have some views under the end of a list.

## Details
- Used library version 3.2.7
- Used support library version 28.0.0-rc01
- Used gradle build tools version 28
- Android Studio version 3.2

When I collapsing first on the second item from the bottom, the last or two last items gone for a moment and show with animation.

Can you check this behavior on this link:
**https://my.mixtape.moe/xmdzig.webm**

**Comment by mikepenz** [comment]
The provided link does no longer exist. 

also the extension is meant with the `FastAdapter` for the `RecyclerView`. I don't believe that it is very great to have it in another nested scroll view. highly depends on the usecase though. 

and the animation case seems normal to me, it's just how the recyclerview and it's itemanimator handle it. 

That's unrelated to this library. 

The Fastadapter only provides the elements, and does not animate or anything. 
you add items. and the adapter will notify the adapter accordingly with the notify* methods. which will do the default behaviour of the RV depending on the itemAnimator and the ayoutmanager
