### ISSUE TITLE
ObservableArrayList with FastAdapter

### ISSUE THREAD

**Issue by denisraison** [mikepenz/FastAdapter#721]
Hello Mike,

I have just a question.
Would be possible to use the FastAdapter reflecting the items from an ObservableArrayList?

I'd like to use the FastAdapter that would update its items whenever we have a change, adding, removing and etc, on my ObservableArrayList list.

Is that possible?

Thanks for the awesome library! :star:

**Comment by mikepenz** [comment]
@denisraison well theoretically you could do something like this by implementing your own `ItemList` which you use with the `FastAdapter`. 

It is important though that the correct updates are always forwarded to the adapter. if an item is moved, removed, ... and this needs to happen on the UI thread. 

See more here:
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/utils/ComparableItemListImpl.java
