### ISSUE TITLE
Converter Problem

### ISSUE THREAD

**Issue by mahdighaemi123** [mikepenz/FastAdapter#722]
Hi Mike,

I have just a Problem.

> FastAdapter fastAdapter;
ItemAdapter<ItemComment> ItemComments;
ItemAdapter<ItemJomlak> ItemHeader;
fastAdapter=FastAdapter.with(Arrays.asList(ItemHeader, ItemComments));
RvComments.setAdapter(fastAdapter);
   
    Problem This Line --> RvComments.setAdapter(fastAdapter);
    Problem: Error:(84, 31) error: incompatible types: FastAdapter cannot be converted to Adapter

Thanks for the awesome library :)

**Comment by mikepenz** [comment]
@mahdighaemi123 I am not sure what you mean. 

the `FastAdapter` extends `a normal `RecyclerView.Adapter` 

please see the sample app where it is in use without any problems :)

**Comment by mikepenz** [comment]
please report back. closed for the time being
