### ISSUE TITLE
The bindView method of this item should set the `Tag` on its itemView

### ISSUE THREAD

**Issue by Grouen** [mikepenz/FastAdapter#725]
Why i always accept this message "The bindView method of this item should set the `Tag` on its itemView", i tried set tag for item view, but it doesn't work.

## Details
- [ 3.3.0] Used library version
- [androidx.appcompat:appcompat:1.0.0 ] Used support library version
- [3.2.0 ] Used gradle build tools version
- [3.2.0 ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

**Comment by mikepenz** [comment]
Sorry this was a really stupid bug. Released a bugfix release just for this very specific thing

**Comment by Grouen** [comment]
Thank you for a quick response and fix.

**Comment by mikepenz** [comment]
Please wait a few minutes until the artifact is available :)
