### ISSUE TITLE
App crash while adding ViewBinderHelper class in model Class 

### ISSUE THREAD

**Issue by Diwko95** [mikepenz/FastAdapter#727]
## About this issue

- I am using [ViewBinderHelper](https://github.com/chthai64/SwipeRevealLayout) class in my Item.
- The app is crashing while declaring in model class

## Details
- This is my sample code:
```
public class Data extends AbstractItem<Data,Data.ViewHolder> {
  ViewBinderHelper viewBinderHelper =new ViewBinderHelper();
``` 
- I am getting "Unable to create converter for class (MyClassName) for method (my method name)" exception
-  I am using Gson Converter
## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by FabianTerhorst** [comment]
You probably don't wanna serialize the whole adapter item. Better use the AbstractModelItem and an own model object to serialize.

**Comment by Diwko95** [comment]
Thanks a lot Mr. Fabian
