### ISSUE TITLE
DiffUtil + automatic id generation is not working

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/FastAdapter#729]
## About this issue

I'm using something like this to update my adapter:

    FastAdapterDiffUtil.set(mFastItemAdapter!!, data, diffCallback)

Whenever I drag and drop items now, I create new items, push it to my store and above function will be called as a result. I checked my diff callback and can see if I drag an item and move it one item up or down, my diff callback returns `areContentsTheSame == false` 2x which is correct (for the 2 exchanged items via drag and drop). But what I see in the end is that the whole adapter flickers and when debugging I can see that EVERY item is rebound.

My diff callback looks like following:

	object ItemDiffCallback : DiffCallback<Item> {

		override fun areItemsTheSame(oldItem: Item, newItem: Item): Boolean {
			val i1 = oldItem.getItem()
			val i2 = newItem.getItem()
			val e = i1.javaClass.equals(i2.javaClass) && i1.rowId == i2.rowId
			return e
		}

		override fun areContentsTheSame(oldItem: Item, newItem: Item): Boolean {
			val i1 = oldItem.getItem()
			val i2 = newItem.getItem()
			val  e = i1.pos!!.equals(i2.pos)
	//        return i1.equals(i2)
			return e
		}

		override fun getChangePayload(oldItem: Item, oldItemPosition: Int, newItem: Item, newItemPosition: Int): Any? {
			return null
		}
	}
	
I show a list of different items of database models, so I can't use each items row id as identifier, so I let `FastAdapter` generate ids.

**Tests**

When debugging I saw, that the new items get new ids, so for my tests I changed my items to generate ids that are constant like following (not save, but good enough to test what I think is the problem):

     override fun getIdentifier(): Long = model.javaClass.hashCode() + model.rowId
	 
The result is that only the drag & dropped items are rebound, just as expected.

Shouldn't it be possible to either reuse already assigned ids in this case or to update the items ids without rebinding the `ViewHolder`? If the `DiffCallabck` says items are the same, then there is no need to assign a new id and the old one can be reused. Not sure why the id is important for the diff anyways yet though...

## Details
- [x] Used library version: 3.3.0
- [x] AndroidX version: 1.0.0
- [x] Used gradle build tools version: 3.2.0
- [x] Used tooling / Android Studio version: 3.2
- [x] Other used libraries, potential conflicting libraries

**Comment by FabianTerhorst** [comment]
Hi,

could you write an test inside https://github.com/mikepenz/FastAdapter/blob/develop/library/src/test/java/com/mikepenz/fastadapter/FastAdapterDiffUtilTest.java that demonstrates the problem?

**Comment by MFlisar** [comment]
I can write one that shows that identifiers change, but the problem is not a data problem but a visual one:

Testcase would look like following:

    @Test
    public void testDiffUtilDragDrop() {
        List<TestItem> originalList = new ArrayList<>();
        originalList.add(new TestItem("Test1"));
        originalList.add(new TestItem("Test2"));

        // if we use immutable data, we must create new items, diff util should do the rest to find out which items are the same
        // we add new but identical items in inverted order to demonstrate a drag & drop action
        List<TestItem> updatedList = new ArrayList<>();
        updatedList.add(new TestItem("Test2"));
        updatedList.add(new TestItem("Test1"));

        // this here works, data is correct
        test(originalList, updatedList);

        // this fails, but items have just been moved, it would be save if identifiers would have been kept
        Assert.assertEquals(updatedList.get(0).getIdentifier(), originalList.get(1).getIdentifier());
        Assert.assertEquals(updatedList.get(1).getIdentifier(), originalList.get(0).getIdentifier());
    }

**Observed problem**

If something like this is done the user sees that all views are redrawn, data data underneath is correct though and even diff result seems fine.

**Idea**

The problem here is that it seems, that fast adapter uses the `identifiers` somewhere therefore rebinds all `ViewHolders` (not sure what happens, just a guess currently) if new but identical items are used. As soon as I copy identifiers or use constant identifiers, everything works as expected.

**Comment by FabianTerhorst** [comment]
This works and is the expected behavior. You are talking about that items that are the same content not the same object should have the same identifier which isn't true.
```java
@Test
    public void testDiffUtilDragDrop() {
        TestItem testItem1 = new TestItem("Test1");
        TestItem testItem2 = new TestItem("Test2");
        List<TestItem> originalList = new ArrayList<>();
        originalList.add(testItem1);
        originalList.add(testItem2);
        
        List<TestItem> updatedList = new ArrayList<>();
        updatedList.add(testItem2);
        updatedList.add(testItem1);

        test(originalList, updatedList);

        Assert.assertEquals(updatedList.get(0).getIdentifier(), originalList.get(1).getIdentifier());
        Assert.assertEquals(updatedList.get(1).getIdentifier(), originalList.get(0).getIdentifier());
    }
```

**Comment by FabianTerhorst** [comment]
Items with the identifier -1 will get an new id generated.

**Comment by FabianTerhorst** [comment]
The ids are beeing generated on FastAdapterDiffUtil.set or for modelAdapter.set, add ect. for example for every item without an id.

**Comment by FabianTerhorst** [comment]
The result of the diffutils are just adapter notifies.

**Comment by mikepenz** [comment]
@MFlisar if in your case you can generate an identifier based on the item contents, you should definitely overwrite the `getIdentifier()` method and return the appropriate, **unique** identifier. so that the same data will have the same id. that's possible in special cases, but be warned that you still have to ensure that the 2 different object instances with the same data are not added, otherwise you would have conflicting id's. 

And @FabianTerhorst already mentioned it correctly that the behavior is working as intended :)

**Comment by mikepenz** [comment]
As mentioned if you have a clear defined logic how you get an identifier from your object then you should overwrite the getIdentifier and supply your own logic (or you just set the identifier based on that logic) 

That's basically the standard behavior of the RecyclerView itself. The FastAdapter only packs it in a nice simple usable construct per item. instead of per recyclerview which makes it easier to reuse

**Comment by MFlisar** [comment]
Will now solve this by generating gobal unique ids in my database because that's the easiest solution for me.

Thanks for the feedback.
