### ISSUE TITLE
How to refresh datalist onResume method with FastAdapter constructor when back button is pressed

### ISSUE THREAD

**Issue by jDilshodbek** [mikepenz/FastAdapter#732]
## About this issue

- I am using ModelAbsract Adapter.
- when I get back from another Activity, onResume method must fire ItemModelAdapter with updated datalist
- I am sending productDataList from Sqlite database to Constructor

## Details
-  this is my onCreatView method:
```
@Nullable
    @Override
    public View onCreateView( LayoutInflater inflater, ViewGroup container,  Bundle savedInstanceState) {
View view=inflater.inflate(R.layout.fragment_menu_lists, container, false);
        recyclerView=view.findViewById(R.id.recyclerView1);
        productList=new ArrayList<>();
        footerAdapter=ItemAdapter.items();
        databaseHelper=new DatabaseHelper(getContext());
        productDataList=databaseHelper.getAllProducts();
      itemModelAdapter=new ModelAdapter<>(new IInterceptor<Data, DataItem>() {
          @Nullable
            @Override
            public DataItem intercept(Data data) {
                return new DataItem(data,MenuListsFragment.this,productDataList);
            }

        });
      fastAdapter=FastAdapter.with(Arrays.asList(itemModelAdapter));
     fastAdapter.addAdapter(1,footerAdapter);
     recyclerView.setAdapter(fastAdapter);
`
```

- this my onResume method:
```
 @Override
    public void onResume() {
        super.onResume();


        productDataList=databaseHelper.getAllProducts();

        itemModelAdapter=new ModelAdapter<>(new IInterceptor<Data, DataItem>() {

            @Nullable
            @Override
            public DataItem intercept(Data data) {
                return new DataItem(data,MenuListsFragment.this,productDataList);
            }

        });

        fastAdapter.notifyAdapterDataSetChanged();
        fastAdapter.notifyDataSetChanged();

        if(!getUserVisibleHint()){
            return;
        }
    }
```

this my Adapter class:
```
public class DataItem extends ModelAbstractItem<Data,DataItem,DataItem.ViewHolder> {

List<ProductData> productDataList;
public DataItem(Data data,OnItemCount listener,List<ProductData> productDataList) {
        super(data);
        this.itemCount=listener;
        productDataList.clear();
        this.productDataList=productDataList;

    }

............
}
```

I am struggling with feeding new dataset via constructor

- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
You don't need
```java
fastAdapter.notifyAdapterDataSetChanged();
fastAdapter.notifyDataSetChanged();
```

if you use the methods to add items via the `ModelAdapter` these things are handled automatically for you. 

Independent of that, I am not sure what the actual problem is? Can you please elaborate a bit more?

**Comment by jDilshodbek** [comment]
My problem is to compare data from Sqlite and from Server in adapter. They have the same id,count fields.I send both database list from Sqlite and Api to the adapter via constructor. When I enter this activity both databases are loaded and count variable is compared from databases. But I may start another activity from this activity. And the started activity also contains both server and sqlite database. Here I may change count variable and update the sqlite database.Finally I go back to previous activity that mentioned before, by clicking BackButton. But when I back here  I need to get updated Sqlite datalist and sent it to adapter directly again like [this](http://belencruz.com/en/2015/04/refresh-data-in-a-custom-android-adapter/) in order to compare server data list with updated sqlite database list

**Comment by jDilshodbek** [comment]
In the shown [tutorial ](http://belencruz.com/en/2015/04/refresh-data-in-a-custom-android-adapter/), We can create custom method in the adapter and call it where it is required. But I can't reach this and call it in the FastAdapter

**Comment by mikepenz** [comment]
I still do not understand the issue. 

If you want to set a new list of items to the adapter just use the corresponding API methods from the ModelAdapter or ItemAdapter. 

Please read the javadoc and have a look at the samples. 
The question seems not really related to the FastAdapter

**Comment by jDilshodbek** [comment]
I am sorry. Can you show me to call this refreshSqliteDB method in the
activity:

public class DataItem extends
ModelAbstractItem<Data,DataItem,DataItem.ViewHolder> {

List<ProductData> productDataList;

DatabaseHelper databaseHelper;
private OnItemCount itemCount;

public DataItem(Data data, OnItemCount listener,List<ProductData>
productDataList) {
    super(data);
    this.itemCount=listener;
    this.productDataList=productDataList;


}



public void refreshSqliteDB(List<ProductData> productDataList){

    productDataList.clear();
    productDataList.addAll(productDataList);

}

**Comment by mikepenz** [comment]
the adapter offers simple methods like add or set.

```
itemAdapter.add(ITEMS);
```

Just look at the sample app. it showcases this.

**Comment by jDilshodbek** [comment]
Thank you for your quick response and efforts. I think you understand my
problem now.
 I am just a junior developer, so I might explained unclearly. Sorry for
that.I think you may better close this issue now

**Comment by mikepenz** [comment]
You may consider using StackoverFlow to ask beginners questions. 

GitHub issues on libraries are absolutely the wrong place for that. 

Good luck!
