### ISSUE TITLE
FastAdapter should support the AndroidX libraries

### ISSUE THREAD

**Issue by BreSmit521** [mikepenz/FastAdapter#734]
## About this issue
FastAdapter currently does not support the AndroidX libraries.

## Details
Per issue 677 (https://github.com/mikepenz/FastAdapter/issues/677) development on AndroidX support was not being actively worked on until AndroidX was in a stable release.  As of Sept. 21, 2018 AndroidX has moved to a 1.0.0 stable release. 

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by FabianTerhorst** [comment]
androidx is used since fastadapter version 3.3.0
