### ISSUE TITLE
Class Cast Exception - Expandable Extension

### ISSUE THREAD

**Issue by sid-dob** [mikepenz/FastAdapter#738]
## About this issue

- Crash - Fatal Exception: java.lang.ClassCastException - Child Expandable cannot be cast to Parent Expandable on FastAdapter - onClickListener
- Not Always , but if you open and close multiple times and scroll up and down and the expand, it crashes.

## Details
- [ ] fastadapter:3.3.1@aar
- [ ] fastadapter-extensions-expandable:3.3.1
- [ ] build:gradle:3.2.1
- [ ] 3.2.1

## Checklist

- [ Y ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ Y ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ Y ] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ Y ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ Y ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@sid-dob please make sure your adapter type definition is a super type of all your items. 

If you have the following

SuperType
- ChildTypeA extends SuperType
- ChildTypeB extends SuperType

Then the following applies

FastAdapter<ChildTypeA> is only supposed to have ChildTypeA as content, that is also true for sub types (sadly Java's generics is not powerful enough to limit that) 

FastAdapter<ChildTypeB> is only supposed to have ChildTypeB as content

FastAdapter<SuperType> you can use both types inside this adapter

**Comment by sid-dob** [comment]
Here , do you mean -> 

ChildTypeA = ExpandableParent
ChildTypeB = Expandablee ( i.e. the item that shows up after expansion )

Is this complex ? or am I missing on something ?
Here are the definitions : 

`
@Suppress("FINITE_BOUNDS_VIOLATION_IN_JAVA")
class ProductDetailExpandableItem<Parent, SubItem>(
        val productDetailState: ProductDetailExpandableItemState
) : AbstractExpandableItem<ProductDetailExpandableItem<Parent, SubItem>,
        ProductDetailExpandableItemViewHolder, SubItem>()
        where Parent : IItem<*, *>,
              Parent : IExpandable<*, *>,
              SubItem : IItem<*, *>,
              SubItem : ISubItem<*, *> 
`

Expandee
`
@Suppress("FINITE_BOUNDS_VIOLATION_IN_JAVA")
class ProductDetailExpandableDetailsItem<Parent>(
        val data: String?, val viewType: Int
) : AbstractExpandableItem<Parent, FastAdapter.ViewHolder<*>, ProductDetailExpandableDetailsItem<Parent>>()
        where Parent : IItem<*, *>,
              Parent : IExpandable<*, *>,
              Parent : IClickable<*>,
              Parent : ISubItem<*, *> 
`

**Comment by mikepenz** [comment]
What type definition does your adapter have? 

`FastAdapter<IItem>`
`FastAdapter<ProductDetailExpandableItem>`
`FastAdapter<AbstractExpandableItem>`

The first super type of your items is the `AbstractExpandableItem` so you can do `FastAdapter< AbstractExpandableItem>` alternative `IItem` will work always
