### ISSUE TITLE
Adapter not updating items correctly

### ISSUE THREAD

**Issue by lbenedetto** [mikepenz/FastAdapter#739]
## About this issue
When clearing the adapter, adding a new item, and then notifying of a data set change, the displayed item does not change. Instead, the existing item disappears (as expected), and then reappears, unchanged. This change probably wouldn't even be visible if I didn't have animateLayoutChanges enabled.

Code to reproduce
```
fastItemAdapter.clear()
fastItemAdapter.add(new CustomItem())
```
Followed by any of
```
fastItemAdapter.notifyDataSetChanged()
fastItemAdapter.notifyAdapterDataSetChanged()
fastItemAdapter.notifyItemChanged(0);
```

I also tried notifying of dataset change after clear AND after add, but that doesn't work either.

## Details
- [3.3.1] Used library version

**Comment by lbenedetto** [comment]
Referring to public int getType() in the custom Item definition?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/items/AbstractItem.java#L43

the identifier, which is the identifier the RV uses. by default the `IdDistributor` will assign a unique ID. Just to ensure that this is also the case for you, or that you provide your own unique id. 

(That's the value returned here for the adapter: https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#getItemId(int) )

**Comment by lbenedetto** [comment]
With this code, the item does not update
```
    @Override
    public long getIdentifier(){
        return voucher.hashCode();
    }

    @Override
    public int getType() {
        return R.id.voucher_list_item_id;
    }
```

With this code, the item does update
```
    @Override
    public int getType() {
        return voucher.hashCode();
    }
```

**Comment by mikepenz** [comment]
Do you have multiple items with the same type id? 

The type must be unique per item type.

**Comment by lbenedetto** [comment]
No. Each item type has its own unique id. I'm using android resources to assign a unique id

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item name="voucher_list_item_id" type="id" />
</resources>
```

Also, this recycler view only displays one type of item.

**Comment by mikepenz** [comment]
@lbenedetto hmmm perhaps you can provide a sample (or do modifications in the sample app of the library) to showcase the issue?

**Comment by lbenedetto** [comment]
Sure. I actually discovered an even simpler case to reproduce.

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        RecyclerView recyclerView = findViewById(R.id.recyclerView);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));

        ItemAdapter<CustomItem> itemAdapter = new ItemAdapter<>();
        FastAdapter fastAdapter = FastAdapter.with(itemAdapter);
        recyclerView.setAdapter(fastAdapter);

        itemAdapter.add(new CustomItem(String.valueOf(System.currentTimeMillis())));
        itemAdapter.add(new CustomItem(String.valueOf(System.currentTimeMillis() + 99999)));

        //False: itemAdapter.getAdapterItem(0).getIdentifier() == itemAdapter.getAdapterItem(1).getIdentifier()
        // Yet the first item is repeated in the recycler twice
    }

```
Here is a simple Android Studio project you can use to reproduce it.
[FastAdapterBug.zip](https://github.com/mikepenz/FastAdapter/files/2608561/FastAdapterBug.zip)

**Comment by FabianTerhorst** [comment]
There is no guarantee that the hashCode of the string is unique. This is not an bug inside this library.

**Comment by lbenedetto** [comment]
Ah, I see. Sorry about that.
