### ISSUE TITLE
simplify adapter creation

### ISSUE THREAD

**Issue by DJafari** [mikepenz/FastAdapter#74]
it's to be good that adapter creation to be simplify
for example [SmartAdapter](https://github.com/mrmans0n/smart-adapters) has a simple api to adapter creation .

mapping model to genericitem with this api to be greated !
for example for FastAdapter :

```java
FastAdapter
	.empty()
	.map(IconModel.class, GenericIconItem.class)
	.map(RightIconModel.class, RightGenericIconItem.class)
	.into(myRecyclerView);
```

thanks for you great library and great support :+1:

**Comment by mikepenz** [comment]
@DJafari most methods are now chainable in the adapter. Theoretically it is now also possible to init everything with a one-liner.

**Comment by mikepenz** [comment]
I think the possibilities with the current API is already really great. If someone want's to add a different API via an addon library I'm open for **PR**s. Otherwise I think it's ok to stay with the current API ;)
