### ISSUE TITLE
Is it possible to expand/collapse Items from within the expandableItem class?

### ISSUE THREAD

**Issue by Androidjent** [mikepenz/FastAdapter#742]
Greetings to the authors of my favorite android library!

I have an item that i want to expand by clicking on an icon, not via autoexpand. In the sample app, this seems to always be handled in the activity, by the following lines within a new ClickEventHook: 

```
expandableExtension.expand(position);
expandableExtension.collapse(position);
```

I'd prefer to outsource the expand eventhook into the expandleItem class, but it seems like there is no function for that, only autoExpansion.

Is there a way to do this? Or is the activity/fragment the proper place to handle eventhook expansions?

Thanks a lot

**Comment by mikepenz** [comment]
Well you need the `ExpandableExtension` to do that. 

Theoretically you can do this due to some nice facts :D. 

So when binding the data to the view, the `itemView` gets the `FastAdapter` set as tag:
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/listeners/OnBindViewHolderListenerImpl.java#L22-L36

So you can do this:
```java
Object tag = holder.itemView.getTag(com.mikepenz.fastadapter.R.id.fastadapter_item_adapter);
if (tag instanceof FastAdapter) {
     ... get the extension from the fastAdapter, do you action
}
```

**Comment by Androidjent** [comment]
Hi Mike,

thank you very much for a fast response - now my fragment is neat and clean, and everything is handled in the item :-) I'll break it down in case someone needs more details. 

The ExpandableItem needs a variable:
`private static ExpandableExtension<IItem> expandableExtension;`
which is set in the bindview method:
```
Object tag = viewHolder.itemView.getTag(R.id.fastadapter_item_adapter);
        if (tag instanceof FastAdapter) {
            FastAdapter fastAdapter = ((FastAdapter) tag);
            if (fastAdapter.getExtension(ExpandableExtension.class) != null)
            expandableExtension = (ExpandableExtension<IItem>) fastAdapter.getExtension(ExpandableExtension.class);
        }
In the item class, the eventhook is defined:
public static class MyExpandableEvent extends ClickEventHook<SimpleSubExpandableItem> {
        @Override
        public View onBind(@NonNull RecyclerView.ViewHolder viewHolder) {
            if (viewHolder instanceof SimpleSubExpandableItem.ViewHolder) {
                return ((ViewHolder) viewHolder).icon;
            }
            return null;
        }

        @Override
        public void onClick(View v, int position, FastAdapter<SimpleSubExpandableItem> fastAdapter, SimpleSubExpandableItem item) {

            if (item.getSubItems() != null) {
                if (!item.isExpanded()) {
                    ViewCompat.animate(v.findViewById(R.id.material_drawer_icon)).rotation(180).start();
                    expandableExtension.expand(position);
                } else {
                    ViewCompat.animate(v.findViewById(R.id.material_drawer_icon)).rotation(0).start();
                    expandableExtension.collapse(position);
                }
                //return mOnClickListener == null || mOnClickListener.onClick(v, fastAdapter, item, position);
            }
            //return mOnClickListener != null && mOnClickListener.onClick(v, fastAdapter, item, position);
            Toast.makeText(v.getContext(), "test pos = "+position, Toast.LENGTH_LONG).show();
        }
    }
```


The only line left in the fragment/activity is:
`fastItemAdapter.withEventHook(new SimpleSubExpandableItem.MyExpandableEvent());`
