### ISSUE TITLE
How to get all selected item even filtered?

### ISSUE THREAD

**Issue by suriyadi15** [mikepenz/FastAdapter#743]
this is code to get selected item:
```
val selectExt = fastAdapter.getExtension(SelectExtension<SelectPersonItem>().javaClass)
listSelected.addAll(selectExt.selectedItems.map { SelectPersonSelectedHolder(this, it.item) })
```
but when i filter, the selectedItems return is not including those not filter.

**Comment by suriyadi15** [comment]
`selectExt.selections` -> this one also can't

**Comment by mikepenz** [comment]
`ItemFilter.getSelections()`

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemFilter.java#L132
