### ISSUE TITLE
New object allocation for every item added to adapter

### ISSUE THREAD

**Issue by shubhamchaudhary** [mikepenz/FastAdapter#75]
Is this the best idea?
Can we reused items?

I am doing this for now: 
```
private List<MyItem> getItemsFor(objects) {
  Lists<MyItem> output = Lists.newArrayList();
  for (MyObject object: objects) {
    output.add(new MyItem(object, stuff, param, moreStuff));
  }
  return output;
}
```

The reason of my concern is that the place where I'm trying to use does too much upon `bindView` and in  constructor.

**Comment by mikepenz** [comment]
@shubhamchaudhary if you want to have your model split of the items you can use the `GenericItemAdapter` which does things like this for you.

**Comment by mikepenz** [comment]
EDIT: the `GenericItemAdapter` will no longer keep an additional list of the model
