### ISSUE TITLE
Skipped 176 frames!  The application may be doing too much work on its main thread.

### ISSUE THREAD

**Issue by afarber** [mikepenz/FastAdapter#750]
Hello,

in an AndroidX app I am using MaterialDrawer and FastAdapter in 2 fragments:

![merge_from_ofoct](https://user-images.githubusercontent.com/1884458/51084511-55add900-172b-11e9-95aa-50f3f0c690b5.png)

And while the fragment on the right side of the above screenshot has more items and works well, the fragment on the left side keeps skipping frames when I scroll it:

```
01-13 11:40:30.055 21410-21410/de.slova I/Choreographer: Skipped 188 frames!  The application may be doing too much work on its main thread.
01-13 11:40:32.999 21410-21410/de.slova I/Choreographer: Skipped 176 frames!  The application may be doing too much work on its main thread.
01-13 11:40:38.871 21410-21410/de.slova I/Choreographer: Skipped 70 frames!  The application may be doing too much work on its main thread.
01-13 11:40:40.202 21410-21410/de.slova I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
01-13 11:40:42.499 21410-21410/de.slova I/Choreographer: Skipped 70 frames!  The application may be doing too much work on its main thread.
01-13 11:40:48.004 21410-21410/de.slova I/Choreographer: Skipped 71 frames!  The application may be doing too much work on its main thread.
01-13 11:40:49.961 21410-21410/de.slova I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
01-13 11:40:52.144 21410-21410/de.slova I/Choreographer: Skipped 70 frames!  The application may be doing too much work on its main thread.
01-13 11:41:09.805 21410-21410/de.slova I/Choreographer: Skipped 113 frames!  The application may be doing too much work on its main thread.
01-13 11:41:10.502 21410-21410/de.slova I/Choreographer: Skipped 40 frames!  The application may be doing too much work on its main thread.
01-13 11:41:15.291 21410-21410/de.slova I/Choreographer: Skipped 212 frames!  The application may be doing too much work on its main thread.
01-13 11:41:15.994 21410-21410/de.slova I/Choreographer: Skipped 40 frames!  The application may be doing too much work on its main thread.
01-13 11:41:21.113 21410-21410/de.slova I/Choreographer: Skipped 208 frames!  The application may be doing too much work on its main thread.
```

There is no network activity - I just scroll the list up and down with my finger, not too fast - and the left fragment is really sluggish, despite having only 4 items in its RecyclerView. Also, when I try to open the MaterialDrawer while in that fragment, the app freezes for few seconds too.

I keep comparing the both fragments and the items, but don't see the reason yet. Do you have an idea please, what could be wrong?

My problematic item has a plus icon which can be clicked and then it displays the game board image, could that be the reason? [GameItem.java](https://github.com/mikepenz/FastAdapter/files/2753008/GameItem.txt)

While the non-problematic item is here: [TopItem.java](https://github.com/mikepenz/FastAdapter/files/2753009/TopItem.txt)

And here are my both fragments, they are pretty same code and even use the same simple layout file with just one RecyclerView -

Can not be scrolled well: [FinishedGamesFragment.java](https://github.com/mikepenz/FastAdapter/files/2753010/FinishedGamesFragment.txt)

Works just fine: [TopFragment.java](https://github.com/mikepenz/FastAdapter/files/2753011/TopFragment.txt)

Thank you for any ideas.

## Details
- [3.3.1] Used library version
- [2.1.0-alpha01] Used support library version
- [4.10] Used gradle build tools version
- [3.2.1] Used tooling / Android Studio version
- [3.12.1] okhttp
- [2.71828] picasso

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [X] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by FabianTerhorst** [comment]
Hi,
please record an method trace and upload it here.

**Comment by afarber** [comment]
Thanks for replying Fabian, do you mean a logcat?

**Comment by afarber** [comment]
Here it goes, thank you (I have renamed it to .txt, please rename back to .trace):

[cpu-art-20190113T123224.trace](https://github.com/mikepenz/FastAdapter/files/2753022/cpu-art-20190113T123224.txt)

![screenshot 2019-01-13 at 12 32 49](https://user-images.githubusercontent.com/1884458/51084756-81cb5900-172f-11e9-9af6-dfb151eab99f.png)

**Comment by afarber** [comment]
I have removed all picasso calls and just use

```
mPhoto1.setImageResource(R.drawable.account_gray);
mPhoto2.setImageResource(R.drawable.account_gray);
```

in the [GameItem.java](https://github.com/mikepenz/FastAdapter/files/2753008/GameItem.txt) and still the same amount of frames is being skipped when slowly scrolling the list of 4 items up and down.

```
01-13 14:45:20.763 4833-4833/de.slova I/Choreographer: Skipped 165 frames!  The application may be doing too much work on its main thread.
01-13 14:45:28.866 4833-4833/de.slova I/Choreographer: Skipped 248 frames!  The application may be doing too much work on its main thread.
01-13 14:45:30.442 4833-4833/de.slova I/Choreographer: Skipped 92 frames!  The application may be doing too much work on its main thread.
01-13 14:45:36.117 4833-4833/de.slova I/Choreographer: Skipped 250 frames!  The application may be doing too much work on its main thread.
```

Here the screenshot without any Picasso:

![screenshot_20190113-144552](https://user-images.githubusercontent.com/1884458/51086090-56059e80-1742-11e9-852b-a25d3672de4d.png)

**Comment by FabianTerhorst** [comment]
Track the time the onbind needs. It must be faster then 10ms.

**Comment by afarber** [comment]
Thank you, I will try finding that.

Or could the reason be, that the left fragment is embedded in a ViewAdapter?

**Comment by afarber** [comment]
I keep looking and haven't be able to find the reason for the scrolling issue yet.

I have prepared [a simple test case at Github](https://github.com/afarber/android-questions/tree/master/FastAdapterScrollingIssue) and have also asked [my question on Stackoverflow](https://stackoverflow.com/questions/54238509/scrolling-issue-with-fastadapter-and-constraintlayout-skipped-211-frames).

**Comment by afarber** [comment]
I have switched to LinearLayout and the issue has been solved.

It seems to be the problem of my ConstraintLayout, sorry.

**Comment by Agm91** [comment]
> I have switched to LinearLayout and the issue has been solved.
> 
> It seems to be the problem of my ConstraintLayout, sorry.

Technically, the ConstraintLayout is for better performance, was not it? Changing to LinearLayout solved it? Any clue why was it?
