### ISSUE TITLE
About RecyclerView Staggered HeaderAdapter

### ISSUE THREAD

**Issue by alphater** [mikepenz/FastAdapter#751]
## About this issue
When adding a Header view to the RecyclerView, and the LayoutManager is a StaggeredGridLayoutManager or a GridLayoutManager, the added Header View will only occupy one item and will not occupy the entire line. This is not what I want. How can I implement the Header View to take up the entire line? thank.
The effect can be seen in the screenshot below, thank you!
![image](https://user-images.githubusercontent.com/4635693/51436723-7a76f300-1ccd-11e9-8db5-eec0ab4696e9.png)

## Details
- [ 3.3.1 ] Used library version
- [ AndroidX ] Used support library version
- [ 4.10.1 ] Used gradle build tools version
- [ 3.3 ] Used tooling / Android Studio version

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by alphater** [comment]
`  
mFastAdapter = new FastAdapter<>();
mFastAdapter.setHasStableIds(true);
mFastAdapter.withSelectable(false);

mHeaderAdapter = items();
mItemAdapter = items();
mFooterAdapter = items();
mFastAdapter = FastAdapter.with(Arrays.asList(mHeaderAdapter, mItemAdapter, mFooterAdapter));

 mHeaderAdapter.add(new HeaderItem().withTitle(getString(R.string.unsplash_str)).withDescription(getString(R.string.title_by_photos)).withSearchHint("Search photos").withEnabled(false));
`

**Comment by mikepenz** [comment]
This is not really an issue of the `FastAdapter` but more a general `RecyclerView` question, specifically related the `StaggeredGridLayoutManager` 

Please refer to the official documentation of the `LayoutManager` to see if it supports what you need. 

For the `GridLayoutManager` you'd have to supply the `SpanSizeLookup` to tell it how many "columns" a specific element should occupy:

https://github.com/mikepenz/FastAdapter/blob/2c85956eb755e4ce44c5a5bd64999529afc94866/app/src/main/java/com/mikepenz/fastadapter/app/IconGridActivity.java#L62

**Comment by alphater** [comment]
Ok, thanks for the reply, thank you.
