### ISSUE TITLE
Unexpected behavior when used with databinding

### ISSUE THREAD

**Issue by ishdemon** [mikepenz/FastAdapter#752]
## About this issue

- When used with Databinding, Abnormal recycling of views happens, items overlapping, keeps changing after i scroll back, wrong image scaling, incorrect onclick
- **How can the issue be reproduced** : By incorporating Databinding in item adapter's .  Works perfect without Databinding. Tried returning incorrect id in _public int getType()_ which i guess disables the recycling of views and it works but then memory allocation is off the chart & ultimately crashes.
Even _setHasStableIds(true);_  still its glitching  all over the RecyclerView. 
   

## Details
- [ ] Used AndroidX
- [ ] Used gradle build tools version 3.3.0
- [ ] enabled setHasStableIds(true);

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by FabianTerhorst** [comment]
Hi, please show how you have implemented the data binding inside an item.

**Comment by FabianTerhorst** [comment]
You could try to override https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/items/AbstractItem.java#L291 instead of ```getViewHolder(View v)```. There you have more control when doing
```LayoutInflater layoutInflater =
                LayoutInflater.from(parent.getContext());
        ViewDataBinding binding = DataBindingUtil.inflate(
                layoutInflater, viewType, parent, false);
        return new ViewHolder(binding);
```

**Comment by khraibani-h** [comment]
any news on this ?

**Comment by ishdemon** [comment]
Nope. If you wanna use databinding in recyclerview, use generic Recyclerview Adapter.

**Comment by mikepenz** [comment]
Was there any resolution to this issue. Seems there was no more activity since

**Comment by mikepenz** [comment]
Please report back to re-open
