### ISSUE TITLE
Fast Adapter 4 - First Impressions

### ISSUE THREAD

**Issue by eakteam** [mikepenz/FastAdapter#753]
Hi there, i have just migrated my large project to Fast Adapter 4 (Kotlin). It costs me about 2 days with 6 hours work each day because i use this lib in first place to my app and it's little difficult to find some good examples when using this lib from Kotlin project too.

I just wanted to say that for the moment everything seems to be working OK (Comparator, Filter, Listeners, ItemAdapter etc.)

**Comment by mikepenz** [comment]
@eakteam that's impressive. Please let us know if there are things which can be further improved. If there is something which is inconvenient or confused, now is the time to still improve :) 

Happy to hear that so far everything seems working.

**Comment by eakteam** [comment]
To thank you for your great free work. Here you have 10 Promo codes to get my Pro app for free and to show respect for this library. 

Fast Adapter has made my job really easy and elegant. I think there are many minor things to improve especially for new programmers that are still learning Kotlin. Anyway i think is more easy than older version to implement and it should be faster and more stable.

Just for reference here you have my Free and Pro version of my app which mainly is using Fast Adapter.

FREE VERSION : 
https://play.google.com/store/apps/details?id=com.eakteam.networkmanager

PRO VERSION :
https://play.google.com/store/apps/details?id=com.eakteam.networkmanager.pro

I am saying again, this is not for adverstiment purposes. I just wanted to say that this library is awesome for the moment.

PROMO CODES FOR PAID VERSION : 

0) SR6UR92L60J3P3SHUZ3ZT7R
1) EN77WB1KEAM6UM2YCKFSMA6
2) BGCMUNB7AZC9TP6NMWKZWF5
3) DSUAF9RURYME477JCGM0FKD
4) GR8XKLPNXXPX99NYLMNT6YJ
5) 7QGL2CDM45SFZHSC26ZB4U9
6) BA82ZHAQXTBSSKN2Z0SME2U
7) PG450P9VF1YSTYDC2Z99FU1
8) NQN4XUYPWSC6H0Q6F2M83E6
9 )S0C9ZF2L0YZ4C97D711LY0S

Best Regards !

**Comment by mikepenz** [comment]
Thank you very much, I really appreciate this! 

Just had a look at the application. it contains quite a long list of functionalities.

If you have suggestions to improve v4 please let us know.

**Comment by FabianTerhorst** [comment]
Thanks a lot!

**Comment by eakteam** [comment]
@mikepenz in the latest release 4.0.0-rc03 i was using in Kotlin this : 

```
fastadapter.onClickListener = object: OnClickListener<SampleItem> {
            override fun onClick(v: View?, adapter: IAdapter<SampleItem>, item: SampleItem, position: Int): Boolean {
}
```

and 

```
itemAdapter!!.itemFilter.filterPredicate = object: IItemAdapter.Predicate<SampleItem> {
            override fun filter(item: SampleItem, constraint: CharSequence?): Boolean {
                return item.emri.toLowerCase().contains(constraint.toString().toLowerCase())
            }
        }
```

But listener classes doesn't exist any more and IItemAdapter.Predicate<SampleItem> too

I was using 4.0.0-rc02

**Comment by mikepenz** [comment]
@eakteam we decided as FastAdapter is now 100% kotlin we should also improve comaptiblity with kotlin and use kotlin interface types for the listeners instead of interfaces to allow lambdas. 

this allows you to write even shorter code, and simplifies the code in general. 

E.g. you do no longer go the complex route to specify the whole filter. just directly pass in the lambda to the filter predicate

**Comment by eakteam** [comment]
Can you please show a short example for how to implement ClickListener & Predicate too ?
Thanks

**Comment by mikepenz** [comment]
@eakteam yes sure :) 

So instead of: 
```
fastadapter.onClickListener = object: OnClickListener<SampleItem> {
            override fun onClick(v: View?, adapter: IAdapter<SampleItem>, item: SampleItem, position: Int): Boolean {
}
```
you can now use a lambda and write directly:
```
fastadapter.onClickListener = { v, adapter, item, position -> 
     true
}
```

and instead of
```kotlin
itemAdapter!!.itemFilter.filterPredicate = object: IItemAdapter.Predicate<SampleItem> {
            override fun filter(item: SampleItem, constraint: CharSequence?): Boolean {
                return item.emri.toLowerCase().contains(constraint.toString().toLowerCase())
            }
        }
```
you can now simply write:
```kotlin
itemAdapter!!.itemFilter.filterPredicate = { item, constraint ->
    item.emri.toLowerCase().contains(constraint.toString().toLowerCase())
}
```

**Comment by mikepenz** [comment]
sadly kotlin does not allow this notation if a interface written in kotlin is used. only for java interfaces. 

kotlin favors kotlin function types which we embrace now :)

**Comment by eakteam** [comment]
@mikepenz Ohhhh my god, i have maybe 15 hours coding something special in my app and when you release the latest version i going crazy how to use this only because of missing "=" before {
Best Regards

**Comment by mikepenz** [comment]
I am really sorry that we had to put that in, but we felt like this is a super important upgrade to help the code get more simple :) 

not sure if you use expandables, but there was also a tiny change for the `IParentItem` interface, which should make the usage of it more convenient.

**Comment by eakteam** [comment]
@mikepenz i think everything is Ok right now, i have started new implementation. The upgrade is really great, more understandable and more better. But because of many hours here with my laptop maybe you know how it feels, things are getting crazy :D :D :D.
Best Regards

**Comment by eakteam** [comment]
@mikepenz , after hours of refactoring i can confirm that for the purposes that i use this library everything is working perfectly. 
Because of this great lib, just to say, i have choose to put it in the "Special Thanks" menu of my app.
This will be done in the next Public release. After this i will contact you again to give your(team or one person who is working with this) 50 more Promotional Codes for everyone who use this library too in their App/Apps to get for Free my Paid app. I want to do this because i didn't find any donation link and  this lib was the reason that makes me go forward in Android programming some years ago. So i feel in dept with you. 

P.s : I don't want to do this to promote my app sincerely, this is just my wish to respect this work, because some years before i really didn't know nothing how to write Java code(i was C# programmer) and you helped me a lot.
If you want you can delete this comment if it is not suitable and i will contact you after next Public release.
Thank you and sorry for my low English, hope to understand me well :) :) ...

**Comment by rasheedk** [comment]
> @mikepenz , after hours of refactoring i can confirm that for the purposes that i use this library everything is working perfectly.
> Because of this great lib, just to say, i have choose to put it in the "Special Thanks" menu of my app.
> This will be done in the next Public release. After this i will contact you again to give your(team or one person who is working with this) 50 more Promotional Codes for everyone who use this library too in their App/Apps to get for Free my Paid app. I want to do this because i didn't find any donation link and this lib was the reason that makes me go forward in Android programming some years ago. So i feel in dept with you.
> 
> P.s : I don't want to do this to promote my app sincerely, this is just my wish to respect this work, because some years before i really didn't know nothing how to write Java code(i was C# programmer) and you helped me a lot.
> If you want you can delete this comment if it is not suitable and i will contact you after next Public release.
> Thank you and sorry for my low English, hope to understand me well :) :) ...


Please post comments / issues on this awesome library .
We do respect **mikepenz** and his open source works a lot  . Please don't use his works as a promotion to your app.

**Comment by eakteam** [comment]
@rasheedk 
> Please post comments / issues on this awesome library .
> We do respect **mikepenz** and his open source works a lot . Please don't use his works as a promotion to your app.

I removed, sorry

**Comment by lmalsch** [comment]
> 
> 
> @eakteam yes sure :)
> 
> So instead of:
> 
> ```
> fastadapter.onClickListener = object: OnClickListener<SampleItem> {
>             override fun onClick(v: View?, adapter: IAdapter<SampleItem>, item: SampleItem, position: Int): Boolean {
> }
> ```
> 
> you can now use a lambda and write directly:
> 
> ```
> fastadapter.onClickListener = { v, adapter, item, position -> 
>      true
> }
> ```
> 
> and instead of
> 
> ```kotlin
> itemAdapter!!.itemFilter.filterPredicate = object: IItemAdapter.Predicate<SampleItem> {
>             override fun filter(item: SampleItem, constraint: CharSequence?): Boolean {
>                 return item.emri.toLowerCase().contains(constraint.toString().toLowerCase())
>             }
>         }
> ```
> 
> you can now simply write:
> 
> ```kotlin
> itemAdapter!!.itemFilter.filterPredicate = { item, constraint ->
>     item.emri.toLowerCase().contains(constraint.toString().toLowerCase())
> }
> ```

I'm using Kotlin to write my app. I can't use the shorter syntax with FastAdapter 4.0.0-rc02.
Is it only available with 4.0.0-rc03? And where can I find that version?

**Comment by mikepenz** [comment]
@lmalsch it should be released to bintray. you can't resolve it?

https://bintray.com/mikepenz/maven/com.mikepenz:fastadapter/4.0.0-rc03

**Comment by lmalsch** [comment]
> 
> 
> @lmalsch it should be released to bintray. you can't resolve it?
> 
> https://bintray.com/mikepenz/maven/com.mikepenz:fastadapter/4.0.0-rc03

Sorry I looked it up on the wrong repo. Now it works, thank you.

**Comment by eakteam** [comment]
Thanks for the latest update `4.0.0-rc04`. 
For my needs(ItemAdapter, Sorting, Filtering) everything seems to works like a charm :) !
Latest Kotlin implementation was needed because of a bug which not compile to Java 1.8 bytecode.
Thanks, Great Work !

**Comment by mikepenz** [comment]
sounds good :) I really hope that this is (one of) the last rc before the final release. 

I wished some more people would pre-test to ensure the APIs are all convenient to use

**Comment by eakteam** [comment]
"I wished some more people would pre-test to ensure the APIs are all convenient to use" -> {
I think you are joking because it is really stable and optimized :D :D :P (Joking)
Sure that this will be awesome, and as i said thanks again for this great help !

I have finally choose to promote this to my "app's special thanks" menu. I think that Google should take a look here like they do with "room database library". Maybe this may seems crazy but they really should take a look :) .
Best Regards, i will try to be the first person always, who test latest releases :D .
Have a great day !
