### ISSUE TITLE
Issue when using Drag n' Drop and DiffUtils together

### ISSUE THREAD

**Issue by IIIuminator** [mikepenz/FastAdapter#755]
## About this issue

- Briefly describe the issue
I'm updating the item list over network and using `FastAdapterDiffUtil` to calculate a diff between new and old list in a `LiveData.observe`. I also have a SimpleSwipeDragCallback attached to the `RecyclerView`. Furthermore I have a `onLongClickListener` setup that pauses the LiveData observation while an item is being moved and restarts them in `itemTouchDropped`. This works properly exactly one time after app launch. After that the Item is dropped as soon as is has been moved by one position. I checked and it only happens with when using `FastAdapterDiffUtil`. If I instead just use `fastItemAdapter.set(newList)` there is no issue, same with a custom usage of `AsyncListDiffer` (which In was using before I found `FastAdapterDiffUtil`).
It seems that the issue is caused by `FastAdapterDiffUtil`, although the first population of the list is done that way too.
Would be thankful about some pointer on how to debug this or what might be wrong with my code. Already looked through the sources of the utils and didn't find't anything that looked like it could cause this behavior.
- How can the issue be reproduced / sample code
https://github.com/IIIuminator/EnQ/blob/1b039c912c85cc4f0bafc867368dd9b138a709da/app/src/main/java/me/iberger/enq/ui/fragments/QueueFragment.kt#L77-L87

## Details
- [4.0.0-beta1] Used library version
- [appcompat:1.1.0-alpha02, recyclerview: 1.1.0-alpha02] Used support library version
- [3.5.0-alpha03] Used gradle build tools version
- [3.5 Canary 3] Used tooling / Android Studio version
- [Fastadapter extensions: utils, ui, drag, swipe, diff] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by FabianTerhorst** [comment]
Have you tried overriding the identifier in your QueueItem, because the recyclerview is handling it differently when same items also have the same identifier?

**Comment by IIIuminator** [comment]
setting a proper identifier fixed the issue, thanks!
