### ISSUE TITLE
Looking for sample code for Fastadapter v4

### ISSUE THREAD

**Issue by Hub2018** [mikepenz/FastAdapter#756]
I'm new with Fastadapter and I'm trying to use directly the latest version 4 in Kotlin, however I'm really struggling to make it work.

I'm wondering if anyone could post a small sample project with Fastadapter 4? It would be extremely helpful especially for beginners!
Thank you!

**Comment by mikepenz** [comment]
@Hub2018 if you jump on the v4 branch. we have already migrated the full sample app to kotlin: 

https://github.com/mikepenz/FastAdapter/tree/feature/v4

For example the main activity: 
https://github.com/mikepenz/FastAdapter/blob/feature/v4/app/src/main/java/com/mikepenz/fastadapter/app/SampleActivity.kt

The sample app for v4 has the same contents, just everything updated to the new version

**Comment by Hub2018** [comment]
Great, thank you! I will have a look!

**Comment by mikepenz** [comment]
If you have any questions, or suggestions for improvements please let us know.
