### ISSUE TITLE
Can´t multiple or single select expandable items in ExpandableMultiselectDeleteSampleActivity

### ISSUE THREAD

**Issue by smarques84** [mikepenz/FastAdapter#758]
We have a use case where we need to single select an expandable item so the user can add subitems or delete the expandable item itself.

We already analyzed the code but can´t find out why we can't select an expandable item, maybe its a limitation from the ExpandableItem? How can we achieve the desired behavior?

Version used: FastAdapter 3.3.1

**Comment by smarques84** [comment]
Another possible solution for us was to use the Swipe Action in our Expandable Item but we need 3 actions for that to work, Add SubItem, Edit Expandable Item (Like Text), and Delete Expandable Item and the swipe example only seems to handle two actions and not more. 

Maybe create an alternative like Facebook Messenger where we can swipe to left and have 3 buttons to select from?

**Comment by FabianTerhorst** [comment]
Have you tried getting the expandable items selection working in version 4? The version includes a lot of improvements for expandable items.

**Comment by smarques84** [comment]
Hello @FabianTerhorst, not we didn´t tried version 4 yet, i can see that the rc2 was released 3 days ago. Our project is an old project made mostly in Java so I have to ask if the new kotlin version of FastAdapter will play nice with Java?

**Comment by FabianTerhorst** [comment]
Yes it plays nicely in java and there is also less migration needed when migration from java v3 zo v4 then from kotlin v3 to v4.

**Comment by mikepenz** [comment]
v4.0.0-rc03 will most likely add a few changes to your code (if you use java7 and not java8 lambdas) but it still should play nicely with java :)
