### ISSUE TITLE
Can't define own filter implementation

### ISSUE THREAD

**Issue by lmalsch** [mikepenz/FastAdapter#767]
## About this issue

I need to define my own filter implementation.

```kotlin
// CustomFilter extends android.widget.Filter 
val customFilter = CustomFilter()
// Doesn't work
itemAdapter.itemFilter = customFilter
```

The documentation of `ModelAdapter` states that this should be possible.

```kotlin
/**
* allows you to define your own Filter implementation instead of the default `ItemFilter`
*/
var itemFilter = ItemFilter(this)
```

## Details
- Used library version: 4.0.0-rc03

**Comment by mikepenz** [comment]
can you extend `ItemFilter`?

**Comment by lmalsch** [comment]
No I can't extend `ItemFilter`, because the class is not opened.

**Comment by mikepenz** [comment]
Closing this as the PR was merged
