### ISSUE TITLE
Run with Android Studio 3.5 c13,Successful install,but appear error!

### ISSUE THREAD

**Issue by lydlovexyz** [mikepenz/FastAdapter#770]
<img width="790" alt="微信截图_20190428094059" src="https://user-images.githubusercontent.com/19246347/56857036-b095d400-699a-11e9-8356-ce70d90bb890.png">

**Comment by mikepenz** [comment]
@lydlovexyz I am not really sure. You try to build the sample app?

**Comment by lydlovexyz** [comment]
yes, build the sample app

**Comment by mikepenz** [comment]
I can not reproduce this in any way :/ 

Are you sure you are building the right thing? (I use AS 3.5 c13 myself)
