### ISSUE TITLE
disable scrolling when element is focused on abstractitem

### ISSUE THREAD

**Issue by AhmedX6** [mikepenz/FastAdapter#771]
hello,

Thank you for your library.
Please could you tell me how to disable scroll when element in view in abstractItem is focused (ACTION_DOWN) and how to reenable the scroll again when this element is ACTION_UP.

Thanks for help

**Comment by mikepenz** [comment]
@AhmedX6 the adapter only provides the items, for scroll behavior or similar you should check the RecyclerView documentation
