### ISSUE TITLE
[v6.x] Add optional Item List implementation that is using a coroutine channel for synchronization and queue background work

### ISSUE THREAD

**Issue by ivoberger** [mikepenz/FastAdapter#772]
## About this issue

- Briefly describe the issue
As stated [here](https://stackoverflow.com/questions/31759171/recyclerview-and-java-lang-indexoutofboundsexception-inconsistency-detected-in) and [here](https://issuetracker.google.com/issues/37030377#comment12) the recycler views internal list needs to be updated on the main thread as otherwise there may be inconsistencies. The current implementation of `FastAdapterDiffUtil` has separate `calculateDiff` and `set` functions which is great for doing the diff calculation on a background thread. The issue is that `calculateDiff` also updates the adapter internal list, which also happens on a background thread if that's where the diff is calculated. It is however mandatory to call the `set` part on the main thread as otherwise android complains that anything other than the main thread is touching its views.
For that reason`FastAdapterDiffUtil` needs to always perform the `adapterItem` update on the main thread.
- How can the issue be reproduced / sample code
https://github.com/IIIuminator/EnQ/blob/149ed0202db876d11b2e8f7eb033b105cac8199f/app/src/main/java/com/ivoberger/enq/ui/fragments/QueueFragment.kt#L95-L104
Any similar implementation like that (`calculateDiff` on background thread, `set` on main thread) will at some point crash. It sometimes takes a while but it happens every time. In that particular sample there are queue updates twice a second meaning is happens pretty quickly.

## Details
- [4.0.0-rc04] Used library version

**Comment by FabianTerhorst** [comment]
Hi, 
can you point to the place where ```The issue is that calculateDiff also updates the adapter internal list``` is happening. Are you talking about the ```collapseIfPossible```? Because i didn't had a single crash because of that and im running calculateDiff in background. But im synchronizing it via a single coroutine and channels to queue item changes and calculate them in background.

**Comment by IIIuminator** [comment]
I'd assume its [this](https://github.com/mikepenz/FastAdapter/blob/v4.0.0-rc04/library-extensions-diff/src/main/java/com/mikepenz/fastadapter/diff/FastAdapterDiffUtil.kt#L63-L71) code. I'm also a bit confused as to why it happens as it's clearly sequential in my code but from what I found when looking up the issue it points to that and doing all of it on the main thread does fix the issue.

**Comment by FabianTerhorst** [comment]
Thats just modifying the arraylist without notifying the recyclerview about it. That only leads to inconsistency when done concurrent or in wrong order.

**Comment by IIIuminator** [comment]
Ah. I'm sorry to bother you, I think I just figured it out. It's because the next update is arriving before the old one is finished, not because the update func isn't sequential
So thanks for making me think about it  :smile:

**Comment by FabianTerhorst** [comment]
Thats probably something that can be improved with a custom item list that does synchronization internally with a coroutine and a channel.

**Comment by IIIuminator** [comment]
that sounds helpful. I fixed my issue with a conflated channel. would make sense to have, especially in the shiny new kotlin version of fastadapter

**Comment by AllanWang** [comment]
I may be interested in this, since I'm making a similar variant for my own library.
I didn't end up using a conflated channel, but just referenced a job that I would cancel on new requests. Conflated makes sense if you want every request (without pending requests) to go to completion

**Comment by mikepenz** [comment]
I'll close this ticket due to inactivity. 

Ultimately the `FastAdapter` will be used less and less thanks to Compose get less and less :D which brings us an adapter less world :D
