### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by prsolucoes** [mikepenz/FastAdapter#773]
## About this issue

I have only some questions:

1. In our app our recycler view is using diff util to add/remove items with more performance instead of notify full dataset. How i can use diff util in this library or append/prepend items to it?

2. Some our lists have different cell types in the same list (banner, product carousel, fixed item etc). In the example on readme i see that don't have any parameter on layout res to detect what type of layout need be return. How to do it?

3. There is any benchmark compared to recycler view and diff util?

Thanks.

**Comment by mikepenz** [comment]
@prsolucoes 

You can use the diff util the same way. Also there is a diff util wrapper provided to simplify usage with the FastAdapter. 

An item is supposed to be 1 representation. you can split apart model and item and have a mapping strategy on how 1 item is resolved by 1 model. 
Also you can always have a base item and then have an implementation which specifies the unique `id`  per item type (very important) and the layout file + the bind logic for your element.

**Comment by mikepenz** [comment]
Please report back if you need additional details
