### ISSUE TITLE
[Feature Request] Reified functions

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#775]
Relevant to 4.x.x

For any function that takes in a single class, you may also use reified classes:

eg

```kt
fun <T : IAdapterExtension<Item>> getExtension(clazz: Class<in T>): T? {
    return extensionsCache[clazz] as T
}
```

can be enhanced with

```kt
inline fun <reified T : IAdapterExtension<Item>> FastAdapter<Item>.getExtension(): T? =
    getExtension(T::class.java)
```

---

As a side note, you either want the first definition to be `as T?` to allow missing extensions, or `as? T` to also ignore casting incompatibilities (which is probably a library bug is that happens), or for the return type to be non nullable.

**Comment by mikepenz** [comment]
@AllanWang thank you so much for all those nice improvements.

Please consider opening a PR :) 

I think it would be possible to have a nullable `getExtension` and a non-nullable `requireExtension` (similar like android does it for the `requireViewById` or so).

**Comment by AllanWang** [comment]
Great. I will be making a PR shortly
