### ISSUE TITLE
Mark functions as opened in FastItemAdapter

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#776]
v4.0.0

Currently, `FastItemAdapter` is opened, meaning that it can be extended.
However, all of its functions are final, so it isn't extremely useful.
Consider marking functions as `open` as well so that they can be overridden.

As an example, I used to have a `FastItemThemedAdapter`, there it would modify the items before they were added.

**Comment by mikepenz** [comment]
Oh yes. absolutely. Still want to allow developers to be able to extend classes and overwrite everything. As I don't see huge advantage of locking down library code too much. As there are always cases which might not have been thought of.
