### ISSUE TITLE
Upload codestyle

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#778]
Please upload codestyle (part of `.idea` folder), or consider using something like `ktlint` or `spotless` so that contributors can easily conform to the current configurations.

**Comment by mikepenz** [comment]
We use default AS configuration without modifications :)

**Comment by AllanWang** [comment]
It's weird because I don't think I've ever changed my configs, yet it's different. For me continuation indent is 8?

**Comment by mikepenz** [comment]
![image](https://user-images.githubusercontent.com/1476232/59418006-8d977600-8dc8-11e9-87c1-75ad63572667.png)

**Comment by mikepenz** [comment]
[Default.xml.zip](https://github.com/mikepenz/FastAdapter/files/3284997/Default.xml.zip)

**Comment by AllanWang** [comment]
What about kotlin though? The kotlin code does not have a continuation of 8, so either your default is different or your style was changed by the contributor

**Comment by mikepenz** [comment]
I have quickly reformatted all files. but in general it looked fine.

**Comment by mikepenz** [comment]
Ok sorry with the formatting I resulted in this one conflicting for you: https://github.com/mikepenz/FastAdapter/pull/780

**Comment by AllanWang** [comment]
Okay now it conforms. If you'd like, I'd recommend something like `spotless` to help you check this in your CI so such changes won't happen again in your `develop` branch. I'll fix the conflict

**Comment by mikepenz** [comment]
code style and inspections where uploaded: https://github.com/mikepenz/FastAdapter/tree/develop/DEV ;)
