### ISSUE TITLE
ExtensionsFactory class restriction

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#779]
Concerns v4.0.0

Is it a problem to add a generic to `ExtensionFactory`, such that `create` must return a value of instance `clazz`? Otherwise there is no guarantee that the two match at compile time. I think in all other cases you don't care about the generic so you can treat it like `ExtensionFactory<*>`. It might be more verbose though since that generic needs to extend `IAdapterExtension`... etc

**Comment by mikepenz** [comment]
As far as I can say is that I was having some problems during the creation of v4 as Kotlin is much more strict when it comes to generics.

But I like in general to have generics checked and ensure the proper types.
