### ISSUE TITLE
Proguard Error with FastAdapter extensions

### ISSUE THREAD

**Issue by R4md4c** [mikepenz/FastAdapter#78]
Hello,

I'm getting these two errors when using Proguard on an application that uses FastAdapter, although I'm not using UndoHelper in my code.

```
Warning:com.mikepenz.fastadapter_extensions.UndoHelper: can't find referenced method 'void remove(int)' in program class com.mikepenz.fastadapter.IItemAdapter
Warning:com.mikepenz.fastadapter_extensions.UndoHelper: can't find referenced method 'void add(int,com.mikepenz.fastadapter.IItem[])' in program class com.mikepenz.fastadapter.IItemAdapter
```

I don't see any proguard rules to add with FastAdapter in the repo, perhaps I'm missing something?

**Comment by mikepenz** [comment]
@R4md4c as you do not use it, it should not matter as those are just **Warning**s. The `UndoHelper` is  a standalone class not used from the `FastAdapter` core itself

**Comment by R4md4c** [comment]
Yeah That is correct, It was fixed by adding the line 
``` -dontwarn com.mikepenz.fastadapter_extensions.UndoHelper``` 
to the proguard-rules.pro file.

Also I've noticed that ReflectionBasedViewHolderFactory, doesn't work when proguard is enabled, because it tries to find the ViewHolder using reflection and it fails because this ViewHolder might be obfuscated. Don't you think that you think that you should mention in README.md that you have to provide your own ItemFactory when proguard is enabled?

**Comment by mikepenz** [comment]
@R4md4c yeah had planned to add this to the README, but have not yet found the time for it

**Comment by R4md4c** [comment]
Great then, Thank you for your extremely nice library!

**Comment by Rainer-Lang** [comment]
@mikepenz there is a github project like "android proguard snippet". Your libs could be added there.

**Comment by mikepenz** [comment]
added to readme ;)
