### ISSUE TITLE
Use interfaces and delegations to propagate functions

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#781]
Given that you are okay with marking classes as nonfinal, a good way to propagate functions is to make interfaces and use delegations.

As an example, the majority of the functions in `FastItemAdapter` simply relay it to `itemAdapter`.

If you instead had an interface of all such functions implemented by `ItemAdapter`, you could do

`FastItemAdapter(val itemAdapter: ...): TheInterface by itemAdapter`.

This is a lot less verbose and will avoid you forgetting to add the functions if `ItemAdapter` changes

**Comment by AllanWang** [comment]
The caveat is that your return type would remain constant. In general, the kotlin way may be to just use `.apply { }` to chain functions, instead of the builder pattern. This would make it more annoying for the java users though

**Comment by mikepenz** [comment]
@AllanWang yeah I wanted to get used more to the delegation functionality of kotlin anyways. I like it. 

In general I think it is really save to say that v4 is really kotlin first, and that it should be ok to make design decisions based on this concept. 

Also java users always have the chance for going with v3 :D

**Comment by mikepenz** [comment]
PR to fix this opened
