### ISSUE TITLE
AbstractItem#isSelectable should probably be read only

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#783]
In almost all situations, getting the value is through some other field. In that case, it doesn't make sense to add a setter. 

I think the only case where the setter is not blank is

https://github.com/mikepenz/FastAdapter/blob/0cd1406eb3dcf361b963a8fd63ad9b8f72a15cb4/app/src/main/java/com/mikepenz/fastadapter/app/items/expandable/SimpleSubExpandableItem.kt#L56-L61

Note that `subItems` is never null, and calling `isSelectable` from the parent likely won't do anything

**Comment by mikepenz** [comment]
@AllanWang theoretically people can design the items to change the selectable state on per element base. 

Not done in the sample, but I can think of usecases where this might be relevant.

**Comment by AllanWang** [comment]
Fortunately you can override `val` with `var`

```kt
open class A {
    open val a: Boolean = true
}

class B : A() {
    override var a: Boolean = true
}
```

**Comment by AllanWang** [comment]
Oh nvm. I see that you call the modifier yourself. In that case this is void
