### ISSUE TITLE
Cleaning up operator fun

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#787]
Given some breaking changes in PRs #784 and #777 ([comment](https://github.com/mikepenz/FastAdapter/pull/777/files#r293699632)), perhaps it is worth looking into the other instances of `operator`

https://github.com/mikepenz/FastAdapter/blob/40dbc20288b01639f8ab6ddedb121fcf0796dc04/library-core/src/main/java/com/mikepenz/fastadapter/IItemList.kt#L29-L31

For instance, `list[pos, item] = preItemCount` might not make sense here.
Same goes for:

https://github.com/mikepenz/FastAdapter/blob/43509d1667504e7c5fbcf9033ce4a1e7ad86d25a/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.kt#L176

https://github.com/mikepenz/FastAdapter/blob/43509d1667504e7c5fbcf9033ce4a1e7ad86d25a/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.kt#L190-L194

**Comment by mikepenz** [comment]
@AllanWang before merging those PRs I have reverted the removed operator use to not break the API. 

We just launched v4 with a big amount of breaking changes and would like to stay API compatible now for a while again :)

**Comment by AllanWang** [comment]
Okay makes sense. Just wanted to remind you since I didn't see the commit within the PR. That's fine then

**Comment by mikepenz** [comment]
Thank you very much!

**Comment by mikepenz** [comment]
I think we might want to close the ticket and re-evaluate for v5 or v4.1

Opened a project for it: https://github.com/mikepenz/FastAdapter/projects/2
