### ISSUE TITLE
Only one item expanded at the item

### ISSUE THREAD

**Issue by mikepenz** [mikepenz/FastAdapter#79]
Evaluate if a "Expandable"-Group would make sense

- item (group 1)
 - item
 - item
 - item
- item (group 1)
 - item
 - item
 - item 
- item (group 2)
 - item
 - item
 - item 

So in the above example only one expandable item of group 1 can be expanded at a single time

**Comment by Rainer-Lang** [comment]
@mikepenz Only one group could be expanded at the same time?

**Comment by mikepenz** [comment]
yes

**Comment by Rainer-Lang** [comment]
Makes sense - stop "evaluating" ;-)
