### ISSUE TITLE
[Question] Binding events

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#791]
I'm looking over the event hook code

https://github.com/mikepenz/FastAdapter/blob/4240451aa5c474638e25acd42134174a70c82f66/library-core/src/main/java/com/mikepenz/fastadapter/utils/EventHookUtil.kt#L48-L54

I wonder what the decision was to get the item from the adapter vs from the tag, set by 

https://github.com/mikepenz/FastAdapter/blob/7f7fe04b3b844106f913bdb76472e52e370cdabb/library-core/src/main/java/com/mikepenz/fastadapter/listeners/OnBindViewHolderListenerImpl.kt#L26-L28

**Comment by mikepenz** [comment]
Mainly for historical reasons.

I believe we should change this also to the tag use, can't think of a reason why not. especially as we use the tag already in most places via: 
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt#L1019
