### ISSUE TITLE
[Question] Why use alpha versions of androidx libraries?

### ISSUE THREAD

**Issue by DeweyReed** [mikepenz/FastAdapter#799]
## About this issue

I notice that 4.0.1 uses many alphas in the `build.gradle`:

```
recyclerView    : '1.1.0-alpha06',
material        : '1.1.0-alpha07',
appcompat       : '1.1.0-beta01',
drawerlayout    : '1.1.0-alpha01',
constraintLayout: '2.0.0-beta1',
```
Many apps are not ready for those alpha versions. I'm wondering why we use alpha instead of good old 1.0.0.

Thank you!😉

## Details
- [4.0.1] Used library version

## Checklist

- [√] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [√] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [√] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [√] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [√] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by FabianTerhorst** [comment]
Only the sample app is using alpha dependencies. The core uses androidx version for recyclerview which is set to 1.0.0.

**Comment by mikepenz** [comment]
Also @DeweyReed you can always specify the specific version you want to use as long as the major version is the same.

E.g.:
https://github.com/mikepenz/FastAdapter/blob/develop/app/build.gradle#L154

**Comment by DeweyReed** [comment]
My bad, I didn't check carefully. But the core does use appcompat 1.1.0-beta01 which may break appcompat 1.0.X users.
Since androidx beta is almost stable, I'll upgrade to 1.1.0-beta01.
Thanks!

**Comment by mikepenz** [comment]
According to the version scheme there should be no breaking changes for minor updates. 

so 1.x.y should be in general compatible. Unless new features are used, but that would be pointed out in the changelog

**Comment by Tolriq** [comment]
Unfortunately they do not follow that :( They change a lot of nullability annotations for 1.1 that breaks many things and require quite a lot or work to adapt to when dealing with tons of generics.
