### ISSUE TITLE
Just add @JvmStatic

### ISSUE THREAD

**Issue by iamareebjamal** [mikepenz/FastAdapter#800]
> As a result of the Kotlin migration the static methods can now be accessed via FastAdapter.Companion. E.g.: FastAdapter.Companion.with(...)

Just add `@JvmStatic` on methods. Refactoring to Kotlin will definitely add breaking changes, but doesn't mean you have to break the things which have a working solution to

**Comment by AllanWang** [comment]
@mikepenz if you want this I can send a patch

**Comment by mikepenz** [comment]
@AllanWang sure. we can bring this in v4.1-beta01

**Comment by AllanWang** [comment]
Functions were already marked as `@JvmStatic` so I've updated migration docs
