### ISSUE TITLE
DiffCallbackImpl as object

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#801]
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-diff/src/main/java/com/mikepenz/fastadapter/diff/DiffCallbackImpl.kt

Should we make this an object? It'll save us from having to create a new instance each time. The class isn't open so no one can use it as an adapter anyways

**Comment by FabianTerhorst** [comment]
It is not opened, because in most cases you need a own implementation by extending DiffCallback. Item identifiers don't help you when they are auto generated. Its right now just a default callback that only works for very basis usecases.

**Comment by AllanWang** [comment]
I'm not making a case that it should be opened. I'm saying that since it isn't opened, people can't extend it, and likely won't be referencing it too much. Converting to an object will be a breaking change, but it shouldn't affect many users unless they create `DiffCallbackImpl` themselves

**Comment by AllanWang** [comment]
In that case as well, shouldn't this be internal?

**Comment by mikepenz** [comment]
Also as object: 
![image](https://user-images.githubusercontent.com/1476232/60755551-91966c80-9ff1-11e9-9540-605945308722.png)
