### ISSUE TITLE
DSL Autosuggest problem

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#805]
With `fastAdapter` being the initial dsl block, using any field named `fastAdapter` leads to the dsl being suggested first. It may become quite annoying for some users, so perhaps you'd rather make it `operator invoke` from the `FastAdapter` class. That way it needs to be capitalized

**Comment by mikepenz** [comment]
Sadly is that this does not function:

![image](https://user-images.githubusercontent.com/1476232/60742403-8c8fd980-9f6d-11e9-8781-b2973c96f0f6.png)

The user would be required to write: 
![image](https://user-images.githubusercontent.com/1476232/60742412-987b9b80-9f6d-11e9-8379-4990602006d0.png)

So I think we should keep the current variant

**Comment by AllanWang** [comment]
Maybe others will provide inputs eventually, but I think the autosuggest problem is a pretty big hassle. It comes down to a naming preference. Those who don't name their field `fastAdapter` won't have a problem.

**Comment by AllanWang** [comment]
```kt
operator fun <Item : GenericItem> FastAdapter.Companion.invoke(block: (FastAdapter<Item>).() -> Unit): FastAdapter<Item> {
    return fastadapter(block)
}

fun test() {
    FastAdapter<GenericItem> {
        itemAdapter<> {  }
    }
}
```

It seems to work fine. You can decide whether you want it under `companion` or as an extension like above
