### ISSUE TITLE
Potential bug in getExpandedItemsRootLevel

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#807]
https://github.com/mikepenz/FastAdapter/blob/3c2db81d62bc747a60d13a9930f45031337c8af6/library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.kt#L307-L314

The backing list is nullable, so if a value is null, the associated index in `expandedItems` will not be set. Wouldn't you want to filter out a nonnull list and only return the indices there instead of potentially having some 0s in the int array?

**Comment by FabianTerhorst** [comment]
That would break existing code, but adding another method would be possible.

**Comment by mikepenz** [comment]
I pushed this change. Hopefully it addresses your concern: https://github.com/mikepenz/FastAdapter/commit/fde3f0d731dea332ea72189b27ad2ad38aa2ff49
