### ISSUE TITLE
[Question] bindView signature

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#813]
Should payloads really be mutable? Should an item ever modify the payload or should it actually be read only?

**Comment by FabianTerhorst** [comment]
The recyclerview library signature is using a MutableList as well thats why and its now impossible to change without breaking existing code.

**Comment by AllanWang** [comment]
Which library are we referring to? `androidx.recyclerview.widget.RecyclerView` is still in java with signature `public void onBindViewHolder(@NonNull VH holder, int position, @NonNull List<Object> payloads`

**Comment by FabianTerhorst** [comment]
Yes and the list interface has a add method that's why it's a mutable list in kotlin.

**Comment by FabianTerhorst** [comment]
But we can add this to the list for fastadapter 5.x i think.

**Comment by AllanWang** [comment]
The list interface does have add, but we can still define a superclass in the constructor.

Part of why I'm asking is I'm migrating to the new FastAdapter in one of my projects and all my signatures were (kotlin) `List`. Changing the signature to `List` will only affect users who use it as `MutableList`, which they probably shouldn't in the first place. Keeping it as `MutableList` affects those who use `List`, and you also won't be able to call the function with immutable lists.

All things to consider for 5.x

**Comment by FabianTerhorst** [comment]
> Changing the signature to List will only affect users who use it as MutableList, which they probably shouldn't in the first place
With current interface you get a compile error when not using MutableList inside a item from library user perspective. But for 5.X that breaking change is fully acceptable.

**Comment by mikepenz** [comment]
There is a v5 branch now available. If this is still of a concern please consider creating a branch towards v5 with these changes :). 

So we can get v5 on track

**Comment by mikepenz** [comment]
Otherwise please close this issue

**Comment by mikepenz** [comment]
Btw. I believe we had it immutable at some point but that resulted in compile time issues.

**Comment by AllanWang** [comment]
^ Can you clarify where the compile error is?

**Comment by AllanWang** [comment]
![image](https://user-images.githubusercontent.com/6251823/74916975-a1de3a80-537b-11ea-8154-49bbe4b2aefc.png)

At least static inference isn't showing a compilation error.

**Comment by mikepenz** [comment]
It's 1 or 2 years back :/ I remember there have been problems with it conflicting, not sure if it was the generic definition, or mutable spec. but I believe we may simple try :D

**Comment by AllanWang** [comment]
I'm going to ask the kotlin slack channel, since technically the java implementation can use `add` in the java interface, but a kotlin list may not provide it

**Comment by mikepenz** [comment]
It's fine we simply can try it again. if things are fine in kotlin it should be good. 

There was some topic a long time ago, I really can't think anymore what particular it was. but maybe it would be fixed by now :)

**Comment by AllanWang** [comment]
As a reason about it myself, I do believe that this is a similar mindset as overriding a java method and enforcing nonnull attributes. So long as the usage adheres to the new interface, it should be fine. The added bonus is that it is very likely that the underlying data type is mutable anyways
