### ISSUE TITLE
Support GenericFastAdapter for Drag n drop, filtering

### ISSUE THREAD

**Issue by kaushalyap** [mikepenz/FastAdapter#815]
I was trying implement a RV with multiple view types ex: [MultiModelItemActivity](https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeModelItemActivity.kt) where there items are separated by headers (2 view types: header view, item view). I want to allow drag and drop items under different headers and support filtering of items through search

 Currently 
- `DragDropUtil.onMove()` accept an `ItemAdapter` so cannot be used with `GenericFastAdapter`
- `GenericFastAdapter` does not support filtering

Is there any way to achieve what I want ?

**Comment by mikepenz** [comment]
@kaushalyap the sample also has an `itemAdapter`: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeModelItemActivity.kt#L39

The FastAdapter is the managing element. the `ItemAdapter` is the specific implementation which knows how to work with items. where they are located and so on.

**Comment by kaushalyap** [comment]
So its possible. Thanks

**Comment by kaushalyap** [comment]
@mikepenz `DragDropUtil.onMove()` not still compatible since it cannot accept a `ModelAdapter`

**Comment by mikepenz** [comment]
Look at its code: https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-utils/src/main/java/com/mikepenz/fastadapter/utils/DragDropUtil.kt it is super straight forward. and you might simply want to bring it into your project for the time being. will check to change the accepted adapter type to be ModelAdapter in the future

**Comment by AllanWang** [comment]
@mikepenz about to submit a PR. It's a small change anyways

**Comment by kaushalyap** [comment]
Yes I am using Drag util, but how could I change the accepted parameter type?

**Comment by mikepenz** [comment]
@kaushalyap you copy it to your project and make it accept the IItemAdapter until a new release is available with the change from @AllanWang

**Comment by kaushalyap** [comment]
Okay thanks!
