### ISSUE TITLE
Select extension didn't work with data that gotten from API

### ISSUE THREAD

**Issue by bkhezry** [mikepenz/FastAdapter#818]
## Selecting items didn't work with data that gotten from API

- I use earthquake data from https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson
`retrofit` get data from the server and map it with Feature class

```kotlin
data class Feature(
    @SerializedName("type")
    val typeString: String,
    @SerializedName("properties")
    val properties: Properties,
    @SerializedName("geometry")
    val geometry: Geometry,
    @SerializedName("id")
    val id: String
)
```
When extend it from `AbstractItem` & set data to the `itemAdapter` data will be showing in the recycler view but select extention didn't work with this data and listener didn't trigger.

```kotlin
val selectExtension = fastAdapter.getSelectExtension()
        selectExtension.apply {
            isSelectable = true
            multiSelect = false
            selectionListener = object : ISelectionListener<Feature> {
                override fun onSelectionChanged(item: Feature?, selected: Boolean) {
                    Toast.makeText(this@MainActivity, "Hi", Toast.LENGTH_LONG).show()
                    Log.i(
                        "FastAdapter",
                        "SelectedCount: " + selectExtension.selections.size + " ItemsCount: " + selectExtension.selectedItems.size
                    )
                }
            }
        }
```
I try to create two instances manualy from `Featrue` class & set them to `itemAdapter`.
select extention work file.
I think there is a problem with data that provide from API. 

## Details
- Used library version 4.1.0-b02
- Used support library version 1.0.2
- Used gradle build tools version 3.5.0
- Used tooling / Android Studio version 3.5.0

**Comment by mikepenz** [comment]
@bkhezry beside it not fireing do you see if the items get selected nevertheless?

**Comment by bkhezry** [comment]
@mikepenz No. 
I add this code for detecting selected item but the color of items didn't change.

``` kotlin
val color = UIUtils.getThemeColor(ctx, R.attr.colorPrimary)
holder.view.clearAnimation()
holder.view.foreground = FastAdapterUIUtils.getSelectablePressedBackground(ctx, FastAdapterUIUtils.adjustAlpha(color, 100), 50, true)


```

**Comment by mikepenz** [comment]
@bkhezry could you please provide a sample app to showcase this problem? 

There shouldn't be a reason it won't work as adding items from an API is the same as adding them manually programmatically. just ensure the stuff is added on the UI thread

**Comment by bkhezry** [comment]
@mikepenz Sorry, I forgot your reply.
Please check this demo
https://github.com/bkhezry/FastAdapterTest

**Comment by mikepenz** [comment]
@bkhezry sorry for the late answer. projects were super stressful. 

So I had a look, and the answer is actually really simple. 

So your model and date you retrieve and parse from the API response is also your item you display in the recyclerView. 

The problem though is the data returned from the API has no field `isSelectable` as such this property is `false`. 

for your usecase I highly recommend to actually make use of the `ModelAdapter` e.g. diffentiating between your model and your items which reflect your `view` in the RV.

This is showcased here for example: 
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/ModelItemActivity.kt#L43

See how we have an `IconModel` which will be transformed to a `ModelIconItem`. 

This will ensure the parsing will not conflict with the items. 

-------------------

An alternative ugly non suggested alternative would be to just make the elements selectable :D


--------------------

side note. It seems your items are not having unique identifiers

**Comment by bkhezry** [comment]
Yes. The other problem was items not having unique identifiers that I fix it before.
Thanks for your help @mikepenz :-)

**Comment by mikepenz** [comment]
No problem. Sorry again for the late answer
