### ISSUE TITLE
How drag from one RecyclerView to another RecyclerView?

### ISSUE THREAD

**Issue by isMeiying** [mikepenz/FastAdapter#821]
There are two RecyclerViews on the activity, and the item in the first RecyclerView can be dragged to the second RecyclerView.

**Comment by mikepenz** [comment]
@isMeiying this is nothing regarding this library, or which an adapter would have to specifically support. 

there are tutorials in the web how to achieve this. 

basically you will need to remove the item from one recyclerView's adapter and add it to the adapter of the other

**Comment by isMeiying** [comment]
> @isMeiying this is nothing regarding this library, or which an adapter would have to specifically support.
> 
> there are tutorials in the web how to achieve this.
> 
> basically you will need to remove the item from one recyclerView's adapter and add it to the adapter of the other

Will FastAdapter join this feature in the future?

**Comment by AllanWang** [comment]
There are many ways of doing this, and I think what Mike is saying is that it isn't dependent on FastAdapter implementations. You are dealing with just one viewholder at a time, so the solution would be applicable beyond just FastAdapter users. It wouldn't make sense to include that in this library

**Comment by isMeiying** [comment]
> There are many ways of doing this, and I think what Mike is saying is that it isn't dependent on FastAdapter implementations. You are dealing with just one viewholder at a time, so the solution would be applicable beyond just FastAdapter users. It wouldn't make sense to include that in this library

I think it can be an enhanced extension that will help me quickly create such an adapter.

`like this`
![IMG_4355](https://user-images.githubusercontent.com/13428030/64902495-56dc3f00-d6da-11e9-8075-56db4789e338.GIF)

**Comment by mikepenz** [comment]
You can find some help regarding this topic in the internet :) https://stackoverflow.com/questions/29690522/drag-and-drop-between-two-recyclerview 

As noted it is not a thing the library is supposed to support
