### ISSUE TITLE
How to Passing Value from activity/fragment to FastAdapter<...> ?

### ISSUE THREAD

**Issue by hadilo** [mikepenz/FastAdapter#823]
i want to passing value from activity / fragment to fastadapter. how the code ? any example ?
i used v 3.3.1

**Comment by mikepenz** [comment]
I don't believe this question is related to this lib. 

You pass a value to the adapter, as you would pass a value to any other adapter, or anything else :D

**Comment by mikepenz** [comment]
Also you can always have a look at the sample app :D
