### ISSUE TITLE
SimpleItemList sample: selected item is sometimes shown as not selected

### ISSUE THREAD

**Issue by BerdiVad** [mikepenz/FastAdapter#824]
In the SimpleItemList of the sample application, when I click on the first item its background becomes red. If after that I click on the second item, the first one is deselected and the second one is selected instead and becomes red. This is the desired behaviour.
But if I click **very fast** on the first item and then on the second item and then again on the first one, non of the items are colored in red. But if I scroll the screen down a little and then up to the beggining, the first item is selected.

**Comment by mikepenz** [comment]
that is due to the animation which is run by the system. The system manages the selection states. you might want to disable the animations for selection state changes and then it ain't occur. 

(at least I am 95% confident that this is the case here :D)
