### ISSUE TITLE
onScrollListener onLoadMore gets triggered automatically without scrolling

### ISSUE THREAD

**Issue by NotNotMarshall** [mikepenz/FastAdapter#826]
The onScrollListenner triggers automatically at the first loading of data into the list.
So the program is busy loading the data from the server into the adapter but the listener keeps triggering load more whenever each new item gets added.
Please don't ask for code

**Comment by NotNotMarshall** [comment]
See!

**Comment by NotNotMarshall** [comment]
![Screen](https://user-images.githubusercontent.com/23288867/67300765-18455b80-f4b4-11e9-9e25-c68988fbfc57.png)

**Comment by NotNotMarshall** [comment]
This pattern of infinite page 1 goes until the end!

**Comment by mikepenz** [comment]
You might want to play around with the new extension which adds support for the `PagedListAdapter` 

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/PagedActivity.kt

**Comment by NotNotMarshall** [comment]
> You might want to play around with the new extension which adds support for the `PagedListAdapter`
> 
> https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/PagedActivity.kt

Can you make it more simple? 
Provide an example... this is the second day I'm wasting on your library.

**Comment by NotNotMarshall** [comment]
I am not using PagedListAdapter at all

**Comment by Morteza-Rastgoo** [comment]
Is there any way to fix this without refactoring current code to PagedActivity.kt code?

**Comment by NotNotMarshall** [comment]
> Is there any way to fix this without refactoring current code to PagedActivity.kt code?
> I just want to fix this with `EndlessRecyclerOnScrollListener`

All you need is love, and don't forget to star this library.
