### ISSUE TITLE
Multi Adapter problem

### ISSUE THREAD

**Issue by NotNotMarshall** [mikepenz/FastAdapter#828]
![image](https://user-images.githubusercontent.com/23288867/67328541-d8dc3680-f4d6-11e9-98ad-69680687a79f.png)

What is the problem with this?

**Comment by mikepenz** [comment]
A `FastItemAdapter` is a `FastAdapter` + a `ItemAdapter`

A `FastAdapter` can only be constructed with `ItemAdapter`s (ModelAdapter). 

You are trying to construct a `FastAdapter` with a `FastAdapter` which it does not like :D
