### ISSUE TITLE
Drag & Drop support with multiple adapters

### ISSUE THREAD

**Issue by hannta** [mikepenz/FastAdapter#829]
I have FastAdapter with four different adapters in it. I want to allow item drag & drop only in one of the adapters. Items in the adapters implements `IDraggable`.

I try to use `SimpleDragCallback`, but the problem is, how I should get the correct adapter in `itemTouchOnMove`. The positions there are FastAdapter / RV global positions, not for that exact adapter.

Or should I try to calculate how many items there is in my other adapters and build some kind of offset etc?

**Comment by mikepenz** [comment]
The `FastAdapter` provided you with a method to retrieve the adapter based on the position:

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt#L564-L572

**Comment by hannta** [comment]
Thanks, I completely missed that one.
