### ISSUE TITLE
Wrong behaviour of isOnlyOneExpandedItem

### ISSUE THREAD

**Issue by zTrap** [mikepenz/FastAdapter#830]
- **Predefines:**
We have list of expandable items, with nesting level more than one and `isOnlyOneExpandedItem` is on. We expand one item and trying expand nested one.

 - **Expected:**
Nested item expands as usual, parent item is not collapsed

 - **Actual:**
Nested item expands and then parent item collapses with nested one

This issue can be reproduced in sample app

## Details

- [x] Used library version **4.1.0**

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Hey @zTrap where in the sample app do you see the problem. do you by coincidence know when this was introduced?
