### ISSUE TITLE
Crash on scroll in absence of Internet Connectivity (With Jetpack Paging) 

### ISSUE THREAD

**Issue by mehul4795** [mikepenz/FastAdapter#831]
**Issue**

I have integrated the Jetpack Paging Support by following the code used in the PagedActivity class of the sample app. I am fetching a list from an API and paging is working fine but while scrolling if the Internet Connectivity goes down, the app crashes.

**Expected Result**

If the Internet Connectivity goes down, I need to show a "Retry" button so that the app can resume the fetch if the connection is re-established when the user presses the "Retry" button. 

**Version of FastAdapter**: 4.1.0

I am not sure if FastAdapter should handle this but any help will be appreciated.

Thanks!

**Comment by mikepenz** [comment]
How does the crash look like? 

Can you catch this case? and add a retry list item?

**Comment by mehul4795** [comment]
I am getting the below exception.
`java.net.UnknownHostException: Unable to resolve host "www.googleapis.com": No address associated with hostname`

I am also attaching the Fragment and DataSource files in case it helps.
[Fragment.txt](https://github.com/mikepenz/FastAdapter/files/3824254/Fragment.txt)
[DataSource.txt](https://github.com/mikepenz/FastAdapter/files/3824255/DataSource.txt)

**Comment by mikepenz** [comment]
well but what is the crash crash. what is the stacktrace. making your application crash and fall apart?

**Comment by mehul4795** [comment]
Sorry, I am unable to get the stacktrace when the application crashes. If you want I can add you as a collaborator to the project?

**Comment by mikepenz** [comment]
No that is not necessary. 

In general I would say this is something on your side to handle and not related to this library. 

In case of the network failing you will have to then decide to put the error item into the drawer

**Comment by mehul4795** [comment]
Okay, no problem. I will look into it.
