### ISSUE TITLE
Setting a String identifier on AbstractItem

### ISSUE THREAD

**Issue by mikezliu** [mikepenz/FastAdapter#833]
AbstractItem requires that the identifier is a long. I'm using unique uid for my server side items, and converting them to a long may result in collisions.

Is there a way to specify a string identifier?

I'm currently converting the server side uuid to a long identifier by using hashCode of the string, but this can collide so it's not a great solution. I need to use identifier to avoid blinking issues when using FastAdapterDiffUtil

**Comment by mikezliu** [comment]
@mikepenz - I'm used to using DiffUtil with recycler views, and I don't think there is such a limitation there (the DiffUtil callback lets you compare two objects for equality however you want, and I can do a string comparison there - https://developer.android.com/reference/android/support/v17/leanback/widget/DiffCallback). Is the limitation you're referring to in RecyclerViews just for non DiffUtil usages? I'm not that familiar there so not sure which limitation you're referring to.

**Comment by mikepenz** [comment]
You are mixing up 2 different things. 

The diffUtil provides a way to detect differences of item in a very generic way. 
wheras the identifier is meant to be a unique id used to optimize various things like animations inside the RecyclerView

See: https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#setHasStableIds(boolean)
and:
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#getItemId(int)

**Comment by mikezliu** [comment]
@mikepenz - ah makes sense, thanks for the clarification
