### ISSUE TITLE
PagedModelAdapter.submitList doesn't accept null

### ISSUE THREAD

**Issue by DeweyReed** [mikepenz/FastAdapter#834]
## About this issue

https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-paged/src/main/java/com/mikepenz/fastadapter/paged/PagedModelAdapter.kt#L301

```Kotlin
    fun submitList(pagedList: PagedList<Model>) {
        itemList.submitList(pagedList)
    }
```

Currently, We can't pass `null` to `PagedModelAdapter.submitList` to clear the list. `itemList.submitList` accepts `null` so the parameter `pagedList` should also be nullable.

For now, since `itemList` is open, I use it directly to submit a `null`.

BTW, thanks for your amazing work!

## Checklist

- [√] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [√] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [√] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [√] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [√] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@DeweyReed thank you very much. I am glad it works for you. 

Will fix this in one of the upcoming updates
