### ISSUE TITLE
Move item in ItemAdapter implementation

### ISSUE THREAD

**Issue by gromiloff** [mikepenz/FastAdapter#84]
Hi,

I need implement some funcionality in adapter logic.

For example,  I have next items: A, B, C, D, E
By event,  need move item "D" to top position (D A B C E)
list change implementation is:
```java
list.remove("D")
list.add(0, "D")
```
So,  for current itemAdapter implementation I call
```java
ItemAdapter<Item> remove(int position)
ItemAdapter<Item> add(int position, Item... items)
```

By I see recycledView crash by notify notifyAdapterItemRemoved.

Does any around implementaion for my task ?

PS: collections swap is not work correct, I need move not swap.

**Comment by mikepenz** [comment]
Basically you need to do the following:

```java
        int preItemCount = getFastAdapter().getPreItemCount(fromPosition);
        Item item = mItems.get(fromPosition - preItemCount);
        mItems.remove(fromPosition - preItemCount);
        mItems.set(toPosition - preItemCount, item);
        getFastAdapter().notifyAdapterItemMoved(fromPosition, toPosition);
```

**Comment by gromiloff** [comment]
@mikepenz you commit incorrect code: not mItems.set, but mItems.add

list.set - method for update item in position, not insert.

So, please reopen task again.

**Comment by mikepenz** [comment]
@gromiloff omg you are completely right. :O It was just to late. sorry for the inconvenience.

**Comment by mikepenz** [comment]
changed this to v1.2.8 (the move works with the global position)
