### ISSUE TITLE
Mistakes in ModelAbstractExpandableItem class

### ISSUE THREAD

**Issue by zTrap** [mikepenz/FastAdapter#841]
`ModelAbstractExpandableItem` contains problems:
 - unused parameter `Parent`
   - can be used in `var parent: IParentItem<*>?` as wildcard type (redundant clarification IMHO)
   - can be removed as redundant
- unused parameter `SubItems`
   - can be used in `var subItems: MutableList<ISubItem<*>>` as wildcard type (redundant clarification IMHO)
   - can be removed as redundant
 - wrong behavior of `isSelectable` field
   - getter must be changed from `_subItems.isNotEmpty()` to `_subItems.isEmpty()` because expandable item must be selectable only if not contains sub-items
 - setter of `subItems` duplicate logic from `MutableSubItemList`
   - `_subItems` can be changed to `val`, clear and add new items from setter
   - `subItems` can be declared as `MutableSubItemList<ISubItem<*>>` and as `val`. Also add method for clear and fill from another collection to `MutableSubItemList` (best way IMHO)

Solutions of this problems makes some breaking changes and can be provided in 5.x version. I'll make PR with selected by you ways

**Comment by mikepenz** [comment]
where do you see an unused parameter `Parent` and `SubItems`? I would still prefer to depend on the generic type. to have type safety. unless I miss something here.

the `isSelectable` you are right. 

Regarding the subItems those were as far as I remember necessary choices, and I highly recommend not to change any to those.

**Comment by zTrap** [comment]
> where do you see an unused parameter Parent and SubItems?

`Parent` and `SubItems` are used **only** in class declaration. No one field or function are not clarified by this parameters.

> Regarding the subItems...

In this logic items provided to setter never will be un-linked and will hold reference on parent, but this problem was solved in `MutableSubItemList`

**Comment by mikepenz** [comment]
Ok thanks. There's a branch `release/v5` would you perhaps like to open a PR against it?

**Comment by zTrap** [comment]
At the moment there is no such branch, but I will create it and open PR within a few hours

**Comment by mikepenz** [comment]
I am pretty sure there is :D I just created 2 PRs against it :)

**Comment by mikepenz** [comment]
And thank you very much :)

**Comment by mikepenz** [comment]
I am closing this ticket. Please just create a PR with the changes which we can bring into v5 :)

**Comment by mikepenz** [comment]
Thank you so much!
