### ISSUE TITLE
Endless Issue

### ISSUE THREAD

**Issue by gromiloff** [mikepenz/FastAdapter#85]
by example you set mVisibleItemCount to constant value (how much items would be displaied on screen),  but this is incorrect. On several screens count items would be different.

May be better get visible items from layout manager ?

**Comment by mikepenz** [comment]
@FabianTerhorst

**Comment by FabianTerhorst** [comment]
#89

**Comment by mikepenz** [comment]
@FabianTerhorst awesome ;)
