### ISSUE TITLE
How to use comparator with fastadapter 4.1.1 ?

### ISSUE THREAD

**Issue by Firsto** [mikepenz/FastAdapter#850]
**itemList.withComparator** is not working now

**Comment by mikepenz** [comment]
Please see the `SortActivity` sample. 

The default list implementation does no longer come with that feature, but the `CompareableItemList` does.

https://github.com/mikepenz/FastAdapter/blob/b716ba353855ed8f2ad9cb8d3ee43637c33236ad/app/src/main/java/com/mikepenz/fastadapter/app/SortActivity.kt
