### ISSUE TITLE
App crashes while sorting raising this error 

### ISSUE THREAD

**Issue by Saransh0905** [mikepenz/FastAdapter#852]
I am trying to sort my list of attendees using this piece of code-
((ComparableItemListImpl <Attendee>)fastItemAdapter.getItemList())
                                           .withComparator((Attendee a1, Attendee a2)->a1.getFirstName()
                                                                                        .compareTo(a2.getFirstName()), true);

I am getting this error-
java.lang.ClassCastException: com.mikepenz.fastadapter.utils.DefaultItemListImpl cannot be cast to com.mikepenz.fastadapter.utils.ComparableItemListImpl
at com.eventyay.organizer.core.attendee.list.AttendeesFragment.sortAttendees(AttendeesFragment.java:159)
Can someone help me out

**Comment by mikepenz** [comment]
@Saransh0905 you are trying to cast a normal `DefaultItemListImpl` to a `CompareableItemListImpl` which is not possible. 

If you want to use a comparable list please see the `SortActivity` in the sample.

```
itemListImpl = ComparableItemListImpl(comparator) // create the list with the comparator to use
itemAdapter = ItemAdapter(itemListImpl) // construct the ItemAdapter / ModelAdapter with the itemList you want to use
fastAdapter = FastAdapter.with(itemAdapter) // create the fastAdapter with the itemAdapter / ModelAdapter you constructed
```
