### ISSUE TITLE
Create dynamic numbers of textviews for each row

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/FastAdapter#857]
I have a layout with one textview, this is easy.

and i need to create as many "textviews" in runtime, as number in the variable **mNumberOfViews**

How ? 

can you tell me an easy example of this ?

that does not affect performance and that recycling works well ?

```
public class ArticulosRelItem extends AbstractItem<ArticulosRelItem, ArticulosRelItem.ViewHolder> {

    public String mName;
    public int mNumberOfViews;

    @Override
    public int getType() {
        return R.id.fastadapter_artrel_item_id;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.listaartrel;
    }

    @Override
    public void bindView(final ViewHolder viewHolder, List<Object> payloads) {
        super.bindView(viewHolder, payloads);

        viewHolder.lblName.setText(mName);

        for (int i = 0; i < mNumberOfViews; i++) {
                TextView text = new TextView(this);
                text.setText("text " + i);
                xxxxxxxxxxxx.addView(text); // here is the problem i dont know how
        }
    }

    @Override
    public void unbindView(ViewHolder holder) {
        super.unbindView(holder);
        holder.lblName.setText(null);
    }

    @NonNull
    @Override
    public ViewHolder getViewHolder(View v) {
        return new ViewHolder(v);
    }

    public static class ViewHolder extends RecyclerView.ViewHolder {
        protected View view;

        public TextView lblName;

        public ViewHolder(View view) {
            super(view);
            this.view = view;
            lblName= itemView.findViewById(R.id.lblName);
        }
    }
}
```

I use the **v3.3.1 (Java && AndroidX)** version of the library

Thanks

**Comment by mikepenz** [comment]
The number of textViews you need are they any number? or is there a fixed set of combinations? 
What do you display in those textViews?

**Comment by mikepenz** [comment]
This issue is btw. not related to the FastAdapter, thus closing. 

I would still love to assist you with your question if you provide a few more details. 

As there may be multiple more efficient approaches to this problem.

**Comment by seba123neo** [comment]
> 
> 
> The number of textViews you need are they any number? or is there a fixed set of combinations?
> What do you display in those textViews?

I have a HashMap like this...the number is 1 to N....

```
HashMap<String, Integer> arrMap =new HashMap<>();
arrMap.put("Row 1", 2);
arrMap.put("Row 2", 1);
arrMap.put("Row 3", 5);
arrMap.put("Row N", 1 to N);
```
Result...

![example](https://user-images.githubusercontent.com/9873666/71829040-7977d680-3082-11ea-82fd-7020f89ee382.png)

**Comment by mikepenz** [comment]
hmmm in general I would suggest to not create views every time it is different, but it seems you don't have the choice. 

you might be able to have a static amount of views in there (with visibility gone) and if the items exceed you add more which you remove again when it is unbound.
