### ISSUE TITLE
Modify item on runtime

### ISSUE THREAD

**Issue by eakteam** [mikepenz/FastAdapter#862]
I am having some troubles, and the adapter is not displaying new data for each item.
E.g : 

1) Add item (title, icon, icon) to itemAdapter (30 items)
`itemAdapter?.add(SampleItem("title"))`

2) Get all items from adapter : 
```
(0 until (fastadapter?.itemCount!!)).forEach { it ->
                val item = itemAdapter?.getAdapterItem(it)
}
```

3) Modify e.g icon from Visibility.GONE to Visibility.VISIBLE inside above forEach loop
```
item?.imageView?.visibility = View.VISIBLE
item?.imageView?.drawable?.let { it1 -> DrawableCompat.setTint(it1, ContextCompat.getColor(context!!, R.color.md_green)) }

```
4) Call `fastadapter?.notifyItemChanged(it)`

But the items are not displaying correctly, and when scroll through items and go back again on the top the adapter is showing default item view without new icon in that case 

**How to achieve that in correct way ? Or it is a bug ?**

This is the item class : 

```
class SampleItem internal constructor(internal var title: String) : AbstractItem<SampleItem.ViewHolder>() {

        override val type: Int
            get() = 0

        override val layoutRes: Int
            get() = R.layout.geoping_lista

        internal var imageView: ImageView? = null
        internal var indicatorView: AVLoadingIndicatorView? = null
        
        override fun getViewHolder(v: View): ViewHolder {
            return ViewHolder(v)
        }

        inner class ViewHolder(view: View) : FastAdapter.ViewHolder<SampleItem>(view) {
            private var indicatorLoading: AVLoadingIndicatorView = view.findViewById(R.id.avi)
            private var imageView: ImageView = view.findViewById(R.id.image2)

            override fun bindView(item: SampleItem, payloads: MutableList<Any>) {
                item.indicatorView = indicatorLoading
                item.imageView = imageView
            }

            override fun unbindView(item: SampleItem) {
                
            }
        }
    }
```

**Please Note :** 

After calling `fastadapter?.notifyItemChanged(it)` in step 4, sometimes the icon is showing in some items, sometimes not, sometimes shows the icon but not changing the color(see step 3) and sometimes when showing but scrolling to the end and top again it shows default view like in step 1 when adding to the adapter....

**Comment by mikepenz** [comment]
@eakteam your item implementation seems wrong. 

Your item itself should have no reference to the views. 

The `ViewHolder` is the only one supposed to have the reference. 

Inside the `bindView` method you should actually use the view from the viewHolder and update it with the data from your `item`

**Comment by eakteam** [comment]
@mikepenz yes i changed the logic and it works, but just to ask why we cannot reference the specific views from item itself when the view's ids is never changed and only need to change their properties ?

**Comment by mikepenz** [comment]
That's due to the way recycler view works.

Basically it will reuse the same views when you scroll. Only updating the information when binding. 

So you have let's say for example 1000 items in your list but just 10 view holders which are always reused while scrolling. 

I'd highly recommend that you checkout the details and the internals it's really interesting.

**Comment by eakteam** [comment]
@mikepenz thanks.
