### ISSUE TITLE
StickyHeader HeaderClickListener with Fastadapter 3.3.1

### ISSUE THREAD

**Issue by ocsike** [mikepenz/FastAdapter#865]
Hi,

In my project I upgraded my Fastadapter 3.2.7  to 3.3.1 and android to androidx.
I used this code for handle header onclick event:
```
StickyRecyclerHeadersTouchListener touchListener =        new StickyRecyclerHeadersTouchListener(rv, decoration);
        touchListener.setOnHeaderClickListener(
                new StickyRecyclerHeadersTouchListener.OnHeaderClickListener() {
                    @Override
                    public void onHeaderClick(View header, int position, long headerId) {
                
                        Toast.makeText(GroupListActivity.this, "Header position: " + position + ", id: " + headerId,
                                Toast.LENGTH_SHORT).show();
                    }
                });

rv.addOnItemTouchListener(touchListener);
```

It works with older Fastadapter, but with the newer one does not work.

**Comment by mikepenz** [comment]
@ocsike what does not work, could you please be a bit more specific?

**Comment by ocsike** [comment]
So, the stickyheader is showing as needed. I add a clicklistener for it, because I'd like to edit header name (header id not changed)  or delete the header  in a dialog, but  the dialog not showing nor the toast. The event not called. 
![dlg](https://user-images.githubusercontent.com/13695075/73641460-54ba5300-4670-11ea-94d0-dec0e2a12b18.jpg)

**Comment by mikepenz** [comment]
Not sure. perhaps an issue with the sticky header library? this is not really a part in this library. 

Otherwise can you try to modify the sample to reproduce the issue? maybe I could have a look

**Comment by mikepenz** [comment]
Please report back if this is still relevant. Please simply reopen for that case :) 

will close for the time being

**Comment by ocsike** [comment]
Hi,
Sorry for late, never mind.  Instead of StickyHeader I use a simple item and if need change the view for it.
Thank you.
