### ISSUE TITLE
Drawables with ratio different than 1:1 (swipe)

### ISSUE THREAD

**Issue by comradewalker** [mikepenz/FastAdapter#866]
https://github.com/mikepenz/FastAdapter/blob/494df3d7aac31e5d34836b77a5ac8adb1ba4da1b/library-extensions-swipe/src/main/java/com/mikepenz/fastadapter/swipe/SimpleSwipeCallback.kt#L125

this line should be:

`val intrinsicHeight = drawable.intrinsicHeight `

otherwise canvas drawing would be stretched for lets say drawables with ratio 3:1.

**Comment by mikepenz** [comment]
Thank you so much for the report. May you open a PR to fix this?
