### ISSUE TITLE
Some problems with V.5.0.0-a06

### ISSUE THREAD

**Issue by eakteam** [mikepenz/FastAdapter#870]
In some use cases with new implementations i'm unable to access public variables in the main class (Fragment, Activity)

**Before migration :** 

```
class ip_lookup : Fragment() {
lateinit var ip_lookup_log: StringBuilder

private inner class SampleItem internal constructor(internal var titulli: String, internal var sekuenca: String) : AbstractItem<SampleItem.ViewHolder>() {

        init {
            shkruaj_log()
        }

        private fun shkruaj_log() {
            ip_lookup_log.append(titulli).append(" : ").append(sekuenca).append("\n")
        }

        override val type: Int
            get() = 0

        override val layoutRes: Int
            get() = R.layout.lista_titull_pershkrim

        //The logic to bind your data to the view
        override fun bindView(holder: ViewHolder, payloads: MutableList<Any>) {
            //call super so the selection is already handled for you
            super.bindView(holder, payloads)
            //bind our data
            //set the text for the name
            holder.titulli.text = titulli
            holder.sekuenca.text = sekuenca

            //set the text for the description or hide
        }

        //reset the view here (this is an optional method, but recommended)
        override fun unbindView(holder: ViewHolder) {
            super.unbindView(holder)
            holder.titulli.text = null
            holder.sekuenca.text = null
        }

        //Init the viewHolder for this Item
        override fun getViewHolder(v: View): ViewHolder {
            return ViewHolder(v)
        }

        //The viewHolder used for this item. This viewHolder is always reused by the RecyclerView so scrolling is blazing fast
        internal inner class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
            var titulli: TextView = view.findViewById(R.id.titulli)
            var sekuenca: TextView = view.findViewById(R.id.txt1)
        }
    }
}
```

**After migrated the Item like this below :** 

```
class ip_lookup : Fragment() {
lateinit var ip_lookup_log: StringBuilder

inner class SampleItem1 constructor(var titulli: String,var sekuenca: String) : BaseItem<SampleItem1.ViewHolder>() {

        init {
            shkruaj_log()
        }

        private fun shkruaj_log() {
            ip_lookup_log.append(titulli).append(" : ").append(sekuenca).append("\n") // the problem !
        }

        override val type: Int
            get() = 0

        override val factory: IItemVHFactory<ViewHolder> = SampleItem1Factory

        override fun unbindView(holder: ViewHolder) {
            holder.titulli.text = null
            holder.sekuenca.text = null
        }

        inner class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
            var titulli: TextView = view.findViewById(R.id.titulli)
            var sekuenca: TextView = view.findViewById(R.id.txt1)
        }
    }

    object SampleItem1Factory: BaseItemFactory<SampleItem1.ViewHolder>() {
        override val type: Int
            get() = 0

        override val layoutRes: Int
            get() = R.layout.lista_titull_pershkrim

        override fun getViewHolder(v: View): SampleItem1.ViewHolder {
            return SampleItem1.ViewHolder(v) // ISSUE HERE
        }
    }
}
```

Can't reference objects `(ip_lookup_log)` of main class (Fragment/Activity) from SampleItem1 class, so the SampleItem1 class should be `inner` in my case, but after that, cannot reference it from `SampleItem1Factory` object ! :  It shows following error : 

`Contructor of inner class ViewHolder can be called only with receiver of containing class`

Hope to understand what i mean :) :)

**Comment by mikepenz** [comment]
That's because you can not access an `inner class` from an outer class. I suppose if you would make the factory itself also an inner class that it would be possible again. 

That being said. You are not required to refactor your item to use a own factory to create the `ViewHolder` you can still use a single item for everything instead. it may just be a better separation of concerns.

**Comment by eakteam** [comment]
@mikepenz, thanks for your response, but can you please help by providing an example how to achieve the changes (without getting "deprecation warning") in my case ?

For instance you can see how it was before in the first comment and refering to it, please help by giving an example code for new changes....

This is because want to be sure that no breaking changes will happen sooner again in next versions if it is possible, thanks !

**Comment by mikepenz** [comment]
You solution is in theory fine. Just make sure you define the proper type for your items. 
Also be aware that this is still be in alpha and we may need to make a few adjustments to make this the best and most flexible API as needed :) 

For now I would really suggest you may still stuck with the old `AbstractItem` until the final API is more stabilized. 

I highly appreciate the early tries though and all feedback is highly welcome to improve the API to be as great to use as possible. 


Btw. what is the main reason you want all you classes here to be `inner` classes?

**Comment by eakteam** [comment]
@mikepenz , thanks for the response, i will wait to be more stable.

The reasons why all the Classes need to be inner is because they modify some global variables of the main Class(in this case the fragment which FastadAdapter is used), and this variable is also accessed by it's main activity (for some real-time purposes).

There are other ways to do it, but after analyzing the performance, decided to use this logic because is not adding much code overhead by the compiler, since directly accessing variables between Fragment<->Activity without using `Broadcast Receivers`, `Streams` or other helper methods

**Comment by mikepenz** [comment]
Independent of this. the issue you saw is not a problem of the FastAdapter itself then, but more a requirement / limitation of how inner classes are designed and work
