### ISSUE TITLE
Shared interface between BaseItem and Factory

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#871]
I see with 5.0.0 that there is separation between the base item and the factory class. Just looking at the release changelog, I see that the `type` value is used in both classes. As far as I'm aware, this either should not exist in factory, since it's associated per item type and not per layout type, or it should only be defined once. In the case that the factory does share methods/values used in items, you can instead make the item take the factory in its constructor, and delegate a common interface to the factory.

For example:

https://github.com/AllanWang/KAU/blob/cfac5f0db6527aace725de14f07b19ba85b5e07e/sample/src/main/kotlin/ca/allanwang/kau/sample/PermissionCheckbox.kt#L62-L109

Where both classes implement `BindingLayout`

**Comment by mikepenz** [comment]
@AllanWang the main idea was to do this for the case of the paged list whereas we do not when filling which items there may all pop up. and in that case we won't be able to have an item instance to generate the view for. 

maybe we need allow for the factory cache to be a map with the `type` as key and then the factory as value?

I really want to ensure we do not have to create a item instance just for being able to construct the viewholder

**Comment by AllanWang** [comment]
I guess my question is, why do factories have types? Factories seem associated to layouts. If the type is necessary because you imagine that different factories may have the same layout file but different view holders, then why define the type again in items? Why not rely on `factory.type`?

**Comment by mikepenz** [comment]
Hmmm I suppose the main reason was due to the full disconnect between factory and item. and so I could match them together. at least for the factory cache. but I suppose it is better to remove it from the factory and only have it in the item.

**Comment by mikepenz** [comment]
removed the type from the factory
