### ISSUE TITLE
ViewBinding suggestions

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/FastAdapter#872]
With 5.0.0, I'm happy to see better support for ViewBinding. I did make my own implementation before, and I have a few suggestions for the new lib.

My version for reference: https://github.com/AllanWang/KAU/blob/5.2.0/fastadapter-viewbinding/src/main/kotlin/ca/allanwang/fastadapter/viewbinding/BindingItem.kt

1. Creating the binding should take in the parent. Inflating with just the layout inflater will != inflating with `(layoutInflater, parent, false)`, as some margin information depends on the parent.
2. In general, I don't see a reason to have separate viewholders along with separate view bindings. The purpose of the viewholder is to keep some references to sub views, and that is exactly what a view binding is. This means that you can have all view binding items use a single view holder, which is hidden from the end user. This suggestion is more debatable as there are some limitations, but depending on most people's use case, this may simplify their code. One problem is that event hooks seem to depend on viewholder classes, and having a single viewholder means that instance checks won't be possible. I get around this by continuing to supply the layout res, and using that to check if two viewholders contain the same binding.

If #2 isn't the goal, I do wonder what the purpose of this module is. What is being abstracted? The user still has to make a view group. Generating the view is "abstracted" in that the user returns `binding` rather than `binding.root`. There are also parts in the class, such as enforcing `isSelected` during `onBind`, and calling `bindView` during `generateView`. Are these problems specific with `viewBinding`? I would expect the same problem to occur with any custom view.

Lastly, why doesn't `AbstractBindingItem` extend `BaseItem`? I haven't looked too deeply at the code yet, but to me viewbinding support is an extension of the existing model, and not a separate implementation

**Comment by mikepenz** [comment]
@AllanWang I will answer the earlier parts at a later point. 

regarding `BaseItem` vs `AbstractItem` I have not yet found a proper name, couldn't make up a proper name to describe the difference. I would still love to offer the user the possibility to have a item class with everything together. but also the option to break apart `item`, `viewHolderFactory` and `model`

**Comment by mikepenz** [comment]
If you have any suggestions on how to rename `AbstractItem` vs `BaseItem` I would really appreciate it. not sure if my english skills block me of thinking for a great naming for these.

`BaseItem`: Split apart in item and factory
`AbstractItem`: Combines both (right now I thought of deprecating it, but not sure if this is really the way to move forward)

-------

The binding was added already in the latest release. https://github.com/mikepenz/FastAdapter/pull/869/files#diff-7fd7053b36ad26bd516f1ca44f2281f8R108 this is not on dev yet though


The idea was actually to provide an as flexible approach as possible. especially for cases where a view includes sub views. which will require their own viewBinding to be read in again. doing this in a generic fashion may cause problems, I think. 


I would love though to add a more generic implementation for the outlined topic you mentioned. 
1 ViewBinding == 1 ViewHolder. 
Having the most simple usecase covered in a generic way would make absolute sense and this still is the goal after all in the dependency.

**Comment by AllanWang** [comment]
I'm not really concerned about the naming of the classes (haven't looked into it too much). I was just wondering why the viewbinding item implemented the iitem interface from scratch, vs extending from the existing item. A lot of the default methods do not relate to viewbinding.

If your viewbinding contains other viewbindings, it seems like that means items are added programmatically. That is definitely a use case, but if the new module serves only to help the parent viewbinding, it seems like it really only addresses the `getView` function, and may end up with more boiler plate (viewbinding generics) just to replace returning a view with returning the binding. People can also choose to hold references to other views through the parent view tags if they wish, so it may be a matter of preference as to whether you'll want to simplify custom views that can't be in the parent viewbinder vs making the user create a new viewholder for every item.

**Comment by mikepenz** [comment]
You are absolutely right, I had totally overlooked the fact that the item itself is not needed anymore due to the factory. which abstracts the viewholder creation part away. 

https://github.com/mikepenz/FastAdapter/pull/869/commits/7c854725243f662c7bf92fa2c86d993cbd5329e7

**Comment by mikepenz** [comment]
The topic regarding the hooks depending on the `VH`. This is just for the default convenience provided methods. 

practically you can define other hooks which will hook on via the item, by making use of the tag. 

![image](https://user-images.githubusercontent.com/1476232/75054029-918ca380-54d2-11ea-98c2-f215fe820135.png)
