### ISSUE TITLE
How to use 1 FastAdapter with 2 different ItemAdapter 

### ISSUE THREAD

**Issue by Raffaa** [mikepenz/FastAdapter#875]
## About this issue
Hi, I've been tring to use two different item adapter with the same fast adapter. The two item adapter have nothing in common (so they don't inherit one from the other). The fast adapter is wrapped inside a StickyHeaderAdapter which gives me the error _Item2 cannot be cast to Item1_ when tries to render the child which has different vh. The error occurs in the method _onBindViewHolder(holder, position, List<Object_>_payloads)_ in the StickyHeader class.

Here is some snippet:

StickyHeader
```java
public class ChartStickyHeaderAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> implements StickyRecyclerHeadersAdapter {

    private FastAdapter<IItem<? extends RecyclerView.ViewHolder>>adpt;

    public ChartStickyHeaderAdapter wrap(FastAdapter<IItem<? extends RecyclerView.ViewHolder>>fastAdapter) {
        this.adpt = fastAdapter;

        return this;
    }

    [. . .]

    @Override
    public void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, int position) {
        this.adpt.onBindViewHolder(holder, position);
    }

    @Override
    public void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, int position, @NonNull List<Object> payloads) {
        this.adpt.onBindViewHolder(holder, position, payloads);
    }

	[. . .]

    @Override
    public int getItemViewType(int position) {
        return adpt.getItemViewType(position);
    }

    @Override
    public long getItemId(int position) {
        return adpt.getItemId(position);
    }

}
```

Fragment
```java
public class MyFragment extends BaseFragment {

    private ItemAdapter<Item1> item1Adpt;
    private MyStickyHeaderAdapter stickyAdpt;
    private FastAdapter<IItem<?>> fastAdpt;
    private ItemAdapter<Item2> item2Adpt;
    [. . .]
    item1Adpt = new ItemAdapter<>();
    item2Adpt = new ItemAdapter<>();
    stickyAdpt = new ChartStickyHeaderAdapter();
    ArrayList<ItemAdapter> list = new ArrayList<>();
    list.add(item1Adpt);
    list.add(item2Adpt);
    chartFastAdpt = FastAdapter.with(list);
    [. . .]
    recyclerView.setAdapter(stickyAdpt.wrap(fastAdpt));
````
(Item1 and Item2 implement IItem<VH> and extend AbstractItem<VH>)
## Details
- [4.1.2 ] Used library version
- [timehop(StickyHeader) ] Other used libraries, potential conflicting libraries

## Checklist
I searched other issues, found  #644, #652 and #76 but unfortunately I wasn't able to solve my issue

**Comment by mikepenz** [comment]
The FastAdapter has to define the parent type, then you can have child item adapters. 
the sample showcases this :)

**Comment by Raffaa** [comment]
> The FastAdapter has to define the parent type, then you can have child item adapters.
> the sample showcases this :)

Yeah, I saw that, in fact I set FastAdapter type to IItem but same error happened.
Btw, thank for your reply, very very fast. :)

**Comment by mikepenz** [comment]
@Raffaa what is the error you see?

**Comment by Raffaa** [comment]
When the adapter try to render Item2 ViewHolder couse the Exception:  Item2 cannot be cast to Item1. The exception is fired at onBindViewHolder method implementation inside StickyHeader implementation. 
Maybe, later, I can create and share you a test repository to help undestand the error.

**Comment by Raffaa** [comment]
Here the repo -> https://github.com/Raffaa/TestFastAdapter2

Just build, and then scroll down in the app

**Comment by mikepenz** [comment]
The issue is that you are not using unique type ids. The type is used by the RecyclerView to tell which items is supposed to be used and thus has to be unique to ensure the correct things are used :). 

The best pattern is to specify a integer int resource per item which you use per item. 

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleImageItem.kt#L33

**Comment by Raffaa** [comment]
Ah, missed that.
Thank you, problem solved :)
