### ISSUE TITLE
FastAdapterDiffUtil.calculateDiff is re-ordering items towards top of scrollview

### ISSUE THREAD

**Issue by mikezliu** [mikepenz/FastAdapter#877]
When I'm using FastAdapterDiffUtil.calculateDiff and it results in items being re-ordered, it seems that the resulting recyclerview is scrolled all the way to the bottom of the scroll view. Is there any way to change this behavior so it prefers the existing scroll view's offset %? So if it's at 25% scrolled, it should prefer to stay at 25% scrolled after re-ordering rather than 100% scrolled.

I'm still trying to understand whether this is caused by the fast adapter diffutil or the underlying diffutil and how the behavior can be changed.

**Comment by mikepenz** [comment]
This is actually should be a behavior of the `RecyclerView` whereas it tries to stick with the item with the id currently shown. 

As far as I know this does not occur and happen in the sample app where we also have a sorting sample with the diff util

**Comment by mikezliu** [comment]
I tested it a bit more, and when re-sorting is done it does seem to stick with the current visible item. So when I reverse the sort from ASC to DESC, it ends up scrolling to the bottom of the list because the one at the top is now shown at the bottom.

I think it might be a better user experience to sticky at the current sort % of scrollview. For now I will probably make the recycler view manually scroll to the top every time I change the sort order to workaround this issue.

**Comment by mikepenz** [comment]
that's what I mentioned :D 

That is the behavior of the RV :) 

You may also read about it here: https://github.com/airbnb/epoxy/issues/224#issuecomment-305991898
