### ISSUE TITLE
Drag and drop using PagedModelAdapter and Paging Library

### ISSUE THREAD

**Issue by mikezliu** [mikepenz/FastAdapter#879]
It would be nice if there's an easy way to do this with FastAdapter. Currently PagedModelAdapter.move is unsupported (though it's unsupported with the paging library as well).

I am thinking of writing another layer in between that caches the changes during drag/drop, and flushes it to PagedModelAdapter once drag/drop is complete.

## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@mikezliu there are no plans on the side of this library to add another layer. as this may lead to lot more complexity which is hard to maintain. 

The available APIs and the flexibility of the library should allow you to adjust / build any functionality you may need in your project. 

if there's a clean way to support this directly via the paging library from google we may have that at some point, but currently this is not on the agenda. 

Thank you so much!
