### ISSUE TITLE
FastAdapter.recursive won't work in PagedModelAdapter's submit commit callback.

### ISSUE THREAD

**Issue by DeweyReed** [mikepenz/FastAdapter#881]
## About this issue

I'll use [the sample from demo](https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/PagedActivity.kt#L74):

` viewModel.demoEntitiesList.observe(this, Observer<PagedList<DemoEntity>> { t -> mItemAdapter.submitList(t!!) })
`

When I use it this way:

```Kotlin
viewModel.demoEntitiesList.observe(this, Observer<PagedList<DemoEntity>> { t ->
    mItemAdapter.submitList(t, Runnable {
        Log.i("test", "current count: ${mFastAdapter.itemCount}")
        mFastAdapter.recursive(
            object : AdapterPredicate<SimpleImageItem> {
                override fun apply(
                    lastParentAdapter: IAdapter<SimpleImageItem>,
                    lastParentPosition: Int,
                    item: SimpleImageItem,
                    position: Int
                ): Boolean {
                    Log.i("test", "This should be printed")
                    return false
                }
            },
            stopOnMatch = false
        )
    })
})
```

The second log never gets called because of [this change](https://github.com/mikepenz/FastAdapter/commit/878977d00ca3fe5c7e4154253a901936ba620a15). `peekAdapterItem` returns null and `PagedItemListImpl`'s `cache` is empty.

## Details
- [5.0.0] Used library version
- [1.1.0] Used support library version
- [29.0.3] Used gradle build tools version
- [3.6.2] Used tooling / Android Studio version
- [X] Other used libraries, potential conflicting libraries

## Checklist

- [√] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [√] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [√] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [√] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [√] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
The `PagedList` is kind of a special list as it does not support many features normal lists can do, as not all information is available and things will adjust on the fly

I think with paged list you also don't have sub items, so you can actually use the items directly. no need to use the recursive function in this case :)

**Comment by DeweyReed** [comment]
Thanks for your response. I'm now using `getItem` to loop all the items.

I'm not sure if I should close the issue so I'll you leave the mission to you :D

**Comment by mikepenz** [comment]
sounds valid. you only want the flat hierarchy. 

as mentioned the `PagedList` is kind of special as not all items are known at all times. so you may want to be a bit more careful when you do that to not start loading elements which are not yet available in you rlist.
