### ISSUE TITLE
RadioButtonSample doesn't work with filter

### ISSUE THREAD

**Issue by Grouen** [mikepenz/FastAdapter#882]
## About this issue

When I use RidioButtonSample logic in my app it works, but when i add filter i can select two radio buttons because selectExtension.selections can be empty when filter was applied.

## Details
- [5.0.0] Used library version
- [1.1.0] Used support library version
- [29.0.3] Used gradle build tools version
- [3.6.2] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [√] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [√] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [√] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [√] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [√] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by Grouen** [comment]
My solution: I pass itemFilter in RadioButtonClickEvent and execute this`  itemFilter?.selectedItems?.forEach {
                it.isSelected = false
            }`  in onClick 
Maybe you known better solution?

**Comment by mikepenz** [comment]
you solution sounds appropriate. 

the sample for radio buttons is just minimal and a showcase. the demo item is not compatible with filters and may require the changes as you mentioned them above :)
