### ISSUE TITLE
Why is call bindView & unbindView methods after click to item?

### ISSUE THREAD

**Issue by Z-13** [mikepenz/FastAdapter#887]
I've an expanded recycler. There're two item class(the parent and child).

When I click on a parent item then I catch breakpoint into `bindView` of my parent item and after expanded I catch it into `unbindView `of my parent item.

Because of this I see blink effect on this item(because I have a Glide and loading an icon and I clear `imageView` into `unbindView` method)

I don't know why after click on item it's happening? 
What if I don't want reload my icon, for example.

Thx!

**Comment by mikepenz** [comment]
@Z-13 could it be that you notify the adapter about a change in the item?

Or have a selected state which is done via an update of the item?

This is the behavior a RecyclerView / Adapter has when a notify occurs (if a notify has a payload then this can be worked around)

**Comment by Z-13** [comment]
@mikepenz I mean that when I tap on the item, I change him state to expanded or not expanded and sometimes need to change item's color or anything else. But, for example, the image which has been loaded into it I don't want change or reload.
How can do it?

p.s. understand that perhaps this question don't touch the lib, but I ran into this when use it. :)

**Comment by Z-13** [comment]
@mikepenz hm, maybe I see a blink effect due to the child item animation , which go to alpha channel from 0 to 100 and located on top the parent item and not under it.

My items animation: `rv.itemAnimator = SlideDownAlphaAnimator()`

And child item as if from above after click on a parent. The demo project FastAdapter has the same effect.
For example, [this lib](https://github.com/thoughtbot/expandable-recycler-view): doesn't have it.

May be U have any idea, how can fix it?
Thx!

**Comment by mikepenz** [comment]
If you for example use a `AlphaCrossFadeAnimator()` instead the effect will be a different one. 

Based on what I see from the link you sent me they use basically just a `AlphaInAnimator` which you could also use. 

The way expanding / collapsing works is by simply updating the adapter with the child items. and all the animating is done by the RV itself as it is meant to be :)
