### ISSUE TITLE
Collapse item when click on header

### ISSUE THREAD

**Issue by AbdoGamal31** [mikepenz/FastAdapter#892]
## About this issue

- Briefly describe the issue
- Hi thank you for your library i have question 
now i have sticky header A and below list of item and below these list i have text called "collapse expand" i want to collapse this list of items when click on " collapse expand " text with animation how i can do it 

## Details
- [ 5.0.1] Used library version
- [ 1.2.0-alpha03] Used support library version

**Comment by mikepenz** [comment]
Retrieve the `ExpandableExtension` from the adapteR:

```
fastItemAdapter.getExpandableExtension()
```
https://github.com/mikepenz/FastAdapter/blob/e0644e631d8c83adc27df5600d6c53a5e04d4f49/app/src/main/java/com/mikepenz/fastadapter/app/IconGridActivity.kt#L34

And then use it's methods to expand / collapse according to your needs

https://github.com/mikepenz/FastAdapter/blob/e0644e631d8c83adc27df5600d6c53a5e04d4f49/app/src/main/java/com/mikepenz/fastadapter/app/IconGridActivity.kt#L82

**Comment by mikepenz** [comment]
I hope this helped and resolved your question :)
