### ISSUE TITLE
notifyAdapterSubItemsChanged does not exists

### ISSUE THREAD

**Issue by hamraa** [mikepenz/FastAdapter#894]
## About this issue

The method `notifyAdapterSubItemsChanged`  does not exists in new versions? 
What is the alternatives for this functionality? 
Tnx

## Details
- [ 4.1.2 ] Used library version

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
It still exists. It was moved to the respective `ExpandableExtension`: https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.kt#L246

**Comment by hamraa** [comment]
Tnx for your support and this great library!

**Comment by mikepenz** [comment]
happy I could help
