### ISSUE TITLE
Nested List with Drag And Drop

### ISSUE THREAD

**Issue by aggarwalpulkit596** [mikepenz/FastAdapter#897]
Hey @mikepenz actually I want to implement something like attached below

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/29139786/83512008-2a2cb980-a4ed-11ea-9431-05d8a82d32e4.gif)

Any suggestion on how should I approach this

**Comment by mikepenz** [comment]
Please have a look at the sample app it showcases drag and drop functionality:

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SimpleItemListActivity.kt

combining items to groups is some very advanced functionality which will require work on your side. 

This actually goes further than what the adapters responsibilities are. As such also out of scope of this library. 

This library is only meant to provide an easier way to implement adapters and their items. 

You may have to experiment with a more complex setup:

ItemTypes:
SimpleItem (e.g. Item 1, Item 2, ...) 
GroupedItem (Combines item 1, item 2) 
PlaceHolderItem (level 0, level 1)

So if you drag and drop one item to a different location you may want to remove the item then from the list and add to the grouped item which then renders the combined set
For the placeholder you may need to experiment if you can inject a "PlaceHolder" into the respective locations as you need it. 


(side question the ui does not actually offer an ungroup anymore :D)

**Comment by mikepenz** [comment]
I hope you were able to resolve your matter. 

I think as of the libraries point of view things should be resolved
