### ISSUE TITLE
List position after removing item

### ISSUE THREAD

**Issue by ddz985** [mikepenz/FastAdapter#898]
Hi, I have a problem with FastAdapterDiffUtil and keeping the list position after deleting an item. I have a list of items and then I'm removing one of the items from this list and setting them again using `FastAdapterDiffUtil[modelAdapter] = list`. The problem is that the list scrolls to the top. I'm not able able to use the `remove` method from `ModelAdapter` because of the architecture which I'm using. I was trying to debug the `DiffResult` and it contains 1 element in mSnakes list so I guest diff is calculating correctly.  How should it be done correctly to keep the recycler view position?

**Comment by mikepenz** [comment]
@ddz985 I can not reproduce this problem. I have extended the list in the sample app to 100 entries and use diff util to order, and it will retain the position. 

This is actually something the `RecyclerView` manages and not the adapter (so it is out of scope of the library) 

Try to ensure the elements have all identifiers. other than that make sure you don't use any flags which may break this. also keep stableIds enabled on
