### ISSUE TITLE
text type face and layout direction was change

### ISSUE THREAD

**Issue by hossein114** [mikepenz/FastAdapter#899]
## About this issue

- Briefly describe the issue:
   When we update this lib from version 5.0.0 to 5.1.0, all text view of the whole app was changed typeface(font), and the direction of the layout was changed.

- How can the issue be reproduced / sample code:
   I change nothing in my code, just increase the lib version

## Details
- [5.1.0 ] Used library version
- [ 1.1.0] Used support library version(androidx.appcompat:appcompat)
- [4.0.0 ] Used Gradle build tools version
- [4.0 ] Used tooling / Android Studio version

**Comment by mikepenz** [comment]
There are no changes in the lib itself which can do this: https://github.com/mikepenz/FastAdapter/compare/v5.0.0...v5.1.0

I assume one of the jetpack libraries results in behavior change for you:
https://github.com/mikepenz/FastAdapter/compare/v5.0.0...v5.1.0#diff-c197962302397baf3a4cc36463dce5eaR18-R33


Perhaps appcompat? https://github.com/mikepenz/FastAdapter/blob/develop/library-core/build.gradle#L41-L43

**Comment by hossein114** [comment]
Yes its true, it's because of AppCompat dependency that you updated to version '1.2.0-rc01' in FastAdapter 5.1.0.
What we can do for this problem?

**Comment by mikepenz** [comment]
Can't see anything in their changelog which could describe it: https://developer.android.com/jetpack/androidx/releases/appcompat#version_120_2

regardless. you can overwrite the method and force the old version in your app if that's the cause. 

it's just a dependency of the FastAdapter and we try to keep in sync with latest releases.

**Comment by hossein114** [comment]
Ok, thanks
We use the old version until the stable version of appcompat will reach.
Best Regards.

**Comment by mikepenz** [comment]
You may want to figure out though what may causes your behavior. as 1.2.0-rc01 will most likely not change any big things until the stable release of it :D

**Comment by hossein114** [comment]
Yes, it's true, we must find a way of fixing it in our app.
Thanks a lot.

**Comment by hossein114** [comment]
For who has the same problem as us for the custom locale, we create an issue on the google issue tracker, and how to fix it:
**link**: https://issuetracker.google.com/issues/158502557
**response**: See [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:appcompat/appcompat/src/androidTest/java/androidx/appcompat/app/NightModeCustomAttachBaseContextActivity.java;l=34) and [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:appcompat/appcompat/src/androidTest/java/androidx/appcompat/app/NightModeCustomApplyOverrideConfigurationActivity.java;l=33) for examples on how to make your custom locale / language overrides work with the latest versions of AppCompat.

**Comment by mikepenz** [comment]
thanks for adding the information here :)
