### ISSUE TITLE
ProgressItem size in grid

### ISSUE THREAD

**Issue by gromiloff** [mikepenz/FastAdapter#90]
I use code from examle https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/EndlessScrollListActivity.java

as layout manager - default GridLayoutManager (spanCount = 2). 

So, the progress item has wight as normal item (half screen). I want the wigth of progress item as 2 items (full wigth screen) in grid layout.

I try to use next code for correct size:
```
final GridLayoutManager a = GridLayoutManager.class.cast(lm);
a.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
    @Override
    public int getSpanSize(int position) {
        return (position == size()) ? 1: a.getSpanCount();
    }
});
```
But get incorrect result - normal items are became full screen size wigth.

So, How I can do my task ?

[screenshot progress incorrect size](https://cloud.githubusercontent.com/assets/1124827/13981293/4ec4a87c-f0f4-11e5-90d1-2c8ee8b5280b.png)

**Comment by gromiloff** [comment]
Sorry it's work fine. Logic was incorrect
return (position != size()) ? 1: a.getSpanCount();

**Comment by masehitam** [comment]
@gromiloff it's old but what is size() ?

**Comment by mikepenz** [comment]
a prive method to his project
