### ISSUE TITLE
Save state for the expandable items

### ISSUE THREAD

**Issue by Z-13** [mikepenz/FastAdapter#900]
I've an expandable adapter like this:
```
adapter = FastItemAdapter()
adapter.getExpandableExtension()

val layoutManager = LinearLayoutManager(activity)

rv.layoutManager = layoutManager
rv.isNestedScrollingEnabled = false
rv.adapter = adapter 
```

On my `AFragment` I've opened some items, then I go to next fragment and get out from it back.
And my `RecyclerView` collapsed all items, but arrow icons are right place. But I'd like to restore expand state my items.

How can I do it?
Thx!

**Comment by mikepenz** [comment]
thanks for reporting back. I am glad it works for you now :)

**Comment by Z-13** [comment]
@mikepenz thx, i've one question, how can I control the  expanded item?
For example, I'd like independently control click and start expand or collapse the item.
