### ISSUE TITLE
RecyclerView not showing at first item position after set new list

### ISSUE THREAD

**Issue by aldyaz** [mikepenz/FastAdapter#902]
## About this issue

- Briefly describe the issue

Issue came up whether set new list after scrolling at certain position using `itemAdapter.set(items)`. I thought it should showing first item (back on top), but it show new list with current scroll position. I've tried `itemAdapter.clear()` and `fastAdapter.notifyAdapterDataSetChanged()` before, but it keep at same position. It seems the adapter saving its scroll state and using it back every set new list.

Is there anything I missed?

## Details

- [x] Used library version
- [x] Used support library version
- [x] Used gradle build tools version
- [x] Used tooling / Android Studio version
- [] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
That's not a behavior the adapter controls. the RecyclerView tries to recreate the same position after its data gets changed. this is done by the ids of the elements in the rv

use the respective recyclerView methods to scroll to top :)

**Comment by aldyaz** [comment]
> That's not a behavior the adapter controls. the RecyclerView tries to recreate the same position after its data gets changed. this is done by the ids of the elements in the rv
> 
> use the respective recyclerView methods to scroll to top :)

So if I want it back to the first position when replace existing list, its rv should perform scroll to top?

**Comment by mikepenz** [comment]
@aldyaz that is actually a thing that in the generic adapter, identifiers and stable ids may not have been used extensively. then the RV will fail to remember the position :) 

But scroll position is in the hands of the RV + the LayoutManager so it's actually nothing the adapter controls on it's own. 

```
recyclerView.scrollToPosition(0)
```
should do the job though

**Comment by Nurtaz440** [comment]
Hello 
How i pass next page inside fist item to second item of recyclerview
