### ISSUE TITLE
How to use multiselect option without ActionModeHelper

### ISSUE THREAD

**Issue by runo280** [mikepenz/FastAdapter#903]
ActionModeHelper needs menu item, but I don't want to use it (I mean menu item).
I looked at [sample ](https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiselectSampleActivity.kt) but I couldn't figure out (as a junior) how to implement multi-select without that.
It would be great if another sample could show the implementation of multi-select with a simple button for the action invoker.

**Comment by mikepenz** [comment]
You can retrieve the `SelectExtension` from the `FastAdapter` and then enable multi select:

https://github.com/mikepenz/FastAdapter/blob/fde5ff985ebf1baed57c97f1329fa53408ce4719/app/src/main/java/com/mikepenz/fastadapter/app/MultiselectSampleActivity.kt#L54-L57
