### ISSUE TITLE
Question : What's the consequence of not migrating Items to the v5 structure ?

### ISSUE THREAD

**Issue by RobbWatershed** [mikepenz/FastAdapter#904]
In the v5.0.0-a06 changelog, you explained how `Item` has to be refactored :

https://github.com/mikepenz/FastAdapter/releases/tag/v5.0.0-a06

Since the library maintains retrocompatibility, nothing prevents me from going on using my v4 items.

I wonder what's the actual consequence of not migrating them ?

**Comment by mikepenz** [comment]
@RobbWatershed there are no functional consequences as far as I can think of. the main difference is that you wouldn't have split the element into its logical pieces, which is very important for some people. 

So if things work for you, you can keep it as it is :)

**Comment by RobbWatershed** [comment]
That's fine. Thanks for the quick answer !
