### ISSUE TITLE
Expand nested items

### ISSUE THREAD

**Issue by JakubMosakowski** [mikepenz/FastAdapter#911]
## About this issue

I cannot find a way to expand nested items.

Example:
**Category 1** 
  -- Subcategory 1 // Subitem of category
    ++ SubSubCategory 1 // Subitem of subcategory
    ++ SubSubCategory 2
  -- Subcategory 2
    ++ SubSubCategory 3
    ++ SubSubCategory 4
**Category 2**
  -- Subcategory 1
  -- Subcategory 2

I'd like to expand "SubSubCategory 2". It works when I'm doing it manually, by clicking (obviously). But in some cases, I'd like to open it programmatically. I know how to do it if I'd like to open Subcategory (`getExpandableExtension().expand(globalPosition)`). But how can I do that with SubSubCategory? I don't know any way to get their position. Changing `isExpanded` flag also doesn't help. I know the identifier of the item I'd like to open.

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Given a (visible) item you could pass in the identifier to the `FastAdapter` and ask for the global position of it:

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt#L477 

or from the `ModelAdapter` if you have that one available: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.kt#L159

this requires the element you want to expand to be visible already though.

**Comment by JakubMosakowski** [comment]
Ahh damn, that was my problem. I should first expand the first row, then search for a nested item. I tried to do it immediately.

`private fun expand(item: GenericItem) {

  // Get position of the item.
  val relativePosition = myAdapter.itemAdapter.getAdapterPosition(item)
  val globalPosition = myAdapter.itemAdapter.getGlobalPosition(relativePosition)

  // Expand item.
  categoriesAdapter.getExpandableExtension().expand(globalPosition)
}` Finally, I simply used the above method twice, the first level then the next one.

**Comment by mikepenz** [comment]
I would be more than happy to take a PR to add a util function for such a case. 

`child` items have a reference to their `parent` item. so it should be rather straightforward to iterate up to the outer parent, and then have all children be expanded from the outermost parent to the lowest child

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/ISubItem.kt#L11

**Comment by JakubMosakowski** [comment]
I can do it today. As you said, it should be doable, by using a parent.

**Comment by mikepenz** [comment]
No stress. But I think it would be a nice addition :)
