### ISSUE TITLE
2 Layout for 1 itemadapter alignment issue

### ISSUE THREAD

**Issue by devtordu** [mikepenz/FastAdapter#916]
## About this issue

- Briefly describe the issue

I have created 2 layouts. One with alignment to the left and the other to the right.
When I feed them to the item adapter, this one follow the first layout processed for all the "cells" of the recyclerview.
The expected result is first cell alignment to the left, second right, third left, ...

- How can the issue be reproduced / sample code

do the basic fastadapter configuration.
create 2 layouts with label and image. One aligned to the right (layout.recyclerview_right_alignment) the other to the left (layout.recyclerview_left_alignment)
create two class (right and left) who extends the item and give them the folowing code

for the first:
override val layoutRes: Int
        get() = R.layout.recyclerview_left_allignment
create another one 

for the second

override val layoutRes: Int
        get() = R.layout.recyclerview_right_allignement

after that, feed the itemadapter with data of your choice and do a simple load balancing code to use the two layouts

## Details

in attached file
[gradle-app.txt](https://github.com/mikepenz/FastAdapter/files/5079422/gradle-app.txt)
[gradle-project.txt](https://github.com/mikepenz/FastAdapter/files/5079423/gradle-project.txt)

**Comment by mikepenz** [comment]
Please ensure each item type has it's own unique identifier

**Comment by devtordu** [comment]
Hello,

It's working perfectly.
Thank you for your help.

And also thank you for your work ;)

Raphaël
