### ISSUE TITLE
how to use ModelAdapter with EndlessScroll?

### ISSUE THREAD

**Issue by ishdemon** [mikepenz/FastAdapter#917]
## About this issue

i tried this : 

`` listItemAdapter = ModelAdapter {
            ModelApptItem(it)
        }``

``val fastAdapter = FastAdapter.with(listItemAdapter)``
        ``val footerAdapter = ItemAdapter<ProgressItem>()``
        ``fastAdapter.addAdapter(1,footerAdapter)``

This lastline throws this error : 
``Type parameter bound for A in fun <A : IAdapter<ModelApptItem>> addAdapter
(
index: Int,
adapter: A
)
: FastAdapter<ModelApptItem>
is not satisfied: inferred type ItemAdapter<ProgressItem> is not a subtype of IAdapter<ModelApptItem>``

**Comment by ishdemon** [comment]
how to make footeradapter compatible with my ModelItem??

**Comment by mikepenz** [comment]
you want to make a non type bound version of the fastAdapter as `FastAdapter.with(listItemAdapter)` will infer the type of the `ModelAppItem` 

can you create the `FastAdapter` providing both adapters initially already?

**Comment by ishdemon** [comment]
You mean 
```
Fastadapter.with(listof(listItemAdapter,footerAdapter)
```

**Comment by mikepenz** [comment]
Yes: 
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt#L912
allows you to have a list of adapters, and the `FastAdapter` will have to be the parent type. in most cases that's then the interface. 

E.g. it may be a `GenericFastAdapter` which is a type alias for: `FastAdapter<GenericItem>` 
and where `GenericItem` is a typealias for `IItem<out RecyclerView.ViewHolder>`

Or similarily showcased here:
https://github.com/mikepenz/FastAdapter/blob/fde5ff985ebf1baed57c97f1329fa53408ce4719/app/src/main/java/com/mikepenz/fastadapter/app/AdvancedSampleActivity.kt#L58

**Comment by ishdemon** [comment]
I tried that but then I was unable to get the model out of item in onclicklistener.

**Comment by mikepenz** [comment]
@ishdemon so the way generics work the `FastAdapter` has to be the greatest type which is available for both. in your case it's the interface. 

So for listeners you will get back the interface as type because the global listener is that generic type in this case. 

you can though do a type check and cast to the anticipated type .

**Comment by mikepenz** [comment]
I hope this helped to solve your question
