### ISSUE TITLE
FastAdapter with FastScroller

### ISSUE THREAD

**Issue by gkiss01** [mikepenz/FastAdapter#919]
I want to use this library: 
https://github.com/quiph/RecyclerView-FastScroller

How can the adapter implement the OnPopupTextUpdate interface, as the lib says?

```
class MyAdapter : RecyclerView.Adapter<SomeViewHolder>, OnPopupTextUpdate {
    override fun onChange(position: Int): CharSequence {
        val header = // compute value for header using position
        return header                  
    }
}
```

**Comment by mikepenz** [comment]
We have a sample for the `FastScrollIndicator` here: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/adapters/FastScrollIndicatorAdapter.kt#L17

Pretty sure you can do this, or just extend the `FastAdapter` and implement the interface as you have to
