### ISSUE TITLE
Is there a way to uncheck them all？

### ISSUE THREAD

**Issue by dzq0906** [mikepenz/FastAdapter#920]
## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Please follow the issue template. 

But I assume you meant: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/select/SelectExtension.kt#L355

**Comment by dzq0906** [comment]
Ok, this will solve my problem, thank you, but this method is outdated, is there any other way to replace it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mikepenz/FastAdapter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 下午4:06
收件人:&nbsp;"mikepenz/FastAdapter"<FastAdapter@noreply.github.com&gt;;
抄送:&nbsp;"NightLiar"<1286465087@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mikepenz/FastAdapter] Is there a way to uncheck them all？ (#920)





 
Please follow the issue template.
 
But I assume you meant: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/select/SelectExtension.kt#L355

**Comment by mikepenz** [comment]
why is this method outdated?

**Comment by dzq0906** [comment]
Your 3.3.1 library USES @deprecated in AndroidX to mark that the method is expired or out of date

**Comment by dzq0906** [comment]
Oh, I am using FastAdapter. I should use SelectExtension. I am wrong
