### ISSUE TITLE
Error deleting in multiselect example

### ISSUE THREAD

**Issue by readbeard** [mikepenz/FastAdapter#93]
Hi,
I noticed that in the multiselect example, the snackbar is shown even when there is no element selected.
Steps for reproducing:

- Long click on an item
- Delete the item clicking on the trash button
- Wait until the undo snackbar is dismissed
- Click again on the trash button.

**Comment by readbeard** [comment]
I think you can solve the problem in this way:
In class UndoHelper, in the method
```java
public Snackbar remove(View view, String text, String actionText, @Snackbar.Duration int duration, Set<Integer> positions)
```
you can add the following line:
```java
if(positions.isEmpty()){
  return Snackbar snackbar = Snackbar.make(view,"No item selected",duration);
}
```

**Comment by mikepenz** [comment]
@readbeard this should not happen if the `ActionMode` is finished when the action is clicked. 

`mode.finish()` should do the job here:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiselectSampleActivity.java#L157

Related to #94

**Comment by readbeard** [comment]
Hi,
i think your fix won't work. In fact, if you call '''mode.finish()''', the _undo_ operation won't work anymore. I tried it before your reply, and that's the reason why i posted my solution.
Do you confirm that?
Thanks
