### ISSUE TITLE
Question:  How to show text during swipe operation

### ISSUE THREAD

**Issue by kenargo** [mikepenz/FastAdapter#933]
The Google Play sample shows text during the swipe operation and I'm trying to create the same effect but the current sample in GitHub and the sample online appear to be from different versions (or I just cannot see the connection).

I searched the issues list, which is often a good source of information but also came up blank.

I'm guessing that maybe the sample is actually using drawables (which do show during swipe) but that wouldn't be the best for localization of maybe I need to manually draw the items at runtime???

Thanks ahead of time!

**Comment by mikepenz** [comment]
@kenargo do you have a screenshot of the screen which you specifically mean? 

I assume you reference this sample activity: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SwipeListActivity.kt

The sample with the text behind is this one:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SwipeDrawerListActivity.kt

(looks like it's font is currently wrong color :D)

**Comment by kenargo** [comment]
This one

-------- Original message --------From: Mike Penz <notifications@github.com> Date: 10/19/20  11:04 PM  (GMT-08:00) To: mikepenz/FastAdapter <FastAdapter@noreply.github.com> Cc: "Kenneth A. Argo" <kenargo@kenargo.com>, Mention <mention@noreply.github.com> Subject: Re: [mikepenz/FastAdapter] Question:  How to show text during swipe operation (#933) 
@kenargo do you have a screenshot of the screen which you specifically mean?
I assume you reference this sample activity: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SwipeListActivity.kt
The sample with the text behind is this one:
https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/SwipeDrawerListActivity.kt
(looks like it's font is currently wrong color :D)

**Comment by kenargo** [comment]
Yes, I think that's it!
