### ISSUE TITLE
[Help] Nested recyclerview example needed

### ISSUE THREAD

**Issue by megaacheyounes** [mikepenz/FastAdapter#935]
Great library, but its a bit challenging to implement a nested layout like playstore,

can you please add an example of nested recycler, vertical recycler view where  each item has a horizontal recycler view

I have already tried to implement something similar but it was laggy and glitchy
 
## Details
- used version v5.2.4
- used BindingItem
- initially I load categories, then load apps for each visible category 
- whenever a category is recycled (new category is visible), I load its apps if not loaded

## issues
- everytime data changes, UI freezes for 1-2  seconds
- scrolling is laggy
- recycled views flicker (bindView(...) called twice)

## Checklist

- [ check ] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [ check ] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [ check ] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ check ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ check ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by Benjiko99** [comment]
Here you go, this worked for me.

```kotlin
class HorizontalRecyclerItem(val data: Data) : AbstractItem<HorizontalRecyclerItem.ViewHolder>() {

    class ViewHolder(val view: View) : FastAdapter.ViewHolder<HorizontalRecyclerItem>(view) {
        private val itemAdapter = ItemAdapter.items<MyNestedItem>()
        private val fastAdapter = FastAdapter.with(itemAdapter)

        init {
            fastAdapter.apply {
                setHasStableIds(true)
                view.recyclerView.adapter = fastAdapter
            }
        }

        override fun bindView(item: MyItem, payloads: List<Any>) {
            // Set list items using DiffUtil
            FastAdapterDiffUtil[itemAdapter] = getListItems(data)
        }
    }
}
```

**Comment by mikepenz** [comment]
Thanks @Benjiko99 for answering.

**Comment by stef-ang** [comment]
is it mandatory to use Diff Util for that case? I have similar case, but my problem is: all items in every parent item are same. apparently the child items are reused by other item.
![Screenshot_1604770051](https://user-images.githubusercontent.com/6779288/98465047-413ca980-21f9-11eb-8974-78e801626270.png)
here is my parent item
```
class HomeMovieSectionVI(val title: String, val movies: List<HomeMovie>) : AbstractBindingItem<ItemHomeMovieSectionBinding>() {

    private val itemAdapter = ItemAdapter<HomeMovieSmallVI>()
    lateinit var fastAdapter: FastAdapter<HomeMovieSmallVI>

    override val type: Int get() = R.id.item_home_movie_section

    override fun bindView(binding: ItemHomeMovieSectionBinding, payloads: List<Any>) {
        binding.textTitle.text = title
        binding.buttonAll.text = "See All"
        itemAdapter.setNewList(movies.map { movie ->
            HomeMovieSmallVI(movie).also {
                it.identifier = movie.id.toLong()
            }
        })
    }

    override fun createBinding(inflater: LayoutInflater, parent: ViewGroup?): ItemHomeMovieSectionBinding {
        fastAdapter = FastAdapter.with(itemAdapter)
        fastAdapter.setHasStableIds(true)
        val binding = ItemHomeMovieSectionBinding.inflate(inflater, parent, false)
        binding.recyclerView.apply {
            layoutManager = LinearLayoutManager(parent?.context, RecyclerView.HORIZONTAL, false)
            adapter = fastAdapter
        }
        return binding
    }
}
```

**Comment by stef-ang** [comment]
nvm, I've got the solution, I moved `recyclerView.adapter = fastAdapter` to `bindView`, and to avoid blink when render, I used `FastAdapterDiffUtil` in fragment only. Thanks for insight.
