### ISSUE TITLE
Potential feature disparity between AbstractItem and AbstractBindingItem regarding ViewHolders

### ISSUE THREAD

**Issue by Benjiko99** [mikepenz/FastAdapter#936]
- [5.2.1] Used library version

I've noticed a potential feature disparity between `AbstractItem` and `AbstractBindingItem` that may limit what items can be created with `AbstractBindingItem`.

With the regular `AbstractItem`, you implement the `ViewHolder` yourself, which gives you the ability to have property variables on the `ViewHolder`. When you're setting new list items, you're passing in all-new instances of the Item, which means you cannot retain any sort of state in them, now I know you don't want to be storing state there...but there is one use case for this, and that is when creating a nested RecyclerView within the Item. I need to hold the nested `FastAdapter` instance somewhere, and this appears like the only place for it, as the `ViewHolder` survives the setting of new list items on the outer RecyclerView.

I'll end my rant here by saying that with `AbstractBindingItem` you cannot implement your own `ViewHolder`, thus lose this long-lived object for storing properties. Do you have any thoughts on this subject? :flushed: 

**Example of what is possible with `AbstractItem`**
```kotlin
class MyItem() : AbstractItem<MyItem.ViewHolder>() {

    class ViewHolder(val view: View) : FastAdapter.ViewHolder<MyItem>(view) {
        private val itemAdapter = ItemAdapter.items<MyNestedItem>()
        private val fastAdapter = FastAdapter.with(itemAdapter)

        override fun bindView(item: MyItem, payloads: List<Any>) {
            FastAdapterDiffUtil[itemAdapter] = getListItems()
        }
    }
}
```

**Comment by mikepenz** [comment]
@Benjiko99 the provided `AbstractBindingItem` is meant for the 99% of the usecases where you'd love viewBinding and have it set-up with ease and not much of work. 

From the libraries perspective the `AbstractBindingItem` is actually just a very slim wrapper around the normal item, and not containing too much logic. 

For more complex usecases you can either define your more complex `CustomAbstractBindingItem` which will use a different base `ViewHolder` serving your needs, or you could actually even use normal `AbstractItem` as base. ViewBinding was working with that one too, just needed a bit more custom work. 

In the end the goal is to provide the easiest possible implementation for most usecases by the library, but stay as flexible for the rest of requirements like possibly yours :) 

So I'd suggest you may want to look into the `AbstractBindingItem` copy it over to your project and extend it with the requirements you'd want to include.
