### ISSUE TITLE
Is indentation possible on expandable lists?

### ISSUE THREAD

**Issue by Androidjent** [mikepenz/FastAdapter#937]
Hello,

so far I found nothing on this topic.
In the sample app, indentation of different levels always seems to be solved like this:

item1
-item2
--item3
_ _
item2
-item3

I would like to have indentation of the item, like this:

https://i.imgur.com/t4Mh0HT.png

Do you know a way with Fastadapter?

Many thanks!

**Comment by mikepenz** [comment]
@Androidjent the `FastAdapter` does not specify the appearance of your elements, what it does though is to provide the framework which allows you to define the UI. 

What you can do for example is to define a `level` for your items (like we did in the MaterialDrawer)
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDrawerItem.kt#L22-L29

and then just apply the padding on the start
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDescribeableDrawerItem.kt#L76
