### ISSUE TITLE
Question: Remove warnings raw use of parameterized class

### ISSUE THREAD

**Issue by sebastianperdomo** [mikepenz/FastAdapter#939]
Hi, is there any way to remove these warnings in the code ?

![imagen](https://user-images.githubusercontent.com/9873666/98031482-524c7b80-1df1-11eb-8a91-bd5986c8f632.png)

i use the Java && AndroidX | v3.3.1 version

Thanks

**Comment by mikepenz** [comment]
@sebastianperdomo sadly not with the old releases. We have since reworked the generic types to simplify them, thanks to Kotlin offering better support. 

Please consider to upgrade to the latest release fully embracing Kotlin for the best experience.

**Comment by sebastianperdomo** [comment]
Thanks mike.

is possible to use the lats version of the Kotlin in a Java AndoridX proyect ? will work ? is compatible ?

**Comment by mikepenz** [comment]
It may work under Java, but I can not guarantee. There's a high chance of various things being a lot more complicated than they'd be with Kotlin. 

I highly recommend you to look into Kotlin as it will significantly help you ;) 

Btw. these are just warnings above and won't cause actual harm to your project as the generic times are anyways removed after compilation
