### ISSUE TITLE
Classes not found in v5.3.0 APK

### ISSUE THREAD

**Issue by RobbWatershed** [mikepenz/FastAdapter#943]
## About this issue

- Briefly describe the issue
Android Studio cannot find certain classes in the 5.3.0 APK (e.g. `com.mikepenz.fastadapter.swipe.SimpleSwipeCallback`, `com.mikepenz.fastadapter.utils.DragDropUtil`) - see screenshots below

![image](https://user-images.githubusercontent.com/35880555/98536976-e5216600-2288-11eb-897f-79359b4ef4c6.png)

![image](https://user-images.githubusercontent.com/35880555/98536989-e783c000-2288-11eb-9dd5-058ad810a595.png)

Gradle setup
```
    def fastadapter_version = "5.3.0"
    implementation "com.mikepenz:fastadapter:$fastadapter_version"
    implementation "com.mikepenz:fastadapter-extensions-diff:$fastadapter_version"
    implementation "com.mikepenz:fastadapter-extensions-swipe:$fastadapter_version"
    implementation "com.mikepenz:fastadapter-extensions-drag:$fastadapter_version"
    implementation "com.mikepenz:fastadapter-extensions-expandable:$fastadapter_version"
    implementation "com.mikepenz:fastadapter-extensions-scroll:$fastadapter_version"
    implementation "com.mikepenz:fastadapter-extensions-paged:$fastadapter_version"
    implementation "com.mikepenz:fastadapter-extensions-ui:$fastadapter_version"
    implementation "com.mikepenz:fastadapter-extensions-utils:$fastadapter_version"
```

I've already done File > Invalidate cache / restart with no effect

- How can the issue be reproduced / sample code
Update a project with gradle dependencies from any version of FastAdapter to v5.3.0

## Details
- [x] Used library version : 5.3.0
- [x] Used support library version : AndroidX (not sure what you're looking for here)
- [x] Used gradle build tools version : com.android.tools.build:gradle:4.1.0 / gradle-6.5 (was working with FastAdapter v5.2.4)
- [x] Used tooling / Android Studio version : AS 4.1 (was working with FastAdapter v5.2.4)
- [x] Other used libraries, potential conflicting libraries : None that I know of

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Do you see those classes in the bytecode from the aar's?

**Comment by RobbWatershed** [comment]
The plot thickens... looks like Gradle has only been able to resolve core, diff and drag. The others AAR are missing.

![image](https://user-images.githubusercontent.com/35880555/98538433-0b480580-228b-11eb-81d8-920f21bb9945.png)

Is everything good on Jitpack ?

**Comment by mikepenz** [comment]
Oh that seems to be it. not all was published to bintray. (btw. this does not use jitpack :D)

**Comment by mikepenz** [comment]
let me try to re-publish

**Comment by RobbWatershed** [comment]
Looks like everything's back to normal. Thanks for your quick answer, as usual 😉

**Comment by mikepenz** [comment]
Sorry that the initial publish failed. Glad all is well now.
