### ISSUE TITLE
Color control for selected and non-selected backgrounds - did I do it the right way?

### ISSUE THREAD

**Issue by Androidjent** [mikepenz/FastAdapter#944]
Hello, thank you very much for reading!

I want to set a background color for selected state while also retaining dynamic control over the non-selected items' background color. Specifically, I want alternating colors for my non-selected items. My code is working OK so far...I rather wonder if this is the clean, idiomatic way to do it or if there is better. This is my shortened Code:

My item:

```
Item : All the interfaces...
{ 
    fun setColor(oColorP:Int): SimpleSubExpandableItem {
        oColor = oColorP
        return this
    }

    override fun bindView(holder: ViewHolder, payloads: List<Any>) {
        super.bindView(holder, payloads)

        //get the context
        val oContext = holder.itemView.context

        val oPressedColor = FastAdapterUIUtils.adjustAlpha(Color.RED, 25)
        holder.view.background = getMySelectableBackground(oContext, oPressedColor, oColor,true)
}
```

```
Customized fastadapterUtil
{
    fun getSelectableBackground(
            ctx: Context,
            @ColorInt selected_color: Int,
            @ColorInt normal_color: Int,
            animate: Boolean
    ): StateListDrawable {
        val states = StateListDrawable()

        val clrActive = ColorDrawable(selected_color)
        states.addState(intArrayOf(android.R.attr.state_selected), clrActive)

       //custom
        val clrNormal = ColorDrawable(normal_color)
        states.addState(intArrayOf(android.R.attr.state_enabled), clrNormal)

        states.addState(intArrayOf(), ContextCompat.getDrawable(ctx, FastAdapterUIUtils.getSelectableBackground(ctx)))

        //if possible we enable animating across states
        if (animate) {
            val duration = ctx.resources.getInteger(android.R.integer.config_shortAnimTime)
            states.setEnterFadeDuration(duration)
            states.setExitFadeDuration(duration)
        }

        return states
    }
}
```

In the fragment, I iterate recursively through ItemAdapter.adapterItems and set the alternating colors I want.  
```
    fun ColorFlashRecursive(oListP:MutableList<SimpleSubExpandableItem>) {
        oListP.forEachIndexed{ index, element ->
            val oColor = Manager.getColor(index % 2 == 0, element.iCatLevel)
            element.setColor(oColor)
            if (element.subItems.isNotEmpty())
                ColorFlashRecursive(element.subItems as MutableList<SimpleSubExpandableItem>)
        }
    }
```
Then, i do Fastadapter.notifyDataSetChanged() to kick off the colors.

The above code works OK, as long as i don't select between different items in a fast tempo. There are never wrong selections, but on fast tempos, there is a tendency to deselect everything or to react slowly. But this could be stock behavior.

There is another way, which has better reaction time, but seems like a dirty hack:

```
Item : All the interfaces...
{ 
    fun setColor(oColorP:Int): SimpleSubExpandableItem {
        oColor = oColorP
        return this
    }

    override fun bindView(holder: ViewHolder, payloads: List<Any>) {
        super.bindView(holder, payloads)

        //get the context
        val oContext = holder.itemView.context

        val oPressedColor = FastAdapterUIUtils.adjustAlpha(Color.RED, 25)
        holder.view.setBackgroundColor(oColor)
        holder.view.foreground = FastAdapterUIUtils.getSelectablePressedBackground(oContext, oPressedColor, 50, true)
}
```

I omit StateListDrawable and use a translucent Foreground for selections.

Can one of these ways be recommended? Or do I need ro look in another direction? I appreciate any advice.

**Comment by mikepenz** [comment]
@Androidjent historically it seems when doing very fast selections the animation from the `StateListDrawable` fails to stay at the right state, so you may want to try it without its animation if it still occurs.

Generally speaking this question is not necessarily related to the `FastAdapter` but more wide on how `RecyclerView`s function.

both approaches would work I believe, only that the second approach results in different behavior. e.g. actually overlapping your items text and everything which may not be anticipated. 

in general it's great though that you use the `StateListDrawable` and let the system update things accordingly. 

Theoretically you can also achieve it with a real item update (triggering `bindView` again, but this is not as efficient, and works a bit against what the system can do)

**Comment by Androidjent** [comment]
Thank you very much! Without the animation, it works better. It does not seem that my app is visually missing out, so I will just go with that.
