### ISSUE TITLE
Lag when setting large lists of items (1k+)

### ISSUE THREAD

**Issue by CarlosEsco** [mikepenz/FastAdapter#945]
Is fast adapter meant not meant for large item adapters?  I am having performance issues on the initial set/add of the items when the item count is 300+ to  over 1k.  I've tried set, setNewList, adding individually, adding in batches, but still get a lag since it seems the entire thing is done on the ui thread.

I have a fragment with the ItemAdapter, and FastAdapter created at the class level.

My view model has a live data that returns the list of items. Up until this point no issues as soon as itemAdapter.set is called my loading bar on screen freezes for a couple seconds then the items are loaded

    Background concurrent copying GC freed 4328(178KB) AllocSpace objects, 0(0B) LOS objects, 13% free, 38MB/44MB, paused 396us total 122.547ms
    Background concurrent copying GC freed 5380(224KB) AllocSpace objects, 0(0B) LOS objects, 11% free, 46MB/52MB, paused 587us total 139.941ms
    Background concurrent copying GC freed 6105(264KB) AllocSpace objects, 1(16KB) LOS objects, 9% free, 55MB/61MB, paused 521us total 168.603ms
    I/OpenGLRenderer: Davey! duration=3132ms; Flags=0, IntendedVsync=1312623048750308, Vsync=1312623048750308, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1312623064676100, AnimationStart=1312623064711900, PerformTraversalsStart=1312623064767200, DrawStart=1312626090931500, SyncQueued=1312626167815700, SyncStart=1312626168811500, IssueDrawCommandsStart=1312626179214300, SwapBuffers=1312626181097300, FrameCompleted=1312626182311700, DequeueBufferDuration=307000, QueueBufferDuration=440000, 
    NativeAlloc concurrent copying GC freed 19539(851KB) AllocSpace objects, 0(0B) LOS objects, 9% free, 58MB/64MB, paused 871us total 209.348ms
    I/Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
    I/OpenGLRenderer: Davey! duration=1948ms; Flags=0, IntendedVsync=1312626371199755, Vsync=1312626371199755, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1312626380364400, AnimationStart=1312626380403800, PerformTraversalsStart=1312626382268800, DrawStart=1312626382428400, SyncQueued=1312626382681100, SyncStart=1312626383096800, IssueDrawCommandsStart=1312627002886900, SwapBuffers=1312628317936700, FrameCompleted=1312628320056500, DequeueBufferDuration=414000, QueueBufferDuration=721000, 
    I/Choreographer: Skipped 80 frames!  The application may be doing too much work on its main thread.
    I/OpenGLRenderer: Davey! duration=776ms; Flags=0, IntendedVsync=1312626388262381, Vsync=1312626988262357, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1312627002305700, AnimationStart=1312627002355800, PerformTraversalsStart=1312627017661200, DrawStart=1312627017843700, SyncQueued=1312627018098100, SyncStart=1312628321051700, IssueDrawCommandsStart=1312628347237200, SwapBuffers=1312628373485600, FrameCompleted=1312628468110800, DequeueBufferDuration=400000, QueueBufferDuration=634000, 

I am using v5.3.0 version of the library

**Comment by CarlosEsco** [comment]
To add when it's only around 100 items it loads instantly and when I remove the set. It loads instantly so it's not the logic leading up to the set

**Comment by mikepenz** [comment]
We can't reproduce this report with the sample app. 

I've adjusted the `AdvancedActivity` to be created with with above 300_000 items. It is not only creating those items instantly but also loads the list without freezes. 

Please verify that your implementation does not contain any heavy allocations, does something heavy during item creation, does not have leaks, ... 

Alternatively please provide a sample app showcasing the issue, so we could reproduce

**Comment by CarlosEsco** [comment]
I'll double check my implementation  and make a sample app this week.

**Comment by CarlosEsco** [comment]
https://github.com/CarlosEsco/fastadaptersample

It seems to happen once you add navigation components

**Comment by mikepenz** [comment]
Thanks for the sample, will try to have a look as quick as possible

**Comment by mikepenz** [comment]
I have had a look at your sample app. the problem is not a result of the `FastAdapter` but instead of your layouts. 

The `RecyclerView` is defined to grow with it's content via `wrap_content` as such it will grow unlimited and will in the end display all items at once. which kinda breaks the purpose of the `RecyclerView` you could already use a `ListView` instead then. 

Just to proof this to be the case I limited the height to 500dp and everything is fast instantly. 

I haven't had a too deep look into what's wrong with the layout hierarchy, only changing to `0dp` height and adding a bottom constraint didn't do the job yet, there's something else off.

**Comment by CarlosEsco** [comment]
oh thanks for the help!!  Its easy to miss a small detail like that.

**Comment by CarlosEsco** [comment]
FYI: It was the nested scrollview. Even switch the recycler to match parent for both caused issues

**Comment by mikepenz** [comment]
thanks for reporting back. I was suspicious about it but haven't had the time to look further into it
