### ISSUE TITLE
Does FastAdapter support DataBinding?

### ISSUE THREAD

**Issue by Mariius** [mikepenz/FastAdapter#949]
## About this issue

- I am looking at examples, but it is unclear if FastAdapter supports DataBinding or not. If yes, then maybe someone could provide an example of how FastAdapter can be used with DataBindings?

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@Mariius the library doesn't specify anything which would prevent it. 

There is an example showcasing `viewBinding` and I know of a few of the users having used `dataBinding` in the past. There may be some issues with discussions in its regard.

I think the core part is that you are able to define the model to the binding when the view is bound. 

```
        public void bind(Movie movie) {
            binding.setMovie(movie);
            binding.executePendingBindings();
        }
```
https://medium.com/@sanjeevy133/an-idiots-guide-to-android-recyclerview-and-databinding-4ebf8db0daff

**Comment by mikepenz** [comment]
Hope this answered your question
