### ISSUE TITLE
`EndlessRecyclerOnScrollListener` creates new objects every scroll

### ISSUE THREAD

**Issue by jasonsparc** [mikepenz/FastAdapter#95]
@FabianTerhorst: It seems that at [line 39](https://github.com/mikepenz/FastAdapter/blob/99a6c7f755e06a120ea472c74d03826d4036ced1/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnScrollListener.java#L39) of `EndlessRecyclerOnScrollListener`, it creates new `OrientationHelper` objects all the time (that is on every scroll). This creates too much garbage for the garbage collector.

I think it's safe to cache the `OrientationHelper` object, creating it only if it is null, that is for the first time.

But because it is possible that the orientation may change, then there should exist 2 `OrientationHelper` objects for each orientation (like [`StaggeredGridLayoutManager`](https://github.com/android/platform_frameworks_support/blob/master/v7/recyclerview/src/android/support/v7/widget/StaggeredGridLayoutManager.java#L403)), creating the `OrientationHelper` for the given orientation only when needed.

Thank you for contributing `EndlessRecyclerOnScrollListener` by the way, it was a great edition :)

**Comment by FabianTerhorst** [comment]
@jasonsparc nice catch.

**Comment by FabianTerhorst** [comment]
#96

**Comment by jasonsparc** [comment]
Nice! :D

**Comment by mikepenz** [comment]
will be in the next version v1.3.0
