### ISSUE TITLE
Helpers are still referenced in README and examples

### ISSUE THREAD

**Issue by readbeard** [mikepenz/FastAdapter#957]
## About this issue
In the README of this repo, and in the linked examples, there are references to and usages of helper classes (e.g.: ActionModeHelper) which are not present anymore in the core of this library (e.g.: _com.mikepenz.fastadapter.helpers.ActionModeHelper_ is missing). This should be updated as it could be misleading for potential users. 
Besides, what's the provided alternative to those helper classes?
## Details
- [5.3.2 ] Used library version

**Comment by mikepenz** [comment]
@readbeard the helper still exists as part of the utils extension. https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-utils/src/main/java/com/mikepenz/fastadapter/helpers/ActionModeHelper.kt

it's noted in the dependencies section as a possible addon: https://github.com/mikepenz/FastAdapter#provide-the-gradle-dependency

If you have suggestions to improve the README please feel free to help make the project better by opening a PR please :)
