### ISSUE TITLE
viewBinding issue

### ISSUE THREAD

**Issue by azizi436** [mikepenz/FastAdapter#960]
Hi 
1) Im using **viewBinding** in my project and now i want to use it for **FastAdapter** but  i dont know what should i put in **<>** 
2)What is the **type** and why we should use **type** exactly? 

![image](https://user-images.githubusercontent.com/36598338/103234714-92456000-4955-11eb-9742-5488b687b983.png)

*my xml item class name is job_item and its **Viewbinding** is **JobItemBinding**

**Comment by mikepenz** [comment]
```
class GalleryItem(...) : AbstractBindingItem<GalleryItemBinding>() {

    override val type: Int
        get() = R.id.gallery_item

    override fun bindView(binding: GalleryItemBinding, payloads: List<Any>) {
        super.bindView(binding, payloads)
        ...
    }

    override fun createBinding(inflater: LayoutInflater, parent: ViewGroup?): GalleryItemBinding {
        return GalleryItemBinding.inflate(inflater, parent, false)
    }
}
```

A sample could look like

**Comment by azizi436** [comment]
Ok thanks, but how can i use **position** ( i mean item position ) in **bindView** ?

**Comment by azizi436** [comment]
> 
> 
> ```
> class GalleryItem(...) : AbstractBindingItem<GalleryItemBinding>() {
> 
>     override val type: Int
>         get() = R.id.gallery_item
> 
>     override fun bindView(binding: GalleryItemBinding, payloads: List<Any>) {
>         super.bindView(binding, payloads)
>         ...
>     }
> 
>     override fun createBinding(inflater: LayoutInflater, parent: ViewGroup?): GalleryItemBinding {
>         return GalleryItemBinding.inflate(inflater, parent, false)
>     }
> }
> ```
> 
> A sample could look like

Ok thanks, but how can i use position ( i mean item position ) in bindView ?

**Comment by mikepenz** [comment]
That's not supported with this item. you can look at the base abstract code: https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-binding/src/main/java/com/mikepenz/fastadapter/binding/AbstractBindingItem.kt#L18

and adjust it so you get the `adapterPosition` of the `ViewHolder`
