### ISSUE TITLE
Restrict where a draged item can be dropped

### ISSUE THREAD

**Issue by poldi171254** [mikepenz/FastAdapter#978]
I'm going through your SimpleItemListActivity example and while I can restrict which items in the list can by dragged/dropped via withIsDraggable, there doesn't seem to be a way of restricting where the item can be dragged to.

An examples would be where I have a list of say ten items, where items 1-3 and 8-10 cannot be dragged, while 4-8 can. I need to be able to move items 4-8 and only those four (i.e item 5 cannot go to items 1-3 or 8-10.

Thanks

**Comment by mikepenz** [comment]
This library is mainly focused on the API improvements around `RecyclerView.Adapter`, while it offers some extension functions to simplify the work with things like draggable, it's not the core purpose. Furthermore those extensions only serve as a sole simplified API and only expose existing functionality from the `RecyclerView` library. 

If it is possible to achieve this with `RecyclerView` APIs it will also be possible in this project. You may find a solution to this searching `RV`

**Comment by mikepenz** [comment]
This new PR + sample activity should help for this usecase: https://github.com/mikepenz/FastAdapter/pull/985
