### ISSUE TITLE
FastAdapter.getPosition implementation question

### ISSUE THREAD

**Issue by DeweyReed** [mikepenz/FastAdapter#988]
## About this issue

[FastAdapter.getPosition](https://github.com/mikepenz/FastAdapter/blob/develop/fastadapter/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt#L477) loops through adapters and accumulates item count until the target is found. My question is, why to use `position = adapter.adapterItemCount` instead of `+=`? Using `=` remembers the last adapter item count rather than all item count before. Is this a bug, or is my understanding wrong?

## Details
- [5.3.5] Used library version
- [4.1.3] Used tooling / Android Studio version

## Checklist

- [√] Searched for [similar issues](https://github.com/mikepenz/FastAdapter/issues)
- [√] Checked out the [sample application](https://github.com/mikepenz/FastAdapter/tree/develop/app)
- [√] Read the [README](https://github.com/mikepenz/FastAdapter/blob/develop/README.md)
- [√] Checked out the [CHANGELOG](https://github.com/mikepenz/FastAdapter/releases)
- [√] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/FastAdapter/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
This looks indeed like a bug. Thanks for pointing this out. Will have a look
