### ISSUE TITLE
Click listener for children views of item that extends AbstractBindingItem

### ISSUE THREAD

**Issue by runo280** [mikepenz/FastAdapter#996]
This is my Item class:

```
class ChannelItem : AbstractBindingItem<ChannelListItemBinding>() {
    lateinit var channel: ChannelEntity

    override val type: Int
        get() = R.id.channel_list_item

    override fun bindView(binding: ChannelListItemBinding, payloads: List<Any>) {
          ...
    }

    override fun createBinding(
        inflater: LayoutInflater,
        parent: ViewGroup?
    ): ChannelListItemBinding {
        return ChannelListItemBinding.inflate(inflater, parent, false)
    }
}
```

I want to set click listener for views inside of my item, I followed your [sample](https://github.com/mikepenz/FastAdapter#4-click-listeners-for-views-inside-your-item) but I can't access to `ViewHolder` of `ChannelItem`:
![image](https://user-images.githubusercontent.com/13608702/115672176-d2808200-a33a-11eb-9758-55899f497ea9.png)

**Comment by mikepenz** [comment]
@runo280 it looks like you are mixing up `Item` vs. `ViewHolder` the `ChannelItem` is the construct holding the data and defining the binding logic, whereas the `ViewHolder` holds the views displayed in the `RecyclerView`

<img width="860" alt="Screenshot 2021-04-22 at 09 26 39" src="https://user-images.githubusercontent.com/1476232/115673375-da492200-a34c-11eb-8172-c28d6ad202ab.png">

You want to adjust the type check to the `ViewHolder` instead

**Comment by runo280** [comment]
It seems I should have asked my question in different way, how can I access to ViewHolder when we use [AbstractBindingItem](https://github.com/mikepenz/FastAdapter#1b-implement-item-with-viewbinding-the-easiest-way)?

**Comment by mikepenz** [comment]
@runo280 this abstract item is not designed to access the viewHolder, as it abstracts its existence away. 

You can look at it's implementation though and adjust it for your needs: https://github.com/mikepenz/FastAdapter/blob/develop/fastadapter-extensions-binding/src/main/java/com/mikepenz/fastadapter/binding/AbstractBindingItem.kt

**Comment by knife-s** [comment]
> @runo280 this abstract item is not designed to access the viewHolder, as it abstracts its existence away.
> 
> You can look at it's implementation though and adjust it for your needs: https://github.com/mikepenz/FastAdapter/blob/develop/fastadapter-extensions-binding/src/main/java/com/mikepenz/fastadapter/binding/AbstractBindingItem.kt

So it is not possible to use `AbstractBindingItem ` with  `addEventHook`?

**Comment by sebastianperdomo** [comment]
Same problem here

how to access the ClickEventHook with a AbstractBindingItem ? the ViewHolder don't exist...

Thanks !

**Comment by mikepenz** [comment]
@sebastianperdomo there is a `ViewHolder` but it's of the type: `BindingViewHolder<ViewBinding>`

**Comment by julienherrero** [comment]
It's a bit late but maybe it will still help: I used [this suggested extension](https://github.com/mikepenz/FastAdapter/issues/884#issuecomment-619419014) to resolve this without switching item type to `ViewHolder`

```
class ClickEvent(private val listener: Listener) : ClickEventHook<FavoriteEmptyItem>() {

        override fun onBindMany(viewHolder: RecyclerView.ViewHolder): List<View> {
            val viewList = listOf(
                viewHolder.asBinding<ItemEmptyBinding> {
                    it.buttonItemEmptyDestination
                },
                viewHolder.asBinding<ItemEmptyBinding> {
                    it.imageViewItemEmptyRemove
                }
            )
            return viewList.filterNotNull()
        }

        override fun onClick(v: View, position: Int, fastAdapter: FastAdapter<FavoriteEmptyItem>, item: FavoriteEmptyItem) {
            when (v.id) {
                R.id.buttonItemEmptyDestination -> listener.onEmptyItemDestinationClick(item, position)
                R.id.imageViewItemEmptyRemove -> listener.onEmptyItemRemoveClick(item, position)
                else -> Timber.w("Unknown FavoriteEmptyItem view id")
            }
        }
    }
``` 

Not sure if it's perfect but it works 👌

**Comment by kimliss** [comment]
```kotlin
fastAdapter.addEventHook(object : ClickEventHook<ChannelItem>(){

    override fun onBind(viewHolder: RecyclerView.ViewHolder): View {
        return ChannelListItemBinding.bind(viewHolder.itemView).xxx
    }

    override fun onClick(
        v: View,
        position: Int,
        fastAdapter: FastAdapter<ChannelItem>,
        item: ChannelItem
    ) {
        
    }
})
```
