### ISSUE TITLE
how to display more different item at only one recyclerView

### ISSUE THREAD

**Issue by ChinaJson** [mikepenz/FastAdapter#997]
## About this issue

- how to display more different item at only one recyclerView

## Details
- I'm not know describe needs, it differend postion dispaly differend view layout

**Comment by mikepenz** [comment]
Please have a look at the sample app it shows many different behaviors: 

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/IconGridActivity.kt

**Comment by mikepenz** [comment]
There are more examples than that :)
